### ISSUE TITLE
Unhandled exception twisted.internet.error.TimeoutError User timeout caused connection failure

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1009]
When the following exception happens, it's not properly managed by GlobaLeaks:
"twisted.internet.error.TimeoutError User timeout caused connection failure
TimeoutError: User timeout caused connection failure."

This ticket is about handling properly the exception "TimeoutError" logging it to GlobaLeaks log file.

**Comment by hellais** [comment]
I this this issue can be closed since it does not provide enough information to debug it.
