### ISSUE TITLE
Simplify client-build

### ISSUE THREAD

**Issue by mmaker** [globaleaks/GlobaLeaks#1016]
Currently, the client needs to run `npm`, `bower`, and `grunt` in order to build the client. 
https://github.com/globaleaks/GlobaLeaks/blob/devel/backend/debian/rules#L12
Wouldn't it be possible to simplify this procedure, perhaps handling it all inside the `Gruntfile`?
##

**Comment by evilaliv3** [comment]
The process has been simplified and bower is not not anymore used.

The only requirement is to have npm, with it we setup a local grunt used then to build the client.
