### ISSUE TITLE
Client unittests may fail due to timeout

### ISSUE THREAD

**Issue by mmaker** [globaleaks/GlobaLeaks#1017]
It's not the first time I encounter this error while travis runs:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/41485971/log.txt
Can we just increase the timeout, or there's something seriously buggy behind this? 
##

**Comment by evilaliv3** [comment]
the bug happens various times if the request take too long so that miocha consider it an error.. i think 2 seconds is the timeout.

**Comment by evilaliv3** [comment]
the timeout has been raised since a lot to 15 seconds and this fixed the issue.
