### ISSUE TITLE
Permalink to recipient and/or context

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1018]
An interesting feature (as we are in a case where it would make things lot easier) would be to have a permalink to a specific recipient and/or context. So xxx.onion/#/receiver=John would go directly to leak to John, where xxx.onion/#/receiver=John&context=Paradise would leak to John in Paradise context.

What do you think? How complicate is to implement it?

**Comment by evilaliv3** [comment]
implementd by @hellais  and intregrated by me.
