### ISSUE TITLE
Receiver notifications section

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1021]
When managing multiple tips, ie. 30+, it is getting time wasting to access comments and new files attached. It would be interesting if from the receiver page there would be a small section for new notifications.
In the current model, you must go to mail inbox, decrypt email one by one and access the notifications urls one by one. I think it could be optimized.

**Comment by evilaliv3** [comment]
this has been now implemented by me and @vecna.

i'm going to release it by tonight, so @infosquatter when you want you can test it and provide use a feedback.

**Comment by vecna** [comment]
another point relevant here, is that @infosquatter is mentioning "when a receiver has 30+ tips". I guess we've to think how to paginate the tip list, because at the moment can contain infinite elements...

**Comment by NSkelsey** [comment]
This has been handled by *bolding* the tip element that has been updated, since the last access by the recipient.

**Comment by evilaliv3** [comment]
@NSkelsey what you are writing is a nice suggestion but is not really happening right now:
1) we have new tips marked bold;
2) we have the time of the update and the time of last read but we are not marking tips as a new (bold) as they get updated.

i'm going to do it immediatly as it is really a nice to have.

**Comment by NSkelsey** [comment]
@evilaliv3 maybe use a slightly different indicator? 

This way there is a distinction between new and updated tips. 

Using italics or a red asterisk "*" could work. I know you don't like the idea of a "new" pill. 

Is the word "updated" in the list of translated strings?

**Comment by evilaliv3** [comment]
you are right @NSkelsey but i think that we should eventually compress/remove all the columns creation_date/update_date/expiration date or we will have so many different indicators to communicate the same thing.

for now that those columns exists and take space, i'm for keeping it clean and simply marking in one way (bold) what requires attention.

no right know we do not have an "updated" string.

**Comment by evilaliv3** [comment]
In addition @NSkelsey, at the time @infosquatter we were not having the following things:
- the "last updated" column
- the possibility of sorting by creation_date/last_update

so that really simply marking the updated one with the bold for now could represent the missing refinement while we think of how better compress the information for the future.

**Comment by evilaliv3** [comment]
This was not estimated, but as we are experimenting with the burndown i will assign the time i took for implementing it.
