### ISSUE TITLE
Merge GlobaLeaks documentation

### ISSUE THREAD

**Issue by mmaker** [globaleaks/GlobaLeaks#1026]
With e2e50756ad6136cdc2b298cd2fc49bcbd232cc26 we have another place hosting documentation.
As far as I can tell, right now there is:
- github
- sphinx
- random google docs
- apiary

This issue is to report this, keep track of the various services hosting globaleaks documentation, and start thinking on ways to centralize the documentation, and validate it against the actual code.

**Comment by evilaliv3** [comment]
Closing, the documentation is now fully on readthedocs: https://docs.globaleaks.org/
