### ISSUE TITLE
Utility to Download, Update, Upload to a website Tor Browser Bundle in several languages

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1035]
This ticket is to introduce a functionality that has been required by Amnesty as a part of their deployment strategy, to enable distribution of Tor Browser Bundle from a private website.

The use case is:

Country where torproject.org is blocked
Distribution of access URL is done privately
End user is already known to local government to be an activist
End user is seasoned old, non-technology savvy person

This ticket is to implement a software, to be part of GlobaLeaks software suite but run independently, that will:

* Download the latests version of Tor Browser Bundle for a defined set of supported languages (Urdu, Arabic, English)

The OS to be supported are:
* Windows
* OSX

The software will run under a period background job (let's say once per day) and, if a new version of TBB is available, will replace the previous version.

The latest version must be checked with https://www.torproject.org/projects/torbrowser/RecommendedTBBVersions .

Download should be done from https://dist.torproject.org/torbrowser/4.0.1/ .

The software may be integrated within the GlobaLeaks software, available and configurable from within the GlobaLeaks interface itself.

**Comment by evilaliv3** [comment]
This feature has been implemented;

When GlobaLeaks his exposed by means of a Tor2web instance, it could benefit of the /gettor and /checktor APIs as documented in: 
- https://github.com/globaleaks/Tor2web/wiki/GetTor
- https://github.com/globaleaks/Tor2web/wiki/CheckTor

**Comment by evilaliv3** [comment]
Closing this ticket and opening some specific one for new improvements.
