### ISSUE TITLE
Improve Privacy Badge by letting "Copy to Clipboard" the .onion URL by one-click

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1040]
This ticket is to Improve Privacy Badge by letting "Copy to Clipboard" the .onion URL by one-click.

This will improve the usability of the process related to the download and use of Tor Browser in connecting to .onion site.

This should be done with Clipboard API, by detecting the capability of the most modern browsers: http://www.w3.org/TR/clipboard-apis/

**Comment by fpietrosanti** [comment]
We can use https://github.com/asafdav/ng-clip

**Comment by evilaliv3** [comment]
I've actually just tested this and it seems tha now the feature is well supported by all the current target browsers included the Tor browser.

**Comment by evilaliv3** [comment]
Implemented. The text is now clickable and shows a pop over message "copy to clipboard" to invite the user to click.
