### ISSUE TITLE
Unittests shall not be enumerated

### ISSUE THREAD

**Issue by mmaker** [globaleaks/GlobaLeaks#1045]
IF UNITTESTS ARE BEING CALLED UNIT-TESTS THERE MUST BE A REASON
TEST CASES MUST BE FUCKING INDIPENDENT FROM EACH OTHER

**Comment by evilaliv3** [comment]
@mmaker with last commit i finished to satisfy your desire! enjoy!

**Comment by mmaker** [comment]
♥
