### ISSUE TITLE
Remove notification/mail from the leaktop workflow

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1047]
This issue is not a specific task but a logic update of:

  * documentation regarding the LeakTop
  * procedure in disable all the notification in admin panel (add new receiver), extending the interface in admin panel
  * implementation of #1021 

At the moment a journalist with a leakTop has to:

  * Boot tails, unlock persistence 
  * download email (get notification if something is avail) decrypt email
    * copy/paste an URL from the decrypted notification -if any-, or
    * login in the node (they need to have a bookmark, otherwise they have to write an URL + /login )
  * in the receiver page works over the Tip

but **Notification** is intended to be something waking you up and bring you to open your leaktop. In this case, the step can be simplified with:

  * boot tails, unlock persistence
  * open a link (bookmark, link in the desktop) bringing to /login
  * works over the Tip

removing a PGP unlock/decrypt step and the configuration task of the mail.

**Comment by evilaliv3** [comment]
@vecna what to do with this ticket? is there any action like documenting it somewhere?

**Comment by vecna** [comment]
No, is part of the Initiative workflow, document the email adoption, or just skip it from the procedure.
