### ISSUE TITLE
Enable to login with a username without an email @ where all users are bound to a single domain

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1048]
This ticket is to enable users to login only with a username that does not contain any `@domain` when the system is configured to work with a strict default domain name.

This is a usability extensions where all users are part of the same organization, so they all have emails from the same orgs (es: afrileaks.org / aslbrescia.it) .

From the admin interface, it shall be possible to configure the default domain name, to enable login without a @domainname.tld .

The login form must present the login interface, with the @domainname.tld highlighted but unselectable, in a similar way to what Google Apps login form does when logging in under google apps domain login page.

**Comment by evilaliv3** [comment]
this is outdated having restyled the receiver loginby means of a simple dropdown selectbox.
