### ISSUE TITLE
Enhance data visualized in overview

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#105]
maybe useful, define two different level of details, or just think about the common usage that an Admin may perform on a node. 

At the moment, the reported data are show in th screenshot attached
![TipOverview](https://f.cloud.github.com/assets/89555/344909/4f4b0b6e-9e0f-11e2-9c2d-57297a0b06d9.png)
![Uploading UserOverview.png . . .]()
##

**Comment by vodkina** [comment]
again, what about this ticket? Is it progressing, or what?

**Comment by evilaliv3** [comment]
This tiket can be considered addressed by the status of the current tip list.

If specific interest is still present in implementing something let's open specific tickets about the missing features.
