### ISSUE TITLE
GlobaLeaks multi-tenancy support

### ISSUE THREAD

**Issue by exedre** [globaleaks/GlobaLeaks#1056]
This feature request is to add multi-tenancy support in GlobaLeaks instances. 

A simple ad effective approach is to delegate to the subdomain management the selection of tenant. Different domains should select different access interfaces and, within GlobaLeaks, different contexts / categories of contexts.

As a practical example: a GlobaLeaks instance is installed on hypotetical domain goofyleaks.org and respond to different subdomains: mickey.goofyleaks.org and donald.goofyleaks.org. 

To user connecting to one of these domains GlobaLeaks instance serves a different home page (or a basic default one if not  exists a specific page)  and can tip only to a specific context (mickey or donald).
##

**Comment by evilaliv3** [comment]
Recent ideas identify valuable the possibility to:
- make it possible to instantiate different instances on the same node through the web interface
- each instance should isolate the more possible the setup
- each instance should benefit of let'encrypt and automate HTTPS publishing
- each insteance should benefit of Tor and automate Tor HS publishing

**Comment by fpietrosanti** [comment]
To keep this feature as simple as possible, we should consider to have:
- routing to instances entirely based on "hostnames"
- Provide HTTPS/hostname routing via SNI extensions
- does not provide handling of multiple IP (only a single IP installation)
- remove all data stored on filesystem into the SQLite database (to avoid having differentiated data directories)

**Comment by evilaliv3** [comment]
I agree on all, i'm skeptic of arriving to have all the files on the databases.

For sure that wont be possible on sqlite that opens a single lock and keep the database locked for the whole time of the file operation.

**Comment by fpietrosanti** [comment]
As discussed, a possible design to prevent the lock (that occur only while writing) is to a) Use a dedicated database for file b) Keep the uploading to filesystem by having a batch that operate in a serial way (one after another one) by writing into the database those files residing into the filesystem. By using that mode there's no problem in having locks and it also fix the locking issues in having to store files on a remote database (because temporarly those will be always written to the filesystem)

**Comment by evilaliv3** [comment]
The general feature has been implemented and released in version 3.0.0

Refer to the changelog for additions currently implemented: https://github.com/globaleaks/GlobaLeaks/blob/master/CHANGELOG
