### ISSUE TITLE
Evaluate cleanup of globaleaks repositories

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1069]
Since we started using the unified GlobaLeaks repository it's now important to think how to avoid people to use old info widespreaded here and there that point to GLBackend and GLClient.

probably it's acceptable to simply apply a renaming of the two repos is the best fix? ? GLBackend-old GLClient-old

\cc @fpietrosanti @hellais @mmaker @vecna

**Comment by fpietrosanti** [comment]
Do we have reasons to keep the history of GLClient and GLBackend repository alive?

**Comment by evilaliv3** [comment]
i think maker migrated all well on the unified repository. maker what do you think?

**Comment by evilaliv3** [comment]
i think @mmaker migrated all well on the unified repository. maker what do you think?

**Comment by mmaker** [comment]
Idealistically we should get rid of GLClient.git and GLBackend.git, as everything we need lives now in GlobaLeaks.git, even the history of the two.
Though, if there are reasons to believe that the infrastructure is still using the two repositories, keeping them where they are would be harmless.

**Comment by vecna** [comment]
No @mmaker, all the deploy are using the .deb package only. get rid of the old repository can just increase clarity, for me is:

 - [x] do it

**Comment by evilaliv3** [comment]
agreed.
anyhouw something still need to be backed-up:
1) work by vecna on captcha
2) work on txtorcon (not really interesting as outdated and to be done properly with the isolated deamon)


the only problem we have (but i do not find it really an issue) is that we will loose tags for old versions (@mmaker ported tags over the new repo but this tags are unuseful as they track only the GLBackend, so i'm suggesting to remove them all as totally wrong and to keep only new tags

**Comment by vecna** [comment]
@evilaliv3 my works about captcha are locally stored, and still I've to switch on "research on vecna/GlobaLeaks and clean commit con globaleaks/GlobaLeaks", don't worry about that, will be recovered on the next days.

**Comment by evilaliv3** [comment]
as the repositories have not been deleted but simply been renamed as *-outdated this ticket can be considered addressed.
