### ISSUE TITLE
Language pre-selector 

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1070]
following the UX workflow designed by Joylab for Amnesty it would be useful to implement a Language preselector widget to be shown to users when they land on the platform.

The Language selector should be the first of a series of pluggable widgets configurable by the application in order to make the user perform various task (preconfiguration, information, etc.)

Currenty feature of the MVC designed are:
1) show a pleasant language selector based on square boxes if enabled languages are less or equal to 3
2) show a lest pleasant language selector based on a selectbox if enabled languages are more thant 3
3) this pluggable widget should be enabled as optional by the admin when configuring node settings.
##

**Comment by evilaliv3** [comment]
@fpietrosanti / @hellais: where do you think it's best to save this information?
1) cookies?
2) local storage?
both of this will re-change a little the threat model we have in mind where we wont to avoid explitittraces of the usage of globaleaks on browsers.
what do you think?

\cc @vecna @mmaker

**Comment by fpietrosanti** [comment]
What's about a URL in the parameter like #widget1=something ?

**Comment by evilaliv3** [comment]
nope @fpietrosanti you have not got the point.
it's not a problem to implement a link with an explicit language inside it that make possible to bypass the widget. the problem is to prived the requirement that the user is not informed of all the widgets everytime it opens the platform, but simply the first time he appen it.

do you remember the various widget designed for Amnestty? they asked that these all of these (language selector wisget, and other information widgets) are shown only the first time the user access the platform.

**Comment by fpietrosanti** [comment]
@evilaliv3 Yes, but why can't we use a URL in the parameter?
If we don't need globaleaks to survive across browsers sessions, why can't we can to save states additional parameter in the URL? 
Btw, given than those widget are just informative, also using cookies should not introduce any additional risks.

**Comment by evilaliv3** [comment]
the problem is in fact that we want it to survive across browsers sessions. this was the intent.
whenever you think to save it in the url i can save it inside javascript global variables as well.
the use of an url is simply to make possible bookmarking or embed pre-set urls somewheres (landing pages), but they wont solve the problem of surviving across sessions.

since now we have discarded cookies at all as we leave explicit traces on the browser why are you changing your vision on this? for the aim of this widget we have to save that the informative steps have been completed and save the language of the user.

@hellais what is your thinking?

**Comment by fpietrosanti** [comment]
@evilaliv3 non persistent cookies does not leave traces on the user browsers. The security-topic related to cookies was part of the overall discussion on "authentication"

**Comment by vecna** [comment]
I'm thinking some hackish way to left traces but keep them plausible deniable in a forensic analysis. This paper is helpful: https://sites.google.com/a/chromium.org/dev/Home/chromium-security/client-identification-mechanisms and I don't get if the feature can be more useful for a WB or for a Receiver.

if is a WB: will probably comeback very few time, no persistence need.
if is a Receiver: has just to make login with default language, and then preferences get loaded.

**Comment by evilaliv3** [comment]
i think that for the moment we can skip to implement any kind of persinsten introduction for this and we will have to discuss it with amnesty in the next meeting.

**Comment by evilaliv3** [comment]
in commit https://github.com/globaleaks/GlobaLeaks/commit/ab0ebad9989daf0ad7456d680eba00f6f06efa66 i've implemented the feature (currently hardcoded and not configurable).

![screenshot from 2015-01-14 21 28 01](https://cloud.githubusercontent.com/assets/217034/5746980/7dc37268-9c34-11e4-8dc5-92c43b191646.png)
![screenshot from 2015-01-14 21 28 05](https://cloud.githubusercontent.com/assets/217034/5746979/7dc25108-9c34-11e4-8377-73283ffc4687.png)
![screenshot from 2015-01-14 21 28 11](https://cloud.githubusercontent.com/assets/217034/5746981/7dc605c8-9c34-11e4-8ba6-84077ab2d312.png)

the only bug present is that the modal is not vertically aligned with respect to the page; i still miss to find a library to achieve this score on all the supported (all) browsers.

**Comment by vecna** [comment]
I've a list of flag (two letter country code to identify) can be useful to hook languages ?

**Comment by evilaliv3** [comment]
what do you mean? can you explain your idea?

**Comment by vecna** [comment]
having flag + language name is always better when the number of language overcome the 4-5 .... eyes want it. I've the flags, names as by two letter code.

**Comment by evilaliv3** [comment]
the ticket has been addressed and simply has an usability improval issue to could be addressed.

i'm leaving this ticket open and simply remove the milestone label as the milestone goal has been addressed.

**Comment by evilaliv3** [comment]
Closing as outdated
