### ISSUE TITLE
Make Hidden Receivers to be hidden also on Tip Page

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1078]
This ticket is to complete #735 by making the Receivers hidden also on the Tip page.

The Receivers should be visible only when some specific events happens, such as the receiver send a message or comment to the Whistleblower.

This behavior of visible or visible on-message-event shall be configurable.

**Comment by evilaliv3** [comment]
Closing as outdated as we do not implement hidden recipients.
