### ISSUE TITLE
Final Steps of submission contain mistaken visualization elements

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1080]
Final Steps of submission contain mistaken visualization elements.

In particular:
- The text containing the disclaimer is shrinked
- There is a red warning saying that the field cannot be empty (but is not possible to "fill anything" other than clicking i accept)

This ticket is to:
- Adjust the size of the text disclaimer being diplayed to the one of the text
- To change the message in warning to something like "Accept Terms and Conditions to proceed"

Screenshot below:
![screen shot 2015-01-06 at 12 35 17 pm](https://cloud.githubusercontent.com/assets/770363/5627979/ccbeee3c-95a0-11e4-89da-83376e20db31.png)

**Comment by evilaliv3** [comment]
in addition numbering the item whenver the page contains a single field is not useful.

**Comment by evilaliv3** [comment]
https://github.com/monospaced/angular-elastic this is the way!

**Comment by evilaliv3** [comment]
With the previous commit i've appliad the same stlye we had for old embedded Tos.

![Uploading Screenshot from 2015-01-06 17:48:29.png . . .]()
