### ISSUE TITLE
integrate angular-elastic in order to beautify text-areas

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1081]
In order to address properly https://github.com/globaleaks/GlobaLeaks/issues/1080 and to beautify forms it would be interesting to integrate the library https://github.com/monospaced/angular-elastic.

enjoy how fancy it is: https://monospaced.github.io/angular-elastic/!

happy epifania!

![image](https://cloud.githubusercontent.com/assets/217034/5628750/af44c182-95ab-11e4-9955-ad1c75d895b8.png)

**Comment by evilaliv3** [comment]
![screenshot from 2015-01-06 17 49 24](https://cloud.githubusercontent.com/assets/217034/5632246/8078e4c4-95cd-11e4-9d7a-11d13183ce5b.png)
![screenshot from 2015-01-06 17 49 37](https://cloud.githubusercontent.com/assets/217034/5632248/84c1d1a8-95cd-11e4-97e0-ecd6a3a7f3da.png)
![screenshot from 2015-01-06 17 49 50](https://cloud.githubusercontent.com/assets/217034/5632249/84df8996-95cd-11e4-9d71-1d658d5673e9.png)

**Comment by evilaliv3** [comment]
This feature was implemented and then removed cause of bad behaviour on internet explorer but it seems that now all users agreed on a css based way on fixing the issue so let's re-give it a try.

**Comment by vodkina** [comment]
Estimate, please :)
