### ISSUE TITLE
GlobaLeaks load 9 times /node before submission

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1082]
It has been tested that globaLeaks load 9 times /node before submission happens.

This test has been done on sourcesure platform by loading the TorHS root, then clicking blow the whistle.

This ticket is to fix this issue, by loading /node only once. 

It maybe related to the old #233 or fixed trough the performance improvement of #371 ?

Below the network trace showing the multiple loading of /node:
![screen shot 2015-01-07 at 8 56 27 am](https://cloud.githubusercontent.com/assets/770363/5642536/6c2e7c08-964b-11e4-9574-3690a951e9e3.png)

**Comment by evilaliv3** [comment]
this is related to various things in which the GLClient is still not well
factored.

I will deal on better studying in order to reduce this behaviours.

**Comment by evilaliv3** [comment]
solved in commit https://github.com/globaleaks/GlobaLeaks/commit/37b0846b7c8d267134b207a5172a3300e5fc33c5 while addressing https://github.com/globaleaks/GlobaLeaks/issues/1086
