### ISSUE TITLE
Revert bootstrap from 3.3.1 to 3.2.0 cause of a bug onto modal backdrops.

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1094]
I seems that angular-ui/bootstrap is not so much compatible with bootstrap 3.3.1 causing failures with the modal backdrops.

It would be needed to revert bootstrap from 3.3.1 to 3.2.0 to solve this issue.

**Comment by evilaliv3** [comment]
the issue has been verified and ticketized onto angular-ui/bootstrap repository: https://github.com/angular-ui/bootstrap/issues/3184

**Comment by fpietrosanti** [comment]
The stable is the better!

**Comment by evilaliv3** [comment]
the issue i was encountering has been fixed in bootstrap 3.3.4 
https://github.com/twbs/bootstrap/blob/f5beebe726aa8c1810015d8c62931f4559b49664/less/modals.less#L65

i've retested it and extensively since a few and i'm now switching to it cause bootstrap-rtl is really more mature at this version; the 3.3.2 of bootstrap-rtl has few fix that still need to be done and will be ready in a few: https://github.com/morteza/bootstrap-rtl/issues/66
