### ISSUE TITLE
deal with a couple of exceptions in /dev/shm GPG section

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1096]
A couple of adopters are sending exception like:
    
    OSError: [Errno 31] Too many links: \\'/dev/shm/globaleaks/gnupg/2NbJvOFJ\\'

Or the disk full in /dev/shm happen too.

Probably is important spot the condition and (disable the node ? write an alert to the admin ? need to be investigated also if this issue is limiting the node possibility to receive files)

**Comment by vecna** [comment]
one of the error is better detailed in #1095 still to figure out the fallback and reproduce the error

**Comment by vecna** [comment]
I'm catching the exception now, but probably is one of the error that has to trigger an "high level alarm mode" and disable submission, because they can't work if that happen. I guess has to be part of the log/alarm/message refactor. need to be kept in mind.

**Comment by evilaliv3** [comment]
I see, let's see this open for a few. i will evaluate a solution while integrating all the work you have done,

**Comment by evilaliv3** [comment]
all is integrated by me and the ticket can be closed.
