### ISSUE TITLE
Investigate issue on jquesy-fileuploader image preview

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1097]
While integrating @hellais code developed for amnesty i'm encountering issues with the images preview.

![screenshot from 2015-01-16 20 24 02](https://cloud.githubusercontent.com/assets/217034/5782725/dc58e54e-9dbd-11e4-9f9f-bb253ea5b0d5.png)

the bug seems to scatter only if i load an image and if it is done the system make not possible to upload futher files.
for this reasons i'm now integrating the code with the exception of not enabling file preview.

the strange thing is that the errors do not apply to the original branch by @hellais probably

**Comment by evilaliv3** [comment]
solved while finishing the integrating the code.

the bug was lieing into a race condition.

**Comment by evilaliv3** [comment]
anjoy the beauty of the new file uploader finally completed and configurable with fields to be filled (e.g., the filename and the description).

![screenshot from 2015-01-17 18 24 51](https://cloud.githubusercontent.com/assets/217034/5789716/59ba3b06-9e76-11e4-89d1-a80521efc509.png)

**Comment by fpietrosanti** [comment]
WOW WOW WOW
