### ISSUE TITLE
Numbers of Receipt are not properly internationalized for non-latin characters

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1099]
While looking at a Cyrillic (Ukraine) GlobaLeaks initiative, it has been noted that the numbers are in latin characters and not cyrillic ones (ie: http://en.wikipedia.org/wiki/Cyrillic_numerals):

![screen shot 2015-01-18 at 8 10 58 pm](https://cloud.githubusercontent.com/assets/770363/5793718/b8674e0e-9f4e-11e4-9f61-380132885c75.png)
![screen shot 2015-01-18 at 8 11 02 pm](https://cloud.githubusercontent.com/assets/770363/5793719/b8716272-9f4e-11e4-845b-19a0adeaff34.png)

This ticket is about adjusting the receipt numbers based cyrillic characters in the two visualization of the Receipt page.

**Comment by evilaliv3** [comment]
This can be tricky for the user as the system will then accept back always only arabic numbers.

Are you sure the adopter was notifying this? i think that the problem reported was related most to the missing translations of the strings: "Valid From", "Expires End", "Your Name", "Credit Card". This strings are now on transifex and the software makes use of them.

**Comment by fpietrosanti** [comment]
Better to ask to our friendly OTF/Transifex support people which is the right strategy, whenever numbers shall be internationalized too as a best practice for non-latin charset such as cyrillic, arabic, chinese, etc

**Comment by evilaliv3** [comment]
in the meantime i've updated a little the SVG to be properly internationalized.

![screenshot from 2015-01-19 10 09 45](https://cloud.githubusercontent.com/assets/217034/5798022/6114ac26-9fc3-11e4-8348-40155f1c147b.png)

**Comment by mapmeld** [comment]
although it would be good to accept Cyrillic, Arabic, and other internationalized numbers as input, I don't think it's such a good idea to output them, especially if we are using the credit card mockup

probably a separate issue, but credit cards use the [Luhn algorithm](http://en.wikipedia.org/wiki/Luhn_algorithm) where the last digit is a checksum for the other 15 digits. It would be simple for an informed person to check if your 16 digit number could ever be a credit card number.

**Comment by evilaliv3** [comment]
@fpietrosanti for what concern the text on the credit card what do you think should be the sentences to be translated?
currently i've put all:
- CREDIT CARD
- YOUR NAME
- VALID FROM
- EXPIRES END

probably is better to "VALID FROM" and "EXPIRES ON" in english as it generally happen on internationl credit cards? any hints?

**Comment by fpietrosanti** [comment]
Sounds fine, looking on google images for russian, japanese and arabic credti card, those field are usually in english

**Comment by evilaliv3** [comment]
ok so i'm going to remove the internationalization of this thing.

**Comment by evilaliv3** [comment]
done in commit: https://github.com/globaleaks/GlobaLeaks/commit/d5daeef9758138825d3ff66db45712e93ba6ba61
