### ISSUE TITLE
Analyze implementation of technical suggestions from AfriLeaks

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1102]
https://hackpad.com/afriLeaks-Technical-Suggestions-GLcrIiMCyJl

afriLeaks Technical Suggestions
This document is a collection of random ideas for how we can simplify the workflow for journalists who want to use the GlobaLeaks instance for afriLeaks. 
 TODO for myself: include onion address on afriLeaks home page and make sure that newsrooms make it available, too. 
Also, we need a nicer layout for the submission system. 

Streamline password management: a single password for TAILS (Persistence) and the GPG key - skip the password manager entirely.
Effort: +
Pay-off: ++
Allow email-only workflow: notification emails include any comments and attachments and responding to that email posts a comment on the tip. 
Effort: ? (+++)
Pay-off: +++
Make sure files are attached such that a properly configured email client will automatically decrypt them.
Effort: ? (++)
Pay-off: +++
Store the GPG passphrase to the Enigmail configuration on TAILS persistence such that GPG mail is decrypted automatically.
Effort: +
Pay-off: ++
Make sure all the keys have all other public keys available on them so the newsrooms can talk securely amongst each other.
Effort: 0
Pay-off: +
Include a (second) version of the attachments where metadata has been scrubbed using server-side MAT. Needs a disclaimer but makes it easier to do the right thing.
Effort: +++ (becomes impossible with client-side crypto!)
Pay-off: +
Install Mozilla Thunderbird and Engimail on the TAILS sticks (instead of Claws), it is more useable. Make sure it doesn't store drafts etc. (Where is Mailpile in terms of readiness?)
Effort: ++
Pay-off: +++
Set up a secure IM (eg. Pidgin OTR) on the TAILS system which is launched automatically and connects to the afriLeaks support team.
Effort: ++
Pay-off: +
For new newsrooms: Choose smaller and more convenient laptop hardware, e.g. ASUS Eee PCs.
Effort: 0
Pay-off: +
GlobaLeaks dashboard upon login should include more information about each of the shown activities, e.g. comment text and a title for the tip (also: replace the numeric identifier with a catchy NSA codeword).
Effort: ++ (?)
Pay-off: +
Explain why newsrooms need to use TOR when accessing the platform as receivers.
Effort: 0
Pay-off: 0 (access a bit faster)

**Comment by evilaliv3** [comment]
Closing this ticket as outdated.
