### ISSUE TITLE
Exception from server "TypeError Inappropriate argument type."

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1103]
Version: 2.60.49
TypeError Inappropriate argument type.
Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/cyclone/web.py", line 1073, in _deferred_handler
    result = function(_args, *_kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/authentication.py", line 187, in call_handler
    return method_handler(cls, _args, *_kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/authentication.py", line 133, in call_handler
    return method_handler(cls, _args, *_kwargs)

  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1228, in unwindGenerator
    gen = f(_args, *_kwargs)

TypeError: get() takes exactly 1 argument (2 given)
##

**Comment by evilaliv3** [comment]
@fiorix can i please ask to verify the two single lines where we define the handler?

i do not understand why this error should happen as the handler is mapped as following so no second arguments should never be passed:

    (r'/authentication', authentication.AuthenticationHandler),

https://github.com/globaleaks/GlobaLeaks/blob/master/backend/globaleaks/handlers/authentication.py#L276

**Comment by fiorix** [comment]
Not sure. I was trying to troubleshoot but can't get it to run from git in a container due to this:

    glbackend database file not found in /GlobaLeaks/backend/workingdir/db

**Comment by evilaliv3** [comment]
ah thanks @fiorix, i was simply interested in a hint

on what conditions an additional argument can be passed to the handler regarldess of the regexp?
given the regexp (r'/authentication', authentication.AuthenticationHandler) this appar really unexpected.

**Comment by fiorix** [comment]
Like I said not sure.. it’s been a couple years since I last wrote any serious Python but my bet is something messed up with the decorator. I’ve seen similar cases before, many times, but can’t really remember and would have to run it to troubleshoot.

**Comment by vecna** [comment]
I don't see this bug in the latest versions, can we consider it solved ?

**Comment by evilaliv3** [comment]
no change have been applied in relation to this.
and it may be also connected to the fact that various notifications where not working since mitotz changed something to the postfix of the default mail credentials. let's keep whit open for a few.

**Comment by evilaliv3** [comment]
Closing as outdated and completed long time ago.
