### ISSUE TITLE
Objects ordering (Context, Receivers, etc) is unique per object, not per language.

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1106]
Currently every ordering variable implemented in the GLBackend is unique per object and not applied differntly per language.

This means that when the user order for example the Context having selected the English language, the change will affect all the languages that obviously won't be ordered as in english.

**Comment by vecna** [comment]
that is a sort of totally architectural bug that we can solve only converting all the list in dict, using the INT as keys ?

**Comment by evilaliv3** [comment]
what do you mean?

from the solution you propose it seems that what i written it was not clear.
let me clarify with an example:
Let me say we have the following Contexts "One, Two, Three" and that i order them alphabetically.
I will get the order: "One, Three, Two"
Let us than switch to italian: we will se "Uno, Tre, Due" but in italian the alphabetical order is "Due, Tre, Uno".

by the way writing the above i found the solution: We do not need a "Reorder alphabetically as i implemented", but a "Show receivers in alphabetical order" and a "Show Contexts in alphabetical order". this can be simply two booleans at node level. 

If agreed @vecna / @fpietrosanti i will push this variables in next db update so to have support for this fix.

**Comment by vecna** [comment]
Ok I see your point, but you are advantaging the alphabetical order because is "neutral", some node, want keep as first the things they want give priority. 

That's why I was guessing, a not-language-dependent ordering is required in a list, and the alphabetical reordering is just a client side feature, for the day the admin press on the button.

**Comment by evilaliv3** [comment]
Both exists since ever vecna but the alphabetical reordering I simply
implemented without any db support has this internationalisation drawback
since ever.

I've described above how I'll solve it that will continue to be optional
and not enforced like now

**Comment by evilaliv3** [comment]
This issue is now solved.
Now the implementation of this functionality is totally different from before:
1) the node offers a boolean "Show contexts in alphabetical order"
2) the context offers a boolean "Show receivers in alphabetical order"

this way is then the application that can show the elements in alphabetical order or human sorted order depenings on 1) and 2)
