### ISSUE TITLE
official CSS and custom CSS separate loading causes flickering

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1110]
Currently the official globaleaks css and the one customized by the user are delivered in two different requests.

this causes the application to load them indipendently and this cause a flickering on adopter nodes that first view the default globaleaks style and then it changes. 

the result is even wors when the adopter has applied some "display:none" to specific class of the application. on this condition the user will see some text appearing and then disappearing while the application is loading.

this ticket deals with the discussion about the fix and the possible solutions.

\cc @hellais @fpietrosanti

**Comment by evilaliv3** [comment]
the more easy solution would be to make the application serve both the files one appended to the other while the application is loading.

this would be straightforward as due to the format of css files one can be appended to the other also if they are minificated or antani.

this would also solve a little problems related to e2e delays.

**Comment by fpietrosanti** [comment]
We have another ticket (i am from mobile just now, don't remember which one) whose fixing require to build a custom index.html from the glbackend. Can't we use this as a single approach to deliber only one big single file with everything required from globaleaks as a way to fix all e2e problems? It's maybe a more "hardcore" solution but it could represent "The solution" to reach the "single page/request" delivery, an approach that could make if possible also to deliver a customized GLC "offline" or from a server that's different from The globaleaks one?

**Comment by evilaliv3** [comment]
yes i think this is the way

**Comment by evilaliv3** [comment]
with this commit i've solved the issue with a small refactor by making the GLBackend provide both the official and custom css in the same request.

i agreee that the solution suggested by @fpietrosanti is the best but is 1) tracked by a different ticket 2) not a short term goal addressable with minor refactoring.

with this commit i've also patched the BaseStaticFileHandler making it provide files in streaming and not as a whole. this way N requests to a file (e.g. 20 request script.js) wont result in a memory occupancy equal to the lenght of the file (20 X 1MB) but simply in NxChunkSize (e.g. 20x8192 bytes). the chunk size of the application now it's also configurable by GLSetting.file_chunk_size

**Comment by fpietrosanti** [comment]
Everytime we reduce the memory use of GLBackend a new cat become a meme in the internet.

There will be a time where we'll be able to fit GlobaLeaks on PLC Microcontroller!
