### ISSUE TITLE
Changelog is broken (404 not found)

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1111]
When clicking the Changelog from the main wiki page it gives out 404 error not found:
https://raw.githubusercontent.com/wiki/globaleaks/GlobaLeaks/Changelog

This ticket is to bring back the changelog

**Comment by evilaliv3** [comment]
the correct link is: https://raw.githubusercontent.com/globaleaks/GlobaLeaks/master/CHANGELOG

**Comment by evilaliv3** [comment]
fixed.
