### ISSUE TITLE
Evaluate the replacement of jquery-file-uploader with nervgh/angular-file-upload

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1113]
https://github.com/nervgh/angular-file-upload

I've found this new library that seems more compact (it doesn't require additional jquery code like jquery-file-uploader) and it's build simply with angularjs.

For sure i'm not suggesting to migrate know as the library is not so much used but we should take care of viewing how things will proceed.

**Comment by evilaliv3** [comment]
the cool thing about this library is that it have compatibility in mind and seems to be compatible also with non htm5 clients.

it performs compatibility checks  by means of the [es5-shim library](https://github.com/es-shims/es5-shim)

@hellais when you find the time can you take a look and write down your thougths on this?

**Comment by fpietrosanti** [comment]
It does not support neither chunked file uploading neither resume

**Comment by hellais** [comment]
Is this still relevant?

I think we have agreed that flow.js is the solution.

**Comment by evilaliv3** [comment]
you are right @hellais
