### ISSUE TITLE
Add possibility for customize the title of the main public pages

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1116]
Currently one can configure simply the node title of the application (that impact on the homepage name) but not the titles of the other pages, e.g. the submission page that has a default title "Blow the whistle"

This ticket deals with the changes needed in order to add possibility for customize the title of the main public pages.

This has been requested by an adopter and could be interesting for all the various initiatives as well.
I'm thinking for example to amnesty that will have specialized titles for the submission page and for the tip page.

**Comment by evilaliv3** [comment]
Relevant pages related to this ticket:
1) the homepage (currently configurable with the node name, we can evaluate to make this a differnet setting
2) the submission page
3) the tip page on receiver side
4) the tip page on whistleblower side

@fpietrosanti  do you think other pages would need such a configuration possibility?

**Comment by fpietrosanti** [comment]
@evilaliv3 mmmmmm, i'm wondering if, when making it configurable (and placing some useful text by default), it's not better to make it configurable, and by default customized, on all pages?

However regarding the other pages i think that also the Receiver Tip List and the whistleblower Receipt page would be a useful stuff to be customized.

Btw i would suggest to call those customization "Header" rather than "Title", because in theory the Title is the one displayed in the head of the browser bar.

**Comment by evilaliv3** [comment]
implemented currently simply for Homepage and Submission Page that are the one requested by adopters.

**Comment by evilaliv3** [comment]
Damn you are right @fpietrosanti, we also need to add the possibility to customize the title of the receipt page.
Currently it is set as:
title: Submission successfully completed!
subtitle: Write down your keycode

we should change it to a single title as for all customizable pages and make possible to add a multi line text.

**Comment by evilaliv3** [comment]
this has been requested by lemonde for a particular case: currently they do not want duplicated strings and due to the addition of the "Your submission was successful." string in the page to amnesty, the top page title "Submission successfully completed!" has become duplicated. by adding the possibility to customize it we will solve also this issu so that lemonde could remove it.

Currently i've now fixed the problem for them by hardcoding an empty line.

**Comment by evilaliv3** [comment]
implemented in : https://github.com/globaleaks/GlobaLeaks/commit/eb52be50c087013f2360e6aa483c8664f5d83351
