### ISSUE TITLE
Add support and configuration for the node landing page

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1118]
It has been requested by Amnesty to have the possibility to make the user land directly on the submission interface.

In order to achieve such a score it would be nice to introduce a "Langing Page" configuration in order to accept the following values:
 - homepage
 - submissionpage

**Comment by fpietrosanti** [comment]
I would suggest to make the settings to be called "start page" and to be:
- default
- directly to submission
- custom landing page (upload custom file)

Would it make sense?

**Comment by evilaliv3** [comment]
i prefer to keep independent this setting: homepage/submissionpage from the customization of the homepage (at least for the backend implementation)

in the future we will eventually implement better UI over this simple API.

**Comment by fpietrosanti** [comment]
Ok but from the admin user point of view it's alert part of changing what is beeing displayed on the "start page"

**Comment by evilaliv3** [comment]
implemented.
