### ISSUE TITLE
scrypt dependency error while using "python setup.py develop"

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1120]
i've found that using "python setup.py develop" i encounter the same issue described here: https://leap.se/code/issues/4948

this causes to not setup correctly scrypt that will result in a broken development environment

**Comment by evilaliv3** [comment]
the bug seems to be sovable by using:

      python setup.py develop --always-unzip

@mmaker do you agree in the solution?

**Comment by evilaliv3** [comment]
in the meantime i've updated https://github.com/globaleaks/GlobaLeaks/wiki/Setting-up-development-environment.

i had to add various corrections cause on a fresh debian jessie the workflow was buggy, but now all should be straightforward. varius dependencies where missing:

**Comment by vecna** [comment]
Can we close this issue ? is still a bug ? @mmaker @evilaliv3

**Comment by evilaliv3** [comment]
yep, i was waiting for the validation of my solution by @mmaker.

let's leave this assigned to him.

**Comment by evilaliv3** [comment]
the problem seems solved with no issues since a few so that the ticket can be closed.
