### ISSUE TITLE
PGP Expiration check/notice fails on keys with no expiration set

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1121]
PGP Expiration check/notice is maybe buggy .

I received the following notification that report as a date of expiration 1970.

===============================
Dear Fabio Pietrosanti,

This is an e-mail to inform you that your PGP key is expiring or already expired.

   0x583A342 (01/01/1970)

Without a valid PGP key, the system will not be able to send you encrypted notifications.

You should extend its validity and update the key present on the GlobaLeaks nodes you are subscribed to or upload a new key.

Kind regards,
GlobaLeaks Demo Instance

**Comment by evilaliv3** [comment]
yep your was the only one PGP key expired and is correct that the mail has been sent but i'm now investigating why in the mail i've written datetime_null() that is when i do not have info on the expiration date.

**Comment by evilaliv3** [comment]
ok i've found what the bug is.
your key has not an expiration date set and this make the key to be recognized as expired.
i'm going to fix the issue.

**Comment by evilaliv3** [comment]
bam! fixed!
