### ISSUE TITLE
GlobaLeaks does configure the Wrong Tor2web URL

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1123]
GlobaLeaks does configure the Wrong Tor2web URL by adding ".tor2web.org" to the existing .onion.

Resulting Tor2web URL link become:
https://c4b3jfyayzdfcfkae.onion.tor2web.org

This ticket is to fix this bug by making the Tor2web url:
https://c4b3jfyayzdfcfkae.tor2web.org

**Comment by evilaliv3** [comment]
fixed in commit: https://github.com/globaleaks/GlobaLeaks/commit/3c385a91f130e359db4c414dc2078157ab621f64
