### ISSUE TITLE
It's not possible to configure Homepage Title with multiple lines

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1125]
It's not possible to configure Homepage Title with multiple lines.

It has been removed the possibility to add a sub-title, but this has been made substituted by enabling multiple-lines Title.

The input form in the admin interface does not enable to do that:

This ticket is to make this text box editable with multiple-lines
![screen shot 2015-02-05 at 10 17 14 am](https://cloud.githubusercontent.com/assets/770363/6057651/619d99b8-ad20-11e4-9c7a-c26ee564373c.png)

**Comment by evilaliv3** [comment]
i agree with this need, but this can be classified as enhancement or an enhancement and no as bug.

**Comment by evilaliv3** [comment]
bam!
