### ISSUE TITLE
If a receiver doesn't have a PGP key configured, his description is not shown

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1126]
If a receiver doesn't have a PGP key configured, his description is not shown, but instead is being replaced by the text "the receiver has not configured the encryption key" .
![screen shot 2015-02-05 at 10 16 36 am](https://cloud.githubusercontent.com/assets/770363/6057660/7a1d2d50-ad20-11e4-874d-e41fecf8894c.png)

This sentence is already provided on-mouse-over on the warning sign.

This ticket is to fix the problem by showing the description.

**Comment by evilaliv3** [comment]
this was my choice not a bug, but i agree with the change and i've applied it with commit: https://github.com/globaleaks/GlobaLeaks/commit/2c4066a9af175cf0d5868ed4505282ea006698bf
