### ISSUE TITLE
Make all globaleaks requests/handler to happen under a sub-path like /globaleaks/

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1130]
This ticket is to refactor the GLC and GLB to make all globaleaks requests/handler to happen under a sub-path like /globaleaks/ .

This is needed in order to strongly simplify the setup of #1128 reverse proxying feature by making them much more reliable

/cc @smari @evilaliv3

**Comment by fpietrosanti** [comment]
When this will be integrated the guide at https://github.com/globaleaks/GlobaLeaks/wiki/Integration-Guide need to simplified as per #1128

**Comment by evilaliv3** [comment]
as discussed it's not a requirement for the need for which it was thought.

given that this issue can be closed for the moment as not useful.
