### ISSUE TITLE
When a custom logo is loaded, the error messages are not fully visibile

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1131]
While testing OCCRPLeaks, we spotted a bug so that when a custom logo is loaded, the error messages are not fully visibile because the custom logo is in "foreground" within respect to the message.

This ticket is to make the GlobaLeaks error messages to be always in foreground within the respect to any other CSS elements.

**Comment by evilaliv3** [comment]
this should be fixed by https://github.com/globaleaks/GlobaLeaks/commit/3680be0199e6f16e5908468cfa7f9e683a7787a7

**Comment by evilaliv3** [comment]
i'm going to apply it to the development platform of OCCRP and see if the bug is solved.

**Comment by fpietrosanti** [comment]
tested, it's fixed
