### ISSUE TITLE
Enable embedding GlobaLeaks into other sites with iframe

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1134]
This ticket is to enable embedding GlobaLeaks into other sites with iframe.

This is required by the OCCRPLeaks and China Digital Times projects.

**Comment by fpietrosanti** [comment]
It shall be checked which is the best way to do it in a way that achieve maximum configurability and browser support.

**Comment by fpietrosanti** [comment]
We shall integrate #707 client-side checking in order to redirect to .onion when on Tor only if the resource is not embedded into an iframe

**Comment by evilaliv3** [comment]
this has been completely implemented.

the iframe embedding check that prevents redirect has been added in: https://github.com/globaleaks/GlobaLeaks/commit/8c6e811ea898b526196cb19e86a00f37f6917352
