### ISSUE TITLE
Provide an embeddable Receipt Login form for Whistleblower

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1136]
This ticket is to provide an embeddable Receipt Login form for Whistleblower.

The request come from OCCRPLeaks project where the adopter's web designer is creating multiple "submission page" with very custom design and styling.

The feature for integration shall be documented in the Integration Guide https://github.com/globaleaks/GlobaLeaks/wiki/Integration-Guide

**Comment by evilaliv3** [comment]
bam!
