### ISSUE TITLE
Check for https site when globaleaks is being embedded

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1140]
We shall integrate a mandatory check that, when globaleaks is being "embedded" from an https enabled site.

In case of non-ssl connection from the origin site a security error should be provided.

It shall also be possible to enforce access to GlobaLeaks via Tor2web only coming trough a white-list of specific base URLs (the ones that are meant for inclusion on the internet), such as for example https://occrp.org/occrpleaks/ is ok but https://occrp.org/leaks is not ok.

GlobaLeaks should check the HTTP referrer from that list, to verify if it's authorized/enabled or not.

**Comment by fpietrosanti** [comment]
That's related to #1134

**Comment by evilaliv3** [comment]
Closing as GlobaLeaks does not currently feature any embeddin capability.
