### ISSUE TITLE
Facilitate copying to clipboard the Receipt

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1143]
This ticket is to facilitate copying to clipboard the Receipt.

This could be approached with two way:
- When a user click on the Receipt, all the receipt numbers get selected (ready for copy/paste)
- When a user click on the Receipt, it automatically add to the Clipboard and provide the user an informative Tip that he can paste it somewhere else

The later can be done with ng-clip directive https://github.com/asafdav/ng-clip or https://github.com/lisposter/angular-zeroclipboard that rely on zeroclipboard 

This ticket is somehow related to #1040

**Comment by fpietrosanti** [comment]
By the way the html5 clipboard-api sounds not be working properly YET

**Comment by evilaliv3** [comment]
Implemented. The receipt is now shown with the layout of a button and it shows a tool tip "copy to clipboard" inviting the user to click it.
