### ISSUE TITLE
Translate GlobaLeaks to OCCRPLeaks related Languages

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1144]
This ticket is to keep track of the translation of the languages required for OCCRPLeaks.

There are two main languages to be implemented at first shot:
- [ ] Russian
- [ ] Azeri

Then we will need also to have translations for:
- [ ] Bosnian
- [ ] Hungarian
- [ ] Serbian
- [ ] Armenian
- [ ] Bulgarian
- [ ] Ukrainian
- [ ] Romanian
- [ ] Uzbek
- [ ] Spain
- [ ] Portuguese
- [ ] Albanian
- [ ] Georgian
##

**Comment by evilaliv3** [comment]
OCCRP has been enabled to autonomously translate for the needed languages.

Closing the ticket as we are not more in charge of the direct activity.
