### ISSUE TITLE
When ?lang parameter is used in the /#/submission the right-to-left layout is loaded

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1145]
When testing integration of GlobaLeaks we encountered a sub so that when ?lang parameter is used in the /#/submission the right-to-left layout is loaded .

This ticket is to fix the bug so that, when the language parameter is passed, only if the language does require RTL it will be fixed.

**Comment by evilaliv3** [comment]
http://digishare360.com/blog/wp-content/uploads/2013/10/Blog-9-Image-1.jpg

**Comment by evilaliv3** [comment]
![blog-9-image-1](https://cloud.githubusercontent.com/assets/217034/6092369/0e9b3014-aedc-11e4-80e5-611a730593a2.jpg)
