### ISSUE TITLE
Uploading files on Tor Browser Bundles gives Canvas Security Warning

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1147]
Uploading files on Tor Browser Bundles gives Canvas Security Warning:
![screen shot 2015-02-07 at 3 02 30 pm](https://cloud.githubusercontent.com/assets/770363/6092385/a26e38c2-aedc-11e4-8489-9a2d3083c8e3.png)

This ticket is to detect this condition and prevent from happening.

**Comment by fpietrosanti** [comment]
@evilaliv3 is this still valid with flow.js?

**Comment by evilaliv3** [comment]
can you also give a trial? i think to have seen i once.

**Comment by fpietrosanti** [comment]
No problem on demo.globaleaks.org with PNG, JPEG and PDF uploading with latests Tor Browser. Closing it
