### ISSUE TITLE
When the content is Right to Left in the Receipt page, the four blocks of the submission key code are inverted on the sample credit card

### ISSUE THREAD

**Issue by g1ll0** [globaleaks/GlobaLeaks#1148]
When the text is written in RTL, the four blocks of numbers of the key code that appear in the fake credit card, are inverted comparing the real key code assigned by the system. See screenshot.
![screen shot 2015-02-07 at 15 10 54](https://cloud.githubusercontent.com/assets/6312072/6092459/19d9c482-aee0-11e4-80ac-cde94fbd62d4.png)

**Comment by evilaliv3** [comment]
implemented!

now given an LTR receipt of 5293 5144 3349 3116:
- the mastercard image will always contain the LTR string: 5293 5144 3349 3116 as international credit cards are always LTR;

- the printed receipt will be shown 5293 5144 3349 3116 on LTR languages and  6113 9433 4415 3925 on RTL languages.

**Comment by evilaliv3** [comment]
i've talked with various RTL peopple and they agree that numbers are always readed in LTR also by RTL speakers so that this ticket should not be reopended.

i will take care of it. it's not simply needed to revert the ticket cause also in the initial implementation things where working wrong.

**Comment by evilaliv3** [comment]
fixed!
