### ISSUE TITLE
OpenPGP.js should be added as library to the one available to GLClient

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1152]
This involve creating a PGP controller in order to export the main functionalities of OpenPGP to angular views.

**Comment by evilaliv3** [comment]
In order to do proper integration we should wait for ticket https://github.com/openpgpjs/openpgpjs/issues/283 to be addressed as currently OpenPGP.js is not providing the library nor bundled nor minified.

**Comment by fpietrosanti** [comment]
Is it useful this AngularJS / OpenPGP.js stuff? https://github.com/omeid/angular-openpgp

**Comment by evilaliv3** [comment]
i do not think so, that inclusion is simply a code ripping of the original openpgp that do not add nothing useful.

**Comment by evilaliv3** [comment]
integrated and we are already benefit of it by simly using the internal sha that it exports to implement the proof of work!

**Comment by omeid** [comment]
@evilaliv3 The project linked does not rip of any code, you can clearly see tha that OpenGPG is a dependency.
It simply declares OpenGPG as an angular module to be available for DI, it may not be much but at the time it helped me have a meaingful and clear way of depending on OpenGPG in my angular applications.

**Comment by evilaliv3** [comment]
Thanks for the clarification @omeid
