### ISSUE TITLE
re-integrate testing of installation script and globaleaks startup testing in travis-ci

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1154]
This ticket is to re-integrate testing of installation scrip and globaleaks startup testing in travis-ci, making testing of the overall build -> install -> test that it started up process.

Currently when we have bugs in the installation script, we cannot detect it.

**Comment by mmaker** [comment]
Af far as I remember, we decided that the whole build process shall not be inside travis.
We want to test the build on multiple patforms, using (possibily) platforms different from ubuntu precise for building, which doesn't event satify all dependencies. 

If we really want to test builds, we need a new machine, possibily with jenkins or buildbot, to run on multiple linux distributions; though travis, with ubuntu precise, shall only perform unittests.

**Comment by fpietrosanti** [comment]
I agree that a full testing would require building for multiple platform, btw the only cheap/quick way to be sure that install script works and GlobaLeaks start is to use travis, unless you feel there's a very quick/fast setup of CI for multiple platform

**Comment by evilaliv3** [comment]
i agree @mmaker that we should do that.
but in the meantime what fabio was asking is simply to restore the minimal two lines in order to spot bugs:
these are:
  curl ... | install
  wget ... | grep GlobaLeaks
and will work like a charm like in past in order to do a basic test

**Comment by evilaliv3** [comment]
by the way maker if you are restarting working maybe we want to align ourselves?

**Comment by evilaliv3** [comment]
i've simply readded the test of the install script testing the released package using the latest install script.

i agree with @mmaker that building the package on travis and retesting now should be avoided. in addition currently the release scripts only work on debian so let's postpone this when in the future @mmaker will eventually start digging into jetkins.

**Comment by fpietrosanti** [comment]
While deploying jenkins is fine to test multiple deployment targets is fine as "the right way to test deployments on real-life systems", it would require a dedicated phisycal machine and some maintenance, so costs between 500-700eur/year . 

We should consider options:
a)  test various cloud solution (see which is costs) https://stackoverflow.com/questions/10012397/are-there-any-reputable-hosted-cloud-based-jenkins-services-available

b) buy a server and deploy our stuff

c) ask OTF to be able to deploy our CI on the OTF-cloud

d) Keep using travis-ci but install/chroot/deploy a base-os that we want to test

**Comment by evilaliv3** [comment]
yep let's see what OTF will answer to this need.

i had to rever my commit cause there are some strange permissions on the travis machine that make the installation script fail cause of them so we should think a different solution from this one.

**Comment by fpietrosanti** [comment]
OTF can provide us Ubuntu 14.04 and Debian 7 machines.
Google gave us those Google Cloud voucher from OTF.

Jenkins, trough JCloud API (in labs) support deployment in Google Compute Units: https://wiki.jenkins-ci.org/display/JENKINS/JClouds+Plugin

Maybe we can have a Jenkins running on OTF Cloud + on-demand-instances fired on Google Compute Unit, that's quite architecture/integration stuff

**Comment by evilaliv3** [comment]
Now that Travis-CI is supporting Ubuntu Trusty i've restored the complete testing workflow including the packaging + the install + the verification with a Curl that GlobaLeaks is running
