### ISSUE TITLE
Improve the notification templates in order to add the tip date

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1155]
It has been requested by Transparency-TI to improve the notification templates in order to add the tip sequence number  and the tip date to betterly identify and organize tip notifications during work activities.
##

**Comment by vecna** [comment]
technicalities: where we can keep the latest number used ? in the node table ?

**Comment by fpietrosanti** [comment]
Their use-case is only to have the same "protocol" the use internally that's made of $date-$progressive number in place of a single number.

Their format for the first new tip of 14 Feb 2014 would be: 14022014-01 while the second would be 14022014-02 .

Today the subject line contain Subject: [Notification 137] while they wish to have Subject: [Notification 14022014-01] .

**Comment by evilaliv3** [comment]
Mmm the idea with naif was to add a sequence number but he adopera request
was in fact simply add the the date (tracked by this ticket and the label
tracked by #1156.

I suggest for the moment to not add the tracking of the number as the
transparency initial idea was simply to have the possibility to manually
add protocol number in relate to othe number  assignment. I will better
specify the ticket when at home

**Comment by evilaliv3** [comment]
i've reduced the topic of this isue simply to tip dates and opened the discussion https://github.com/globaleaks/GlobaLeaks/issues/1158 for what concerns tip sequence numbers.

**Comment by evilaliv3** [comment]
Tip mail titles and mail templates allow to use ```%TipNum%``` and ```%TipLabel%``` for printing the tip number and the label.

Other tickets deals with the documentation of mail templating.
