### ISSUE TITLE
Handle globaleaks installation on system with apparmor disabled

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1162]
GlobaLeaks is now strictly enforcing apparmor profile and this cause problem during installation because Debian does not enable it by default (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=702030).

This ticket is to improve the installation script in a way that facilitate user life during the installation process to properly enable apparmor by:
a) Detecting that the kernel support it
b) Detecting that user-space tools are properly installed
c) If "a" and "b" conditions are properly matched, with user confirmation/permission, modify the grub configuration to enable it and reboot following the steps described at https://wiki.debian.org/AppArmor/HowToUse
##

**Comment by fpietrosanti** [comment]
That's related to #1177

**Comment by evilaliv3** [comment]
Depreacted since: https://github.com/globaleaks/GlobaLeaks/issues/1177
