### ISSUE TITLE
Disable Debian from the GlobaLeaks target: Ubuntu only

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1163]
This ticket is to remove the official debian support from GlobaLeaks, coming back to the original Ubuntu only.

The main reason is that Ubuntu have apparmor enabled by default https://wiki.ubuntu.com/AppArmor while Debian have it disabled by default https://wiki.debian.org/AppArmor/HowToUse .

GlobaLeaks, since 1 week, require AppArmor to start (before there was a bug that allowed globaleaks to work also without apparmor).

This means that GlobaLeaks, in order to be installed on Debian, require to modify the boot loader and to reboot the system. This action is not always possible on VPSs.

This situation over-complicate the deployment of GlobaLeaks on Debian.

Given there are no clear advantage in supporting Debian directly and that, due to the strict apparmor support we cannot go into official debian.org repository, this ticket is to remove Debian support and go back to only Ubuntu 12.04 and ubuntu 14.04

**Comment by fpietrosanti** [comment]
To do that we shall:
- remove debian target from packaging scripts 
- remove debian support from installation script
- remove support from technical requirements https://github.com/globaleaks/GlobaLeaks/wiki/Technical-requirements
- remove debian mention from https://deb.globaleaks.org

**Comment by fpietrosanti** [comment]
Only whenever the ticket https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=702030 will get resolved with Debian supporting by default apparmor we will be able to restore debian support

**Comment by evilaliv3** [comment]
i can agree with the idea but some things written here are a little messy:
To do that we shall:
- remove debian target from packaging scripts: no debian target exist in current packaging scripts, it simply exist a git branch.
- remove debian support from installation script; this can be done easily;
- remove support from technical requirements https://github.com/globaleaks/GlobaLeaks/wiki/Technical-requirements; this can be done without problems
- remove debian mention from https://deb.globaleaks.org; this can be done easily

**Comment by evilaliv3** [comment]
ok i agree that for deployment reasons we shuuld for for the moment follow this direction and continue to work also on debian only for research/testning reasons.

let's stop saying that we support also debian and remove the packaging for debian from the repository.

@fpietrosanti what about all the adopters that already are using debian?

\cc @mmaker

**Comment by evilaliv3** [comment]
my point of view for the moment is that we can't now stop providing support to current debian adopters and the package for ubuntu we are creating is not compatible on debian machines.

so what i'm going to do for the moment is to not sponsorize debian package existance.
this involve the following two actions:
- do not show it on deb.globaleaks.org
- do not show it on the wiki

**Comment by evilaliv3** [comment]
both actions described above have been applied. i think it's enough for now.
