### ISSUE TITLE
It should be possible to customize the text near the context selection

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1164]
Currently the text near the context selection is enforced by code to "I want to report on:".

The amnesty use case demonstated the need for adopters to customize it.
E.g. amnesty is now using "I want this information to go to:"

It would be important to add the possibility to customize this by the Content configuration of globaleaks, by means of a "Context selector text" set by default to "I want to report on" reusing current translations.

**Comment by evilaliv3** [comment]
Currently for amnesty reasons this change is hardcoded into amnesty branch.

**Comment by vecna** [comment]
Is not easier change the .po files, instead of create new db column ?

we've to realize that no node at the moment use more than 4 context. is far easier get rid of the "scrolldown" interface and let the user select with a click ? in this way, we can let, for every context, customize the introduction text (instead of a node-level string)

**Comment by evilaliv3** [comment]
i think that this simple selection based on a string and a select box should anyway remain also if we eventually will add a selection similar to the one of receiver withe clear description of the topic.

the real good solution that would finally solve this issue of not requiring db changes is https://github.com/globaleaks/GlobaLeaks/issues/999 but requires various work

as short term a single db entry is easy and straightforward to be introduced.

i clarify why your solution based on .po/.json is too much tricy for now and why a single db entry would solve easily the problem:
1 the .po/.json change is too much techie as one should have to change multiple files with multiple translations
2 also if people will success in these, they will have to do this change any time he will need to update the node, by fetching new translation manually
solving 1 and 2 require really more work than simply adding the possibility to customize that string (that is one of the last in the software that is not customizable.

**Comment by vecna** [comment]
mmhh.. I feel that the API has to return the description of the resource, not the things useful for our rendering. every string in the application, sooner or later, someone can ask to customize.

I remember that one possible solution was:

1) we provide translated default (ApplicationData)
2) the "en" language act like a KEY in the GCLlient translation mechanism
3) the translated application is hardcoded in GLC
4) a request on /translation can return the keys to be override 
5) admin panel, all the keys available in english, click on them, you get a number of textarea equal to the language supported, and you can change them.

in this way, we get rid of the application text in the /node /context /receivers, I feel in the long term this is better.

**Comment by vecna** [comment]
but of course, if now is just for that string, go for it. in the long term I guess every string want to be customized, the first time we meet a control-maniac-UX-designer :)

**Comment by evilaliv3** [comment]
i've still to add the support for this in DB. i will be doing this before releasing the new package.

**Comment by evilaliv3** [comment]
done!
