### ISSUE TITLE
Add possiby to set tip expiration to unlimited

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1165]
I has been requested by an adopter for the possibility to set the tip expiration to 0 in order to get un unlimited expiration time.

Depending on the data retention policy this can be a strinct requirement by an organization and before or later we will continue to face this need.

The adopter is the private company for which @2langnic is developing some features in relation to his master thesis.

The feature has been also requested by TI-it. 

Currently the software discards the 0 as a valid value. Shall we include it with the special meaning of disable tip expiration?

\cc @fpietrosanti @hellais @vecna @mmaker

**Comment by evilaliv3** [comment]
This will be for sure less ricky when we will have e2e encryption in place where we can eventually accept this setting only if the system will enforce encrypted data.

**Comment by vecna** [comment]
We've just to keep in mind, that all those feature has to be reported in the /node API, to provide open data and transparency accounting on GlobaLeaks configuration. I'm not against that, just I want that for the audience will be clear (in the future, when leakdirectory can transform these information in icons)

**Comment by fpietrosanti** [comment]
TI-it did not explicitly asked to have unlimited expiry time, but to have a longer one because their investigation last for several months. 
They also asked to integrate within their existing "case management system" ("The Database") in order to export and save for mid-to-long-time the relevant-case they are investigating.

GlobaLeaks is not a case management system, neither a document management system, so we shall not keep for long time submission inside globaleaks. 

The requests coming from @2langnic private company shall be probably formulated in terms of functional requirements and the right technological/integration solution shall be oriented/indicated.

The solution we've been considering with organization objecting for data-retention policy is that they need a "case management system" where to export the globaleaks submissions to manage it after an investigation has started and need to be maintained during time.

So, discussing the "workflow" and "procedure" for the management of submission is the way to go, to identify which kind of integration/additional feature and/or software is required.

**Comment by evilaliv3** [comment]
Closing this as we all agree that a Tip should have forcefully an expiration time set (eventually big, but set.)

**Comment by evilaliv3** [comment]
More and more adopters are asking for this.

The reason is that anyhow even if the adopter set the expiration to a big number there are annoying things happening when one do it; e.g. the whistleblower ends in viewing strange dates as expiration in age 4200.

So probably accepting that one set to 0 for unlimited would work and we can show in the interface of the user that the same interface with written "Expired: never" or something like that.

**Comment by NSkelsey** [comment]
I think this could be quickly solved in the UI. 

Just interpret an expiration date past the year 3000 as 'not expiring in your lifetime' or better just hide the expiration date.

**Comment by evilaliv3** [comment]
yep sure, but it would be probably better and more secure a specific setting even for future implementation that would maybe follow.

**Comment by NSkelsey** [comment]
@evilaliv3 Yep you are certainly right. If the servers time got fast forwarded to the year 3000, these tips go away.

**Comment by evilaliv3** [comment]
not for this reason only, but also for the recipient tip table we could save space for the expiration column.

**Comment by NSkelsey** [comment]
After some discussion today this will be implemented as a `-1` stored in the existing config value.

The question left to answer is if this setting remains in config is placed on individual contexts.

One requires a migration. The other does not.

**Comment by evilaliv3** [comment]
I think having this configuration as context variable offer more flexibility;
 @fpietrosanti also has always supported this idea.

**Comment by NSkelsey** [comment]
After a quick look at the context configurator, the tip expiration time is already a per context setting.

What is system wide is the whistleblower access expiration. This needs to move into the context configuration next to the data expiration.

**Comment by evilaliv3** [comment]
Ah, yes nick sorry for not being clear on the status.

I'm not sure if to move also the access expiration as a per coontext configuration. i specifically designed it globally wanting to reduce the mess that the user can do around this setting that is more related to the security of the platform than to a necessity of the user.

In general also i think that probably will be important to have for both the setting a:
- default configuration at node level (in advanced settings)
- a per context configuration inside the context that at context creation will use the default value.

what do you think?

**Comment by NSkelsey** [comment]
The config should live in one place. Either per context or per Node.

I do not think it is good practice to sprinkle related config like this all over the UI. The data preservation & expiration material should all be in one place.

I think that it should be a per context setting, right along side the overall expiration of the submissions.

**Comment by evilaliv3** [comment]
I agree with you. what i am talking is that i think that that a node default used only as default (with no actual action on the system) would facilitate various use cases.

Suppose this scenario: an initiative wants to create 50 contexts and has for all a policy of 1year of daya retention and 3 months for access expiration.
Do we want to facilitate this possibility having the possibility to first change the default and then create the 50 context already using that default or not?

This general scenario works for discussing also other configurations.

**Comment by NSkelsey** [comment]
Ah but the default can live as a hard coded setting on the initialization of the variable. So if the default is 90 days for access expiration but it is customizable on a per context basis this use case works.

I think it just adds extra confusion to have an application wide configuration that configures the default value for a per context variable which can be customized as well.

KISS KISS.

**Comment by evilaliv3** [comment]
@NSkelsey would you please see if the solution is fine for you?

eventually in next migration we could evaluate to add an sql contraint check on the time to live to enforce it to have a value >= -1

**Comment by evilaliv3** [comment]
Here follows the screenshots for the interfaces when the expiration time is set to unlimited (-1):

Whistleblower tip:
![screenshot from 2016-10-03 11-54-26](https://cloud.githubusercontent.com/assets/217034/19033853/e0692a3c-8960-11e6-936c-d6bce6f8a124.png)

Recipients tip list:
![screenshot from 2016-10-03 11-54-01](https://cloud.githubusercontent.com/assets/217034/19033840/d716c1b0-8960-11e6-87bb-55d06edad12e.png)

**Comment by NSkelsey** [comment]
Per context on and off.
###On
![schermata 2016-10-04 alle 1 33 27 pm](https://cloud.githubusercontent.com/assets/1095794/19072751/37ddc67a-8a37-11e6-8295-85f5f33ff4a5.png)

###Off
![schermata 2016-10-04 alle 1 33 35 pm](https://cloud.githubusercontent.com/assets/1095794/19072755/3bcf119e-8a37-11e6-9cc6-aed3f068b963.png)

Released in v2.64.6
