### ISSUE TITLE
Evaluate the possibility to serve different fonts depending on client localization

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1168]
In relation to the Amnesty project and with reference to Urdu translation the translator verified that currently globaleaks is not using a good set of fonts able to show globaleaks properly on the various languages.

To overcome this issue maybe we have to discuss the possibility to configure the usage of a different font based on the user selected language. Sadly this configuration would be forcefully needed due to the fact that we can't chose forcefully a font on behalf of the adopter that will want to chose it.

**Comment by NSkelsey** [comment]
This can be solved by adding another CSS class ext for the specific langauges.

A selector with `ext-applang` could set custom fonts.

**Comment by evilaliv3** [comment]
Up to the current status of the implementation this ticket has been already addressed.

The software sets and updates the language information in the <html> tag by using the ```lang``` attribute and users can the CSS ```:lang``` selector to configure an alternative font to be loaded depending on the language.
