### ISSUE TITLE
GlobaLeaks could allow only T2w access throught a precise public website (referrer check)

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1171]
This feature is a feature discussed during ALAC workshop.

In the case of ALAC their public website already states a lot of information about the differences between confidentiality and anonymity and already clarify the user the more security provided by the direct access through Tor by the means of the TBB.

Under this conditions they are asking for the possibility to not show the privacy badge when the user is coming from the official informative page.

In addition to this it would be interesting to totally prevent that the user is coming from a different website or by writing the direct link in the url bar and in that case provide a redirect to the informative page.

**Comment by fpietrosanti** [comment]
I'd avoid "blocking" but just having a configurable settings:
- Don't Display Privacy Badge if users comes from URL: <URL>

That way the admin, if configure that URL, it will be matched as a referrer and will not display the privacy badge.

**Comment by fpietrosanti** [comment]
That's somehow related to #1140 of OCCRP

**Comment by evilaliv3** [comment]
Closing as seprecated sinze Tor2web is no longer used within the project.
