### ISSUE TITLE
Send IRC notification of Travis-CI build events (failure, or restore after a previous failure)

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1172]
This ticket is to integrate IRC notification of TRAVIS-CI build following documentation of http://docs.travis-ci.com/user/notifications/ .

It has been already tested with OFTC network by https://github.com/travis-ci/travis-ci/issues/2453

**Comment by evilaliv3** [comment]
Closing as outdated. These notifications are already implemented on the slack channel.
