### ISSUE TITLE
GLClient should generate unique css class identifiers to permit rich user customizations

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1173]
By following the same approach of common UI/UX toos it would be useful if GLClient could generate automatically unique CSS class names for each object generated so that it would be easy for the adopter to properly style the page.

thanks to this for example the design of the custom submission page for Amnesty would be really more simple if the system assign unique classes to fields elements like:
- step-1, step-2, step-3
- step-1-link, step-2-link, step3-link
- field-1, field-2
- field-1-2-3 (in case of nested fields)
- context-1, receiver-1

**Comment by evilaliv3** [comment]
With previous commit i've applied what i described in this ticket by applying it to the only submission fields just to test the flexibility of what of the approch.

**Comment by evilaliv3** [comment]
This is really important as it would facilitate the end2end testing with [Protractor](https://github.com/angular/protractor) moving to May milestone.

\cc @origliante

**Comment by evilaliv3** [comment]
With previous commit i've assigned numbered ID(s) to a lot items both on submission view and on administration views in relation to: steps, contexts, receivers, fields.

**Comment by origliante** [comment]
Yes it it, for what I've found during the tests development, I would suggest this:
- for repeating objects:
  - a common class, example: .private_messages
  - an id that's easy to deal with. Also in the current UUID-like format, since it is already node-unique, example: class="private_messages" id="123123-asfas-213-123213-gr1122"

This permits to easily write complex end to end tests, for example:
  - send multiple messages from the wb interface, save the uuid of a particular message in a variable
  - login to the receiver, read that particular message and check if it matches

- for unique objects:
  - a "verbose" id, example: id="newMessage_textbox"

This should be done on every interaction-related object.

\cc @evilaliv3 @vecna

**Comment by evilaliv3** [comment]
what i was writing is related to CSS elements not to models.

already messages/comments exports their IDs:

    from backend/globaleaks/handlers/rtip.py:

    def receiver_serialize_message(msg):
        return {
            'id': msg.id,
            'creation_date': datetime_to_ISO8601(msg.creation_date),
            'content': msg.content,
            'visualized': msg.visualized,
            'type': msg.type,
            'author': msg.author
        }

**Comment by origliante** [comment]
So in the protractor case it is possible to look for the type field with by.css("[type='message']") ?

**Comment by evilaliv3** [comment]
yep.

let's prefer to use by.xpath, and generally write more precise selectors by using partent-child relations, e.g.:

    element(by.id('step-2')).element(by.id('field-0-input'))

i'm quite ready to commit the finalized submission test and there you will find the complete example

**Comment by origliante** [comment]
+1

**Comment by fpietrosanti** [comment]
Those changes are gonna break all adopters with a custom CSS?
If so, are there other major changes required in the pipelines that would break the CSS that's better to do it now (to avoid breaking it again in future) ?

**Comment by evilaliv3** [comment]
no break at all man. it's only new additional rock and roll.

**Comment by evilaliv3** [comment]
Given the Goldilocks needs of customizing the UI towards the new idea of making templates for GlobaLEaks it's becoming more and more needed that every unique html block of globaleaks has CSS IDs assigned and repeated elements has a unique ID (....-number, e.g. ....-1) and a general class so that while making a template one would find easy to mock every default ugly graphic in a facy UI.

**Comment by evilaliv3** [comment]
i'm now starting working on this ticket for all that relates Goldilocks need with the aim of accomplishing it by today.

i will try to dig also into https://github.com/globaleaks/GlobaLeaks/issues/1362 that is tightly coupled to their needs.

**Comment by evilaliv3** [comment]
@lagon1: in commit https://github.com/globaleaks/GlobaLeaks/commit/0004ffc43873cca9d9e163c2fcec0bf3259639da i've added few  IDs and Classes to each element related to the steps and of the post submissioon tip status page. i've added the one that i remember useful let me know if you have other need.

i've added:

-  #SubmissionTabsNavigationBox id  to make possible show/hide the original step navigation bar
- #SubmissionTabsContentBox id to make possible sandboxing changes to steps
- each step has a unique id (e.g.  id="step-0") and a class SubmissionStep  and so in there; i would suggest you to see at https://github.com/globaleaks/GlobaLeaks/blob/devel/client/app/views/submission/main_horizontal.html and  tell me if there is still something that you would suggest to add
- on the tip page each widget has an  id (e.g. TipInfoBox, TipQuestionnaireAnswersBox) and a common class TipPageSection
-  each tip page widget has an header with class TipPageSectionTitle and a content of class TipPageSectionContent

as we move forward i will also start preparing a documentation of this id/class to be put on the wiki as reference in general.
