### ISSUE TITLE
Figure out a long term strategy to manage exceptions

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1174]
At the moment we are in a mix between, getting spammed, abuse the limit of our mails from our account, having potentially sensitive data (no, not really, worst case scenario, the path of the python files), and we just need exception email to spot bug/race condition that has never been trigger by us.

so we've to think about it. This comment: https://github.com/globaleaks/GlobaLeaks/commit/b8762f55c225819df2a0e42ba254532b5386ed7b#commitcomment-9861697 show one of my needs, the fact that some test node has ramdisk full and we receive every day an email, is another issue, and I wonder if there are other condition and other situation in which we need to be notified. 

what do you think about ?

**Comment by fpietrosanti** [comment]
@vecna No unhandled exception should ever occur, we shall only manage *all* of them, properly handling it (that most of the time means logging it in an ordered way, some time may require alerting the admin). That's the long-term-strategy, handle each single unhandled exception on-time, as long as we notice it.

If we have a lot of filesystem interactions that trigger unhandled exception, it means that we have not enough control/check in the code-flow

**Comment by vecna** [comment]
ok, so the point is: address them when happen. ok then we just need to discriminate the exception caused by development version and the exception caused by running nodes. with the option "-z" will be enough make a clear difference.

**Comment by vecna** [comment]
Can be close I guess

**Comment by evilaliv3** [comment]
i will close this after testing it just to see what happens if we write -z with no arguments.
and i want to see what happens in general in this situations and eventually open tickets of improvements if this conditions are not well handled.

**Comment by vecna** [comment]
@evilaliv3 happen that globaleaks do not start and ask to you to put an argument

**Comment by evilaliv3** [comment]
great thanks. assignin this to me so that i will remember to simply test it and close.
