### ISSUE TITLE
Setup and integrate a new email notification facility specific for GlobaLeaks notifications

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1179]
Setup and integrate a new email notification facility specific for GlobaLeaks notifications because the old one died.

Hermes Center should provide an email notification service for default email installation.

This service shall be based on Postfix SMTP/TLS with authentication over Tor Hidden Service.

This service should avoid any logging.

This service should preemptively block sending any email that are not coming from GlobaLeaks (TODO: Define how to do it, to prevent simple abuse. That abuse prevention shall not be perfect).

**Comment by vecna** [comment]
@evilaliv3 @hellais @mmaker there are many issues mail related, did someone of yours get experience with https://twistedmatrix.com/trac/wiki/TwistedMail ?

**Comment by fpietrosanti** [comment]
@vecna we can have a postfix running on localhost on the machine hosting demo.globaleaks.org with some basic configuration to listen on 127.0.0.1:25, exposed on Tor Hidden Service land, with SMTP/TLS and authentication configured.

That service shall detect email being originated from GlobaLeaks (with some Header and/or Subject matching) whitelisting that ones, and blocking everything else by using Postfix's built-in filter.

That service running on .onion can become the new default email service of the GlobaLeaks platform.

The #724 and #1180 are probably the most important for notification robustness (due to the many problems of operating behind Tor)

**Comment by evilaliv3** [comment]
@vecna not never worked on that.

i agree to simpify the solution to configure  bunch of postfix instances on a machine (e.g., demo.globaleaks.org)

the real problem in all is to test against them during unit testing; due to his strong pythonic experience I would like to ask @maker to work on that and to @hellais to support him with suggestions.

**Comment by hellais** [comment]
I have not used Twisted mail, but it seems pretty straightforward.

If you have some specific questions let me know.

**Comment by evilaliv3** [comment]
great @hellais thanks.
it's origliante tnat probably will dig on this in a bit.

**Comment by fpietrosanti** [comment]
That exists now
