### ISSUE TITLE
GlobaLeaks SMTP notification should support only TLS methods

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1182]
It seems that due to a bug globaleaks is currently not using strong SSL/TLS protocols while performing  SMTP connections.

This has been spotted while disabling SSLv2 on default smtp server used for demo purposes and configuration of wich is included in globaleaks defaults.

**Comment by evilaliv3** [comment]
analyzing the bug i've understood the issue that is not a security bug but simply a malcunction bug.

the issue lies in line 127 of globaleaks/utils/mailutils.py: https://github.com/globaleaks/GlobaLeaks/blob/b48fcfa07dfcb89dd194deaa65051f6714325013/backend/globaleaks/utils/mailutils.py#L127

here we enfoce the use of SSLv3, this way when one use SMTP/TLS the configuration was only working if the server was able to talk SSLV3 (and never TLS).
the variable to be overriddedn is called sslmethod and not method.
due to this since always the ssl cipher that has been used is the Twisted 13.2.0 default that is: SSL.SSLv23_METHOD

**Comment by evilaliv3** [comment]
@hellais / @vecna can you validate this solution so that by today or tomorrow i can push out this fix?

**Comment by vecna** [comment]
is hard to test it.... how can be tested ?

**Comment by evilaliv3** [comment]
i know. at least as code analysis. reading the ticket of Tor i reported  and see if it sound reasonable to you.

to this aim probably in future we will have to integrate in our CI environment a set of different SMTP servers (probably integrable also in travis itself in order to simulate the connections against different mail servers configured with the nost important relevan differnt configs.

**Comment by evilaliv3** [comment]
we got a confirmation by a new adopter that the fix seems to work like a charm.
