### ISSUE TITLE
GlobaLeaks does not work with Orweb from Mobile because Javascript is disabled

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1189]
GlobaLeaks does not work with Orweb from mobile because Javascript is disabled.

The user see the following error:
![nojs](https://cloud.githubusercontent.com/assets/770363/6574453/37c92232-c725-11e4-81fd-7284aa5928d6.jpg)

Once the user go in the Preferences and click "Enable Javascript" he will see the interface:
![yesjs](https://cloud.githubusercontent.com/assets/770363/6574490/d3f7a034-c725-11e4-82c2-05587d0472e8.jpg)

This ticket is to detect that a user is coming from Orweb and have Javascript disabled, providing graphical screenshots guidance/instructions on how to enable it .

**Comment by fpietrosanti** [comment]
@n8fr8 we have this problem with Orweb, is it possible to detect client-side that a user is running Orweb with Javascript disabled?

**Comment by fpietrosanti** [comment]
Below settings with JS disabled by default:
![js-disabled](https://cloud.githubusercontent.com/assets/770363/6576410/531474c6-c737-11e4-9b4a-9735539f7b23.jpg)

Below settings with JS manually enabled:
![js-enabled](https://cloud.githubusercontent.com/assets/770363/6576415/5b632398-c737-11e4-81da-1c6a8a2c15a5.jpg)

With the previously uploaded screenshots we can improve the default page explaining that JS is disabled, with step-by-step guide to enable it on Orweb.

**Comment by n8fr8** [comment]
I like the guide you have created. That said, I am not sure what you are specifically asking us to do with Orweb?

Otherwise, we are working away on getting Orfox/TB "Mini" out, so that will be the new preferred browser for people to use.

**Comment by fpietrosanti** [comment]
@n8fr8 It's a question: There's a way to fingerprint a user coming from Orweb, that have Javascript disabled by default, in order to provide visual instructions on how to enable it?

Because we got feedback from LeMonde in France that users complain that GlobaLeaks does not work with "Orweb" (Because Javascript is disabled), so we'd love to provide visual instructions on how to enable it. But to do it, we need to "detect" that a user is using (Orweb && Javascript is disabled)!

**Comment by evilaliv3** [comment]
this could be probably closed as orweb does not provide fingerprinting capabilities (and i think so of orfox); i hthink the guide we have is enough.

**Comment by comradekingu** [comment]
Orweb is deprecated in favour of orfox https://guardianproject.info/2015/06/30/orfox-aspiring-to-bring-tor-browser-to-android/

None of them sends a specific user-agent, unless you request the mobile site. A multiple choice guide when JavaScript fails might be the best solution.
