### ISSUE TITLE
Add the possibility to enable/disable post submission file uploads on the Tip pages

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1191]
It has been requested by an adopter to have the possibility to enable/disable post submission file uploads allow receivers to swich them on/off depending on the submission field answers.

What is currently missing is:
- the possibility to configure the context with: "Enable post submission uploads": On/Off";
- the possibility for the receiver to switch the submission instance value of this configuration for each submission receiver.

**Comment by fpietrosanti** [comment]
Which adopter? 
Why a receiver want to change this behavior enabling/disabling file uploads?

**Comment by evilaliv3** [comment]
cause they want to enable the whistleblower to submit material only when they have validated that the whistleblower has answered theyr question and the submission will be valid and circonstantiated.

this way they can avoid to forcefully validate videos/images wasting resources.

**Comment by evilaliv3** [comment]
support in the backend is already integrated in devel branch.

we should simply implement the UI in the client.

**Comment by vecna** [comment]
I just noticed this issue, but I'm afraid the UX for the receiver will become quite hard. 
Can't we think to "steps" in the revision process, and the receiver has just to click on "go in the next step", and this step imply some new fields in the Tip ?

so this also solve the Tip status questions. You can know when/what/why is blocking a Tip to go further in the steps, because the receiver has to provide such choice.

**Comment by evilaliv3** [comment]
@vecna: the need for disabling the file uploads/comments/messages seems to be particularly important when the receivers wont to be sure to not have any possible open field where the whistleblower can write "I'm Pino Cammino". This is an important scenario in the most critical setupp.

Anyhow i got totally your concern in making the interface too much complex and in the general this feature will be disabled and it will be the admin that in advanced settings would eventually enable it and teach receivers when to use it.

**Comment by evilaliv3** [comment]
Here follows the interfaces designed:

Receiver interface (enabled only when the receiver is marked "Allow the recipient to grant permissions to whistleblowers on specific submissions")
![screenshot from 2015-11-03 10 07 01](https://cloud.githubusercontent.com/assets/217034/10904439/78735344-8213-11e5-8f19-97f72ed8e5eb.png)

Whistleblower interface:
![screenshot from 2015-11-03 10 06 50](https://cloud.githubusercontent.com/assets/217034/10904443/7e59adbc-8213-11e5-8afe-6b2769c45a51.png)
