### ISSUE TITLE
Languages selector should be internationalized

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1192]
It has been suggested by translators and UI experts that also languages names should be internationalized so that depending on the user selected language also the language selector is understandable by the user.

e.g. for me that i'm italian, the "English" selector should appear "Inglese".

This would require extracting languages names and pushing them on transifex.

**Comment by fpietrosanti** [comment]
I'd suggest to evaluate if there is some library/archive that already do provide that feature (ie: name of languages in most of world languages), without a translator having to work over it.

**Comment by evilaliv3** [comment]
it was already evaluated by me and that does not exist.

few libraries exists and not complete and in addition our translations are tightly mapped ont transifex names, and it's totally impossible that some library uses exactly the same names as starting point.

i will interact with the transifex developers in order to offer such a feature in general and share this translators effort on all the transifex projects.

**Comment by fpietrosanti** [comment]
Consider also asking this to OTF's mailing list, as a shared deliverable that many OTF projects will benefit from

**Comment by eighthave** [comment]
I think the best way to handle the names of the languages is to keep in their native language only, and never translate them into any language (including English).

To take your Italian example, if you are reading the Italian text and you don't understand what Ελληνικά means, then that language option is not going to be useful for you.  But if you only speak Ελληνικά, then it is going to be a lot easier to read the word "Ελληνικά" than "greek" or "greco".  Just like if you were reading the greek text, you'll find it a lot easier to read "Italiano" than "ιταλικά".

For example, here is what we post in the app description for ChatSecure:

★ WE SPEAK YOUR LANGUAGE: ChatSecure is available for friends who speak: العربية, Български, 中文(简体), 中文(台灣), Català, Čeština, Dansk, ‏עברית‏, Nederlands, English, Esperanto, فارسی, Français, Deutsch, Ελληνικά, Magyar, Bahasa Indonesia, Italiano, 日本語, 조선말, Norsk, Polski, Português, Русский, español, español (España), Slovenčina, Slovenščina, Српски, Svensk, བོད་སྐད།, Türkçe, and Tiếng Việt

**Comment by eighthave** [comment]
As for getting the names of languages in the native language, you can get them directly from Java/Android:

https://github.com/guardianproject/ChatSecureAndroid/blob/master/src/info/guardianproject/util/Languages.java

**Comment by evilaliv3** [comment]
thank you @eighthave 
your suggestion is gret.

the only problem in using simply the java mapping is that it do not offer a mapping for "Portugese (Brazil)" / "Portuguese (Spanish)" etc, e.g., how did you manage to create "español (España)" ? 

it would be interesting to ask Transifex to export an API that export {lang_code, lang_name, native_lang_name} for each of the lang_code, so that all Transifex users will benefit from such an official mapping.

\cc @glezos @diegobz

**Comment by eighthave** [comment]
Using the same approach, you can break the language code into its two parts, then query the system for the country name too.  I.e. `pt_BR`, then query for `pt` language name and `BR` country name.

**Comment by eighthave** [comment]
One thing to consider is whether you want to show the user all of the country variants.  The only case where the country variant makes the language very different is simplified vs traditional chinese (i.e. `zh_CN` vs the other `zh` variants like `zh_TW`).  For the rest, I think people will be able to understand it fine, but it'll just be a bit off.  We only use these language names when the user is manually choosing a language to keep the UI simple and clean.  If the user has set their system to a country variant, e.g `es_MX`, then the app will automatically use the country variant.

**Comment by eighthave** [comment]
Here are two examples of how we use it:
![language-chooser-chatsecure](https://cloud.githubusercontent.com/assets/143465/6643497/0573509a-c983-11e4-8770-2e604c069e15.png)
![language-chooser-courier](https://cloud.githubusercontent.com/assets/143465/6643498/057ad3ba-c983-11e4-8dd3-2a97dfbaf9ef.png)

**Comment by evilaliv3** [comment]
this has been investigated by me and i've quite implemented it.
moving the ticket to next milestone.

**Comment by comradekingu** [comment]
I think flags should be added to the UI. This offers one-click selection, toggling, and vastly improved cognition.
It also deals with having selected something by accident only to get all options in 'foreign', so that language-names can be properly localized. Followed by ISO 639-1 codes.

So Germany (de) for English
and Deutschland (de) for Germans  Even if you get
ئەڵمانیا (de) for Centralkurdish, you still have some way of recovery.

This way you wont have to, provided there is support, specify which version of Spanish you want, should you first accidentally to foreign, and then click a flag that doesn't directly correspond to that language.
Same story with multi-lingual flag-regions.

**Comment by evilaliv3** [comment]
thanks for the feedback @comradekingu 

i think that for the MVP we should focus on having simply the text internationalized in the natural language of the user instead that in english.

Right now we have:
LANGUAGES_SUPPORTED = [
 { "code": "ar", "name": "Arabic" },
 { "code": "bs", "name": "Bosnian" },
 { "code": "ca", "name": "Catalan" },
 { "code": "de", "name": "German" },
 { "code": "el", "name": "Greek" },
 { "code": "en", "name": "English" },
 { "code": "es", "name": "Spanish" },
 { "code": "fa", "name": "Persian" },
 { "code": "fr", "name": "French" },
 { "code": "he", "name": "Hebrew" },
 { "code": "hr_HR", "name": "Croatian (Croatia)" },
 { "code": "hu_HU", "name": "Hungarian (Hungary)" },
 { "code": "it", "name": "Italian" },
 { "code": "ja", "name": "Japanese" },
 { "code": "ka", "name": "Georgian" },
 { "code": "ko", "name": "Korean" },
 { "code": "nb_NO", "name": "Norwegian Bokmål (Norway)" },
 { "code": "nl", "name": "Dutch" },
 { "code": "pt_BR", "name": "Portuguese (Brazil)" },
 { "code": "pt_PT", "name": "Portuguese (Portugal)" },
 { "code": "ro", "name": "Romanian" },
 { "code": "ru", "name": "Russian" },
 { "code": "sq", "name": "Albanian" },
 { "code": "sv", "name": "Swedish" },
 { "code": "ta", "name": "Tamil" },
 { "code": "th", "name": "Thai" },
 { "code": "tr", "name": "Turkish" },
 { "code": "uk", "name": "Ukrainian" },
 { "code": "ur", "name": "Urdu" },
 { "code": "vi", "name": "Vietnamese" },
 { "code": "zh_CN", "name": "Chinese (China)" },

haviing a flag + the ISO is something that we could discuss but it's not that easy to deal with this having a nice UI and showing the ISO 639-1 would be probably too much verbose?

**Comment by comradekingu** [comment]
Just the language codes are fine. It solves the "foreign" problem. Adding a "language"-pictogram next to the language dropdown is probably a good idea too.
You could potentially have enabled "foreign" and not know where the menu to undo it is.

Similarly having languagecodes help if someone happens to come by the landing page not speaking a word of English. I suppose you could be sent links with &lang= suffix, but still a potential issue to avoid.

**Comment by NSkelsey** [comment]
Basic support added in 4a7a546. Did not add country flags, but I think that is a great idea.

![change-langs](https://cloud.githubusercontent.com/assets/1095794/14925395/359d3e16-0e15-11e6-80ff-8ccca7b3c423.gif)

(There are still some bugs!)

**Comment by NSkelsey** [comment]
@comradekingu if you can find abunch of low res, small, uniform looking country flag PNGs, I can add them to the UI.

**Comment by comradekingu** [comment]
http://www.famfamfam.com/lab/icons/flags/

2016-04-29 20:29 GMT+02:00 Nick Skelsey <notifications@github.com>:

**Comment by evilaliv3** [comment]
implemented! by @NSkelsey;

what i wanted to get addressed on this issue is done; i suggest to keep the icon issue as a researchable topic for the future.

anyway the valid resources for this i think are:
https://github.com/lipis/flag-icon-css
https://github.com/asafdav/ng-flags

probably we would need to implement the same code of ng-flags, without using the library in order to not add not needed dependencies.
