### ISSUE TITLE
Tips preview lacks of clear Comments/Messages counter indication

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1193]
Since the refactor related to https://github.com/globaleaks/GlobaLeaks/issues/1015 the Tip preview interface for the receiver is not providing good information for the user in relation to Comments/Messages counter.

Currently there is simply a counter called Comments. We should add a Messages counter with the private messages count.

I suggest to continue to call them Comments and Messages at least on this minimalistic interface with few space regardles of the fact that on the Tip page we call "Additional Info" the comments, and Private Messages the messages.

\cc @fpietrosanti

**Comment by evilaliv3** [comment]
![unnamed](https://cloud.githubusercontent.com/assets/217034/6638248/49eba4ec-c984-11e4-9a0c-c3d2f924fc06.png)

this is the current status.

**Comment by fpietrosanti** [comment]
good

**Comment by evilaliv3** [comment]
![screenshot from 2015-03-18 01 21 16](https://cloud.githubusercontent.com/assets/217034/6700351/2ec3152e-cd0d-11e4-81a7-2145d0564e9b.png)

implemented!
i've simplified the interface removing the column Info, and putting all inside the Preview column.
in addition the various infos like "Files", "Comments", "Private Messages" are shown only if the counter is > 0, this way the interface do not waste space for unuseful data like "Files: 0"
