### ISSUE TITLE
Email notification

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1194]
I've been noticing since a long time some failures with the email notifications. In some cases I thought it was the email server, and maybe it is, but after having different nodes experiencing the same issues using different email servers, I'm sending this issue. Email notifications have been performing 3 different behaviors in what seems to  be in a random standard:
a) Arrive normally
b) Arrive with a considerable delay
c) Never arrive

Now in Mexicoleaks all partner reported behavior b and c.

**Comment by evilaliv3** [comment]
the delay is ok as it part of a different approach of the mail scheduling implemented by @vecna.

i will do some tests verifying if it is real that c) sometimes may happen.

**Comment by fpietrosanti** [comment]
@infosquatter Can you tell us which email server are you using? Because we found out that email sending "behind tor" revealed to be a bit problematic sometime

**Comment by fpietrosanti** [comment]
Applied label MexicoLeaks

**Comment by infosquatter** [comment]
It's the Greenhost one.

Fabio (naif) Pietrosanti:
> @infosquatter Can you tell us which email server are you using? Because we found out that email sending "behind tor" revealed to be a bit problematic sometime
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/globaleaks/GlobaLeaks/issues/1194#issuecomment-80052486
> 

-- 
PEDRO NOEL
- Editor
Associated Whistle-Blowing Press - https://awp.is
Chaussée d'Alsemberg 608A
1180 Uccle/Bruxelles - Belgique
GPG key: http://pgp.mit.edu/pks/lookup?op=get&search=0x72B725E1410034FB

**Comment by evilaliv3** [comment]
Closing the ticket as outdated;

Resiliency of the notification mechanism has been improved and specific tickets deals with implementing automatic retesting of the configurations.
