### ISSUE TITLE
Issue adding PGP public key to receiver

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1197]
After a receiver was added to a context with multiple receivers and was the only receiver lacking a public pgp key attached, while attaching the key to this receiver the secure notification did not changed and receiver continued not able to receive submissions. Solution was to delete receiver from the context and add it again.

**Comment by evilaliv3** [comment]
i will try to reproduce this tomorrow morning and see if i'm able to reproduce it and eventually fix it.

**Comment by fpietrosanti** [comment]
Applied label MexicoLeaks

**Comment by evilaliv3** [comment]
this issue has been verified also by @origliant while developing end2end.

The issue existsed only on receiver side due to the fact that the update to the receiver settings didnt invalidate the /receivers API cache.
