### ISSUE TITLE
Anomaly Detection email are not "useful" or "actionable"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1198]
Nowdays admin can receive Anomaly Detection email like:
admin@XXXXXXX.i1i105GBnsparency.i1i0ncy.i1i105GBnsparency.i1isuccessful_logins: 5
rency.i1i105GBnsparency.i1i0ncy.i1i105GBnsparency.i1it

Those email have a set of bugs:
- Are badly formatted/unreadable
- Are not useful at all or are not "actionable" 
- Does not introduce/describe what are used for

For the following reason the anomaly detection email shall be:
- disabled/removed

OR 

- shall become useful/actionable
- shall be formatted properly
- shall have an introduction/explaination text on what they are and why are useful/actionable

When i say "useful" i meant that the admin must be able to acquire information that are useful somehow, tell him some information that are relevant for him in his admin duty.

When i say "actionable" i meant that the Admin shall have a way to "act", "do something", to check or preemptively "do stuff" on the content of this email.

If the content is not useful nor actionable, those email shall be disabled/removed.

**Comment by evilaliv3** [comment]
@fpietrosanti you totally misunderstood the issue here.

the format of the email is clear and complete: https://github.com/globaleaks/GlobaLeaks/blob/master/client/app/data/txt/admin_anomaly_template.txt

what is happening is simply that there is a bug in the templating thing that make probably happen some cylick replacement that ends in fucking all the resulting email.

**Comment by evilaliv3** [comment]
for sure the information provided can be better, but what is causing "admin@XXXXXXX.i1i105GBnsparency.i1i0ncy.i1i105GBnsparency.i1isuccessful_logins: 5
rency.i1i105GBnsparency.i1i0ncy.i1i105GBnsparency.i1it" is not a wrong template in the intention of the author but a bug that lies somewhere in the templating system

**Comment by fpietrosanti** [comment]
@evilaliv3 sure, one of the problem is the template, but i don't see the anomaly detection email nor useful nor actionable, that's where i mostly see the bug

**Comment by vecna** [comment]
Which are the actions ? they can be suggested in the email. Just as update, the condition detected (defined in anomaly.py) are these 6:

           # If percentage is <= 1%: disable the submission
            'condition': free_disk_percentage <= 1,

            # If disk has less than the hardcoded minimum amount (1Gb)
            'condition': free_disk_megabytes <= GLSetting.defaults.minimum_megabytes_
required,

            # If ramdisk has less than 2kbytes
            'condition': free_ramdisk_bytes <= 2048,
 
            # If percentage is 2% start to alert the admin on the upcoming critical s
ituation
            'condition': free_disk_percentage == 2,

            # Again to avoid bad surprise, we alert the admin at (minimum disk required * 2)
            'condition': free_disk_megabytes <= (GLSetting.defaults.minimum_megabytes_required * 2),
    
           # if 5 times maximum file can be accepted
            'condition': free_disk_megabytes <= (Alarm._HIGH_DISK_ALARM * GLSetting.memory_copy.maximum_filesize),
    
         # if 15 times maximum file size can be accepted
            'condition': free_disk_megabytes <= (Alarm._MEDIUM_DISK_ALARM * GLSetting.memory_copy.maximum_filesize),

**Comment by vecna** [comment]
@evilaliv3 @fpietrosanti I've restructured the templates https://docs.google.com/document/d/10zRQ2VeaBzo5w1UWyq7Eka910NxFtq3hgyPqQWs8xBA/edit#

**Comment by vecna** [comment]
so, has to be planned a database structure and Admin interface to let Admin configure thresholds. This issue is become that, right ?

**Comment by evilaliv3** [comment]
No.
Since we changed the email templates with good actionable tests we
forgotten to close the ticket.

Please close it.

We should open a new one for the specific aspect of making the settings
configurable but it's not a requirement by now, let's simply put it in
wishlist.

And to answer your question, tickets does not chage the topic but only get
refined a little based on discussions. This is why what you are suggesting
does not have to stay here.
