### ISSUE TITLE
Create GlobaLeaks self-care Demo for http://demo.globaleaks.org

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#120]
In order to show out how globaleaks works, without the need to install globaleaks, it is required to create a custom way of using globaleaks where a single user can interact as:
- as a whistleblower
- as a receiver (receiving the submission sent as a whistleblower)
- as an admin, with ready-only view of a configured globaleaks node (being able to interact with all the interfaces, but without saving data).

This should improve the use evaluation and understanding of globaleaks software.

This ticket should review the functional and technical implementation to implement this kind of software show-case.
##

**Comment by evilaliv3** [comment]
Closing as outdated
