### ISSUE TITLE
Enable configuring Contexts that are "hidden" on the main submission interfaces

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1202]
This ticket is to enable configuring Context that are "hidden" on the main submission interfaces.

This requirement comes from Transparency International Italy ALAC because they are going to host "multiple" initiatives on their ALAC platform (for anti-corruption of few public administration), so they will have:
- their main ALAC's context https://alac.transparency.it that is the onlyy onew shown on the main submission interface
- other public administration embedded sites (with GlobaLeaks Integration mode) that are explicitly shown only when the Context Parameters is explicitly set

To implement that kind of behavior we can add a new property to a context that's "Hidden", so it's not shown on the main submission interface as a part of the "contexts", unless it's explicitly enabled/passed as a parameter.

**Comment by evilaliv3** [comment]
This feature was implemented long time ago.

The context configuration section currently lists a link that can be used to test the context.
