### ISSUE TITLE
Enable customizing globaleaks graphical design of "embedded mode" on a context by context basis

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1203]
This ticket is to enable customizing globaleaks graphical design of "embedded mode" on a context by context basis.

This requirement comes from Transparency International Italy ALAC because they are going to host "multiple" initiatives on their ALAC platform (for anti-corruption of few public administration) and they will leverage the new "embedded" deployment support of GlobaLeaks, one for each Public Agency.

Each public agency will "embed" globaleaks in their intranet, so they will require the "look and feel" to be adjusted to the website that's embedding globaleaks.

The idea of this ticket is to enable customizing the graphical design of globaleaks (ie: CSS and/or other parameters to be defined with a technical analysis) so that each context can have such customizations.

The very same requirement will probably come up from OCCRPLeaks, once they start deploying it to the various media.

**Comment by evilaliv3** [comment]
concerning this topic i've some doubts and already a suggestion.
currently as specified this force the contexts that want to use the same layout to upload the same css, the same files and bla  bla; this represent a limiti the first step (setup) and in the mainainance (update in an aligned way of this)

what i suggest is to add a templateing system like common website framework offer and make possible by URL or by context mapping to select this template.

the url mapping is powerful but has an importante drawback; that every site can impersonate one other in the graphic. so i'm here suggesting to implement the static dir as a virtual template directory and then map this template on a context.

**Comment by fpietrosanti** [comment]
@evilaliv3 as i specified completely leave open to any implementation without technical constraint, it's only "functional specs" . 

Please just consider that any customization must be doable from the admin interface.

**Comment by evilaliv3** [comment]
Closing as current implementation prevents embedding.
