### ISSUE TITLE
Evaluate removal of max downloads of files

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1204]
As @vecna was suggesting it would be interesting to remove the max download file and the max access for the tips.

Now that all user accesses are tracked by a login the max download file and the max access file do not offer anything better that could not be managed by recognizing a patter of to much accesses to a resource.

Removing the max download file and the max access to tips we will solve issues of users:
1) accessing too much to a single file and than downloading the zip and finding inside onliy the files currently available for downloads. various adopters reported me this in past and i simply explained it and then ignored it.
1) accessing too much time and see that yey are not able to access anymore.

**Comment by fpietrosanti** [comment]
A unused feature is a dead feature & dead code, so imho we can trash it

**Comment by evilaliv3** [comment]
agreed! :) let's do it!

**Comment by evilaliv3** [comment]
removed!
