### ISSUE TITLE
Evaluate the possiblity for mail templates simplifications

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1205]
Currently we offer a too much complex templating system for mails that are not used at all.

This ticket is to discuss the possible simplifications:
1) the configuration of mail titles both encrypted and unencrypted version is currently not needed as email subjects are in cleartest. what we want to do here?

2) in general currently we offer two customizations for encrypted/unencrypted mails. i suggest to simplify the configuration. the problem lies in fallback situations where two templates are needed (e.g. a user for wich the PGP expire or a globaleaks server with a mixed situation of users with PGP and some with no PGP.

@fpietrosanti, @vecna: this are the two points to which i'm thinking now, but maybe you have others.

**Comment by fpietrosanti** [comment]
By having different templates for encrypted and unencrypted emails leave the possibility to implement functionalities such as "delivery of submissions over email" that once was available, but unspecified publicly. But given that this feature is not present anymore, if you want to simplify, we can have a single template. Then, in future, if/when we'll re-implement delivery of submission fields over email, we'll re-introduce encrypted email template.

**Comment by evilaliv3** [comment]
no, i prefer to keep things that are in the roadmap. so i prefer to keep both templates. this solve my douby number 2)

what about number 1)?

**Comment by fpietrosanti** [comment]
@evilaliv3 is the two email will contain different stuff, it's reasonable to have different subjects

**Comment by evilaliv3** [comment]
i see, my doubt is the following and is related mostly to the internationalization overeaded that an adopter will face.

suppose the scenario of a multi language node with mixed receivers with both users with PGP and not-PGP. the adopter will have to configure and keep aligned two subjects (encrypted/unencrypted) for the same emalil type also if he has to do it for each language. the current implementation is really not usable in this.

**Comment by evilaliv3** [comment]
Closing the ticket as it do not apply anymore to current codebase that feature only a set of mail templates used for both plaintext and encrypted mail notifications.
