### ISSUE TITLE
An admin should be able to require a mail notification for each notification event

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1208]
It has been requested by TI-it for the possibility for the admin to be able to require a mail notification for each notification event.

This would be needed in order to let the administrator control what is happening on the system by simply controlling the email notification and be sure that if a notification scattered onto the platform it's track is kept also in the email.

This is felt by the user as a strong legacy capability that should be important to optionally enable in order to be sure to not loose information.

**Comment by fpietrosanti** [comment]
How notifications are going to change respect to that model (1 event = 1 notification) ?

**Comment by evilaliv3** [comment]
not exactly.
globaleaks always apply a digest on the mail notification period, so that over the period all events are aggregated into a single email, but right now in case the user have seen the event info before the mail is sent, the related info is not written in any email.

with the patch i'm going to do instead every event info will be always present in a mail that can be a single mail (in case only an event scattered) or a digest mail (if multiple event scattered during the period), but you are sure that what happened on the node can be always read inside an email.

**Comment by fpietrosanti** [comment]
Can we make it default behavior?

**Comment by evilaliv3** [comment]
done!
