### ISSUE TITLE
Remove "activities" page on receiver and make "Tips" the default on

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1209]
During the various demo done in Philippines we had really hard time to identify what's the usefulnes for the end-user of the "activities" page on the receiver.

The receiver user does not have any useful actionable information on the activities page other than a list of "unknown tip" with a set of events that he can click on.

I suggest to remove the activities page entirely, leaving the "Tips" page as the main page of the receiver

**Comment by evilaliv3** [comment]
if i may add my opinion i confirm that this page caused problems also to TransparencyTI.
i agree with @vecna in the concept but right now it is really really causing too much confusion to adopters.

for the next release i will remove the page and keep the text/translations memory and eventually we will re-add the feature when betterly studied.

**Comment by vecna** [comment]
Yeah totally, has not to be the default, I'll try the commit later to review.

**Comment by evilaliv3** [comment]
done!
