### ISSUE TITLE
Improve visualization of "View Submission" in the Receipt page

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1210]
It has been reported by Amnesty that the "View Submission" link in the Receipt page show be bigger/better visible in order to provide a guidance for the next-action of the Whistleblower in accessing his tip.

Attached the screenshot related to the part of the interface to be improved:
![screen shot 2015-03-30 at 11 22 43 am](https://cloud.githubusercontent.com/assets/770363/6893695/4740ea42-d6cf-11e4-9724-cc02232b7388.png)

**Comment by evilaliv3** [comment]
it should be simply bigger in the size of what? pleaase open more clear issues or they are unuseful to me and i will probably start closing them as bad defined. :P

**Comment by fpietrosanti** [comment]
@evilaliv3 what's not clear of the ticket? "bigger/better visible" leave autonomy to the way it could be implemented

**Comment by evilaliv3** [comment]
With previous commit i've improved the colors by replacing the link with a button, and putting the button on the left of the widget following the same design of the app as in other pages. this should help the user to recognize the button as a step button that allow him to proceeed.

![screenshot from 2015-04-01 12 19 28](https://cloud.githubusercontent.com/assets/217034/6939130/bf439c42-d869-11e4-9ea1-bfccd82effeb.png)
