### ISSUE TITLE
It's possible to finalize a submission when a file upload is in progress

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1212]
It's possible to finalize a submission when a file upload is in progress.

I tested uploading multiple files in parallel (4-5), when the first one has been completed but others was still going in parallel, i was able to confirm the disclaimer on step-3 and to finalize a submission.

This ticket is to check that no file uploads are in progress when finalizing a submission.

**Comment by evilaliv3** [comment]
should be fixed now.

@hellais can you retest it? can you plese see why on a large (long) file upload the loading bar is not visible annymore?

**Comment by hellais** [comment]
This should now be closed.
