### ISSUE TITLE
Receivers client cache is not correctly updated if a new receiver is added until globaleaks is restarted

### ISSUE THREAD

**Issue by origliante** [globaleaks/GlobaLeaks#1216]
Adding a receiver and subsequently trying to make a submission from the WB client to that receiver is impossible, the receiver is not in the list. Tested on current devel .63

**Comment by evilaliv3** [comment]
i will investigate the issue because i was thinking to have solved it.

as suggested by @fpietrosanti then for the future it would be important to make every cached element subject to an expiration time so to solve issues of this kind with also a practical approach.

**Comment by evilaliv3** [comment]
the issue has been fixed by me in current devel since march.
i've veried that @origiante was still using the mast branch.
