### ISSUE TITLE
Bring air mattress, king size

### ISSUE THREAD

**Issue by hellais** [globaleaks/GlobaLeaks#1218]
@origliante can you bring your king air mattress for the hackfest?

Thanks :love: :ninja: :cat:

**Comment by evilaliv3** [comment]
![air-mattress-sleeping-bag-design-inspiration-2](https://cloud.githubusercontent.com/assets/217034/6910616/cc4dc5f8-d755-11e4-8ce3-dfe0d02ce22d.jpg)

**Comment by hellais** [comment]
Mattress delivered :+1:

**Comment by evilaliv3** [comment]
well done!
