### ISSUE TITLE
The PGP key for E2E could be generated in background while the user chose it's password

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1226]
Currently the PGP key used for E2E is generated when the user click on the password save button.

GlobaLeaks could optimize the process generating the key starting immediately from the moment the user logs in so that at that when the user click the password save button the application can simply encrypt the password with the scrypt secret generated starting from the password.

The same can be done for the whistleblower; when the wb initialize the submission the system can start generating the pgp, concurrently generate the the receipt,apply the scrypt to the receipt so that at the time of the submission the only operation still to be performed will probably be the encryption of the wb_fields

\cc @origliante
##

**Comment by hellais** [comment]
My only fear with doing this when we don't have webworkers is that the UI could be irresponsive while this is happening since there no real "background" without webworkers.

**Comment by evilaliv3** [comment]
for sure this ticket should be implemented by using webworkers.

me and @origliante are already working on this.

**Comment by origliante** [comment]
I'll push it to my repo in the next commit

**Comment by evilaliv3** [comment]
Closing as outdated.
