### ISSUE TITLE
Texts for new E2E encryption interfaces should be defined and put under internationalization

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1227]
This ticket is to keep track of the work related to the study, definition and internationalization of the UI and texts for the E2E functionalities.
##

**Comment by evilaliv3** [comment]
@fpietrosanti / @origliante: this work should be considered of high importance for this milestone so to be ready to push the new texts on transifex by the end of the April milestone and being ready to integrate all the work related to the D2.1 and D2.2.

when finished after a first review by @hellais i will take care of asking some of our current best translators and then i will push them on transifex.

**Comment by evilaliv3** [comment]
In relation to this ticket please work directly on the following document: https://docs.google.com/document/d/1Jte37_70JIi8cWxxGbMRKNhHom7XvbKGi98QctnwrWg/edit

**Comment by fpietrosanti** [comment]
@evilaliv3 I think that, more than text, we shall talk about "interfaces", so doing this while implementing it, otherwise we will not be able to define it in advance?

**Comment by hellais** [comment]
I reviewed the 2 texts on those pages, suggesting an alternative.

**Comment by evilaliv3** [comment]
as the branch is still not ready for integration let's move this ticket to next month milestone.

**Comment by evilaliv3** [comment]
@NSkelsey, thanks for your work of today collecting the string for the implenetation.

After a revision i've decided to annotate them here in order to discussu together how to possibly narrow them down to more simple sentences and possibly less sentences:
```
browser-crypto texts for key-gen:
<span data-translate-xxx>User activation in progress</span>
<span data-translate-xxx>Generating the encryption key</span>
<span data-translate-xxx>Saving the encryption key on the platform</span>

password-change (from user-prefs and admin/user):
<span data-translate-xxx>A reset permanently removes the user's account data and their access to existing content.</span>
<span data-translate-xxx>Only use this action if the user has forgotten their password.</span>
<span data-translate-xxx>Password change in progress</span>
<span data-translate-xxx>Updating the encryption key on the platform</span>

submission-decrypt-failures:
<span data-translate-xxx>This message failed to decrypt.</span>
<span data-translate-xxx>There was a problem decrypting the answers to the questionnaire.</span>

recipient-key-gen-error: (too specific)
<span data-translate-xxx>Error initializing recipient's private key</span>
```

**Comment by NSkelsey** [comment]
Wow this is an old ticket. As mentioned in commit ea818d6dd4b4d71ee143e9a4b4486b248f6de306, the last two proposed sentences should be removed as too specific.

> User activation in progress 

This should have a following text that informs the user what 'activation' means when using crypto in the browser.

**Comment by evilaliv3** [comment]
Closing as outdated.
