### ISSUE TITLE
Texts for new Flood Resiliency interfaces and mail notifications should be defined and put under internationalization

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1228]
This ticket is to keep track of the work related to the study, definition and internationalization of the UI and texts for the Flood resiliency functionalities.

**Comment by evilaliv3** [comment]
@fpietrosanti / @vecna: this work should be considered of high importance for this milestone so to be ready to push the new texts on transifex by the end of the April milestone and being ready to integrate all the work already implemented for the D8.

when finished after a first review by @hellais i will take care of asking some of our current best translators and then i will push them on transifex.

**Comment by evilaliv3** [comment]
In relation to this please work directly on the following document: https://docs.google.com/a/evilaliv3.org/document/d/1_BrubzTbqOgCi4mNx-po5VYPZVRUV9MBzbj7DkO8Q_0/edit

**Comment by hellais** [comment]
Note: we should put this sort of information (the texts) on some public venue so that also others (non Hermes/GlobaLeaks people) can review it also and not on some private google doc since it doesn't contain any confidential information...

**Comment by hellais** [comment]
When I finally open the google doc I see that it is empty.

If you give me a basic idea of what needs to be written/reviewed I can work on it.

**Comment by vecna** [comment]
@hellais  This is the gdocs about the text https://docs.google.com/document/d/10zRQ2VeaBzo5w1UWyq7Eka910NxFtq3hgyPqQWs8xBA/edit

**Comment by vecna** [comment]
@hellais give a look before the latest closing of comments happen :)

**Comment by hellais** [comment]
@vecna I finished reviewing the first 3 pages, but there are still a bunch of unresolved comments and suggestions.
Could you perhaps first close all the pending comments and requests for modification so I can finish the review?
