### ISSUE TITLE
Integrate pgpy in place of python-gnupg

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1229]
Given the switch from server encryption to client end2end encryption I would suggest to start switching from python-gnupg to pgpy.

This has been already tested by @origliante and would would straightforward with the following benefit:
- reduced attack surface for the application that due to python-gnupg currently allow the binary to access the sheel by means of a specific apparmor rule
- less dependencies of the application

the only current drawback is the missing support for streaming encryption that would cause the backend to need a RAM amount in linear dependency with the size of the file to encrypt; anyway also this limitation is near to be solved: https://github.com/SecurityInnovation/PGPy/issues/139
##

**Comment by evilaliv3** [comment]
@fpietrosanti do you agree?

**Comment by fpietrosanti** [comment]
@evilaliv3 that's a duplicate of #860

**Comment by evilaliv3** [comment]
somehow, let's say this one is the specific one if we go in direction of PGPy; by the way my questions was do you agree to proceed in this direction?

**Comment by fpietrosanti** [comment]
@evilaliv3 mmmm i'm not conformable in switching from GnuPG working in streaming to PGPy not working in streaming. 
I suggest to wait till e2e will be in place, widely used, or to start integrating it only for notification purposes, to we can unroll an upgrade on existing deployments and see how it does behavE?

**Comment by evilaliv3** [comment]
my suggestion is to go out with this together with the end2end implementation and i hope by that time that the streaming encryption will be in place also but for me it doesn't matter.

**Comment by fpietrosanti** [comment]
@evilaliv3 Then let's go for it, but we'll at least need to ask OTF to make an audit of such a library. If we are troll enough, i'd suggest also to make such a small library/wrappers around python-gnupg to use PGPy, to increase adoption. We shall try to avoid ending up in the same situation of Storm :P

**Comment by hellais** [comment]
I don't think it's wise to do the switch **before** a proper security audit has been done.

**Comment by evilaliv3** [comment]
i agree, let's postpone this for a little and ask feedback by the crypto community and if agreed between various projects that having a native implementation of pgp in python would be useful eventually we could try to ask some shared funders to fund an audit.

**Comment by fpietrosanti** [comment]
I asked opinions about that here:
OpenPGP in Python: Security evaluations? http://lists.randombit.net/pipermail/cryptography/2015-April/007214.html

**Comment by evilaliv3** [comment]
ok waiting for the community discussion, i'm now moving the ticket to whishlist milestone.

**Comment by evilaliv3** [comment]
Closing this ticket that is probably not of interest anymore to integrate pgpy that misses streaming encryption.
