### ISSUE TITLE
Study how to minify webworkers inside the application

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1230]
In order to finally integrate our end-to-end encryption implementation we should need to use webworkers in order to perform various activities in browser threads.

common usages of webworkers seems to require the web worker to not be minified but to be available as separate javascript file.

this ticket is to investigate for the possibility to bundle our webworkers files as part of the minified script.js

\cc @fpietrosanti @hellais

**Comment by evilaliv3** [comment]
i've found this library that seems to be a good starting point: https://github.com/mattslocum/ng-webworker

it declares that the support for IE is still missing; i'm going to open a ticket on their repository in order to ask for suggestion.

**Comment by evilaliv3** [comment]
this was an other probably outdated project on this topic: https://github.com/shama/workerify

**Comment by evilaliv3** [comment]
from my research there is no need for using any external library but the good solution would be to implement this solution: http://stackoverflow.com/questions/10343913/how-to-create-a-web-worker-from-a-string

in practice for a lot of browser we will simply load the worker directly from the minified javascript file, while for IE10 we will have to load a separated javascript file that can contain simply a small generic function to wich then pass the function to be executed, so that also for IE10 there is a small solution that do not involve loading a second big file but simply a small one.

in the futur the an improval of the solution i'm proposing would be use the CACHE of Service Workers: http://stackoverflow.com/questions/5408406/web-workers-without-a-separate-javascript-file

p.s.: obviously all the code we write should work also on browsers that do not support webworkers; even if it's a different topic we should keep this in mind.

**Comment by evilaliv3** [comment]
moved to wishlist as this is not to be considered a priority and won't be simple to be solved in a cross-compatible fashion

**Comment by hellais** [comment]
I also did a brief study and this is going to be quite a PITA to do.

We should do some benchmarks and figure out how the current e2e crypto implementation performs and if we can do without webworkers in the first release or not

**Comment by evilaliv3** [comment]
Closing this ticket for two reasons:
- we don't run anymore any worker directly;
- within the project we are not anymore minifying every component as this does actually particular difference in recent browsers / tor browser.
