### ISSUE TITLE
The clientside redirect do not handle correct url redirection

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1234]
i've verified that while handling the clientside redirection to the HS for some urls the client does not perform correct URL redirection.

E.g. the redirection for https://experiment.globaleaks.org/#/embedded/submission?lang=en seems to redirect to http://imdk4xvljqsyjocv.onion/embedded/submission?lang=en ; what is missing is the hash character.

while accessing the /#/admin resource the redirect seems to happen correctly.

**Comment by hellais** [comment]
This is probably due to a misuse of the angular.js `$location` module.

**Comment by evilaliv3** [comment]
Yep I know thanks. I've fixed the bug and I will commit the code asap

**Comment by evilaliv3** [comment]
fixed!
