### ISSUE TITLE
Low flood detection threshold causes bad usability

### ISSUE THREAD

**Issue by calamarim** [globaleaks/GlobaLeaks#1235]
I connected with my unpublished GL site of  BBA via TB, that is for sure no flooded, but despite this

![screenshot from 2015-04-16 11 18 08](https://cloud.githubusercontent.com/assets/1076322/7177889/992c528e-e42a-11e4-9189-9f6a2e08e731.png)

the antiflood pose me a question
site  onion   4ulztymoocewpojo.onion
looks an important issue to me

**Comment by hellais** [comment]
This does indeed seem like a bug: @vecna any idea what is going on?

@calamarim can you look inside of the admin interface at the statistics tab and check to see if there are some anomalies detected?

**Comment by evilaliv3** [comment]
i will raise down the current threshold that seems too low and i will push out the fix in few days when finishing with other small bugfixing.

**Comment by evilaliv3** [comment]
with previous commit i've relaxed the testing threshold of more than one order.
this would be enough to not cause problems on real users while testing the goodness of the implementation.
