### ISSUE TITLE
File uploader give no clue that user need to wait

### ISSUE THREAD

**Issue by calamarim** [globaleaks/GlobaLeaks#1236]
When submitting a tip containing a file, the file uploader icon is on the right and give no evident clue about the need to wait. The icin is on the righr, the message is small and 
The user will probably close the page or do something other disruptive for the submission.
Moreover, when upload is finished, the icon changes but the massage telling to wait remains
![screenshot from 2015-04-16 11 34 37](https://cloud.githubusercontent.com/assets/1076322/7178283/de9287dc-e42d-11e4-8c93-f676d5e8f544.png)

**Comment by hellais** [comment]
If you see a tick that means that they have completed to upload.

When they are being uploaded you should see a progress bar instead of a tick.

@calamarim Is that not the case?

**Comment by evilaliv3** [comment]
I agree that the interface could show more.

to do things better it would be interesting to integrate:
1) a loader bar for the single file upload (based on the chunck uploaded in respect to the total chunks)
2) if possible a global loading bar in relation to the (based on the chunck uploaded in respect to the total chunks)
3) Change the texts of the ui from "Uploading files..." to "Uploaded files" when the upload of the files have been completed and viceversa.

@calamarim do you think this would be enough to solve the issue?

**Comment by evilaliv3** [comment]
This ticket can be closed as the features described above have been all implemented.
