### ISSUE TITLE
typo in wiki/Installation-guide

### ISSUE THREAD

**Issue by cortesimone** [globaleaks/GlobaLeaks#1237]
here https://github.com/globaleaks/GlobaLeaks/wiki/Installation-guide

there are supposedly 2 typos:
- curl instead of wget in apt-get install line
- the page is said to be "all rights reserved"
##

**Comment by evilaliv3** [comment]
thanks @cortesimone 

I noticed the curl mention error while showing the page at the workshop! :)
in past we used curl; now that we use wget there is also no need to install it.

and great that you noticed that the globaleaks is said since ever all right reversed instead of reversed. :)

**Comment by evilaliv3** [comment]
ah no!
 obviously the reversed work was intentiuonally in the initially start of the project in order to clarify our vision on copyright (copyleft): https://en.wikipedia.org/wiki/All_rights_reversed

@fpietrosanti maybe we can write something totally different in the footer of the wiki?

in the meantime i've fixe the curl/wget issue

**Comment by fpietrosanti** [comment]
@cortesimone @evilaliv3 Are there a problem in the "All rights reserved" clause? Is like in the source code with copyright statement of Hermes Center, where copyright attribution is a guarantee for the freedom of the AGPL licensing. 

Maybe, being documentation, we could explicitly define a free license such as FDL or CC?

**Comment by hellais** [comment]
"All rights re**v**ersed", nice touch :+1:

**Comment by cortesimone** [comment]
do you see what I mean? :)

"reversed" is easily misunderstood/misread

**Comment by hellais** [comment]
I think adding (ↄ) to the end of that text should fix this.

**Comment by cortesimone** [comment]
I know it is formally correct, and has been in use since 1985, but still, I think it is confusing.

**Comment by hellais** [comment]
@cortesimone confusion is fun, sometimes.

:confused:

**Comment by cortesimone** [comment]
It is totally up to you :stuck_out_tongue_winking_eye:
