### ISSUE TITLE
Implement end 2 end tests for GLClient

### ISSUE THREAD

**Issue by hellais** [globaleaks/GlobaLeaks#1240]
We should implement end 2 end tests (the unittest type not the crypto one) for everything that is in:

https://github.com/globaleaks/GlobaLeaks/tree/feature/end2end/client/tests/glbackend/

**Comment by evilaliv3** [comment]
I would suggest to follow the following order for the test that would give a good coverage.

1) clean setup interface test
2) completion of the wizard
3) test on the data expected after the wizard
4) configuration by the admin
5) first login of the receiver, password change, generation of the end to end key and encryption with the password
6) submission by the whistleblower completing fields and loading files (this would test encryption of fields and files)
7) login of the receiver, access to the tip list, access to the tip and files (this would test deryption of fields and files)
8) submission by receiver of comments and private messages (this would test encryption from receiver side)
9) access by the whistleblower to the tip using the receipt of point (6), reading of comments of point (8) and usage of the functionalities of the tip status page: attachment of new files, comments, private messages (this would test post submission operations and encryption)
10) access by the receiver testing the postpone and tip deletion features

this represents for me the basic testing to be implemented  and that would at least cover all the end2end features that would be critical for the testing of the end2end implementation from the point of view of browser compatibility.

**Comment by origliante** [comment]
@hellais continuing the work of @vecna I'm working on this:
https://github.com/origliante/GlobaLeaks/commit/506889d3c0270b498458245538d59fe25ce555d9

are you skilled on protractor?

**Comment by evilaliv3** [comment]
closing this ticket as  all has been reviewd and finalized and all is in place on devel branch
