### ISSUE TITLE
It should be possible to reset to default the fields of a context

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1241]
It has been requested by IRPI to have the possibility to reset fields of a context to default.

This would be useful for two reasons:
- i would allow a globaleaks setup to renew translations for all default fields instantiated into a context without having the need to remove the context (and generally a context cannot be deleted without loosing current fields.
- it would allow a context to reset fields to current default in case of a wrong migration during updates. this issue has been verified on IRPI that has a really outdated instance and migration of fields was failing somehow; anyhow all the old adopters have used defaults fields so that this feature would help on such condition.

**Comment by fpietrosanti** [comment]
It would also allow to "improve" the existing default field-set, as we improve it in globaleaks with default, well done questionnaires

**Comment by evilaliv3** [comment]
yep. defaults are already updated by default but they apply only to new context.
while this feature is specifically to reset the steps/fields of a context to the default.

**Comment by evilaliv3** [comment]
implemented.
