### ISSUE TITLE
Too many files, can't download

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1242]
It was reported in Mexicoleaks that a submission of 647 files can't be downloaded. Journalist say it was downloading for hours, but transference get stuck.

**Comment by evilaliv3** [comment]
i would say this is more a feature able to protect the receiver from been hijacked than a bug :)

anyway i will implement a unit test for this so to see the various problems on this side.

thanks @infosquatter

**Comment by evilaliv3** [comment]
closing this ticket as probably outdated.
