### ISSUE TITLE
possible bug in messages migration or UI interface 

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1247]
An adopter reported that he is not able to see some messages we received.

The issue may lie into a migration problem or into an UI issue ans should be investigated

**Comment by evilaliv3** [comment]
not reproducible. removing the milestone for now and leave the ticket open.

**Comment by fpietrosanti** [comment]
can be closed?

**Comment by evilaliv3** [comment]
yep i think so.
