### ISSUE TITLE
Evaluate removal of jquery

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1249]
In latest developement i've been able to remove any explicit use of jquery so that it would be interesting to evaluate it's removal as it represent 200kb of not used code.

we are currently using it for the following two things:
1) angularjs uses jquery if it finds it; instead if it not find it it uses a small implementation jqlite that they developed. i've not found any reference that clarify mee if it's better for compatibility reasons or not, but i do not think so (https://docs.angularjs.org/misc/faq)
2) we use it for the error messages fadeout implemented by @hellais

**Comment by evilaliv3** [comment]
most of my work on this topic is tracked by commit: https://github.com/globaleaks/GlobaLeaks/commit/fd33586af13239d561c513147e9f67ea7d0368e2

**Comment by fpietrosanti** [comment]
Which is the problem in having jquery?

I do not see performance issues

**Comment by evilaliv3** [comment]
it's not a matter of having performance issues, it's a matter of including libraries not used at all and that wheight 200kb. i'm just questioning what is the reason to keep that?

**Comment by evilaliv3** [comment]
anyway this is totally not a priority, just question.

**Comment by evilaliv3** [comment]
Jquery is dead since a while!
