### ISSUE TITLE
Error installing GlobaLeaks on Ubuntu 14.04 "Depends: python-pip but it is not installable"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1254]
On Ubuntu Python 14.04 i got the error "Depends: python-pip but it is not installable" while installing GlobaLeaks.

The error is because the multiverse repo is missing:
https://forum.sourcefabric.org/discussion/11460/package-dependency-errors-on-1-8-2-install/p1

The fix, only on Ubuntu 14.04 and newer, is to add it with the following command line:
apt-add-repository multiverse && apt-get update

The pre-requisite to use "apt-add-repository" is to install "software-properties-common" .

This happen on Ubuntu 14.04 that has been installed as "Minimal" .

All this procedure works only on Ubuntu 14.04 and above and shall be integrated into the installation script:
If Ubuntu =>14.04
  If there's not multiverse repository in APT
   then install software-properties-common 
   then execute apt-add-repository multiverse && apt-get update
fi
proceed_with_installation

**Comment by evilaliv3** [comment]
fixed!
