### ISSUE TITLE
Error in GlobaLeaks install on Ubuntu 14.04 when creating a Tor Hidden Srvice

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1256]
Current version of GlobaLeaks is broken on Ubuntu 14.04 because it does not automatically create a Tor Hidden Service.

The error given is related to Tor not being able to create the TorHS:
Apr 30 06:49:33.000 [notice] Tor 0.2.4.20 (git-0d50b03673670de6) opening log file.
Apr 30 06:49:33.000 [warn] Couldn't open "/var/globaleaks/torhs//private_key.tmp" (/var/globaleaks/torhs//private_key) for writing: Permission denied
Apr 30 06:49:33.000 [err] Couldn't write generated key to "/var/globaleaks/torhs//private_key".
Apr 30 06:49:33.000 [warn] Error loading rendezvous service keys
Apr 30 06:49:33.000 [err] set_options(): Bug: Acting on config options left us in a broken state. Dying.

Trying now to make a diagnosis

**Comment by fpietrosanti** [comment]
The permissions was all OK. This issue disappeared after a reboot.
The very same issue has been reported on http://tor.stackexchange.com/questions/4510/i-have-my-custom-url-private-key-and-hostname-but-tor-wont-serve-it .

There's no clear indication of what's the problem

**Comment by evilaliv3** [comment]
i know the issue.
tor is installed as dependency of globaleaks and when it starts the directories of globaleaks (/var/globaleaks/torhs) are still not created and so this error is scattered.
while after the reboot globaleaks has rightly created the dirs so noerror is raised.

i'm going to fix this issue creating the directories before starting tor. obviously i will add this code while not removing existent one releated to globaleaks checks for creation/permissions at startup.

**Comment by evilaliv3** [comment]
got the issue, apparmor should be restarted before starting Tor or Tor would not be able to write the key.

**Comment by evilaliv3** [comment]
fixed and retested on the OTF cloud both for trusty and for wheezy.
