### ISSUE TITLE
ETA/progress bar on uploading

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1257]
I noticed the ETA/progress bar on uploading process was changed by this "uploading/uploaded" icon. I strongly suggest to use some kind of ETA visualization. 

The current interface is not intuitive at all, you don't know if the file is really uploading, if there was an error, what is the estimate time of the process etc.

**Comment by evilaliv3** [comment]
thanks for the feedback @infosquatter 
we are working on that as we have recently updated the uploading library in order to be able easily to implement end-to-end encryption and this new library does not offer a progress bar natively.

**Comment by evilaliv3** [comment]
Implemented!

![upload](https://cloud.githubusercontent.com/assets/217034/8279416/c406035e-18d4-11e5-832e-7f5fe5be7ff5.png)

**Comment by evilaliv3** [comment]
and here goas the massive improval! check it out!

![1](https://cloud.githubusercontent.com/assets/217034/8280311/7df79a6e-18dc-11e5-85d6-baeb571eb9bb.png)
![2](https://cloud.githubusercontent.com/assets/217034/8280312/80b697aa-18dc-11e5-897d-a43143fc2a20.png)
![3](https://cloud.githubusercontent.com/assets/217034/8280314/833d4f78-18dc-11e5-97ae-0c8ab10c58f2.png)

**Comment by infosquatter** [comment]
Yes, it is great. I think it can be closed! Thanks!
