### ISSUE TITLE
Add in InternalTip information on the kind of security used by WB

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1260]
As discussed with @infosquatter, an evaluable information is the security level of the WB at the time of the submission.

We can store in InternalTip a boolean, based on the presence of X-Tor2Web or not. This information can be useful for two reasons:

  * stats about Node usage, KPI over anonimity advocacy, general consideration of T2W usefulness 
  * understand the risks of the WB and perhaps offer more appropriate suggestion. 

What do you think about ? @evilaliv3 @fpietrosanti @hellais has to be done in the next DB update.

**Comment by fpietrosanti** [comment]
I suggest to integrate this bit of information (tor/tor2wb) as part of #1188 (requested by publeaks)

**Comment by evilaliv3** [comment]
yep i find this useful and yep let's add it to internaltip as i don't consider ricky store that info in cleartext.

what do you think?

**Comment by infosquatter** [comment]
I agree on adding it to the internaltip, since this data is useful for
journalistic cross-check investigation!


Giovanni Pellerano:

**Comment by hellais** [comment]
I think this has some value, but I would also evaluate the possible security implications it could have.

In particular I am thinking that it may not give plausible deniability to the operator of the tor2web node (or to the WB for that matter).
The scenario I am thinking of is:

* GL Node get's siezed or somebody with credentials to view the InternalTip flag gains access to which submissions (and at what time) were not submitted via Tor

* They then coerce the tor2web operator (or sieze it or obtain it via legal means) to have the access logs for the time period in question

* The IP address of a whistleblower is revealed

This is also possible without this flag present, but adding it makes it a little bit easier to do (and more accurate).

**Comment by infosquatter** [comment]
That is true. Can the tor2web logs be disabled by default? Maybe there
should be a 'Globaleaks configuration standards' for tor2web?

Arturo Filastò:

**Comment by fpietrosanti** [comment]
@infosquatter Tor2web have not logging enabled by default

**Comment by vecna** [comment]
Implemented view in single Tip page + handler + patched the TEST (but not developed a dedicated test)

**Comment by evilaliv3** [comment]
reviewed in https://github.com/globaleaks/GlobaLeaks/commit/f924ec603e230104ebd5924a3a4b2a8653422587 and now merged into devel.
