### ISSUE TITLE
Contribution guidelines should be written in CONTRIBUTING.md

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1263]
The projects is currently missing the CONTRIBUTING.md file with the list of "rules" and suggestions to be followed by contributors.

It would be valuable to write down here the various good notes with reference to:
- code style
- unit testing
- ...

Valuable contributiing guidelines to be read as good example:
https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md
https://twistedmatrix.com/trac/wiki/ContributingToTwistedLabs

And here is an example of how github suggest users to read contributing guidelines when opening new issues and pull requests:
![screenshot from 2015-05-09 13 07 46](https://cloud.githubusercontent.com/assets/217034/7549961/8e48da9c-f64d-11e4-8635-ba466fb6871c.png)

**Comment by hellais** [comment]
+1

**Comment by vodkina** [comment]
Contributing To GlobaLeaks

There are many ways individuals and organizations can contribute to GlobaLeaks.

As many open source projects, GlobaLeaks benefits from the volunteer effort of the community. The more the help, the better is the software, its localization and its documentation.

You can contribute to GlobaLeaks in different and all welcomed ways:

• Coding
More info on this subject at https://github.com/globaleaks/GlobaLeaks/wiki#software-development

• Spotting security flaws: GlobaLeaks bounty program
Anonymous whistleblowing can be easy and secure. Unfortunately, no technology is perfect and GlobaLeaks believes that working with skilled security researchers across the globe is crucial in identifying software weaknesses.
While we do our best to provide a secure software by default, security vulnerabilities and new attack techniques must be taken into account. If you believe you've found a security issue in the Globaleaks framework codebase, we encourage you to participate in our bounty program [https://hackerone.com/globaleaks] hosted by Hackerone [https://hackerone.com]

• Translating
GlobaLeaks software is currently localized and internationalized in more than 20 languages.
The work on translation is performed in collaboration with the Localization Lab [http://www.localizationlab.org/] and with help of the Transifex volunteers community.
To read more on how translation is performed and you you could help on this side visit the Localization Lab guidelines [http://www.localizationlab.org/translator-getting-started-guide].

• Donations
To support GlobaLeaks Project you can help us with donations that will goes entirely for the software development and localization!

	• Bitcoin [https://www.globaleaks.org/bitcoin.html]
	• PayPal [https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=%2022CAHH6GRRCTC]
	• Subscription [https://globaleaks.org/paypal.html] 
	• Flattr [https://flattr.com/submit/auto?user_id=GlobaLeaks&url=https://github.com/globaleaks/globaleaks&title=GlobaLeaks&language=en&tags=github&category=software]

**Comment by evilaliv3** [comment]
@vodkina: https://github.com/globaleaks/GlobaLeaks/blob/devel/CONTRIBUTING.md

done!

it's already on the devel branch and github will start using it as it will land in master.

**Comment by evilaliv3** [comment]
DONE!

![screenshot from 2015-12-21 00 55 24](https://cloud.githubusercontent.com/assets/217034/11921000/d31d8f14-a77d-11e5-9d41-ac622875e5dc.png)

i leave this open and i will close it when integrated with some guidelines on coding.

**Comment by evilaliv3** [comment]
done!
