### ISSUE TITLE
Evaluate integration of Hund in order to track javascript code quality on commit

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1264]
I'm evaluating the use of [Hound](https://github.com/thoughtbot/hound) for the tracking of the javascript code quality on commit.

it's seems a nice tool that simply perform jshint but currently ask for really heavy permissions on the repo, that would allow them to do whatever they want like editing the wiki and even committing.

i'm now going to open an issue on their ticketing system in order to support them in setting the permission request accordingly to their real need.

the following is a screenshot of the currently required permissions:
![screenshot from 2015-05-09 21 22 10](https://cloud.githubusercontent.com/assets/217034/7551700/98948c76-f693-11e4-80a0-14ad812a2e72.png)

**Comment by hellais** [comment]
Much third party, no privacy, wow.

![MEME](https://imgflip.com/i/lv2oo)

**Comment by fpietrosanti** [comment]
I love the the cloud. Why don't clone the repo automatically to use Hund on an ad-hoc repo?

**Comment by evilaliv3** [comment]
outdated; we are using codeclimate and i'm currently satisfied of it! :)

**Comment by fpietrosanti** [comment]
Those are not competing afaik, hound check style and insert comment on style violation while codeclimate check quality and security

**Comment by evilaliv3** [comment]
https://docs.codeclimate.com/docs/list-of-engines
