### ISSUE TITLE
Evaluate integration of CodeClimate in order to track oth python and javascript code quality on commit

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1265]
I'm evaluating the use of [CodeClimate](https://codeclimate.com) for the tracking of the both python and javascript code quality on commit; the python analysis is a new feature now in beta that they have enabled from few time: https://codeclimate.com/changelog/5527d990e30ba006c1001032

it's seems a nice tool that simply perform a lot of interesting analysis but currently ask for really heavy permissions on the repo, that would allow them to do whatever they want like editing the wiki and even committing.

i'm now going to open an issue on their ticketing system in order to support them in setting the permission request accordingly to their real need.

the following is a screenshot of the currently required permissions:
![screenshot from 2015-05-09 21 56 41](https://cloud.githubusercontent.com/assets/217034/7551863/9092f788-f698-11e4-97e8-3d295f453ad0.png)

**Comment by hellais** [comment]
![NOSECURITY](https://i.imgflip.com/lv2oo.jpg)

**Comment by evilaliv3** [comment]
i agree with with the doge; let's see if they will change permissions in the future.

**Comment by fpietrosanti** [comment]
If the product it's useful please let's use it by setting up a "bitch repository" with automatic cloning from the real one.

When a technology is good and valuable and the code is public, there's no privacy issue if you don't care about data integrity.

**Comment by evilaliv3** [comment]
i don't like granting people the power for forcepushing on globaleaks embedding code inside it without us not noticing it.

obviously github can do the same, but it has more eyes on it.

**Comment by evilaliv3** [comment]
and in general i do not trust a project that set wrong permissions in general due to ignorance on the matter.
