### ISSUE TITLE
Integrate Travis-CI notification of failed test to IRC

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1268]
This ticket is to Integrate Travis-CI notification of failed test to IRC to irc.oftc.net #globaleaks channel.

The configuration to be done is at:
http://docs.travis-ci.com/user/notifications/

**Comment by evilaliv3** [comment]
Duplicated: https://github.com/globaleaks/GlobaLeaks/issues/1172
