### ISSUE TITLE
Adopt Mailinator as mailbox for unit testing

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1273]
A perfect solution for implementing unit testing of the email would be [Mailinator](https://mailinator.com/).

Mailinator could be used for:
- as simple mailbox for every receiver created (e.g. globaleaks-receiver1@mailinator.com)
- as simple mailbox for the admin user (globaleaks-admin@mailinator.com)
- as simple mailbox for the exception mail used in tests (globaleaks-exceptions@mailinator.com)

in addition thanks to the [Mailinator API](https://mailinator.com/apidocs.jsp) implemented in Node.js and in Python it would be easy to implement some rest of the mail rourtines.

**Comment by vodkina** [comment]
Go for it!

**Comment by evilaliv3** [comment]
Checking if mail will be received would be easy and fast even manually:
- [Laura Poitras](https://mailinator.com/inbox.jsp?to=laura.poitras)
- [Glenn Greenwald](https://mailinator.com/inbox.jsp?to=glenn.greenwald)
- [GlobaLeaks Admin](https://mailinator.com/inbox.jsp?to=globaleaks-admin)
- [GlobaLeaks Exceptions](https://mailinator.com/inbox.jsp?to=globaleaks-exceptions)

**Comment by evilaliv3** [comment]
here we go!
