### ISSUE TITLE
Application links should be relative to the globaleaks url

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1275]
It has been reported by OCCRP that in ther integrated mode implementation various links are not working properly.

e.g. the links that from the tiplist page point to the specific link are not working.
they are https://occrp.org/#/status/tipID while they should be https://occrp.org/occrpleaks/#/status/tipID

**Comment by evilaliv3** [comment]
@fpietrosanti/@vecna the only way to handle this would be to implement links in javascript openLocation(angular relative url). 

what do you think?

**Comment by fpietrosanti** [comment]
@evilalive dos this problem would be fixed and/or make it easier to be fixed by implementing #1130 ?

**Comment by evilaliv3** [comment]
not at all;

pushing both in current milestone and discussing with @vecna the change.
it would be interesting to study this basic html capability: http://www.verdantrefuge.com/writing/2013/angularjs-changing-app-path-base-element/

it would be really helpful then to replicate this funny configuration on travis and make the tests run against it.

**Comment by evilaliv3** [comment]
here we go my darling @fpietrosanti: i mangaged to make it work on https://127.0.0.1:8080/a/n/t/a/n/i/ !!! 

![screenshot from 2015-05-18 22 21 51](https://cloud.githubusercontent.com/assets/217034/7689593/cda9a880-fdad-11e4-938f-6cf763a0e901.png)
![screenshot from 2015-05-18 22 22 35](https://cloud.githubusercontent.com/assets/217034/7689598/d79cec94-fdad-11e4-905a-f08137b99853.png)
![screenshot from 2015-05-18 22 27 22](https://cloud.githubusercontent.com/assets/217034/7689603/de85cb70-fdad-11e4-9be6-271e7e47590d.png)
![screenshot from 2015-05-18 22 27 27](https://cloud.githubusercontent.com/assets/217034/7689608/e4717228-fdad-11e4-9eda-7b768fff21a0.png)

as you can see now all urls are relative to the script.js file
so that if the reverse proxy can serve the app at http://www.funnyurl.org/sim/sa/la/bim globalleaks will work properly and magically!

e.g. i made it work with this simple reverse proxy implemented with two lines of node:

    var proxy = require('redbird')({port: 8080});
    proxy.register("localhost/a/n/t/a/n/i/", "http://127.0.0.1:8082");
