### ISSUE TITLE
Evaluate the use of HTML5 mode for locations

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1276]
In relation to https://github.com/globaleaks/GlobaLeaks/issues/1130 and https://github.com/globaleaks/GlobaLeaks/issues/1275 i found that it would be probably valuable to use the HTM5 location mode: https://code.angularjs.org/1.2.27/docs/guide/$location

this would permit to provide better user experience in relation to the history of the navigation and probably would offer more features.

this special mode is available obviously only on HTML5 browser but we are supporting only HTML% browser so i would find useful to use this feature also.

\cc @vecna @hellais @fpietrosanti : what do you think?

**Comment by fpietrosanti** [comment]
I don't understand how it's better for the end-user. What would change for end-user for example?

Btw if it's better, i'd consider checking the w3c accessibility stuff, if it change something in good or bad for #811 and #809

**Comment by evilaliv3** [comment]
its seems that would be canoninical urls without the # and the user will be able to benefit of the history.

**Comment by evilaliv3** [comment]
i studied better and i do not consider this useful at all.
