### ISSUE TITLE
DISABLE_MAIL_TORIFICATION from /etc/default/globaleaks does not work

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1278]
If you try to setup globaleaks with  DISABLE_MAIL_TORIFICATION in /etc/default/globaleaks set to 1 the platform will not start with the following error:
# DISABLE_MAIL_TORIFICATION = [0/1]
DISABLE_MAIL_TORIFICATION=0

root@ubuntu2:~# /etc/init.d/globaleaks start
 * Starting GlobaLeaks daemon globaleaks
 * Enabling GlobaLeaks Network Sandboxing...
   ...done.
 * Enabling GlobaLeaks Apparmor Sandboxing...
Usage: globaleaks [options]

globaleaks: error: no such option: --disable-mail-torification
   ...fail!

**Comment by evilaliv3** [comment]
the parameter was written wrong inside the init script;
in addition also the parameter inside /bin/globaleaks had not an uniform name with the others.
