### ISSUE TITLE
Update API Architecture document

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#128]
Currently the web page of API specification is very out-dated:
https://github.com/globaleaks/GlobaLeaks/wiki/API-Specification

This ticket is to update the document of API specification or to drop it and replace it with information on how to understand/know the various API looking directly at code files.
##

**Comment by evilaliv3** [comment]
The API is dead, long dead to the API.

Given the specialization of the current client all API documentation is postponed to an eventual later stage.
