### ISSUE TITLE
Enable Tip interface where there's only Private Messages without "Additional Information"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1284]
Enable Tip interface where there's only Private Messages without "Additional Information" .

This should be a configuration in the context that does not show "Additional Information" (the old comments) but only leave the Private Messages available.

**Comment by evilaliv3** [comment]
it's now possible to indipendently enable/disable both Privated Messages and Additional Information (Comments)  so that this ticket can be closed.
