### ISSUE TITLE
When a field of type checkbox is mandatory, it's now shown in the submission interface that's mandatory like for text field

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1285]
When a field of type checkbox is mandatory, it's now shown in the submission interface that's mandatory like for text field.

This ticket is to show the red text "This field is mandatory" also for checkboxes field when those are marked as mandatory.

**Comment by evilaliv3** [comment]
here we go!

**Comment by evilaliv3** [comment]
d
