### ISSUE TITLE
Display a dynamic counter of the character that has been written in a text field, while being typed

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1287]
This ticket is to display a dynamic counter of the character that has been written in the text field, while being typed.

That's a UX improvement asked by ozivieni.

**Comment by evilaliv3** [comment]
@fpietrosanti can you better describe this feature request?

what is the exact aim of this?
i mean:
 - should it apply only to text areas or to every input?
 - should the counter be a countdown? if yes what should be the starting value if the textarea is not limited?
 - etc :) but please do not open tickets with "unicorn!" "but betterly define them as "i wanna be a unicorn with the possibility to fly and if i enconunter batman i wanna be able to do a rocket jump"

**Comment by evilaliv3** [comment]
![0](https://cloud.githubusercontent.com/assets/217034/8045975/a65b46fe-0e37-11e5-9f0b-f0c0dbdda140.jpg)

**Comment by evilaliv3** [comment]
DB support added in commit: https://github.com/globaleaks/GlobaLeaks/commit/614ae061d0d3a29f2d2e2dda9a1760011c5e6dbe

**Comment by evilaliv3** [comment]
This ticket was overllapped with https://github.com/globaleaks/GlobaLeaks/issues/1351.

both have been addressed and the solution is described on the other ticket.
