### ISSUE TITLE
It should be possible to reorder submission steps inside contexts

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1288]
It should be possible to reorder submission steps inside contexts.

This currently represent a big limit of the steps implementation as a user should already know the order of the steps when creating them (in order) and without any possibility to change that order without recreating them all.

This known issues has been recenlty reported by Virtualroad while customizing the platform for one of its customers.

**Comment by fpietrosanti** [comment]
Applying label "A: VirtualRoad" to track request from a specific adopter

**Comment by evilaliv3** [comment]
![screenshot from 2015-06-10 16 26 32](https://cloud.githubusercontent.com/assets/217034/8084899/b9c88600-0f8d-11e5-8969-ab22df30a71e.png)
![screenshot from 2015-06-10 16 26 43](https://cloud.githubusercontent.com/assets/217034/8084904/bd7f0b48-0f8d-11e5-8469-2b60c4e69e60.png)

okay the feature is in place, what it's missing is simply the migration script integration.

@hellais as you can see the card is changed to be full with (for steps only); this is due to the fact that ng-sortable does not seem to me to behave so well so that whenever possible i prefer to have a draggable that move only over row and not columns.

**Comment by evilaliv3** [comment]
completed!
