### ISSUE TITLE
Quality Assurance report before move the current 'devel' in 'master'

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1294]
Some minor bug spotted:

  * angular-sanitize (fixed by @evilaliv3 )
  * Exception below:

        File "/home/xx/Dev/GlobaLeaks/backend/globaleaks/plugins/notification.py", line 76, in get_mail_body_and_title
        raise NotImplementedError("This event_type (%s) is not supported" % event.type)
        NotImplementedError: This event_type (receiver_notification_limit_reached) is not supported

  * the Template in Anomaly detection (screenshot below):
 
**[removed - because was containing some unexpected data in the screenshot :P ]**

**Comment by vecna** [comment]
This debug line is very confusing :P 

       2015-06-13 01:03:15+0200 [D] List of event 30 after the filtering process is 2 long

**Comment by evilaliv3** [comment]
from what i see there are two things to see:
1) why %NodeName% is not replaced
2)  you dont't have receiver_notification_limit_reached; maybe you are still using an builded client? have you removed the build dir?

**Comment by vecna** [comment]
no the error 2 is already resolved, was a renaming issue. I'll commit ASAP. 
the email, has two errors: also the number of file and submission are reported as the same, but they are not.

Plus:

2015-06-13 01:02:31+0200 [D] Received key proof_of_work, Unexpected in the template:
2015-06-13 01:02:31+0200 [D] ['context_id', 'human_captcha_answer', 'receivers', 'wb_steps']

If Token serialize proof_of_work, I've to keep in rest/requests

**Comment by vecna** [comment]
This has been optimized for the *lazy evaluation*:

-            if event['handler_check'](self.request.uri) and \
-                            event['method'] == self.request.method and \
-                    event['status_checker'](self._status_code):
+            if event['status_checker'](self._status_code) and \
+                   event['method'] == self.request.method and \
+                   event['handler_check'](self.request.uri):

**Comment by vecna** [comment]
Not yet addressed: receiver preferences, if you enable ping notification, you can change the email but ping_notification boolean do not seem updated in the UI.
