### ISSUE TITLE
its possible from the admin to mark a "File Upload" field as preview but the implementation is missing

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1297]
Is it possible from the admin to mark a "File Upload" field as preview.

The receiver interface cannot preview file upload in preview, so it must be visualized somehow (list of files?) or it should not be possible to mark a file upload field as preview.

**Comment by evilaliv3** [comment]
in the short term suggest to go for the second option, removing the possibility to mark the field as visible in preview.

in fact due to the small space i do not see any kind of good preview to proivide and the number of files is already shown and is more than enough for current preview.

**Comment by evilaliv3** [comment]
the same currently apply to fields of type fieldgroup
