### ISSUE TITLE
"Multiple answer accepted" in field editing must be available only for multi-select

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1300]
Currently, while editing fields in the admin interface, it's possible to enable "Multiple answer accepted" also for select-box (for example).

The "Multiple answer accepted" in field editing must be available only for the field that support it.

**Comment by evilaliv3** [comment]
Currently the only field type that accept such a configuration is the fileupload so that i've hidden the checkbox for all the other fields types.
