### ISSUE TITLE
When creating a new field in a step, the last added should be the last in the index

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1301]
When creating a new field in a step, the last added should be the last in the index.

Actually it's ordered with a unpredictable logic, to be checked, but user expectation is that last added, will be the last in the order.

**Comment by evilaliv3** [comment]
The issue does not apply simply to fields but also to:
1. steps
2. contexts
3. receivers

and whenever we will make possible to reorder also fields options it will apply also to them.
