### ISSUE TITLE
Cannot create field with title longer than 159 characters

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1302]
While trying to create the a field of type selectbox with the following title "Have you made any complaint about the offence to any judicial, prosecutorial, law enforcement authority or any NGO, international organisation or other group?" it's possible to add it.

Also after increasing the text size limits in the admin interface from 128 to 512, it's not possible to add it.

**Comment by evilaliv3** [comment]
the issue apply to each field type, and not only to selectboxes. and it apply to their titles not to descriotion, so that i've modified the issue title.

**Comment by evilaliv3** [comment]
the issue lied in the usage of data-ng-maxlength instead of the simple maxleght as used in all the application.
