### ISSUE TITLE
Evaluate usage of Base64 encoding for storing recevier and node images inside the db

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1303]
Given that the images of the receiver and of the node are really small and given the current limit we have serving simply images in png format it would be interesting to evaluate to use a base64 encoder in order to save images in the db. this could be done clientside in a compatible fashion and would allow to accept file upload limiting that simply by file extension and file size ( with a not critical filtering done clientside).

with this idea i would like to solve few issues:
1) starting to move all that is possible to db (and node images and receiver images are expected to be small and trusted)
2) making possible to serve those image inside the api; this would limit the round trip times)
3) make possible to load/serve multiple images file types; currently a lot of admins ends in loading .jpg files that are saved by us as png files that result in a failure on every IE that in late jesus christ age 2015 is continuing to trust the file extensions instead of validating the file itself.

this could be done by using https://github.com/adonespitogo/angular-base64-upload that seems a valuable solution.

**Comment by vecna** [comment]
that's good! and we can return in a single REST all the required images, mixing the one required by node + receivers. 

can be modify by receiver, too ?

**Comment by evilaliv3** [comment]
I'm not so certain, i'm thinking if it would be possible for a user to inject an XSS or all would result in a stored XSS.

the feature would be really great and would simplify a bit the backend but we should verify that <img src=base4_user_data is safe from xss attacks.

**Comment by fpietrosanti** [comment]
We can ask to our friends at OWASP if a data:uri used in such scenario could be used to xss-ize us but i do think that The base64 decoder should be safe enough. We should additionally consider that only authenticated And authorized users can upload images of profiles

Sent from mobile

>

**Comment by ikkisoft** [comment]
If you're generating the Base64 server-side, I would say that it's safe - as long as it's only used for img tags and you're also forcing the content-type. As you can see with the examples below, the *a* tag would be vulnerable. The first *img* tag is vulnerable on specific old browsers (don't remember which one)

```html
<html>
<body>
<a href="data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTs8L3NjcmlwdD4=">ClickMe</a>
<img src="data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTs8L3NjcmlwdD4="/>
<img src="data:image/png;base64,PHNjcmlwdD5hbGVydCgxKTs8L3NjcmlwdD4="/>
</body>
</html>
```

**Comment by evilaliv3** [comment]
thanks @ikkisoft perfect! we are in possibility to do all that you are saying.

i was thinking to reduce an API removing the need for a file upload, but anyhow the only possibility to save the base 64 on the backend will reduce roundtrips when serving data that will be served in one single json.

**Comment by evilaliv3** [comment]
damn i was so happy and satisfied of implementing such a feature but today i woke up with a doubt: ok to serve the image in the same request of receivers, but how to deal with nodes with tons of receivers? e.g. publeaks that has  ~42 receivers? this will slow down completely the first loading of the submission interface.

**Comment by fpietrosanti** [comment]
You mean that's because of base64 encodind overhead? 

Pre-fetching is the Key to the kingdom!

Sent from mobile

>

**Comment by evilaliv3** [comment]
prefetching will happen anyhow, but if one goes fast to the submission page
it will wait for all the /receivers API to load that may take time.

written differently which should be the maximum allowed size for a
receiiver image loaded by the user?

**Comment by fpietrosanti** [comment]
@evilaliv3 I would not block uploading a big image, instead, i would instead apply a big warning on the admin interface that the total size of images of Receivers is XYZKB, that image of Receiver X and Y exceed maximum recommended size of YKB (50KB?) and without fixing it whistleblower may have  bad experience in slow-loading of the website.

That way an end-user (that's not capable of resizing an image) is not prevented from configuring it (it's not blocking while doing first configuration), but it's always alerted that he have to fix that issue.

**Comment by evilaliv3** [comment]
this does not solve the main issue that i've described: it's stupid to design an API that would serve 50 images while serving the description of 50 receivers.

what about instead making an API /receivers/images serving only but all the images?
this way one can first load the /receivers and then fetch all the images as a whole.

**Comment by fpietrosanti** [comment]
@evilaliv3 +1 (but we always have the issue of not displaying the submission interface with empty images of receivers for publeaks, so making a super-cool confort loader can be an approach, but 1 step at time)

**Comment by evilaliv3** [comment]
i would suggest to go for this design:

- /resources: new API serving as a whole /node, contexts, /receivers
- /receivers/imgs: new API serving all but only receivers images
- /receiver/::id_receiver/image: new API serving the precise receiver image
- the same as above for the PGP key

**Comment by evilaliv3** [comment]
gived the mixed changes I was requiring to implementing https://github.com/globaleaks/GlobaLeaks/issues/354 i decided to implement this feature.

i've skipped to do reasearch on base64 encoding on the client and done it on the bakend by means of 'import base64'
the current implementation does still support only PNG files (the client hardcode the PNG mime type for security reasons) but there are a lot of benefits:
- images are now delivered from rest API /node (deliver the logo), /contexts (deliver all images of contexts), /receivers (deliver all images of receivers; thanks to this the client should load definitely faster
- we have files on the db (this will be an experimentation, as it is possible that this would have too much impact on performances)
