### ISSUE TITLE
Submission form CSS problem

### ISSUE THREAD

**Issue by EsterVR** [globaleaks/GlobaLeaks#1309]
When creating a "step" in the submission form with a certain size (height actually), the buttons "Previous Step" and "Next step" are not visible (covered by footer). 

![ipi_submission_form](https://cloud.githubusercontent.com/assets/12279370/8292728/81cb299e-1931-11e5-8d64-e3d857e22bc7.png)

**Comment by evilaliv3** [comment]
as discussed privately with @EsterVR this does not represent an issue of globaleaks but a customization issue where the customized css was including old default css rules of previous release that this way are overriding some aspects of the sticky footer implementation.
