### ISSUE TITLE
Sometime email notifications for a new tip get sent twice

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1312]
Sometime email notifications for a new tip get sent twice, as it has been reported by Transparency International Italy and documented below.

The code handling the notifications should be properly inspected, adding integrity checks to prevent this behaviour from happening.

![cattura](https://cloud.githubusercontent.com/assets/770363/8329307/ac22f5e4-1a78-11e5-9883-5f2f97a6beea.JPG)
![cattura2](https://cloud.githubusercontent.com/assets/770363/8329308/adb206ca-1a78-11e5-887e-e49ddcfe919e.JPG)

**Comment by evilaliv3** [comment]
Not reproducible.

**Comment by fpietrosanti** [comment]
Because it's not reproducible it doesn't mean a bug isn't here. 
Is it possible to introduce some kind of light check that detect if such condition happen again, log it and notify us as an exception?

**Comment by vecna** [comment]
we check deeply, and still we lack of a proper logging system that support us in investigating bug.
