### ISSUE TITLE
It's not possible to download files bigger than 1MB

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1316]
It has been tested by TI-it that It's not possible to download files bigger than 1MB, that stack in the browser download.

Below screenshot of the issue

![cattura 1](https://cloud.githubusercontent.com/assets/770363/8350043/4e417dd8-1b22-11e5-8183-a09c7d19a6d4.JPG)

**Comment by vecna** [comment]
Bug confirmed in local..... .... that's has to be tested absolutely :(

![image](https://cloud.githubusercontent.com/assets/89555/8351940/4c6dab08-1b31-11e5-8b95-d89569ec3660.png)

**Comment by vecna** [comment]
Easy solution: download the .zip collection, that works despite the size.

**Comment by evilaliv3** [comment]
Bug spotted. Being out for a meeting I will fix it and release for tomorrow
early afternoon

**Comment by evilaliv3** [comment]
the problem was that theflow library by default was sending 3 chunks in parallel but due to the encrypted temporary files implementation we have we can't accept unordered chunks.

**Comment by evilaliv3** [comment]
done, release 2.60.83 is out and include the fix
