### ISSUE TITLE
Detect automatically possible performance issues of GlobaLeaks API handlers

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1320]
This ticket is to detect automatically possible performance issues, by having an automatic measurement of the handlers of API answering/processing time.

If the processing time goes above a defined time, trigger an alert email going to the admin of the node and to the exception-handler email at globaleaks.

This approach will detect automatically, in a real-life scenario usage (that cannot be tested with automated testing easily), if a performance issues will ever occur.

Described at https://github.com/globaleaks/GlobaLeaks/issues/1269#issuecomment-117023020 .

**Comment by evilaliv3** [comment]
This has been implement as part of 2015 milestone but i forgotten to update and close the ticket.
