### ISSUE TITLE
administrator can see file names

### ISSUE THREAD

**Issue by Taipo** [globaleaks/GlobaLeaks#1323]
There are some situations where a GL server may be administered by someone other than a receiver. In those instances, the receiver may not want the administrator to see meta data of leaks. The filenames are visible to an administrator via the files overview section.

Filenames themselves can be revealing about the content within. In the most extreme conditions, can in of themselves give away the identity of a leaker that has not taken the right precautions. 

Example:
`my_leak_by_alice_smith.pdf`

For a receiver this is of course ultimately an issue of trust with a leaker, however that same level of trust should not be automatically extended to the administrator for the following reasons:
- an administrator can be 'coerced' into unlocking their admin panel
- a GL server can be captured while logged into as administrator

So my proposal is to encrypt the file name with the receivers PGP key.
##

**Comment by vecna** [comment]
You right, that interface has been put (mostly) for debug and overview reason. has never been made a security assessment. now is under stabilization the **end to end encryption** capability, that kind of interface will completely change. 

We can also remove that thing you are asking, just tell us if is really urgent or important for you.

**Comment by fpietrosanti** [comment]
@vecna that's something that has to be configurable, because file names maybe required for some users. 

Btw consider that @Taipo deployment is blocked due to bug #1311 that cannot be fixed until we get completely rid of using Cookie that cannot be fixed until we fix #1233 as described on https://github.com/globaleaks/GlobaLeaks/issues/1233#issuecomment-98316656

**Comment by vecna** [comment]
@fpietrosanti we are going to make it configurable in the D2 anyway, not in this shape.

**Comment by evilaliv3** [comment]
As an update on the ticket, since one year or more sensible information has been removed from any web interface.

Metatata are anyhow still available on the filestystem and on the database and i will be possible to remove them just at the end of the implementation of the clientside encryption.
