### ISSUE TITLE
Design proper DB support for unencrypted submissions fields

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1326]
In order to support stats collection it would be important to design proper table for submission fields answers of  data marked to be subject to stats.

**Comment by evilaliv3** [comment]
@vecna / @hellais: with @fpietrosanti we where thinking to store data in a table like (submission_id, field_id, field_answer_id) by unrolling here all the data that is sent unencrypted (cause it will be marked as stats).

this by design in general would work only for qualified data that is less critical while any open question answer will be never stored that way but only.

do you have any concern or you suggest something different?

**Comment by fpietrosanti** [comment]
i'm fine

**Comment by evilaliv3** [comment]
implemented and merged in master since release 2.60.104
