### ISSUE TITLE
Can't add PGP public key to receiver profile

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1327]
[-] [ ] [Errno 28] No space left on device: &#39;&#47;dev&#47;shm&#47;globaleaks&#47;gnupg&#47;oFQ1fUCg&#39;

**Comment by evilaliv3** [comment]
hi @infosquatter thanks for reporting it. we have received some emails from a setup so that was your.

i will test if there are cases in shich /dev/shm is not emptied. in the meantime can you simply reboot the machine?) that would solve the issue; and let me know!

**Comment by evilaliv3** [comment]
the issue was that unfinished submissions were leading keys in the ramdisk for the uploaded files so days by days they were probably accumulating.
