### ISSUE TITLE
Critical (Submission near to be disabled)

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1331]
In the tip interface from the receiver side, all files are not available. There are no files at all at /var/globaleaks/files/encrypte_upload .

Log says:

2015-07-16 22:30:34+0000 [-] &#39;[!] Critical (Submission near to be disabled): Disk space permit maximum of 5 uploads (50GB on 39GB)&#39;

Still the machine has 37GB free space.

**Comment by fpietrosanti** [comment]
@vecna

**Comment by vecna** [comment]
Yo @infosquatter, that is appropriate. IRC you've 99999999 as "maximum file upload size" (admin -> advanced settings), therefore means that five submission can fill up your disk. If you put 500 megabytes ax maximum file upload, this alarm will disapperar (until you reach 2.5 gigabyte of space, 500Mb x 5)

**Comment by evilaliv3** [comment]
by the way @infosquatter if you simply update the node this kind of check has been removed so that you wont have any issue.

@vecna with @fpietrosanti we decided to go for the initial simple checks that where described by @fpietrosanti in https://github.com/globaleaks/GlobaLeaks/issues/297#issuecomment-74482518
in addition to the simple check of @fpietrosanti i've decided the adopt the concept of three thresholds with different meaning as you suggested HIGH, MEDIUM, LOW.

this way checks are more deterministic and independent from the setting of the user

current checks are:

```
    # list of bad conditions ordered starting from the worst case scenario
    conditions = [
        {
            'condition': free_disk_megabytes <= 300 or free_disk_percentage <= 3,
            'info_msg': info_msg_0,
            'stress_level': 3,
            'accept_submissions': False
        },
        {
            'condition': free_ramdisk_bytes <= 2048,
            'info_msg': info_msg_1,
            'stress_level': 3,
            'accept_submissions': False
        },
        {
            'condition': free_disk_megabytes <= 500 or free_disk_percentage <= 5,
            'info_msg': info_msg_2,
            'stress_level': 2,
            'accept_submissions': True
        },
        {
            'condition': free_disk_megabytes <= 1000 or free_disk_percentage <= 10,
            'info_msg': info_msg_3,
            'stress_level': 1,
            'accept_submissions': True
        }
    ]
```

**Comment by vecna** [comment]
eh ok, but this is blocking me :P 

       2015-07-27 11:20:12+0200 '[!] Fatal (Submission disabled): free_disk_megabytes <= 300 or       free_disk_percentage <= 3'
       2015-07-27 11:20:12+0200 [D] Switch in Disk space available status, 0 => 3
       2015-07-27 11:20:12+0200 [-] Switching disk space availability from: True to False

whatever, has to be done some command line switches.

**Comment by fpietrosanti** [comment]
@vecna do you have less than 300Mb free on your disk??

**Comment by vecna** [comment]
@fpietrosanti no, I just have less than 3% (my disk is always at 98% 99% of capacity)

**Comment by vecna** [comment]
option -A, take as argument 1, 2 or 3.

ignore the alarm level LESSER OR EQUAL the number specified.

**Comment by fpietrosanti** [comment]
@vecna https://www.youtube.com/watch?v=zOD1umMX2s8

**Comment by evilaliv3** [comment]
the user knows HIGH, MEDIUM, LOW so eventually use this codewords.

new hard disk then is tha way!
