### ISSUE TITLE
Improve GlobaLeaks to make it compliant with WAI-ARIA Accessibility Requirements

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1334]
In order to make GlobaLeaks suitable for use by Public Administration it should satisfy Accessibility requirements such as the WAI-ARIA ones http://www.w3.org/WAI/intro/aria.php .

This ticket is to use all the required ARIA accessibility features of AngularJS wth ngAria https://docs.angularjs.org/guide/accessibility and other accessibility requirements http://blog.shinetech.com/2014/11/26/getting-started-with-angular-and-accessibility/  and https://egghead.io/lessons/angularjs-using-ng-aria-to-automatically-improve-your-angularjs-accessibility

The WAI-ARIA compliance shall be put under automated testing as per #1333

**Comment by fpietrosanti** [comment]
Related also to #809

**Comment by evilaliv3** [comment]
the module ngAria has been included in commit: https://github.com/globaleaks/GlobaLeaks/commit/390233c1c1341229f9522a081fd7331837612c76

now angular should generate valid wai-aria attributes to all the dynamic content it generate in relation to ng-disabled/ng-if/ng-show/ng-repeat etc.

what is now missing is simply to the automated testing as by https://github.com/globaleaks/GlobaLeaks/issues/1333

**Comment by fpietrosanti** [comment]
@evilaliv3 is just the inclusion of ngAria module making all of the magic, or does it require "using ngAria" module to support WAI-ARIA with an overall interface review?

**Comment by evilaliv3** [comment]
as i've told you few times ngAria solves all that relates to the automatic fashion of angular.

for all the various manual aspects no automagic library would never exist.

le'ts keep ope the issue so as you will like :)

**Comment by vodkina** [comment]
Why this issue is open? Let's close this, as the module ngAria has been included in commit: 390233c since last  August.
Just keep the #1333 open, 'cause it's the issue referring to automated testing of WAI-ARIA.

**Comment by fpietrosanti** [comment]
But this ticket is not about integrating ngAria, but making GlobaLeaks compliant with WAI-ARIA that require *manual* testing / verification by someone that can test Accessibility compliance of the software.

In case change this ticket to this in "Integrate WAI-ARIA support library" and open a new one "Test and validate compliance with WAI-ARIA specification"
