### ISSUE TITLE
Still problem with jp(e)g

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1335]
It is reported that on July 6 2015 (after @DrWhax updated the software) the problem with .jpg repeated.

Mexicoleaks receiver says 3 jpg aprox. 200KB, 450KB and 400KB can't be visualized (come in blank) after download.

**Comment by infosquatter** [comment]
Obs: There was a .pdf in the same tip which can be opened normally after download. So it seems it's really a problem with the type of file and not with the submitted tip.

**Comment by evilaliv3** [comment]
@infosquatter please when open tickets report:

1. the version of the software
2. if possible a way to reproduce the bug.

without 2 nor 1 i'm unable to proceed on the issue that i'm not able to verify right now.

**Comment by infosquatter** [comment]
Thanks @evilaliv3:

1 -  GlobaLeaks: 2.60.76
2 - Can't be reproduced, sorry. The error seems to occur sporadically
and still we can't make a rule out of it.

Giovanni Pellerano:

**Comment by evilaliv3** [comment]
Ok.

That version included various issues in relation to the file upload. I'm
vonfideny that the latest one is fixed for what relate to this issue.
