### ISSUE TITLE
Rename "Receivers" to "Users" in the admin interface

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1336]
By introducing multiple roles for users (ie: like the custodian for the WB identity and maybe other roles), we are differentiating users into the system (there's not only "Receivers").

For that reason the Tab "Receivers" in the admin interface must be just named "Users", enabling a user role to be displayed in the list of users and to configured in the user profile (if it's a Receiver or a custodian or an admin).

**Comment by evilaliv3** [comment]
This would require different api and views to be created.
Infact currently there is only a view for receivers that uses the api /receivers that in an 	homogeneous shows only receivers.

If we will have different user maybe we should create a view users that will us an api /users

This is mostly needed for a programmatical reasons given the fact that in angular for sure we will have to manage this different objects with different arrays.

**Comment by fpietrosanti** [comment]
@evilaliv3 Let's keep away the admin and just keep there the Receiver Objects, calling them "Users" ? :)

**Comment by evilaliv3** [comment]
read man, please read!

in angular it's better to have resources uniform in order to be able to do some mapping from js to html using ng-repeat (basically FORs cycles); so that i will have to divide them in js while it will be probably more easily to have different API.

**Comment by fpietrosanti** [comment]
@evilaliv3 yes, but my point is that Receivers can be named to Users anyway in the interface, regardless of their JS objects implementation :)

**Comment by evilaliv3** [comment]
Im not with the implementation of this ticket as specified.

From what i'm designing with latest implementation the gergon should work this way:
- User: will be the generic user with associated a name, a password, a description, possibly a pgp key for noitifcations etc; all this variables will be generic and proper of each user role.
- Roles: the platform would allow to grant a user different roles (in the first implementation only one for KISS reasons but it will be easy to make the extent to multiple roles); this roles will continue to be called: Admin, Receiver, Whistleblower and Custodian (the new role that we are going to create).
