### ISSUE TITLE
Introduce a "Custodian" user for Whistleblower Identities

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1337]
It has been requested a feature to gives an option to a whistleblower to reveal his identity, without displaying it directly to the Receiver.

The Receiver shall be allowed to request an authorization to view it by motivating the request.

The authorization request that the receiver has to fill has to be configurable, with it's own information entity (internally managed as a group-field) from the web administration interface, so the admin can customize it according to it's meaning. By default a simple text form.

The Custodian will receive a notification that a new requests is coming from ReceiverName, with a reminder on how many pending requests are there.

The Custodian log-in and can see the list of all the requests pending as follow:
| ContextName | ReceiverName | SubmissionID | Date of Request | Motivation | <ACCEPT> <DENY>

If the Custodian deny the authorization, he must write a motivation and he motivation shall be an information entity like the "authorization requests", configurable. By default it's a simple text form.

The Receiver, at the action of Custodian ACCEPT/DENY, will receive a notification informing him that a request to access for SubmissionID on ContextName has been ACCEPTED or DENIED.

When the Receiver log-in he can see in the TipList for all the tip if the requests pending/approved or denied, sorting the Tips by those parameters.

Once opening a Tip the Receiver can see the "Whistleblower Identity information" box (from #185) if:
- indicate if whistleblower has provided his identity information or not
- if it has been provided
  - if authorization is required by policy and it has not yet been requested, provide "Request Identity" button
  - if authorization is not requested or authorization has been granted, just display it
  - if authorization request is pending, display the status of the request, the date of request and the motivation
  - if authorization request has been denied, display the status of the request (denied), the date of the request, the motivation of the request, the date of the response, the motivation attached with the response.

The Admin and the custodian can view and export a log of all the requests for authorizations that has been done and it's outcome, including the dates and the motivations.

The admin cannot see the motivation of the requests and motivations of rejections because those information are encrypted with the key of the custodian.

**Comment by evilaliv3** [comment]
mocked up in https://github.com/globaleaks/GlobaLeaks/commit/4fdb73a8ea23ca016b3935ea68a55ebebb481059

**Comment by evilaliv3** [comment]
@fpietrosanti: i'm sketching out the DB support needed for the IdentityAccessRequests feature that would allow a Receiver to ask access to the Identify of the Whistleblower safeguarded by the Custodian.

do you agree that this would be the schema that would allow to implement the feature as currently discussed?

```
class CustodianRequests(Model):
    receivertip_id = Unicode()
    custodian_id = Unicode()
    # internaltip = Reference(ReceiverTip.internaltip_id, ReceiverTip.id)
    request_date = DateTime(default_factory=datetime_now)
    request_motivation = Unicode()
    answer_date = DateTime(default_factory=datetime_null)
    answer_motivation = Unicode()
    answer = Unicode()   # 'pending', 'denied', 'allowed'
```

**Comment by fpietrosanti** [comment]
@evilaliv3 
Regarding data structure:
* Request motivation could also contain structured data, such as select-box and not only simple text-description. 
* The answer, shall also follow the very same approach of text + structured data selectors.

I think also about logging:
* A running log of all the requests done and it's outcome shall be available/visibile on the Tip of the receiver.

* A full log of all requests/responses shall be available to the Custodian and to the Admin (or shall we think to gives out a privilege to see the logs?)

**Comment by evilaliv3** [comment]
@fpietrosanti your ideas are so confused.
- the motivation as structured data: we are non implemening a form builder inside this feature; KISS my gosh.
- the answer should be evaluated by the system in 3 different simple ways: pending, allowed, denied as this is the only way that a button deny/approve may work.
- the log: ok, and the data stracture above described offer this possibility as one will have all te requests done by a receiver to the guardian.
- ok for the permissioons to access the logs.

your points opens for me two questions:
- a context should have assigned only a custodian or more?
- the request should be addressed to a precise custodian or to all and simply one of them should grant the tip?
- the request for access is attached to the tip or to the custodian; i mean if i change the custodian the new one should be able to validate the requests?

**Comment by evilaliv3** [comment]
All that relates to this ticket has been implemented as part of the 2015 October milestone.

The only thing missing it's the mail notification for the various events but specific tickets exists for this.
