### ISSUE TITLE
Enable configuring a minimum and maximum amount of text

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1338]
This ticket is to improve the submission fields for the default questionaries structure, introducing the ability to specify for text-fields the minimum and maximum amount of text to be written in.

This will enable to include default questionaries that separate:
- "What happened?" inquiry with a minimum of 50 and maximum of 200 characters
- "Describe your report with greater details:" inquiry with a minimum of 500 characters and a maximum of 5000

This ticket can be complementary to #1287

**Comment by evilaliv3** [comment]
DB support added in commit: https://github.com/globaleaks/GlobaLeaks/commit/614ae061d0d3a29f2d2e2dda9a1760011c5e6dbe

**Comment by evilaliv3** [comment]
Also the admin UI for the configuration part has been accomplished.

Its still missing the usage of this data on the submission interface but it will be done in ticket  https://github.com/globaleaks/GlobaLeaks/issues/1351 while dealing with the validation of the whistleblower input.
