### ISSUE TITLE
Unandled exception while performing SMTP TLS challengeResponse authentication

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1341]
It maybe a UTF8 related issue of the password, like per https://github.com/stephenmcd/mezzanine/issues/899 (that's another project with a similar error)

2015-07-27 19:10:44+0000 [ParserProtocol,client] &#39;[!] Exception mail! [1]&#39;
2015-07-27 19:10:44+0000 [ParserProtocol,client] Starting factory &lt;txsocksx.client.SOCKS5ClientFactory instance at 0x7fcfb3785908&gt;
2015-07-27 19:10:44+0000 [ParserProtocol,client] Unhandled Error
        Traceback (most recent call last):
          File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;log.py&quot;, line 88, in callWithLogger
            return callWithContext({&quot;system&quot;: lp}, func, *args, **kw)
          File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;log.py&quot;, line 73, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;context.py&quot;, line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;context.py&quot;, line 81, in callWithContext
            return func(*args,**kw)
        --- &lt;exception caught here&gt; ---
          File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;posixbase.py&quot;, line 614, in _doReadOrWrite
            why = selectable.doRead()
          File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;tcp.py&quot;, line 215, in doRead
            return self._dataReceived(data)
          File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;tcp.py&quot;, line 221, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;protocols&#47;tls.py&quot;, line 419, in dataReceived
            self._flushReceiveBIO()
          File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;protocols&#47;tls.py&quot;, line 389, in _flushReceiveBIO
            ProtocolWrapper.dataReceived(self, bytes)
          File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;protocols&#47;policies.py&quot;, line 120, in dataReceived
            self.wrappedProtocol.dataReceived(data)
          File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;protocols&#47;basic.py&quot;, line 571, in dataReceived
            why = self.lineReceived(line)
          File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;mail&#47;smtp.py&quot;, line 1063, in lineReceived
            why = self._okresponse(self.code,&#39;&#92;n&#39;.join(self.resp))
          File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;mail&#47;smtp.py&quot;, line 1466, in esmtpState_challenge
            self._authResponse(self._authinfo, resp)
          File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;mail&#47;smtp.py&quot;, line 1478, in _authResponse
            resp = auth.challengeResponse(self.secret, challenge)
          File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;mail&#47;imap4.py&quot;, line 4452, in challengeResponse
            response = hmac.HMAC(secret, chal).hexdigest()
          File &quot;&#47;usr&#47;lib&#47;python2.7&#47;hmac.py&quot;, line 72, in __init__
            self.outer.update(key.translate(trans_5C))
        exceptions.TypeError: character mapping must return integer, None or unicode

**Comment by evilaliv3** [comment]
I'm veryfying this issue in relation to the change of the default smtp server: https://github.com/globaleaks/GlobaLeaks/commit/c9e7020574ab8febddab5e09111f398a1ebb6d1b

I've now a clear idea of what is happening.
We store the smtp settings as unicode python types but some of the libraries used for authentication does not accept them.

i'm going to test the change to password = authentication_password.encode('utf-8'), that would anyhow preserve utf8 encoding.

**Comment by evilaliv3** [comment]
fixed!
