### ISSUE TITLE
In the fields vertical ordering, the field number is not rewritten according to its position

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1343]
In the fields vertical ordering, the field number is not rewritten according to its position and the "presentation order" can be duplicated. Tested while making OB

**Comment by evilaliv3** [comment]
fixed in commit: https://github.com/globaleaks/GlobaLeaks/commit/9e3d217320ced5637b3f743b45f033c85ed71e3e
