### ISSUE TITLE
Receiver limitation to be overcome

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1345]
Receivers should be able to:
- modify/update their own description
- see which email is associate to the notification account
- have written for which kind of operation has to contact the admin (changing photo, changing email, password recovery).
##

**Comment by fpietrosanti** [comment]
Applied GLC/GLB label, please apply appropriate OTF/Adopters labels

**Comment by evilaliv3** [comment]
this if implemented should be subject to an enabler to be enabled by the admin.

the risk in allowing to change eventually. the name, the description and the image in fact allows an user to impersonate other users so that eventually this changes should be moderated.

**Comment by evilaliv3** [comment]
related to: https://github.com/globaleaks/GlobaLeaks/issues/156

**Comment by evilaliv3** [comment]
This ticket can be closed as outdated and superseaded by:https://github.com/globaleaks/GlobaLeaks/issues/2271 and https://github.com/globaleaks/GlobaLeaks/issues/2272
