### ISSUE TITLE
When admin login the "Login" button should not allow consecutive multiple clicks

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1348]
When admin login the "Login" button should not allow consecutive multiple clicks, condition that trigger flood protection.

A feedback on progress of login operations, until the server gives back an answer, shall be provided
<img width="334" alt="screen shot 2015-07-30 at 1 57 10 pm" src="https://cloud.githubusercontent.com/assets/770363/8982556/0673832c-36c3-11e5-859a-c74645be8491.png">

**Comment by evilaliv3** [comment]
Ticket addressed.

Now login button is disabled for all admin/receiver/whistleblower login forms whenever a login action is in progress.
