### ISSUE TITLE
Mandatory indicator in the fields during submission must be done in a less invasive way

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1350]
Actually the *mandatory indicator* in the fields during submission is invasive, by the means that it add a written red text for each field.

When there are *a lot* of mandatory fields, it impact the visualization of the UX. 

This ticket is to represent a mandatory field in a less invasive way that's suitable for questionnaires with a lot of fields.

<img width="459" alt="screen shot 2015-07-30 at 2 36 37 pm" src="https://cloud.githubusercontent.com/assets/770363/8983201/804d1f5a-36c8-11e5-8f38-d7774910c74f.png">

**Comment by evilaliv3** [comment]
![screenshot from 2015-08-01 23 35 48](https://cloud.githubusercontent.com/assets/217034/9023694/9ce4c62e-38a6-11e5-94a3-16a8aab41169.png)

![screenshot from 2015-08-01 23 36 29](https://cloud.githubusercontent.com/assets/217034/9023695/a20341e4-38a6-11e5-9992-cf443a49b1e4.png)

and an other ticket goes!
