### ISSUE TITLE
Wrong security level detected in the InternalTip

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1355]
The submission has been made via Tor, but the WhistleBlower interface report **HTTPS** in green. I suggest to recycle the icons of Tor (onion, barred onion).

![image](https://cloud.githubusercontent.com/assets/89555/9412210/c8f96718-482a-11e5-8ea3-8cf6556856cf.png)

**Comment by evilaliv3** [comment]
this bug is already fixed in development version that will be releasedd by today or tomorrow.

**Comment by evilaliv3** [comment]
the check  was simply reversed.

**Comment by vecna** [comment]
Onion/NotOnion ? you like it ?

**Comment by fpietrosanti** [comment]
@vecna NotOnion it not significative for anyone outside the Tor environment. I would suggest:
- Encrypted (onmouseover: "The connection has been protected trough HTTPS")
- Anonymous (onmouseover:"The connection has been anonymized trough the Tor Anonymous Network")

That would explain the "properties" of the connection in a way that can be understood by a non technical person, with simplied terms and an on-mouse-over explaination.

**Comment by evilaliv3** [comment]
@fpietrosanti plase try to be aligned with what we already agree:
current popover text infact already exists and are great:

"The connection used to send this submission has been secured with HTTPS ensuring confidentiality."
"The connection used to send this submission has been secured with Tor ensuring confidentiality and anonymity."

the show word are "HTTPS" and "Tor"; given the technical information i'm ok to keep this.
I'm not ok in using "Encrypted" as it's meaningless, but eventually open to change if we want to adopt Confidential vs Anonymous

**Comment by fpietrosanti** [comment]
@evilaliv3 confidential vs. anonymous doesn't work for threat model that called them differently (ie: TI-it). If you want to keep technical acronym such as HTTPS and Tor it's fine, but IMHO would be better to use word that are not technical acronym (like "Encrypted" and "Anonymous"), explaining with the technical acronym inside the on-mouse-over description.

**Comment by evilaliv3** [comment]
ok for keeping HTTPS / Tor :P

Encrypted vs Anonymous does not say anything. i prefer a technical acronym (as also the word "Connection" is) and then have a good poopover as we currently have.

**Comment by vecna** [comment]
Onion / NonOnion is the same icon you see in the Tor Browser, and is the official identification of "you have used an anonymous connection". is the best way to communicate it.

https://check.torproject.org/torcheck/img/tor-off.png
http://img.softmonk.com/tor_icon.jpg

**Comment by fpietrosanti** [comment]
@vecna That way the "tor off" would have a negative significate for the end-user while the message should be neutral imho, without any good/bad significate (we have the privacy badge already for that).

**Comment by evilaliv3** [comment]
It is true, i tested in the released package and it seems that the connection is detected or shown wrongly.

**Comment by evilaliv3** [comment]
@vecna: got the point on the issue: i was testing only from the whistleblower side where the boolean tor2web is even not exported by the API :)

i will fix by:
- exporting tor2web flag on whistleblower API
- verifying that probably the usage of the boolean is simply reversed.
