### ISSUE TITLE
Rename "text" and "text area"

### ISSUE THREAD

**Issue by delvecchiodavide** [globaleaks/GlobaLeaks#1360]
I think the terms "text" and "text area" should be renamed in:

text -> text line
text area -> multiline text

This is a more admin friendly name.
If they cannot be renamed, we should add a brief description.

**Comment by evilaliv3** [comment]
got your point @delvecchiodavide 

i would suggest to go for:
single-line text input
multi-line text input

i'm going to ask to  a professional techie and translator that is helping us on this side.

**Comment by evilaliv3** [comment]
having asked to our  helper we agreed for:
- Single-line text input
- Multi-line text input

**Comment by evilaliv3** [comment]
chande and integrated in devel branch in https://github.com/globaleaks/GlobaLeaks/commit/fd9c2696b81686b55afdfe576ebe1aa3761313bd
