### ISSUE TITLE
Add a brief description for each item in "advanced settings"

### ISSUE THREAD

**Issue by delvecchiodavide** [globaleaks/GlobaLeaks#1361]
I propose to insert a brief description to each item present in the tab "advanced settings" in the admin interface.

Here is a brief description that I wrote to make the admin work more friendly.

Enable insecure configuration without PGP encryption:
This flag will enable the possibility to receive informations from the receiver without using PGP

Allow other websites to include the GlobaLeaks-platform inside iframes
Other website will be able to include a GlobaLeaks form using iframes.

Allow receivers to postpone expiration date of the tips
Every data sent from a whistleblower has a default expiration period. This option will enable a receiver to postpone the expiration period.

Allow receivers to delete tips
Enable a reiver to delete data sent from a whistleblower

Enable Ahmia publishing
Enable the possibility to find this site through Ahmia (the biggest search engine for Tor hidden services)

Disable the privacy panel
if you enable this, the "challange" popup that ask you about the capabilities of HTTPS will NOT appear.

Disable the security awareness panel
If you enable this, the "danger" label on the top of the homepage will NOT appear.

**Comment by vecna** [comment]
Is more or less what I started with #1258 ?

**Comment by evilaliv3** [comment]
well done @delvecchiodavide !

yes the issue is duplicated i'm moving the text provided by mergin them with the one written by @vecna and me on https://docs.google.com/document/d/10zRQ2VeaBzo5w1UWyq7Eka910NxFtq3hgyPqQWs8xBA/edit

i will then ask a review to professional techie and translator that is helping us on this side.
