### ISSUE TITLE
Enable delayed file upload "on submit"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1363]
This ticket is to enable delayed file upload to be executed only "on submit", to enable file upload to happen from the end-user perspective to happen "before the receiver selection" .

This behaviour must be configurable from the web administration interface on/off in advanced settings.
##

**Comment by vecna** [comment]
please clarify what is "on submit" ? on submit of what ? which event you are referring to ?

**Comment by evilaliv3** [comment]
with "on submit" we mean adding the possibility to upload all the files at the end of the submission.

this will be also a requirement for the end to end2end encryption so that i'm not confident that making this configurable would be a good idea.
in addition also the logic needed wont be so easy to be done so thet when done having to manage and maintain two workflows like this would be a big effort for us; let's go for not starting the upload as soon as the user selects the files but doing it only when he want to finalize the submission.

this is a big improvement also in the security of the platform where if the user does non request to finalize the submission he does not end in loading files on the server at all.

**Comment by fpietrosanti** [comment]
@evilaliv3 Moving all the files upload to the end, require having such an intermediate page that pop-up "on clicking submit" that display a progress of the submission being done in a nice way, with proper progress bar, informative messages, etc. 
It could be a re-work done in a similar way to the work by PubLeaks UX designer?

**Comment by evilaliv3** [comment]
i think so, and i think we can do it all inside the next Publeaks discussions as it is a requirement also of the publeaks project (given the fact that already they know that we will switch to end2end asap)

**Comment by marceloomens** [comment]
Yes, it's a requirement to defer uploads when end-2-end encryption is enabled perhaps, but for now it would be enough to start the upload in the background somehow and make the status available for display after submission. I'll leave it up to you to choose the best, most future-proof solution.

**Comment by evilaliv3** [comment]
This would be a requirement when the end2end encryption will be in place but anyhow is nothing that would impact now on Goldilocks design. They just have to keep this in mind.

**Comment by NSkelsey** [comment]
The current status of the discussion on this feature is that Flow JS supports the possibility to select multiple files and then at a later point upload them.

In this way when the Whistleblower is really ready to submit everything a submission uploading interface will submit the form and simultaneously perform the upload of all of the files in a atomic (well almost) fashion.

**Comment by evilaliv3** [comment]
@NSkelsey: that is not completely true.
Sorry if i was not clear while explaining:
- browsers actually allows one to handle the file upload as one prefer; they just pass you the file descriptor and then you do what you prefer with your timing.
- an example of this is the implementation in JqueryFileUpload
- flowjs automatically start uploading as the file is loaded but i think the patch is really easy and valuable for the whole project so i think i will start discussing it on the ticketing system of flowjs and then implement a patch there.

**Comment by fpietrosanti** [comment]
Do we need delayed file upload strictly due to browser crypto?

Sent from mobile

**Comment by evilaliv3** [comment]
not only.

1) The issue on the browsercrypto has been bypassed by blocking the user so the current implementation is safe and if the user see the interface for uploading files, it means that if he/she uopload a file the file will upload without issues. -> future optimization on this (not a priority) is to allow the user to choose the files before the key generation will have finished; this way the user won't face dead periods where he has to wait for the application, and eventually there will be a single dead period at the end for finishing to generate keys, encrypting, uploading.

2)The reason why we were thinking to this with @NSkelsey is that currently we have only a global proof of work on the submissions that prevent to complete the sumibssion but not prevent to make a DoS on the file upload function itself. If we want to apply the proof of work on every file upload we would need such a pause() capability on the file uploader.

**Comment by evilaliv3** [comment]
Closing as deprecated. 

The current encryption model makes it possible to start file uploads in backgrond as soon that they are uploaded and enable the whistleblower to switch recipients after a successful file upload without issues.

Closing this ticket as outdated.

The possibility for removing an already uploaded file upload is tracked by: https://github.com/globaleaks/GlobaLeaks/issues/2521
