### ISSUE TITLE
Identify and enforce supported browsers of GlobaLeaks UI (GLClient)

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#137]
This ticket is to define the list and minor version of supported browser for GlobaLeaks support.

The supported browser's client access should enforced trough the Client UI, by displaying a big warning that the specific browser is still not supported, before allowing to do anything.

Following the implementation of this ticket, we should update technical requirement document at https://github.com/globaleaks/GlobaLeaks/wiki/Technical-requirements with the details of supported client browser .
##

**Comment by fpietrosanti** [comment]
Related to #950

**Comment by fpietrosanti** [comment]
To properly complete the feature, from https://github.com/globaleaks/GlobaLeaks/issues/950#issuecomment-56305937 

"
I think it's also very important to log somewhere that a user with "that user agent" was not able to access globaleaks, because we need to know how many users get forcefully denied access. 
The admin must be given proper information and statistics on the amount of blocked users.

For the text i suggest:
"Sounds like you are using $BROWSERNAME $BROWSERVERSION that's too old to be supported by the GlobaLeaks software due to well known security weakness. 
GlobaLeaks is supported on the following Browsers:

Google Chrome from XX version
Microsoft Internet Explorer from XX version
Mozilla Firefox from XX Version
Apple Safari from XX Version
The name of the browser must also show the "logo" of the browser.
The download button, must just bring the user to the download page of the browser from the manufacturer."

**Comment by fpietrosanti** [comment]
Related to #968 #969 requirements

**Comment by evilaliv3** [comment]
@fpietrosanti / @origliante:

i think that to make it simple the browser support test should be dividied into two aspects (steps of the detection):
  1. verify if the browser is capable of running globaleaks (browesername/version is enough for this; (e.g. ie>11 is able to run globaleaks)
  2. verify that the browser configuration is able to run globaleaks (e.g. ie>11 but with cookies disabled is not able to run globaleaks, this issue should be detected and the user notified.

Related to 1: i'm quite sure that a simple brower name/version would be enough to test it all and i suggest to do a precise test using 'bowser' library
Related to 2 requirements shuld be betterly analized.

Current requirements for GlobaLeaks are
- Support for HTML5 (to be analyzed deeply in angularjs; e.g. the FileAPI is present in every HTML5 browser?)
- support for web.crypto
- Support for Cookies (this is only a temporary requirement that would be removed; it's not important to consider this now. https://github.com/globaleaks/GlobaLeaks/issues/1233, https://github.com/globaleaks/GlobaLeaks/issues/923)
- Support for LocalStorage (currently not used. @vecna/@hellais/@fpietrosanti do you think it would be useful for something)

**Comment by fpietrosanti** [comment]
Cookies are already tested, and will be soon removed,

Localestorage ia not required.

 let's make IT simple, no more than 1/2 hour to implement the check given that most of the work is the collateral  (logging unsupported request, statistics, nice looking web page with clickable links to download the supported browsers, text copy/review)

**Comment by origliante** [comment]
1/2 hour means not using anything but if (browser.crypto) ...
I was experimenting with modernizr and beginning to search for the capabilities needed by angular 1.2
If we dont use modernizr and dont take a deeper look, the only thing we can say is "install chrome or firefox latest version"

**Comment by evilaliv3** [comment]
ok so given @fpietrosanti comment in my response i think twe best would be to simply write a browser detection based on the browser i've listed here for the test https://saucelabs.com/u/globaleaks that are the one written here: https://github.com/globaleaks/GlobaLeaks/blob/devel/scripts/travis_saucelabs.sh

for what concern safari it's the one that is on 8.3. i do not know the version. @fpietrosanti can you provide any int that you know better MAC OSX?

**Comment by origliante** [comment]
So test to check browser name/version for:
Safari >= 8
IE >= 11
Chrome >= 37
Firefox >= 36

right?

**Comment by evilaliv3** [comment]
sounds interesting, well done.

i will test it in a bit.

**Comment by fpietrosanti** [comment]
Give me a globaleaks where to test with Safari and i'll do that, either on iOS 8.2 and Mac OS X Yosemite.

I'd may suggest to test the presence of window.crypto as simple discriminating point as previously dsicussed (or ask to make a webcrypto operations, like a sha1 if it succeed) because numbering may have issues to be tracked, like (open questions):
1. Does Chrome on Mobile use the same numbering of Desktop? 
2. Does Safari Mobile use same numbering of Desktop? 
3. Does Chrome-based browsers such as Chromium, etc have the same user-agent as Chrome?

If we test the capability, then we log server side any user-agent that does not have the capability, we can easily profile what's working and what's not working w/out maintenance. 
Btw i'm also fine with the current approach, just consider extending testing to mobile browsers and Chromium

**Comment by evilaliv3** [comment]
@origliante: thinking to what @fpietrosanti i think the suggestions are right.
we should try not to do a whitelist based on the supported browsers but based on the browsers capabilities that currently we have identified generically in the test of presence of:
- windows.crypto
- windows.crypto.getRandomValues

i will push the basic code in few minuts as the currently one written can't be used (nor the one detecting the browser version nor the one that imp,ement the TorBrowser detection)

in the meantime i've prepared the unit test skeleton so that our BrowserCheck solution will be validated on all saucelab browsers.

**Comment by evilaliv3** [comment]
to clarify our magic function, by relying on a test on capabilities, should:
1) return False on all the browsers that miss a set of capabilities for which WE KNOW it wont work
2) return True for all the other

the solution should be validated on Saucelabs so that we verify that our function returns false on all the browsers were it cant work, and true on the other.

**Comment by evilaliv3** [comment]
going on with the investigation i've found this relevant code of oepnpgp.js:

    /**
     * Get native Web Cryptography api. The default configuration is to use
     * the api when available. But it can also be deactivated with config.useWebCrypto
     * @return {Object} The SubtleCrypto api or 'undefined'
     */
    getWebCrypto: function() {
      if (config.useWebCrypto === false) {
        // make web crypto optional
        return;
      }

      if (typeof window !== 'undefined' && window.crypto) {
        return window.crypto.subtle || window.crypto.webkitSubtle;
      }
    }

as you can see @origliante writing a good check involve more know how and research of a simple hypotesis.

based on my current understanding the current good check would be:

    void isBrowserSupported() {
      if (typeof window !== 'undefined' && window.crypto) {
        return !!(window.crypto.subtle || window.crypto.webkitSubtle);
      }
      return false;
    }

**Comment by evilaliv3** [comment]
just for info, on IE window.crypto is aliased by window.msCrypto as like always microsoft likes fullfilling the namespace of standard objects with funny names-ad-minchiam.

**Comment by origliante** [comment]
We are recently running end to end tests on particular browser versions, IMO the logical thing is to enforce a browser version >= a particular number. If we just check for window.crypto how can we know if the client is going to work? We test the client on browser versions not on every browser who defines window.crypto

@evilaliv3 @fpietrosanti

**Comment by evilaliv3** [comment]
we can't exclude users from all browsers that we have not tested as the number of platforms/browsers we are testing is really limited.

so based on the result on the testing we can try to design good checks based on capabilities that will act as a euristic evaluation that with a certain probability will guarantee that if we say "its cabable!" it will also work for real. it's now clear?

**Comment by evilaliv3** [comment]
interesting simple layout to be kept in mind whenever we will work on this ticket: https://hackerone.com/browser-not-supported.html

**Comment by evilaliv3** [comment]
no update for this milestone on this ticket that continued to be a low priority one.

let's move it out from the milestone and keep it only  in the wishlist remember to try to accomplish it before of the publishing of the end2end encryption stuff.

**Comment by evilaliv3** [comment]
Browesers compatibility is not tested based on a capability assesment.

In case of error a message clarify the failure and list the compatible browsers and their versions.
The message is currently shown in EN and IT.
The interface is missing: a nice UI, a language selector to switch the message in the user language based on a selectbox; this select box should be implemented without using any library but siimply standard html.

Current output is the following:
![screenshot from 2015-11-16 11 28 56](https://cloud.githubusercontent.com/assets/217034/11179746/d59a0008-8c55-11e5-9b21-98a48ddceed1.png)

**Comment by evilaliv3** [comment]
The capabilities assessed (and completely browser tested) are:

- FileAPI/Blob support (used by FlowJS and in the near future  by end2end encryption)
- Web workers (used now by the proof of work and in the near future by the end2end encryption)
- WebCrypto (used mostly in the near future by end2end encryption)

**Comment by vodkina** [comment]
@evilaliv3, estimate for this issue is set at 13. Please, agree or update accordingly. Thanks

**Comment by evilaliv3** [comment]
:+1:

**Comment by evilaliv3** [comment]
This ticket has been implemented in its basic aspects and the browser support is documented.

Further improvement on enriching the interface are currently postponed.
