### ISSUE TITLE
Installation script installs obsolete version of Tor daemon

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1371]
The installation script is installing an obsolete version of the Tor daemon (probably from the deb official repo which is not updated since 2013), causing the Tor HS to be unavailable.

It was solved by purging Tor and Globaleaks, installing Tor from the official torproject.org and installing Globaleaks again.

It happened in a brand new machine which had not Tor daemon installed previously.

Log:

Aug 27 04:56:15.121 [warn] Please upgrade! This version of Tor (0.2.2.35) is obsolete, according to the directory authorities. Recommended versions are: 0.2.4.23,0.2.4.24,0.2.4.25,0.2.4.26,0.2.4.27,0.2.5.8-rc,0.2.5.9-rc,0.2.5.10,0.2.5.11,0.2.5.12,0.2.6.5-rc,0.2.6.6,0.2.6.7,0.2.6.8,0.2.6.9,0.2.6.10,0.2.7.1-alpha,0.2.7.2-alpha

**Comment by infosquatter** [comment]
I did some search and it seems debian maintains the Tor package. I'm not sure which how the packaged distributed for Ubuntu 12.04 are update or not. Maybe after Ubuntu 14 was distributed they stop updating 12.04.

**Comment by fpietrosanti** [comment]
@infosquatter GlobaLeaks is now supported on Ubuntu 14.04 and not on Ubuntu 12.04 for new installation. That's the reason with the "old installation script" (when we where only working on ubuntu 12.04), we where installing the Tor's deb repository to install latests Tor from Tor Project. But with Ubuntu 14.04 the latests version is recent enough to stay with the default Ubuntu repository.

**Comment by infosquatter** [comment]
Ubuntu 12.04 is still an option in the wiki's Ŕequirements section.

**Comment by fpietrosanti** [comment]
Thanks pedro, just removed from the supported list!
