### ISSUE TITLE
Reduce startup time by loading GLClient and from a ZIP archive

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1372]
This ticket is to further reduce the startup time and download size of Globaleaks client by downloading GLClient compressed as a ZIP file, uncompressing and executing it into the memory of the browser.

Actually an already minified GLClient account for a size of 861kb that, once compressed with zip, become 228kb .

The JSZip ZIP javascript library, usable to do in-browser decompression, have a size is 78kb, so there would be a saving of more than 50% of the download size of the GLClient.

Maybe that's not useful / not required due to the Gzip/Deflate compression doable on the browser for all the HTTP transported data.

It would be interesting to understand if we can ship an uncompressed GLClient that's easy to be inspected at source code level, by keeping that level of compression.

The very same ZIP approach could be followed for translation/json resources.

**Comment by evilaliv3** [comment]
@fpietrosanti: the backend is applying js compression and already the glclieent is delivered as a 200kb file starting from an original packaged file of 800kb.

**Comment by evilaliv3** [comment]
so there is no need for me to add such the complexity you are adding with this and the additional 78kb that are not few.

**Comment by evilaliv3** [comment]
closing becouse outdated and becouse already the backend implement gzip while delivering the contents.

**Comment by evilaliv3** [comment]
As update on this matter, the modern client uses Brotli
