### ISSUE TITLE
issues with file uploads

### ISSUE THREAD

**Issue by IuliiSe** [globaleaks/GlobaLeaks#1373]
- often files upload but the status bar shows that the upload is still incomplete (screenshot);
- no option to delete files uploaded by mistake (for instance, duplicated file can not be deleted).
![file submission fail](https://cloud.githubusercontent.com/assets/13403429/9522242/0a040d82-4cd4-11e5-864b-18fa9b652da1.png)

**Comment by evilaliv3** [comment]
@IuliiSe thanks for reporting back to us.

1. are you able to understand whay this behaviou is happening or are you able to provide a file for which it happens?
2. for what relates to files added for error currently there is no possibility to block the upload as the upload start as soon that the user add them; this will be somehow possible in the near future where we will implement this: https://github.com/globaleaks/GlobaLeaks/issues/1363

**Comment by evilaliv3** [comment]
closing the issue as outdated.
