### ISSUE TITLE
Add a copyright header to all source files and update license for attribution clause

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1376]
This ticket is to add a copyright header to all source files and update license for attribution clause, including the LICENSE file, as follow

    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

The task of adding this header shall be automated for all kind of source code we're dealing with.

This ticket is to adjust the license and communication including Attribution Clause of AGPL, so that it must be always mentioned that a whistleblowing initiative is based on GlobaLeaks.

**Comment by fpietrosanti** [comment]
http://nodeexamples.com/2013/10/29/checking-for-copyright-headers-in-your-source-code-using-gruntjs/

**Comment by evilaliv3** [comment]
@fpietrosanti this script is not useful at all as it simply checks if the license it present but it does not add license where missing nor it changes the date where outdated.

anyhow before all we should know:
1. how to call the software syntetically; my suggestion is: GlobaLeaks, the first opensource framework for secure and anonymous whistleblowing
2. who is the author (see point 3 for where it goes): sometimes we written the full name of Hermes, sometimest the GlobaLeaks Project, in the future probably the foundation? so i would suggest to involve roberto and do the thing well done in one shot.
3. the copyright line is "#Copyright (C) <year>  <name of author>"; i've always been in doubt in what year should be written; if it has to be updated somehow during time or what.

**Comment by fpietrosanti** [comment]
This ticket must be improved by:

- Defining the additional terms of 7.b of AGPLv3 for the ATTRIBUTION
  (example 7b additional term http://htsql.org/license/)

- Making a web page on globaleaks.org explaining the licensing

**Comment by fpietrosanti** [comment]
Related #1520 /cc @NSkelsey

**Comment by fpietrosanti** [comment]
Proposed clause to be added mixing HTSQL / SugarCRM Public License in a AGPL compatible way (to be checked):

PRELIMINARY STATEMENT OF THE LICENSE: 
GlobaLeaks may be used, modified, and/or deployed subject to the AGPLv3 with a supplemental term requiring as a form of attribution of the original author, the inclusion on each user interface screen (i) the "Powered by GlobaLeaks - AGPLv3 Licensed" logo and (ii) the copyright notice in the same form as the latest version of the Covered Code distributed by Hermes Center for Transparency and Digital Human Rights (http://hermescenter.org or by Whistleblowing Solutions I.S. SRL (http://whistleblowing.solutions). at the time of distribution of such copy. When users click on the "Powered by GlobaLeaks" logo and/or text it must direct them back to https://www.globaleaks.org website. 

Any party requiring to remove the Author Attribution from the user interfaces, is required to obtain a written consent by Whistleblowing Solutions I.S. SRL (http://whistleblowing.solutions) that act as a non-profit social enterprise who's purpose is to sustain the continuity of development of the GlobaLeaks software while maintaining it entirely as a free software, available for public interests purposes pursuing the social goal of protecting whistleblowers and increasing transparency.

This free software license ensures user’s freedom to run, copy, share, study, change and improve this software by requiring publicly available derivative works are, as a whole, compatibly licensed.

LICENSE TEXT:
""
This program is free software: you can use, redistribute, and/or modify
it under the terms of the GNU Affero General Public License, version 3
or later ("AGPL"), as published by the Free Software Foundation, and as
supplemented by additional terms according to section 7 of the AGPL:

This Program was created by Hermes Center for Transparency and Digital Human Rights (http://hermescenter.org) and by Whistleblowing Solutions I.S. SRL (http://whistleblowing.solutions) under the name of the GlobaLeaks Project (https://globaleaks.org).  
As permitted by section 7b of the AGPL, we require preservation of copyright notices and author attributions in this Program's documentation and Appropriate Legal Notices.  
This Program displays such notices in each user interface screen with author attributions that include "Powered by GlobaLeaks - AGPLv3 Licensed" . The author attribution must be clearly visible with size of the fonts and icons to be proportionate to the user interface being used.

For works containing this Program or any covered work, each interactive
user interface must include a prominent and conveniently accessible
feature for the display of Appropriate Legal Notices.  This display
must include author attributions and copyright notices as found in this
Program.  This display of these author attributions must be convenient
for a user wishing to browse credits, shown in a manner separate and
distinct from license texts, and commensurately prominent with respect
to other author attributions.  To the extent that it is technically
feasible and not obtrusive, the graphical form of these author
attributions, such as a "Powered By" logo, must be preserved;
otherwise, a textual equivalent is permitted. When users click on the 
"Powered by GlobaLeaks" logo it must direct them back to 
https://www.globaleaks.org website.

Any party requiring to remove the Author Attribution from the user interfaces, is required to obtain a written consent by Whistleblowing Solutions I.S. SRL (http://whistleblowing.solutions) that act as a non-profit social enterprise who's purpose is to sustain the continuity of development of the GlobaLeaks software while maintaining it entirely as a free software, available for public interests purposes pursuing the social goal of protecting whistleblowers and increasing transparency.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"

**Comment by NSkelsey** [comment]
@fpietrosanti I performed a review. The language needs some legal eyes.

I do not like the line "Powered by GlobaLeaks." It is very web 2.0 and it implies some sort of cloud based moon power that runs the system.

Something like "Built with GlobaLeaks" works better IMO.

**Comment by NSkelsey** [comment]
@fpietrosanti mateo has convinced that it should be powered by. Logo could simply be:

<img width="437" alt="schermata 2016-06-16 alle 3 10 10 pm" src="https://cloud.githubusercontent.com/assets/1095794/16117881/a1a2a986-33d4-11e6-8a4b-f2e4ee008b64.png">

**Comment by evilaliv3** [comment]
I like this!

- AGPLv3 not GPL
- we should load it in base64 so a good compressed image work

@fpietrosanti: GlobaLeaks is a fearful world for the openwhistleblowing community; how do we deal with this?

**Comment by NSkelsey** [comment]
@fpietrosanti, here is modal for the UI switch that an admin must click. A couple points:

1) Forcing everyone to click through this is not great
2) This is DRM baybeeeeee
3) Functionally (realistically) we cannot separate the disable and the request for approval to remove the attribution. Instead we can do a double modal!

<img width="595" alt="schermata 2016-06-16 alle 11 18 25 pm" src="https://cloud.githubusercontent.com/assets/1095794/16133529/ab7d304a-3418-11e6-989f-335d81d7ac22.png">

/cc @evilaliv3 @lastknight

**Comment by fpietrosanti** [comment]
@NSkelsey the enabler is another ticket at #1520, to be discussed, not part of legal compliance itself

**Comment by evilaliv3** [comment]
@fpietrosanti / @NSkelsey:

i've updated the texts; do not edit other comments as we lose the history of the changes.

i think that reviewing the english it was reviewed also official texts of the AGPLv3 license; NEVER DO SUCH A THING.

edits:

- i've added some suggested texts on how to apply the AGPLv3 have been added (https://www.gnu.org/licenses/agpl-3.0.en.html)
- ive restored official texts that were replaced maybe for english review.
- i've added links that were missing for hermes and for ws

```
GlobaLeaks
Copyright (c) 2011-2016 - Hermes Center for Transparency and Digital Human Rights

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program was created by Hermes Center for Transparency and Digital
Human Rights (http://www.logioshermes.org) and by Whistleblowing
Solutions I.S. SRL (http://www.whistleblowing.solutions) under the
name "GlobaLeaks" (https://globaleaks.org).

As permitted by section 7b of the AGPL, we require preservation of
copyright notices and author attributions in this program's documentation
and Appropriate Legal Notices.

This program displays such notices in each user interface screen with an
author attribution that includes "Powered by GlobaLeaks".
The author attribution must be clearly visible with size of the fonts
and icons proportionate to the user interface being used.

For works containing this program or any covered work, each interactive
user interface must include a prominent and conveniently accessible
feature for the display of Appropriate Legal Notices. This display
must include author attributions and copyright notices as found in this
program. This display of these author attributions must be convenient
for a user wishing to browse credits, shown in a manner separate and
distinct from license texts, and commensurately prominent with respect
to other author attributions. To the extent that it is technically
feasible and not obtrusive, the graphical form of these author
attributions, such as a "Powered By" logo, must be preserved;
otherwise, a textual equivalent is permitted. When users click on the 
"Powered by GlobaLeaks" logo it must direct them back to the
https://www.globaleaks.org website.

Any party that wishes to remove the Author Attribution from the user
interfaces is required to obtain written consent from
Whistleblowing Solutions I.S. SRL.

The purpose of this non-profit social enterprise is to support the
development of the GlobaLeaks software while maintaining it entirely
as free software available for public interests purposes pursuing the
social goal of protecting whistleblowers and increasing transparency.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.
  
You should have received a copy of the GNU Affero General Public License
along with this program. If not, see http://www.gnu.org/licenses/.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

**Comment by NSkelsey** [comment]
Additional analysis by an awesome start-up lawyer in the US:


-         The fact that HTSQL is using this approach gives us some comfort that it’s ok. 
-         On the GPL website, they state that they will not raise legal objections to people modifying their license, which gives us some (not perfect, but some) comfort that even if you’re wrong about what Section 7(b) allows you to do, you won’t get in too much trouble for it.
-         You currently have the phrase “END OF TERMS AND CONDITIONS” before the additional terms section.  That’s a bit confusing and may suggest (to some readers) that the additional terms are not legally binding terms and can be ignored.  (It’s kind of like having a premature closing tag in HTML.)  I would suggest moving the “END OF TERMS AND CONDITIONS” language to the very end of the license (after the additional terms section), or modifying it to make it clear that it signals the end of the standard GPL terms, not the end of the license itself.
-       Consider making this revision for clarity: “When users click on the ‘Powered by GlobaLeaks’ logo or text it must direct them back to the https://www.globaleaks.org website.”
-         When listing the name of companies, lawyers generally include the name of the jurisdiction in which the company was organized and the specific entity type to avoid confusion.  For example, if you wanted to refer to Apple, you would call it “Apple Inc., a Delaware corporation.”  To avoid having to list out all that info every time you reference Apple, you would then create a defined term (using this notation: (“Apple”)) and just use that defined term every time you want to reference that specific company.  To minimize the possibility of confusion, I would suggest making the following changes to the license:
   - “This program was created by Hermes Center for Transparency and Digital Human Rights, a [JURISDICTION] [ENTITY TYPE] (“Hermes”) (http://www.logioshermes.org) and by Whistleblowing Solutions I.S. SRL, a [JURISDICTION] [ENTITY TYPE] (“Whistleblowing Solutions”) (http://whistleblowing.solutions) under the name "GlobaLeaks" (https://globaleaks.org).”
  - “Any party that wishes to remove the author attribution from the user interfaces is required to obtain written consent from Whistleblowing Solutions.”

\cc @fpietrosanti

**Comment by evilaliv3** [comment]
Thanks @NSkelsey, seems a valuable feedback

I agree with all except what relates to the "END OF TERMS AND CONDITIONS" that is a sentence used as start and trailer by the AGPL so its the original text of the AGPL that read in a pedantic way says that it cannot be modified ;)

**Comment by evilaliv3** [comment]
Splitting this ticket in tho considering done the edit of the attribution clause.

Opening now a new ticket for evaluating if and how automate the addition of the copyright header to all the sources.
