### ISSUE TITLE
"file unavailable" and "change password" page for Receivers

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1378]
### ReceiverTip with many files

![image](https://cloud.githubusercontent.com/assets/89555/9564564/dd7958ba-4eab-11e5-8647-9331b29568b3.png)

the status "file unavaiable" has to be changed with "file temporarly unavailable" because in fact will be soon available.
Now that the delivery take in account 20 files per time, and not more (they are a queue, are taken 20 in the next iteration). If a receiver access to the Rtip when some files are not yet available.. at least knows.

maybe: the number of download done, can back to be printed (without the /3 or the limit, because that is not true anymore). (note: this is also an AdopterRequest) 

### First receiver access, password change

This page instead says "GlobaLeaks" when has to be NodeName ?

**Comment by evilaliv3** [comment]
@vecna the file uploader in general is somehow under re-strutdying already also for publeaks

let me answer you and reassume some notes i've taken:

1. perfect for having divided the scheduler in iterations; having devidied one atomic query in multiple independent query it will be possible anywwhay to do all the atomic query in one single scheduler iteration but i will look at it in the future, and for now what you have done is ok. let me know when i'm ready for integrating it.
2. for what relates to the number of files and in general to some informative content related to files in the tip page, from now one it should be possible to enable/disable this objects as we removed the number to satisfy some adopter removing a feature bad implemente, we want now to reintroduce it for satifying other, and we should continue on this iteration of satisfying all in the proper framework way.
3. what a messy ticket. things here are related more than 3 different topics; i'm going to split them but please organize your ideas next times and open multiple tickets. :)
