### ISSUE TITLE
Make possible to embed every page in embedded mode instead of only /submission and /receipt

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1383]
What currently implemented for feature https://github.com/globaleaks/GlobaLeaks/issues/1134 is enabling globaleaks to be embedded in inside iframes if needed.

But currently the starting point for such an embedding is to include /submission or /receipt, but not other pages e.g. a /admin (admin login) or a /login (receiver login and in future general login for every not priviledged user)

this limits a lot the customization possibilityies so that i would suggest that the app should serve every url embedderd if the url if the url has an ?embedded=true query argument, instead of implemening the /#/embedded prefix as we are doing now.

**Comment by evilaliv3** [comment]
@fpietrosanti: do more with less! see the commit and enjoy!

**Comment by evilaliv3** [comment]
we have to remember the change from:

http://domain/#/embedded/submission valid only for /submission and /receipt
to the new possibility that is valid for every url and would require only a ?embedded=true

\cc @vecna this is relevant to you and whenever released in next release we should mention it to adopters that makes use of current /#/embedded links

**Comment by evilaliv3** [comment]
for retrocompatibility reasons ive fixed:

1. /#/embedded/XXX automagically points to /XXX?embedded=true 
2. /#/receipt now is different if after submission(receipt page) or if accessed directly (whistleblower login page)

attached are images of 2:
![screenshot from 2015-08-30 23 23 41](https://cloud.githubusercontent.com/assets/217034/9569528/95cf92b8-4f6e-11e5-8caa-63047a772684.png)
![screenshot from 2015-08-30 23 23 49](https://cloud.githubusercontent.com/assets/217034/9569530/98f1eb6c-4f6e-11e5-8c1a-915191297d3c.png)
![screenshot from 2015-08-30 23 23 59](https://cloud.githubusercontent.com/assets/217034/9569531/9c11ade6-4f6e-11e5-969d-796e7990f729.png)

**Comment by vecna** [comment]
is much more comfortable if the URLs are given in some place. 
In our usages we saw that the manual building of the URL is quite slow to be done.

Reopen or new issue ?

**Comment by evilaliv3** [comment]
Sorry fabio I'm missing what you are suggesting. Can you betterly clarify?
Il 02/Set/2015 16:56, "Claudio A." <notifications@github.com> ha scritto:

**Comment by vecna** [comment]
we need the URLs written in some place of the Admin interface, so the Admin can copy-paste such URLs without having to look into the documentation.

**Comment by evilaliv3** [comment]
what described above is done. please do not reopen thinkgs that are already closed in order to be accounted in the report. eventually next time simply put comments and i will reopen it if needed.

i'm going to open a specific ticket for what you are suggesting.
