### ISSUE TITLE
Serious issue: @naif is working on his 35th birthday!

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1385]
It has been detected that @fpietrosanti is working even today on its 35th birthday.

Various are the references for the issue (https://github.com/globaleaks/GlobaLeaks/issues/1142#issuecomment-136277945) that anyhow would need serious debugging and proper patching;

Adopters and partners should be alerted as well and all should take a party in their town; if you have an NSA grade telco instrument (e.g. Twitter, Facebook, etc) please advice as much that you can end help us stop this and make this man relax a bit!

Tomorrow he will restart working anyhow, everyday day, on a large plethora of topics, for all his life long, but if we are successful at least he won't be able to do it tomorrow in the morning!

Happy  birthday naif! Haaaappy bithhday to youuuu.

[Serious trolling should follow; please help me!]

![e0964519f3ee16c927a66c1569fd708e](https://cloud.githubusercontent.com/assets/217034/9573444/e165ad40-4fbc-11e5-856e-6d0da2034fd0.jpg)

\cc  @vodkina @vecna @hellais @mmaker

**Comment by marceloomens** [comment]
That is a serious issue indeed! I'd schedule at least 24 hours for refactoring.

![](https://i.imgur.com/BbNEaiY.gif)

**Comment by glamrock** [comment]
@fpietrosanti is this true? Good god man, leave it to the junior coders for one day! 

![11879143_893015467454047_7498250787004632377_o](https://cloud.githubusercontent.com/assets/452041/9574837/92c9fcfa-4f98-11e5-8233-08ce04da8fdc.jpg)

**Comment by vecna** [comment]
### Genesis

![image](https://cloud.githubusercontent.com/assets/89555/9576896/7cf03fa4-4fdc-11e5-8a10-a18dbb6f4f17.png)

**Comment by vecna** [comment]
implemented at 1 Sept 2015

**Comment by fpietrosanti** [comment]
Ok, i love you all! :-) 
![_57](https://cloud.githubusercontent.com/assets/770363/9599684/1912c58c-5096-11e5-99d2-8588d868f9d8.JPG)
