### ISSUE TITLE
Add capability for configuring a PGP key for notifications to the admin and to the exception mail address

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1387]
Given the various features that we have implemented in order to keep track of possible clients bugs and in order to monitor in general what is happening on the node it would be useful to add the possibility for the admin to configure a PGP key to be used for the notification to the amin itself and to the configured exception email.

This would require simply to add a per-user possibility to load the PGP key and an additional field for storing the PGP key to be used for exception mails notification; this additional field is needed in order to make possible to have an admin PGP key different from the configured exception email to make possible for who trusts the implementation to forward an email e.g. to our private mailing list where we keep track of possible bugs.

What  described above should be kept in mind while finalizing the end2end encryption db refactor that would anyhow impact on how the user/receiver tables are done and where already is planned to move the PGP key form the Receiver tableto the User table.

\cc @fpietrosanti @vecna @DrWhax

**Comment by vecna** [comment]
But, which sensitive data are in there ? or can be in there ? is a angular stacktrace ?

**Comment by evilaliv3** [comment]
E.g. We are sending the user agent of the browser. This is important to
detect bugs but it's an information to be protected. Or in general we do
not control what is in the stacktrace of a generic browser and we are not
sure if some browser may export the IP or what other possible
fingerprinting stuff for the whistleblower. Got the point?

**Comment by evilaliv3** [comment]
Implemented!

![screenshot from 2015-09-09 01 41 32](https://cloud.githubusercontent.com/assets/217034/9750140/5704db38-5694-11e5-97f9-d3c8ea61177f.png)
![screenshot from 2015-09-09 01 41 37](https://cloud.githubusercontent.com/assets/217034/9750141/5a66d9ca-5694-11e5-91ae-2a75a45c4f5e.png)
![screenshot from 2015-09-09 01 41 47](https://cloud.githubusercontent.com/assets/217034/9750142/5f0527d4-5694-11e5-9db3-3ba6a64ec2c1.png)

@fpietrosanti / @vecna: it won't be bad to add our PGP key as preconfigured one so that if one keep sending the exception in our direction we are sure that we are not exposing their users;

what should be in your thinking the fallback in case the PGP key expires?

in my thinking we should send an email to the exception destination saying that the PGP key for exceptons is expired; without doing it with a monitoring schedule i would simply replace the exception subject/content with "Exception: Cannot deliver the exception cause the PGP key for encryption is expired."
