### ISSUE TITLE
Improve Packaging by packaging and distributing software dependencies

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#140]
Currently our packaged globaleaks (deb) does install (in post-install) non-debian packaged python libraries with PIP.

This ticket is to improve our distribution and packaging system by providing dependencies's debian package.

This require introducing building for multiple distribution of all the dependencies (requiring for example compilation of python binding of c libraries) to be done with Pbuilder:
http://wiki.debian.org/PbuilderTricks
http://www.tolaris.com/2009/03/31/backporting-debian-packages-with-pbuilder/

/cc @hellais

**Comment by evilaliv3** [comment]
let's close this as outdated and with no info in relation to the current deeep analysis done in 1515.
