### ISSUE TITLE
it should be possible to configure post submission questions (associated to tip)

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1404]
An interesting feature that has been thought during the ICC hackaton would be to make possible for receivers to configure post submission questions associated to a specific tip.

the use case is the following:
1. the admin/receivers configure submissions questions using only closed answer questions; this closed questions would prevent any privacy related information to be leaked by the whistleblower; this point is something already doable by the current platform.
2. continuing on 1. it would be interesting for the receiver to configure new closed questions directly on the platform in order to ask for a specific set of new questions related to what the whistleblower has asked before.

this is strictly related to tickets like https://github.com/globaleaks/GlobaLeaks/issues/1402 and https://github.com/globaleaks/GlobaLeaks/issues/1191

**Comment by evilaliv3** [comment]
This feature has been recently analyzed in relation to the current status of the project and the the AntifrauCV project.

Current ideas are the following:
- A SecondaryQuestionnaire could be associated to the Context;
- A Internal tip could be marked by a recipient as "RequireSubmissionIntergration" via a Button "Require the whistleblower to fill the integration questionnaire";
- When a whistleblower access a second time to the submission after the InternalTip has been marked to require integration the user should be prompt to the request of filling a new questionnaire with a text or butto
- After clicking on the button or text "Fill the integration questionnaire" the user should visualize the /submission interface and after the submission the new tip should be connected to the existing tip;
- No receipt should be generated for this new tip and the user should be automatically redirected on the existing tip page;
- No 'new submission email' should be generated on this new tip;
- A new template email should be designed in order to communicate recipients about the action performed by the whisatleblower as integration on an existing tip.



Anaylsis on the easy and viable implementation are the following:
Multiple tips could be associated via a 'integrates_tip' variable that could attach the tip to its parent.
this interconnection may be implemented via the tip id that hat is already a public information with respect to the whistleblower.

**Comment by evilaliv3** [comment]
Closing as the feature has been fully implemented.

**Comment by creativeanalyst** [comment]
Thank you @evilaliv3 . 
I need to explore these various type of questions like secondary questions, post submission questions and closed questions features referred in this chain of post. 
I am new to platform and so far I have learned and tried them how they works that there are two type of questions - default and additional questions.
