### ISSUE TITLE
Captcha validation should be performed before allowing the user to proceed with the submission

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1406]
Currently when the system provides a captcha to the user, the user has to fill the answers to the problem but its answer is simply kept in the client memory and then sent out to the server when the user want to finalize the submission.

this cause user experience issues wherever the user fail to answer as:
- the system ask: solve me 2 + 7
- the user fail to answerand write 10 and click send; the system fool the user making it seems that all is oke
- the user will the do a lot of actions on the form and when he will click the submission submit button the interface will fail.

This ticket is to implement a syncronous validation of the captcha.
Wherever a captcha model is opened the captcha window should not be closed before the user has answered correctly; the system should also re-generate a question for each of the failed answers.

**Comment by vecna** [comment]
yes because the captcha is sent along the submission. not in a previous moment where error can be spotted.

**Comment by evilaliv3** [comment]
ah no no you are misunderstunding.
your design is perfect there is simply a simply refinement that i was proposing:

1. the token is delivered at the first opening of the submission [Perfect]
2. the eventual answer is sent only at the closing of the submission [Here is where i would like to refine the solution]

i would like that whenever the user click on "send" button of the captcha widget, the client would send a put on the same API with a command 'captcha". this api should end in simply operating on the captcha answer data and still only in memory.

what i'm proposing can be implemented simply in the put putting there a switch variable like:
- "finalize" (the current only one action that finalize the submission"
- "captcha" (that will simply validate captcha answers provided along the request)

sounds good?

**Comment by evilaliv3** [comment]
done!
