### ISSUE TITLE
ver .106 - Questionnaire Answers remain empty 

### ISSUE THREAD

**Issue by IuliiSe** [globaleaks/GlobaLeaks#1415]
the text filled out by source in Questionnaire Answers boxes disappears when the tip reaches the receiver. Users can see only the attached files, but descriptions are missing.

**Comment by evilaliv3** [comment]
thank you for reporting this @IuliiSe.

it seems a bug of the current builded glclient that makes the whistleblower answer not to be sent to the server.

i'm going to investigate the issue and i will release a fix in the next hours; i will update you here when done.

\cc @kyrylkov

**Comment by evilaliv3** [comment]
The bug, reproduced on current master, seems to have been solved by latest changes on the devel branch.

Anyhow with the previous commit i've also tried to improve the solution reducing possible bugs of this kind.

**Comment by evilaliv3** [comment]
the bug should be fixed now.

let's update to 2.60.107!
