### ISSUE TITLE
Bug in receptor selection/submission

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1421]
In Mexicoleaks, its not possible to make a submission unless one of the receivers "Masde131" is selected. The config for this receiver in the admin panel is the same of all the others, though - status enabled and pre-selected.

Link: http://kjpkmlafh2ra57wz.onion/#/submission

**Comment by evilaliv3** [comment]
hi @infosquatter ! let me recheck and i will be back to you shortly.

which version are you running?

**Comment by evilaliv3** [comment]
damn i'm not able to verify the bug on current version, but it seems that mexicoleaks still need to be updated.

can you please take care of it and see if the bug continue to happen?

**Comment by infosquatter** [comment]
Ok, I will update it and come back to you, thanks!

Giovanni Pellerano:

**Comment by infosquatter** [comment]
Solved by updating the software!

**Comment by evilaliv3** [comment]
great to know that! 

this ticket can be closed so!
