### ISSUE TITLE
User Preferences should be generalized on both backend and client to allow every kind of user to have its own

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1424]
By current stable release the only user that benefit of having a preferences configuration panel is the Receiver.

This would be needed by introducing the custodian user as for: https://github.com/globaleaks/GlobaLeaks/issues/1337

Also the admin has the possibility of changing his preferred language and timezone and its password but the current design allow only one admin to exist while the next (not far) future is requiring to have multiple users.

At the current time the user preferences common to any user are:
- the timezone
- the language
- the password
- the pgp key

In the future we may evaluate to make changable also the name, the description and the image that currently are possibilities only of the admin.

**Comment by fpietrosanti** [comment]
We may already start considering a "siteid" to look forward supporting multiple whistleblowing-sites in the same globaleaks instances, for all the users ?

**Comment by evilaliv3** [comment]
@fpietrosanti: this is not a preference that the user will set but more a property of the user set by the admin.

anyhow the current approach is to never introduce something that would become deadcode! :) all that you are viewing added will be accomplished in a week or less :P

**Comment by evilaliv3** [comment]
@fpietrosanti: this is not a preference that the user will set but more a property of the user set by the admin.

anyhow the current approach is to never introduce something that would become deadcode! :)

**Comment by evilaliv3** [comment]
Et voila!

Detail of admin preferences menu:
![screenshot from 2015-09-13 11 08 59](https://cloud.githubusercontent.com/assets/217034/9849619/c46d33bc-5aec-11e5-98d9-33285c39db4a.png)
![screenshot from 2015-09-13 11 09 03](https://cloud.githubusercontent.com/assets/217034/9849622/cd40ef2e-5aec-11e5-9406-9de46db9ba41.png)
![screenshot from 2015-09-13 11 09 05](https://cloud.githubusercontent.com/assets/217034/9849628/d93d3256-5aec-11e5-82ff-c653abbb948d.png)

Detail of the refactoring of the receiver preferneces creating a general settings tab:
![screenshot from 2015-09-13 12 23 59](https://cloud.githubusercontent.com/assets/217034/9849643/f9447ab4-5aec-11e5-9a7d-39a9a447c989.png)
