### ISSUE TITLE
Does not display conditional questions and steps that have not been triggered during submission

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1426]
This ticket is to enable configuration of a visualization behaviour to avoid showing unanswered (empty) questions on Receiver side, while working on a tip.

That's to avoid seeing a long list of unanswered questions with only few data in the middle.

**Comment by evilaliv3** [comment]
This is now a requirement for the ICC pilot.

There is not that much activity behind completing this and i can take care of this as the logic to be applied is the same i've written on the submission form.

**Comment by evilaliv3** [comment]
I find important showing the unanswered questions becouse it's important to know which question where provided to the whistleblower at the time of the submission and this helps in understangind what the whistleblower answered.

By the way for sure we should avoid showing:
- conditional steps that were not triggered by questionnaire ansers or score.

**Comment by fpietrosanti** [comment]
Wait, that's not the goal of this ticket. This ticket comes from OpenWhistleblowing and SportelliRiemergo's testing of long questionnaire, that display badly on the tip with only a small amount of answered question because are very long.

**Comment by evilaliv3** [comment]
I've already expressed also my point of this and swithced the topic of the ticket.

Next time that we have a situation where the ticket change topic, like now, better to leave it closed and open a specific ticket.

**Comment by evilaliv3** [comment]
going to do it now.
