### ISSUE TITLE
[duplicated] bug in GL frontend JavaScript?

### ISSUE THREAD

**Issue by IuliiSe** [globaleaks/GlobaLeaks#1428]
Getting an error message:

Exception generated by client: Mozilla/5.0 (Windows NT 6.1; rv:24.0) Gecko/20100101 Firefox/24.0

Error Message: Error: [$compile:ctreq] http://errors.angularjs.org/1.3.17/$compile/ctreq?p0=flowInit&p1=flowImg

**Comment by evilaliv3** [comment]
@IuliiSe this is a duplicated issue already documented here: https://github.com/globaleaks/GlobaLeaks/issues/1381

it does not cause any app failure and it's simply a defect that sometimes sees to happen when the user make refresh.

have you find a way of reproducing it? this would help solving it.
anyhow it doesnt happen to me in latest releases; is your platform up to date?
