### ISSUE TITLE
security awareness title missing in certain nodes

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1436]
This appear in the current https://secure.afrileaks.org/#/

![image](https://cloud.githubusercontent.com/assets/89555/10410156/54b5783e-6f39-11e5-8d41-eaa5470c1dc3.png)

**Comment by fpietrosanti** [comment]
i can see it on afrileaks, what's your javascript debugger say?
<img width="1159" alt="screen shot 2015-10-10 at 11 27 49 am" src="https://cloud.githubusercontent.com/assets/770363/10411875/f7595a26-6f41-11e5-95c6-c46166bf8161.png">

**Comment by vodkina** [comment]
???
![schermata 2015-10-10 alle 17 32 52](https://cloud.githubusercontent.com/assets/2151323/10411903/0726e490-6f75-11e5-8976-f4f4ac3338c1.png)

**Comment by evilaliv3** [comment]
@vecna this was an issue in a very old version and probably afrileaks has
not been updated since that.

You can notice that it miss a { in the angularjs sintax.

This issue can be closed
Il 10/Ott/2015 17:33, "vodkina" <notifications@github.com> ha scritto:
