### ISSUE TITLE
unable to postpone expiration date (in DEMO), silent failure

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#1437]
This is a two categories of bugs:

  * the removal of debug lines has caused that now we have a bug unclear also if DEBUG level is set in /etc/default/globaleaks, so I can't provide more info
  * a postpone operation performed by a receiver, fail with 405 (no other info avail)

**Comment by evilaliv3** [comment]
the issue was due to a wrong put to /rtip instead of /rtip/id

the fact that it was not easy debuggable is not to the removal of a debug output put due to the fact that the the right API was not called.
