### ISSUE TITLE
Selectbox Options are not ordered in the submission interface as it's shown on the admin

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1438]
Selectbox Options are not ordered in the submission interface as it's shown on the admin, see screenshots below between submission interface and admin:
<img width="704" alt="screen shot 2015-10-12 at 10 54 28 pm" src="https://cloud.githubusercontent.com/assets/770363/10446907/5d16eb46-7134-11e5-8c7d-6fde35876c3b.png">
<img width="771" alt="screen shot 2015-10-12 at 10 54 41 pm" src="https://cloud.githubusercontent.com/assets/770363/10446908/5d177ea8-7134-11e5-815a-ddc17d9fd18a.png">

**Comment by NSkelsey** [comment]
I am investigating this issue.

**Comment by evilaliv3** [comment]
I'm not completely sure this is still an issue; this has to be verified on the devel branch.

**Comment by evilaliv3** [comment]
@fpietrosanti :) given the simple fix to be done and the relevancy of the ticket (that i was forgetting) for the adopters and the fact that retesting it make me found some other bugs we agreed with @NSkelsey that he will pick up other tickets :) thank you anyway @NSkelsey
