### ISSUE TITLE
Fields on the same row but on different column are not orizzontally aligned if outside a "group field"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1449]
Fields on the same row but on different column are not orizzontally aligned if outside a "group field" .

It seems that's possible to allign only fields in the same row, if they are part of a group field, but when they are created independently, outside of a group field, they does not appear to be alligned orizzotally.

We tested with 1 "date" field and 1 "single line text" field, on the same Row, but on different column, they did not appear to be orizzontally aligned, but vertically ordered.

**Comment by evilaliv3** [comment]
This was a requirement of the implementation i did of the horizontal alignment.

Now the current solution allows it, so that i can remove the explicit check preventing this.
