### ISSUE TITLE
Hint of Step does not display on the interface

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1450]
While configuring the step with all the fields, we did noticed that "Hint" box of a Step, even if filled properly, does not display anywhere interface.

This ticket is to either remove the "hint" (suggerimento) on the Step, either to display it somewhere

**Comment by evilaliv3** [comment]
The hint in the step was adding by me initially but i've not found valuable to complicate the interface with this additional element so i'm more for removing it and eventually if some will draw a use case we will implement it properly one day.
