### ISSUE TITLE
Error postponing tip

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1452]
Mexicoleaks  media report they can't postpone tips. They are using the latest version of the software, updated 10 days ago.

They say that on clicking on the postpone button, it says it will postpone but in the end it is not actually postponed.

I dont have further details since I dont have access to any receptor of this deployment.

**Comment by evilaliv3** [comment]
you are right. this seems a bug present in latest release i was thinking to have fixed it and re-releaesd but no. probably i was thinking to wait a few and release current devel and i forgot that a release was needed for this and time passed by.

i'm going to fix it and push out a package.

**Comment by evilaliv3** [comment]
in the meantime @infosquatter you can suggest users to postpone tip expiration from the tip list where the feature is working properly.

by tonight there will be anyhow a release that will fix the issue.

**Comment by infosquatter** [comment]
Ok, I will suggest them that. Take your time. Thanks!

**Comment by evilaliv3** [comment]
Solved in released package 2.60.113
