### ISSUE TITLE
Angular-elastic library seems to not behave well on internet explorer when no min-height/row is set.

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1459]
Angular-elastic library seems to not behave well on internet explorer when no min-height is set.

On these conditions the textarea appear smaller than a single line height.

It seems a bug already reported by other users on various tickets as https://github.com/monospaced/angular-elastic/issues/71 and https://github.com/monospaced/angular-elastic/issues/58

**Comment by evilaliv3** [comment]
In the meantime that we discuss the proper solution i would simply suggest to avoid using the library that is anyhow not providing such an important feature.

**Comment by soferio** [comment]
The problem is solved for me (in the sense that it now works nicely on Microsoft Edge) by adding:

> style='min-height: 1em' rows='1'
