### ISSUE TITLE
Improve submission list by adding a column "Update date" of the submission list

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1463]
This ticket deals with the addition of a column "update date" on the submission list.

The information to be provided is the latest date of an action on the ticket among:
- original submission date
- the latest comment
- the latest message
- the latest file upload

The tip list should be ordered by default by this new column.

**Comment by fpietrosanti** [comment]
It maybe nice also to be able to disable/enable the different "dates" on tip list (for example, expiry date in OpenWhistleblowing is not required)

**Comment by evilaliv3** [comment]
@fpietrosanti the expiration date even if longer will continue to exists also on openwhisleblowing; it is not possible and not possible to put it to unlimited. 

Anyhoe nice hint  to add a configurator of the list; i will keep it in mind for the future while dealing with the tip list enrichment also in relation to the context dependend columns and the need to the refactor the archived questionnairs
