### ISSUE TITLE
Enable disabling PGP warning on Receiver Tip interface 

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1467]
This ticket is to Enable disabling PGP warning on Receiver Tip interface.

Required for Edison project

**Comment by evilaliv3** [comment]
As we are now going to ship a db migration i'm going now to implement this feature.

**Comment by evilaliv3** [comment]
Feature implemented; i agree it is needed in various projects expecially on the startup of the project where there is a board to be persuaded and you do not want it to focus on security aspects.

But has this (and in future other) features may affect the security of the platform / of the user the interface has been studied as following:
- the user has explicitly to disable this warning with a checkbox with the following text: "Disable the warning messages that are shown when encryption is not available"
- when disable the user see a warning "This setting affects the security of the users and must not be used in production."
