### ISSUE TITLE
AppArmor gives DENIED error (but everything still works)

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1468]
AppArmor gives DENIED error (but everything still works) on Ubuntu 14.04

[26739.511888] type=1400 audit(1446390722.068:36): apparmor="DENIED" operation="open" profile="usr.bin.globaleaks" name="/proc/28716/status" pid=28716 comm="globaleaks" requested_mask="r" denied_mask="r" fsuid=0 ouid=0

**Comment by evilaliv3** [comment]
@fpietrosanti: GlobaLeaks is affected by the same issue of tor2web related to ```uname```: https://github.com/globaleaks/Tor2web/issues/261

I've now managed to know the reason and it's the inclusion of pip for checking the dependencies;
some internal code of pip while loading calls os.uname()

i'm now viwing if i'm able to include a more precise file without triggering the os.uname, if not i'm going to add ```/bin/uname``` to both GlobaLeaks and Tor2web.
in fact i do not see problematic to open to that that can be needed for other reasons also by us and it's definetly the less vulnerable vector to attack i think, or at least i hope!

**Comment by evilaliv3** [comment]
it's valuable to not that also in the future when removing the usage of pip for setupping dependencies, we will anyhow always use pip python library for a reason or an other like those rechecking.

**Comment by fpietrosanti** [comment]
That's bad as it's a 2nd command line (other than gnupg) to be executed, that prevent us from removing /bin/sh from apparmor profile. It would be better to open an issue to pip library to remove executing uname and using native libc functions instead.

**Comment by fpietrosanti** [comment]
Linked on https://github.com/pypa/pip/issues/3442

**Comment by evilaliv3** [comment]
Instead of allowing ```/bin/uname``` i've added a rule for silently denying it's execution by apparmor.
