### ISSUE TITLE
The file /etc/default/globaleaks shall not be overwritten

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1469]
This ticket is to resiliency of the file /etc/default/globaleaks by avoiding any overwriting by the debian package.

The idea is that GlobaLeaks will always load /usr/share/globaleaks/default file first, then /etc/default/globaleaks

The file /etc/default/globaleaks will contain only a header saying
"# GLOBALEAKS FILE TO CHANGE NETWORK AND SECURITY SETTINGS
"# YOU CAN OVERRIDE ANY SETTINGS DEFINED IN FILE  /usr/share/globaleaks/default"
"# BY ADDING LINES IN THIS FILE"

**Comment by evilaliv3** [comment]
Done!

the text written in the /etc/default/globaleaks is:
```
# This is a configuration file for /etc/init.d/globaleaks;
# it allows you to perform common modifications to the behavior
# of the globaleaks daemon.
#
# Default settings can be found at: /usr/share/globaleaks/default
