### ISSUE TITLE
Submission problem with multiple nesting of "Group Fields"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1470]
There is a problem with submission fields that are multiple nesting of Group Fields. 

Tested with Edison, attached example export of a context triggering the bug.

There is also an unhanded exception being received

[contesto anticorruzione edison 0911.json.txt](https://github.com/globaleaks/GlobaLeaks/files/29943/contesto.anticorruzione.edison.0911.json.txt)

**Comment by evilaliv3** [comment]
Issue not present in recent releases.
