### ISSUE TITLE
Improve first login experience by not asking the "Current Password"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1471]
This ticket is to Improve first login experience by not asking the "Current Password", when "forced password change" is in place, because the user (admin, receiver, custodian) has just typed his password before.

**Comment by evilaliv3** [comment]
This was implemented long time ago and is now improved with https://github.com/globaleaks/GlobaLeaks/issues/2614

Here is a screenshot of the current interface:
![screenshot-127 0 0 1_8082-2019 09 27-08_56_18](https://user-images.githubusercontent.com/217034/65749319-2b0f7f00-e106-11e9-8947-61f110e1a635.png)

![screenshot-127 0 0 1_8082-2019 09 27-09_02_52](https://user-images.githubusercontent.com/217034/65749341-3498e700-e106-11e9-9110-d3d511d245c6.png)
