### ISSUE TITLE
Enable Recipients to share files with Whistleblowers

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1473]
This ticket is to enable Recipients to share files with Whistleblowers.

This request come from TI-it that's acting as intermediary between the Whistleblowers and the public agencies where corruption happens, and they often need to gives back to the Whistleblower the visibility of the answers coming from the Public Agencies.

**Comment by evilaliv3** [comment]
Feature implemented recently and shipped on 2016-11-24 with release 2.65.0
