### ISSUE TITLE
Repo is down

### ISSUE THREAD

**Issue by infosquatter** [globaleaks/GlobaLeaks#1476]
W: Failed to fetch http://deb.globaleaks.org/precise/Release.gpg  Could not connect to deb.globaleaks.org:80 (194.150.168.85). - connect (111: Connection refused)

W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by evilaliv3** [comment]
hi pedro!

we have a release issues on migrations of submission  so we are intentionally  preventing new installs so to prevent user data losses.

all will be fixed by today.

thank you for notifying

**Comment by evilaliv3** [comment]
fixed :) all is up and running with previous release 2.60.113.
