### ISSUE TITLE
Help hint limits is capped to 128byte and shall become the same of "Title Length Limit"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1477]
Help hint limits is capped to 128byte and shall become the same of "Title Length Limit" already configurable in the advanced settings

**Comment by NSkelsey** [comment]
I do not believe this is an issue, but I may be looking at the wrong help field. The size of the help hint text is configurable and in this example it is set to 1024 bytes. See the large hint box and highlighted code.

### Whistleblower's view
<img width="686" alt="screen shot 2015-11-11 at 6 55 13 pm" src="https://cloud.githubusercontent.com/assets/1095794/11106656/c5d20750-88a5-11e5-8142-1ec44dd1e3c8.png">


### Code
<img width="1003" alt="screen shot 2015-11-11 at 6 49 48 pm" src="https://cloud.githubusercontent.com/assets/1095794/11106575/18e75b80-88a5-11e5-886b-f08d064a50ff.png">
[From fields.js](https://github.com/globaleaks/GlobaLeaks/blob/master/client/app/views/admin/fields.html#L105)

**Comment by evilaliv3** [comment]
I confirm that this issue is not present.
