### ISSUE TITLE
Full license missing?

### ISSUE THREAD

**Issue by donaldr3** [globaleaks/GlobaLeaks#1483]
It looks like /LICENSE is just the header text for AGPLv3, and not the full license text (http://www.gnu.org/licenses/agpl.txt). That header text is for the top of files included in the project, but a full copy of the license should be included as well. Thanks.

**Comment by evilaliv3** [comment]
thank you for notifying this @donaldr3! really appreciated :)

**Comment by evilaliv3** [comment]
done!
