### ISSUE TITLE
Installing GlobaLeaks on Ubuntu 15.10 trigger an apparmor error

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1490]
Installing GlobaLeaks on Ubuntu 15.10 trigger an apparmor error. 

Ubuntu 15.10 is not automatically tested with Jenkins, so we shall introduce automated testing also for that version

yawnbox
10:12 [05:20:56] anyone on who might be able to help me troubleshoot installation on Ubuntu 15.10
10:12 [05:21:28] 14.04.3 does not recognize an internal drive
10:12 [06:20:23] "job for tor.service failed because the control process exited with error code"
10:12 [06:21:50] tor log says "couldn't open "/var/globaleaks/torhs//private_key.tmp" and "coldn't write generated key..."
10:12 [06:21:56] seems to be an apparmor error

**Comment by n-daniel** [comment]
Try this:
add this line 
ReadWriteDirectories=-/var/globaleaks/torhs/
in # Hardening section of init file:
/etc/systemd/system/multi-user.target.wants/tor.service

**Comment by n-daniel** [comment]
An elegant solution is this:
1. create /etc/systemd/system/tor.service.d/directory.conf
2. write this:
[Service]
ReadWriteDirectories=-/var/globaleaks/torhs/

3. reinstall or reconfigure GlobaLeaks

**Comment by yawnbox** [comment]
Thank you, @n-daniel! I have confirmed this works.

My steps:

sudo ufw enable
sudo apt-get update
sudo apt-get dist-upgrade -y
sudo shutdown -r now

sudo su
mkdir /etc/systemd/system/tor.service.d
vim /etc/systemd/system/tor.service.d/directory.conf

[Service]
ReadWriteDirectories=-/var/globaleaks/torhs/

wget https://deb.globaleaks.org/install-globaleaks.sh
chmod +x install-globaleaks.sh
./install-globaleaks.sh

**Comment by evilaliv3** [comment]
Closing this as outdated.

We are now not applying any apparmor/systemd quirk for Tor as every operation is managed via Tor ephemeral configurations via tor control port by means of the txtorcon library.
