### ISSUE TITLE
Remove file "download" link from whistleblower status view

### ISSUE THREAD

**Issue by t1msammut** [globaleaks/GlobaLeaks#1491]
Hi.

As a submitter/whistleblower viewing a submission via a /#/status URL, each file in the Files box has a download link. That link does not appear to work (at least on a system with PGP enabled globally) and I don't think it should given that files are encrypted to the receivers' PGP keys. 

You can see the links I am referring to in the attached screenshot. 

Please remove these links. 

Thanks!

![screenshot from 2015-11-20 16-04-15](https://cloud.githubusercontent.com/assets/10746039/11305473/b9ec5cfa-8fa4-11e5-9584-f2d994c7ec08.png)

**Comment by evilaliv3** [comment]
thank you for reporting this @t1msammut 

this is simply a graphical dead link impacting amnesty custom graphic.

i will take care of fixing it.

**Comment by evilaliv3** [comment]
@t1msammut: sorry for the delay, all should be fixed now!
