### ISSUE TITLE
issue with angularjs

### ISSUE THREAD

**Issue by IuliiSe** [globaleaks/GlobaLeaks#1496]
Every time there is a submission we receive a admin notification about some problem. Submissions go through successfully. 

The notification includes the following:

"
Exception generated by client: Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0

Error Message: Error: [$compile:ctreq] http://errors.angularjs.org/1.3.19/$compile/ctreq?p0=flowInit&p1=flowImg

[....] 
"

**Comment by fpietrosanti** [comment]
Did you tried to upgrade to the very latest version that we just released yesterday?

It's a major upgrade with tons (a couple of months of development) of bugfixes and this one (that's a "flow" file uploader component initialization issue) shall be fixed.

We've not yet done any announcement, as we want to be cautious in following the upgrades one by one, to detect and fix issues that may occur.

Let us know if the upgrade goes smoothly, just to be paranoid enough, make a tar backup archive of /var/globaleaks/ before!

**Comment by IuliiSe** [comment]
We just upgraded.

There is an issue with submission button now. It counts down the waiting time, but does not become active after waiting times runs out. Submission can not be completed.

**Comment by evilaliv3** [comment]
@IuliiSe please check that:
1) there is at least one receiver selected
2) all mandatory questions are filled

if it is not workking anyway, i'm supposing that you have receivers not visible and you have deselected "show recipients selection step" but without makinrg "select all recipients by default".

**Comment by IuliiSe** [comment]
@evilaliv3 
I have:
1) checked
2) checked

0) did not change settings on "show recipients selection step"

**Comment by evilaliv3** [comment]
bug just verified @IuliiSe;

sorry for the inconvenience, its seems to be an issue with the build package.
we are now investigating and i will post here when fixed.

**Comment by IuliiSe** [comment]
@evilaliv3 

Maybe, some details will help you. We get the following notifications on "GlobaLeaks Exception 2.60.115"

Exception generated by client: Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0

URL: http://....onion/#/submission

Error Message: TypeError: uploads[key] is undefined
Error Message: TypeError: flow is undefined

twisted.internet.defer.CancelledError 
This error is raised by default when a L{Deferred} is cancelled.


CancelledError

**Comment by evilaliv3** [comment]
this has been fixed and shippeed in 2.60.117
