### ISSUE TITLE
unhandled exception in mail notifications: txsocksx.errors.ConnectionRefused 

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1501]
After updating GlobaLeaks on Edison platform, got this Unhandled exception for txsocksx.errors.ConnectionRefused .

The txsocksx.errors.ConnectionRefused callback shall be properly handled and logged with a meanfull error in the log file
```
2015-11-25 18:53:29+0100 [ParserProtocol,client] &#39;[!] Exception while performing scheduled operation AnomaliesSchedule: &#39;
2015-11-25 18:53:29+0100 [ParserProtocol,client] &#39;[!] Unhandled exception raised:&#39;
2015-11-25 18:53:29+0100 [ParserProtocol,client] &#39;[!] txsocksx.errors.ConnectionRefused &#92;&#92;n    Connection refused ( 5 )
&#92;&#92;n    
&#92;&#92;n
&#92;&#92;nTraceback (most recent call last):
&#92;&#92;n
&#92;&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;jobs&#47;base.py&quot;, line 74, in _operation
&#92;&#92;n    yield self.operation()
&#92;&#92;n
&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;defer.py&quot;, line 1097, in _inlineCallbacks
&#92;&#92;n    result = result.throwExceptionIntoGenerator(g)
&#92;&#92;n
&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;failure.py&quot;, line 389, in throwExceptionIntoGenerator
&#92;&#92;n    return g.throw(self.type, self.value, self.tb)
&#92;&#92;n
&#92;&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;jobs&#47;statistics_sched.py&quot;, line 102, in operation
&#92;&#92;n    yield compute_activity_level()
&#92;&#92;n
&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;defer.py&quot;, line 1097, in _inlineCallbacks
&#92;&#92;n    result = result.throwExceptionIntoGenerator(g)
&#92;&#92;n
&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;failure.py&quot;, line 389, in throwExceptionIntoGenerato
r&#92;&#92;n    return g.throw(self.type, self.value, self.tb)
&#92;&#92;n
&#92;&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;anomaly.py&quot;, line 103, in compute_activity_level
&#92;&#92;n    yield sendmail(mailinfo[&#92;&#39;mail_address&#92;&#39;], mailinfo[&#92;&#39;subject&#92;&#39;], mailinfo[&#92;&#39;body&#92;&#39;])
&#92;&#92;n
&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;protocol.py&quot;, line 53, in dataReceived
&#92;&#92;n    self._parser.receive(data)
&#92;&#92;n
&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;tube.py&quot;, line 41, in receive
&#92;&#92;n    status = self._interp.receive(data)
&#92;&#92;n
&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 48, in receive
&#92;&#92;n    for x in self.next:
&#92;&#92;n
&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 177, in apply
&#92;&#92;n    for x in self._apply(f, ruleName, argvals):
&#92;&#92;n
&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 110, in _apply
&#92;&#92;n    for x in rule()
:&#92;&#92;n
&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 256, in parse_Or
&#92;&#92;n    for x in self._eval(subexpr):
&#92;&#92;n
&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 241, in parse_And
&#92;&#92;n    for x in self._eval(subexpr):
&#92;&#92;n
&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 440, in parse_Action
&#92;&#92;n    val = eval(expr.data, self.globals, self._localsStack[-1]
&#92;&#92;n
&#92;&#92;n  File &quot;&lt;string&gt;&quot;, line 1, in &lt;module&gt;
&#92;&#92;n
&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;txsocksx&#47;client.py&quot;, line 153, in serverResponse
&#92;&#92;n    raise e.socks5ErrorMap.get(status)()
&#92;&#92;n&
#92;&#92;nConnectionRefused
&#92;&#92;n&#39;
2015-11-25 18:53:29+0100 [ParserProtocol,client] Starting factory &lt;txsocksx.client.SOCKS5ClientFactory instance at 0x7fe8af59ecb0&gt;
2015-11-25 18:53:29+0100 [-] Stopping factory &lt;txsocksx.client.SOCKS5ClientFactory instance at 0x7fe8af5659e0&gt;
2015-11-25 18:53:29+0100 [ParserProtocol,client] &#39;[!] SMTP connection failed (Exception: )&#39;
```

**Comment by evilaliv3** [comment]
@fpietrosanti aside from handling the exception, have you diagnosed the reason why the port was found closed?

i mean, apart from handleing situations where the smtp/socks is setupped wrongly, there was a migration bug or you were simply configuring badly the platform?

**Comment by fpietrosanti** [comment]
Re-happened today with 2.6.120 because remote tcp-port of smtp server where closed:
2015-12-09 14:42:59+0100 [GLHTTPConnection,1,127.0.0.1] Starting factory &lt;txsocksx.client.SOCKS5ClientFactory instance at 0x7f33589001b8&gt;
2015-12-09 14:42:59+0100 [GLHTTPConnection,1,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;posixbase.py&quot;, line 614, in _doReadOrWrite
	    why = selectable.doRead()
	  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;tcp.py&quot;, line 215, in doRead
	    return self._dataReceived(data)
	  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;tcp.py&quot;, line 221, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;endpoints.py&quot;, line 112, in dataReceived
	    return self._wrappedProtocol.dataReceived(data)
	--- &lt;exception caught here&gt; ---
	  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;protocol.py&quot;, line 53, in dataReceived
	    self._parser.receive(data)
	  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;tube.py&quot;, line 41, in receive
	    status = self._interp.receive(data)
	  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 48, in receive
	    for x in self.next:
	  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 177, in apply
	    for x in self._apply(f, ruleName, argvals):
	  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 110, in _apply
	    for x in rule():
	  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 256, in parse_Or
	    for x in self._eval(subexpr):
	  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 241, in parse_And
	    for x in self._eval(subexpr):
	  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;ometa&#47;interp.py&quot;, line 440, in parse_Action
	    val = eval(expr.data, self.globals, self._localsStack[-1])
	  File &quot;&lt;string&gt;&quot;, line 1, in &lt;module&gt;
	    
	  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;txsocksx&#47;client.py&quot;, line 153, in serverResponse
	    raise e.socks5ErrorMap.get(status)()
	txsocksx.errors.ConnectionRefused:
