### ISSUE TITLE
issue in frontend JavaScript?

### ISSUE THREAD

**Issue by IuliiSe** [globaleaks/GlobaLeaks#1502]
After every submission a notification is send to admin on:

Exception generated by client: Mozilla/5.0 (Windows NT 6.1; rv:38.0) Gecko/20100101 Firefox/38.0

Error Message: TypeError: $rootScope.successes is undefined
Error Message: TypeError: $rootScope.errors is undefined

Stacktrace:
[
{
"columnNumber": 9, 
"lineNumber": 5740, 
"functionName": ".responseError", 
"fileName": "http://....../app.js"
}, 
{
"columnNumber": 129, 
"lineNumber": 4958, 
"functionName": "f/<", 
"fileName":  "http://....../app.js"
}, 
{
"columnNumber": 309, 
"lineNumber": 4972, 
"functionName": "lf/this.$get</r.prototype.$eval", 
"fileName":  "http://....../app.js"
}, 
{
"columnNumber": 404, 
"lineNumber": 4969, 
"functionName": "lf/this.$get</r.prototype.$digest", 
"fileName":  "http://....../app.js"
}, 
{
"columnNumber": 76, 
"lineNumber": 4973, 
"functionName": "lf/this.$get</r.prototype.$apply", 
"fileName":  "http://....../app.js"
}, 
{
"columnNumber": 442, 
"lineNumber": 4926, 
"functionName": "g", 
"fileName":  "http://....../app.js"
}, 
{
"columnNumber": 50, 
"lineNumber": 4931, 
"functionName": "T", 
"fileName":  "http://....../app.js"
}, 
{
"columnNumber": 78, 
"lineNumber": 4932, 
"functionName": "Uf/</w.onload", 
"fileName":  "http://....../app.js"

**Comment by evilaliv3** [comment]
This should be fixed at the time of version 2.60.118
