### ISSUE TITLE
Implement a setup-development-environment script  to facilitate new developers working on GlobaLeaks

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1506]
As suggested by @br1n0 it would be important to implement a setup-development-environment script  to facilitate new developers working on GlobaLeaks.

The script should automatize the setup of https://github.com/globaleaks/GlobaLeaks/wiki/setting-up-globaleaks-development-environment by properly:

1. execute commands part of the setup of the development environment (mainly a refinement of the above documentation that eventually would need to be updated)
2. provide valuable output for the state of the advancemenet of the setup
3. detect failures and provide suggestions for solving issues
4. detect already existing directories/programs and try to setup only what is really needed trying to mess the user environment the less that we can.

**Comment by evilaliv3** [comment]
@br1n0 has already suggested a valuable starting point for the script:
```{r, engine='bash', count_lines}
#!/bin/bash
#to install globaleaks-dev

# this force to exit at first error returned
set -e

echo "Step.0: enable universe"
sudo add-apt-repository universe

echo "Step.1: update"
sudo apt-get update

echo "Step.2: apt-get install"
sudo apt-get install build-essential git python-pip libssl-dev libffi-dev python-virtualenv python-dev 

echo "Step.3: git clone"
git clone https://github.com/globaleaks/GlobaLeaks.git

echo "Step.2.5: git checkout b0fcc46729448bd85248da5e0fb7a3a2af9615e6"
cd GlobaLeaks/ && git checkout b0fcc46729448bd85248da5e0fb7a3a2af9615e6 && cd ..


echo "Step.4: git node install 1/2"
curl -sL https://deb.nodesource.com/setup | sudo bash -

echo "Step.5: git node install 2/2"
sudo apt-get install nodejs

echo "Step6.: install grunt and bower"
sudo npm install -g grunt grunt-cli bower

echo "Step.7: install Client npm Dependencies"
cd GlobaLeaks/client && sudo npm install -d

echo "Step.8: install Client grunt Dependencies"
grunt setupDependencies && cd ../../

echo "Step.9: install Backend"
cd GlobaLeaks/backend

echo "Step.10: install Backend virtualenv"
virtualenv -p python2.7 glenv

echo "Step.11: install Backend activate"
source glenv/bin/activate

echo "Step.12: setup Backend python setup"
python setup.py develop --always-unzip 

echo "Step.13: finally start  globaleaks"
cd ../../ && ./GlobaLeaks/backend/bin/globaleaks -z -d -n
```

**Comment by br1n0** [comment]
i've done some changes to make it more flexible,
now it show the installation stage on console, but put the last one on status.txt
you can use the first parameter to replicate a specific version from repository
this is updated version:

#!/bin/bash
# to install globaleaks-dev
# the status of installation will be printed in console, 
# the last successful status is in status.txt
# the script could ask to enter the password of admin

# run withouth sudo! e.g. :
# ./installDev.sh 
# it will prepare the eviroment at last commit
#
# if you want the eviroment at spcific revision, pass the revision id as 1st parameter
#./installDev.sh b0fcc46729448bd85248da5e0fb7a3a2af9615e6


# this force to exit at first error returned
set -e

echo "Step.0/13: enable universe" |tee status.txt
sudo add-apt-repository universe

echo "Step.1/13: update"
sudo apt-get update

echo "Step.2/13: apt-get install" |tee status.txt
sudo apt-get install build-essential git python-pip libssl-dev libffi-dev python-virtualenv python-dev 

echo "Step.3/13: git clone" |tee status.txt
git clone https://github.com/globaleaks/GlobaLeaks.git

#if you need to replicate the enviroment to a specific version, pass the id of revision as parameter
if [ $1 ] 
	then
	echo "Step.2.5/13: git checkout $1" |tee status.txt
	cd GlobaLeaks/ && git checkout && cd ..
fi


echo "Step.4/13: git node install 1/2" |tee status.txt
curl -sL https://deb.nodesource.com/setup | sudo bash -

echo "Step.5/13: git node install 2/2" |tee status.txt
sudo apt-get install nodejs

echo "Step6./13: install grunt and bower" |tee status.txt
sudo npm install -g grunt grunt-cli bower

echo "Step.7/13: install Client npm Dependencies" |tee status.txt
cd GlobaLeaks/client && sudo npm install -d

echo "Step.8/13: install Client grunt Dependencies" |tee status.txt
grunt setupDependencies && cd ../../

echo "Step.9/13: install Backend" |tee status.txt
cd GlobaLeaks/backend

echo "Step.10/13: install Backend virtualenv" |tee status.txt
virtualenv -p python2.7 glenv

echo "Step.11/13: install Backend activate" |tee status.txt
source glenv/bin/activate

echo "Step.12/13: setup Backend python setup" |tee status.txt
python setup.py develop --always-unzip 

echo "Step.13/13: finally start  globaleaks" |tee status.txt
cd ../../ && ./GlobaLeaks/backend/bin/globaleaks -z -d -n

**Comment by br1n0** [comment]
this fix the first bug foun for ~60lines of script:
the file status.txt updated is on the base Directory only!

```bash
#!/bin/bash
# to install globaleaks-dev
# the status of installation will be printed in console, 
# and the last status is  in the file called ./status.txt
# the script could ask to enter the password of admin

# run withouth sudo! e.g. :
# ./installDev.sh 
# it will prepare the eviroment at last commit
#
# if you want the eviroment at spcific revision, pass the revision id as 1st parameter
#./installDev.sh b0fcc46729448bd85248da5e0fb7a3a2af9615e6

baseDir=`pwd`

# this force to exit at first error returned
set -e

echo "Step.0/13: enable universe" |tee  $baseDir/status.txt
sudo add-apt-repository universe

echo "Step.1/13: update"
sudo apt-get update

echo "Step.2/13: apt-get install" |tee  $baseDir/status.txt
sudo apt-get install build-essential git python-pip libssl-dev libffi-dev python-virtualenv python-dev 

echo "Step.3/13: git clone" |tee  $baseDir/status.txt
git clone https://github.com/globaleaks/GlobaLeaks.git

#if you need to replicate the enviroment to a specific version, pass the id of revision as parameter
if [ $1 ] 
    then
    echo "Step.2.5/13: git checkout $1" |tee  $baseDir/status.txt
    cd GlobaLeaks/ && git checkout && cd ..
fi


echo "Step.4/13: git node install 1/2" |tee  $baseDir/status.txt
curl -sL https://deb.nodesource.com/setup | sudo bash -

echo "Step.5/13: git node install 2/2" |tee  $baseDir/status.txt
sudo apt-get install nodejs

echo "Step6./13: install grunt and bower" |tee  $baseDir/status.txt
sudo npm install -g grunt grunt-cli bower

echo "Step.7/13: install Client npm Dependencies" |tee  $baseDir/status.txt
cd GlobaLeaks/client && sudo npm install -d

echo "Step.8/13: install Client grunt Dependencies" |tee  $baseDir/status.txt
grunt setupDependencies && cd ../../

echo "Step.9/13: install Backend" |tee  $baseDir/status.txt
cd GlobaLeaks/backend

echo "Step.10/13: install Backend virtualenv" |tee  $baseDir/status.txt
virtualenv -p python2.7 glenv

echo "Step.11/13: install Backend activate" |tee  $baseDir/status.txt
source glenv/bin/activate

echo "Step.12/13: setup Backend python setup" |tee  $baseDir/status.txt
python setup.py develop --always-unzip 

echo "Step.13/13: finally start  globaleaks" |tee  $baseDir/status.txt
cd ../../ && ./GlobaLeaks/backend/bin/globaleaks -z -d -n
```

**Comment by evilaliv3** [comment]
Script added to devel repository and linked in https://github.com/globaleaks/GlobaLeaks/wiki/Setting-up-GlobaLeaks-development-environment

**Comment by evilaliv3** [comment]
thanks @br1n0!

**Comment by br1n0** [comment]
glad to be helpful :)
