### ISSUE TITLE
Evaluate and testing Widget designed with a custom independent bootstrap for embedded mode

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1511]
This ticket is to evaluate and testing Widget designed with a custom independent bootstrap for embedded mode.

We identified that this strategy could be a way to avoid using iframe (that leaves trace in the history), but there's a major issue related to the embedding of bootstrap using prefixes in a way that would enable inclusion in an existing website, without having the existing website to break our modal single-page website in the modal.

If that works properly, we may have a new way for embedding GlobaLeaks with CORS on the backend and pure javascript solution on the client, embeddable in any website without traces.

Some link to evaluate posible solutions:
Using *just* Bootstrap modal stackoverflow.com/questions/17088160/using-just-bootstrap-modal

Note: This ticket is probably technically imprecise

**Comment by evilaliv3** [comment]
Design idea obsoleted by current research and development.
