### ISSUE TITLE
Release 2.60.120, now tagged, should be released

### ISSUE THREAD

**Issue by danilort** [globaleaks/GlobaLeaks#1512]
Hello,
the upgrade to version 2.60.120 is not working.

STEP:
1) globaleaks -v
           GlobaLeaks Version: 2.60.119
	
2) apt-get update && apt-get install globaleaks
           Already GlobaLeaks is the newest version.
	   0 upgraded, 0 newly installed, 0 to remove and 172 not upgraded 

3) globaleaks -v
           GlobaLeaks Version: 2.60.119

**Comment by evilaliv3** [comment]
dear @danilort,

the code of release 2.60.120 has been currently signed but given other duties related to the project were ongoing the debian package release has been postponed by today afternoon.

we will take care of updating this ticket when done.

**Comment by evilaliv3** [comment]
done!
