### ISSUE TITLE
GlobaLeaks dependencies should be properly analyzed in relation to debian packaging

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1515]
Since the target of GlobaLeaks is to be an easy installable and properly packaged Debian package we should, once for all, start a proper analysis of the dependencies.

To this aim we should in my opinion start properly analyzing as a whole the following distributions:

- precise, wheezy, trusty, jessie (current ubuntu/debian stables)
- xenial, stretch (next ubuntu/debian stables)

in this analysis we should see what is already packaged in the distributions and what are the version present, that even if outdated (but secure) can be selected for the following aims:

1. release a package for each version, that will be from now on specific in the dependencies versions;
2. target as packaging as first that we can at having a globaleaks package that makes use of only debian dependencies;
3. target as reducing as max as possible the dependencies installed using pip, and choose their version properly so that the sub-dependencies of the packages installed in pip are already in debian.

**Comment by evilaliv3** [comment]
Here follow my current analysis:
![screenshot from 2015-12-05 11 03 21](https://cloud.githubusercontent.com/assets/217034/11607266/4922dfe2-9b40-11e5-811d-ca332d3a1828.png)

The living document can be found at: https://docs.google.com/spreadsheets/d/1OR82snOBSdd6miJwwr4yK34KC7rcoIYUI5Iozv2CZ7I/edit#gid=0&vpid=A1

**Comment by fpietrosanti** [comment]
Related tickets #140 #775 #956

**Comment by evilaliv3** [comment]
done and all the requirements are now under testing: https://travis-ci.org/globaleaks/GlobaLeaks

- https://github.com/globaleaks/GlobaLeaks/blob/devel/backend/requirements/requirements-precise.txt
- https://github.com/globaleaks/GlobaLeaks/blob/devel/backend/requirements/requirements-trusty.txt
- https://github.com/globaleaks/GlobaLeaks/blob/devel/backend/requirements/requirements-xenial.txt
- https://github.com/globaleaks/GlobaLeaks/blob/devel/backend/requirements/requirements-wheezy.txt
- https://github.com/globaleaks/GlobaLeaks/blob/devel/backend/requirements/requirements-jessie.txt
- https://github.com/globaleaks/GlobaLeaks/blob/devel/backend/requirements/requirements-stretch.txt

**Comment by evilaliv3** [comment]
@fpietrosanti: we forgotten to analyze the txtorcon requirement!

@meejah can i please ask you to help us on the following analysis?

i think that what we should understand is the following:
1. starting from which version is txtorcon allowing to configure tor hidden services (requirement of globaleaks)
2. starting from which version is txtorcon allowing to start/stop tor (requirement of both globaleaks and tor2web)
3. which is the version of Tor required needed for 1) and 2)
4. will be the above version of txtorcon/Tor included in next stable stretch(debian) / xenial (ubuntu) ?
5. will it be possible to have backports of this requirements on trusty/jessie

@garrettr do you have also these requirements on SecureDrop?

**Comment by meejah** [comment]
I will have to dig into globalleaks code to answer that, as it depends on the method.

If you're using ``TorConfig`` and setting attributes up "by hand" it should work from fairly old versions. ``launch_tor`` was in 0.7.0, but saw improvements and more options up to 0.13.0 (this is probably the version you want for that, as it stopped using a torrc in ``TMPDIR`` and instead passes everything via command-line args). The Tor version shouldn't matter.

Can you point me to the code that configures hidden-services via txtorcon?

The release notes I have are at: http://txtorcon.readthedocs.org/en/latest/releases.html

As to the Debian questions, you'd have to ask Lunar^ or use the Debian package-tracking: https://packages.qa.debian.org/t/txtorcon.html as I don't do the Debian packaging. It looks like "stretch" has 0.14.0 currently (https://packages.debian.org/search?suite=stretch&searchon=names&keywords=txtorcon)

**Comment by evilaliv3** [comment]
ah no, we are still planning the integration of txtorcon and currently all is done manually by a shell script modifying the torrc, so that any suggestion of you is welcome!

anyway yep if 0.13 is complete, for sure both stretch and xenial already have the 0.14 so we are ready! thanks

**Comment by meejah** [comment]
Ah, okay. Then I recommend using the things in the ``endpoints`` if you're comfortable depending on a new-ish txtorcon. Thus, you can use ``TCPHiddenServiceEndpoint`` to set up your service, and that will handle launching a tor instance for you as well -- so, e.g., call ``TCPHiddenServiceEndpoint.global_tor()`` to get a hidden-service endpoint that is on a Tor instance private to your process ("global" refers to "global to the Python process we're running in right now).

See http://txtorcon.readthedocs.org/en/latest/txtorcon-endpoints.html#txtorcon.TCPHiddenServiceEndpoint.global_tor

If you wanted a private tor instance for *each* endpoint you created like that, use ``.private_tor`` instead. In all cases you'll get back a Twisted endpoint upon which you call ``.listen()`` with the factory for your ``Site`` (or whatever is listening there).

Hope this helps. Don't be shy about bugging me in ``#tor-dev`` too if you want :)

**Comment by evilaliv3** [comment]
perfect thanks! going to start testing this integration tonigh!

talk to you on ```#tor-dev``` then!

**Comment by evilaliv3** [comment]
Adding txtorcon 0.14 to requirements along with ipaddr>=2.1.10 that it adds.
The decision of 0.14 is due to the fact that ubuntu/debian versions before xenial/stretch have only txtorcon<=10, so we will have support for full debian packaging with xenial/stratch that currently have 0.14

**Comment by evilaliv3** [comment]
Here comese the updated requirements:
![screenshot from 2016-01-12 22 41 12](https://cloud.githubusercontent.com/assets/217034/12277823/e3e4cf26-b97d-11e5-9f5c-2ee80d41914c.png)

It will be probably possible to remove python-ipaddr by supporting a patch to txtorcon to make it use ipaddress: https://github.com/meejah/txtorcon/issues/153

**Comment by evilaliv3** [comment]
in relation to https://github.com/globaleaks/GlobaLeaks/issues/720 I've verified which distribution have ```haveged``` are available on ubuntu/debian and it seems to me that no issues should exists in supporting it on all the targeted distributions:
- precise: 1.1
- trusty: 1.7c
- xenial: 1.9.1
- wheezy: 1.4.4
- jessie: 1.9.1
- stretch: 1.9.1

**Comment by evilaliv3** [comment]
i've done a recheck today, updating the stretch and xenial shop list so that with the browser crypto read we could also try to deliver it fully debianized.

the document has been updated and the studied dependencies versions have been put under testing in https://github.com/globaleaks/GlobaLeaks/commit/e7c22380eb63f64b79b11a1a66b5320ddeab5f8a

**Comment by adrelanos** [comment]
Could you please also check https://github.com/globaleaks/GlobaLeaks/issues/957?

**Comment by evilaliv3** [comment]
sure @adrelanos; we are planning the integration of txtorcon + tor launched by globaleaks as a subprocess with it and the key stored and loaded onto the database.

all has been already tested, just require time for integration and testing! :)

any update from your side?

**Comment by adrelanos** [comment]
Great!

> any update from your side?

Not sure what you might be interested in? :)

The development version of Whonix, Whonix 14 is capable to run Tor
ephemeral hidden services using applications such as onionshare,
ricochet and ZeroNet. The former two get installed by default (available
from packages.debian.org). ZeroNet is unfortunately not available from
packages.debian.org. Very most likely unMessage and GlobaLeaks can be
made to work in Whonix as well once testable.
