### ISSUE TITLE
Feature: Integrated URL Shortener

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1527]
In relation to https://github.com/globaleaks/GlobaLeaks/issues/1018 it would be valuable to implement an integrated URL shortener.

Such a feature included in globaleaks would help dealing with all the adopters use cases where the single platform is linked by multiple initiative stakeholder and in which each stakeholder require an unique personal link that point to a special context.

This way the administrator will be able to create this shortened urls and point them to the internal url that may vary during time without requiring changes on the stakeholder website.

E.g. the admin will be able to create:
- /u/stakeholder1 -> /#/embedded/receiver=receiverXXX&context=contextYYY
- /u/stakeholder1 ->/#/embedded/receiver=receiverKKK&context=contextZZZ

**Comment by fpietrosanti** [comment]
I'm wondering if this feature shall not be designed by later further designed by:
- assigning receivers
- assigning contexts
- enabling building the "parameters" for an embedded url (selectable, misc)

That way who need to create the embedded url, will be also presented with all the configurable items.

Once implemented, we may open an improved with such an "embedding wizard"

**Comment by evilaliv3** [comment]
![screenshot from 2015-12-18 02 01 15](https://cloud.githubusercontent.com/assets/217034/11886534/58271a4a-a52b-11e5-8ef6-f46e4cbc437e.png)

bam!
