### ISSUE TITLE
Mailflush issue

### ISSUE THREAD

**Issue by IuliiSe** [globaleaks/GlobaLeaks#1532]
15 messages with warnings: 
Job Time Exceeded 2.60.124
"[Mailflush] is taking more than 15 minutes to execute"
[Mailflush] is taking more than 10 minutes to execute
[Mailflush] is taking more than 5 minutes to execute

**Comment by kyrylkov** [comment]
+1

**Comment by evilaliv3** [comment]
Thank you @IuliiSe & @kyrylkov  :)

that is normal given a more complexity of the latest implementation; but mail should work riight?

by the way we are finally near to a release that will fix once for all the resiliency of the mail component :) please take patience for few days

**Comment by IuliiSe** [comment]
No. Mail does not work. Messages are seen only when the receiver logs in. No notifications about new submissions are sent to the receivers email.

**Comment by evilaliv3** [comment]
okay thanks for the feedback. by the way the upcoming release completely rewritten this routines in order to deal with various possibile migration issues so i think for sure it will be solved by that.

sorry for the inconvenience

**Comment by vodkina** [comment]
@evilaliv3, please assign estimate to this issue. Thanks

**Comment by evilaliv3** [comment]
i'm assigning to this the time i'm passing fixing in the general the refactor of the mail routines to make them more resilient, but given that we are near to release the fix this is more an estimation of the past work

**Comment by evilaliv3** [comment]
ok development for addressing these issues is in place and readyt to be shipped in 2.60.125
