### ISSUE TITLE
The Whistleblower Identity field can be customized leading to error

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1542]
The Whistleblower Identity field can be customized leading to error in the submission processing.

This ticket is to prevent Whistleblower Identity field customization (but only configuration), by resetting during the upgrades any previous customization eventually done.

**Comment by evilaliv3** [comment]
This should be now fixed and the changes applied are the following:
- the whistleblower identity field can be now configured and not modified or deleted by the user.
- the whistleblower identity field that is still to be considered experimental is enabled via the experimental feautures enabler.
