### ISSUE TITLE
Automate X.509 certificate issuance and maintenence with Let's Encrypt

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1546]
It would be valuable to integrate support for [Lets's Encrypt](https://github.com/letsencrypt/letsencrypt).

This would make possible to implement https://github.com/globaleaks/Tor2web/issues/252 in a straightforward way!

Upon completion of such an implementation the twisted related code could then made available for integration directly in the twisted library in order to support both the [Twisted](https://github.com/twisted/twisted) and the [Let's Encrypt](https://github.com/letsencrypt/letsencrypt) projects.

Sadly as discussed few months ago with @pde no wildcard certificates will be available (at least for the short term); whenever this will happen it would be possible to integrate this directly inside [Tor2web](https://github.com/globaleaks/Tor2web)

- [x] Select package and implementation of acme protocol: [python-acme](https://letsencrypt.readthedocs.io/projects/acme/en/latest/)
- [x] Complete LetsEncrypt handler for handling of ACME protocol.
- [x] Rework admin/network https interface for LetsEncrypt path
- [x] Author and internationalize text describing briefly LE and where to learn more
- [x] Implement automatic renewal https://github.com/globaleaks/GlobaLeaks/issues/1966
- [x] Implement admin notification on renewal failure https://github.com/globaleaks/GlobaLeaks/issues/1968

**Comment by fpietrosanti** [comment]
Related to #1547

**Comment by fpietrosanti** [comment]
GlobaLeaks must support an preliminary check trough a visual feedback that the intended hostname for the HTTPS is reachable from the internet, and this check must be done trough Tor before enabling the request to activate LetsEncrypt. Only when the "networking" requirements to activate it are checked to be OK (existing hostname in DNS, hostname reachable from the internet on the TCP ports of internet) the enrollment procedure should be started up.

**Comment by virgil** [comment]
I looked into using LetsEncrypt for onion.link but I didn't see any way to
get a wildcard certificate.  So I caved it and just bought a cert from
Comodo.  If LetsEncrypt starts allowing wildcard certs I'm totally in.

-V

**Comment by mithrandi** [comment]
https://pypi.python.org/pypi/txacme is out now; I'm not sure if the lack of wildcard certificates makes Let's Encrypt support a moot point for GlobaLeaks, but if not, the txacme endpoint interface should provide an easy way to integrate Let's Encrypt support into a Twisted application serving TLS over port 443 (ie. an HTTPS server).

**Comment by evilaliv3** [comment]
love! is there by the chance someone working on the packaging of txacme for Debian/Ubuntu? for us would be that important to have this integrated in xenial/stretch because for this releases are including all our dependencies and txacme sould be the only one out :(

answering your question @mithrandi there is no need for the wildcard as globaleaks generally exposes itself through a private tor2web instance. is only for a public tor2web instance like onion.to that would be great to have *.onion.to

is only the generic tor2web instance

**Comment by evilaliv3** [comment]
related: https://github.com/globaleaks/GlobaLeaks/issues/1546

**Comment by NSkelsey** [comment]
This issue has been renamed to reflect the fact that this is now an active deliverable. Looking into the current status of devel with the HTTPS integration done we are left with the following TODOs:

- [ ] Select package and implementation of acme protocol.
- [ ] Complete LetsEncrypt handler for handling of ACME protocol.
- [ ] Rework admin/network https interface for LetsEncrypt path
- [ ] Author and internationalize text describing briefly LE and where to learn more
- [ ] Add admin notification and templates for cert expiration, renewal, and renewal failure.

**Comment by evilaliv3** [comment]
This issue has been renamed to reflect the fact that this is now an active deliverable with an associated milestone: https://github.com/globaleaks/GlobaLeaks/issues?q=is%3Aopen+is%3Aissue+milestone%3A%222.70+-+Letsencrypt%22

In addition i've integrated a check list so to annotate what planned and the state of completion.

**Comment by NSkelsey** [comment]
This has been implemented, tested, and will be release with `v2.70.0`
