### ISSUE TITLE
Enable administrator to configure HTTPS directly from the administration interface

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1550]
This ticket is to enable administrator to configure HTTPS directly from the administration interface.

Actually GlobaLeaks does not support directly HTTPS and there are additional deployment complexity for every deployment when:
- There's no need to hide GlobaLeaks server location
- Whistleblowers or Receivers need to access the system directly without Tor

Tor2web is a complex software that require a system administrator (and not just a globaleaks administrator) with medium-advanced system administration skills with command-line and digital certificate handling, heavily impacting the strategic goal of globaleaks to be "easy to be setup".

For that reason we must introduce support for enabling and configuring HTTPS directly into GlobaLeaks.

GlobaLeaks must support listening on 443 port, binding to that port before dropping root-privileges, and that may require some init/startup changes. 

The administrator must be able to enable also listening on port 80 (HTTP) with automatic redirection to the configured HTTPS port.

The administrator must be able to change the listening port, but this change will require a restart.
this change require a restart of the application. For that reason, after a port-listening change is applied, the administrator is given a overlay message, saying that the system administrator must issue as a linux root user the command "/etc/init.d/globaleaks restart" .Whenever the administrator log-in, if there's a change that has been done that require a restart like the IP address binding/change, he will be informed to restart the software to apply such a changeset.

The HTTPS support must be provided with 3 different deployment scenario (to be prioritized):
1. Deployment with LetsEncrypt #1546 
   1.1 This is to be almost automatic
2. Deployment with assistance in generating the certificate
   2.1 This require the end-user to configure the hostname, generate a CSR (Certificate Signing Request), export a CSR file (to be sent to the CA), import the signed certificate, import the certificate chain with strong validation and integrity checks to be done on all steps.
3. Deployment by importing existing certificate
   3.2 This require the end-user to import a key files, a certificate file and a certificate chain file

Any hostname specified/configured/imported during the HTTPS enabling process shall be automatically put in hostnames to which GlobaLeaks answer requests specified at #1548

**Comment by evilaliv3** [comment]
@fpietrosanti: i think 2 and 3 should be swapped in the priority, as 3 is anyhow preliminar to 2.

**Comment by mttstt** [comment]
I solved installing Apache2, configuring these two line:
ProxyPass / http://127.0.0.1/
ProxyPassReverse / "http://127.0.0.1/

**Comment by evilaliv3** [comment]
@mttstt have you evaluated to adopt [Tor2web](https://github.com/globaleaks/Tor2web) ? 

Tor2web is specialized HTTPS proxy that we develop specifically for globaleaks and tor2 onion services in general.

It can be installed on the same server or on an second one if you would like to preserve the anonymity of were the globaleaks platform is.
The connection between Tor2web and GlobaLeaks can be in simple IP:Port proxy as you are doing with Apache or can be a Tor connection.

**Comment by fpietrosanti** [comment]
This ticket is about implementing The software feature in GlobaLeaks. 

Apache reverse proxy is not supported and it's outside the Security threat model of the platform. 

Do follow Tor2web integration guide to achieve integration with https in the way it's software supported:
https://github.com/globaleaks/GlobaLeaks/wiki/Installing-GlobaLeaks-Tor2web-Letsencrypt

**Comment by mttstt** [comment]
Yes I know about future about Tor2Web, but how you said in the first post "Tor2web is a complex software..." and there's no always need to hide GlobaLeaks server location.
My proposal seems to me an effective solution, anyway do you think that this solution has potential security vulnerabilities ?

**Comment by fpietrosanti** [comment]
Yes, it'a outside the security threat model of GlobaLeaks.
No Tor detection, no Tor automatic redirection, no awareness of anonimity status of the Whistleblower in GlobaLeaks because of missing Tor2web in-band signaling of those information, no HTTPS hardening, no TLS hardening.

**Comment by vodkina** [comment]
Estimated at 7, as agreed with @evilaliv3

**Comment by NSkelsey** [comment]
Ready for release.
