### ISSUE TITLE
Python3 Compatibility

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1551]
Starting from Ubuntu 16.04 (LTS) [21th April 2016] ubuntu will include by default support for only python 3, so this is becoming a fundamental requirement: http://summit.ubuntu.com/uos-1511/meeting/22568/python3-only-on-the-images/

As not all libraries will ever be compatible for python 3, there will be for sure the possibility to still use python 2 but this would eventually require to go out of the official ubuntu support.

This ticket is to discuss about the requirements for making GlobaLeaks compatible with python3.

All the libraries that we are using are already going in the direction of supporting python 3 except Cyclone (https://github.com/fiorix/cyclone/issues/171) and Storm (https://bugs.launchpad.net/launchpad/+bug/1530734)

If supporting cyclone in this won't be an issue, this can't be said for storm that is nowadays an abandoned project; i've opened a ticket on their bugtracker in order to see the answer and decide if we have really to go for a different ORM.
Alternative solutions if we go for this are:
- twistar (that is the only native twisted solution) that will be probably packaged for debian in the short term and that wont't be difficult to package by ourself being a native python package with no C bindings
- django orm (and if we go for this i think we should decide to abandon twisted with all the consequences :) )
- sqlalchemy (that lacks of official support for twisted and i don't think will be a good soolution

among all i'm more for experimenting with twistar.

**Comment by fpietrosanti** [comment]
Regarding twistar (last commit Oct 2015), it would be interesting to analyze also the @fiorix txdbapi https://github.com/fiorix/txdbapi (last commit 2012) if provide some specific advantage over twistar uses?

Twango, the django-orm/twisted project at https://github.com/gdoermann/twango has last commit from 2014, there's a lot of cooperation directions between twisted and django reading at June 2015 blogpost http://reinout.vanrees.org/weblog/2015/11/06/twisted-and-django.html but as far as i understand the main actual point of cooperation has been running django application trough the WSGI native interface on Twisted, but no specific insight/reading of django-orm. It would be nice to ask that community if they have some plan to bridge/extend the concept of twango by default in Twisted db API!

**Comment by NSkelsey** [comment]
Python 2.7 is shipping on 16.04.

**Comment by fpietrosanti** [comment]
Isn't that ticket about Python 3 compatibility anyhow, regardless Ubuntu 16.04 ?

**Comment by NSkelsey** [comment]
Didn't mean to close sorry.

**Comment by evilaliv3** [comment]
As update with this ticket a rewritten minimal REST API has been written and is going to be integrated in the stable brach.

The rewrite remove the cyclone dependency and its code is just an implementation of the same few functionalities used in the cyclone libraries, inspired from python-klein but  with the addition of some authentication decorators proper of the application. The aim of the new implementation expected to not grow in the capabilities is to offer a minimal set of enforced checks able to protect from the most common developers errors (e.g. forgetting authentication decorators and leaving authenticated resources accessible from unauthenticated users)
