### ISSUE TITLE
iframe security: custom X-Frame-Options and Content-Security-Policy headers

### ISSUE THREAD

**Issue by marceloomens** [globaleaks/GlobaLeaks#1552]
It would be great to be able to specify

```
X-Frame-Options: ALLOW-FROM uri
```

in combination with

```
Content-Security-Policy: frame-ancestors uri
```

We'll need the combination because X-Frame-Options is deprecated; the ALLOW-FROM directive was never supported by Chrome and Safari, whereas I think that Content-Security-Policy is not widely supported by IE.

This will increase security of Globaleaks implementations based around iframes. The current implementation basically only allows you to 'drop' the X-Frame-Options altogether (thereby dropping the default SAMEORIGIN policy).

See also:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/X-Frame-Options
- https://developer.mozilla.org/en-US/docs/Web/Security/CSP
- http://content-security-policy.com/
- http://www.html5rocks.com/en/tutorials/security/content-security-policy/

**Comment by evilaliv3** [comment]
Cloasing as duplicated of https://github.com/globaleaks/GlobaLeaks/issues/1998
