### ISSUE TITLE
Separate "Enable recipient selection" from "Show recipient's information on the status page of the submission" in context configuration

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1556]
It would be valuable to separate "Enable recipient selection" from "Show recipient's informormation on the status page of the submission" in context configuration.

In fact it user may want to prevent leaving the whistleblower the possibility to select recipients (that can be considered simply as "the organization", while still wanting to show to the whistleblower data on the accesses to the status page of the submissions by the internal users of the organization.

**Comment by evilaliv3** [comment]
in addition aside from the change i think that the current "Enable recipient selection step" is confusing in relation to the fact that this configuration changes also what happen on the status page of the submission"

**Comment by fpietrosanti** [comment]
In the status page there are two different recipient information:
- If they read the submission
- The selection to enable messaging individually

You may wish to avoid displaying the list of recipients and if they have read it or not, but you may still wish to leave their username present in the selection from the recipient on the messaging.

Btw, do we have a use-case on the project we're following about that?

**Comment by evilaliv3** [comment]
I would keep things separated from the receipients selection in messages.
If you enable private messages is obvious that you have receiver selection for the destination and that you want it.

This ticket is related only to the visibility of the access with a 'per receiver' detai or as a whole (read if at least one receiver has read)

**Comment by evilaliv3** [comment]
and no there is no project related specifically; simply now there is some confusion in the user that do not want receiver selection but want to show who accessed the data. 

they simply canno do that right now and i would find it valuable.
