### ISSUE TITLE
Activation Wizard does not handle in the UX session timeouts

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1561]
When a user is executing the Activation Wizard, if does not do anything for a certain amount of time (ie: 20 minutes), then click "Next", the interface will wrongly report "Congratulations!", then clicking on "Go to the administration interface" will bring the user back to the beginning of activation wizard (with the language selection).

**Comment by evilaliv3** [comment]
this issues does not exists anymore because the wizard has been refactored as an atomic operation.
