### ISSUE TITLE
Bottone invia non funzionante (Submit button should be disabled)

### ISSUE THREAD

**Issue by AlessioZa** [globaleaks/GlobaLeaks#1563]
Salve,
ho appena installato la nuova versione nuova di Globaleaks 2.60.133

Riscontro un problema in quanto non riesco a chiudere le segnalazioni. Una volta definiti quali sono i campi obbligatori e non, all’interno della configurazione del contesto, se cero di effettuare una segnalazione alla fine della procedura, rispettando l’obbligatorietà dei campi, il tasto invia non è accessibile.

Ho utilizzato firefox 44.0 e i.e. 11

Grazie per la collaborazione

**Comment by evilaliv3** [comment]
Grazie @AlessioZa per aver segnalato il possibile malfunzionamento.
Come ha potuto vedere (https://github.com/globaleaks/GlobaLeaks/issues/1558) lo stesso probabile malfunzionamento era stato verificato da un altro utente, motivo per cui stiamo provvedendo a verificare e nel caso il malfunzionamento venga confemrato pubblicheremo una correzione quanto prima.

Se ha modo di riprodurre deterministicamente l'errore con una particolare configurazione potrebbe gentilmente indicarcela? questo velocizzerebbe le nostre operazioni di verifica. grazie.

**Comment by AlessioZa** [comment]
Grazie per la risposta.
Ho provato form molto semplici con e senza campi "richiesti": il submit è sempre disabilitato.
Ho fatto un semplice debug con firefox cherileva solo questo avviso:

mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create scripts.js:887:9


Attendo fiducioso.

**Comment by AlessioZa** [comment]
Buongiorno,
avreste novità in merito? 

Grazie

**Comment by evilaliv3** [comment]
Buonasera  @AlessioZa,
non siamo riusciti a riprodurre l'errore che ha segnalato per cui specifiche correzioni non sono presenti.

Non escludo che i recenti sviluppi abbiano eventualmente già risolto la problematica.

Entro la giornata di oggi sara' disponibile una nuova versione 2.60.134 includente solo migliorie di stabilizzazione.

Appena rilasciata provvedo a segnalaglielo qua cosi che possa provare ad aggiornare e vedere se per caso tutto fosse già stato risolto.

**Comment by evilaliv3** [comment]
Ok @AlessioZa se vuole riprovare abbiamo provveduto ad effettuare il rilascio che le dicevo.

**Comment by AlessioZa** [comment]
Grazie mille.

Attendo la sua segnalazione

**Comment by AlessioZa** [comment]
Buongiorno,
in fase di aggiornamento ho rilevato il seguente errore: 

aa-exec:ERROR: profile 'usr.bin.globaleaks' doesnot exist 

[fail]

**Comment by evilaliv3** [comment]
Salve @AlessioZa,
l'errore che ci segnala purtroppo e' stata una regressione avvenuta su un componenete al momento non testato automaticamente.
Abbiamo gia' provveduto a rilasciare una versione che corregge tale difatto.
Scusandoci del disturbo la invitiamo ad aggiornare alla versione 2.60.135

Grazie

**Comment by AlessioZa** [comment]
Salve,
ho eseguito con successo l'aggiornamento tuttavia il problema permane. Che tipo di controlli vengoo effettuati sul bottone di invio? Potrebbe essere legato alle impostazioni del file "default"?

Grazie

**Comment by evilaliv3** [comment]
Cosa intende con opzione del file default?

Posso chiederle di fare le seguenti prove:
1) crei un nuovo contesto e vi associ un ricevente e verifichi se sul nuovo
contesto il problema sussiste?
2) se il problema sussiste con 1) provi a disabilitare il meccanismo di
sicurezza proof of work; trova una casella per disabilitarlo nella sezione
"Configurazione avanzata"

la sua installazione e' gia' esposta pubblicamente? se si volentieri
possiamo provvedere a verificare cosa succede direttamente

in generale se le torna piu comodo puo' contattarci via mail direttamente:
support@logioshermes.org

grazie

**Comment by AlessioZa** [comment]
Il file di configurazione dove sono indicati per esempio gli host list.

Ho provato sia il punto 1) sia il punto 2) ma il bottone "Invia" è sempre non abilitato.

L'installazione non esposta pubblicamente.

Sa darmi ulteriori indicazioni?

Grazie

**Comment by AlessioZa** [comment]
Salve,
il problema sembrava dipendere da una impostazione avanzata sull'https: disabilitandola e riabilitandola è tornata afunzionare.

**Comment by mttstt** [comment]
Ho lo stesso problema con la nuova versione 2.64.6 e anche con la versione precedente 2.64.5.

**Comment by NSkelsey** [comment]
@mttstt se non ha iniziato la piattaforma correttamente vedrò questo button disattivato.

Potrebbe:
- Their are no receivers with PGP keys assigned to the context. (you can disable this feature)
- All of the required questions in your form are filled out.
- The logs of the server are reporting errors
