### ISSUE TITLE
W: GPG error: http://deb.globaleaks.org trusty/ Release: The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <...>

### ISSUE THREAD

**Issue by kyrylkov** [globaleaks/GlobaLeaks#1567]
The error we're getting now on `Ubuntu 14.04` running `apt-get update`

**Comment by evilaliv3** [comment]
Thank you sergiy; it appear that due to a failure in the release process the repository was not signed.

Could you recheck if it is now working for you?

**Comment by fpietrosanti** [comment]
We may put this under monitoring, with the cloud http monitoring system requesting a shell script that will trigger on travis the basic installation process, that would quickly bring detection of repository integrity issue like this in a self-contained way

**Comment by kyrylkov** [comment]
@evilaliv3 gone now

**Comment by evilaliv3** [comment]
thanks @kyrylkov
