### ISSUE TITLE
How to decrypt the PGP file?

### ISSUE THREAD

**Issue by alepartenza** [globaleaks/GlobaLeaks#1570]
Hi
When the receiver receives and download a PGP file format, as it does to decrypt it?

**Comment by NSkelsey** [comment]
Hi @alepartenza,

You need to use the tool you used to generate the PGP key to decrypt it. 

You might have used [GPG](https://www.gnupg.org/index.html) to generate the receiver's key. If that is the case then you might have to use the command line to decrypt the file.

This means running a command in a terminal window like:

```bash
gpg --output doc.txt --decrypt doc.txt.gpg
```
