### ISSUE TITLE
Error Missing key triggered by score

### ISSUE THREAD

**Issue by AlessioZa** [globaleaks/GlobaLeaks#1572]
Buongiorno,
in fase di inserimento di ulteriore steprilevo ilseguente errore:

Missing key troggered by score

Non riesco a capire il motivo.

Grazie

**Comment by evilaliv3** [comment]
Salve alessio,

Ha ragione lei e questo e' un difetto del corrente rilascio che verrà
risolto con un aggiornamento pubblicato domani.

Le darò qui notifica a rilascio effettuato.

Grazie

**Comment by evilaliv3** [comment]
Fixed in commit https://github.com/globaleaks/GlobaLeaks/commit/8c2f6593c7b15888fdf8f6e6b5b0a71780ec2948

Released in version 2.60.138
