### ISSUE TITLE
 Install script broken on up-to-date Ubuntu 14.04

### ISSUE THREAD

**Issue by capo10** [globaleaks/GlobaLeaks#1573]
```
root@fischietto:/home/soffiatore# ./install-globaleaks.sh
Performing GlobaLeaks installation on Ubuntu - trusty
Checking preliminary GlobaLeaks requirements
 + apt-key requirement meet
 + apt-get requirement meet
Adding GlobaLeaks PGP key to trusted APT keys
Running: "apt-key add /tmp/globaleaks_key.25014"... SUCCESS
Running: "rm -f /tmp/globaleaks_key.25014"... SUCCESS
Running: "apt-get update -y"... FAIL
COMBINED STDOUT/STDERR OUTPUT OF FAILED COMMAND:
Scaricamento di:1 http://deb.globaleaks.org trusty/ InRelease [758 B]
Splitting up /var/lib/apt/lists/partial/deb.globaleaks.org_trusty_InRelease into data and signature failedIgn http://deb.globaleaks.org trusty/ InRelease
E: Errore GPG: http://deb.globaleaks.org trusty/ InRelease: Il file con la firma in chiaro non è valido, ottenuto "NODATA" (la rete richiede autenticazione?)
```

Thank   you
Angelo

**Comment by capo10** [comment]
Ubuntu 14.04.3 LTS

**Comment by fpietrosanti** [comment]
Can you try again?

**Comment by capo10** [comment]
Hi Fabio, can I speak in italian?

I find this link for the same problem
http://pountex.altervista.org/risolvere-bug-apt-get/?doing_wp_cron=1455715421.2268400192260742187500

and now i run  ./install-globaleaks.sh


root@fischietto:/home/soffiatore# ./install-globaleaks.sh
Performing GlobaLeaks installation on Ubuntu - trusty
Checking preliminary GlobaLeaks requirements
 + apt-key requirement meet
 + apt-get requirement meet
Adding GlobaLeaks PGP key to trusted APT keys
Running: "apt-key add /tmp/globaleaks_key.10944"... SUCCESS
Running: "rm -f /tmp/globaleaks_key.10944"... SUCCESS
Running: "apt-get update -y"... SUCCESS
Installing software-properties-common
Running: "apt-get install software-properties-common -y"... SUCCESS
Adding Ubuntu Universe repository
Running: "apt-get update -y"... SUCCESS
Running: "apt-get install globaleaks -y"... FAIL
COMBINED STDOUT/STDERR OUTPUT OF FAILED COMMAND:
Lettura elenco dei pacchetti...
Generazione albero delle dipendenze...
Lettura informazioni sullo stato...
E: Impossibile trovare il pacchetto glob

Grazie
Angelo


2016-02-17 14:25 GMT+01:00 Fabio (naif) Pietrosanti <
notifications@github.com>:

**Comment by capo10** [comment]
I resolved
 I disabled the firewall
I disabled the content filtering gateway of my!
Thank You Fabio

2016-02-17 14:35 GMT+01:00 Angelo Benedetto Capodieci <angelo@capodieci.it>:
