### ISSUE TITLE
Enable recipients to export submission from the tip list page

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1580]
As an improvement for https://github.com/globaleaks/GlobaLeaks/issues/931 it would be valuable to add an export button to the tip list page.

This would make more easy for the user to decide what to download having a look to the submissions resume.

**Comment by NSkelsey** [comment]
When the recipient selects multiple tips and clicks export the angular app will initiate multiple zip file downloads.

**Comment by evilaliv3** [comment]
good to go

**Comment by NSkelsey** [comment]
The export button can move down into the tip list itself, but the mass selection does not work. Currently this is what I have -- which is not good:

<img width="611" alt="screen shot 2016-03-18 at 7 51 35 pm" src="https://cloud.githubusercontent.com/assets/1095794/13894862/f082778a-ed42-11e5-9ff6-72e1e779537f.png">

**Comment by NSkelsey** [comment]
The new format looks like this at rest:
![screen shot 2016-03-21 at 11 30 15 am](https://cloud.githubusercontent.com/assets/1095794/13923800/61a12742-ef58-11e5-80f6-3ea086e3e4b5.png)

And when hovered:

![screen shot 2016-03-21 at 11 30 30 am](https://cloud.githubusercontent.com/assets/1095794/13923808/67474672-ef58-11e5-89ea-f9e1e1f9c2cb.png)

**Comment by evilaliv3** [comment]
allright :)

probably we would avoid exporting the tip links as i was doing (ret['export'] = '/rtip/' + rtip.id + '/export'
) but have the client calulate them;
this way we do not lose backend time on something that can be delegated to the client and we keep the json answers smaller?

**Comment by NSkelsey** [comment]
Okay. That is fair.

**Comment by NSkelsey** [comment]
What the UI looks like when delete or postpone is not enabled and the select box is hidden:

![screen shot 2016-03-21 at 11 30 22 am](https://cloud.githubusercontent.com/assets/1095794/13924809/182b17a4-ef5c-11e5-9875-1b269addf738.png)

**Comment by NSkelsey** [comment]
#1595 addresses this issue.
