### ISSUE TITLE
The whistleblower body page is blank

### ISSUE THREAD

**Issue by mttstt** [globaleaks/GlobaLeaks#1582]
After some customizations to the interface as admin I had problems with the interface of the whistleblower. After pressing the button "blow the wistle" (the message "Warning! You are not anonymous" are disabled) the body of the page "Blow the Whistle" is empty.
This thing happened to me with two separate installations.

Ubuntu 14.04
Release:2.60.143
Language Italian

**Comment by evilaliv3** [comment]
@mttstt could you please check that:

1) you have at least a configured context with a configured questiionnaire
2) you have at least a configured recipient
3) the context and the recipient are associated (you can do the association both from the context and recipient configuration)

**Comment by mttstt** [comment]
Thanks next monday I will check that.

**Comment by mttstt** [comment]
Ok I solved, but I had to delete and recreate my configurations.

**Comment by evilaliv3** [comment]
thanks for the feedback @mttstt;
in case you came out to reproduce the issue please annotate it here :)
