### ISSUE TITLE
Implement HTTP Basic Authentication to allow to protect the deployment during development

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1589]
It has been requested by various adopters for the possibilty to protect the deployment during development in order to not disclose what under development before internal review and proper launch.

This is a feature missing since time that would be easy to be implemented by supporting HTTP Basic Authentication as by [RFC2617](https://tools.ietf.org/html/rfc2617).

The Admin should be able to enable such a feature via Advanced Settings by having the possibility for configuring a username and a password.

**Comment by evilaliv3** [comment]
Implemented:
- backend implementation
- clientside UI
- migration scripts

the following are the screenshots of the UI

![screenshot from 2016-03-18 15 02 01](https://cloud.githubusercontent.com/assets/217034/13879983/81b53626-ed1a-11e5-80c0-02c940b3fe52.png)

![screenshot from 2016-03-18 15 02 01](https://cloud.githubusercontent.com/assets/217034/13880019/a89137f4-ed1a-11e5-9952-ff6f2f1857fc.png)

**Comment by evilaliv3** [comment]
Here is the latest interface designed together with @NSkelsey 

we discussed that a "Danger" clarification is needed and the password should be explicilty be shown in plaintext to make it definitely clear that the feature is not implemented for security reasons.

![screenshot from 2016-03-18 19 58 52](https://cloud.githubusercontent.com/assets/217034/13888907/26b70b94-ed44-11e5-9b8a-9e615b98c11f.png)

**Comment by NSkelsey** [comment]
PR #1589 closes this.

**Comment by evilaliv3** [comment]
Update: this feature was abused for offering platforms to whistleblowers inside an intranet and was for this reason removed long time ago.
