### ISSUE TITLE
Implement context selection following same UI of recipients cards

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1593]
Various adopters (basically all the ones that implement multiple context) have designed a context selection on an external website by implementing the context selection following somehow the same UI of our recipients cards.

It would be interesting as in previous discussed by @vecna and commonly implemented in the main whistleblowing software a context selection based on cards that would involve putting a logo and a description.

This would simplify the user interaction as the UI would require the user to perform a single click in order to move select the context without having to open a dropdown and then selecting an option based simply on its name.

**Comment by fpietrosanti** [comment]
Dup of Ticket #354

**Comment by evilaliv3** [comment]
finally you  found it! closing this as duplicated.
