### ISSUE TITLE
Improve browsertesting of file downloads that is currently performed only on Chrome

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1596]
Currently the saucelabs browser-testing of the file downloads and of the tip export is performed only on Chrome; the reason behind that all the browsers except Chrome ask for user input in case of file downloads.

It would be nice if we could improve this situation covering at least Firefox/Tor browser for which a known workaround exists: https://stackoverflow.com/questions/31526120/download-file-on-firefox-with-protractor

**Comment by NSkelsey** [comment]
I have the work around implemented locally. I will integrate it with stronger testing of the downloaded files as well.

**Comment by evilaliv3** [comment]
K! keep it small for now ;)

simply triggering the file download on 2 browsers covering Firefox/Tbb in addition to the only Chrome will be an important improvement.

we will postpone the retesting on the zipfile when we will have the browsercrypto and all need to be clientside! ouch! ouch!

for the improvements discuss it here and in general open new tickets when you see something valuable so that also if the time for all is missing we can remember to do it later! and help me doing the same if you see me fighting on a ticket :)

**Comment by NSkelsey** [comment]
The branch test/1596 attempts to address this and some of the small TODOs within `tests-globaleaks-process.js`.

https://github.com/globaleaks/GlobaLeaks/tree/test/1596

**Comment by NSkelsey** [comment]
To accomplish this task, any local development can employ `saucelabs` APIs to verify functionality.

**Comment by evilaliv3** [comment]
what do you mean? i would suggest if you are confident that it can be reade propose it as pull request! :)
