### ISSUE TITLE
Icons are not visible on IE/EDGE

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1601]
Bootstrap Icons appear to not be visible on IE/Edge.

The cause still require to be investigated.

**Comment by evilaliv3** [comment]
@fpietrosanti: I've never noticed the bug but it may be present since time with people people simply not reporting it?

i may lie in the wrong content-type that the application send out for the fonts:
![screenshot from 2016-03-24 12 46 42](https://cloud.githubusercontent.com/assets/217034/14016170/ae575594-f1be-11e5-8e27-550d9a4fb892.png)

as you can see some are delivered as text/html


p.s. Saucelabs is great and doing science matter:
![screenshot from 2016-03-24 12 43 06](https://cloud.githubusercontent.com/assets/217034/14016196/d0fadc74-f1be-11e5-933b-1a053fe8a52c.png)
![screenshot from 2016-03-24 12 43 28](https://cloud.githubusercontent.com/assets/217034/14016204/d558cb0a-f1be-11e5-8369-a57b18024c76.png)

**Comment by fpietrosanti** [comment]
That's probably because we disable IE Mime Sniffing (X-Content-Type-Options: nosniff) from https://docs.google.com/document/d/1SMSiAry7x5XY9nY8GAejJD75NWg7bp7M1PwXSiwy62U

**Comment by evilaliv3** [comment]
But we are not doing it recently; so maybe this bug exists since ever?

Anyhow currently on python side we were guessing the mime type given the extension.

with the same library (the standard python one) i'm able to do the following:
- read the mime type and see if it is a known one with read_mime_type
- if None is returned guess it based on the extension as we are doing.

https://docs.python.org/2/library/mimetypes.html

**Comment by evilaliv3** [comment]
I've partially addressed the issue adding some missing mimetypes that are now delivered correctly.

Anyhow this has not solved the problem:
![screenshot from 2016-03-24 15 13 07](https://cloud.githubusercontent.com/assets/217034/14019632/16028280-f1d4-11e5-8217-a6d3d64cfeed.png)

**Comment by evilaliv3** [comment]
The BUG was lying in IE/Edge not loading fonts when the cache is not allowed; this is crazy but it is.

So the only fix possible for allowing bootstrap fonts is:
```python
        # to mitigate information leakage on Browser/Proxy Cache
        if self.request.uri.startswith('/fonts/') and re.search('MSIE|Edge', self.request.headers.get("User-Agent", "")):
            # Special condition: https://github.com/globaleaks/GlobaLeaks/issues/1601
            self.set_header("Cache-control", "no-cache, must-revalidate")
        else:
            self.set_header("Cache-control", "no-cache, no-store, must-revalidate")
            self.set_header("Pragma", "no-cache")
```

I'm going to open a ticket to asses the forensic traces that this would open on IE/Edge and in general to assess on every browser the possible traces left by downloading the bootstrap fonts.
