### ISSUE TITLE
Integrate Mocha tests into Grunt and Travis Builds

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1602]
This one should be easy. The Frontend api tests are not run in the travis builds, but they should be.

A command like this runs them:
```
> client/node_modules/mocha/bin/mocha -R list client/tests/api/test_00* --timeout 30000
```

**Comment by evilaliv3** [comment]
well done! when is thicketed it's there! ;)

as estimation yep it's totally easy to be done, i've already done it but simply forgot this.

i will pick up this and do when i will be tired of doing something more needed! ;)

**Comment by NSkelsey** [comment]
The new devDependency which I have added is: https://github.com/pghalliday/grunt-mocha-test

After some scrutiny the group seems fine. However it seems to me that this project could have 3 less dependencies if a simple exec command was used inside of the Gruntfile:

```
var sys = require('sys')
var exec = require('child_process').exec;
function puts(error, stdout, stderr) { sys.puts(stdout) }
exec("./node_modules/mocha/bin/mocha -R list tests/api/test_*.js -timeout=30000", puts);
```

@evilaliv3 for future reference which one do you prefer?
