### ISSUE TITLE
The install script must block installation on non-supported platform

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1612]
The install script must block installation on non-supported platform, informing the user that he is trying to install on a non-supported platform (everything except Ubuntu 14.04).

The end-user shall be given the opportunity to re-start the install script with a command-line parameter to bypass this check, that's self-explatory, like --yes-i-know-what-i-m-doing-the-planet-will-self-destroy .

I've been supporting an end-user installin globaleaks on a Debian 7.4 (failing, but that's not the problem, it's not supported debian), never receiving an information that he was installing globaleaks on a unsupported platform, so going into an erroneous/possibly-problematic condition.

Performing GlobaLeaks installation on Debian - wheezy
Checking preliminary GlobaLeaks requirements
 + apt-key requirement meet
 + apt-get requirement meet
Adding GlobaLeaks PGP key to trusted APT keys
Running: "apt-key add /tmp/globaleaks_key.12329"... SUCCESS
Running: "rm -f /tmp/globaleaks_key.12329"... SUCCESS
Running: "apt-get update -y"... FAIL
COMBINED STDOUT/STDERR OUTPUT OF FAILED COMMAND:
Hit http://debian.furanet.com wheezy Release.gpg
Ign http://debian.furanet.com wheezy Release.gpg
Hit http://debian.furanet.com wheezy Release
Hit http://debian.furanet.com wheezy Release
Ign http://debian.furanet.com wheezy/main amd64 Packages/DiffIndex
Hit http://debian.furanet.com wheezy/main amd64 Packages
Hit http://debian.furanet.com wheezy/main amd64 Packages
Hit http://debian.furanet.com wheezy/contrib amd64 Packages
Hit http://debian.furanet.com wheezy/non-free amd64 Packages
Ign http://debian.furanet.com wheezy/contrib Translation-en
Ign http://debian.furanet.com wheezy/main Translation-en
Ign http://debian.furanet.com wheezy/non-free Translation-en
Ign http://debian.furanet.com wheezy/main Translation-en_US
Ign http://debian.furanet.com wheezy/main Translation-en
Ign http://deb.globaleaks.org unstable/ Release.gpg
Ign http://deb.globaleaks.org unstable/ Release
Ign http://deb.globaleaks.org unstable/ Sources/DiffIndex
Ign http://deb.globaleaks.org unstable/ Packages/DiffIndex
Ign http://deb.globaleaks.org unstable/ Translation-en_US
Ign http://deb.globaleaks.org unstable/ Translation-en
Err http://deb.globaleaks.org unstable/ Sources
  404  Not Found
Err http://deb.globaleaks.org unstable/ Packages
  404  Not Found
W: There is no public key available for the following key IDs:
7638D0442B90D010
W: Failed to fetch http://deb.globaleaks.org/unstable/Sources  404  Not Found

W: Failed to fetch http://deb.globaleaks.org/unstable/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by evilaliv3** [comment]
This ticket re-proposes something already said and discussed in the past; now i'm changing also my vision but this ticket is probably duplicated!

the warning exists already, but it still consider wheezy and jessie as supported platform.

i'm going to leave supported only the Ubuntu LTS.

**Comment by evilaliv3** [comment]
In addition the person that was setupping globaleaks was using an installscript outdated;  the unstabe repository not exists since we started providing different packages for different distributions.
