### ISSUE TITLE
Adopt rtlcss in order to deal with automatic handling of rtl CSS files whenever possible

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1621]
The [rtlcss](https://github.com/MohammadYounes/rtlcss) by @MohammadYounes seems to work really well in handling automagically RTL conversion of CSS written for LTR.

That library is already used by wordpress and is under evaluation by the bootstrap: https://github.com/twbs/bootstrap/issues/19555

It would be interesting to adopt it in the project instead of caring of all manually

**Comment by NSkelsey** [comment]
Are you thinking that this will be implemented as a compiled CSS file that is used only when an RTL language is chosen?

This seems like a win-win.

**Comment by evilaliv3** [comment]
In general i do not like that much the solutions that dupliate the file cause they leak information, like that the user is an RTL user, leak a lot, but we can evenually serve anyhow both the files and use one of them on the client. The same apply sadly for the translations that generally are really bigger, but we can evaluate to gzip them inside the client so to pack them and reduce their size.

**Comment by evilaliv3** [comment]
Having a single file is an option discussed by in https://github.com/MohammadYounes/rtlcss/issues/34 and doable with https://github.com/rtsao/postcss-rtlcss-combined but as rightly identified by @MohammadYounes that could lie various isues due to the css hierarchies so for the meantime let's simply accept to have two different files.

**Comment by NSkelsey** [comment]
@evilaliv3 you are in general referring to the issue of analysis of HTTPS traffic. That issue is larger in scope than one or two CSS files.

My understanding of the Tor browser was that this issue is addressed by noise generated in the Tor network.

**Comment by MohammadYounes** [comment]
There is also [postcss-inline-rtl](https://github.com/jakob101/postcss-inline-rtl) which inlines the minimum amount of RTL CSS you need and solves the specifity problem.

**Comment by evilaliv3** [comment]
thanks @MohammadYounes! we will keep that in mind!

**Comment by evilaliv3** [comment]
Implemented! if you would like to cite us as your early users we would love that! :)

GlobaLeaks, the first open-source whistleblowing framework built using AngularJS, Bootstrap and Twisted!

**Comment by evilaliv3** [comment]
![screenshot from 2016-04-02 01 28 06](https://cloud.githubusercontent.com/assets/217034/14222662/99d1d55c-f873-11e5-97a8-bdaeda074a49.png)

**Comment by MohammadYounes** [comment]
Sure, update the readme and send a PR. 

Also [RTL-bootstrap](https://github.com/MohammadYounes/RTL-bootstrap/tree/3) might be of interest to you (also contains JS components RTL support)

**Comment by evilaliv3** [comment]
Thanks.

Yes all our interest in rtlcss is mainly for boostrap, but we found RTL-bootstrap still not not handled that well and not aligned with bootstrap 3.3.6 and the latest patches; Would it take time to do a proper clean patching?

p.s. i've already tried also ```postcss-inline-rtl``` but  it seems to have some defect:

![screenshot from 2016-04-02 02 25 39](https://cloud.githubusercontent.com/assets/217034/14223107/63c9ff5a-f87a-11e5-9995-7fb5e29dd7c3.png)


The code of the nav is a standard use of some Bootstrap classes so probably simply using rtlcss works best now:

```html
<ul class="nav nav-pills nav-stacked">
  <li data-ng-class="active.content">
    <a href="#/admin/content">
      <i class="glyphicon glyphicon-chevron-right"></i>
      <span data-translate>General settings</span>
    </a>
  </li>

  <li data-ng-class="active.users">
    <a href="#/admin/users">
      <i class="glyphicon glyphicon-chevron-right"></i>
      <span data-translate>User management</span>
    </a>
  </li>
...
</ul>
```

\cc @jakob101

**Comment by jakob101** [comment]
I'd like to see what's the issue with postcss-inline-rtl, and resolve it :) 
I'm out of the country but will be back on monday. Can we talk more then?

**Comment by evilaliv3** [comment]
sure @jakob101, reach me even on skype if you like; my nick handle is 'evilaliv3'

**Comment by MohammadYounes** [comment]
I'll rebase with bootstrap master later today.

**Comment by evilaliv3** [comment]
great @MohammadYounes!

let me know if i can help somehow. what would be great instead of a simple rebase would be to do a patching with few organized commits atop of a clean 3.3.6 that is likely to be the final stable version of bootstrap;

probably something done with rtlcss/postcss-inline-rtl is likely to be integrated in bootrap and would be a great benefit for the community out there: https://github.com/morteza/bootstrap-rtl/issues/98

[https://github.com/twbs/bootstrap/issues/19555]

**Comment by MohammadYounes** [comment]
Currently it's 3.3.5 ([comparison](https://github.com/twbs/bootstrap/compare/v3.3.5...MohammadYounes:3)). It has 1 extra feature that [wasn't merged](https://github.com/twbs/bootstrap/pull/14818). 

I thought about sending a PR, but they made it clear no RTL support will be added to v3

**Comment by evilaliv3** [comment]
Okay, my suggestion is to squash it a little having in this order to have atop of 3.3.6
- a commit that rtlcss
- few clean commit that have the eventual patchs
- a last commit with the build

i'm unsure if it would be a good result to relase it using postcss-inline-rtl so to have a single file that can do both depending on the rtl direction.

**Comment by MohammadYounes** [comment]
Yeah, using postcss-inline-rtl will make it easier for distribution. I'll do it later tonight :)

**Comment by MohammadYounes** [comment]
I pushed [inline-rtl](https://github.com/MohammadYounes/RTL-bootstrap/tree/inline-rtl) branch, to get a working local build, postcss-inline-rtl requires the following updates:

* adding `float` to the always convert list ([PR](https://github.com/jakob101/postcss-inline-rtl/pull/2)) - without this justified button groups will be broken.
* account for comment nodes when removing empty rules ([PR](https://github.com/jakob101/postcss-inline-rtl/pull/3)) - without you'll get a bunch of lint errors.
* ability to extend the list of properties to convert ([Issue](https://github.com/jakob101/postcss-inline-rtl/issues/4)) - without this directional icons are not flipped and carousel nav icons will be revered.


:sleeping:  :wave: 
.

**Comment by MohammadYounes** [comment]
A preview of the docs can be found @ http://mohammadyounes.github.io/RTL-bootstrap/inline

**Comment by jakob101** [comment]
You, my man, are great!

Thanks, I missed that.

Hope you had a good night sleep :)

**Comment by MohammadYounes** [comment]
Thanks  :)

**Comment by evilaliv3** [comment]
This is amazing!

other suggestions that comes to my mind:
- As bootstrap releases versions with numbering ```X.Y.Z```, let's start releasing ```X.Y.Z-K``` or ```X.Y.Z.K``` depending if the first is standard or not; e.g. would you please release a ```3.3.6-1```
- would you please tag a release, put in on bower and we will start using it!

question: we are using https://github.com/angular-ui/bootstrap; is there some particular tweak you did to the official bootstrap JS that should be probably be done there (p.s. i do not want you to look at the whole code, simply guess given your experience).

reference ticket: https://github.com/angular-ui/bootstrap/issues/4762

**Comment by evilaliv3** [comment]
thanks @MohammadYounes you are doing really an amazing job! :)

**Comment by MohammadYounes** [comment]
@evilaliv3 Thanks :)

The only change to JS was in [tooltip placement](https://github.com/MohammadYounes/RTL-bootstrap/commit/3be91ac69ddd92a47e1e53bcebe2b80b3d04b30e#diff-f3e99e0bb007ace7a370f0492b9cb5ab) since it was done via JS not CSS.

For Angular UI, the same needs to be done [here](https://github.com/angular-ui/bootstrap/blob/master/src/position/position.js#L434-L485).

I'm still waiting for @jakob101 to update postcss-inline-rtl before users can actually build this!

**Comment by MohammadYounes** [comment]
I just noticed that carousel transition is not working as expected :( 

I'll check it later tonight.

**Comment by evilaliv3** [comment]
ah! anyway i'm thinking to change back from angular-ui/bootstrap to http://mohammadyounes.github.io/RTL-bootstrap/inline!

let's do it :) as soon that it will be ready and aligned with the 3.3.6 i will one shot do the change!

**Comment by evilaliv3** [comment]
ah no damn, for various reasons we would still need to run us anguar-ui/bootstrap for the more control it offers us in angular :( i will so try to build a patch for the tooltips in RTL as you did in http://mohammadyounes.github.io/RTL-bootstrap/inline

**Comment by jakob101** [comment]
@MohammadYounes I will update tomorrow, I'm still out of the country! :)






On Sun, Apr 3, 2016 at 5:51 AM -0700, "Giovanni Pellerano" <notifications@github.com> wrote:












ah no damn, for various reasons we would still need to run us anguar-ui/bootstrap for the more control it offers us in angular :( i will so try to build a patch for the tooltips in RTL as you did in http://mohammadyounes.github.io/RTL-bootstrap/inline

**Comment by MohammadYounes** [comment]
@jakob101 Take your time :)

@evilaliv3 I updated the branch:
 * Fixed carousel by adding `transition` to the always convert list [PR](https://github.com/jakob101/postcss-inline-rtl/pull/5).
 * Fixed tooltip positioning inside modal [commit](https://github.com/MohammadYounes/RTL-bootstrap/commit/f10c0c2afa0ace9a009cc3eb8c9524539d466383).

Now it's fully converted :)

**Comment by evilaliv3** [comment]
Great @MohammadYounes!

I was about to integrate it in globaleaks but what we miss is:
- at least that it is published on bower; could you?
- a tagged release would be lovely

if it is good and you also think this would help easy the process what we can do is too fork your project under the GlobaLeaks organization; assign you permissions to commit on the specific repository where to collaborate; i can handle the publishing on the bower and sign the releases that could have a numbering 3.3.6-our.numbering.

this way then for our personal use i will do the same for angular-ui/bootstrap-rtl

let me know if this plan is ok for you.

**Comment by evilaliv3** [comment]
what i was about to do is to use:
```
"bootstrap": "git@github.com:MohammadYounes/RTL-bootstrap.git#f10c0c2afa0ace9a009cc3eb8c9524539d466383"
```

but this forces me to download the whole repository and in addition the repository currently miss the build in the ```/dist``` directory (i would suggest that every time you bild it you commit the build in a separate new commit with the bumb the release.

i've a doubt in the release numbering as bootstrap uses X.Y.Z but semver does not allow X.Y.Z.K with a forth number like 1.2.3.4: https://github.com/mojombo/semver/issues/168
@MohammadYounes @jakob101 any suggestion?

**Comment by evilaliv3** [comment]
probably the idea that comes to my mind is to always tag the same version of the current release of bootstrap, and whenever we apply changes simply delete the tag and re-tag it with the same current numbering.

**Comment by MohammadYounes** [comment]
@evilaliv3 I will commit the `dist` along with the updated version of postcss-inline-rtl (see [#4](https://github.com/jakob101/postcss-inline-rtl/issues/4)).

I think this would be the last version in v3, and for v4 they [mentioned](https://github.com/twbs/bootstrap/issues/19555) it's to be added in a future minor release:
> RTL support is currently slated for a future minor release after v4.0.0 has a stable release.

For now, I believe it's easier to have the [`dist`](https://github.com/MohammadYounes/RTL-bootstrap/tree/gh-pages/inline/dist) manually included in your repo.

**Comment by MohammadYounes** [comment]
@evilaliv3  tagged under [3.3.6](https://github.com/MohammadYounes/RTL-bootstrap/tree/3.3.6)
