### ISSUE TITLE
Evaluate adoption of docker as app container

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1622]
Following the research already done in https://github.com/globaleaks/GlobaLeaks/tree/master/appliance, it would be interesting to complete the design of the appliance by integrating docker as app contaiiner.

A first draft of the docker container has been already implemented by @mwaeckerlin in https://github.com/mwaeckerlin/globaleaks

\cc @ianribas @n-daniel

**Comment by mwaeckerlin** [comment]
Thank you for the mention. Feel free to use my implementation, use it, clone it, change it, provide upstream. Ask me, if I can help. I already used it in a test installation, so it works: https://github.com/mwaeckerlin/globaleaks

**Comment by ckeeney** [comment]
I suggest this issue be closed so all future discussion of Dockerizing GlobaLeaks can take place in #692.

**Comment by evilaliv3** [comment]
Agreed thanks @ckeeney.

Closing as duplicate.
