### ISSUE TITLE
Implement mlockall(1|2) in order to prevent RAM to be swapped

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1623]
In relation to tickets like https://github.com/globaleaks/GlobaLeaks/issues/685 it would be important to implement mlock().

In previous test implementation we were not considering the possibility to enable both the flag 1(CURRENT) and 2(FUTURE) at once.

This can simply done with the following snippet:
```python
import os
import ctypes

libc = ctypes.CDLL("libc.so.6", use_errno=True)

MCL_CURRENT = 1
MCL_FUTURE = 2

if libc.mlockall(MCL_CURRENT|MCL_FUTURE):
    print("mlockall failure: %s" % os.strerror(ctypes.get_errno()))
    quit(-1)
```

This would allow the backend to lock all the current data pages and the future ones.

**Comment by evilaliv3** [comment]
@fpietrosanti the feature is ready and working.

what missing is:

1. to define the amount of RAM required by GLobaLeaks in order to set ulimit -l that by default is 64kb on ubuntu 14.04
2. modify /etc/default with a ```RAM=VALUE```
3. modify /etc/init.d/globaleaks to perforrm ```ulimit -l $RAM```
5. modify /etc/init.d/globaleaks to call globaleaks with ```-P``` (disable_swap)
6. decide how to handle the SEGFAULT that globaleaks will get in case it will exceed the memory limit; this should be anyhow be done not only in relation to this feature.

\cc @NSkelsey

**Comment by fpietrosanti** [comment]
I remember that the problem with mlock() testing was that application where going in OOM, without any possibility to recover it, so we postponed it to a possible future when we'll have a supervisor capable of handling that condition

**Comment by evilaliv3** [comment]
this can happen regardless of the mlock();

do you sometimes answer to the question that the others write? :)

**Comment by evilaliv3** [comment]
and here is the solution to your big problem:

/etc/cron.d/globaleaks:
```
* * * * * service glboaleaks status | grep running || service globaleaks restart
```

**Comment by fpietrosanti** [comment]
Well not as easy, because the OOM killer of Linux try to defend the stability of the system and in a OOM condition (where there's not enough memory + not enough swap and cached-memory has been totally free'd up), the most often memory consuming software will get killed. Instead, with a fixed memory hard-limit on the software, any memory pressure on the system (ie: because a backup is running and there's a lot of filesystem cached memory), could trigger the OOM killer on globaleaks first, that cannot be "catched" at application level

**Comment by fpietrosanti** [comment]
The vecna's report on mlock breaking globaleaks is at #843 on enabled by default swap encryption

**Comment by evilaliv3** [comment]
that's not report but a "it does break all the system".

i'm so scared now that i'm about to give up with all the project.

**Comment by evilaliv3** [comment]
an you know why it was considered that "it does break all the system" ?

simply because no one checked that "ulimit -l" answer 64kb.

i do science or at least i try but if you @fpietrosanti prefer to simply raise unsolvable problems proceed for it!

**Comment by fpietrosanti** [comment]
I'm just __underlying__ that dealing with memory management related things can be risky because of OOM (referring to the #843 tests) and that the risks that may occur cannot be "detected / exception handled" unless there's a supervisor process, so we would not know if something bad happened due to that feature. Enabling by default maybe risky, some "controlled" testing on our platform maybe better for some time?

**Comment by evilaliv3** [comment]
you are right what i'm criticizing is:
1) i'm saying that we need to handle the OOM issue anyhow; now i'm pushing the cron job without no discussion as you were not interested in discussing and i've implemented it now.
2) 1) will solve the current totally unhandled status, and would also solve in case we we disable the swap and there is nothing an hipervisor can do more that the cronjob cannot do and we send an email if this occur; but why you do not want do discuss it?
3) i left some question on the size of the RAM; i've estimated it as 512MB as the most big setup we have are using ~300MB.

**Comment by NSkelsey** [comment]
3) The average RAM size may not reflect peak RAM usage on the machine. Let's write a test case that creates memory pressure to see how the application behaves and observe what actually happens if it is OOM.

**Comment by evilaliv3** [comment]
as discussed of the record with @fpietrosanti, probably the best is to simply set ```ulimit -l unlimited``` in order to let the globaleaks binary to not swap at all.

as experiment i will implement that but i think in the end i would make no sens to be used;
the reason is that avoiding the program to swap without never release the memory it allocated would simply cause failures.

@fpietrosanti have you ever discussed this?

an interesting reading is this: https://eklitzke.org/mlock-and-mlockall

**Comment by evilaliv3** [comment]
with ulimit as well we could limit the virtual mmory size of the process in order to avoid it use more than X.

**Comment by evilaliv3** [comment]
implemented but to be considered higly experimental.

to enable it one has to add ```DISABLE_SWAP=1``` to /etc/defaults/globaleaks

**Comment by fpietrosanti** [comment]
Closing this require documenting the security feature in "Application Security Specs" or "Operating Security Specs" . 

It could be also useful to open-up the improvement tickets of that features for future consideration (detecting/reporting OOM conditions, having an application watchdog loop-free)

**Comment by evilaliv3** [comment]
Yep; but what do you think about the issue i described in relation to the fact that the application will keep locked the peak of the memory used at runtime? i.e. if one day the app will use 4GB of ram in a peak, it will keep it locked undefinitely. this is whay i consider this feature a research one, unstable and not really useful to be documented.

the only practical solution to the above program is under certain conditions to remove the lock and rekeep the lock giving the chance to the operating system to recall the unused RAM, but this will open in such a condition to the possibility to swap.
