### ISSUE TITLE
min_date and max_date configurations on questions of type Date should deny navigate dates out of boundary

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1624]
The current implementation of #1588 allow to configure min_date and max_date on questions of type Date but due to limits of the angular-ui/bootstrap library we can't deny the user to navigate out of the defined range of dates.

This is a limit of angular-ui/bootstrap that is also present in the original bootstrap library and is upstream tracked by: https://github.com/angular-ui/bootstrap/issues/1993

**Comment by NSkelsey** [comment]
Careful selection of params in the date-picker options might get us out of this. 

https://angular-ui.github.io/bootstrap/#/datepicker

**Comment by evilaliv3** [comment]
Nope; sadly the options available help in avoiding to go bottom up selecting the year for example, but there is no configuration that prevenst you to move in the past or in the future by using arrows.

**Comment by evilaliv3** [comment]
Closing as outdated. This feature was implement time ao and is working in current 4.6.1
