### ISSUE TITLE
Update GlobaLeaks Application Security Design and Details Document with "Web Privacy" related information

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1625]
I noted that our " GlobaLeaks Application Security Design" document at https://docs.google.com/document/d/1SMSiAry7x5XY9nY8GAejJD75NWg7bp7M1PwXSiwy62U/  is missing all the "Web Privacy" related technical feature that we have in place.

This ticket is to add a new section on Web Privacy documenting the design and technical features of:
- No Cookies (using HTTP headers for auth)
- Various No Caching headers (except a certain condition for certain files for IE)
- Images base64 encoding in JS/rest loaded resources
- Embedded mode design with dynamic iframe loading + starter plugin
- Disabling of autocomplete on input field
- Possibly other features already ticketed-but-not-implemented

**Comment by NSkelsey** [comment]
I have a fair bit of copy edits for the document that should be included in the update as well.

**Comment by evilaliv3** [comment]
@NSkelsey could you apply them directly on the document or report them here/

**Comment by NSkelsey** [comment]
@evilaliv3 I will start the edits now and perform them on the document.

**Comment by NSkelsey** [comment]
Web privacy section added, with a section about No use of cookies, and the use of standard system fonts added.
