### ISSUE TITLE
Change Recipient file download to use SaveAs

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1626]
In order to prepare for client side decryption of file downloads it is nessecary to remove file download as an XHR post. Instead, we must use a javascript library like [FileSaver.js](https://github.com/eligrey/FileSaver.js) to handle the download of the file in such a way that we can decrypt and then download said file.

The order of operations here is:
1. research
2. local testing
3. development
4. ???
5. profit

**Comment by NSkelsey** [comment]
It occurred to me that handling client side streaming decryption is very similar to decoding streaming audio or video. 

The HTML5 specification has quite a [bit of support](https://w3c.github.io/media-source/) for this kind of behavior.

**Comment by evilaliv3** [comment]
@NSkelsey analyzed the situation for the browsers and it seems that you great Safari is not supporting saving files in javascript with a defined filename: https://bugs.webkit.org/show_bug.cgi?id=102914

do you have anny suggestions?

He have already for some of the files of the admin panel, but this requirement will impact that badly on the clientsite crypto.

**Comment by evilaliv3** [comment]
in comment https://bugs.webkit.org/show_bug.cgi?id=102914#c79 Brent Fulgha on 2016-03-31 08:32:51 PDT said: Tests all pass with this revision. Will land this final patch. 

Committed r198893: <http://trac.webkit.org/changeset/198893>

But it's definitely something that will be there only for future browsers.

**Comment by fpietrosanti** [comment]
We should then think about the way to handle the current feature of "Download Multiple Files" and "Download all Files" (that may require some state machine to handle multiple operations may fail, require retries, may require confort loader or progress bar displaying what's going on)

**Comment by evilaliv3** [comment]
@fpietrosanti: let's keep tickets small; e.g. all in your previous comment should go for me in a second different ticket called: "Implement comfort loader for the submission export feature".

the reason of do this are important:  AGILE!

i'm moving this to an other ticket and answering there with some comment.

**Comment by evilaliv3** [comment]
@NSkelsey: i discussed with fabio about the multiple confirmation popups that will happen in every browser.
We think that is not valuable to implement the saveAll on the tip list for now because it will simply confuse the user.

I suggest that in this ticket we will simply deal with replacing the saveAs for the single file as this ticket had been designed in order simply to integrate the saveAs capability as requirement for moving on the clientside encryption so let's not get stucked on blocking issues :)

**Comment by evilaliv3** [comment]
Implemented by @NSkelsey in: https://github.com/globaleaks/GlobaLeaks/commit/c1ba08fb52c7275df208282283a7e39bd190be0b

Refined by me with:
 - https://github.com/globaleaks/GlobaLeaks/commit/0b8d4781251b3e8376d389c5e45fcddc784bbe00 : removed Blob polyfill as all the targeted browsers versions supports Blobs.
 - https://github.com/globaleaks/GlobaLeaks/commit/e2e9509f9fc01a07409c8d55862e32fc19306c0e : implemented it all also for single file downloads
 - https://github.com/globaleaks/GlobaLeaks/commit/252d334d78611c6749e48aafdb4de9b4d2943b9c : removed handling of sessions passed as query string that is not needed at all and prone to more threads e.g. in relation to forensic traces.
