### ISSUE TITLE
Implement update script

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1628]
Currently the update process is demanded to a complete manual process.

This process involve:

1. checking that the repository key is still valid and eventually update it
2. perform eventual backups before updating
3. fingercross and update

I think that in the short-term we should have a minimal update-globaleaks.sh that address 1. and 2. in automatic fashion.

For point 2. we will think something about in the future to make it easy to eventually rollback in case of any failure.

**Comment by fpietrosanti** [comment]
w.t.r to PGP key update i feel that globaleaks should periodically, check if a new PGP signing key is available, fetch it and make it installed to avoid to follow custom procedures. That could be similarly part of "awareness" of updates availability feature such as #1493 that require to periodically fetch stuff related to updates and execute actions

**Comment by evilaliv3** [comment]
i agree @fpietrosanti but only for the future when that will be in place.

for now an autofetching of the key that could anyhow happen after the user tried to update on the console does not helps what is my goal that is at least to easy my work.

**Comment by evilaliv3** [comment]
implemented and updated the wiki;

the output is the following:
```bash
root@bloodyroot:~# gl-update 
Performing GlobaLeaks update
Adding GlobaLeaks PGP key to trusted APT keys
Running: "wget https://deb.globaleaks.org/globaleaks.asc -O /tmp/globaleaks_key.23279"... SUCCESS
Running: "apt-key add /tmp/globaleaks_key.23279"... SUCCESS
Running: "rm -f /tmp/globaleaks_key.23279"... SUCCESS
Running: "apt-get update -y"... SUCCESS
Running: "apt-get install globaleaks -y"... SUCCESS
```
