### ISSUE TITLE
Implement Microsoft Edge testing

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1630]
Currently Microsoft Edge is not tests as protractor does still not support it due to a missing webdriver capability.

This ticket is to keep track of this and eventually implement that test case when supported.

References tickets:
- https://github.com/angular/protractor/issues/2377
- https://github.com/angular/protractor/issues/3016
- https://developer.microsoft.com/en-us/microsoft-edge/platform/status/webdriver/details/

**Comment by evilaliv3** [comment]
@vodkina  / @NSkelsey / @fpietrosanti : i've created the label S(Status): Blocked in order to be able to mark what eventually will be blocked for external or internal reasons.

I'm proposing this looking at the use of the labels/milestones done in angular and protractor; they use a milestone called "Blocked" but i think a label is more appropriate.

**Comment by inthegarage** [comment]
Please see my comments on https://github.com/angular/protractor/issues/2377

I currently can get this working (kinda), so the browser loads(Edge) and it navigates to my page, however all tests fail with the same error:

    Failed: Error while waiting for Protractor to sync with the page: "window.angular is undefined.  This could be either because this is a non-angular page or because your test involves client-side navigation, which can interfere with Protractor's bootstrapping.  See http://git.io/v4gXM for details"

The url mentioning browser.ignoreSynchronization = true; appears to be irrelevant,

The tests all pass in IE 11, as you'd expect.
In edge the screen is actually used and navigated so this appears to be solely a protractor issue now. Can this be looked at please?

**Comment by ramsyadav** [comment]
Visit the link there is a way to test with protractor.
https://github.com/angular/protractor/issues/2377

I have tested it.It's working,but some functions and code you've to change according to edge browser support.

**Comment by tyaga001** [comment]
Should we hold on to test on edge browser with protractor as you have removed microsoft edge from testing as it still not supported by protractor. please clarify as currently i am unable to launch edge with protractor APIs.

**Comment by tyaga001** [comment]
@ramsyadav - Could you please help here as, we are not able to invoke the edge browser on windows 10 platform, more details you can check here. 
https://stackoverflow.com/questions/47766363/unable-to-launch-microsoft-edge-with-protractor

**Comment by evilaliv3** [comment]
Closing as outdated and supported since many years.
