### ISSUE TITLE
GPG error

### ISSUE THREAD

**Issue by kyrylkov** [globaleaks/GlobaLeaks#1632]
W: GPG error: http://deb.globaleaks.org trusty/ Release: The following signatures were invalid: KEYEXPIRED 1460066203 KEYEXPIRED 1460066203 KEYEXPIRED 1460066203

**Comment by evilaliv3** [comment]
hi @kyrylkov 

the key is expired as it was expirinng the on the 7th of april but it has been renewed and you have simply to do as documented at https://github.com/globaleaks/GlobaLeaks/wiki/Upgrade-Guide:
 ```curl https://deb.globaleaks.org/globaleaks.asc | apt-key add -```

From this release on also we have added a ```gl-update``` script that internally perform basic operations like this (for now only this and in the future eventually backups and other stuff).
