### ISSUE TITLE
Implement SaveAll/ExportAll capability for Files/Tips

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1634]
Moving forward the implementation done in https://github.com/globaleaks/GlobaLeaks/issues/1626 an improvement would be to implement a SaveAll/Export all capability for Tips/Files to be handled clientside.

This should be implemented in compliance on the latest ideas on the clientside encryption that would require the client to fetch resources, do processing (decryption), and generating a file download.

The reason we would need to end in generating a single file download (a zip file?) is that as tested by @NSkelsey most of the browser always ask for confirmation for the file download regarding of the fact that the file could be a trusted not risky one (e.g. the mentioned zip file).

**Comment by evilaliv3** [comment]
Let's concentrate our effort on what needed for the single file/tip download/export completing the clientside crypto and  put this as wishlist for the future.

**Comment by evilaliv3** [comment]
@NSkelsey could you please when cleaned your pull request for #1626, take care that your notes/snippets on this topic are saved here as track for future implementations?

**Comment by NSkelsey** [comment]
@evilaliv3 Okay. I will edit this comment as I collect things.

### Ease of Use
In terms of usability the best option would be for a single file download that is one zip of all of the exported tips. With Client-side crypto this is complicated.

### Cross Platform Compatibility
Automatic downloaded is not supported in the Safari webkit version ?.?.?
But there is an open ticket to close issue in newer versions: XXXXXX.html

**Comment by evilaliv3** [comment]
Closing as outdated.

As for current 4.6.1 release te software features the possibility to export all the submissions by clicking a button. When the button is pressed the client perform multiple requests to trigger the download of each submission that is provided by the platform as a file download; This implementation is able to bypass the limitation of the browser on blob sizes.
