### ISSUE TITLE
Uploading file of 1.47GB report wrong size of 1GB while uploading

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1637]
Uploading a file of 1.47GB report wrong size of 1GB while uploading, as shown below

<img width="423" alt="screen shot 2016-04-12 at 1 21 45 pm" src="https://cloud.githubusercontent.com/assets/770363/14458468/b3e8467e-00b1-11e6-9404-1e60188734f2.png">

**Comment by evilaliv3** [comment]
Bug identified.

It exists since we apply conversion from bytes to GB, MB, Kb.

going to fix it.

**Comment by evilaliv3** [comment]
We were implementing a custom directive while we can use one implemented in angular-filter.
By the way it seems that angular filter is doing it wrong so before fixing it using the [angular-filter](https://github.com/a8m/angular-filter) ```byteFmt``` we would need to suggest them to fix it.

**Comment by NSkelsey** [comment]
Fixed in release v2.60.3
