### ISSUE TITLE
The DatePicker UI should be subjected to internationalization

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1641]
The DatePicker UI is currently not subject to internationalization.

This ticket is to keep track of the research on the feasibility of this and the possible implementation.

The requirement has been requested in the context of the ICC pilot.

**Comment by evilaliv3** [comment]
This should be probably feasible by using simply [```angular-i18n```](https://github.com/angular/bower-angular-i18n) that is the official module of Angular for the internatonalization.

**Comment by evilaliv3** [comment]
Angular does now support naturally to swap the locale at runtime so that we should evaluate using: ```https://github.com/lgalfaso/angular-dynamic-locale``` by @lgalfaso

We have to see how to make it possible inlining the locales in the built script and this is tracked by: https://github.com/lgalfaso/angular-dynamic-locale/issues/93

**Comment by NSkelsey** [comment]
1) angular has an i18n support: great!
2) this support is static: oh dear!
3) there is a good simple module making it dynamic, https://github.com/lgalfaso/angular-dynamic-locale: GREAT!
4) this module loads a separate file at runtime each time you change language: OH DEAR!
5) ok doing some inlining we got out of this mess!!!! finally !!!! yeah!!!! ou yeeeeaaa!
there is something we have to think about translations then in general

**Comment by NSkelsey** [comment]
@evilaliv3 I can confirm that using `angular-dynamic-locale` works for changing the UI within datepickers and datepicker-popups.

I will push a functioning sandboxed example as a separate branch next to devel. The question for me, is how to integrate this into the inlining....!

**Comment by NSkelsey** [comment]
@evilaliv3 branch `feature/dynamic-locale` has a functioning example of setting the $locale object to french after the fact. I do not know how the you intend to implement the support for the ICC's request so I am leaving this here.

These are the things left to clarify:
1. At what point must the locale be set for a specific user? At first visit or after they choose a language from a list?
2. How can we package the angular-i18n/en-us.js files into the existing js bundle?

**Comment by evilaliv3** [comment]
@NSkelsey most of the analysis on this is at ticket https://github.com/globaleaks/GlobaLeaks/issues/1445 that would be nice if you could address together with this :)

#1445 talks about the wizard but it apply in the real to every user navigation session.

this would help you aswering your point 1. and the order of preference for me continue to be:
1) explicit url lang (?lange=en),
2) receiver/admin language if explicitly set by the user (this as far far improvement as it require to think a lot about this, i think)
3) browserlanguage (if supported by the node),
4) default of the node

the main code that deals with this is here: 
https://github.com/globaleaks/GlobaLeaks/blob/master/client/app/js/controllers/main.js#L10
https://github.com/globaleaks/GlobaLeaks/blob/feature/dynamic-locale/client/app/js/controllers/main.js#L306

This should anser your point 2. https://github.com/lgalfaso/angular-dynamic-locale/issues/93 ; let me know if you have any doubt.

**Comment by NSkelsey** [comment]
Solved by 5b0a8585b2992eb
