### ISSUE TITLE
When receivers are hidden it should be configurable the name shown to the whistleblower upon recipient messaging

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1642]
Nowadays even if the details of the recipients are not shown to the user and recipients act as a whole on behalf of the organization, when the recipient write a message or comment the name of the recipient is shown to the whistleblower.

It would be interesting to avoid doing this and on such a condition replace the name with the recipient with the string "Recipient"; this string should be then configurable (so that the adopter could write e.g. WildLeaks/IRPI/or a name different from the initiative name).

I annotate here that probably the text "Whistleblower" should be replaced with "Source" or made configurable as more and more adopter says me that; this should probably happen at least on this comment/message interface.

\cc @fpietrosanti @NSkelsey

**Comment by NSkelsey** [comment]
I agree with the premise. 

1) The simplest way to do this is to just add a switch and assign a number. The first recipient say John Doe becomes Recipient 1, while the second becomes Recipient 2 and so on.

This string could be configurable by each recipient OR (exclusive or) by the admin. If it is the former, then I foresee the potential for mischief amongst recipients (John Doe could become Glen Grenwa1d). If only the admin can make the change for each user this is a little safer for the WB.

The last bit to consider for admin's controlling the name is how to change the psuedoanonymous name changing during the commenting process. I could see the system automatically adding a comment to inform the WB's of the name change. This would have to be an optional comment notification so that somebody malicious cannot monitor the renaming.

2) I agree with the "Whistleblower --> Source" change. Source is a bit more general. @comradekingu should have an opinion as well ;-)

**Comment by NSkelsey** [comment]
A little more info on 1) PGP public keys contain information about the recipient that in most cases would reveal their identity.

Observe the content of @evilaliv3's public key:
```bash
> gpg -a --export "evilaliv3@globaleaks.org" | gpg --list-packets --verbose
gpg: armor header: Version: GnuPG v1
:public key packet:
	version 4, algo 1, created 1428495055, expires 0
	pkey[0]: [4096 bits]
	pkey[1]: [17 bits]
	keyid: F4CBD5BD67A0F187
:user ID packet: "Giovanni Pellerano <giovanni.pellerano@evilaliv3.org>"
:signature packet: algo 17, keyid B842093DC6765430
	version 4, created 1437479001, md5len 0, sigclass 0x10
	digest algo 8, begin of digest c9 c7
	hashed subpkt 2 len 4 (sig created 2015-07-21)
	subpkt 16 len 8 (issuer key ID B842093DC6765430)
	data: [160 bits]
	data: [160 bits]
:signature packet: algo 1, keyid F4CBD5BD67A0F187
	version 4, created 1429890961, md5len 0, sigclass 0x13
	digest algo 2, begin of digest db e5
	hashed subpkt 27 len 1 (key flags: 03)
	hashed subpkt 9 len 4 (key expires after 2y0d0h0m)
	hashed subpkt 11 len 5 (pref-sym-algos: 9 8 7 3 2)
	hashed subpkt 21 len 5 (pref-hash-algos: 8 2 9 10 11)
	hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
	hashed subpkt 30 len 1 (features: 01)
	hashed subpkt 23 len 1 (key server preferences: 80)
	hashed subpkt 2 len 4 (sig created 2015-04-24)
	hashed subpkt 25 len 1 (primary user ID)
	subpkt 16 len 8 (issuer key ID F4CBD5BD67A0F187)
	data: [4094 bits]
:signature packet: algo 1, keyid DD773D6D7326078E
	version 4, created 1459542534, md5len 0, sigclass 0x12
	digest algo 8, begin of digest 51 b6
	hashed subpkt 2 len 4 (sig created 2016-04-01)
	subpkt 16 len 8 (issuer key ID DD773D6D7326078E)
	data: [4095 bits]
:user ID packet: "Giovanni Pellerano <evilaliv3@globaleaks.org>"
:signature packet: algo 17, keyid B842093DC6765430
	version 4, created 1437479001, md5len 0, sigclass 0x10
	digest algo 8, begin of digest c0 37
	hashed subpkt 2 len 4 (sig created 2015-07-21)
	subpkt 16 len 8 (issuer key ID B842093DC6765430)
	data: [160 bits]
	data: [157 bits]
.
.
.
```

With client side crypto changing your alias could be akin to generating a new GPG key.

**Comment by fpietrosanti** [comment]
For 1. i'd suggest to simply make a "Public Name" entry parte of the Recipients configuration data. If un-configured, it will use the normal Name, if configured will show everywhere the "Public Name" in place of the "Name" .

For 2. it's fine to make it configurable, default should stay Whistleblower that's the general use-cases, while "Source" is only "journalistic". The best way to do it, it would be do make a select-box, with selectable "Whistleblower (default) / Source / Other" and if Other is selected, a text-field is displayed.

**Comment by evilaliv3** [comment]
I agree on the suggestions by  @fpietrosanti 

The numbering @NSkelsey is not possible as recipients can be changed during time; If an initiative has the requirement to keep recipient not known we could create the end2end key mapped on the uuid assigned to the recipient and that whould work great; i'm totally for this.
This way the only thing leaked is how many recipients there are are, how many are active, and which answered but i do not feel this a threath if the kees not disclosed as we are saying and ife this interface returns pseudonyms this way.

each user should have so a pseudonym that if configured is returned in plac of the realname.

**Comment by evilaliv3** [comment]
in addition is not a necessity that this pseudonim is unique so that for example IRPI could show visually IRPI to the user interface that is sometimes perceived more professional by the adopter.

**Comment by NSkelsey** [comment]
I see one problem with @fpietrosanti with 1) which I tried to get at earlier. Recipient's changing their public names should be handled with some care. If any recipient can change their public name, then they could easily spoof who they are among the available recipients.

Imagine two recipients commenting with a source and Recipient 1 briefly changes his name to Recipient 2 to produce a misleading comment. This is a feature that could be abused and without some warning to the source it would appear as if Recipient 2 has said something completely off. At the very least public name changes should be placed in the anomaly logs.

**Comment by evilaliv3** [comment]
sury @NSkelsey you are right; but take my and the comments of fabio as not english speakers.

already know we are avoiding this kind of spoofing possibilities and the name is cocnfigurable only by the admin.
what @fpietrosanti was saying is to allow the admin to configure the pseudonym to be shown that could be different from the name/surname of the user.

then it will be a different topic if and not allow the user to change this information (like also this photo) and there will be settings for this permissions to be designed but this is not what this ticket is about

**Comment by NSkelsey** [comment]
Ahhhh configurable by the admin. Got it.

**Comment by evilaliv3** [comment]
implemented!
