### ISSUE TITLE
PGP file encryption is currently working in streaming

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1643]
While working on https://github.com/globaleaks/GlobaLeaks/issues/1639 i discovered that the PGP file encryption is currently working in streaming.

For various mistakes in the code handling the PGP encryption the file is always re-read in RAM while performing various actions:
- the renaming of the file instead of relying on ```os``` functions or using ```gnupg``` to encrypt to write directly to the destination, is currently implemented reopening the encrypted file and reading it as a whole simply for rewriting it in the destination file; this is not impacting simply a failure in case the RAM does not last but is causing performances issues copying a file more times than needed.
- to get the size of the file and other time the encrypted file is opened, read as a whole as string simply for performing a len() function on that string.

as result the file is read, read, read again and again and again.

No security issue arise, but whenever it happen that th file is near the size of the available RAM, the encryption is failing resulting in creating submissions with files in ```unavailable``` status.

This ticket is to keep track of the required bugfixing and as memento for not doing this kind of errors again.

**Comment by fpietrosanti** [comment]
If an error happens while processing the files with PGP encryption, are there any kind of exception handling/error detection that enable to understand that something went wrong for whatever reason, being notified about it?

**Comment by evilaliv3** [comment]
@fpietrosanti as in general, there is not any kind of code that should do an explicit notification, but simply we should avoid what done before that when shit happen we simply pass over it.

the code i'm writing and rewriting recently handle the local exception and pass to the layer over so that when the exception reach the top level we are notified.
