### ISSUE TITLE
Research file size download limits in relation to the browsercrypto and the saveAs functionality

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1654]
This is related to the browser crypto branch.

After some investigation it looks like the current method of encrypting files yields a silent limit at around ~31MB. The decryption/download has no problems with files of this size. This may indicate a problem with the Fusty Flow library. -- tested on Chrome 50 on OSX 10.10.5.

Further research is needed.

Some visual proof (the files are about 1MB larger than their stated names):

<img width="394" alt="screen shot 2016-04-24 at 8 39 24 pm" src="https://cloud.githubusercontent.com/assets/1095794/14771565/88d0b6d2-0a5d-11e6-95e9-3da70a0f94d7.png">

In general the UI to demonstrate to the user what is happening behind the scenes needs to exist. It is not sufficient to show a loading icon while the file in the browser is slowly encrypted and then uploaded to the server.

**Comment by NSkelsey** [comment]
Oh lol this is the default max file size for a vanilla GL server.

A warning should really popup to tell you that the max file size is exceeded.

Further investigation to follow.

**Comment by NSkelsey** [comment]
Actually the file encryption and upload can handle files up to 1GB on a machine with 8GB of RAM – It just uses all of it.

### From Activity Monitor (peak at upload):

<img width="611" alt="screen shot 2016-04-24 at 9 09 34 pm" src="https://cloud.githubusercontent.com/assets/1095794/14771724/a637b03c-0a61-11e6-863e-286c52755d04.png">

### From Chrome task manager after the fact 

There is 1GB of memory leaks in there – or non GC'd objects...:


<img width="880" alt="screen shot 2016-04-24 at 9 10 58 pm" src="https://cloud.githubusercontent.com/assets/1095794/14771725/aa50a96c-0a61-11e6-8573-5e1805ba4d08.png">

Additionally it seems that the download side is completely unable to deal with files of 750MB or greater in size. All the UI does is spin!

<img width="1064" alt="screen shot 2016-04-24 at 9 18 17 pm" src="https://cloud.githubusercontent.com/assets/1095794/14771740/189a29d4-0a62-11e6-9bf8-952070c2eea2.png">

**Comment by evilaliv3** [comment]
@NSkelsey i've removed from this ticket to study the interface; let's keep things separated as much that we can.

Anyway the issue on the error message is a regression that i confirm both on the master branch and the browsercrypto branch.

It is probably related to my changes onf the fileAdded event binding; i will take care of this specific topic at least for fixing the regression and then we could open a ticket for the future improval of that interace.
https://github.com/globaleaks/GlobaLeaks/blob/master/client/app/js/controllers/fileupload.js#L7

**Comment by evilaliv3** [comment]
@NSkelsey in the meantime i've fixed it this way as short fix that i'm now going to release together with a bugfix spotted by a user on the submission step activation.

![screenshot from 2016-04-25 13 45 30](https://cloud.githubusercontent.com/assets/217034/14788407/fa7d5dee-0b07-11e6-948b-75ef555b6750.png)

I've moved the error near the button, and the file is not not loaded by flow at all.
In the past instead flow was anyhow sending the whole file with the server crying at each chunk (this was a bug) an we were showing the error in the file uploader withdeg.

I make you not that we will have to work on the texts and their internationalization as the current one do not communicate the configured size to the user.

current text is: "This file exceeds the maximum upload size for this server."

**Comment by NSkelsey** [comment]
Yep this works.

One nit pick, the alert should use the `class="alert alert-danger"` CSS styles.

**Comment by evilaliv3** [comment]
Allright! 

![screenshot from 2016-04-25 22 18 37](https://cloud.githubusercontent.com/assets/217034/14797574/ba8c630c-0b33-11e6-9410-8926493fb7ed.png)

**Comment by NSkelsey** [comment]
With a 750 MB file upload the chrome memory profiler creates the following output, while the file is being encrypted:


<img width="201" alt="screen shot 2016-04-26 at 2 05 49 pm" src="https://cloud.githubusercontent.com/assets/1095794/14829294/956021f6-0bb8-11e6-9342-b36a6f55f6e7.png">

**Comment by fpietrosanti** [comment]
For SaveAs there's a maximum download size of 500Mb documented on https://github.com/eligrey/FileSaver.js/
<img width="635" alt="screen shot 2016-04-26 at 9 05 41 pm" src="https://cloud.githubusercontent.com/assets/770363/14830781/be68b5f6-0bf2-11e6-99ea-e2db90cba937.png">

**Comment by NSkelsey** [comment]
@fpietrosanti, after some analysis it appears that the download is not getting to the `filesaver.SaveAs` function. On my local machine on the `browser-crypto` branch the request to download the file stalls in the HTTP GET request, which is before the blob is returned back into Javascript's memory.

**Comment by NSkelsey** [comment]
Chrome design documentation on their implementation of Blobs in the browser (hint (they get paged to disk)

https://docs.google.com/document/d/19OmSKoWTJrUPwoA3G2-ZHe6jPMw2voDpyStgHFXH7qI/edit#

**Comment by evilaliv3** [comment]
This limitations do not affect anymore the application that do not uses XHR requests when implementing file download or exports.

The saveAs functionality is just used on some functionalities that save small files.
