### ISSUE TITLE
Next Step Button not shown

### ISSUE THREAD

**Issue by mcbernie** [globaleaks/GlobaLeaks#1655]
Found an error in GLClient.controller('SubmissionCtrl'....

`$scope.lastStepIndex = function() {
    var last_enabled = 0;

    for (var i = 0; i < $scope.selected_context.questionnaire.steps.length; i++) {
      if (fieldUtilities.isStepTriggered($scope.selected_context.questionnaire.steps[i]), $scope.answers, $scope.total_score) {
        last_enabled = i;
      }
    }

    return last_enabled;
  };`

has wrong if statement need to be:
`if (fieldUtilities.isStepTriggered($scope.selected_context.questionnaire.steps[i], $scope.answers, $scope.total_score)) {`

**Comment by evilaliv3** [comment]
Nice catch @mcbernie ! thank you so much.

i confirm the error and going to patch it now and disabling the score feature that had to not be enabled when experimental features are disabled.

we are going to release a bugfixed release and let you know here.

**Comment by evilaliv3** [comment]
Done, should be now fixed and released in 2.60.7

Thanks @mcbernie

**Comment by mttstt** [comment]
2.61.7 I suppose

**Comment by evilaliv3** [comment]
back the future @mcbernie ! you are right
