### ISSUE TITLE
Admin and Receiver should be blocked from creating submissions

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1656]
Currently if you are authenticated as an Admin or a Receiver manually navigating to `#/submission` will bring you to the submission page where you can create a tip that will be accepted by the server.

The logic on the client (and maybe even the backend) should block these role's from visiting pages intended only for Whistleblowers.

**Comment by evilaliv3** [comment]
Right point; this will probably pass from implementing a stateful appllication that is now completely (and badly) stateless.

**Comment by evilaliv3** [comment]
This apply also to custodians and the topic is in general more wide and to which pages could be navigated by a user depending on its current authentication.

e.g. a logged whistleblower should not go to /admin or to /custodian, and a logged admin neither.

**Comment by evilaliv3** [comment]
implemented!
