### ISSUE TITLE
Specify and analyze key escrow support for client-side encryption support

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1658]
This ticket is to specify and analyze key escrow support for client-side encryption support, given the problem that end-users loose their password and a procedures to be able in-place to avoid loosing data.

**Comment by evilaliv3** [comment]
Closing this ticket as deprecated due to changes in the finalization of the application encryption and going to open a fresh new ticket with the up to date analysis
