### ISSUE TITLE
Users can bypass forced password change

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1660]
This ticket is to analyze a possible bug that has been reported by Faffa, related to the fact that a Recipient that should change a password (1st login), is able to bypass the password and goes straight the tip list.

It's a low priority bug, but to be consider as with client-side it become mandatory

**Comment by evilaliv3** [comment]
yep this is something existing since ever and that i'm viewing to fix with @NSkelsey.

a user can currently navigate the pages without any check on that and he will get re-proposed the password change as he re-log in next times.

**Comment by evilaliv3** [comment]
This will becoming more relevant with the end2end password key creation so that i will take care now of implementing it while completing it and eventually anticipating it to the master branch.
