### ISSUE TITLE
Support configuration for deployment with reverse proxy on sub-path that does not handle URL rewriting

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1663]
This ticket is to support configuration for deployment with reverse proxy on sub-path that does not handle URL rewriting.

While working on testing deployment of OpenWhistleblowing behind Cisco ACE 4710 cluster handling HTTPS termination of existing anticorruption authority website, with reverse-proxy configured on the path www.website.it/submission/, the URL forwarding happens to be symmetric (/submission/ is forwarded to GlobaLeaks as /submission/), this trigger a 404 not found.

This ticket is to implement some kind of workaround that enable the configuration of a "PREFIX" that, if configured, enable the platform to also answer HTTP requests on /PREFIX/handler (or suggest another way to do it).

**Comment by evilaliv3** [comment]
Documented: https://github.com/globaleaks/GlobaLeaks/wiki/Advanced-configuration
