### ISSUE TITLE
Implement basic facilities for rechecking translations of translations sources

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1670]
The more the project proceed, the more we should take care of the translations we get.

Working with various adopter i found various translations errors causing malfunctions and worried the adopter.

E.g. i found some German translations where `%TipNum%` was written `%TipNum %` or `%ContextName%` was changed to `%Context%`.

It would be interesting as an improvement to have some basic facilities for automating the verification of the translations in relation to the most common mistakes

for exampel we could check that:
1) all the keywords present in the original text are still present in the translation texts
2) no additional keywords have been inserted in the translations text

this two simple texts would help to spot immediatly bugs that i'm now verifying we have already in a lot of existing translations.

**Comment by NSkelsey** [comment]
Testing this can be done in `tests/utils/test_templating` with the following psuedo code.

```python
for keyword_class in supported_template_types:
  for lang in supported_languages:
    template = get_related_template(app_data, language, keyword_class)
    
    check_keywords_present(template, keyword_class.keyword_list)
    check_no_extra_keywords(template, keyword_class.keyword_list) 
```

For `check_no_extra_keywords` we search for the commonly occuring typos and capitalization issues. 

If one of these assertions fails it would be very helpful to have the language, template and offending string all printed. Even more convenient would be to wait to fail the test until all of the templates in all of the languages have been tested so that in one go we find all of the potential issues in the translations.

**Comment by evilaliv3** [comment]
i agree on the logic of the pseudo code and probably the fact that we have keyword_class.keyword_list defined in the backend by the current status make it possible to implement it easily on the backend.

regardless of this i would rather suggest to implement this sanity check in the build script as last check of the grunt makeAppData. for the moment let's design the task as an additional verifyAppData where to implement the pseudo code above.

for this reason we could define a templates_descriptor.json describing the templates so that this descriptor then could be used by both the client and the backend.

a good start, serving the case but with no overengineering could be:
```
{
  'template_name1': ["Keyword1", "Keyword2", "Keyword3", ...],
  'template_name2': ["Keyword1", "Keyword2", "Keyword3", ...],
  'template_name3': ["Keyword1", "Keyword2", "Keyword3", ...],
}

**Comment by NSkelsey** [comment]
This has been implemented and placed in devel.

Running:

```bash
> grunt verifyAppData --new_keys
```

Or using the more verbose:

```bash
> gl-dev template_vars > client/template_vars.json
> grunt verifyAppData
```

Will generate a report of all of the detected issues with template variables used inside of volunteer translations.

Currently we are just looking for syntax issues. I will open another ticket that specifically looks at sanitizing the volunteer provided translations for malicious input. (None of which I have seen after manual some review)
