### ISSUE TITLE
Failure in PGP files creation causes file corruption

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1672]
As reported by ```RegioneToscana``` an encoding failure in saveAs implementation affects the file saving routines of the application.

This seems to happen not on all files but on some particular filetypes so that i think that the bug is related to the ```AutoBOM``` feature of filesaver that seems also to not be implemented correctly: https://github.com/eligrey/FileSaver.js/issues/219, https://github.com/eligrey/FileSaver.js/issues/217, https://github.com/eligrey/FileSaver.js/issues/186, https://github.com/eligrey/FileSaver.js/issues/156

**Comment by evilaliv3** [comment]
I think that we could simply disable the autobom; in fact if the file saved should be equal to a correct file upload, there is no need for the file to be altered in its encoding.

i think the autobloom is needed only when one is creating the file client-side, but for upload/download features as GlobaLeaks does this feature is totally unnecessary.

\cc @NSkelsey

**Comment by NSkelsey** [comment]
Damn, I explicitly used `application/octet-stream` to try to avoid these kind of problems.

Can we simply set `disableAutoBOM` to `true`? Any word on the failing file types. Let's document the issue with a test case.

**Comment by evilaliv3** [comment]
yes i think so; feel free to jump on this or i will do it tomorrow night as i'm currently in a car!

**Comment by NSkelsey** [comment]
Okay I will see what I can get down at this moment.

**Comment by eligrey** [comment]
@NSkelsey auto-BOM does not trigger with `application/octet-stream`. The only situation where auto-BOM is triggered is if `disableAutoBOM` is not `true` AND the content-type you specify matches `text/*;charset=utf-8`. My BOM mark might be the wrong value though, so I am looking into to changing that.

**Comment by evilaliv3** [comment]
gotcha @eligrey! thank you so much for your support and hints.

@NSkelsey i think that the issue is that in the final integration we simply created the blob without specifying the mime type, so the default apply and maybe is so the autoboom scatter in this case; @eligreym do you confirm it?

**Comment by eligrey** [comment]
Not sure, but a quick grep of your code doesn't appear to be resulting in any MIME types

When you type `Blob`, `URL`, and `URL.createObjectURL` in your console (while in your app), do you see `[native code]`? If not, this is a problem with angular overriding globals (I think someone mentioned something like that to me a while back).

If this is the case, you might want to [file a bug with angular.js](https://github.com/angular/angular.js/issues/new).

**Comment by evilaliv3** [comment]
Thanks.

We do not set explicitly the mime type because the payload comes to angular
that already set it.

Anyway nick it would be great to set it explicitly anyhow on the client by
changig it explicitly.

@fpietrosanti: reading better what regione toscana written the issue is on
encrypted Files so maybe it is impacting the encryption, decryption or
download of it! I will dig into this those days

**Comment by evilaliv3** [comment]
@NSkelsey / @fpietrosanti if you remember i handled recently the big file upload issues, handling soome refactor.

That refactor introduced an issue on the PGP file creation where we not decrypting the AES files.
This impacts only users that uses PGP.
