### ISSUE TITLE
Use sqlite3 secure_delete

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1678]
We are leaking information to disk when performing simple deletes with sqlite3.

To avoid analysis of deleted tips, messages, and other metadata further research of secure deleting is required

https://www.sqlite.org/pragma.html#pragma_secure_delete

**Comment by evilaliv3** [comment]
@NSkelsey what do to you think of this changes?

i've not discovered various aspects:
- auto_vacuum is the only pragma to be set before creating any table as it want to allocate additional data for working at runtime;
- foreign_keys instead should be enabled in every query and there is no need to enable them at db initialization

**Comment by evilaliv3** [comment]
implemented!

**Comment by evilaliv3** [comment]
i've documented what implemented and added also documentation for what relates the file overwrite performed by the platform [GlobaLeaks Application Security 
Design and Details](https://docs.google.com/document/d/1SMSiAry7x5XY9nY8GAejJD75NWg7bp7M1PwXSiwy62U)
