### ISSUE TITLE
Support Alternative Databases

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1679]
If we can define our create table in SQL that conforms to the ISO SQL-92 specification we will be able to support MySQL, MSSQL, Postgres and more from a basic language point of view.

Since nothing is especially complex defining the schema once in compliant SQL-92 with sqlite3, we can hit compatibility with other systems for free.

[1]: Comparison of db compatibility: http://troels.arvin.dk/db/rdbms/
[2]: The spec.txt: http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt 

Related to #785
\cc @fpietrosanti @evilaliv3

**Comment by evilaliv3** [comment]
Duplicated: https://github.com/globaleaks/GlobaLeaks/issues/1324
