### ISSUE TITLE
When the Receiver label a submission, the label is not saved

### ISSUE THREAD

**Issue by danilort** [globaleaks/GlobaLeaks#1681]
When the Receiver set the Label, this is not saved.

Steps to reproduce:
	• logon as Receiver
	• open one submission
	• write on text-box (es: MyTAG)
	• click the button 

![2016-05-27_124918](https://cloud.githubusercontent.com/assets/16148184/15605935/4ed16bd2-2409-11e6-9c3f-a9672f2cdef2.png)

Danilo

**Comment by danilort** [comment]
PS: Globaleaks  2.61.12

**Comment by evilaliv3** [comment]
Thank you for reporting this @danilort;

The bug has been identified and i'm going to fix it and implement the related testing in order to prove fix and add resiliency for further regressions.

**Comment by evilaliv3** [comment]
Fixed and unit test added.
