### ISSUE TITLE
Permission denied : AppArmor

### ISSUE THREAD

**Issue by EsterVR** [globaleaks/GlobaLeaks#1684]
I have done a fresh installation of Globaleaks on a new VPS (Proxmox with LXC) running Ubuntu 14.04 . During the installation process, I encountered the following error:
```

 * Enabling GlobaLeaks Apparmor Sandboxing...
Traceback (most recent call last):
  File "/usr/sbin/aa-status", line 194, in <module>
    commands[cmd]()
  File "/usr/sbin/aa-status", line 17, in cmd_enabled
    if get_profiles() == {}:
  File "/usr/sbin/aa-status", line 92, in get_profiles
    for p in open(apparmor_profiles).readlines():
PermissionError: [Errno 13] Permission denied: '/sys/kernel/security/apparmor/profiles'
   ...fail!
Unable to initialize AppArmor!
AppArmor is probably disabled; please enable it by following instructions at https://wiki.debian.org/AppArmor/HowToUse

```

I am not trying to be smart this time, but waiting for your advice :)

**Comment by evilaliv3** [comment]
It is possibile that the promox kernel you are using does not support
apparmor.

You have two possibiluties:
- change the kernel
- disable the apparmor sandboxig in the meantime you change the kernel :)
you could do it setting the apparmor sandboxig to 0 in
/etc/default/globaleaks

**Comment by fpietrosanti** [comment]
"Use of libvirt-lxc is not generally recommended due to a lack of Apparmor protection for libvirt-lxc containers." from https://help.ubuntu.com/lts/serverguide/lxc.html

Opened ticket #1686 to detect the condition, preventing the installation and informing about the limit, at installation time and startup time.

**Comment by EsterVR** [comment]
The kernel we are using supports AppArmor. In fact Proxmox 4 comes with AppArmor support by default since it is used to provide resource isolation in the container. Proxmox 4 doesn't work without Apparmor.

**Comment by fpietrosanti** [comment]
@EsterVR If i understood, the LXC container "inside itself" have some problem in using AppArmor, but it's mostly used to protect the "host" operating system isolating different "containers" among themeselfe ?
https://help.ubuntu.com/lts/serverguide/lxc.html#lxc-apparmor

**Comment by evilaliv3** [comment]
This issue was in the end solved by identifying that that was an issue on the apparmor configuration of the node instead of globaleaks itself.
