### ISSUE TITLE
The URL on the notifications email don't work well

### ISSUE THREAD

**Issue by danilort** [globaleaks/GlobaLeaks#1689]
GlobaLeaks Version: 2.61.12

The keywords %TorURL% (notification templates) don't work well.
(the old version 2.60.121 was working well)

The URL on the email is correct:
http://v3xoewpevrengdp3.onion/#/status/59b3ceeb-3dc3-4215-aecf-921c75a9c9aa
but when I click, I arrive on the home page:
http://v3xoewpevrengdp3.onion/#/

What I expect:
	- the Receiver copy&paste the URL in torBrowser
	- insert user/psw
	- the Receiver see directly the submission

Ciao, Danilo

**Comment by NSkelsey** [comment]
Thanks Danilo,

@evilaliv3 this error has to do with the new `requiresAuth` and `noAuth` resolvers. The path is not saved in the `dest` param (thats not the right name) for redirect after login like it used to be.

A very simple testcase needs to be written to catch this in the future.
