### ISSUE TITLE
Allow the configuration of the default password via advanced settings

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1691]
As discussed with @evilaliv3 the Wizard will no longer require admin authentication.

Within the the wizard the field admin password is exposed. This space could be used to set the default password for all new users of the system and additionally be a configurable setting by the admin in the backend.

This removes the exposure that creating new users has when a platform has been online for a long time and the default credentials are allocated to some new receiver.

**Comment by fpietrosanti** [comment]
Are we going to have a sort of "initiatized vs. un-initialized" state

**Comment by NSkelsey** [comment]
Yep, in fact we already do. The return of /node signals whether the wizard has been completed or not.

**Comment by evilaliv3** [comment]
The default password of the system is now configurable by the admin in the Advanced Settings.

I would suggest for now to not add this configuration during the wizard for now in order to not complicate that much the wizard.
