### ISSUE TITLE
the wizard operations should be atomic

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1692]
Analizing changes related to https://github.com/globaleaks/GlobaLeaks/issues/1691 i think it would be important that the wizard operations become atomic.

Right now, a malicious user to log in before the wizard is completed and alter the settings.

The real admin will then log in without noticing this changes.

It would be important to implement the wizard as an atomic operation that prevents to perform any action on the configuration before it is accomplished.

**Comment by evilaliv3** [comment]
@NSkelsey / @fpietrosanti: i've already implemented quite alle this changes and i'm near to show you.

Basically what i've implemented, that for me is a big improval is the fact that the admin user is now created and activated during the wizard. The interface is still the same but basically it would not be possible for a custom client to bypass the wizard and enter as admin by changing settings before the admin logs in completing the real wizard.

This way only the first user that will complete it will end in changing the password with guarantees that no other users would have changed anythings.

**Comment by NSkelsey** [comment]
ACK, I like this model.

**Comment by vodkina** [comment]
Could you please, estimate the issue?!

**Comment by evilaliv3** [comment]
@NSkelsey by today i will release the devel, then cherrypick this commit in devel.

If you want this morning you can already cherry-pick into the browser crypto and work on the admin key generation. what do you think?

**Comment by NSkelsey** [comment]
Will do.

**Comment by evilaliv3** [comment]
merged into devel!
