### ISSUE TITLE
Improve UX for Receipt Inquiry removing 1 click/enter

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1693]
This ticket is to improve UX for Receipt Inquiry removing 1 click/enter.

I just did noticed on AirBnb registration platform that, when you have to type the SMS-verification code of 4 digits, as long as you type the last-digit the interface automatically start a confort indicator saying that's "logging in".

We may do the very same with the receipt input, by automatically using it as long as the last digits is typed by the whistleblower.

**Comment by evilaliv3** [comment]
Implemented!

The new UI looks as following:
![screenshot-127 0 0 1-8082-2019 07 24-23-29-41](https://user-images.githubusercontent.com/217034/61830264-ffa0b780-ae6a-11e9-9b5a-00b3c0821dab.png)

![screenshot-127 0 0 1-8082-2019 07 24-23-33-52](https://user-images.githubusercontent.com/217034/61830481-881f5800-ae6b-11e9-987e-d422e27927da.png)
