### ISSUE TITLE
Failure in sending email about tip expirations

### ISSUE THREAD

**Issue by danilort** [globaleaks/GlobaLeaks#1696]
Hello, 
I think it would be useful to add a notification, which alerts the Receiver that the TIP is about to expire.
The Receiver can then decide to extend the expiration date.

I suggest to add also new keyword for the notification templates:  %TipExpiration%.

Ciao, Danilo

**Comment by evilaliv3** [comment]
This feature existed in past as requested by various adopters (https://github.com/globaleaks/GlobaLeaks/issues/748).

I would mark this as a bug to be investigated.

**Comment by evilaliv3** [comment]
Fixed; will be released in the next release.
