### ISSUE TITLE
Disable browser autocomplete for html elements

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1698]
To reduce the number of traces in the user's browser it is nessecary to inform compliant browsers to set `autocomplete=off`

Additionally, browsers that support this behavior empirically should be documented.

Commit 098746b addresses the implementation. Tests are still TODO.

**Comment by NSkelsey** [comment]
This is hard to test in Chrome due to the default configuration of the chrome profiles for selenium web drivers.

Firefox profiles may be easier to configure to set autofill properties.

This means that each browser may or may not support autofill (or the ability to disable it).

To close this ticket every form in the application should by default set `autocomplete` to `off`.

**Comment by evilaliv3** [comment]
The relevant forms that require autocomplete==off now have it.

I've completed this change in https://github.com/globaleaks/GlobaLeaks/commit/a648f248c743c84d7bcf0eaecfe643e42b117299

It involve:

- submissions forms (for the whistleblower)
- messages and comments (both for whisteblower and recipients)
- the receipt login (for the whistleblower)
- the authentication login (for every user)

**Comment by evilaliv3** [comment]
Done!
