### ISSUE TITLE
Customized css is not applied

### ISSUE THREAD

**Issue by EsterVR** [globaleaks/GlobaLeaks#1701]
I am trying to customize the layout of a Globaleaks site but the CSS that I am uploading through the admin interface does not take effect. I can also not find the uploaded css file on the server (via ssh).

q1) Where should the uploaded css be stored?
q2) Any idea why it is not applied?

**Comment by NSkelsey** [comment]
@EsterVR did you have some luck?

Is there anyway we can improve the UI?
