### ISSUE TITLE
Verify that PGP keys and encrypted payloads generated clientside do not leak browser information

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1709]
Given the upcoming browsercrypto module implementing key generation and encryption client-side, it would be important to verify that keys generated client-side and encrypted payloads do not leak browser information.

In the specific we should verify that openpgp.js is:
- the generated keys and algorithms used are not browser dependent.
- the algorithms selected when doing encryption are not browser dependent.

**Comment by evilaliv3** [comment]
@tanx is there some browser dependent selection of algorithms involved in key generation or in encryption that we should keep in mind?

\cc @toberndo @fpietrosanti

**Comment by tanx** [comment]
Not that I know of.

**Comment by evilaliv3** [comment]
Okay, thanks; i will take this open in order to pay a bit of attention to it.

**Comment by vodkina** [comment]
is this an issue pertaining to the current (june) milestone? If so, please estimate it. Thanks :)

**Comment by evilaliv3** [comment]
moved out of the milestone for now.
