### ISSUE TITLE
Init.d service generates mangled logs

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1723]
From a production system we are seeing the first line of every log file generated with a-bunch of ^@a's

This will remain a TODO until it can be reproduced elsewhere.

**Comment by evilaliv3** [comment]
I've investigated the bug and it seems to me to not be an issue with the platform.

To be verified if the issue is not related to the adopter setup where i remember that logs are subject to zip thanks to some external software.

**Comment by NSkelsey** [comment]
No longer present.
