### ISSUE TITLE
Extend field triggers to function with fields in nested groups

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1727]
Right now the field triggers (optional questions) implementation allow the trigger to be only at the root level of the questionnaire and not inside a nested structure of fields.

This ticket is to keep track of the current status of the implementation and of the work for extending fields triggers to hierachic fieldgroups groups.

**Comment by NSkelsey** [comment]
Some observation's taken from a meat space discussion on this topic with @evilaliv3 

- The backend schema currently fully supports this functionality
- The frontend logic needs to be adjusted to handle the triggers better
- Selection of a field option is not a robust trigger and we could look to extend other acceptable answers
- The nested field group User interface could handle nesting by adding margins and indenting less

**Comment by NSkelsey** [comment]
Some notes from the admin UI in admin > questionnaires > step > field "multichoice" > field opts

- Newly added fields are not added to the selection boxes used to select possible triggers.
- All three triggers can be applied, which breaks validation of the option on submission to backend (minor). These options should just be exclusive toggles.
- The implementation lives around 290 in `admin/questionnaires/fields.html`
- Its still not clear what's preventing the nesting other than the disable of the UI.

**Comment by NSkelsey** [comment]
The challenge with 4) lies within the fact that $scope.sibilings is used to attach triggers.

I think that this may have been attempt to optimize the queries to speed up the performance of serializing questionnaires for /public and /admin/questionnaires, where the attached triggers are joined to each field query as we recursively extract fields from the db

The all of the queries related to field serialization:
```bash
2017-09-01 17:51:18+0200 [-] [17:51:18.776666] EXECUTE: u'SELECT field.description, field.editable, field.fieldgroup_id, field.hint, field.id, field.instance, field.label, field.multi_entry, field.multi_entry_hint, field.preview, field.re
quired, field.stats_enabled, field.step_id, field.template_id, field.triggered_by_score, field.type, field.width, field.x, field.y FROM field WHERE field.step_id = ?', (u'b9ade647-3c3d-4a3d-8376-2a7ca57576eb',)
2017-09-01 17:51:18+0200 [-] [17:51:18.777603] DONE
2017-09-01 17:51:18+0200 [-] [17:51:18.806098] EXECUTE: u'SELECT field.description, field.editable, field.fieldgroup_id, field.hint, field.id, field.instance, field.label, field.multi_entry, field.multi_entry_hint, field.preview, field.re
quired, field.stats_enabled, field.step_id, field.template_id, field.triggered_by_score, field.type, field.width, field.x, field.y FROM field WHERE field.fieldgroup_id IN (?, ?, ?)', (u'dda6fd50-0b51-4ea2-bb41-cc6465a09a52', u'2cbc7c06-4a
ff-4d1a-a408-e65fe899f31f', u'588719d6-3f6a-4f88-a026-792a3192ba45')
2017-09-01 17:51:18+0200 [-] [17:51:18.807274] DONE
2017-09-01 17:51:18+0200 [-] [17:51:18.815812] EXECUTE: u'SELECT fieldattr.field_id, fieldattr.id, fieldattr.name, fieldattr.type, fieldattr."value" FROM fieldattr WHERE fieldattr.field_id IN (?, ?, ?)', (u'dda6fd50-0b51-4ea2-bb41-cc6465a
09a52', u'2cbc7c06-4aff-4d1a-a408-e65fe899f31f', u'588719d6-3f6a-4f88-a026-792a3192ba45')
2017-09-01 17:51:18+0200 [-] [17:51:18.817252] DONE
2017-09-01 17:51:18+0200 [-] [17:51:18.867266] EXECUTE: u'SELECT fieldoption.field_id, fieldoption.id, fieldoption.label, fieldoption.presentation_order, fieldoption.score_points, fieldoption.trigger_field, fieldoption.trigger_step FROM f
ieldoption WHERE fieldoption.field_id IN (?, ?, ?)', (u'dda6fd50-0b51-4ea2-bb41-cc6465a09a52', u'2cbc7c06-4aff-4d1a-a408-e65fe899f31f', u'588719d6-3f6a-4f88-a026-792a3192ba45')
2017-09-01 17:51:18+0200 [-] [17:51:18.870402] DONE
2017-09-01 17:51:18+0200 [-] [17:51:18.875370] EXECUTE: u'SELECT fieldoption.field_id, fieldoption.id, fieldoption.label, fieldoption.presentation_order, fieldoption.score_points, fieldoption.trigger_field, fieldoption.trigger_step FROM f
ieldoption WHERE fieldoption.trigger_field IN (?, ?, ?)', (u'dda6fd50-0b51-4ea2-bb41-cc6465a09a52', u'2cbc7c06-4aff-4d1a-a408-e65fe899f31f', u'588719d6-3f6a-4f88-a026-792a3192ba45')

```
It would be much faster to extract all of the triggers before hand and only after the fact attach them to the serialized fields. This however breaks the recursive serialization we from `serialize_questionnaire`.

**Comment by NSkelsey** [comment]
Nota bene that the above queries actually request all related fields that are triggered by a specific field.

This means we don't need to pass $scope.sibilings into the `field select option`, but instead an enumeration of all of the fields that are at the current fields level or lower in the Questionnaire hierarchy.

**Comment by evilaliv3** [comment]
@NSkelsey: I've currently reverted the addition of the patch from devel.

Few issues where not satisfied and should be corrected before integrating it.
1. it was not possible to configure a trigger on a field option of field level > 1 (that is the main and only topic of the ticket)
2. if manually injecting such a configuration the resultin submission interface was failing to activate the field when the option is selcted.

point 1 is a minor correction that will involve the removal of an ng-if condition; the latter istead requires proper update of the isFieldTriggered function by making it work on multiple layers while currently it uses the ```answers``` dictionary that is just a map of the root fields.

The main reason of the current implementation and limit to the first level is a performance issue related to evaluate for each level the full three of fields; To reach this goal a proper implementation should probably evaluate to perform a single visit of the tree to determine the activation of each field keeping a map {fieldid: active} or directly storing this state inside the field tries.
