### ISSUE TITLE
Fix Translation in tip delete

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1729]
The second sentence does not describe WHAT to delete.

![schermata 2016-07-18 alle 4 23 17 pm](https://cloud.githubusercontent.com/assets/1095794/16917962/0b5ca226-4d04-11e6-82fd-8d7681d567a6.png)

It should be something like:

```
Please make sure that you securely delete all of the files on your computer
and other receivers' computer related to this submission.
```

**Comment by evilaliv3** [comment]
Nick would you please fix this sentence?

here are currently mixed the foollowing two concepts:
1) if you confirm, the data on the platform will be definitely lost;
2) regardless of the platform if the intention is  to delete the content, be sure to delete your copies.

i would probably go for communicating only 1) for now.

**Comment by NSkelsey** [comment]
```
Are you sure that you want to delete the submission?

Everything related to the submission stored on the platform will be deleted.

Please be aware that everything stored off of the platform like files you have saved on your computer must be deleted manually.
```

@evilaliv3 my humble submission, the last line is bonus.

**Comment by evilaliv3** [comment]
Ok i like them. Let's put them all and eventually we will remove the last one if not understood by the users.

**Comment by evilaliv3** [comment]
bam!

**Comment by evilaliv3** [comment]
@NSkelsey the france language coordinator proposed this change:

key Please be aware that everything stored off of the platform like files you have saved on your computer must be deleted manually.
Long sentences like that are heavy, it should at least be punctuated, possibly :"Please be aware that everything stored off the platform, e.g. files you have saved on your computer, must be deleted manually."

**Comment by NSkelsey** [comment]
Better!
