### ISSUE TITLE
Unique identifier for Tips does not use UTC

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1734]
An adopter has noticed that the submission counter order occasionally reports incorrect sequence numbers.

![submissions](https://cloud.githubusercontent.com/assets/1095794/17019926/30056f62-4f3f-11e6-9b4b-a1ecd010bf01.png)

The problem is that we generate the tip Name on the frontend using the angular `date` filter, which uses the browsers local time to express the date. When the sequence counter is generated on the backend, UTC is used.

The call in the tipFileName filter looks like this:
```
var d = $filter('date')(tip.creation_date, 'yyyyMMdd');
```

And it is missing the [optional timezone argument](https://docs.angularjs.org/api/ng/filter/date) which should use UTC+0:
```
var d = $filter('date')(tip.creation_date, 'yyyyMMdd', '0');
```

**Comment by NSkelsey** [comment]
What will happen if we add the `UTC+0` param is the following:

Any tip that was created after midnight on local time will have see sequence date change.

So `20160714-2` will become `20160713-2`

**Comment by evilaliv3** [comment]
good to go for me nick. if you open a pull request i will merge it!

**Comment by evilaliv3** [comment]
works for me, reviewd and merged in devel.

**Comment by NSkelsey** [comment]
@evilaliv3 I will open a ticket on using a platform wide TZ instead of a recipient based one, so that this display along with the date-times used in other interfaces use the same TZ across users and places.

**Comment by evilaliv3** [comment]
i agree that won't be bad to have the possibility to disable the user defined timezones and adopt a systemwide timezone related to the platform.

this way we will conserve the requirement of not leaking the timezone of the platform for the initiative where this is perceived as critical and we will satisfy your need of having all unified on a specific timezone.

in that feature so specify to have the possibility to:
- enable a global timezone
- personalize this global timezone

i wonder if we implement this if we could remove the user specific timezone that has been anyhow never used.

\cc @fpietrosanti: what do you think? answer after reading this entire issue.

**Comment by NSkelsey** [comment]
@evilaliv3, for initiatives that do not want to disclose this info they will just not set a timezone?

One more point
1) At migration time the system timezone will be set to UTC+0. This will change the display of the dates and times in the tip interface for events occurring.
In general I think we should have a way to notify users of changes introduced by newer versions of the software. Something like the dates changing silently is bad UX!

**Comment by fpietrosanti** [comment]
IMHO that's just a normal web application, so the time representation should have:
1. a system wide timezone configuration (set with a selector with all the TZ)
2. a recipient specific timezone configuration (to enable the user to have a representation of time, relative to it's timezone, think a multi-national with 6 recipients on 6 different timezones)

If we consider that leaking the timezone information is a risk:
a) When/where it's leaked on the public interface of the whistleblower?

**Comment by evilaliv3** [comment]
@fpietrosanti i resume the issue because identified by nick that i confirm:
1) for sure we have to switch a node timezone for the Tip Unique identifier, because an ID like 20160701-01 cannot change depending on the timezone of the user; this was happening and different users where viewing different ID depending on their relative timezone.

2) as extension of the issue 1 in general i'm perceiving as a big usability issue that users does not perceive the same remote timezone, because this make difficult to cooperate; so if you want to maintain this local timezone, the interface for each date should start to be explicit on the timezone used (e.g. writing GMT+1 near every date, if the current user timezone is set on GMT+1)

**Comment by NSkelsey** [comment]
I think Fabio's solution works. Have a node setting and a user setting, where the application's default is UTC.

- Sequence numbers always use UTC, so that they do not change based on changing config.

- We stop performing the Timezone sniff that gives us the local TZ for the user.

- The dates displayed to Users, prefer their local settings over the nodes config.
