### ISSUE TITLE
Deny the whistleblower to copy contents of the application inside its clipboard

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1735]
Right now the platform allows the whistleblower to copy contents of the applications inside its clipboard.

This could represent a security issue that could bypass the security measure put in place in order to prevent to leave forensic traces on the browser.

This ticket is to discuss the possible protections that could be:
1. deny the whistleblower to copy any content on the clipboard
2. deny also to the recipient to copy any content on the clipboard
3. make the eventual 1. and 2. as configurable features.

i'm for implementing only the 1 as an enforced behaviour configured by CSS and for not implementing nor the 2 and the 3.

@NSkelsey @fpietrosanti what is your thinking?

**Comment by evilaliv3** [comment]
```javascript
if ($rootScope.Utils.isWhistleblowerPage()) {
  if ((e.ctrlKey || e.metaKey) && (((e.which || e.keyCode) === 65) ||   /* (ctrl or meta) + a */
                                   ((e.which || e.keyCode) === 67))) {  /* (ctrl or meta) + c */
    e.preventDefault();
    return;
  }
}
```

**Comment by evilaliv3** [comment]
The above code is more interesting than the CSS code as i found the css code to be strongly faulty on various browsers.

**Comment by fpietrosanti** [comment]
I think that being a concious action by the Whistleblower (that Will have it'own reasons and thinking about The action of Saving what he submitted, doing an explicit/conscious action of selecting and copying the data), he should not be prevented from doing it.

If there's a security risks, let's define a risk scenario and how this feature would address it

**Comment by evilaliv3** [comment]
from my point of view the security risk exists; if the user copy the receipt or other initiative specific contents onto the clipboard this contents could be leaked undefinitely there.

**Comment by evilaliv3** [comment]
Input for this ticket collected during the ISO 27001 audit.

**Comment by fpietrosanti** [comment]
The content in the clipboard is stored in the volatile memory of the computer, like the browser web page content, but it get overwritten automatically everytime there's a new copy and paste or computer is rebooted. 
I see no clear risk compared to the same risk related to browser data staying in volatile memory until it's closed or worst risk of swap paging content of the submission by the browser.

But we would just make a bit harder for the Whistleblower from archiving it's own stuff, if he wish (that's not an accidental mistake, but a conscious action), forcing him to bypass our "security" procedure by doing a photo or worst printing it (writing other data to disk, such as printer spool file).

**Comment by evilaliv3** [comment]
i may agree on the first part of the defense of your point, and i've already reverted the changed but let me comment that the second part does not make any sense.

for sure whistleblowers can make mistakes out of the platform, but the platform has to implement the better policies anyhow; if we follow your suggestion most of the features that we have could be trashed, like the data retention policy make no sense if users keep their data everywhere.
