### ISSUE TITLE
Disable cat and paste on password confirmation inputs

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1736]
Currently the platform allows cat and paste on password confirmation inputs.

This is not generally recommended as it allows the user to cut and paste a wrongly typed function fooling the user and ending in saving and unknown password.

**Comment by evilaliv3** [comment]
The following seems a good solution: http://stackoverflow.com/questions/27783144/disable-cut-copy-and-paste-function-for-textbox-using-angularjs

```javascript
app.directive('stopccp', function(){
    return {
        scope: {},
        link:function(scope,element){
            element.on('cut copy paste', function (event) {
              event.preventDefault();
            });
        }
    };
});
```

```javascript
<input stopccp ng-model="val" />
```

**Comment by evilaliv3** [comment]
Input for this ticket collected during the ISO 27001 audit.

**Comment by NSkelsey** [comment]
I agree with Fabio

**Comment by evilaliv3** [comment]
closing as completed and integrated in devel.

**Comment by evilaliv3** [comment]
Marking as discarded to track that this implementation was deprecated following community consensus in: https://github.com/globaleaks/globaleaks-whistleblowing-software/issues/2028
