### ISSUE TITLE
Backup script help informs the user of arguments not used

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1744]
The current backup script (gl-admin backup) help inform the user of the possibility to use some commands arguments that are not used in the real.

e.g.: gl-admin backup mention the possibility to explicit the destination path for the backup to be created but this argument is not used by the script.

this ticket is to keep track of the fix of such an issue by:
- change the BASENAME argument to BASEPATH that is more explicit in communicating that the argument can host a full path (relative/absolute)
- making possible to choose the above BASEPATH in the real!

**Comment by NSkelsey** [comment]
We should use a real config parser for the admin script.

**Comment by evilaliv3** [comment]
What do you mean with config parser?
Il 05/Ago/2016 12:52 "Nick Skelsey" <notifications@github.com> ha scritto:

**Comment by evilaliv3** [comment]
More than a config parser i think we should use an option parser.

We could use the same already used in bin/globaleaks: https://docs.python.org/2/library/optparse.html
```from optparse import OptionParser```
