### ISSUE TITLE
Allow configuration of the Tor Browser download link

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1745]
The privacy badge is since ever including a hardcoded ```Download the Tor Browser``` link that points to https://www.torproject.org/download/download

With the [GetTor](https://github.com/globaleaks/Tor2web/wiki/GetTor) feature of Tor2web (https://github.com/globaleaks/Tor2web/issues/168) the platform could serve Tor directly.

This added value helps:
 - simplify the user adoption of Tor, serving directly the Tor browser for the operating system and the language of the user;
 - allowing to bypass censorship of the main Tor distributions servers (e.g.: torproject.org)
 - improve the security of the download, avoiding to leak external evidences of the interest by the whistleblower of downloading the Tor browser.

This ticket is to track the changes needed for making the Tor browser link configurable from the admin panel.

**Comment by NSkelsey** [comment]
Fixed and release in 2.63.0
