### ISSUE TITLE
Recover expired data

### ISSUE THREAD

**Issue by strikerno19** [globaleaks/GlobaLeaks#1746]
My CEO forgotten open e-mail from globaleak since May 2016, My CEO want to recovery expired data from database, please recommend how to recovery expired data. Thank You

**Comment by NSkelsey** [comment]
strikerno19: I am sorry this happened to you. Once the data is deleted it is deleted permanently. The defaults are designed to protect at risk organizations.

To avoid this in the future increase the tip expiration time to many years and use the tip access expiration setting (new in version 2.63.0) to permanently revoke a whistleblower's access.

**Comment by strikerno19** [comment]
Thank you, for your recommended. I'm not sure, if I update version for change tip access expiration setting to version 2.63.0 will have an impact to systems or not

**Comment by fpietrosanti** [comment]
@strikerno19 If you are doing a professional uses of Whistleblowing, would you please consider supporting GlobaLeaks project with some donations or maintenance contract to get dedicated support and contribute to the r&d roadmap :*

**Comment by NSkelsey** [comment]
Closing this as informational.
