### ISSUE TITLE
Enable insecure configuration without PGP encryption

### ISSUE THREAD

**Issue by Taipo** [globaleaks/GlobaLeaks#1753]
It appears that when "Enable insecure configuration without PGP encryption" is deactivated, submissions are being blocked.

Email notifications are still being encrypted correctly when PGP is configured, however irrespective of having a valid PGP key registered by the receiver, if that advanced setting is disabled/deactivated, whistle-blowers are unable to complete a submission.

Once reactivated, submissions are enabled again.

Server: Ubuntu Server 14.04.4 x64

**Comment by NSkelsey** [comment]
@Taipo are you on the latest release?

**Comment by Taipo** [comment]
As of an hour ago, yes.

**Comment by NSkelsey** [comment]
Can you verify that the context you are using has a receiver attached to it?

If that is not the problem I will try to recreate it, locally

**Comment by Taipo** [comment]
Yes it has a receiver. Keep in mind, every works ok if  "Enable insecure configuration without PGP encryption" is enabled.

**Comment by NSkelsey** [comment]
@Taipo, thank you for finding the issue and submitting the ticket.

I really cannot reproduce your problem.

With two receivers with PGP keys and the enabled insecure checkbox checked, I can (as a WB) create submissions:
![schermata 2016-08-24 alle 11 05 16 am](https://cloud.githubusercontent.com/assets/1095794/17924904/f2a0e18a-69ea-11e6-864e-63210b113959.png)

Two new questions:

- Can you ping `synnick` [(on IRC)](https://kiwiirc.com/client/irc.oftc.net/?nick=gl-?#globaleaks)?
- Where exactly are you getting blocked from submitting? 


At the home page (Here)?
![schermata 2016-08-24 alle 11 05 48 am](https://cloud.githubusercontent.com/assets/1095794/17924981/49b51f72-69eb-11e6-9da6-f688c4119443.png)

Or at Receiver selection?
![schermata 2016-08-24 alle 11 10 23 am](https://cloud.githubusercontent.com/assets/1095794/17925001/62b41cda-69eb-11e6-99ff-16b913ca6e2b.png)

Or somewhere else. . .

**Comment by Taipo** [comment]
I was also able to create a submission in that configuration. The problem is the very opposite of that. When Unticked, submissions are prevented, even if valid PGP key is present.

**Comment by Taipo** [comment]
So for example:
![disabled](https://cloud.githubusercontent.com/assets/5398266/17925346/b5126df6-6a40-11e6-87d7-1e74bfa7a1e3.png)

When completing the submission, the Submit button remains disabled.
![submit](https://cloud.githubusercontent.com/assets/5398266/17925351/b8c1adfe-6a40-11e6-9f27-5877e64572d0.png)

**Comment by NSkelsey** [comment]
Okay, that is a well tested use case. The application definitely works in that setup.

I suspect that the PGP key you configured for the user is invalid. Can you show (receiver -> preferences -> PGP Key) to me.

**Comment by Taipo** [comment]
Oh its very valid.

![encryption_enabled](https://cloud.githubusercontent.com/assets/5398266/17925680/09850af0-6a42-11e6-824f-2db65afa29a9.png)

With it set to enable insecure config, I am still getting encrypted notifications which I can and have decrypted.

**Comment by NSkelsey** [comment]
Okay @Taipo, I don't have a solution for you and I need to go do other things. We will leave the ticket open until it gets resolved. This is a bug that our tests don't catch.

Try contacting [Whistleblowing Solutions](http://whistleblowing.solutions/) for professional support if this is something you need resolved right away.

**Comment by Taipo** [comment]
Thanks for that. As it stands, it works fine as long as I leave that setting enabled. Just thought I should report it anyway.

**Comment by evilaliv3** [comment]
Bug confirmed, patch on its way.

**Comment by evilaliv3** [comment]
The patch will be shipped in 2.63.3

**Comment by evilaliv3** [comment]
@Taipo the package has been released if you want you can proceed updating and revert the setting you changed for make it work temporarely.

**Comment by Taipo** [comment]
2.63.3 is still not accessible from updates

**Comment by evilaliv3** [comment]
thanks for reporting Taipo, i will recheck in a bit and update you when done.

**Comment by evilaliv3** [comment]
You were right @Taipo.

Due to a typo in the package version there was an issue in the release process.
I've now issued and released 2.63.4 that improve some translations updates and minor UI fixes.

let us know if your issue is fixed.

**Comment by Taipo** [comment]
Issue is fixed thanks for that.
