### ISSUE TITLE
Add reasons why submission cannot be completed in the interface

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1754]
Text should be added under the submission interface to show what is preventing the submission button from becoming active.

Would have solved #1753

**Comment by NSkelsey** [comment]
There is also a problem with the string used for email and the email validation regex <- !!!

In english the text reads something like:
```
The specified input is not valid: please enter a valid email address. please enter numbers only. please enter numbers only.
```

**Comment by NSkelsey** [comment]
Two options for the UI.

## Option A
![schermata 2016-09-28 alle 3 13 22 pm](https://cloud.githubusercontent.com/assets/1095794/18914837/f9df831a-858e-11e6-91ca-590a0e8c16e5.png)

## Option B
![schermata 2016-09-28 alle 3 16 52 pm](https://cloud.githubusercontent.com/assets/1095794/18914855/0b0405b2-858f-11e6-9274-bf0af66cfc11.png)

I think B is a bit more visible.

**Comment by evilaliv3** [comment]
Good to go for version B!

**Comment by NSkelsey** [comment]
The UI as it stands now. 

I have split problems with steps out from problems with the final step of performing the submission. When you click next step and their are errors the top error box will appear.

When you get to the final page, if submissions are disabled you will be told why in the bottom box.

![schermata 2016-09-28 alle 6 43 28 pm](https://cloud.githubusercontent.com/assets/1095794/18923135/7810126a-85ab-11e6-8b88-099941870e41.png)

**Comment by evilaliv3** [comment]
Good work.

I suggest to come out with one only summary. We will continue to have also inline indicators of falures, wanting to separate multiple summaries with different meanings will be confusing for the user.
In addition always consider what planned in the future when you develop a feaure: if it is real that currently one can arrive advance in the steps without selecting the recipients, that wont be possible with the browser encryption.
This means that if one will be in Step N all errors of Steps < N will be already ok; e.g.: you wont have a "you must select at least one receiver error".

**Comment by evilaliv3** [comment]
@NSkelsey i just got your point regarding putting the message at the end.

It works also for me but considering that we have multiple steps, what about having the message organized as the following:

```
Some errors are preventing the completion of the submission
  Step 1:
     - at least one receiver should be selected
 Step 2: 
    - 3 question(s) are missing the answer or the answer is not valid
    - 1 file(s) is still being uploaded
  Step 3:
    - 3 question(s) are missing the answer or the answer is not valid
```

as i was saying above, probably the error on the recipient selection will disappear with the browser-crypto integration.

important thing to be considered is the difficult internationalization that we will face with sentences like the one written above that mixes texts and numbers.

**Comment by NSkelsey** [comment]
### Final Submission Error panel
![schermata 2016-10-04 alle 5 56 59 pm](https://cloud.githubusercontent.com/assets/1095794/19082246/9bd4f4ac-8a5d-11e6-84e5-4f35a7956abe.png)


### Step Error panel
![schermata 2016-10-04 alle 6 00 24 pm](https://cloud.githubusercontent.com/assets/1095794/19082240/97800bbc-8a5d-11e6-97ff-b21c6cd7746b.png)

**Comment by NSkelsey** [comment]
@evilaliv3 can confirm that a file upload in process is not displaying in the submission error panel correctly.

Needs to be addressed.

**Comment by evilaliv3** [comment]
String readded corrected in "Waiting for the file(s) to finish uploading."

I consider this a temporary fix;
The final interface for the file upload would not have to block the user in clicking the submit button but would have to be something implemented in the loader shown to the user after he/she clicked the button and would have possibly to be impemented with graphical elements in order to minimize the translation effort.
