### ISSUE TITLE
Perform a secure delete on migrated db files.

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1760]
We need to use secure delete for database files during migrations, otherwise we are leaving around information on the system that is potentially leaking sensitive information.

Currently we use `os.remove(orig_db_file)` to delete the old database (and tmp db's) in [migration.py](https://github.com/globaleaks/GlobaLeaks/blob/master/backend/globaleaks/db/migration.py#L187-L194)

This is important as we move to encrypt more content stored in the DB.

**Comment by evilaliv3** [comment]
Very good and important catch @NSkelsey!

As the patch seems so easy when you want commit it so that we could include it in the next stable release.

**Comment by evilaliv3** [comment]
Fixed by @NSkelsey in e6d26380
