### ISSUE TITLE
Switch the default of allow_indexing to true by easing the reachability of the globaleaks based projects

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1763]
By design GlobaLeaks is designed to maximize its reachability; at the start there was the intent to have it widely used with possible whistleblower finding the initiatives directly by surfing on google.

since the start instead we always denied to it to be crawled by spiders.

I think that this is against our initial ideas.

I would suggest to switch the default of allow_indexing to true, and let the user eventually set it manually to false.

I think this will satisfy better most of the use cases where users wants their initiative to be publicly available; Only few uses cases that i have in mind (maybe even none) required to not have crawling disabled.

**Comment by evilaliv3** [comment]
@vecna @NSkelsey @fpietrosanti @Taipo what do you think?

**Comment by fpietrosanti** [comment]
@evilaliv3 We may generate the Sitemap XML and few other metadata that are useful/required by search engines

**Comment by evilaliv3** [comment]
Yep the idea of the sitemap is good and we can export some of the main information like:

"/" langing page
"/submission" submission page

and thats it, and enable this API only in case the crawlers are enabled (that will be the default).

**Comment by evilaliv3** [comment]
The sitamap.xml is also in place as described above.
