### ISSUE TITLE
Error Message: TypeError: Cannot read property 'insertBefore' of null

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1766]
A production environment is triggering the exception "Error Message: TypeError: Cannot read property 'insertBefore' of null".

This seems to happen on the admin interface on the url: "/#/admin/content"

The setup is using version 2.62.3 and the failure is probably related to the languages hotfix feature.

**Comment by evilaliv3** [comment]
@NSkelsey: lets skip to investigate this for now, i will get additional information during the morning and update the ticket.

I do not think this issue still exists on recent versions because the feature is now highly tested by the recent end2end tests.

The bug seems to happen on Safari and IE, but i've not got it while using Chrome.

**Comment by vodkina** [comment]
we are now at version 2.65.4. Is this bug yet actual or is it superseded in new version?

**Comment by evilaliv3** [comment]
This has still not be reproduced. Let's just remove the ticket from the milestone but keep the ticket open.

**Comment by evilaliv3** [comment]
Closing as outdated.
