### ISSUE TITLE
Test notification email is not subject to mail templating and variables replacement

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1771]
Current implementation of the test email notification is not subject to mail templating and variables replacement.

As result mail are currently sent out like the following:

```
Dear Administrator,

This is a test email sent out from the platform's administrative interface.

Reception of this email indicates that the server was able to authenticate to and interact with the SMTP mail server.

Kind regards,
%NodeName%
```

This ticket is to keep track of the changes needed in order to fix the issue;

**Comment by evilaliv3** [comment]
Given whast involved it is higly possible that this ticket will require important refactor of the templating system.

**Comment by NSkelsey** [comment]
Why does the test mail need to be subject to templating? It might be nice to include various template variables just to see what values they print out but I do not see a real need to support this behavior.

**Comment by evilaliv3** [comment]
The reason why this template requires to be subject to templating is because it includes the %NodeName% signature.

**Comment by NSkelsey** [comment]
Delete it! Close bug!

**Comment by evilaliv3** [comment]
I would like that all mails follows the same logic and are subject to templating.
With a previous refactoring i've already implemented the Node level for templating so it's a matter to complete this part.

Assigning this to me and i will close this soon.
