### ISSUE TITLE
The private message box does not enlarge vertically automatically when the user write multi-line

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1772]
The private message box does not enlarge vertically automatically when the user write multi-line.

The user have to enlarge it manually.

This ticket is to make the input box to automatically enlarge vertically without the user having to do it manually.

![img_8360](https://cloud.githubusercontent.com/assets/770363/18844195/92a87bca-841c-11e6-9927-dbe1820c55a5.JPG)

**Comment by evilaliv3** [comment]
Ticket duplicated: https://github.com/globaleaks/GlobaLeaks/issues/1081

look how beautiful it was the original!
