### ISSUE TITLE
can't setup the dev environment

### ISSUE THREAD

**Issue by humanitiesNerd** [globaleaks/GlobaLeaks#1783]
On Ubuntu 10.04 x86_64, running the provided script ( https://raw.githubusercontent.com/globaleaks/GlobaLeaks/devel/scripts/setup_development_environment.sh )

the compilation of python dependencies fails

`Searching for cryptography==0.8.2
Reading https://pypi.python.org/simple/cryptography/
Downloading https://pypi.python.org/packages/be/66/defdddf34c506047e02ba4ce4a2b3063352525f31433106547965515f6ca/cryptography-0.8.2.tar.gz#md5=7d33499e851300c194cbb0396de72462
Best match: cryptography 0.8.2
Processing cryptography-0.8.2.tar.gz
Writing /tmp/easy_install-daYJV5/cryptography-0.8.2/setup.cfg
Running cryptography-0.8.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-daYJV5/cryptography-0.8.2/egg-dist-tmp-6J63ZA

Installed /tmp/easy_install-daYJV5/cryptography-0.8.2/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg
no previously-included directories found matching 'docs/_build'
warning: no previously-included files matching '*' found under directory 'vectors'
src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:499:6: error: conflicting types for ‘BIO_new_mem_buf’
 BIO *BIO_new_mem_buf(void *, int);
      ^
In file included from /usr/include/openssl/asn1.h:65:0,
                 from src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_f3e4673fx399b1113.c:220:
/usr/include/openssl/bio.h:692:6: note: previous declaration of ‘BIO_new_mem_buf’ was here
 BIO *BIO_new_mem_buf(const void *buf, int len);
      ^
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

**Comment by NSkelsey** [comment]
Hi @humanitiesNerd thanks for checking out GL. 

The build script (along with the default install script) has targeted its dependencies at Ubuntu 14.04 (trusty).

Please let comment here if you have any problems using that platform.

**Comment by NSkelsey** [comment]
Also we have an [IRC channel ](https://kiwiirc.com/client/irc.oftc.net/?nick=gl-?#globaleaks) that is a decent place to get development setup advice!

(come hang out)
