### ISSUE TITLE
GlobaLeaks runned in development with wrong command line arguments can lead to a not closable process

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1784]
I just found that running GlobaLeaks with wrong command line arguments can lead to a not closable process.

This can be reproduced for example running the following command:
```./bin/globaleaks  -z evilaliv3 -nB```

The output will be the following
```bash
evilaliv3@remotehost:~/Devel/GlobaLeaks/backend$ ./bin/globaleaks  -z evilaliv3 -nB
Starting GlobaLeaks
Usage: globaleaks [options]

globaleaks: error: no such option: -B

^C^Z
[1]+  Stopped                 ./bin/globaleaks -z evilaliv3 -nB
```

As shown by the output, running the above command will lead to GlobaLeaks to not react to ^C with impossibility to close it.

**Comment by NSkelsey** [comment]
Annoyed the heck out of me as well. The parser should just bail out of the startup with incorrect commands.

**Comment by NSkelsey** [comment]
Cannot reproduce. It is likely a bug in the interaction of shell, ctrl+c, the python process.

```bash
> ./bin/globaleaks -z nick -nB
Starting GlobaLeaks
Usage: globaleaks [options]

globaleaks: error: no such option: -B
```

**Comment by evilaliv3** [comment]
For me the issue is that on that condition the process is stuck and does not automatically exit.

at least this should be solved.

**Comment by evilaliv3** [comment]
Fixed.
