### ISSUE TITLE
It is a bug ?

### ISSUE THREAD

**Issue by mttstt** [globaleaks/GlobaLeaks#1787]
GL version 2.64.5.

Thanks ?

**Comment by mttstt** [comment]
Here the picture:

![globaleaksbug](https://cloud.githubusercontent.com/assets/17787853/19230684/2acf9320-8ed6-11e6-870c-0d4d2e8b5f96.png)

**Comment by NSkelsey** [comment]
Yes @mttstt we addressed this issue in v2.64.6 –– the most recent release.

If you update and the problem persists please tell us.
