### ISSUE TITLE
Properly handle missing config L10N fields

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1788]
We are recieving exceptions that look like this:

```
GlobaLeaks version: 2.64.5

KeyError Mapping key not found.

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
    result = g.send(result)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/notification.py", line 148, in post
    subject = notif['admin_test_static_mail_title']

KeyError: 'admin_test_static_mail_title'

```

The issue is probably with a user set language that has been dropped from internationalization but persists in their settings as the chosen language for mailed out updates.

This results in an empty config_desc dictionary for the internationalized notification fields.

Will close when a test is written to reproduce the issue.

**Comment by evilaliv3** [comment]
Im going to pick up this ticket that is important important to fix the
autovie venete setup.

I will also get sure that the admin prevents the user disabling all
languages

**Comment by evilaliv3** [comment]
This has been affressed as by current release (2.65)

**Comment by evilaliv3** [comment]
The database constraints added and the migration scripts implemented for older versions solved the issue by not making it possible.
