### ISSUE TITLE
Enable use of Vagrant for easy testing/setup of globaleaks

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#179]
This Ticket is to integrate the Vagrant available at  https://github.com/lastknight/globaleaks_vagrant into the main globaleaks repository.

The integration should:
- Integrate the Vagrant file into the Globaleaks repository
- Fix it (if there's some bug)
- Create a dedicated wiki page on how to setup Vagrant and Virtualbox (possibly with screenshots)
##

**Comment by evilaliv3** [comment]
The Vagrant script exists and the up to date version of it is in the https://github.com/globaleaks/GlobaLeaks/tree/testing/16.04 branch and will be (hopefully) soon merged.

**Comment by NSkelsey** [comment]
See pull #1827

**Comment by evilaliv3** [comment]
Closing as outdated by the current Docker script.
