### ISSUE TITLE
The interface for authenticated users should display a username

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1791]
Currently the login widget shows the user role, but a logged user cannot see with which user is logged.

Im suggesting the following changes:
1) show the name of the user for every user but the whistleblower in place of the role.
2) in the user preferences /#/preferences show the following information:
  Username: ... (when simplified login is enabled here there will be the user ID)
  Name: ...
  Role: ...

i'm confident for the change number 1), while not that sure of 2);
what do you think @NSkelsey, @fpietrosanti?

**Comment by fpietrosanti** [comment]
Facebook do that, so it make sense

**Comment by NSkelsey** [comment]
ACK ACK.

**Comment by NSkelsey** [comment]
### Final Interface
![schermata 2016-10-12 alle 1 47 25 pm](https://cloud.githubusercontent.com/assets/1095794/19308940/748d0698-9082-11e6-8837-2666478d86be.png)

Closing because I have spent too much time on this.

**Comment by evilaliv3** [comment]
Nick i've cleaned the interface a bit applying a bit of review.

- Sentences were missing colons.
- The directive for the role was to me a bit abuse for now (let's evaluate to have things like this in general in all the app but when more necessary than these situation)
- The logo was not enclosed inside an element making it's size respnsive and i've changed its visualization making it more uniform to how we handle the all application
I like the idea of this page but i think that few things were a bit redundant.
A directive for the role is

**Comment by evilaliv3** [comment]
here the screenshoot that show also the finalization of the user login widget.

![screenshot from 2016-10-15 23-42-34](https://cloud.githubusercontent.com/assets/217034/19413593/14869fe0-9332-11e6-8609-4bc82d02c533.png)

**Comment by evilaliv3** [comment]
I've changed the title of the ticket that was wrong with respect of what i specified.
@NSkelsey in place of the username (that is quite always the user.id in every setup), the valauble thing to show on the login widget is the name of the user.

**Comment by NSkelsey** [comment]
ACK, agree totally.
