### ISSUE TITLE
The CAPTCHA is not working

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1793]
With enable CAPTCHA set to true; the submission interface does not display a challenge and submissions can be created without providing a solution for their attached token.

There are two problems here.

1) This grep shows the captcha interface is no longer attached to the UI:

```bash
nskelsey @ Trisong ~/projects/GlobaLeaks/client devel
> grep -nr captcha app/views
app/views/admin/advanced/tab1.html:166:        <input data-ng-model="admin.node.enable_captcha" type="checkbox" />
app/views/partials/captchas.html:5:  <div id="HumanCaptcha" data-ng-if="arg.submission._token.human_captcha">
app/views/partials/captchas.html:11:        <span>{{arg.submission._token.human_captcha}}</span>
app/views/partials/captchas.html:16:          <input id="human_captcha_answer" class="form-control" data-ng-model="arg.submission._token.human_captcha_answer" type="number" autocomplete="off" />
```

2) ~~The `token.validty_check` function only checks if the submitted value lives within a valid timespan in `globaleaks/utils/token.py`.~~
The problem lies somewhere in [generate_token_challenges](def generate_token_challenge(self, challenges_dict = None):).

**Comment by NSkelsey** [comment]
The Alarm stress levels must be triggered before the Captcha is triggered.

**Comment by evilaliv3** [comment]
@NSkelsey has this been investigated?

**Comment by NSkelsey** [comment]
Yes, the bug was in my understanding. The Captcha is only displayed when the number of events trigger an alarm.
