### ISSUE TITLE
TorBrowser download link not working

### ISSUE THREAD

**Issue by Taipo** [globaleaks/GlobaLeaks#1794]
When the Privacy Panel is enabled, the download link appears to be  
```
{{node.tb_download_link
```

I assume the missing closed braces are the cause.

```
<a href="{{node.tb_download_link" target="_blank" rel="noreferrer">
```

**Comment by evilaliv3** [comment]
thanks @Taipo ! i just pushed the fix one minute before you, but i've removed my patch preferring merging your contribution :)

**Comment by Taipo** [comment]
Thanks

**Comment by evilaliv3** [comment]
Will be shipped in next release by today or tomorrow.

**Comment by NSkelsey** [comment]
Good catch, thank you for reporting it!
Il 20 ott 2016 9:51 PM, "Te Taipo" <notifications@github.com> ha scritto:
