### ISSUE TITLE
Globaleaks doesn't work well on Mobile Browser

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#180]
The current web interface of globaleaks doesn't visualize well on a mobile browser.
It has been tested on:
- Android with Chrome
- iOS with Safari

In both situation the interface doesn't scale well and minor error are reported.

This ticket is about making a dedicated quality assurance session for mobile browsers and fixing all the UI issues.
##

**Comment by evilaliv3** [comment]
Closing this ticket as definitely too generic on the topic.

A lot of improvements have been done on mobile and the application is almost entirely implemented to be responsive.
