### ISSUE TITLE
Let Recipients upload files for individual submissions

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1802]
Creating this ticket to log the request (low priority).

The idea is that the commenting and message interface could be supplemented with an extra file upload section for recipients to deliver files to Whistleblowers. I think better support for links or usage of external services is a better option. 

This sort of feature represents a significant refactor and it opens the possibility that a malicious receiver could use a specially crafted file to deanonymize a whistleblower.

Other than the security concerns, this could possibly enrich the UX. . . . . !

/cc @fpietrosanti @evilaliv3

**Comment by evilaliv3** [comment]
@NSkelsey why the BustiaEtica label has been renamed MH96DX? @vodkina was just asking

**Comment by evilaliv3** [comment]
This ticket was actually a duplication of the ticket https://github.com/globaleaks/GlobaLeaks/issues/1473 that was opened working with transparency on alac in 2014!

the feature is now in place thanks to the work of @NSkelsey!

\cc @fpietrosanti
