### ISSUE TITLE
Add updated translation file (Ukrainian language) during the next system update

### ISSUE THREAD

**Issue by IuliiSe** [globaleaks/GlobaLeaks#1806]
Translation has been successfully updated via Transefex.com
Please, add the updated file (Ukrainian language) during the next system update.

https://www.transifex.com/otf/globaleaks/translate/#uk/master/38908599

**Comment by evilaliv3** [comment]
sure! in general translations are always pulled in before a new release.

i will probably issue a new one tomorrow. is it ok?

**Comment by evilaliv3** [comment]
@IuliiSe: the up to date translation for the ukrainian has been added to release 2.64.14.

:) thanks for your contribution!
