### ISSUE TITLE
Officially support Ubuntu 16.04 LTS Xenial Xerus

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1809]
This is a ticket to track requirements going into a PR for official support of 16.04.
The branch currently used is `testing/appliance-infra`

- [x] python package dependencies selected and frozen.

Plan to deploy using the 16.04 packages in Ubuntu's archives instead of using pip to handle the requirements at install time.

- [x] backend pip selection requirements relaxed
- [x] single command installation with `install-globaleaks.sh`
- [x] Review the debian package [upgrade guide](https://www.debian.org/doc/debian-policy/upgrading-checklist.html) and update accordingly
- [x] testing of installation on OS
- [x] debian package release and listed on deb.globaleaks.org

It is not clear exactly how to test 16.04 with current infrastructure. A packer build system could be set up in a private cloud to automate and test the build. Or more likely we will use local VMs until it becomes a blocking issue.

**Comment by NSkelsey** [comment]
I believe with the non Xenial builds we may be violating a rule of the policy-checklist for upgrade to policy version `3.7.9`:

[For upgrade `3.7.9.0`](https://www.debian.org/doc/debian-policy/upgrading-checklist.html)
> Section 4.9:
> debian/rules: required targets must not attempt network access.

The older installation does not obey this rule since the package issues a pip request in the postinst step.

**Comment by evilaliv3** [comment]
The packaging is accomplished, what is missing is final retesting and release that i will try to accomplish by the next week.

**Comment by evilaliv3** [comment]
Support for Xenial is released and published on the repository.

Websites and wiki pages have been updated as well.
