### ISSUE TITLE
Exported tip's data.txt does not render well in MS-Land

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1820]
The default tip export template does not use `\r\n` anywhere and programs like notepad and wordpad (using default settings) end up with everything on one line. Additionally the utf-8 encoding is not detected and the languages which deviate from ASCII get clobbered.

I propose we just reccomend other programs. Like msword . . . msword works. . . . . ;-[

Updating the template to add carriage returns is only a partial solution, because the whole file needs to have including the variables that are included. I am super uninterested in doing a string replace. 

At this point this issue documents is only to say __all characters output are UTF-8__ forever.

**Comment by NSkelsey** [comment]
Wont fix. cc/ @evilaliv3

**Comment by fpietrosanti** [comment]
Well, this mean that the functionality of export is broken and that's a bug: "Tip export  does not work on windows". 

That's a common bug of software being developed and tested on *nix. 
It's not just quick to remove the readline dynamically? Notepad can render UTF8, maybe it's a problem on the original templates and the way we created?

**Comment by evilaliv3** [comment]
Nick: Let look at this together on monday doing some tests

**Comment by NSkelsey** [comment]
Wrote the function `msdos_encode` and the unittest for its usage. 

@evilaliv3 Okay, we don't have good coverage of the test_export handler, due to not reading the `ZipStream`. TTYL

@fpietrosanti I think the guessed encoding when they opened up the UTF-8 files was wrong and they saw glyphs. Will take a look with a windows VM.

**Comment by evilaliv3** [comment]
@NSkelsey what do you think about msdos encode?

in my opinion our solution should'nt be platform dependent; we should simply working on improving the current solution and eventually if no solution is present select a different file format (xml)/(pdf) readable well buy each operation system with a tool available  in all the operating systems with no additional download.

**Comment by evilaliv3** [comment]
Nick: Looking well at it i think yes your solutions may work as most of the
editors Support All except notepad:
https://en.m.wikipedia.org/wiki/Comparison_of_text_editors#Newline_support

For now we can have this fix and in the future adopt pdf as more
professional solution in general
