### ISSUE TITLE
Force unique filename constraint on wbfiles in the database schema

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1821]
Currently the enforcement of filename uniqueness for wbfile uploaded by recipients is done in python.

To perform the enforcement with the database requires the addition of a many-to-many table that expresses the relationship.

In python the code looks roughly like this:
```python
wbfile_names = store.find(WhistleblowerFile, WhistleblowerFile.recievertip_id == ReceiverTip.receivertip_id, 
                                              InternalTip.id == rtip.itip)                                                                 
if new_name in wfile_names:
     return errors.FailedSanityCheck()
```

The sql instead looks like this:

```sql
CREATE TABLE wbfile_itip_ref (                                                                           
    whistleblowerfile_id,
    internaltip_id,                                                                                      
    name TEXT NOT NULL, 
    PRIMARY KEY (name, internaltip_id),                                                                  
    UNIQUE(whistleblowerfile_id),                                                                        
    FOREIGN KEY (whistleblowerfile_id) REFERENCES whistleblowerfile(id) ON DELETE CASCADE,               
    FOREIGN KEY (internaltip_id) REFERENCES internaltip(id) ON DELETE CASCADE                
);  
```

This is blocked until another migration can be prepared. And when @evilaliv3 thinks it is a good idea. Hint (it is a good idea)

**Comment by evilaliv3** [comment]
Ok for this @NSkelsey!

Lets consider this in the next migration.

The implementation does not require any new many to many reference; why are you proposing this?
If that was the case yes i would be against because it would be a painful sketchi table aside from KISS guidelines.

but it simply require an UNIQUE(name) added to the whistleblower table. so go for it:

this is the modified table:
```sql
CREATE TABLE whistleblowerfile (
    id TEXT NOT NULL,
    creation_date TEXT NOT NULL,
    content_type TEXT NOT NULL,
    receivertip_id TEXT NOT NULL,
    name TEXT NOT NULL,
    file_path TEXT,
    size INTEGER NOT NULL,
    downloads INTEGER NOT NULL,
    create_date TEXT,
    last_access TEXT,
    description TEXT,
    UNIQUE(name),
    UNIQUE(file_path),
    FOREIGN KEY (receivertip_id) REFERENCES receivertip(id) ON DELETE CASCADE,
    PRIMARY KEY (id)
);
```

**Comment by NSkelsey** [comment]
@evilaliv3 because adding a `UNIQUE` constraint like that would mean every file name across the whole system would be unique. Using `internaltip_id` and `name` instead enforces uniqueness across each tip. Obviously we can add an `internaltip_id` to the whistleblowerfile table, but if you want to use normalized sql adding this table many-to-many is how to do ti.

**Comment by evilaliv3** [comment]
ok lets go for adding the internaltip_id in order to keep the implementation small and more straight forward.

**Comment by NSkelsey** [comment]
More discussion suggests that a ONE to ONE reference from whistleblowerfiles to receivers is a better setup, to prevent the delete cascade while maintaining the references relationship across existing users without removing the files when a user gets deleted.

```sql
CREATE TABLE wbfile_usertip_ref (
    whistleblowerfile_id,
    receiver_id, 
    PRIMARY KEY (whistleblowerfile_id),                                                                  
    UNIQUE(whistleblowerfile_id, receiver_id),                                                                        
    FOREIGN KEY (whistleblowerfile_id) REFERENCES whistleblowerfile(id),               
    FOREIGN KEY (receiver_id) REFERENCES receiver(id),
); 
```

**Comment by evilaliv3** [comment]
Closing as outdated.
