### ISSUE TITLE
Retest migration from GlobaLeaks version 2.60.127 to latest db version

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1822]
This ticket is to keep track of the activities related to the retesting of the migration from the db version of 2.60.127 to the current release.

I'm annotating here the procedure i would consider valuable; lets see if that help arriving ready for the adopter migration in a painless way.

Suggested path involves:
- creating a development environment version 2.60.127
- rebuild the client of that version
- run it
- start reproducing the adopter setup from the main details available looking at the node from the external point;
- performing 2 submissions, filling the questionnarie and uploading some files.
- performing the migration to the latest version
- pray
- evaluate if all was correct.
- iterate on the possible bugfixing

Expected timing for a good activity by experience: max 2 hours if things go well, ~5hours if things go wrong with proper patch ready to go.

Valuable bits for reproducing the instance:
- 1 recipient if the node has one recipient, 2 recipients if the node has more recipient
- 1 or 2 context depending if the node has 1 or more context
- pgp keys reproducing presence, absence, mixed scenario based on the user case.
- analysis of the /node configuration reproducing the aspects that impact on the submissions.

**Comment by evilaliv3** [comment]
@NSkelsey: just as a test case try to follow this path; enrich the procedure with the feedback from doing this activity; don't forget chocolate and beers!

**Comment by NSkelsey** [comment]
Questo e' andato bene.
