### ISSUE TITLE
Prevent export and enforce usage of the Pseudonym

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1823]
An adopter has started using the pseudonym and noticed that it is not used uniformly or everywhere across the interfaces exposed to Whistleblowers and the public. Additionally, the author field is exported in the JSON so the field effectively does not work.

This is a bug we must fix if we are going to support this feature. It is not okay for this bug to exist.

**Comment by evilaliv3** [comment]
Agreed! proceed with that. For now just fix the serialization.

What we can plan, as design in general, is to to export in the API only the id of object and rely on the fact that others API will export the actual data (e.g. receivers inside /public). This way the queries will be less impacting on the performance and the security of what is exported will be more strict.

soundas like a good plan @NSkelsey ?

**Comment by evilaliv3** [comment]
This has been budfixed and has been solved. Further improvement would be the one described above but the ticket can be considered addressed.
