### ISSUE TITLE
Submissions expiration should be subject to a tip summary

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1829]
An adopter made us notice that the submission expiration is sometime annoying.

I just analyzed the situation and identified possible issues on the following condition:
- suppose a node with ~10 recipients of the same team
- suppose they have an average of 100 living submissions
- suppose these recipients are enabled for postponing tip expiration and that they will usually postpone this at once and thus setting the same tip expiration time for theach tip.
when the expiration will happen will be spawned ReceiversCount * SubmissionsCount = 1000 mails at a time.

this still is related to the digest for email that we are thinking to implement to reduce emails over a configurable period, but for what relates specifically to these emails we could implement shortly a fix summarizing them per recipient.

**Comment by evilaliv3** [comment]
@marceloomens: would this ticket address the issue you were facing?

**Comment by marceloomens** [comment]
Hi @evilaliv3 it's certainly related. I will send an email to all Publeaks recipients later today to tell them about the notification suppression option on the tipsheet.

**Comment by NSkelsey** [comment]
Just noting outdated language

```Tip [%TipNum%] is going to expire in %ExpirationWatch% hours```

**Comment by evilaliv3** [comment]
I picked this up, will be shipped by means of budgixing small changes and then extended with other tickets.

**Comment by evilaliv3** [comment]
Patch implemented and integrated in devel branch.
