### ISSUE TITLE
Send all unhandled stack exception by default ALSO to website node administrator email

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1831]
This ticket is to send all unhandled stack exception by default ALSO to website node administrator email (if configured).

Actually we are receiving all unhandled stack exception but the website owners doesn't know if something is not working.

If the admin will receive the very same unhandled stack exception that we receive, will be stimoulated to upgrade the software to the latest version and/or to open up to us a support request.

**Comment by NSkelsey** [comment]
This is a great idea. The stack exception mails should be configurabile as
a list of addresses where the admins email is added at startup.

We could add the admins mail in the startup wizard by adding the addresses
provided to the list.

Tangentially related to #1830
Il 15 dic 2016 10:20 AM, "Fabio (naif) Pietrosanti" <
notifications@github.com> ha scritto:

**Comment by NSkelsey** [comment]
I started the implementation of this feature @evilaliv3. Two decisions were made that could go differently:

1. Only one mail will be sent for each exception to all addresses in the list.
2. There will only be one key that will be used to encrypt the exception notifications as they go out.

The goal here is to keep the changes small and keep the exception logic straight forward. Along with the UI!


<img width="515" alt="schermata 2016-12-23 alle 6 20 05 pm" src="https://cloud.githubusercontent.com/assets/1095794/21463806/c919398c-c93c-11e6-9026-69b53caf5692.png">

**Comment by evilaliv3** [comment]
What about a boolean configuration in the admin users to mark if they will
have to receive the exceptions?

This way we can have a global setting with an enabler and a key + each
receiver with an enabler and it's key.

I would not go for a separated list/model just for this. What do you think?

**Comment by evilaliv3** [comment]
Actually i like a lot that you this time proposed a small fix, but was not my intent to guide to you this approach aalways when designing new features, but just for bugfixing :)

What i dislike instead of this minimal fix is the fact that the PGP key will be the same for everyone.
Probably what i would do it to have:
1) The notification to us using a POST HTTPS request to a server of us (subject to an enabler that the admin could be eventually disable in the same way like one do for anonymous statistics in Chrome or other softwares)
2) Notification to the admin that will use naturally their key.

2) will be anyhow be necessary for implementing Capabilities for Admin/Custodians

@fpietrosanti ?

**Comment by fpietrosanti** [comment]
This ticket is about implementing a 60 minutes fix, that's sending exception email by default also to configured admin email. 
Let's try to minimalistically make a fix and then open up feature improvement for the future.

**Comment by evilaliv3** [comment]
Thank you fabio for the feedback.

Yep so @NSkelsey as plan lets do the following:
- simply a for as we initially discussed (this way naturally admins will receive the email in PGP if they will have PGP configured); the feautre should be implemented without any database edit nor migration but just a for loop in place of the current sendmail function.
- the configuration (client/backend) will follow on a later stage, with long term design and using the User models.

fine for you?

**Comment by NSkelsey** [comment]
That works for me.

The mails will go out to the admins plus this optionally configurabile
globaleaks-stackexception@...

We will oppurtunisticly perform the encryption and skip failures.

There isnt much of a point of using PGP if the default stackexception
address is used.

In the future the default mail address could be encrypted by default and it
all will be togglable.

When that happens we will all have a great Christmas.
Il 24 dic 2016 7:29 AM, "Giovanni Pellerano" <notifications@github.com> ha
scritto:

**Comment by fpietrosanti** [comment]
> The mails will go out to the admins plus this optionally configurabile
> globaleaks-stackexception@...

Yes, but by default should  go to both

**Comment by evilaliv3** [comment]
Yes, lets postpone for now also the configuration that make it possible to disable it and implement it with #1848 when as planned we will replace the SMTP anonymous exception notification by means of HTTPS POSTs.

**Comment by evilaliv3** [comment]
Ah, just noticed that @fpietrosanti already opened the ticket #1844 for the same reason i just drafted today in 1848

**Comment by NSkelsey** [comment]
Merged into devel.
