### ISSUE TITLE
Tor is now resetting tor hidden service file permissions to debian-tor users

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1847]
Current releases of Tor perform reset of tor hidden service permissions to the following:
```bash
root@demo:/var/globaleaks/torhs# ls -al
total 16
drwx------ 2 debian-tor debian-tor 4096 Dec 26 20:15 .
drwxr-x--- 6 globaleaks debian-tor 4096 Dec 26 20:06 ..
-rw------- 1 debian-tor debian-tor   23 Dec 26 20:15 hostname
-rw-rw---- 1 debian-tor debian-tor  887 Dec  7 17:20 private_key
```

This causes impossibility for GlobaLeaks to read the tor hidden service name for display to the user.

**Comment by evilaliv3** [comment]
The ticket is a duplicate of https://github.com/globaleaks/GlobaLeaks/issues/1328

**Comment by fpietrosanti** [comment]
We could be able to quickly workaround it by adding the user globaleaks to the debian-tor group

**Comment by evilaliv3** [comment]
Actually this is the more simple fix with limited security impact and no functional issues.

Going to test and integrate it.

**Comment by evilaliv3** [comment]
In the real no particular need for the fix exists.

GlobaLeaks never access this file after the initialization where the initialization happenso with root priviledges.

For this reason acting as root at startup GlobaLeaks has no problem in reading the file. Closing the ticket that will be properly and completely addressed when integrating Txtorcon and ephemeral tor onion services.

**Comment by fpietrosanti** [comment]
This problem happened again on https://forum.globaleaks.org/t/after-upgrade-from-14-04-to-16-04-onion-site-doesnt-work/97/6

**Comment by kyrylkov** [comment]
Yes, seems to be the reason why we cannot get it up and running after the upgrade.
