### ISSUE TITLE
Re-implement default software exception notifications by means of HTTPS

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1848]
In relation to https://github.com/globaleaks/GlobaLeaks/issues/1831 and https://github.com/globaleaks/GlobaLeaks/issues/1830 default software exceptions should be implemented by means of an HTTPS POST.

This would offer the following improvements:
- notifications could be encrypted without hardcoding a key in the software
- the encryption keys could change during time

implementing this via HTTPS the exceptions could also notify the failures about SMTP that being a configurable aspect of the platform is subject to more user misconfiguration than what HTTPS is subject to being the minimal automatic prerequisite of the software functioning.

**Comment by fpietrosanti** [comment]
That's not for the admin, that only have an email account available to be notified, but for globaleaks team handling the development as the software product manufacturer. 

As a software product manufacturer that need to handle in a structured way errors coming from production software, it's worth implementing an application error management platform such as the ones documented on #1844 where almost all platform have HTTPS transport (but using their own data format)

**Comment by evilaliv3** [comment]
Ah we are totally in sync. I've not noticed you opened this ticket just few hours ago.

Closing this one as duplicated.
