### ISSUE TITLE
Whistleblower Identity Management Feature

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#185]
This ticket is to introduce in GlobaLeaks the management of the Whistleblower Identity by making it a structured and "information element" of the software, that can have it's properties and influence behaviors of the client.

The Identity Information can be represented as a special FieldType that can be added in the Step of a Context. 

The Whistleblower identity, as being managed by #1337 for use by a Custodian, it's an independent information entity that shall be entirely configurable and customizable from the web admin interface.

The Whistleblower identity shall be graphically represented in a way that's self-contained and not just mixed within the submission field, with it's structure.

The TipList shall enable looking if the Whistleblower identity has been disclosed or not.

From the admin interface, in the context it shall be possible to "Enable Whistleblower Identity Management", in order to enable the FieldType to be available to be added.

When enabling "Whistleblower Identity Management" the following options will be presented for configuration and customization:
  * Whistleblower Identity Fields: view/enable/disable/change each default whistleblower identity field
  * Additional Whistleblower Identity Fields: add new Whistleblower identity field
  * Title text: Title of the box asking the Whistleblower Identity (by default "Identity Information")
  * Prefix text: The text to be displayed/customized as an introduction before asking for the identity information
  * Whistleblower Identity Question Text: Ability to customize the text when asking for the whistleblower identity (By default "Do you want to tell you who you are?")
  * Whistleblower Identity Question Default: Yes/No/Unselected (If Question is Enabled enable to configure the question default settings in the Whistleblower submission workflow)
 * Alert Disclaimer for "Yes" answer: If enabled, customize the text and two options button text to confirm/cancel selection of Yes, to be displayed when the whistleblower choose "Yes"
 * Alert Disclaimer for "No" answer: If enabled, customize the text and two options button to confirm/cancel selection of No, to be displayed when the whistleblower choose "No"
 * Enable Authorization to access identity information: Yes/No (Enable encrypting the information for custodian authorization)
 * If enabled, provide a list of users with Custodian "role" to choose to be used for #1337 feature

That way the administrator can consciously and finely configure the ability to ask for identity information, adapting to the different use-cases of globaleaks .

Here the collection of screenshots of various commercial whistleblowing tools:
https://docs.google.com/document/d/1NFHW1OpfLTYskbTCA8lgJZDePUYD75QaZP7xTiNshhk/edit

TODO: Provide default structure of information for default "Identity Information"

**Comment by evilaliv3** [comment]
Question: right now every thing that is related to tips, is deleted when tips expiry in an automagical manner (there is a db ON DELETE CASCADE that delete using references).

in relation to identities:
1) is an identity associated to a single tip or not? (maybe that i receive 2 tips and i decide as receiver to trash one identity and do the link to an existent one?)
2) is an identity deleted when no associated tips exists

this two questions are important to define the db structure that will permit the feature in a flexible way.

**Comment by fpietrosanti** [comment]
1) No, each identity is single at Tip level.
Btw we may consider in future to provide to the Receiver some analytics capabilities, with a browser of all "Persons Involved" among all Tips, giving a way to manually link/reconcile different "Person Involved" objects (across different tips) to indicate that they are "the same person". That would enable to spot/identify persons that are involved in multiple submissions. But it sounds to me like a mid-term, advanced analytics goal, not to be considered now at DB-level

2) Yes, because it shall be part of a Tip

**Comment by evilaliv3** [comment]
@fpietrosanti currently the fields identified with A.N.A.C are:
- name
- surname
- date of birth
- place of birth
- fiscal code
- residence / home
  - street name
  - street address
  - street number
  - zip code
  - region
  - country
  - phone number
  - identity
  - phone number
  - email address

this are somehow general but not properly given the different world practices
- in english forms generally ask also for the mid name
- some fields are not the translation of the other: 
- in big cities (foreign countires with respect to italy) you ask also for the apartment
- country is not the translation of stato; we should really start caring of communicateing translate the context of the translation and all should be aware the we try to generalize to not have set of different questions for different countries as much as we can.

an other doubt i've is:
ok we want to add a default field, but we should find a balance over the questionnaire so that it does not end in asking for too much.
  
for example anac want to put:
1. Qualifica di servizio attuale
2. Incarico (Ruolo) di servizio attuale
3. Unità organizzativa e sede di servizio attuale
4. Qualifica di servizio all'epoca del fatto segnalato
5. Incarico (Ruolo) all'epoca del fatto segnalato
6. Unità organizzativa e sede di servizio all'epoca del fatto segnalato

i'm thinking that this all along with all the questions above are too much for a default whistleblower identity field. what should we put for now in OUR default?

**Comment by evilaliv3** [comment]
@fpietrosanti: here follows the fields as currently defined, properly studied for internationalization

Can you please review them before i send them to AO?

- Name
- Surname
- Sex
- Male
- Female
- Date of birth
- Place of birth
- Fiscal Code
- Place of residence / Domicile
 - Street address
 - House number
 - Zip code
 - City
 - Province
 - State
- Phone number
- Email address
- Present job title
- Present job responsibility (role)
- Present organization unit and job location
- Past job title at the time of the fact reported
- Past job responsibility (role) at the time of the fact reported
- Past organization unit and job location at the time of the fact reported

**Comment by vecna** [comment]
you are gonna to take so much criticism having only two sex supported :P

**Comment by evilaliv3** [comment]
i agree completely @vecna and was already taking care of this.

the real issue (now solved, read below) is technical handling the translation with transifex as i've already discusses somewhere.

let me clarify the issue an below is the solution
 1. transifex accept only a translation for the same word.
 2. supposing i will push "Other" that in english is correct the should be only one translation of "Other" in all the app. but for sure the Other in relation to Gender in some languages should be translated with a specific word and not doing it will result hilarious.

by the way recently i've i will puth on transifex GENDER_OTHER and a comment: please translate as the world for Other in a sex selector  Male, Female, Other and then i will handle it as good script kiddie.

**Comment by evilaliv3** [comment]
@vecna and anyway it was correct Male/Female asking for the Sex that is the biological diversity.
But ok to ask for Gender and put Male, Female, Other.

**Comment by evilaliv3** [comment]
Implemented and ready to be shipped in 2.60.114!
