### ISSUE TITLE
Implement configuration section for HTTPS Certificates

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1852]
This ticket is to implement a configuration panel for HTTPS certificates.

The admin interface should satisfy the following specs:
- Implement a file upload for 3 different files: Key file, Intermadiate Chain File, Certificate
- each of the file upload should have a Title (e.g. "Certificate Key File:") and a file upload button (e.g. "Load").
- when the file has not been uploaded the interface should visibly clarify that the file is not there (with colors or icons).
- when the file has been uploaded the interface should visibly clarify that the file has been loaded and communicate that the file could be deleted or replaced (with colors or icons).
- files should be stored as a db entry.
- no validation should be performed, the whole validation will be afterwards implemented integrating the underlying HTTPS component.

This work is preliminary for the integration of HTTPS inside GlobaLeaks.

As first step would be good to:
  - implement first a mockup
  - finalize the strings and push them on transifex
  - implement the database support
  - proceed with the implementation

Let's avoid for this first implementation drag drop or visualization of the file postponing it all to an eventual future improvement.

**Comment by fpietrosanti** [comment]
Notes
1. We may need to consider also to "export" those files.
2. We may need also to consider that a certificate should be bound to an hostname and that a globaleaks system could in future support multiple hostnames (like multi-tenancy or multiple entry-points from intranet and internet to a whistleblowing system), so in the DB we may to specify the uploaded certificate to which hostname it's bound to (considering that a single certificate could have multiple hostname in it's CN field)

**Comment by evilaliv3** [comment]
@fpietrosanti ok for the first one but if you agree lets skip 2.

That is completely doable afterwords and is currently overengineering. Multitenancy is a separated big deliverable that will require whole study so please do not mix things.

**Comment by evilaliv3** [comment]
in addition in general common platforms (e.g. plesk) separate the hostname configuration to the certificate configuration, so eventually we have only to consider to give a name to the certificate configuration (key+certificate+intermediate) and then in the host configuration one will associate host configurations with ssl certificates. 

repeating the example of Plesk in the host configuration one has a selector that says: "which certificate among the one available you want to use for this host?"

but this all is a different evolution that will come afterwards; this ticket deals simply with implementing a minimal support for configuration of only the following three entries:
- key
- cert
-intermediate

as direction that i would like to be followed these entries shouldnt validated at allnor associated to a name that by default will be the name of the only hostname configured in the platform.

**Comment by fpietrosanti** [comment]
Sure, make sense, let's keep it simple!

**Comment by NSkelsey** [comment]
Made a bit of progress on this today.

The handlers for pushing the files into `working_dir/files/ssl` are about %50 finished because I ended up writing the files to disk. Sorry @evilaliv3 for whatever reason, a few hours ago I read `files should not be stored as a db entry`

Validating the types of these files as they are uploaded will be interesting. I hope we can trust to the cryptography package to handle untrusted input. The certificates are coming in as `ASN.1` which means we need a sturdy parser.

The UI right now could replace the green upload with a "replace" or just allow only the delete:
![https-conf](https://cloud.githubusercontent.com/assets/1095794/21746616/69acfd6a-d54b-11e6-9f56-5ae27c2542e0.png)

**Comment by evilaliv3** [comment]
Perfect.

here some ideas:
- for sure the direction is to have all the files to the database, for now just move them inside node configuration.
- maybe we can skip the file upload (flowjs), just manage the file reading on the client and save using a JSON POST?
- we should then elaborate better on the simplification of the interface. i do not like that much that we have to say that 3 files are needed where in some situations only 2 are necessary. we should instead mark visibly as missing the key and the certificate and leave optional the certificate load.
- we could in addition add a HTTP Service: Active/Inactive to notify if the service is on or of and eventually giving a clickable link?

@fpietrosanti could you please add your feedback?

**Comment by evilaliv3** [comment]
@NSkelsey about the button Upload/Replace yes i'm also for the choice of having just a but at a time. Upload / Delete. Visibly it should be communuicated that the certificate is there.

maybe with something like:
Status: missing. [Upload]
Status: loaded. [Remove]

interfaces like plesk in addition make upload / remove the files all at once (key+certificate+intermediate(optional)); this kind of interface should be also investigated.

**Comment by evilaliv3** [comment]
@NSkelsey, thinking to our last discussions would be great if you can move forward this interface with the following changes:

- add a top interface Status: [ON/OFF]; the interface should be OFF/gray out when the configuration is incomplete, should be OFF when OFF, should allow swtich to ON only when fully configured
- the switch could be already be mocked as following: 1) show a modal with a failure message on fail (that in the future will be extended with reason of the failure. 2) show a success message on success offering a link to the login page via HTTPS.

if you could proceed with this would be great!
Then probably we will have to move the whole setting out of the advanced settings, mayve in an "Host Configuration" or "Network Settings" panel. \cc @fpietrosanti

**Comment by NSkelsey** [comment]
CSR generation modal:

![csr_config](https://cloud.githubusercontent.com/assets/1095794/22338141/e6e1c6c2-e3e6-11e6-8981-3ddd74554e7a.png)

**Comment by NSkelsey** [comment]
Ready for release.
