### ISSUE TITLE
Adjust main page of GlobaLeaks Web-Admin interface with new contact information

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1857]
Following the implementation of #1856 related to Contact Flow (https://docs.google.com/document/d/1KPkj2AHq9T31mtdwDcdpJHn1Nnv1v1GfT8f53-i2d_U/edit ) re-organization, this ticket is to re-write the main page of GlobaLeaks web-admin interface by:
- introducing new contact flow
- better professionalizing the text ( including specifying the support provided by WBS)

**Comment by NSkelsey** [comment]
I believe all relevant points mentioned in that document are now displayed on the home page of the admin interface. @fpietrosanti can you please verify this is the case?

### /admin/landing
![about](https://cloud.githubusercontent.com/assets/1095794/25908463/90a875ba-35aa-11e7-8643-01712ce7884e.png)

**Comment by fpietrosanti** [comment]
No, the landing page should be reviewed only by using contacts from #1856 and shall also contain "better professionalizing the text ( including specifying the support provided by WBS)" .

It means removing mentions to NSA, removing mentions to hermescenter emails, writing the availability of professional service support by WBS

**Comment by NSkelsey** [comment]
@fpietrosanti the [readme](https://github.com/globaleaks/GlobaLeaks/blob/master/README.md#community-and-professional-support) on the project contains almost exactly this language and structure.

The line missing is:
```
For professional support and development of anti corruption and
compliance projects contact Whistleblowing Solutions, the social enterprise maintaining GlobaLeaks, fill out this [form](contact).
```

The next commit will add this content into the interface and bring it under internationalization.

**Comment by NSkelsey** [comment]
Instead of a WBS contact form I will just include a mailto link for info@whistleblowingsolutions.it

**Comment by NSkelsey** [comment]
`
For professional support and development of anti corruption and
compliance projects contact Whistleblowing Solutions, the social enterprise maintaining GlobaLeaks, through [email](info@whistleblowingsolutions.it).
`

**Comment by NSkelsey** [comment]
Okay here is the latest as of 59999ba. @fpietrosanti feel free to reopen if it does not pass inspection.

![about-v2](https://cloud.githubusercontent.com/assets/1095794/25915963/6753aab8-35c3-11e7-958c-8d28e91e5529.png)
