### ISSUE TITLE
Adjust GlobaLeaks Irc channel topic

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1861]
Following #1856 adjust the IRC Channel #globaleaks with information that are relevant to drive users to the right contact information:
Actually is "current topic is: GlobaLeaks, OpenSource Whistleblowing platform was online in ~2012, now what? - http://demo.globaleaks.org/ - http://github.com/globaleaks/GlobaLeaks -  http://globaleaks.org - http://leakdirectory.org "

We shall rework it in a way to drive contact to Website, Forum, Github

**Comment by vodkina** [comment]
<img width="1246" alt="screenshot 2017-01-30 14 40 11" src="https://cloud.githubusercontent.com/assets/2151323/22425179/29768804-e6fa-11e6-82ec-c0d209ef6832.png">
