### ISSUE TITLE
Adjust GlobaLeaks Forum main page

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1862]
Following #1856 this ticket is to adjust http://forum.globaleaks.org/ main page to contain all the relevant contact information (driving development on github, professional contact to wbs, community to forum, chat on irc)

**Comment by vodkina** [comment]
<img width="1278" alt="screenshot 2017-02-12 12 10 02" src="https://cloud.githubusercontent.com/assets/2151323/22861567/47c4a9e0-f11c-11e6-994a-ba1f5a323610.png">

**Comment by fpietrosanti** [comment]
I'd suggest to point all Professional Support and Non-Profit support and Media to https://www.globaleaks.org/contact/ as the only web contact point.

Then implementing #1864 we'll dispatch communications to the right point

**Comment by vodkina** [comment]
Implemented, as suggested by @fpietrosanti
