### ISSUE TITLE
Adjust Github Issue template with relevant structure and contact information

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1863]
Following implementation of #1856 this ticket is to create a github issue template that contain the relevant information on how to open-up a ticket, but also drive the user to the right contact channel (development on github, professional contact to wbs, community support to forum, chat on irc)

**Comment by vodkina** [comment]
Can we close this issue?

**Comment by evilaliv3** [comment]
Fine from my side, it is in place and also improving the quality of what we get.

Improvements will be done with day by day expirience (e.g. i'm going to add the question vor the operating system and its version that would have helped in quite all the recent tickets)
