### ISSUE TITLE
Setup CloudFlare (Project Galileo) on relevant domains

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1869]
This ticket is to keep track of the setup CloudFlare protections (Project Galileo) on the relevant domains:
- https://www.globaleaks.org
- https://www.hermescenter.org
- https://www.whistleblowingsolutions.it

**Comment by evilaliv3** [comment]
@fpietrosanti got an internal contact via the OTF community.

Following the guidelines for the CNAME setuphttps://support.cloudflare.com/hc/en-us/articles/200168706-How-do-I-do-CNAME-setup- i've created a cloudflare account adding all the above domains and ive issues a support request.

I'm now waiting for the answer.

**Comment by NSkelsey** [comment]
I believe this is now closeable.
