### ISSUE TITLE
Make it possible to create the HTTPS key and the CSR via the web interface

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1870]
Following the implementation of the HTTPS Configuration it will then valuable to implement Key generation via the web interface.

This ticket is to collect the ideas about this integration first analyzing if it is worth doing it, then eventually discussing the UI and estimating the implementation time.

All that needed would be eventually already available in the pyopenssl implementation that we integrate since Ubuntu Precise (0.14): https://github.com/pyca/pyopenssl/blob/0.14/examples/certgen.py

Minimal desiderata would be to automate the generation of the CSR by using the following parameters:
- the hostname
- the 2048 bits (should be probably enouugh)

All other data could be probably automatically generated/left empy or just left as advanced possible setting?

**Comment by fpietrosanti** [comment]
I'd suggestion that we need to ask the certificate parameters with the same data asked by OpenSSL certificate generation (that's what commercial CA provider usually ask?)

**Comment by evilaliv3** [comment]
Here what CPANEL implement, maybe we can implement the same simplifications:

![image](https://cloud.githubusercontent.com/assets/217034/21862180/5a47eaa2-d838-11e6-87a7-743935549c3a.png)

**Comment by fpietrosanti** [comment]
laic

**Comment by NSkelsey** [comment]
Producing a useful CSR will require the domain to be configured and GL to be aware of it.

**Comment by fpietrosanti** [comment]
@NSkelsey Producing a CSR is an entirely offline process (see example https://it.godaddy.com/help/apache-generate-csr-certificate-signing-request-5269), but yes, when the certificate will be loaded to be used the HTTPS server must known it's hostname to answer properly.

**Comment by NSkelsey** [comment]
It can be generated both offline and via [the OpenSSL library](http://www.pyopenssl.org/en/latest/api/crypto.html?highlight=signing%20request#OpenSSL.crypto.X509Req) and we looking at doing it in the backend via a handler. There are a couple advantages:

1. No command line needed.
2. It lets the admin go to their preferred CA.
3. It prevents the transfer of the server key from client to server. 
4. It lets us choose the type ciphers/key sizes to be used in the setup.

So provided it doesn't destroy lots of time. We are planning on supporting the generation of the CSR in the platform.

**Comment by NSkelsey** [comment]
Current UI for the CSR step.

![csr-step-1](https://cloud.githubusercontent.com/assets/1095794/21901453/13e5a4d0-d8f8-11e6-995e-401725d701a7.png)

**Comment by NSkelsey** [comment]
### Current UI for the Certificate Upload:
![upload-certs](https://cloud.githubusercontent.com/assets/1095794/22215054/48136152-e19a-11e6-99ef-c9145478096a.png)

### Current UI for the HTTPS enabled status:
![https-status](https://cloud.githubusercontent.com/assets/1095794/22215058/4a4c43da-e19a-11e6-836e-3a52da832822.png)

### Current logs generated by subprocesses spawned via interface:
![tmuxd](https://cloud.githubusercontent.com/assets/1095794/22215064/527bcdfa-e19a-11e6-8a79-67753df9c7e0.png)

**Comment by NSkelsey** [comment]
@evilaliv3 @fpietrosanti

I am looking for useful summary information to display about a configured cert in the UI. Currently I have:

1. Enabled
2. Status message from the backend
3. Cert expiration date
4. anchor to the https enabled URL.

**Comment by vodkina** [comment]
estimated at 7, as agreed with @evilaliv3

**Comment by NSkelsey** [comment]
Ready for release. By default we use 2056 bit RSA keys and sign SHA 512 hashes.
