### ISSUE TITLE
torrc deprecation notices

### ISSUE THREAD

**Issue by filternetz** [globaleaks/GlobaLeaks#1874]
**Current behavior**
Upon starting Globaleaks with Tor I get:

<pre>
Jan 17 14:14:10.524 [warn] The SocksListenAddress option is deprecated, and will most likely be removed in a future version of Tor. Use SocksPort instead. (If you think this is a mistake, please let us know!)
Jan 17 14:14:10.524 [warn] The TransListenAddress option is deprecated, and will most likely be removed in a future version of Tor. Use TransPort instead. (If you think this is a mistake, please let us know!)
Jan 17 14:14:10.524 [warn] The DNSListenAddress option is deprecated, and will most likely be removed in a future version of Tor. Use DNSPort instead. (If you think this is a mistake, please let us know!)
</pre>

**Expected behavior**

Not getting this for a future release, or be notified somehow.

**Minimal reproduction of the problem with instructions**

Use current torrc generated by Globaleaks.

**What is the motivation / use case for changing the behavior?**
To be future proof

<pre>
# dpkg --list | grep globaleaks

hi  globaleaks                           2.65.8                              Opensource whistleblowing platform.

</pre>

**Comment by evilaliv3** [comment]
Thanks for the reporting @filternetz!

**Comment by evilaliv3** [comment]
@filternetz the issue report has been addressed.

Ive removed all the deprecated directives that we were injecting in globaleaks.
It appears that one (```SocksPort```) is not injected by GlobaLeaks and probably is added by an other software installed on the platform you were debugging on.

**Comment by evilaliv3** [comment]
thanks!
