### ISSUE TITLE
Expiry extension confirmation lists current datetime instead of future datetime

### ISSUE THREAD

**Issue by marceloomens** [globaleaks/GlobaLeaks#1878]
**Current behavior**
Tip expiry extension confirmation lists current datetime as new expiration datetime; this should be a datetime in the future.

**Expected behavior**
On the expiry extension confirmation box list the future expiration datetime

**Minimal reproduction of the problem with instructions**
![screenshot from 2017-01-23 11 05 02](https://cloud.githubusercontent.com/assets/634149/22203524/cd006248-e16d-11e6-850f-e319c1449043.png)

* **GlobaLeaks version:** 2.65.8

* **Browser:** all

**Comment by evilaliv3** [comment]
Fixed;

the formula calculating the time to be shown was still considering to have the tiptimetolive already generated in milliseconds while recent APIs returs a value in days.
