### ISSUE TITLE
Evaluate to make submissions expire with a date set on the 24:00 of the expiration day

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1879]
This ticket it so evaluate the simplification of generating/visualizing tip expirations with a date set on the starting of the day.

This would simplify the understanding by the users and would allow to have more compact interfaces communicating the time of the expiration removing the information related the hour and the seconds that is probably confusing.

**Comment by evilaliv3** [comment]
@marceloomens / @infosquatter would you please comment on this tickets if you would find this useful for your users?

\cc @NSkelsey @fpietrosanti

**Comment by infosquatter** [comment]
Yes, I think that is simpler. But I would recommend to close the tip in
the END of the day (11:59pm) - it is safer in case of any misunderstandings.

Giovanni Pellerano:
> @marceloomens / @infosquatter would you please comment on this tickets if you would find this useful for your users?
> 
> \cc @NSkelsey @fpietrosanti 
>

**Comment by marceloomens** [comment]
![smiley-signs064](https://cloud.githubusercontent.com/assets/634149/22205127/ba9da0d6-e175-11e6-952a-c73b1d4f7b45.gif)

**Comment by evilaliv3** [comment]
Implemented, will be shipped in next release.

By the current implementation the Tip will expire all a 00:00 UTC; 
There is still the requirement to show the full date with details of minutes and settings because the dates served by the served are in UTC to guarantee location anonymity of it; For this reason it is fundamental to show the user the minutes and settings of the deletion in the UTC reference.

The more simplification for the user so will be currently just not being confused buy not aligned hours like 01:45, 10:23 but all will be uniform ad 01:00 or 02:00 depending on the timezone of the recipient.
