### ISSUE TITLE
Newer versions of gnugpg do not support gpghome kwarg

### ISSUE THREAD

**Issue by combs** [globaleaks/GlobaLeaks#1885]
~                           

**Current behavior**

When saving a new PGP key for a user, it shows a red "Error" toast and then sends the following exception email:
```


GlobaLeaks version: 2.65.14

TypeError Inappropriate argument type.

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/user.py", line 277, in put
    response = yield admin_update_user(user_id, request, self.request.language)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python2.7/dist-packages/globaleaks/orm.py", line 102, in _wrap
    result = function(store, *args, **kwargs)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/user.py", line 155, in admin_update_user
    return user_serialize_user(db_admin_update_user(store, user_id, request, language), language)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/admin/user.py", line 145, in db_admin_update_user
    parse_pgp_options(user, request)

  File "/usr/lib/python2.7/dist-packages/globaleaks/handlers/user.py", line 32, in parse_pgp_options
    k = parse_pgp_key(pgp_key_public)

  File "/usr/lib/python2.7/dist-packages/globaleaks/security.py", line 441, in parse_pgp_key
    gnob = GLBPGP()

  File "/usr/lib/python2.7/dist-packages/globaleaks/security.py", line 361, in __init__
    self.gnupg = GPG(gnupghome=temp_pgproot, options=['--trust-model', 'always'])

TypeError: __init__() got an unexpected keyword argument 'gnupghome'

```

It looks like some versions of GnuPG python binding [expect argument as "homedir" instead of "gnupghome"](http://stackoverflow.com/questions/35028852/how-to-set-the-gnupg-home-directory-within-the-gnupg-python-binding)`. 

**Expected behavior**

PGP key is saved

**Minimal reproduction of the problem with instructions**

Edit a user in GL admin
Paste in pgp key
hit Save

**What is the motivation / use case for changing the behavior?**

Encryption ftw

* **GlobaLeaks version:** 2.X.Y

```
root@transfer:/var/globaleaks/log# globaleaks -v
GlobaLeaks Version: 2.65.14
GlobaLeaks DB version: 35
root@transfer:/var/globaleaks/log# python
Python 2.7.9 (default, Sep 17 2016, 20:26:04) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gnupg
>>> print gnupg.__version__
2.2.0
```

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Other (specify) ]

Tor Browser

**Comment by combs** [comment]
are Python modules `gnupg` and `python-gnupg` different? Which one do I need?

**Comment by NSkelsey** [comment]
@combs yes they are. gnupg provides the gpg tools package and python-gnupg provides a python module to interact with it. Why don't you join us on [IRC](https://webchat.oftc.net/?nick=gl-guest.&channels=globaleaks) and lets chat there.

Try something hacky like changing line 361 in globaleaks/security.py :
```
    self.gnupg = GPG(homedir=temp_pgproot, options=['--trust-model', 'always'])
```

to:

```
    self.gnupg = GPG(gnupghome=temp_pgproot, options=['--trust-model', 'always'])
```

and then restart GL with a `> sudo service globaleaks restart`

**Comment by combs** [comment]
Cool, thank you, I got it working with `pip uninstall gnupg` and `pip install python-gnupg`.
will join the irc if I run into anything else.

thanks!

**Comment by NSkelsey** [comment]
That is a much better solution.

**Comment by misophetamenos** [comment]
Hi everybody, 
When running the proposed by @combs , the problem has been solved, it was not necessary to modify the code.

Thank you!

**Comment by evilaliv3** [comment]
Thanks @misophetamenos;

@misophetamenos / @combs do you know why on your platforms it was installed the wrong dependency?
Maybe the node is not a Ubuntu or the server is not used just for GlobaLeaks?

**Comment by combs** [comment]
Yes, it was Raspbian. (Unsupported distribution.)

**Comment by misophetamenos** [comment]
In my case, the implementation I have done in Ubuntu 14.04, in the execution of the GL installation, I was requesting the python modules for their operation and as they appeared they were installing them.

I attached the list of everything that I had to execute to have it in operation.

*****************

Apt-get install apparmor
Apt-get install build-essential libssl-dev libffi-dev python-dev
Apt-get install python-pip
Apt-get install python-cryptography
Pip install --upgrade pip
Pip install -U pip setuptools
Pip install twisted
Pip install cyclone
Pip install storm
Pip install scrypt
Pip install python-gnupg
Pip install txsocksx
Pip install service_identity
Pip install pyOpenSSL
Apt-get install tor
***********************
