### ISSUE TITLE
Update trusty cryptography dependency

### ISSUE THREAD

**Issue by garrettr** [globaleaks/GlobaLeaks#1888]
The current stable version of the Python cryptography library is 1.7.2: https://cryptography.io/en/latest/changelog/. Globaleaks uses different versions depending on the installation environment:

```
$ grep -r "cryptography==" backend/
backend/requirements/requirements-stretch.txt:cryptography==1.3.1
backend/requirements/requirements-jessie.txt:cryptography==0.6.1
backend/requirements/requirements-trusty.txt:cryptography==0.8.2
backend/requirements.txt:cryptography==0.8.2
```

Some are extremely old, and all have one or more security issues according to the cryptography changelog. Additionally, it can be difficult to build such old versions of the library on newer Linux distributions. For example, I cannot build `cryptography==0.8.2` on Fedora 24, while `cryptography==1.7.2` builds without issues.

**Comment by NSkelsey** [comment]
Thanks for reporting @garrettr.

All the shipped packages actually use the trusty dependencies. Currently that is `trusty` `precise` and `jessie`, but we are by default only supporting `trusty` installs. The rest of the requirements files in there are leftover from an attempt to track the python packages available in each distribution. Now we have a spread sheet. . . . which I cannot find.

The goal here is to simply drop the pip requirement and instead rely on the distributed python dependencies that ship with the OS.

I noticed that you guys are checking in the python securedrop dependencies via wheels and distributing them inside the debian package. It seems like a great solution. Is this an approach that works across platforms?

N.B. The cryptography dependency is used for AES on temp files and SHA2 hash fncs.

**Comment by evilaliv3** [comment]
The dependencies analysis in relation to packaging is discussed here: https://github.com/globaleaks/GlobaLeaks/issues/1515

**Comment by evilaliv3** [comment]
@garrettr thee reason why you are not compiling anymore the 0.8.2 on the version of Fedora that you are using (probably the latest stable) is probably related to different dev libraries and headers that are present on that distribution. The same for example happens if one try to compile the 0.8.2 on ubuntu xenial (16.04)

**Comment by NSkelsey** [comment]
The `cryptography` and `cffi` deps were updated in 2ea3e9ea to use the Xenial dependencies in `requirements-trusty.txt`. This is a compatibility change to support our usage of the latest release within the ubuntu universe.

The latest version of these libraries we will use are the installed targets on the latest platform we support. We expect these versions to continue to receive backports fixing issues and vulnerabilities.

Hence `cryptography==1.2.3` and `cffi==1.5.2`
