### ISSUE TITLE
Implement Tor IP check and redirect Tor users to Hidden Service address

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1891]
This ticket is to keep track of the activities needed in order to implement the Tor IP check and redirect Tor users to Hidden Service address.

The feature implementation should starts from the Tor2web codebase where to maximize the code reuse and improve the shared codebase.

**Comment by evilaliv3** [comment]
Implemented should be documented as feature in the apppication security document.

The feature first implemented in feature 1852 branch is now landed in devel branch.

**Comment by NSkelsey** [comment]
This is implemented as of e20e8fbd5a5756c8f2a23a1a6387a178207b6451
