### ISSUE TITLE
Submitter can't upload files due to bug.

### ISSUE THREAD

**Issue by filternetz** [globaleaks/GlobaLeaks#1894]
**Current behavior**

On version 2.63.4 I got the following in the error logs:

<pre>
2017-02-06 17:43:24+0000 [GLHTTPConnection,3145,127.0.0.1] &quot;[!] Submission create: receivers import fail: object of type &#39;NoneType&#39; has no len()&quot;
2017-02-06 17:43:24+0000 [-] Uncaught exception
        [Failure instance: Traceback: &lt;type &#39;exceptions.TypeError&#39;&gt;: object of type &#39;NoneType&#39; has no len()
        &#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;defer.py:423:errback
        &#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;defer.py:490:_startRunCallbacks
        &#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;defer.py:577:_runCallbacks
        &#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;defer.py:1155:gotResult
        --- &lt;exception caught here&gt; ---
        &#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;defer.py:1097:_inlineCallbacks
        &#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;failure.py:389:throwExceptionIntoGenerator
        &#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;handlers&#47;submission.py:451:put
        &#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;threadpool.py:191:_worker
        &#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;context.py:118:callWithContext
        &#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;context.py:81:callWithContext
        &#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;orm.py:116:_wrap
        &#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;handlers&#47;submission.py:429:create_submission
        &#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;handlers&#47;submission.py:399:db_create_submission
        ]

2017-02-06 17:43:24+0000 [-] &#39;[!] Unhandled exception raised:&#39;
2017-02-06 17:43:24+0000 [-] &#39;[!] TypeError Inappropriate argument type.&#92;&#92;n&#92;&#92;nTraceback (most recent call last):&#92;&#92;n&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;internet&#47;defer.py&quot;, l
ine 1097, in _inlineCallbacks&#92;&#92;n    result = result.throwExceptionIntoGenerator(g)&#92;&#92;n&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;failure.py&quot;, line 389, in throwExceptionIntoGenerator&#9
2;&#92;n    return g.throw(self.type, self.value, self.tb)&#92;&#92;n&#92;&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;handlers&#47;submission.py&quot;, line 451, in put&#92;&#92;n    self.request.language)&#92;&#92;n&#92;&#92;n  
File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-packages&#47;twisted&#47;python&#47;threadpool.py&quot;, line 191, in _worker&#92;&#92;n    result = context.call(ctx, function, *args, **kwargs)&#92;&#92;n&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;
python2.7&#47;dist-packages&#47;twisted&#47;python&#47;context.py&quot;, line 118, in callWithContext&#92;&#92;n    return self.currentContext().callWithContext(ctx, func, *args, **kw)&#92;&#92;n&#92;&#92;n  File &quot;&#47;usr&#47;local&#47;lib&#47;python2.7&#47;dist-pac
kages&#47;twisted&#47;python&#47;context.py&quot;, line 81, in callWithContext&#92;&#92;n    return func(*args,**kw)&#92;&#92;n&#92;&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;orm.py&quot;, line 116, in _wrap&#92;&#92;n    result
 = function(self.store, *args, **kwargs)&#92;&#92;n&#92;&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;handlers&#47;submission.py&quot;, line 429, in create_submission&#92;&#92;n    return db_create_submission(store, token_id, reque
st, t2w, language)&#92;&#92;n&#92;&#92;n  File &quot;&#47;usr&#47;lib&#47;python2.7&#47;dist-packages&#47;globaleaks&#47;handlers&#47;submission.py&quot;, line 399, in db_create_submission&#92;&#92;n    raise excep&#92;&#92;n&#92;&#92;nTypeError: object of type &#92;&#39;
NoneType&#92;&#39; has no len()&#92;&#92;n&#39;
</pre>

A submitter can't successfully upload files/make a submission.

So I upgraded Globaleaks to 2.65.15 and now when I make an submission(I do not get errors in the globaleaks log) I do not get past tab 2 (fill out your submission) See screenshot: https://i.imgur.com/uiI8KmV.png

**Expected behavior**

A submitter should be able to make a submission.

**Steps to reproduce the problem or feature illustration**

Make an submission on: http://kjpkmlafh2ra57wz.onion/#/submission

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

2.65.15

* **Server Operating System and Version (if appliable):**

# lsb_release -r
Release:        14.04

**Comment by infosquatter** [comment]
Also facing the same bug. It is crucial to solve it.

**Comment by evilaliv3** [comment]
We just verified the issue and issues a 2.65.19.

That release fixes a bug spotted by @infosquatter and still related to this ticket but slightly different (https://github.com/globaleaks/GlobaLeaks/commit/689b511aa56fdd4400f6a16ccabfbaa50fb41183)

The issue reported by @filternetz instead is probably related to old bugs fixed in current release. We suggest to update to latest version to evaluate if the bug is still present.

**Comment by NSkelsey** [comment]
Will reopen if new reports if they come in.
