### ISSUE TITLE
Unrecognized Content-Security-Policy directive 'referrer'.

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1898]
The CSP configuration that is currently used has been deprecated and should be updated.

Documentation reference: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/referrer

**Comment by evilaliv3** [comment]
The current header that is deprecated is also recognized as error on chrome and is currently causing tests failure on travis.

It should be replaced with ```Referrer-Policy: "no-referrer"```: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy

**Comment by evilaliv3** [comment]
The new header is in place. Its worth ith to know that it is a standard draft shared and implemented by quite all the browsers, except Microsoft, obviously.

**Comment by evilaliv3** [comment]
Keeping this open until documented.

**Comment by NSkelsey** [comment]
The new header is documented and outdated information about `Content-Secuirty-Policy` is now gone.
