### ISSUE TITLE
Improve Unit Testing of Email Notification

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#190]
This ticket is about improving unit testing of email notification of globaleaks.

The unit-test must be implemented following the discussion on #122 (originally about a bug, then became unit-testing discussion).
##

**Comment by evilaliv3** [comment]
@origliante, with this commit https://github.com/globaleaks/GlobaLeaks/commit/7e93f4732618ebaacd7398e90f992410f723ad2c i've integrated the code you proposed for this issue.

to be precise this ticket is currently not addressed at all. we sill miss completely an unit testing of such a feaure. pleease notice the commit message i've written where with a small sentence i've tried to better qualify what has been addressed in that commit.

**Comment by evilaliv3** [comment]
Specifically in relation to unittest all but the twisted functions are tested. The specifical twisted emails are tested by their specific tests in the twisted framework.

Other tickets track the runtime testing of the configuration that is a different unrelated topic.
