### ISSUE TITLE
Debian package authentication issue

### ISSUE THREAD

**Issue by fiyona** [globaleaks/GlobaLeaks#1900]
WARNING: The following packages cannot be authenticated!
  globaleaks
E: There are problems and -y was used without --force-yes
am getting this error when installing  globaleaks

**Comment by evilaliv3** [comment]
@fiyona thanks for notifying this.

it seems we forgot to apply the package signature.

all should be OK now, could you please recheck?

**Comment by fiyona** [comment]
Thanks..............it was successfull
