### ISSUE TITLE
Tor2web is not running

### ISSUE THREAD

**Issue by fiyona** [globaleaks/GlobaLeaks#1903]
* Enabling Tor2web Apparmor Sandboxing...                                      aa-exec: ERROR: profile 'usr.bin.tor2web' does not exist

 * Tor2web is not running

Hello
Help!..how do i go about this

**Comment by evilaliv3** [comment]
Thanks @fiyona but from the information provided is impossible to be able to reproduce the reason of the failure.

Please open a ticket on the Tor2web repository including useful information.

https://github.com/globaleaks/Tor2web

**Comment by fiyona** [comment]
Hello Giovanni,
Kindly help me on how i can go about this error,

When i start tor2web , i get the following error;-

service tor2web status
Letsencrypt detected, fixing permission for /etc/letsencrypt/{live,archive}
for tor2web user
 * Enabling Tor2web Apparmor Sandboxing...
                                                            aa-exec: ERROR:
profile 'usr.bin.tor2web' does not exist

 * Tor2web is not running
