### ISSUE TITLE
Cannot update project logo

### ISSUE THREAD

**Issue by chepurko** [globaleaks/GlobaLeaks#1908]
**Current behavior**

Clicking on Change picture for the Project logo under General settings > Theme customization and uploading a PNG of size 140x140 displays the new logo in the preview, but the logo is not updated upon clicking Save.

**Expected behavior**

The new logo should be shown instead of the default Globaleaks logo.

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

v2.65.19

**Browser:**

- [ ] All browsers
- [x] Chrome:  56.0.2924.87 (64-bit)
- [x] Firefox: v48
- [ ] Safari:
- [ ] Mobile Chrome:
- [ ] Other: 
- [ ] Not Applicable

* **Server Operating System and Version (if appliable):**
 
Ubuntu 14.04

* **Client Operating System and Version (if appliable):**

Ubuntu 16.10/16.04, Windows 7

**Comment by chepurko** [comment]
I would also add that I can't do the same for the Context logo when editing a context under Context configuration. Seems like I can't upload an image/logo anywhere.

**Comment by evilaliv3** [comment]
Bug confirmed, regression added in https://github.com/globaleaks/GlobaLeaks/commit/199d64b2ff8b8e0e69fcaed376de8df3a325d3cc

Patch on its way, will be shipped out in few days with release 2.66

**Comment by NSkelsey** [comment]
Can confirm it is fixed.
