### ISSUE TITLE
Integrate TxTorcon to configure Tor via ControlPort by means of Ephemeral Hidden Services

### ISSUE THREAD

**Issue by adrelanos** [globaleaks/GlobaLeaks#1909]
Can you please port GlobaLeaks to use ephemeral Tor hidden services?

* This basically means, use the Tor ControlProtocol to create the hidden service. Not using torrc modifications.
** Yes, ephemeral Tor hidden services can also persist between reboots. After creating it with add_onion new, you get the hidden service private key, can store it, and restore it later.
** This can be done using python-stem. - https://packages.debian.org/stretch/python3-stem
** From that perspective, GlobaLeaks would be a project similar ricochet. (https://github.com/ricochet-im/ricochet)
** Further, onionshare is also an example using Tor ephemeral services.

Wishlist:

* Use python-stem since that is perfectly compatible and tested with https://github.com/Whonix/control-port-filter-python.
* Don't send more than 1 Tor ControlPort command at once.
** I.e. do not request `'status/circuit-established status/bootstrap-phase`, do request `'status/circuit-established` followed by 'status/bootstrap-phase'.
** That makes our (and Tails also I believe so) control protocol filtering easier.
* Please do not listen on any random local port.
** onionshare listens on `17609` - `16759`.
** zeronet listens on `15441`.
** Have a look at https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers and see if you can find some unused port or port range.
** A fixed or limited list of ports makes our documentation to open a port in the Whonix-Workstation a lot saner.

Implementing this ticket as well as https://github.com/globaleaks/GlobaLeaks/issues/956 would allow us at [Whonix](https://www.whonix.org/) to install GlobaLeaks by default.

This feature request supersedes my previous similar feature request:
https://github.com/globaleaks/GlobaLeaks/issues/962

Similar to:
https://github.com/AnemoneLabs/unmessage/issues/4

**Comment by evilaliv3** [comment]
Thanks @adrelanos for your great feedback and the interest in supporting us in getting into whoonix.

Actually we are planning already to integrate txtorcon but for the same capabilities, but we still need to do a final choice.

For your information in globaleaks we would like to use more than one tor subprocess; We would like to have one for the outgoing traffic and one for the incoming traffic; in relation specifically to the incoming traffic we are planning that possible the platform could host multiple hidden services in relation to some multitenancy capabilities that we will soon implement.

Do you have an suggertion for the port range that we could use?
1) a main outgoing tor subproess will require the outgoing sock port and a tor control port
2) multiple tor subprocesses will require a tor control port for managing hidden service creation/reload

**Comment by adrelanos** [comment]
> Do you have an suggestions for the port range that we could use?

Not much. Only one above 1024 so you can bind to it without root as well as looking through https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers and then just arbitrarily picking a range that is not used by anything else.

Btw it's `Whonix`, not `Whoonix`.

> multiple tor subprocesses will require a tor control port for managing hidden service creation/reload

Multiple Tor processes is something we don't currently support in Whonix. (I mean, it's certainly possible to manually configure Whonix to do that, but that does not have good usability.)

> a main outgoing tor subproess will require the outgoing sock port and a tor control port

Not a problem in @Whonix to provide multiple outgoing Tor SocksPorts.

Btw I don't see why multiple outgoing Tor SocksPorts would be required - if you set a different socks user name per instance, IsolateSOCKSAuth (default enabled in Tor) kicks in and you get stream isolation. (And different Tor hidden services are stream isolated by default by Tor anyhow.

Tor ControlPort access is generally not an issue in Whonix 14. Due to the implementation gateway's control-port-filter-python and workstation's anon-ws-disable-stacked-tor packages, the application can use any default localhost Tor socks or control port. (127.0.0.1 9050, 127.0.0.1 9150, anything) No special application support required for that.

python(2.7 or 3)-stem is easier to get to work with Whonix than txtorcon from the Whonix side (#215), but looks like that is going to be sorted out.

----

FYI: Not exactly the same situations as yours.... However, multiple vs a single Tor process is an open research question. We're in contact with Roger of tor and Tariq who wrote the guard rotation paper, there might be a research wanted blog post soonish.

https://www.whonix.org/wiki/Dev/Multiple_Whonix-Workstations

//cc @HulaHoopWhonix

**Comment by fpietrosanti** [comment]
@evilaliv3 why do we need to have multiple tor-subprocess rather than one Tor with multiple HS attached to it?

**Comment by evilaliv3** [comment]
Development of this feature is on its way.

On development we already integrated txtorcon and simplified the model to use a single process with multiple hidden services.

Expected release is with the multi tenancy branch that would require ~2 months of stabilization from now.

**Comment by evilaliv3** [comment]
@adrelanos this feature is in place and will be shipped with 2.70.

In the first version of the the ephemeral services implementation we decided to have globaleaks communicate via unix socket (the default ```/var/run/tor/control``` file).
This way it is really simple for us to keep the configuration safe as globaleaks in order to access such a configuration just require to be added to the ```debian-tor``` group.

- Do you find this a good solution to the issue?
- Do you consider important to be able to configure a TCP configuration for the control port and of an authenticated cookie? If yes we may consider this for the future and make it configurable via the admin interface /cc @NSkelsey @fpietrosanti

**Comment by adrelanos** [comment]
/var/run/tor/control is fine. Both,

* /var/run/tor/control
* and /var/run/tor/control.authcookie

will be available in Whonix-Workstation in Whonix 14.

(FYI: https://github.com/Whonix/anon-ws-disable-stacked-tor forwards it to Whonix-Gateway. So nothing @globaleaks has to worry about.)
