### ISSUE TITLE
Support longer certificate chains when enabling HTTP.

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1913]
**Current behavior**

If you upload an SSL certificate chain with more than one cert only the first one is used. For most use cases this is not a problem. But it means that the clients browser will either have to retrieve the intermediate certificate or it will consider the servers certificate chain incomplete.

**Steps to reproduce the problem or feature illustration**

![trust-chain](https://cloud.githubusercontent.com/assets/1095794/23583222/e70131e6-013d-11e7-871e-a0924bc02b93.png)

**GlobaLeaks version:**

v2.66.0

**Resolution**
Parse multiple certs, spoon feed them to `load_certificates` and load them into the SSL context one at a time.

**Comment by evilaliv3** [comment]
@NSkelsey could you please try reverting the order of the certificates? they should be in the right order to be loaded correctly

In addition we could implement the test of the intermediate load at context level (without a real http connection) with: https://github.com/Mysterie/streamster2-pyopenssl/blob/master/Test/test/test_ssl.py

**Comment by NSkelsey** [comment]
Quick update on this.

The `ChainValidator` class in [tls.py](https://github.com/globaleaks/GlobaLeaks/blob/devel/backend/globaleaks/utils/tls.py#L211). A regex or a `str.split` needs to be added to try and load multiple certs with an exception raised on any issues.

**Comment by evilaliv3** [comment]
i've implemented a regexp recognition based on https://github.com/hynek/pem

```
import re

with open('/data/evilaliv3/ssl/cert.pem', 'r') as f:
    data = f.read()

INTERMEDIATE_RE = re.compile(b"-----BEGIN CERTIFICATE-----\r?.+?\r?-----END CERTIFICATE-----\r?\n?""", re.DOTALL)

def parse(data):
    return [match for match in INTERMEDIATE_RE.finditer(data)]

for match in parse(data):
    print match.group(0)
```

@NSkelsey could you please recheck if the solution work and produce a patch inside the letencrypt branch?

probably the solution to implement should do two temptatives:
- try to split and if get some matches try to load them.
- if no match is found just try to load it at once

**Comment by evilaliv3** [comment]
Postponed out of the milestone to be retested more carefully.

**Comment by NSkelsey** [comment]
In the process of updating the certificate validators, I've realized an interesting side effect of making our certificate validation more stringent. Instances that update to the new validation with https enabled and an invalid certificate -- in this case a certificate file with more than one certificate in it -- will discover on startup that HTTPS is disabled because the system has detected an invalid configuration.

I do not believe that in this case that this is problematic, because there are still only a few setups that are using HTTPS and loading a certificate chain into the certificate field will break a few things. However, for future changes that we may have to make we should be aware of this validation on update issue.

**Comment by NSkelsey** [comment]
Okay, notably missing from the tests cases is a positive example of multiple certificates being served correctly. I will upload a positive example in time for `v2.70.3`.
