### ISSUE TITLE
Error adding the public PGP key to a user.

### ISSUE THREAD

**Issue by misophetamenos** [globaleaks/GlobaLeaks#1914]
Hello everyone.

I have problems adding the PGP public key for a user to be an administrator or receiver, it generates error without indicating a cause.

These keys have been generated with GPG v1 and v2, with the same error result, on the other hand, I have tried grendolas of type RSA and DSA.

I consulted the documentation of the project in this portal, but I did not find much information.

I appreciate the help they can give me, so that I can advance in the test of this project.

Sorry for my bad English.

**Comment by NSkelsey** [comment]
Hi @misophetamenos thank you for reporting this. Two questions: are you seeing a generic red box? Does the log `/var/globaleaks/log/globaleaks.log` show problems? Could you answer the same questions answered [here](https://github.com/globaleaks/GlobaLeaks/issues/1882)

Uploading the public half of an RSA key of 2048 bits is certainly supported.

**Comment by misophetamenos** [comment]
Hi, @NSkelsey thanks for your quick response.

First, confirm that a red box.
Second, I have checked the logs and the following error appears:

***************
2017-03-11 08: 25: 52-0800 [HTTPConnection, 28,127.0.0.1] & quot; [!] Unable to instance PGP object: __init __ () got an unexpected keyword argument 'gnupghome' & quot;
2017-03-11 08: 25: 52-0800 [-] Uncaught exception
**************************************************

Third, I performed the procedure with a 1024-bit key and generated the same error.

I attached the test logs made with keys of 1024, 1536 and 2048 bits.
[pgp-key_error_1024.txt](https://github.com/globaleaks/GlobaLeaks/files/835983/pgp-key_error_1024.txt)
[pgp-key_error_1536.txt](https://github.com/globaleaks/GlobaLeaks/files/835985/pgp-key_error_1536.txt)
[pgp-key_error_2048.txt](https://github.com/globaleaks/GlobaLeaks/files/835984/pgp-key_error_2048.txt)

**Comment by evilaliv3** [comment]
Hello @misophetamenos thanks for reporting this.

I guess you are not following the standard setup path right?
The issue you are getting is a duplicated issue of https://github.com/globaleaks/GlobaLeaks/issues/1885; you find there the solution;

basically i guess you have installed the gnupg package manually but the one that you have to install is python-gnupg.

if you can take us more about your use case and the platform we can guide you better and in case you project require it we can discuss about providing you professional support.

Closing the ticket for now as duplicated
