### ISSUE TITLE
Is it possible to display the files hosted on the server?

### ISSUE THREAD

**Issue by misophetamenos** [globaleaks/GlobaLeaks#1915]
Hello,

My query is about the files that are hosted on the server regarding the submissions, these are stored in the / var folder with extension ".plain".

Is it possible to view or decrypt these files?

Thank you.

**Comment by NSkelsey** [comment]
Hi @misophetamenos if you are looking at `.plain` files stored in the /var/ directory, those are files uploaded to the platform without encryption. You can download these files from the recipient's interface. If you enable encryption the extension of those files will change.
