### ISSUE TITLE
Stats of the week

### ISSUE THREAD

**Issue by fiyona** [globaleaks/GlobaLeaks#1926]
![image](https://cloud.githubusercontent.com/assets/19567585/23997996/ad3edce4-0a64-11e7-93cf-eb6fa936fd82.png)

Kindly briefly explain this for me

**Comment by fpietrosanti** [comment]
For support requests please kindly post on the Community Support Forum at https://forum.globaleaks.org . If you need any specific Professional Support you can send an inquiry to https://www.globaleaks.org/contact/
