### ISSUE TITLE
Display and force acceptance of GlobaLeaks license during wizard configuration

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1927]
This ticket is to Display and Force acceptance of GlobaLeaks License at Activation Time, before going trough the wizard.

The license AGPL 3.0 of GlobaLeaks shall be displayed and the end-user shall be informed that he need to accept it in order to go forward.

Only when the user click "Accept" the end-user move to the Configuration Wizard.

**Comment by NSkelsey** [comment]
Half of this ticket is now implemented. The license is available as a static resource on the platform under `/data/license.txt` The other half of including the license in the wizard as a required step is similarly possible. This definitely an easy task.

**Comment by NSkelsey** [comment]
I've opened the branch `feature/1927` with 975aa7e0b06bc81d8fed0369be92aa6c9881b479. There are a few things to note.

1) I intend to store the license as a static file in the client dir.
2) For multi-tenancy we may want to customize the license that actually gets to displayed to a user. This will be easy by just overwriting the license file.
3) the display of the license is in a scrolled window, with a required checkbox that forces acceptance.

Point 3) has an interesting extension that we could implement. Keep the ability to select the "I agree checkbox" until the text box has been scrolled to the bottom. This is a bit of an anti-pattern in the sense that, if you actually want somebody to read the license it would be better to just display it in full and have them scroll down to find the agree text. Either way for me it works.

**Comment by evilaliv3** [comment]
Thanks for the update.

1. Good to have it as a raw LICENSE file. Consider to not create a copy of the license file but to perform a link to the backend/LICENSE, to verify that the file is copied and accessible in a build client, and then just use it a a REST resource as in other interfaces. This way we avoid to add it inside the build client.
2. Yes this is a possibility but i do not think any implementation would affect this. This topic is part of the rebrending analysis but not related to the multitenancy: https://github.com/globaleaks/GlobaLeaks/issues/1955
3. the license is a long file so better to keep into a textarea; for the moment let's just implement the textarea and the checkbox postponing the implementation of the scroll+enabling of the checkbox after review and integration of this.

**Comment by evilaliv3** [comment]
Review performed and branch integrated in devel.

Here the current interface:
![image](https://user-images.githubusercontent.com/217034/30313082-6d6bddb8-979c-11e7-886e-732302a01807.png)

**Comment by NSkelsey** [comment]
merged in deve.
