### ISSUE TITLE
Can not install GlobaLeaks due to network connection failure

### ISSUE THREAD

**Issue by alepartenza** [globaleaks/GlobaLeaks#1937]
I'm trying to install GlobaLeaks but I get the timeout error.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                                     Dload     Upload  Total    Spent    Left   Speed
  0     0    0     0    0     0      0      0 --:--:--  0:02:06 --:--:--     0curl: (7) Failed to connect to deb.globaleaks.org port 443: Connection timed out

**Comment by NSkelsey** [comment]
Hey @alepartenza, are you running?

```bash
curl https://deb.globaleaks.org/install-globaleaks.sh | sudo -E bash
```

The server deb.globaleaks.org is online. Can you verify that the download
link https://deb.globaleaks.org/install-globaleaks.sh works on your local
machine and the machine you are installing GlobaLeaks on.

**Comment by alepartenza** [comment]
I tried with:
`curl https://deb.globaleaks.org/install-globaleaks.sh | -E sudo bash`

and the previous procedure:
```
wget https://deb.globaleaks.org/install-globaleaks.sh
chmod +x install-globaleaks.sh
./install-globaleaks.sh
```

but nothing, not install GlobaLeaks.
I had done other installations in the past gone well. I use Ubuntu 14.04

**Comment by evilaliv3** [comment]
@alepartenza: i confirm what written by @NSkelsey;

the server is up and running, try to understand why you cannot reach it from your local network.

for further necessities depending on your project needs evaluate to request professional support via whistleblowingsolutions.it / globaleaks.org

**Comment by alepartenza** [comment]
I have solved. 
The problem was created by Ubuntu 14.04. I did the install on Ubuntu 16.04 and the package was installed.

**Comment by evilaliv3** [comment]
Great!

Closing the ticket then.
