### ISSUE TITLE
Could not send notification from https browser

### ISSUE THREAD

**Issue by alepartenza** [globaleaks/GlobaLeaks#1940]
Hi,
if I try to send a report from browser, loading the wheel never stops turning.
If the report sent by TOR is fine.

Globaleaks Version: 2.67.1

**Comment by NSkelsey** [comment]
Hi @alepartenza thanks for reporting. Please use the issue template to answer questions about the browser you are using. Can you verify that the demo.globaleaks.org is similarly not functioning? If the issue is only on your site, consider contacting professional support.

**Comment by alepartenza** [comment]
The problem appears when I use the experimental features and demand patterns.
Disabling the option is fine.

**Comment by evilaliv3** [comment]
What do you mean by demand patterns?

**Comment by alepartenza** [comment]
Scrivo in Italiano:
Attivo le funzionalità sperimentali e il modello di domanda 'Vuoi fornire i tuoi dati identificativi?'.
Se volessi inviare una segnalazione da browser non TOR ma da https://www.nomedominio.org la stessa non va a termine e la rotellina Loading non smette mai di girare non stampando il codice di segnalazione.

**Comment by evilaliv3** [comment]
Va bene grazie, verificheremo il problema e cercheremo di inserire il suo fix nella nostra roadmap.
La feature è purtroppo ad ora sperimentale e non ne è appunto garantito il funzionamento.

Consideri nel caso sia requisito del suo progetto che siamo disponibili ad un eventuale supporto professionale attraverso l'impresa sociale whistleblowing solutions appositamente creata: https://www.whistleblowingsolutions.it

**Comment by evilaliv3** [comment]
Closing the ticket as outdated.

Feel free to re-open it if still actual.
