### ISSUE TITLE
Sanitizing metadata in uploaded files on the client-side

### ISSUE THREAD

**Issue by ralienpp** [globaleaks/GlobaLeaks#1942]
The status quo is that it is possible to perform deanonymization by examining the metadata of uploaded files (I tried the demo interface and saw no hints about it). A whistleblower may be unaware of possible embedded GPS coordinates in JPG files, or author names in Word documents, etc.

Globaleaks would give _a false sense of anonymity_, while the journalists who receive the documents will be able to connect the dots and find the identity of the submitter. Even worse, the police could raid the offices of a newspaper and confiscate all the computers, to do forensic analysis. The authorities would find the source of the leak even if the journalists themselves had no intention to help them.

There is a related issue here: #1323, but meta-data is potentially more dangerous.

I think that in an ideal case we could:

- tell people about the dangers of metadata _before_ they submit anything
- use client-side libraries to remove metadata before the data gets to the server. This should be done, at least for the most common formats like PDF, JPG, Word, Excel, Powerpoint
- perhaps even display a summary of what metadata was found and removed before the submission.
- metadata could be removed on the server too (though it implies submitters have to trust the server admins - which is too much to ask, in my opinion)

**Comment by NSkelsey** [comment]
@ralienpp there was an implicit choice made to not scrub, AV scan, or try to analyze submitted files as they are loaded in the platform. There are tools for scrubbing metadata that are well made and shipped by default with Tails. There are many good reasons for keeping the interaction of core software small with formats that are notorious for providing RCEs. Further Globaleaks has a data retention policy that by default removes submitted data within 15 days

For setups that use PGP the content of the files is stored encrypted on the server. If PGP is not encrypted the Whistleblower is informed in the interface that their intended recipients are not encrypting files. That warning might not quiet address the meta data issue and could be changed to include language about the risk of Personally Identifiable Information/Metadata.

This --> FAQS

**Comment by NSkelsey** [comment]
Current language:
```html
<strong><span data-translate>Warning</span></strong>
<span data-translate>One or more of the recipients of this submission has not configured a PGP key.</span>
<span data-translate>This means that the submitted files will be stored in plaintext on the server.</span>
```

@ralienpp any suggestions?

**Comment by ralienpp** [comment]
Thanks for the feedback, I wasn't aware that it is so by design.

I do have a suggestion. I apply the "mother test", basically I ask myself "what would my mother think if she read that?". What is PGP? What is plaintext? So what if it is plaintext?

Thus I would add something like this:

```
<strong><span data-translate>Warning</span></strong>
<span data-translate>One or more of the recipients of this submission has not configured a PGP key.</span>
<span data-translate>This means that the submitted files will be stored in plaintext on the server.</span>
<span data-translate>If anyone (e.g. law enforcement agents who confiscated the hardware) gets access to the server, they will be able to read your submitted files.</span>
<span data-translate>Ensure that the files do not have clues (in metadata or in their contents) that could be used to reveal your identity.</span>
```

I believe it should be made clear to the submitter that:

- someone who gets access to the server will also be able to read the files (not just the journalists)
- their anonymity is in jeopardy if the docs contain references to the source



If you apply the mother test again, you see that the next questions would be "what is metadata?" and "how to check it?".  Therefore, this page presents an opportunity to answer the questions right away by providing links to tools or to a brief explanation.

The fact that the tools are available does not imply that people are aware of them and will use them. I have not tried Tails yet, but I will do so (as I am helping someone set up Globaleaks and will train them about the whole thing). If Tails doesn't somehow patch the "open file" dialog to pass everything though the data sanitizer - that's bad, in my opinion.


At the same time, if you make people perform extra steps at the final moment, some of them may actually give up (like a bounce rate on a web-site). In any case, I will find the FAQ and see what the rationale behind the decision was, in order to see a clearer picture. I'd appreciate it if you could give me a link to it (I didn't find it, but I found #663).

**Comment by evilaliv3** [comment]
Thank you @ralienpp for your important feedback.
So looking forward for comments like yours.

I've some additional clarification from my side;

About metadata, the premises are:
- the journalist is and will have always to be be a trusted party in the process;
- removing the metadata that can deanonymize the whistleblower without removing the metadata that can proove the malpractice (e.g. the name of the perpetrator or of the victim) is not possible.
- technically it is even quite difficult to be sure to remove the metadata for every file as the metadata do not have standard formats.

what we decided is:
- to not remove automatically the metadata
- to eventually offer the recipient to save the documents in a "safe" metadata-free mode by providing a print feature of it and giving the recipeint the possibility to download two files 1) the clean one (to use during work) 2) the original to use in a legal procedure if and when necessary.

about the texts and the mention about PGP you are right, the language is cryptic, here we fail also because are so so so old texts; recently we are taking care of this.
The choices that lead to that text, in two sentences and not more are: try to write a concise sentence, that do not require too much translations and that so won't have that much errors in the translations process that is where the more are inserted.

now probably i would go to keep them short but eventually i would replace "PGP" with  "Encryption" saying: "One or more of the recipients of this submission don't have encryption enabled".

FAQ: yes they do now exists still :(

\cc @fpietrosanti

**Comment by NSkelsey** [comment]
Here is another revision of the text, that tries to elaborate the consequence of someone evil gaining access to the box.

```
<span data-translate>At least one of the recipients of this submission has not configured an encryption key.</span>
<span data-translate>This means that the submitted files will be plainly readable on the server.</span>
<span data-translate>If someone malicious breaks into the server, they will be able to read your submitted files.</span>
<span data-translate>Ensure that the files do not have clues (in metadata or in their contents) that could be used to reveal your identity.</span>
```

**Comment by fpietrosanti** [comment]
Please consider while writing the text that not all whistleblowers are anonymous, in fact for what anti-corruption NGOs say us, most declare who they are, so encryption is meant to protect the information against unauthorized access, not to avoid disclosure of whistleblower identity.

**Comment by ralienpp** [comment]
We come from different places and have different requirements. For example, this happened in my country: https://en.wikipedia.org/wiki/Moldovan_bank_fraud_scandal

Members of the parliament are _purchased in bulk_ to make them join another party and vote "correctly". Judges issue whatever decisions are desired by those who pay them. People who criticize the government are harassed, a vocal critic of those in power was found dead with a "self-inflicted" gunshot wound, etc.

Those who are supposed to find and punish the guilty are guilty themselves, so obviously there is no progress in these cases, even though "our best men and women are working on it as we speak".  It is expected that any potential whistleblower is *very* concerned about their own life, so (if they had proper infosec training) they would:

- remain anonymous even to the journalists; because if law-enforcement exerts pressure on the journalists (e.g. with rubber-hose cryptanalysis) - there's nothing that they can learn, *in principle*.
- remove all metadata and other clues that could possibly unmask them

Without proper infosec training they might just think that making a new email address like "theunknownunknown1935@gmail.com" is sufficient to remain anonymous.


Unfortunately I have to say that despite all of the above, there are countries that are worse off than Moldova; that's why I believe that at least some basic safe-guards should be in place, at least for the lower-hanging fruits (common, well-documented formats).

**Comment by evilaliv3** [comment]
Thanks for the feedback. I totally understand and see your point.

After reading well the full trace of Alex i found out that this is totally
inline with past he research path we always discussed.

Let me elaborate why and which is the state.

Technically the receiver is and can only be a trusted party
It is technically iimpossible to remove all the metadata.
It is technically impossible to discern good from bad metadata.

This lead us for the moment to simplify the assumptions, leave the metadata
scrumbling in responsibility of the recipient avoiding to make false
promises to the user.

But the points you are making are totally legit and i support them.

In particular, is normal path we follow to
- work on adding more clarifications to the user on the topic
- working on simplifying the technical gergon to make the topic more
understandable to the user

It's a research topic kept open to:
-Offer the possibility to show the user recognised metadata even asking to
the user what to remove
- Offer to the admin the possibility to enforce max removal if the scenario
requires that.

Remains true and legit what told by Nick that aside that this is inline
with the research to do, we will never be able to point out that the
technique implemented won't guarantee anything and that the best practice
will remain to highlight that better (not perfect) specialized tools exists

**Comment by ralienpp** [comment]
Alright, I got permission to join the project on Transifex and after I fill out the remaining strings for Romanian and Russian, I will try to make another iteration and suggest changes for the texts that involve complex matters.

In the meantime, as a source of inspiration, I would like to share a paper I've read recently.
[Obstacles to the Adoption of Secure Communication Tools.pdf](https://github.com/globaleaks/GlobaLeaks/files/920297/Obstacles.to.the.Adoption.of.Secure.Communication.Tools.pdf)


Here are some highlights

```
Ten participants confused encryption with authentication.
“Multiple encryption” was described as using both a username
and multiple passwords to log in to an account. “Double
encryption” was equated to two-factor authentication (P12).
...
P3, P7, P8, P11, P13, P22, and P43 have not heard
of encryption, and did not provide any deﬁnition. P1 and
P59 conﬂated encryption with data encoding. P1 explained
encryption as sending messages in “computer language:
01010011110100” (i.e., binary), and said “these messages can
only be understood by computer scientists, hackers, service
providers and governments. Lay people cannot.” P59 explicitly
described encryption as sending text in “binary language:
122121122”.
Other participants explained encryption as:
...
2) Making conversations “invisible” (P14).
3) Slowing down the process of understanding the data,
but the company can still read the messages. “Basically,
encryption is (no encryption + adding some time to send
the data packets)” (P23).
...
5) Using a special language (P27, P32, and P35). If some-
one (like a computer scientist) knows the language, they
can decrypt the message (P26).
6) Using proxies to access websites. P29 believes that using
proxies (encryption) protects against the company and
government agencies, however, proxies are not legal to
use.
All participants, but three, believe that encryption protects
against the unsophisticated attackers “who do not know how to
hack”.
```

```
The key takeaway from mental models research is that
non-experts do not understand abstract security properties.
They can only understand why a property matters in the
context of a speciﬁc threat model that matters to them.
```
Thus, the texts should necessarily address the "what's in it for me?" aspect.

```
57 participants (excluding P2, P4 and P5) provided various
incorrect explanations of digital signatures: (1) inserting a
USB stick into the PC to sign a document using a unique
code, (2) scanning a hand-written signature, and then adding
the signature electronically to a document, or (3) signing a
digital document using a stylus pen. P29 described a digital
signature as “a speciﬁc font type in Microsoft Word used to
type names”.
```

There are more gems in the paper itself, enjoy the read! :-)
