### ISSUE TITLE
Exposing Globaleaks in a normal browser via Https

### ISSUE THREAD

**Issue by fiyona** [globaleaks/GlobaLeaks#1943]
Hello,
I managed to locate the location of my certificates using my terminal.
Whats the best way to save them and upload them in globaleaks via Network settings

https://summitcl.com/

**Comment by evilaliv3** [comment]
thank you @fiyona.

no particular recommendation exists and the UI shuld guide you into the process.

GlobaLeaks is a volunteering project and also the documentation is handled that way; in case you find something missing i kindly invite you to contribute to the project by improving the documentation you find on our wiki: https://github.com/globaleaks/GlobaLeaks/wiki

please do not use the wiki for this kind of requests and evaluate to contact Whistleblowing Solutions that is a social enterprise we create specifically for being able to support enterprises like https://summitcl.com/

https://www.globaleaks.org/contact/
