### ISSUE TITLE
Design new login username in compatibily with multitenancy design

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1945]
The username requires to be unique by design, and currently globaleaks is creating the first users called 'admin' and 'receivers.

One possibility would be to ask the admin to chose the username during the wizard both for the admin and for the recipient and to provide an error if the username is already in use.
I do not like this solution that would require more user input as the start, to have to handle the issue of communicating to the user "you cannot call your user 'admin' because a user with username 'admin' is not existing.

For this reason i think we require a new login username that by design will be unique and i'm so proposing that we re-implement the same login macanism that we did at the first implementations: use the email as username.

The email in fact are unique by design.

**Comment by evilaliv3** [comment]
\cc @fpietrosanti @NSkelsey

**Comment by NSkelsey** [comment]
The tenant creation handler can take a user(name|mailaddress) with a password, to side step this issue when walking through the wizard. In the usage scenario for multi tenancy with provisioning, the user email is already known.

I do not find asking a user for their username to be too much input. Instead how about removing the context name section of the wizard? For the moment we could just name it `original`, that input doesn't really provide anything useful to the platform and at the point it is not clear where that is even displayed publicly.

![context](https://cloud.githubusercontent.com/assets/1095794/25086631/460f27cc-2369-11e7-8d67-6115172399fd.png)

Further commenting on the SQL, the email address is currently not unique, while the username is.

```sqlite3
CREATE TABLE user ( 
    id TEXT NOT NULL,
    creation_date TEXT NOT NULL,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    salt TEXT NOT NULL,
    deletable INTEGER NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'receiver', 'custodian')),
    state TEXT NOT NULL CHECK (state IN ('disabled', 'enabled')),
    name TEXT NOT NULL, 
    description BLOB NOT NULL,
    public_name TEXT NOT NULL,
    last_login TEXT NOT NULL,
    mail_address TEXT NOT NULL,
    language TEXT NOT NULL,
    password_change_needed INTEGER DEFAULT 0 NOT NULL,
    password_change_date TEXT DEFAULT '1970-01-01 00:00:00.000000' NOT NULL,
    pgp_key_fingerprint TEXT NOT NULL,
    pgp_key_public TEXT NOT NULL,
    pgp_key_expiration INTEGER NOT NULL,
    img_id TEXT,
    UNIQUE (username),
    FOREIGN KEY (language) REFERENCES enabledlanguage(name),
    FOREIGN KEY (img_id) REFERENCES file(id) ON DELETE SET NULL,
    PRIMARY KEY (id)
);
```

Can we just do username OR email? It expresses it self the same way in the auth scheme. Selecting user with uname (or email) and a matched password hash with salt results in valid authentication.

**Comment by evilaliv3** [comment]
The latest discussion on this topic lead to think that for at least the first multitenancy implementation objects like users will not be shared among tenants.

This will offer to perform particular simplification allowing to implement the minimal functionality of the multitenancy that will then be re-worked gradually to offer share objects.

For this reason it has been considered that the ```user``` table will contain a ```tid``` not requiring any change to the way the username behave with respect to current implementation in the stable branch.
