### ISSUE TITLE
Remove the simplified login feature

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1946]
The simplified login feature is a feature that impacts the design of multi-tenancy with custom unclean code.

As it is a feature that we supported just for one project (afrileaks) that even really worked as simplification i was already about to remove it months ago.

With the refactor https://github.com/globaleaks/GlobaLeaks/issues/1945 where we will probably revert the login to be based on the email as username i'm here suggesting to remove such a feature.

In addition it is worth it to mention that none of the professional users of globaleaks are using it as it is their natural concern to not list the name of their users. This concern is shared by the anonymous users as well.

**Comment by NSkelsey** [comment]
Thumbs up on the removal. A simple commit can do the removal and devel and a rebase can bring into `2.70.0`

**Comment by vodkina** [comment]
agree

**Comment by NSkelsey** [comment]
Code will come in `2.70.0`
