### ISSUE TITLE
Recipient is not received email alert of submission

### ISSUE THREAD

**Issue by strikerno19** [globaleaks/GlobaLeaks#1947]
**Current behavior**

- Recipient is not received email notification alert of submission but in list of submissions is complete 
- my company use email server from gmail for organization
- I'm configured two roles of user is Admin and Recipient
- User configured have email address and password of email address

**Expected behavior**

- How to configuration for email of recipient or user
- How to configuration when email notification is not active 

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

v2.60.144

**Browser:**

- [x] All browsers
- [ ] Chrome:  v45.0.1
- [ ] Firefox: v55.0.1
- [ ] Safari:
- [ ] Mobile Chrome:
- [ ] Other: 
- [ ] Not Applicable

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by NSkelsey** [comment]
Hi @strikerno19,

In newer versions of GlobaLeaks, you can test the administrators email setup to see if notifications are being sent via the "test mail" button in the administration interface under "Notification Settings" to see if the current configuration can emit emails to to other users.

For your version `v2.60.144` which is quite old, I suggest looking through the logs in `/var/globaleaks/logs/globaleaks.log` and looking for issues related to notifications or SMTP.

**Comment by vodkina** [comment]
You mention your company using email server from gmail for organization. Have you configured the relay service in advanced settings of gmail?

**Comment by evilaliv3** [comment]
Closing as probably outdated ticket.
