### ISSUE TITLE
Implement /changelog API serving CHANGELOG file and implement Admin UI its visualization

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1949]
Since we are planning on removing `username` in the mvp/multitenancy branch we need to handle the migration of the schema well and informing users that they now need to use their email address for logging in.

I am in favor of displaying a message on `/#/admin` and `/#/login`. I feel that admin that suddenly lose the ability to log in will cause a lot of unnecessary confusion. We can require user interaction in the migration that walks through each username + mail address combination with some messaging that explains what is happening.

Further in the admin interface it would be sane to display system messages on the first login of an admin into an updated system.

**Comment by NSkelsey** [comment]
From @evilaliv3: (that is also talking of too much topics in my opinion, already we have a ticket talking of the missing logs on the admin interface)

Needs partial resolution of displaying the changelog in the admin interface in accordance with #1493. Renaming the ticket to reflect the need for 2.70

1/2 is #/admin redirects to /#/login.
1/2 is displaying the changelog

**Comment by evilaliv3** [comment]
After analyzing the redirect implementation i've decided to implement it but just for the admin user.
Different decision for the recipient (that didn't had a /receiver link) and the custodian (that has not been used); preserving this would lead too extra code that makes total no sense. Sadly in fact the standard component of angular do no implement regexps so to simplify this apsect with smart code.

This ticket will from now on deals just with the implementation of a /changelog API where to serve the changelog, a /version API where to serve the version et similia.
Following the security trough obscurity model (that i do not support i guess we will have to maintain these apis accessible only by admin users).

**Comment by NSkelsey** [comment]
All that is left to do is decide and implement change log display. The solution we will go for will involve a new variable in the `config` table table or in the `user` table that denotes the latest version of the change log the admin has seen.

I prefer placing a `Text` column on the `user` because it lets us control the display for each admin instead of all admins on an instance or a tenant. This way we get the nice property that every admin gets the messaging displayed. In fact thinking, about it we can just use the `last-logged` in date along side a list of messages with the date that they were created. The first messages are the change log entries with the release dates attached.

The oldest message could contain the back log of changes and then all subsequent releases could just contain the changelog for that release.

'''python
events = [('release-date', 'message'), (x,y)
'''

Further on the home-screen of the admin interface we can leave a widget that lets the admin scroll through the message log sorted by date.

**Comment by fpietrosanti** [comment]
What about embedding a remote page that contain the changelogs and possibly other news?

Consider also the #marketing label ticket on changing all of the contact and text in the main admin page to reflect new contact flow.

**Comment by NSkelsey** [comment]
hmmmm,

It is a decent idea to allow other content that is dynamic and out side of the just GL system messages. If the page was an endpoint with structured JSON that had messages for instances that get rendered as Markdown, it could be nice, but the implementation complexity is a draw back.

I am not quite sure how to do it safely. It would be wisest to just include a link that takes you out of the platform. For example a simple solution like IFraming a page for example could lead to issues if there is malicious JS on the iframed page.

Let's keep this discussion focused on the changelog.

**Comment by NSkelsey** [comment]
The branch `feature/1949` tracks this commit. The final frontend UI is needed for resolution.

Some uncommitted screens:

![contact](https://cloud.githubusercontent.com/assets/1095794/25715883/57c351ae-30fd-11e7-8aad-92bac706bdf7.png)

The labeling will change and the update tab will probably disappear in accordance with the goal for a solution on updates @evilaliv3 and have talked about.

![dont-call-it-a-msg](https://cloud.githubusercontent.com/assets/1095794/25715917/7c66ffe2-30fd-11e7-8f61-084569295975.png)

**Comment by fpietrosanti** [comment]
Are also all changes, since the last version before globaleaks has been updated, displayed?
If i moved from a version of 12 months ago to today, probably there are many changes.

**Comment by NSkelsey** [comment]
I think if there are more than 10 releases between updates I will do some sort of summary with a mass hide and an easy way to page through the changes. The goal of the displaying this here is to alert an admin of a change to the system that they need to be aware of.

Clearly just displaying the change log doesn't quiet solve this. We could add a `critical` or `must-acknowledge` tag to some changes for the releases which have made API changes that the admin must be aware of it.

That could let us skip 50 display 1 critical, skip another 20 display another 1 critical and at least be sure that the admin read the 2 changelogs that changed the submission expiration scheme and removal of usernames.

**Comment by fpietrosanti** [comment]
We may also just show the full changelog of all past versions and highlight in a coloured way what is "critical"
