### ISSUE TITLE
Hidden service is not displayed on PrivacyBadge

### ISSUE THREAD

**Issue by vjrj** [globaleaks/GlobaLeaks#1950]
**Current behavior**
I get a empty onion url in the home privacy badge like:

`Then, copy and paste the following address into the Tor Browser:`

**Expected behavior**
Should be:
`Then, copy and paste the following address into the Tor Browser: something.onion`

Seems that after db update 36 in `client/app/views/partials/privacybadge.html` should use `onionservice` instead of `hidden_service` config variable.

**GlobaLeaks version:**

2.67.4 (from migration)

**Browser:**

- [x] All browsers
- [ ] Chrome:  v45.0.1
- [ ] Firefox: v55.0.1
- [ ] Safari:
- [ ] Mobile Chrome:
- [ ] Other: 
- [ ] Not Applicable

**Server Operating System and Version (if applicable):**
 
Ubuntu (16.04)

**Comment by evilaliv3** [comment]
Bug confirmed, going to issue a patch.

**Comment by evilaliv3** [comment]
Fixed. The fix will be available in few days starting from version 2.67.5.

**Comment by evilaliv3** [comment]
thanks @vjrj !
