### ISSUE TITLE
Implement job scheduler for Let'sEncrypt certificate renewal

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1966]
This ticket is to keep track of the implementation of a job scheduler for Let'sEncrypt certificate renewal.

The implementation should by design look forward for the possibility to renew multiple certificates as requirement for the multi tenancy and should keep track of failures and retries.

**Comment by NSkelsey** [comment]
By default the scheduler could run on startup and every three days after. The check would just be to see if the certificate will or is expired in 30 days. It will try twice to do the renewal using the Lets Encrypt ACME endpoint.

If the renewal fails, we will track it in memory and stop retrying after 30 failures. This corresponds with the moment the LE certificate becomes invalid.

After 15 failures or within 15 of days of the expiration a certificate expiration mail will be sent to the admin asking them to investigate the issue on the platform or if the certificate is a vanilla cert loaded manually to pursue a certificate renewal from their CA.

A thing I am not sure about is how to handle the case if the loaded certificates are expired. I think that the platform should not launch the HTTPS workers complain in the logs and in the user interface that the certificates need to be renewed. @evilaliv3 @fpietrosanti what do you two think?



Further this certificate

**Comment by evilaliv3** [comment]
fine for me to proceed this way @NSkelsey. good plan!

as for your last question i would say that we can yes just log that we are unable to set-it-up as the certificate is expired and downgrade to HTTP.

I think than that in case HTTP is used andthe connection is not a Tor connection we should show a different privacy panel informing that the connection is insecure and that any operation of the website could be subject to interception by a third party; this check could be implemented just in javascript checking that the domain is not an onion and the connection protocol is http (i think in addition we already have this checks functions). The topic is partially related to https://github.com/globaleaks/GlobaLeaks/issues/1664 even if here the feature i'm describing would have to be just a visual informative with an alternative text in the current privacy panel.
