### ISSUE TITLE
Implement admin notification of Lets'Encrypt certificate renewal failure

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1968]
This ticket is to keep track of the implementation of the admin notification of Let'Encrypt certificate renewal failure.

**Comment by evilaliv3** [comment]
The notification in case of Letencrypt adoption should be different from the one involved in https://github.com/globaleaks/GlobaLeaks/issues/1967 for manual certificate renwal and would have just to notify users about failures in renwal of the certificate.

I think in fact not necessary to warn users about certificates expiration as GlobaLeaks will implement automatic renewal; notification instead would be necessary in case the renewal will FAILURE.

Eventually we could evaluate to notify the users also in case of SUCCESS

**Comment by NSkelsey** [comment]
Frankly, I think that in the failure in the automated renewal process can just come through the normal admin exception mailer. This way we have a chance to address the problem which may be a service disruption issue or an incompatible change to the protocol. As the certificate passes the 15 day period it can pick up the normal expiration mails that warn about the certificate expiration. The language for the template just needs to be a bit generic to catch the two cases and we are covered.

I vote to close this ticket.

I like the idea of a successful renewal generating a short message that demonstrates success. Another option would be to store the successful renewal in a system event log that the administrators can view on the platform itself.

**Comment by evilaliv3** [comment]
I've not seen notifications of this kind in long time, better to recheck.
