### ISSUE TITLE
Analyze and fix the codebase for Python3 compatibility

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1974]
This ticket is to keep track of the activity related to the analysis and fix of the entire codebase by means of the python 2to3 helpers.

The helper allow to print automagically most of the corrections that should be applied in order to make the code python3 ready: https://docs.python.org/2/library/2to3.html

**Comment by NSkelsey** [comment]
There are [several pieces](https://docs.python.org/3/howto/pyporting.html) to achieving python 3 compatibility.

### Changes to the code base
The biggest change is the usage of unicode for all `str`s. The tool `2to3` produces a 4600 line diff of patches for our application where most of these changes remove the `u` from the `u'unicode_string'`.

Removing these lines will break our interactions with storm which means any changes that bring us near python3 compatibility have to not carefully not break current functionality.

### Package dependencies
There are some blocking packages that will prevent our transition to py3 that are not included in the ubuntu archive.

- [parsley](https://github.com/pyga/parsley/pull/46) -- implemented py3 but package may not be in repo
- [txsocksx](https://github.com/habnabit/txsocksx/issues/19) -- requires parsley with py3 
- storm -- we will deprecate the library first.

### No switch of interpreter

Its clear that when Canonical decides to completely drop python2 from the Ubuntu archive, GlobaLeaks will need to ready to execute with python3. Before that date, we have no need to change from py2 binaries or interpreters. 

### Backwards compatibility

We will need to ensure the proper function of GlobaLeaks running with python2 and python3 for the lifetime of this project. This means that

**Comment by NSkelsey** [comment]
`gl-admin` converts easily enough. Here's a sample.

```python3
--- gl-admin	(original)
+++ gl-admin	(refactored)
@@ -23,18 +23,18 @@
 
 def check_file(f):
     if not os.path.isfile(f):
-        print >> sys.stderr, "Missing file: %s" % f
+        print("Missing file: %s" % f, file=sys.stderr)
     try:
         with open(f, 'r'):
             pass
     except IOError as err:
-        print >> sys.stderr, err
+        print(err, file=sys.stderr)
         sys.exit(1)
 
 
 def check_dir(d):
     if not os.path.isdir(d):
-        print >> sys.stderr, "Missing dir: %s" % d
+        print("Missing dir: %s" % d, file=sys.stderr)
         sys.exit(1)
 
```

**Comment by NSkelsey** [comment]
The above commit 746cc69 provides almost all we need for 2to3 compat in that script. 

[Line 217](https://github.com/globaleaks/GlobaLeaks/commit/746cc69ffdb9e277db868f8267d7623ddfad1a60#diff-39b35dd1df954571d7813d3ae5e24a6cL217) of gl-admin needs to handle the type of the associated config object in a different way. However, when we move to py3 compat in modules config, we will end up having to map the current `unicode` type to a capability detecting shim that works like:

```python
try:
  ConfigItem.text = unicode
except NameError:
  ConfigItem.text = str
```

**Comment by evilaliv3** [comment]
Update: Storm has been replaced with SQLAlchemy.

**Comment by evilaliv3** [comment]
[txsocksx](https://github.com/habnabit/txsocksx) seems to be the last piece of py27 remained in the globaleaks codebased.

Its fix or removal is tracked by tickets:
- https://github.com/habnabit/txsocksx/issues/19
- https://github.com/globaleaks/GlobaLeaks/issues/2243

**Comment by NCommander** [comment]
Python 3 support (abiet experimental) landed on devel. Closing
