### ISSUE TITLE
Beautify the "Loading" message modal by adding at least drop-shadow.

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1977]
**Current behavior**

When waiting for requests to load the loading message that freezes the interface is ugly and it harms my good sense of taste.

__When browsing in Italian:__
![loader-window](https://user-images.githubusercontent.com/1095794/27121717-b6d2c0ca-50e8-11e7-9280-ce5d131a331f.png)

**Expected behavior**

Waiting for the application to resolve XHR requests should be a pleasant experience and the loading modal should look better and display something other than "Loading" when we are using other languages. The modal is often the first thing our users see when they interact with a GlobaLeaks site, so it should merit some care and style.

**Steps to reproduce the problem or feature illustration**

Throttle your connection and connect to a GL node or spend a year working on the project and you too will come to the conclusion that the modal needs to be improved.

**GlobaLeaks version:**

v2.67.5

**Comment by evilaliv3** [comment]
Closing as outdated.
