### ISSUE TITLE
Introduce AGPL 3.0 Additional Terms for modified globaleaks software distribution

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#1980]
Modified versions of the software are being re-distributed in violation of the AGPL 3.0 (https://www.gnu.org/licenses/agpl-3.0.en.html) and we had to issue FOIA requests to government agencies to force disclosure that it has been modified and force re-distribution of modified software to the end-user. 

This ticket is to improve the license of GlobaLeaks in order to apply additional terms as per AGPL 3.0 point 7-c:

c) Prohibiting misrepresentation of the origin of that material, or requiring that modified versions of such material be marked in reasonable ways as different from the original version; or

Point 7-c allow us to require that modified versions should be marked in a custom way and we want, following the existing additional terms of point 7-b, to use the Footer as the legally binding way to specify that the software has been modified, providing the download link for the modified versions of the material.

The following is a proposed additional terms:

```
           ADDITIONAL TERMS AS PERMITTED BY SECTION 7c OF AGPLv3
-------------------------------------------------------------------------------
This program was created by Hermes Center for Transparency and Digital Human Rights (https://www.hermescenter.org) and by Whistleblowing Solutions I.S. SRL (https://whistleblowingsolutions.it) under the name "GlobaLeaks" (https://www.globaleaks.org).

As permitted by section 7c of the AGPLv3, we require that modified versions of the material ("the software") should be marked in a reasonable way so that's clearly different from the original version.

Any modified material being re-distributed should have the program to displays a Modified Material Notice in each user interface screen with an explicit statement that includes "This server is running a modified version of GlobaLeaks software. Download here the modified version of the source code."

The Modified Material Notice must be clearly visible with size of the fonts and icons proportionate to the user interface being used.

The Modified Material Notice must be in the language used by the interface being used.

For works containing this program or any covered work, each interactive user interface must include a prominent and conveniently accessible feature for the display of Modified Version Notice. 

When users click on the "Download here the modified version of the source code" (or the equivalent localized language version of the sentence) it must direct the user to an archive file containing the modified version of the source code or to an intermediate web page containing all the direct download link of the modified version of the source code.

Any party that wishes to remove the Modified Material Notice from the user interfaces is required to obtain written consent from Whistleblowing Solutions I.S. SRL.

The purpose of this non-profit social enterprise is to support the development of the GlobaLeaks software while maintaining it entirely as free software available for public interests purposes pursuing the social goal of protecting whistleblowers and increasing transparency.
```

**Comment by NSkelsey** [comment]
Good stuff, Here are 2 quick edits.
FROM:
`Download here the modified version of the source code.`
TO:
`Download the modified version of the source code`

FROM:
`The Modified Material Notice must be in the language used by the interface being used.`
TO:
`The Modified Material Notice must be in the same language as the rest of the interface.`

**Comment by NSkelsey** [comment]
For reference here is securedrop's clause:

![securdrop-disclaimer](https://user-images.githubusercontent.com/1095794/27545026-10a0e8ac-5a8f-11e7-92f6-651e74c66dd1.png)

**Comment by hellais** [comment]
So this is effectively making GlobaLeaks not free software anymore? 😢

**Comment by fpietrosanti** [comment]
Those modification are "additional terms" not adding any further rights other than the one already defined by AGPL 3 in section 7 and fully qualify as free software in compliance with FSF made AGPL 3.

In turn those additional terms as explicitly defined and allowed per 7b/7c of AGPL 3.0 provide operational instruction to defend the freedom of the software, specifically the existing rights that AGPL provide.

Sent from mobile

**Comment by fpietrosanti** [comment]
I've been thinking that this could be further extended to include an automatic waiver, assuming proper behaving of who re-distribute the modified software in order to contribute back to the project.

Who re-distribute the software may behave in a proper way as a project contributor by following on specifically listed operational guidelines such as:

1. open up related github issues for the features
2. get feedback from the developers community on the implementation on the issues
3. implement the modifications respecting the security, quality and configurability guidelines of the software
4. send proper git pull requests to the project
5. explicitly ask for code review then following code review suggestions coming from other developers
6. adjust the code so that the software could be available to the project for official inclusion, representing a community contribution

**Comment by fpietrosanti** [comment]
Actual modifications committed:
https://github.com/globaleaks/GlobaLeaks/blob/master/LICENSE#L713

**Comment by NSkelsey** [comment]
I do not think we can effectively enforce changes to come through a certain channel with the terms of a license. Further I do not feel that specify how the software must be modified is in the spirit of the GPL. The spirit of the contributions we want to the code base are voluntary ones. I think it would be very strange for a open source license to attempt to compel contributions in a certain form. I've certainly never seen anybody try it before and I do not think we ought to write a license to attempt to it.

Commit with the modifications b1c3673c671c34009e92da3ba87f2c8f15441718

**Comment by fpietrosanti** [comment]
@NSkelsey it's just not possible to impose or to compel how software must be modified, that would be an obligation against basic AGPL section 1 and section 5. What AGPL do allow in section 7 for additional is instead what "who re-distributed modified sources" must mention and where, and that's fair enough.

Any volunteers is untouched by those terms because it would surely work in a community oriented way and it's not willing to engage in re-distributing modified globaleaks, instead wish to have their contribution to be part of the official software edition.

However it does touch commercial companies that wish to modify the sources without contributing back to the community that are further interested committing AGPL violations for an abusive competitive advantage. 

That's already fully fixed by the current additional terms.

What i'm saying is that we may further provide those commercial companies re-distributing modified versions of GlobaLeaks, a way to avoid putting the notice in the footer IF they behave exactly like a volunteer would do, in a community oriented way, but then the behaviour must be clearly defined.

**Comment by NSkelsey** [comment]
@fpietrosanti let me see if I understand the idea. In the cases where written permission is acquired from Whistleblowing S.R.L, that permission will come with the stipulations that changes contributed by the requesting organization must be submitted back to the project through the channels which we use to improve the product.

So that written permission will only be granted with a contract that dictates behavior of the organization adapting the software.

It is conceivable if a group wants to remove the footer, they could just offer to pay for the right.

**Comment by fpietrosanti** [comment]
@NSkelsey Whistleblowing Solutions I.S. SRL, by statutory obligations, cannot produce private knowledge but only public outcome of knowledge.
So yes, if a company wish to re-distribute modified sources without a mention in the footer that's modified could ask WBS SRL for permission to do so, and WBS will guarantee (by it's statutory commitment) that the modifications will be back publicly into GlobaLeaks software (and that any money paid to WBS will be only invested in the GlobaLeaks Project, with no private dividend distribution possibly at all). 

What i would like to further extend is that there should be "no need to ask WBS permission to remove the footer notice for re-distribution of modified software" as long as "the subject doing the re-distribution of modified sources is behaving in a way that's really community oriented and focused on having those modifications back into the main software release".

And i feel that that's a kind of innovative approach to the licensing that, given the rights by 7/c to require specific way to "mark" modified version of the software, dictate a set of fair and reasonable rules related to which condition the "mark" should be present or not, and what it should be.

**Comment by fpietrosanti** [comment]
done
