### ISSUE TITLE
Tor browser labels password fields in the interface as insecure.

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1984]
**Current behavior**

The latest version of firefox that ships with the Tor browser does not disable the "Warning insecure transport .  . ." dialogue for onion services. As an end user of the tor browser we are going to have to deal with this issue.  

**Expected behavior**

In my opinion the Tor browser ought to disable the dialogue in their browser patches.

**Steps to reproduce the problem or feature illustration**

Connect to an instance with the latest tor browser and you will see:

![login-insecure](https://user-images.githubusercontent.com/1095794/27395660-da5b9bca-56b0-11e7-92fc-10c04ab1bda8.png)

**Browser:**

TorBrowser v7.0.1

**Comment by NSkelsey** [comment]
The Tor browser labels all HTTP sites as insecure if a certificate is attached. It seems that digicert has only issued two onion certificates in the past; one to Facebook and the other to Protonmail.

The setting `security.insecure_field_warning.contextual.enabled` within Firefox controls the setting and can be disabled manually. At this time there is no, ticket in trac.torproject.org

Another example from riseup:

![insecure-here](https://user-images.githubusercontent.com/1095794/27544273-e9354f94-5a8c-11e7-9714-94192ed18cd7.png)

**Comment by NSkelsey** [comment]
From my read of the discussion on trac.torproject.org there is not much we can do but wait for a solution.

**Comment by pastly** [comment]
For those following along at home, Tor's ticket is [#21321](https://trac.torproject.org/projects/tor/ticket/21321).

**Comment by NSkelsey** [comment]
It looks like Digicert is [offering certificates for .onion domains](https://www.digicert.com/blog/ordering-a-onion-certificate-from-digicert/) at a negotiable, potentially reasonable price. The secure drop project has already had some of their users acquire [these certificates on their own](https://github.com/freedomofpress/securedrop/issues/1605). This may be a great solution for getting around this dialogue and adding another layer of defense to the content of traffic in transit.

**Comment by NCommander** [comment]
This was fixed upstream, and I confirmed it's not a problem with the latest Tor Browser, closing.
