### ISSUE TITLE
Failure in serialization of contexts and recipients images

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1986]
It has been reported a failure in the serialization of contexts and recipients images.

Images appear to be exported as empty on the user interface while appear to be loaded correctly on the user interface.

**Comment by fpietrosanti** [comment]
Ref https://forum.globaleaks.org/t/context-selector/88/8 @Taipo

**Comment by evilaliv3** [comment]
The bug has been verified by me and appear to be present since the rewrite in the serialization of the API for optimizing fetch of resources: https://github.com/globaleaks/GlobaLeaks/commit/faafb114

The bug affects all software verisons starting from 2.67.6

A fix has been already identified and i'm working on the creation of a patch that will be release in the upcoming release expected to be released by today: 2.80.0

\cc @Taipo @fiyona @fpietrosanti @NSkelsey
