### ISSUE TITLE
Detect and warn user about lockout from the platform when disabling HTTPS

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1987]
**Current behavior**

Currently when HTTPS is disabled from an HTTPS connection, the interface is frozen and the user is asked to reconnect to the platform.
![disabled](https://user-images.githubusercontent.com/1095794/27682692-d738924a-5cc3-11e7-9d2b-44d8123b9655.png)

**Expected behavior**

With @evilaliv3 we decided it would be much better to warn the user right before they perform this action. And present to them a dialogue with the following content
```
Warning! You are about to disable access to the platform over HTTPS. 
Your current connection is using HTTPS. This means you will immediately
 lose access to the platform if you cannot connect to it from the following 
URLS:
    - http://fake.platform.globaleaks.org
    - http://thirteenchars1234.onion
```

**Comment by evilaliv3** [comment]
Implemented and shipped in current stable release (2.70.10).

Closing the ticket as addressed.
