### ISSUE TITLE
Detect Tor failures with automatic setup retries

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1994]
Currently when the platform is expected to start Tor and it fails globaleaks discards the error silently, not performing any retry at run-time and avoiding to notify the user of the failure.

This ticket is to discuss the implementation of the relevant features for:
- identifying failures in the actions performed for setuping Tor (startup/reactivations + retries)
- online re-checking that Tor is running and the hidden service is setupped (thinking to implement features that would scale having multiple tenants)
- logging of failures conditions

**Comment by fpietrosanti** [comment]
It would be a natural extension of #1989 that do check the status of correct loading of TorHS.

By issuing a periodic refresh of the key with an UPDATE_ONION it's possible to have a watchdog of the Tor process by an integrity check of the Tor HS descriptor loading functionality

**Comment by evilaliv3** [comment]
I agree.

UPDATE_ONION is currently not an option of txtorcon nor in the version we are using (0.15.1) nor in the developmen one.

We may need to implement it by ourself as a mock for the moment, but this should not be that difficult.

@meejah do you have any valuable hint on this topic of monitoring of correct setup and rechecking of correct configuration at runtime?
since we started using ephemeral hidden services w are now worried that their configuration could be lost at runtime and be in general less resilient to the configuration via /etc/tor/torrc

thank you so much :)

**Comment by evilaliv3** [comment]
Actually @fpietrosanti UPDATE_ONION is something that does not exist :)

we should in place us ```GETINFO onions/current``` ```GETINFO onions/detached``` commands to get information about hidden services created via the controller (https://trac.torproject.org/projects/tor/ticket/6411)

That is what at least is told in the Tor changelog for 0.2.7.1: https://raw.githubusercontent.com/torproject/tor/master/ChangeLog

**Comment by NSkelsey** [comment]
An interesting observation is the interaction between, ADD_ONION and the current control connection. 

IIRC Tor will serve the hidden service for as long as the control connection that issued ADD_ONION remains open. This means that Globaleaks is brought down and restarted, the Tor process no longer serves the onion address. After a quick check, this is in fact the [case](https://gitweb.torproject.org/torspec.git/tree/control-spec.txt#n1461).

Right now Tor failures are logged like so:

```
2017-07-04 15:49:06+0200 [-] [I] Starting up Tor connection
2017-07-04 15:49:06+0200 [-] [E] Tor daemon is down or misconfigured . . . starting up anyway
```

We correctly chose to not block the applications startup because Tor is not there, but we could for example block the serving of content until either the Tor setup is fully finished or in a failed state.

I find the idea of simply retrying to connect to Tor unreliable and unpredictable. 


To start we can improve the admin's awareness in the admin interface about the 'Status' of tor like we have for HTTPS. Further we can improve the verbosity of the connection establishment in our logging about the state of the Tor process in the backend. For example, we could ping GETINFO onions/current ever 10 minutes or so to determine if the connection is alive. This would help with other scheduled jobs *like the exit relay ip list) that rely on a Tor connection avoid trying to connect to a broken interface.

**Comment by meejah** [comment]
You can pass `Detach=True` to make an `ADD_ONION`-added service outlive the control connection.

Are you finding that the control-connection "goes away" periodically, even though tor is running? Are you using TCP or Unix control-connection?

**Comment by evilaliv3** [comment]
Thank you @meejah for the prompt support as usual.

No actually we have not experienced any bug till now and we are just guessing on the stability of:
- supposing the ephemeral service is setupped "today" what are the guarantees that it will still configured tomorrow? (i mean i expect that sometimes to internally fails and restart eventually rereading the torrc; but what about the configurations done with the tor control port?
- what are the mechanisms that  you suggest to put in place in order to verify periodically that things are working?

**Comment by evilaliv3** [comment]
p.s. actually we are using the unix socket.

we found that more easy because it is protected by default with the implementatio of the cookie in the default tor configuration and so for allowing GlobaLeaks to access it we just need it to be in the debian-tor group of the os.

**Comment by meejah** [comment]
If you used `ADD_ONION` in the normal way, the service will stick around until the control connection goes away. If you re-connect, you'll have to re-add the hidden-service.

`Detach=True` might work for your use-case. You can always confirm your service is still there with `GETINFO onions/current` (or `GETINFO onions/detached` if you used `detach=True`) as suggested above. I don't believe there's any EVENTs that signal a service "going away".

**Comment by meejah** [comment]
As far as showing status to the user, it might be useful to say how many `PURPOSE=HS_SERVICE_INTRO` and `PURPOSE=HS_SERVICE_REND` circuits are currently active...?

**Comment by evilaliv3** [comment]
That is a valid debug information but i think i was not clear with the doubt;

as far that you know if one lunches Tor today, configure it stateless via the control port, how many are the probabilities (just in terms how much confident you are for your experience ) that 1) during time it would not loose the configuration 2) which commands/sequence of checks and retries would you implement on top of txtorcon in order to see that all is alive and eventually restart it?

**Comment by meejah** [comment]
I have never seen a control connection randomly vanish (without the underlying Tor dying).

I think any command at all would be fine to see if Tor is still alive and happy -- so a `GETINFO onions/current` would probably be good if you want to "for sure confirm" that your service is still there.

**Comment by NSkelsey** [comment]
Really helpful information @meejah, thank you. 

On shutdown @evilaliv3 and I are considering removing our shutdown logic for a simple closing of the control connection. This way we just let Tor handle killing the Onion Service 

In the control spec for ADD_ONION however there is this slightly ambiguous sentence:
> It is the Onion Service server application's responsibility to close
  existing client connections if desired after the Onion Service is
  removed.
[source](https://gitweb.torproject.org/torspec.git/tree/control-spec.txt#n1548)

This specifically uses 'client connections' to mean IP streams or does it refer to client Circuits routed through Tor. If it is the latter, that would suggest that we must iterate through active circuits and kill them via the control port.

**Comment by evilaliv3** [comment]
With @NSkelsey we analyzed the issee and identified a good approach for the handling of this issue:

The Tor configuration couldbe implemented by a LoopingCall object called OnionService implementing the following features:
- setup at startup
- re-configuration on failure

In addition we identified the possibility to check on the unix socket file in order to optimize the process and avoid to log unlimited lines of failures on the log file.

**Comment by evilaliv3** [comment]
For me this ticket is handled;

I remains open the question by @NSkelsey  to @meejah  and eventually the possibility to handle notification/alerting to the user via email and via the web interface but i would suggest to postpone both to eventual specific tickets.

**Comment by meejah** [comment]
I'm pretty sure what the spec means by "client connections" is the actual connection to the service itself (e.g. Web connections) which could be long-lived (e.g. WebSocket, pipelining) and so the service can shut those "nicely" before quitting or removing the service. You should not have to mess with tor circuits.

Note that if you use the new `txtorcon.Tor` object as the top-level txtorcon thing, you can call `Tor.quit` and it will both close the control connection nicely and kill the underlying running tor if appropriate (i.e. if you created the `Tor` instance with `txtorcon.launch()`).
