### ISSUE TITLE
Admin/users does not display loaded public keys correctly 

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#1995]
**Current behavior**

`admin/users` does not parse public keys correctly. It looks like:
![screenshot_2017-07-04_16-38-42](https://user-images.githubusercontent.com/1095794/27834455-5c347538-60d7-11e7-90d0-b0f202fd5579.png)

**Expected behavior**

It should look like this:
![screenshot_2017-07-04_16-39-04](https://user-images.githubusercontent.com/1095794/27834451-58406d24-60d7-11e7-8835-4d99f68997ce.png)

**GlobaLeaks version:**

v2.70.2

**Browser:**

Chromium 58

**Comment by NSkelsey** [comment]
Found another state:

![derp](https://user-images.githubusercontent.com/1095794/27866268-f01d009e-6195-11e7-8656-7917486da329.png)

**Comment by NSkelsey** [comment]
This issue only exists for in scope changes to the PGP interface. A single refresh where the underlying model is reloaded in the UI places the correct values into the fields below. Further the issue only exists within the Admin > Users and Admin > Receivers interfaces. In User/Preferences the pgp key display is functioning correctly.

There was a commit at some point that solved this issue but after some digging I still cannot locate it.

**Comment by evilaliv3** [comment]
Cloasing as probable outdated ticket now solved.
