### ISSUE TITLE
Implement a Content Security Policy

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#1998]
This ticket is to discuss and implement a Content Security Policy within the GlobaLeaks framework in order to allows a subset of the possible method for loading resources avoiding in particular the inclusion of remote ones.

Current [application security design document](https://docs.google.com/document/u/1/d/1SMSiAry7x5XY9nY8GAejJD75NWg7bp7M1PwXSiwy62U/pub) defines the usage of just one directive, the ```upgrade-insecure-requests``` that is actually  and missing on microsoft browser that is anyhow in the recommended good practices in relation to HTTPS and in addition to HSTS.

From a first analysis of https://content-security-policy.com/, in addition to this i would like to propose to allow only:
- enable ```'self'``` resources that allow the browser to load resources on the same domain
- enable ```data:``` resources that allow the browser to load base64 resources

the first is the optimum minimal one while the latter is required for most of our optimizations and thus required.

this would offer the application the following benefits:
- no unintentional external tracking or possible trackers (external fonts) would be possible
- it would not be possible to intentionally inject external resources

**Comment by evilaliv3** [comment]
In order to implement the above it would be necessary to add a new header (multiple content security policies headers can exists and should exist):
- ```Content-Security-Policy: default-src 'self' data:```

In addition the following edits are necessary:
- Angular should be configured in a specific way where it will avoid to use some optimizations and perform only actions compatible with csp and thus avoiding to use inline scripts (https://docs.angularjs.org/api/ng/directive/ngCsp)
- Convert our code using inline-scripts to use data URI

**Comment by evilaliv3** [comment]
From a more deeper analysis 'https:' is the good way to go for being sure that it should be possible to include only HTTPS resources when HTTPS is enabled.

This as the ```upgrade-insecure-requests``` setting that is missing since the Tor2web removal should be added only only on HTTPS connection while the others should be present also on HTTP/Tor connections.

**Comment by NSkelsey** [comment]
It is worth noting that when the `allow_iframe_inclusion` flag is set the Content-Security-Header is set to `same-origin`. In this case, we just want to add this rule to the policy - not replace it.

**Comment by evilaliv3** [comment]
coud you elaborate nick?

the two are two different headers, one is the policy for being included inside an iframe and one is a content for including from globaleaks external resources (and in general resources)

**Comment by NSkelsey** [comment]
The CSP header `frame-ancestor` [obsoletes the](https://www.w3.org/TR/CSP11/#frame-ancestors-and-frame-options) `x-frame-options` and can be used to specify the behavior of browsers when interpreting things like `iframes`

**Comment by evilaliv3** [comment]
i see. yep we could by default block and conditionally based on allow_iframe_inclusion allow them in the same if condition that we already implement for the X-Frame-Options

**Comment by evilaliv3** [comment]
Closing as implemented with rank A+ on observatory.mozilla.org

https://observatory.mozilla.org/analyze/try.globaleaks.org

![screenshot-observatory mozilla org-2019 08 14-17_00_16](https://user-images.githubusercontent.com/217034/63031887-17d98480-beb5-11e9-84e7-84725f74eaf5.png)
