### ISSUE TITLE
Expose configured hostname in the public node variables

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2002]
**Current behavior**
Actually when a GlobaLeaks platform is internet exposed it uses https, but there's no way to check it out which is the hostname (if any) it's configured for from standard HTTP or Onion-reachable interface

**Expected behavior**
This ticket is to add to the public node variable the public hostname configured on GlobaLeaks, if configured.

**Comment by evilaliv3** [comment]
@fpietrosanti: this is already in place for both the public hostname and the tor hidden service.

The ticket could be simply closed.
