### ISSUE TITLE
Installing on unsupported platform trigger an infinite loop from install-globaleaks.sh

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2006]
**Current behavior**
When a user try to follow installation instruction from https://github.com/globaleaks/GlobaLeaks/wiki/Installation-Guide on a unsupported platform (in this case an Ubuntu 16.10), it trigger an infinite loop.

The command triggering the infinite loop is:
curl https://deb.globaleaks.org/install-globaleaks.sh | bash

**Expected behavior**
The software should abort the installation, reporting that's not a support platform and that shall be executed manually?

**Comment by NSkelsey** [comment]
@fpietrosanti can you please post the output [of the loop](https://github.com/globaleaks/GlobaLeaks/blob/devel/scripts/install.sh#L42-L48) (which I assume is this one) as well as the output for the following commands on 16.10:

```bash
> lsb_release -is
> lsb_release -cs
```

**Comment by fpietrosanti** [comment]
root@parcogiochi:~# bash -x install-globaleaks.sh 
++ id -u
+ '[' '!' 0 = 0 ']'
+ ASSUMEYES=0
+ EXPERIMENTAL=0
+ '[' 0 -eq 1 ']'
+ LOGFILE=./install.log
+ DISTRO=unknown
+ DISTRO_CODENAME=unknown
+ which lsb_release
++ lsb_release -is
+ DISTRO=Ubuntu
++ lsb_release -cs
+ DISTRO_CODENAME=yakkety
+ echo 'Detected OS: Ubuntu - yakkety'
Detected OS: Ubuntu - yakkety
+ echo yakkety
+ grep -vqE '^xenial$'
+ echo 'WARNING: The up-to-date required platform is Ubuntu Xenial (16.04)'
WARNING: The up-to-date required platform is Ubuntu Xenial (16.04)
+ '[' 0 -eq 0 ']'
+ true
+ read -p 'Do you wish to continue anyway? [y|n]?' yn
Do you wish to continue anyway? [y|n]?

**Comment by slglayglay** [comment]
An infinite loop of something like:
"Please answer..Yes"

**Comment by slglayglay** [comment]
I had the issue on Debian 9

**Comment by evilaliv3** [comment]
Solved removing from the suggestion of the install guide the "curl | bash" combination as it does not allow the user to pass further arguments to the script.
