### ISSUE TITLE
Installation script should check that the port where globaleaks want to bind are free

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2007]
**Current behavior**
Actually when the software install, it may fail if the port where globaleaks must bind, are already used by another process.

**Expected behavior**
This ticket is to embedd into the installation script a check that the ports that globaleaks want to use by default are free to use and fail with the right message if they are not.

**Comment by NSkelsey** [comment]
In our installation documentation we ask to install GlobaLeaks on an new ubuntu machine, so we have never considered it important to check that the ports are free. I am okay with changing that recommendation we just have to consider other consequences as well.

An alternative is that we can #2010 and this ticket with a failure within the backend startup if the ports are not bind-able. This is a  better solution than checking from bash and then again in the backend.

However, in the past with @evilaliv3 we considered it not a fatal error if one of these ports is not bind-able because the platform could still be reachable from Tor, another port, etc, etc, so the behavior up until now is intentional.

**Comment by fpietrosanti** [comment]
@NSkelsey with #2010 implemented, the install process will fail anyhow unless also this ticket #2007 is implemented (because globaleaks will fail to start, so the installation of the package will fail). 

Btw i'd start considering Tor as an additional transport, on top of standard HTTP/HTTPS transport, not the default one, as the support experience say us that most of the people don't understand/know what tor is.

**Comment by evilaliv3** [comment]
I agree with the general idea but not sure the right path is to have this check inside the setup script.

In my opinion is the application that has to do it and will have anyhow the need to do it.

In general anyhow if we move for implementing this let's keep it simple and let's go for the decision that ports are not configurable and the following exact ports should be available to GlobaLeaks:
- 0.0.0.0:80
- 0.0.0.0:443
- 127.0.0.1:8082
- 127.0.0.1:8083

the assessment can be done with ```timeout 1 bash -c 'cat < /dev/null > /dev/tcp/0.0.0.0/443'``` by chaning the ip and port

**Comment by fpietrosanti** [comment]
For checking for open ports, it would be better to check with netstat that gives out the listening ports from a kernel perspective rather than actively connecting to a port (see https://stackoverflow.com/questions/21897119/shell-script-how-do-i-determine-if-a-port-is-in-use-e-g-via-netstat or https://serverfault.com/questions/36334/bash-snippet-to-see-if-something-is-listening-on-a-port)

Btw the configurability of the ports doesn't matter at installation time (from the installation script perspective), as it's something eventually doable after the installation time (we can also prevent that, but i'm confident there will be some complex-advanced scenario with reverse proxy when it will be needed to change it)

**Comment by NSkelsey** [comment]
I agree with @evilaliv3 that if the check is done, it should be done in the setup script.

The goal of the installation script as it is written is to bring the machine to the point where `apt-get install globaleaks` is run.

The function for the setup script could be simply (interpreted from results above as):
```bash
function is_tcp_sock_free {
    netstat -tlpn 2&>/dev/null | grep -e $1 -q

    if [ $? -eq 1 ]
    then
        echo yes
    else
        echo no
    fi
}

is_tcp_sock_free '0\.0\.0\.0:80'
is_tcp_sock_free '0\.0\.0\.0:443'
is_tcp_sock_free '127\.0\.0\.1:8082'
is_tcp_sock_free '127\.0.\.0\.1:8083'

```

However, the current tail of the installation script could be improved nicely with some simple output checking to see if the tor hidden service has come online. Waiting with a while loop would help output more interesting information at the end of the script.

Currently we see:
```
echo "GlobaLeaks should be reachable at http://127.0.0.1:8082"
```

We could instead check for the configuration of the onion service.

**Comment by fpietrosanti** [comment]
@NSkelsey for the last item ticket #2008 on referring the http uri with server IP

**Comment by NSkelsey** [comment]
It is also possible to specify the sockets used by GlobaLeaks as a [socket dependency](https://www.freedesktop.org/software/systemd/man/systemd.socket.html#) via systemd. 

If they are not available startup will fail and the application during startup will fail with errors related to the already bound socket.

**Comment by fpietrosanti** [comment]
Any additional check detecting and communicating in advance failures, are good checks!

**Comment by fpietrosanti** [comment]
If the software listening is globaleaks, the check should pass

**Comment by NSkelsey** [comment]
Failure of the install script in these cases looks like this:

```bash
root@ip-172-30-0-42:/home/ubuntu# ./install.sh 
Checking preliminary packaging GlobaLeaks requirements
 + apt-key requirement met
 + apt-get requirement met
Detected OS: Ubuntu - xenial
Running: "apt-get update -y"... SUCCESS
 + curl requirement met
 + netstat requirement met
Running: "is_tcp_sock_free_check 0.0.0.0:443"... SUCCESS
Running: "is_tcp_sock_free_check 127.0.0.1:8082"... SUCCESS
Running: "is_tcp_sock_free_check 127.0.0.1:8083"... SUCCESS
Running: "is_tcp_sock_free_check 0.0.0.0:80"... FAIL
Ouch! The installation failed.
COMBINED STDOUT/STDERR OUTPUT OF FAILED COMMAND:
For Professional Support requests please visit: https://www.globaleaks.org/contact/
Please report encountered issues to the Community Forum at https://forum.globaleaks.org
```

Commit 401c99186085d6a5734a4373a8d41b4c021d65c5 contains a fix for last_status for successful installs that will break the statistics script running on deb.globaleaks.org. \cc @fpietrosanti

**Comment by fpietrosanti** [comment]
It would be useful to check that it's not globaleaks, already listening on those ports and to output a user feedback explaining what's the problem ("Port XX is occupied by another process")
