### ISSUE TITLE
Installation script should report the accessibility of the platform the IPs of the server rather than 127.0.0.1:8082

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2008]
**Current behavior**
Actually, when installing GlobaLeaks, at it's end the install script say:

"GlobaLeaks should be reachable at http://127.0.0.1:8082"

**Expected behavior**

The install script must report that GlobaLeaks is accessible on http://IP_OF_THE_SERVER without any references to 127.0.0.1 or port 8082 (that are now just internal resources)

**Comment by evilaliv3** [comment]
The following one liner could be used in order to retrive all the ip of the local interface of the system:
```ifconfig | sed -En 's/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'```

The install script should just print all the possible combination of the local IPs with the port 80.

**Comment by NSkelsey** [comment]
The implemented solution in dbb0ee4 will only work for machines whose issued IP is publicly routable. Every VPS provider I've encountered routes a public IP to an internal IP attached to their customers server. Maybe in local networks this might be somewhat useful.

We could for example issue a request that hits an external service to find the publicly routable IP.

```bash
> curl canihazip.com
```

There was a solution published earlier by @fpietrosanti that connected to google.com and read the address of the socket. This is the solution that I think meaningfully resolves this ticket. Its a quick change.

**Comment by evilaliv3** [comment]
I would suggest to keep for the moment the current implementation without adding an additional request to an external service.

In addition let's consider that while the current implementation expese IPs address on which the platform is surely reachable, while using canihazip.com that could be not true; in fact:
- the ip usd for outgoing connections is not always the same of the one for incoming connections
- there could be firewalling rules on the incoming connections that could prevent that.

**Comment by NSkelsey** [comment]
It is definitely not possible to use a local conn to discover the external IP. The router that switches the packet from the public net into the local net is going to be the only point where the public IP is reported.

```python
In [0]: import socket
In [1]: socket.create_connection(('deb.globaleaks.org', 80)).getsockname()
Out[1]: ('10.9.20.13', 33014)
```

**Comment by fpietrosanti** [comment]
The output of this is a facilitation to let the user make "copy & paste" into the browser.
We need to assume that the admin knows the IP address of the machine where the installed the server, as he connected to the system and executed the install script.

**Comment by evilaliv3** [comment]
Yes i agree and suggest to keep what we just added that report real information with a simple implementation.

Funny alternatives but leaking are:
```
dig +short myip.opendns.com @resolver1.opendns.com
dig @8.8.8.8 -t txt o-o.myaddr.l.google.com
```
