### ISSUE TITLE
Cannot send notification email

### ISSUE THREAD

**Issue by doudoulong** [globaleaks/GlobaLeaks#2011]
**Current behavior**

Got an "Error" after clicking on "Test the configuration" and no notification was sent.

**Expected behavior**

Send notification email through the email account I set.

**Steps to reproduce the problem or feature illustration**

I left "SMTP name" field blank because I don't know what to fill. The "SMTP email address" field and "Username" field are both username@gmail.com. SMTP server address is smtp.gmail.com. Port is 587. Transport security is SMTP/TLS. 

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

**Browser:**

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
Thanks for the bug report @doudoulong;

we will try to retest this configuration and get back to you when done.

**Comment by NSkelsey** [comment]
Hi @doudoulong;

The smtp username is just the name that appears as the sender next to their email address.

I can confirm it is possible to use smtp.gmail.com to send mail from globaleaks. In the process of testing this setup I have discovered some issues with our SMTP configuration.

Unfortunately you will need to disable "Anonymize outgoing connections" in the network settings channel and make some configuration that will use old unsafe configuration. If you must use the SMTP from google now, you will need to allow "Less secure apps" and downgrade your connection to SSL connecting via port 465. Alternatively you can wait for us to close this ticket and issue you an update.

What follows below is for the project devs.

---

Google's SMTP servers are always going to block Tor exit ips for connection to their servers, so disabling tor SOCKS usage must be done.

There is an issue with the stored values/defaults in [config_desc](https://github.com/globaleaks/GlobaLeaks/blob/08b9ad0/backend/globaleaks/models/config_desc.py#L62) and the string checks in [utils/mailutils.py](https://github.com/globaleaks/GlobaLeaks/blob/08b9ad0/backend/globaleaks/utils/mailutils.py#L124)

`'security': Unicode(validator=shorttext_v, default=u'TLS'),`

However we only ever look for the presence of the string 'SSL':

`if security == "SSL"`

Investigating the reported issue above using googles [recomended settings](https://support.google.com/a/answer/176600?hl=en) against there different endpoints we get some interesting results. 

With authenticated SMTP aspmx.l.google.com on port 25:

```
2017-07-18 10:31:10+0200 [-] [D] Attempting to send test email to: xxxxxxxxxx@gmail.com
2017-07-18 10:31:10+0200 [-] [D] Sending email to xxxxxxxxx@gmail.com using SMTP server [aspmx.l.google.com:25] [TLS]
2017-07-18 10:31:10+0200 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory instance at 0x7f96e1524878>
2017-07-18 10:31:11+0200 [-] [E] SMTP connection failed (Exception: 502 Server does not support Client Authentication schemes [CRAM-MD5, LOGIN, PLAIN]\n<<< 250-ENHANCEDSTATUSCODES\n<<< 250-PIPELINING\n<<< 250-CHUNKING\n<<< 250 SMTPUTF8\n)
2017-07-18 10:31:11+0200 [-] [D] [Failure instance: Traceback (failure with no frames): <class 'twisted.mail.smtp.AUTHRequiredError'>: 502 Server does not support Client Authentication schemes [CRAM-MD5, LOGIN, PLAIN]\n<<< 250-ENHANCEDSTATUSCODES\n<<< 250-PIPELINING\n<<< 250-CHUNKING\n<<< 250 SMTPUTF8\n\n]
```

With SSL (this is the requested TLS port) on smtp.gmail.com on port 587 the connection hangs.

```
2017-07-18 10:37:49+0200 [-] [D] Attempting to send test email to: jeb4pres2016@gmail.com
```


With SSL on smtp.gmail.com on port 465 we get something interesting

```
2017-07-18 10:37:21+0200 [-] [E] SMTP connection failed (Exception: 534 5.7.14 <https://accounts.google.com/signin/continue?sarp=1&scc=1&plt=AKgnsbsk
5.7.14 SU4tAzSoT_j2vu3Nzb5uTYC6rmadITXw1yqZ_Ivq_mZFQtI2aVC7uaelRlHO51L_-SU1LI
5.7.14 Mh4eUO6AGtpyjYc2kM96FaIqLIun3vb6fAKouyDYYGuyTZff_IHt0sZghsmQ55VFUiUvjD
5.7.14 _mfM5dNYpFq571lzE2cftttbA4s7EQAQzG6pFnk98M-rt2rUDBPhYgOviPkS2tgHMqmf69
5.7.14 -vlra5HePzL1rC_TPmKziT8Z1opLY> Please log in via your web browser and
5.7.14 then try again.
5.7.14  Learn more at
5.7.14  https://support.google.com/mail/answer/78754 h1sm995106wrb.25 - gsmtp
. . . 
```
Following the link and enabling less secure apps lets us make the connection.

![less-secure-apps](https://user-images.githubusercontent.com/1095794/28308273-fc4a195a-6ba5-11e7-948f-8e7565735cd7.png)


Trying again it works.
```
2017-07-18 10:48:39+0200 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory instance at 0x7f96e1aada28>
2017-07-18 10:48:41+0200 [-] 201 POST /admin/notification/mail - 2343ms
2017-07-18 10:48:41+0200 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory instance at 0x7f96e1aada28>
```

![test-mail-works](https://user-images.githubusercontent.com/1095794/28308638-1fbaadcc-6ba7-11e7-8b19-29e8f25eeb02.png)

**Comment by NSkelsey** [comment]
Interestingly the raw output of that successful mail indicates that TLSv1.2 was used, not SSL as indicated in config interface.

```
Return-Path: <jeb4pres2016@gmail.com>
Received: from localhost ([82.112.202.114])
        by smtp.gmail.com with ESMTPSA id g55sm1308305edg.66.2017.07.18.01.48.18
        for <jeb4pres2016@gmail.com>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Tue, 18 Jul 2017 01:48:19 -0700 (PDT)
Message-ID: <596dcb53.ba89500a.df8d3.5fee@mx.google.com>
Content-Type: multipart/alternative;
```

**Comment by NSkelsey** [comment]
To summarize, the open issues from this ticket are.

1) ~~The config_desc notification.security=TLS does not do anything and instead relies on the E in ESMTPFactory to work correctly. When we try to connect over TLS at 587 with smtp.gmail.com the connection hangs.~~ Actually, retrying with Less secure apps enabled allows us to send mail via 587.

1) Sending mails via google's SMTP requires enabling "Access to less secure apps"

2) The UI in admin > Notification Settings is missing descriptions of the notification fields in the interface, that explains the significance of the more confusing fields like:

- SMTP name
- SMTP mail address
- Username

**Comment by doudoulong** [comment]
Thanks! The two disables worked!
