### ISSUE TITLE
There is no Tor hidden service after the installation

### ISSUE THREAD

**Issue by doudoulong** [globaleaks/GlobaLeaks#2013]
I can access the server at both localhost:8082 and localhost:80, after installation using the following:

wget https://deb.globaleaks.org/install-globaleaks.sh
chmod +x install-globaleaks.sh
./install-globaleaks.sh

But tor hidden service was not up. It seems tor is installed. But after I uncommented the two hidden service lines in torrc and restarted tor, there was no hidden_service folder under /var/lib/tor.

**Comment by evilaliv3** [comment]
@doudoulong: which version of GlobaLeaks are you running?

check to have 2.70.8 that includes some bugfixing releated to this topic.

You should not see anything in /var/lib/tor, all the configuration of tor is performed via the tor control port.

check the globaleaks log at /var/globaleaks/log/globaleaks.log for lines like the following:
```
2017-07-18 00:47:23+0200 [TorControlProtocol,client] Created onion-service at wf4rmrcjm3fboweh.onion
2017-07-18 00:47:23+0200 [TorControlProtocol,client] Created 'wf4rmrcjm3fboweh.onion', waiting for descriptor uploads.
2017-07-18 00:51:22+0200 [TorControlProtocol,client] Uploaded 'wf4rmrcjm3fboweh.onion' to '$15319513EEF1F22EE864BD6502BC357009126586~furrygame'
2017-07-18 00:51:22+0200 [-] [I] Initialization of hidden-service wf4rmrcjm3fboweh.onion completed.
```

**Comment by alepartenza** [comment]
Yes, but by installing Globaleaks 2.70.8, the TOR address does not appear on the network settings tab.

![network_settings](https://user-images.githubusercontent.com/4155187/28314058-663cbaa8-6bb9-11e7-9c34-7584a736560b.jpg)

**Comment by NSkelsey** [comment]
Hi @alepartenza, I believe your issue is unrelated to the original. The logs in `/var/globaleaks/log/globaleaks.log` should provide the detail you need to understand the issue better.

I've created a larger to ticket #2014 to capture the common issue that we are seeing across these two posts.

**Comment by NSkelsey** [comment]
Hi @alepartenza, I believe your issue is unrelated to the original. The logs in `/var/globaleaks/log/globaleaks.log` should provide the detail you need to understand the issue better.

I've created a larger to ticket #2014 to capture the common issue that we are seeing across these two posts.

**Comment by doudoulong** [comment]
Thanks for the help!!!
