### ISSUE TITLE
--allow-unauthenticated issue with running the installation file

### ISSUE THREAD

**Issue by doudoulong** [globaleaks/GlobaLeaks#2015]
![screenshot from 2017-07-18 15-48-42](https://user-images.githubusercontent.com/4751354/28336881-99a8772a-6bd1-11e7-8e00-dd678474da87.png)

It's a little tricky with this particular issue. I just ran this installation on the VM on my MAC laptop and didn't have any problem. Then I ran the installation file on the VM on a Ubuntu desktop and got the problem. 

I don't with package that caused the problem.

**Comment by evilaliv3** [comment]
@doudoulong it seems that during the install script something failed without adding the keys we use to sign the repository and packages.

Try as first just to re-run the installation script.
If it does not work try to do (as root):
```pwd
wget https://deb.globaleaks.org/globaleaks.asc
apt-key add globaleaks.asc
```

**Comment by evilaliv3** [comment]
If that would not work please provide us some more information about the setup you are using (VM/Ubuntu version/etc).

thanks!

**Comment by doudoulong** [comment]
I repeated the installation both on the Ubuntu 16 VM on my MAC laptop, and the Ubuntu 16 VM on the desktop. Again, I got the same results. Everything worked fine with the VM on my laptop and I got the same error as before on the VM on my desktop. 

The desktop is pretty old. It only has 4GB RAM so I assigned 2GB to the VM, which I know it's not the ideal amount for Globaleaks. But I didn't have any problem running the installation script on the VM on the desktop yesterday. So I am wondering was any update in the .sh file in between?

**Comment by evilaliv3** [comment]
No update added.
If before running the install script you manually execute the following commands from root what do you get?

```bash
wget https://deb.globaleaks.org/globaleaks.asc
apt-key add globaleaks.asc
```

**Comment by evilaliv3** [comment]
@doudoulong could this ticket be closed or you are still having the issue?

**Comment by evilaliv3** [comment]
Closing as the ticket as probably outdated.
