### ISSUE TITLE
Reload HTTPS configuration without dropping existing connections

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2016]
Currently GlobaLeaks handles the reconfiguration of HTTPS by shutting down the HTTPS daemons and restarting them.

This ticket is for dealing with the activities to make GlobaLeaks be able to reload HTTPS configuration without dropping existing connections.

When an HTTPS configuration need to be applied, GlobaLeaks should:
- signal existing HTTPS processes to stop accepting new connections. the process should close when all their connections ends or when a timeout limit is reached.
- startup new processes running the new configuration.

**Comment by NSkelsey** [comment]
Currently, I am looking at the placing the testing of the implementation at the end of `test_init_with_launch` within the `tests/workers/test_supervisor.py` module. Testing this code is a delicate matter because it requires a full connection that is intentionally held open, maybe blocked just from its corresponding connection, right before a shutdown is issued by a unit-test.

**Comment by NSkelsey** [comment]
I've written a working unit test to handle catching the case. I propose to handle the shutdown process will work in the following way in the `https_proxy_worker`

1) Shutdown signal received
2) New connections rejected
4) Collect connection finish into a `deferredList`, that when resolved halts the process
5) Set a `deferredCallLater` to halt in 30 seconds.
6) fin.

**Comment by NSkelsey** [comment]
Work related to this 9da883119. 

For closure on this, we require functional testing that is partially working in branch `refactor/2016` at 8fdba2031fa0b0728aebaf0fb915d5686a1d2f74

**Comment by fpietrosanti** [comment]
Is this done?

**Comment by NSkelsey** [comment]
An implementation was added to devel in 9da8831199b69ad28a470ede3626732eacf88172, it remains outside of unit testing but we haven't seen any related failures since its integration in `v2.71.3`

**Comment by evilaliv3** [comment]
I would suggest to  leave this open still for a wile.

i'm about to start implementing this aspect for the multitenancy branch ancticipating the implementation in devel and i will take care of reporting here the eventual changes to the implementation.

**Comment by evilaliv3** [comment]
Released as part of the multitenancy implementation.

The ticket can be closed.
