### ISSUE TITLE
Implement REPORT_STATUS functionality inside the install script in order to track script failures 

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2021]
This ticket is for keeping track of the activities of implementation of a REPORT_STATUS functionality for the init script in order to keep track script failures.

**Comment by evilaliv3** [comment]
By the current analysis it has been identified valuable to track the following information:
- last command executed
- exit status for the last command
- lsb_release -c -s (distro release codename)

This could be implemented by means of a curl request on the install script resource passing the arguments as query strings.

Even though the information collected and the communication methods selected are considered to be privacy preserving the completion of the feature implementation includes the addition on the install guide of a documentation of the feature; a possible text for this could be: "```For debugging purpose the install script, while interacting with the install repository, communicates the status of the install and its eventual failures without revealing any privacy sensitive information. In case of failure you are or for any support request you are invited to join our user forum: https://forum.globaleaks.org```"

\cc @NSkelsey @fpietrosanti

**Comment by fpietrosanti** [comment]
I'd suggest then also to make a REPORT_STATUS for the installation success, verifying that GlobaLeaks started up with a local curl request on localhost, reporting then failure or success?

**Comment by NSkelsey** [comment]
I've reviewed the language here. I think we can add this string as output to the command as well.

> To quickly discover issues with packaging and the installation process, the install script communicates the success or failure of the installation to the repository from which it was downloaded in a non-intrusive manner. If you encounter a failure, you are invited to provide more details on our user forum: https://forum.globaleaks.org

**Comment by evilaliv3** [comment]
Thanks for the fast feedback @NSkelsey and @fpietrosanti.

Proceeding on a first implementation that i'm hoping to accomplish already by this morning.

**Comment by evilaliv3** [comment]
Implemented, integrated in devel and bugfixed.
