### ISSUE TITLE
GlobaLeaks Unhandled Exception on statistics of

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2027]
**Current behavior**
Receiving an unhandled exception from a node on the statistics jobs:
Platform: xxxxxxxxxxx ()
Version: 2.70.9

Job Statistics died with runtime -1.0000 [low: 4.0000, high: 62.0000]

**Expected behavior**
the system should not die but handle the possibly erroneous conditions without triggering any exception

**Comment by NSkelsey** [comment]
Commit 9d33fe7 improves our logging of errors produced by jobs. With the release of v2.70.9 we will have better resolution on errors here.

**Comment by evilaliv3** [comment]
@fpietrosanti: Nothing particular to do about this ticket as a job that dies regularly will be re-executed at the next cyclone.

Anyway @NSkelsey analyzed the possible improvements and added proper logging and notification of the exception stacktrace that is what is required to analyze the failure.
