### ISSUE TITLE
Introduce a warning to be acknowledged on-submission if "HTTP in cleartext"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2034]
**Current behavior**
With the current HTTP/HTTPS usability improvements of GlobaLeaks it can happen that a a globaleaks website goes online in clear-text HTTP.

That's very good from the usability, testing and evaluation point of view but very bad from a security perspective, because a node must go online at least with Tor Onion and HTTPS enabled.

**Expected behavior**
In order to balance the usability tradeoff in enabling the admin to test, evaluate, configure globaleaks, it's good that everything is accessible in HTTP, but the admin should get an clear warning to be available in multiple-place that the system configuration must be finalised by enabling at least HTTPS.

That way the system will be fully functional in HTTP, but with an annoying, non-removable warning that remember that the system configuration must be finalized.

**Comment by evilaliv3** [comment]
I propose for this ticket to implement different security awareness message to be shown when the user is visiting the submission page (or click the blow the whistle) with HTTPS and without Tor;

The proposed widget should:

- communicate to the whistleblower that the connection is not confidential in the title of the modal(the same way we currently communicate that it's not anonymous)
- comunicate that the reason it is confidential is that HTTPS is not configured.

What i think such an implementation would address is:
- the whistleblower will be informed of this state that could be the initial state of the platform or a possible state of the platform happening due to a certificate expiration
- the administrators will be trained on the use at first setup being informed of the need for HTTPS but being still able to test the platform as soon that the wizard is completed.

**Comment by evilaliv3** [comment]
Proposed texts for a minimal implementation to cope with current status and to be improved with longer discussion

TITLE: ```Warning!: The connection channel is not secure.```

TEXT: ```The platform is still not configured to accept HTTPS connections and should be used just for testing purposes.```

**Comment by NSkelsey** [comment]
@evilaliv3 I do not like the usage of "should be used just for testing purposes" instead we should just provide guidance on safe usage. If the UI lets you deviate from that behavior it should be for someone that knows how to deviate. I think the above text could confuse a whistleblower with the phrase "testing purposes".

> Warning! Your connection is not safe! 

> The platform is not using encryption and does not provide any privacy. Everything thing you submit can be recorded by network observers.

Alternatively the second sentence could be:

> Nothing you submit to this platform is private and will likely be recorded by third parties.

**Comment by evilaliv3** [comment]
Thanks @NSkelsey for your feedback.

I got your points in editing the text but let me explain why i was suggesting to keep this and iterate together in making it better.

the reasons behind the proposed texts are:
- this message is intended to be there just at the first setup; the more it become nice the more admins will just leave it there without configuring HTTPS the same that happened for the one not setupping Tor.
- the term HTTPS is technical and is there to recall precisely the admin on the action that has to perform.
- the text was then small to not overload translators with texts that we hope will never shown; but this is the minor thin.

**Comment by NSkelsey** [comment]
Two quick notes on the implementation.

1) Localhost should similarly not have the modal popup
2) Tabbing and UI interaction are still possible through the keyboard when the modal is visible X_x

**Comment by Taipo** [comment]
On default install accessing via the onion address, this warning displays continuously. Is that the intention?

**Comment by fpietrosanti** [comment]
It seems there's a bug being reported on https://forum.globaleaks.org/t/http-warning-nag-screen/121 that display the warning also over .onion ?

**Comment by Taipo** [comment]
May be in the $rootScope.connection.https section

**Comment by evilaliv3** [comment]
@fpietrosanti @Taipo  https://github.com/globaleaks/GlobaLeaks/commit/4de8f2a1ceff3b730959782cb98184ec9abf7d8c that is included in 2.70.1 released few days ago.

**Comment by Taipo** [comment]
The warning still activates via onion default install.

**Comment by evilaliv3** [comment]
This issue should be fixed now.
