### ISSUE TITLE
multiple failure of install script due to PGP keyserver fetch

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2035]
**Current behavior**
Actually the install script use gpg keyserver fetching that uses HKP protocol and HKP protocol require the ability to make outbound connections to port 11371 that's uncommonly opened on firewalls (especially is blocked on DMZ of firewalls for servers, only requiring outbound 80/443).

Due to that reason certain installation fails.

**Expected behavior**
This ticket is to remove this reason of failure by switching back to PGP hard-coded keys in the install-script to avoid dependencies on downloading keys possibly from remote host on unusual 11371 HKP port (that can be blocked on firewalls) that can bring additional failures reasons.

Below logs of multiple attempt to install the software manually with failure on keyserver download, likely because of HKP 11371 port unreachability.

x.x.x.x - - [25/Jul/2017:20:48:52 +0000] "GET /install-globaleaks.sh HTTP/1.1" 200 5963 "-" "Wget/1.18 (linux-gnu)"
x.x.x.x - - [25/Jul/2017:20:49:55 +0000] "GET /install-globaleaks.sh?DISTRO=xenial&LAST_COMMAND=gpg%20--keyserver%20keys.gnupg.net%20--recv%20A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89&LAST_STATUS=2 HTTP/1.1" 200 5963 "-" "curl/7.52.1"
x.x.x.x - - [25/Jul/2017:20:50:46 +0000] "GET /install-globaleaks.sh?DISTRO=xenial&LAST_COMMAND=gpg%20--keyserver%20keys.gnupg.net%20--recv%20A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89&LAST_STATUS=2 HTTP/1.1" 200 5963 "-" "curl/7.52.1"
x.x.x.x - - [25/Jul/2017:22:04:01 +0000] "GET /install-globaleaks.sh HTTP/1.1" 200 5963 "-" "Wget/1.17.1 (linux-gnu)"
x.x.x.x - - [25/Jul/2017:22:04:33 +0000] "GET /install-globaleaks.sh?DISTRO=xenial&LAST_COMMAND=gpg%20--keyserver%20keys.gnupg.net%20--recv%20A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89&LAST_STATUS=2 HTTP/1.1" 200 5963 "-" "curl/7.47.0"
x.x.x.x - - [25/Jul/2017:22:05:41 +0000] "GET /install-globaleaks.sh?DISTRO=xenial&LAST_COMMAND=gpg%20--keyserver%20keys.gnupg.net%20--recv%20A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89&LAST_STATUS=2 HTTP/1.1" 200 5963 "-" "curl/7.47.0"
x.x.x.x - - [25/Jul/2017:22:13:57 +0000] "GET /install-globaleaks.sh?DISTRO=xenial&LAST_COMMAND=gpg%20--keyserver%20keys.gnupg.net%20--recv%20A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89&LAST_STATUS=2 HTTP/1.1" 200 5963 "-" "curl/7.47.0"

**Comment by fpietrosanti** [comment]
Very same problem happened today during a download because of inability to resolve deb.globaleaks.org hostname while downloading the GlobaLeaks pgp key:

y.y.y.y - - [25/Jul/2017:14:00:10 +0000] "GET /install-globaleaks.sh?DISTRO=xenial&LAST_COMMAND=curl%20https%3A%2F%2Fdeb.globaleaks.org%2Fglobaleaks.asc%20-o%20%2Ftmp%2Ftmp.fQRq9k6BuZ%2Fglobaleaks_key&LAST_STATUS=6 HTTP/1.1" 200 5963 "-" "curl/7.47.0"

Definitively having hard-coded keys in the install script would be a good way to mitigate that specific failure

**Comment by evilaliv3** [comment]
let's go for it.

few notes:
- I agree that could help reducing a failure (on the GPG command and its custom port)
- i do not agree that we should consider the dns resolution to deb.globaleaks.org a problem.

in fact if we consider the the dns resolution to deb.globaleaks.org a problem:
- we should consider fixing: the guidelines that say how to install globaleaks (with wget file download from deb.globaleaks.org)
- we should consider that apt-get install globaleaks included in the script would not work
- we should consider the implemented reporting script for install failures would not work

**Comment by fpietrosanti** [comment]
Sure, in general by hardcoding the pgp keys we're just removing two possible cause of failure in the execution flows.

Then, we can add a further check that try to resolve deb.globaleaks.org and deb.torproject.org  and report a DNS configuration failure that must be resolved before proceeding ensuring that /etc/resolv.conf is properly configured

**Comment by evilaliv3** [comment]
done Sir!
