### ISSUE TITLE
Warn user about not confidential configuration of the platform and inform admins about need for HTTPS configuration 

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2036]
For demo purposes we always allowed the platform to receive submissions even if HTTPS is not configured.

This most of the time allow a lazy administrator to setup a node and boot the initiative even without HTTPS enabled.

This ticket is to discuss the addition of a different security awareness message to be shown when the user is visiting the submission page (or click the blow the whistle) with HTTPS and without Tor;

The proposed widget should:
- communicate to the whistleblower that the connection is not confidential in the title of the modal(the same way we currently communicate that it's not anonymous)
- comunicate that the reason it is confidential is that HTTPS is not configured.

What i think this ticket will address is:
- the whistleblower will be informed of this state that could be the initial state of the platform or a possible state of the platform happening due to a certificate expiration
- the administrators will be trained on the use at first setup being informed of the need for HTTPS but being still able to test the platform as soon that the wizard is completed.

**Comment by evilaliv3** [comment]
Closing as duplicated of https://github.com/globaleaks/GlobaLeaks/issues/2036

**Comment by evilaliv3** [comment]
Closed as duplicated of https://github.com/globaleaks/GlobaLeaks/issues/2036

**Comment by evilaliv3** [comment]
Closed as duplicated of https://github.com/globaleaks/GlobaLeaks/issues/2034

**Comment by fpietrosanti** [comment]
That should explicitly say that the system is not yet configured

Sent from mobile
