### ISSUE TITLE
16.04 globaleaks file doesn't create torhs folder

### ISSUE THREAD

**Issue by filternetz** [globaleaks/GlobaLeaks#2047]
**Current behavior**

Currently, on a 16.04 Ubuntu machine after the installation of Globaleaks, I want to visit the TorHS but I don't see any /var/globaleaks/torhs/ folder being created.

**Expected behavior**

torhs folder gets created

**Steps to reproduce the problem or feature illustration**

Install Globaleaks on a 16.04 machine.

**GlobaLeaks version:**

2.71.1

Some debug logs:

```

globale+  8228  1.0  4.7 548580 95948 ?        Sl   08:47   0:03 /usr/bin/python /usr/bin/globaleaks --ip=0.0.0.0 --user=globaleaks --group=globaleaks --working-path=/var/globaleaks/ --ramdisk=/dev/shm/globaleaks/ --loglevel=CRITICAL

debian-+  8070  0.8  1.8  73608 37096 ?        Ss   08:47   0:02 /usr/bin/tor --defaults-torrc /usr/share/tor/tor-service-defaults-torrc -f /etc/tor/torrc --RunAsDaemon 0

[Tue Aug 15 08:59:15 2017] audit: type=1400 audit(1502787555.743:10): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="system_tor" pid=2062 comm="apparmor_parser"
[Tue Aug 15 08:59:18 2017] audit: type=1400 audit(1502787558.331:11): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="usr.bin.globaleaks" pid=2206 comm="apparmor_parser"


```

**Comment by evilaliv3** [comment]
Thank you @filternetz for reaching out to us.

This is not a bug but it is just related to different workflow that GlobaLeaks is following while managing HiddenServices.

In releaes starting from 2.70 globaleaks is managing hidden services at runtime via the tor control port and all the data (the onion name and the onion key) is stored on the database.

Here what you should know about the feature:
- You should read the generated onion service via the web interface: /#/admin/network
- In alternative you could read the setting from the terminal with: ```gl-admin readvar onionservice```
- Migrations from old nodes are managed automatically taking what in /var/globaleaks/torhs inside the database
- If you want to set a key manually you could do it using ```gl-admin setvar``` like explained in https://github.com/globaleaks/GlobaLeaks/issues/1993

Please let us know if this fixed your issue and eventually reopen it in case you need further help.

In addition if you were currently following a wiki page that is not updated please notify us of that error :)
