### ISSUE TITLE
I cannot open globaleaks Form on chrome browser

### ISSUE THREAD

**Issue by strikerno19** [globaleaks/GlobaLeaks#2048]
**Current behavior**

I use Chrome browser but can not open my form for choose issue of globaleaks
but I open on Firefox is work please suggestion for me 
Thanks You.

**Expected behavior**

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

2.67.4

**Browser:**

Chrome 60.0.3112.90
Firefox 54.0.1

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by NSkelsey** [comment]
Hi @strikerno19, it is not clear what your issue is.

Are you reporting that a certain page in GlobaLeaks is broken or that the whole site is broken when using Firefox? Can you please check https://demo.globaleaks.org with your Firefox to see if the same issue persists? Finally, can you post a screenshot and some more information and we can figure out what is not working.

Thanks!

**Comment by strikerno19** [comment]
Sorry, NSkelsey
I does not use GlobaLeaks on google chrome browser, when I open url http://ept.thaitobacco.or.th/ to show blank page

Thanks you

**Comment by NSkelsey** [comment]
Hi @strikerno19 the URL you provided works for both with chromium and firefox for me. Maybe it is an issue with the version of chrome you are using? The connection to https://ept.thaitobacco.or.th works for me as well as to the onion service. I do not think this is an issue with GlobaLeaks code!

**Comment by fpietrosanti** [comment]
@strikerno19 if you do a professional uses of GlobaLeaks for a public-private organization, please consider donating something to GlobaLeaks https://www.globaleaks.org/donate or to subscribe a maintenance/support contract to get premium-dedicated assistance directly contributing to GlobaLeaks development! For any email info@whistleblowingsolutions.it
