### ISSUE TITLE
Support drag and drop of files

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#2063]
**Current behavior**

Currently, interaction with the system UI is required to select a file to upload in the administation interfaces, the user preference interfaces and the whistleblower interfaces.

**Expected behavior**

It would be really nice to be able to drag files into the interface to make the application friendlier!

There is an angular library for supporting exactly this behavior too. https://github.com/codef0rmer/angular-dragdrop

As an addendum @evilaliv3 posits that default input boxes that handle 'file-change' events can also handle the drop of a file on the HTML element. This may mean that we can simply add a "landing zone" to the `fileInputChange` directive to support this functionality.

**GlobaLeaks version:**

Everything before `v2.71.3`

**Comment by evilaliv3** [comment]
@NSkelsey to which interfaces does this ticket applies?

Currently i'm thinking just to the PGP key file upload in order to build a text are with file upload and drag+drop builtin. 

For the rest already we have this support thanks to [ng-flow](https://github.com/flowjs/ng-flow)

**Comment by NSkelsey** [comment]
I honestly forgot that `ng-flow` did that. I guess this would then apply to the few places in the admin interface where we do not use `ng-flow` to handle file uploads.

**Comment by evilaliv3** [comment]
Feature implemented, it will be released starting from release 3.11.16

Current interface design is the following:
![screenshot-127 0 0 1_8082-2019 09 24-11_27_37](https://user-images.githubusercontent.com/217034/65500556-c19e2f00-debf-11e9-8431-b8894ad68611.png)

**Comment by NSkelsey** [comment]
Looks really nice :+1:

**Comment by evilaliv3** [comment]
Assigning this to me in order to verify this is still the case on the new clint on 5.0.*
