### ISSUE TITLE
 Disable the security awareness panel not working properly

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2067]
the advanced selection "Disable the security awareness panel" is not working properly

the sequrity awareness panel :
...
Sending submissions over HTTPS exposes the act of doing so, but not the content.
...
always comes up no mater what

This is still an issue in the most recent version of the software as i installed just today 27/8/17
Im not sure which is the current version number.
It is installed on ubuntu server 16.04 

have tested both edge and chrome on win 10 and show the same behaviour.

have had the exact same configuration in the past with no issues.

**Comment by NSkelsey** [comment]
Hi @elbill, can you please check in the Administration interface > Home that the software version you are running is v2.71.3?

Can you also provide an example, screenshots, or steps to reproduce the issue you have encountered? Thanks!

**Comment by elbill** [comment]
Hello @NSkelsey 
Software version indeed 2.71.3
Attaching settings showing that security awareness panel has been disabled.
then it comes up when you press the "blow the whistle" button. (The questions have been disabled and don't show up).
I hope this helps. I can provide admin access if necessary since this is not operational installation. thanks
![2017-08-28](https://user-images.githubusercontent.com/23246886/29763610-8ac6e7c0-8bdc-11e7-94fa-77bcb8e0f478.png)
![2017-08-28 2](https://user-images.githubusercontent.com/23246886/29763892-b3ac65c4-8bdd-11e7-960e-c0a7f7b57bf5.png)

**Comment by evilaliv3** [comment]
Thank you for the prompt feedback @elbill !

Thanks yo you we identified the issue and we are ready to issue a fix; a new release will be probably available by today with number 2.72

**Comment by elbill** [comment]
Something tha missed my attention. While setting up the HTTPS, I received this email. It may be related:
Platform: sec.fraudline.gr ()
Version: 2.71.3

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)

  File "/usr/lib/python2.7/dist-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)

  File "/usr/lib/python2.7/dist-packages/globaleaks/rest/api.py", line 311, in render
    if self.should_redirect_https(request):

  File "/usr/lib/python2.7/dist-packages/globaleaks/rest/api.py", line 218, in should_redirect_https
    if GLSettings.memory_copy.private.https_enabled and \

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/objectdict.py", line 9, in __getattr__
    raise AttributeError(name)

AttributeError: private

**Comment by elbill** [comment]
Great , thanks!

**Comment by elbill** [comment]
@evilaliv3 
I have seen that you have fixed the issue, however with the same release number.  So I can not update on line using the same release number. How can I do this?
Thanks in advance

**Comment by elbill** [comment]
@evilaliv3 
Sorry to bother you again. I have seen that you have applied some changes in 2.71.3 release. Does it have to do with my bug report? I have updated the installation but the problem persists. 
If not when is the 2.72 release expected. 
Thanks in advance

**Comment by evilaliv3** [comment]
Good morning @elbill, release 2.72.1 is already out since yesterday.

Sorry for having forgot to update the ticket.

To update you just need to perform: ```apt-get update && apt-get install globaleaks```
That should fix your issue

Feel free to reach us again if it does not :)

**Comment by elbill** [comment]
Seems to be working fine now! 
thanks @evilaliv3.
