### ISSUE TITLE
HTTPS warning

### ISSUE THREAD

**Issue by nc67** [globaleaks/GlobaLeaks#2072]
Hello.
Can I disable HTTPS unsafe connection?
Thank you.
Nicolò
Version software: 2.71.3
![https](https://user-images.githubusercontent.com/31469719/29912956-d828c9c6-8e33-11e7-98fa-b32bc252512a.JPG)

**Comment by fpietrosanti** [comment]
Salve Nicolò,

GlobaLeaks ha bisogno che l'interfaccia HTTPS per il collegamento sicuro venga abilitato, seguendo le istruzioni riportate all'indirizzo:

http://globaleaks.readthedocs.io/en/latest/ConfigurationGuide.html#configure-https

Ha usato il formulario per la richiesta di servizi professionali, che eroghiamo a supporto del progetto con l'impresa sociale Whistleblowing Solutions Impresa Sociale Srl https://www.whistleblowingsolutions.it e per la quale forniamo servizi di manutenzione, hosting e sviluppo software personalizzato (rigorosamente solo opensource, nel migliorare il bene comune GlobaLeaks).

Se avesse l'occasione, direttamente o tramite co-finanziamenti quali PON e simili, di contribuire e supportare lo sviluppo del progetto con l'ente presso cui lavora tramite un progetto alla Impresa Sociale Whistleblowing Solutions, sarebbe un grande risultato di investimento pubblico in un bene comune! :)
Per richieste di supporto pro-bono, è attivo il forum https://forum.globaleaks.org dove condividere la conoscenza delle problematiche evidenziate in modo collaborativo tramite una comunità di supporter del progetto.

Penso stia implementando una infrastruttura di whistleblowing digitale in compatibilità con la 190, giusto?

In tal caso la invitiamo, ai fini della configurazione del questionario, a fare riferimento al ricco questionario di trasparency international italia https://alac.transparency.it .

Non esiti a contattarci nuovamente per assistenza

Saluti

-- 
Fabio Pietrosanti - President & Co-Founder
fabio.pietrosanti@logioshermes.org | +39.340.1801049

HERMES - Center for Transparency and Digital Human Rights
Associazione No Profit | Via Aretusa 34, IT-20129 Milan, Italy
t. +39-02-87186005 (voicemail) | f. +39-02-87162573
TaxCode: IT-97621810155 | EuropeAid: IT-2012-AOD-0806909254
w. http://logioshermes.org | m. info@logioshermes.org

**Comment by nc67** [comment]
Grazie per la risposta…
Naturalmente capisco che almeno l’HTTPS debba essere utilizzato per un minimo di sicurezza.
Il problema che ho è che il sito Globaleaks che ho configurato si trova su un server interno alla mia rete con indirizzo privato del tipo 192.168.x.x Nattato su un’indirizzo pubblico con record DNS e accessibile attraverso un ReverseProxy. La configurazione quindi non è delle più semplici e stranamente, puntando all’indirizzo pubblico “prova.dominio.it “ che corrisponte ad un’IP pubblico che attraverso il ReverseProxy dovrebbe raggiungere la macchina interna sulla quale ho installato il sistema, questa non viene aperta. Per questo motivo non ho potuto configurare correttamente l’HTTPS.

**Comment by fpietrosanti** [comment]
Ciao Nicolo,

per attivare HTTPS con LetsEncrypt e quindi certificati gratuiti e automatici, l'IP deve essere raggiungibile sulla porta 80 e 443 su internet, poi può esserlo anche con un reverse proxy, ma lì dipende dalla configurazione di reverse proxy.

Senno' è possibile seguire la procedura manuale, comprando un certificato digitale da impostare a mano, e in quel caso può anche non trovarsi su internet esposto http://globaleaks.readthedocs.io/en/latest/ConfigurationGuide.html#manual-https-configuration .

Se posso suggerire, farei una NAT su internet con port-mapping anziché con reverse-proxying, così da eliminare possibili problemi di reverse proxying.

**Comment by NSkelsey** [comment]
I believe this is no longer an issue and should live instead on forum.globaleaks.org.
