### ISSUE TITLE
Perform automatic backups of the working dir

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#2074]
Having backups of the application data is desirable even for whistle blowing systems. Careful consideration needs to be taken when defining backup functionality so that the data retention policy defined within the application is respected. This ticket is the first half of the remote backup idea proposed by @fpietrosanti in [his comment](https://github.com/globaleaks/GlobaLeaks/issues/528#issuecomment-281650878) on #528 

**Current behavior**

Within gl-admin we support `gl-admin backup` and `restore` which takes the working directory and copies it into a zip file. 

**Expected behavior**

Backing up should be automatic and manageable for our users.

**Feature illustration**

The application scheduler could produce these zips on a schedule that rotates the backups. Further we could improve the system to backup configuration only without the need for storing data from the whistleblower tables. Only the system administrator should be able to produce and read backups and they should be as isolated from the running application as we can make them.

**What is the motivation or use case for changing the behavior?**

Having backups of the application data is desirable even for whistle blowing systems. Careful consideration needs to be taken when defining backup functionality so that the data retention policy defined within the application is respected.

**Comment by fpietrosanti** [comment]
Let's for a .tar.gz instead of .zip, as it preserve unix uid/gid/permissions.

To be analysed whenever to "execute" a command from twisted (that require apparmor profile opening) or setup a globaleaks-backup-crontab at installlation time, that run once per minute, and to which twisted can "pass parameters" by writing instruction to a file.

**Comment by NSkelsey** [comment]
ACK on using gziped tar files.

The standard library of python contains [gzip](https://docs.python.org/2/library/gzip.html) and [tar](https://docs.python.org/2/library/tarfile.html) modules. So we don't need a managed crontab to do this work.

If we configured twisted to write parameters to a file we would also have to change the app armor profile. I think that the backup script will end up having to be python, if we want lots of configurability.

Further we should consider how to clean a sqlite3 database's transaction log.

**Comment by fpietrosanti** [comment]
Just beware that doing recursive file listing, reading, compression, saving from Python may lead to buffering/memory issues and possibly to permission issues (not today, but in future if we move to multi-process with multi-uid/gid). I love to avoid the exec() of system command, but also to be careful on possible issues above

**Comment by evilaliv3** [comment]
I agree with what written;

I see not concern in memory/buffer issues bacause both Gzip and Tar algorithms are designed to work in streaming, also the python implementation support that and is up to the user to not make particular issues. Mostly what happen when generating the zip is that one create provide a file list eventually even of a root directory and then the process is almost straigthforward.

@fpietrosanti: you elaborated the idea of having incremental backups; after thinking a bit about it i think this would be really difficult for mix reasons:
- we miss in python support by off-the-shelf components;
- the complexity of having incremental backups is not in having to implement them that is easy, but is in implementing an incremental backup with support of a data retention policy; proprietary/opensource off the shelf components exists but require to perform a sort of "shrink" on the backup server and obviously also exec() on the globaleaks machine.

**Comment by NSkelsey** [comment]
Okay, I'd like to propose a complete picture for backing up data stored within the workingdir. Backups will be handled by a program called `gl-backup` that:

1) Runs once a day via cron
2) Produces a gzipped tar of the application data stored on disk
3) Manages the number of snapshots and old snapshot removal
3) Respects the data retention policy specified within the application WRT tip expiry times.
4) Provide easy points for remote services to provide create offsite backups of application data.
5) Retrieves its configuration from settings controllable by an administrator from the web interface.
5) Be usuable in a one off mode before migrations and other potentially lossy actions
6) Logs its actions

I believe reqs 3&4 will be tied tightly together and a simple parsing of the current data retention policy could be applied to the archive being produced. If it is possible we can specify an expire time somewhere in the metadata of the file or of the tar, so that the application can judge based on the current time and the 'archive expire time' when to shred the archive. This could be based on the a policy specified by the `first tip expiration` or a configurable setting `backup archive period`.

**Comment by vodkina** [comment]
just a note about 1. 
in a previous comment to this issue it is mentioned: "So we don't need a managed crontab to do this work." 
I think the two assertions are contradicting.

**Comment by evilaliv3** [comment]
Thanks @NSkelsey;

the proposal in general seems fine, but i would suggest before implementing to continue keep open the conversation for a while.

Here some comments to aspecs of the proposal still to be defined:
I would discourage the implementation of point 4; that point is for me  me satisfied naturally by globaleaks in relation to new generated archives together with a backup rotation set with the proper timing of deletion of old backups. Any different solution opening an archived old migration and editing it to make an old migration comply with the current expirations would drive to a too complex implementation that is not proper of any system (e.g. in transaction systems typical of bank or telephonic databases)

I would like also to add a new explicit requirement, not that easy to be achieved that would probably need live 
9. Database archival and related filesystem file should be consistent and minimize periods of stop of the business logic.

This point is particularly critical because if the simple db copy could happen online thanks to special backup functions and locks of the database, different thing apply to the files on the filesystem that could probably require a shutdown of the application; this causes that probably we will have to perform the entire backup in a window of shutdown of the application that in a large multitenant deployment could take long time.

**Comment by evilaliv3** [comment]
References on how to perform a safe backup with sqlite:
- https://sqlite.org/backup.html
- https://sqlite.org/c3ref/backup_finish.html#sqlite3backupinit
- https://gist.github.com/achimnol/3021995

**Comment by fpietrosanti** [comment]
I would avoid any aspects related to system configured data retention policy, that's up to the data administrator to be considered. 

Consider a simplified approach, a system administrator would just do a cold "tar zcvf /var/backups/globaleaks-$day-$month-$year.tar.gz /var/globaleaks" and then scp this file somewhere else, deleting file older than X days to keep online Y full snapshots.

This can be implemented in a couple of shell script, run by crontab, taking parameters from globaleaks database.

Implementing this basic logic entirely in python, is cool, just take it simple as it is.

**Comment by fpietrosanti** [comment]
Here comments of past ticket on making it as simplest as possible: https://github.com/globaleaks/GlobaLeaks/issues/528#issuecomment-281650878

**Comment by evilaliv3** [comment]
I agree;

The implementation focus at least for the first goal should probably be related to points 1, 2, 3 keeping in mind the discussed topics but achieving a practical goal.

For what relates to a safe copy of the database let's skip it for the moment for the following reasons:
1) a python way using the sqlite online backup  api is not available, and the previouslymentioned link that use C calls: https://gist.github.com/achimnol/3021995
2) sqlite3 has a ```.dump``` command but requires shell execution (that we could eventually keep in consideration if we decide to execute to implement it all in bash that is for me still a valid option where the bash script could read db variables thanks to the already implemented support in gl-admin)

but in general that this is a refinement we should postpone an subject to longer discussion.

**Comment by NSkelsey** [comment]
In response to @fpietrosanti's [comment](https://github.com/globaleaks/GlobaLeaks/issues/2074#issuecomment-329247253]
> "tar zcvf /var/backups/globaleaks-$day-$month-$year.tar.gz /var/globaleaks" and then scp this file somewhere else

See [gl-admin backup](https://github.com/globaleaks/GlobaLeaks/blob/devel/backend/bin/gl-admin#L72-L86) for the simple solution that stops the service produces a .tar.gz backup and then restarts the service.

Responding to @vodkina's [point](https://github.com/globaleaks/GlobaLeaks/issues/2074#issuecomment-329172880)
> in a previous comment to this issue it is mentioned: "So we don't need a managed crontab to do this work." I think the two assertions are contradicting.

There are a few ways we can schedule running this program. If we use the schedulers within the application, the globaleaks process will have to be given permission to read/write the backup directory. If we write a standalone daemon that can fire itself, we have to maintain a full daemon. If we call the program from cron we can avoid the complexity of maintaining another daemon that must stay alive on the system.

I think that going with an entry in the crontab is the best compromise.

For @evilaliv3's [comments](https://github.com/globaleaks/GlobaLeaks/issues/2074#issuecomment-329252367)
> 1.  a python way using the sqlite online backup api is not available, and the previouslymentioned link that use C calls

I tested the script on a xenial system and it seems to work. I wouldn't discount it because it loads a shared lib. 

> 2. sqlite3 has a .dump command but requires shell execution (that we could eventually keep in consideration if we decide to execute to implement it all in bash that is for me still a valid option where the bash script could read db variables thanks to the already implemented support in gl-admin)

With the code that we already have, I think we need to do the following to implement the minimal minimal minimal functionality is the following:

- [ ] Add once daily crontab entry in `globaleaks.postinst`
- [ ] Write a gl-backup script that executes the following algorithm:
```
checks for the existence of the backup dir and the pending delete dir and initializes if not their
reads `wbtip_timetolive` and uses that as the reference for maximum archive lifetime from time == now.
reads the files in the backup dir and decides based on a flag if they should be deleted. 
if some files are found that should be deleted:
   move said files to pending delete dir and logs fact
generates a new backup
sends naif a fax of node config
logs successful completion
``` 
- [ ] documents its usage via `-h`
- [ ] provide docs that explain the existence of a pending delete dir that they need to review/delete.

**Comment by fpietrosanti** [comment]
@NSkelsey with the regards to the crontab entries, we've done several analisys in past also related to software watchdog with the idea to have a "globaleaks system crontab" that's executed once every minute.
That globaleaks system crontab would then read instruction from a file (as a stateless IPC) where will find action-parameters for the specific scheduler it must do on the next run (no commandline, just parameters to what the scheduler knows it should do).

That would then enable to have such a system-scheduler operating on application instructions once every minute, enabling future operations of scheduled updates, application watchdog and similar stuff that should be done as root by a system process.

With the regards to the algorithm to consider data retention querying the db, i would avoid that entirely, because the parameters from a sysadmin perspective are just:
- "how often you do the backup" 
- "how many copies of backup you want to keep online" 

Mixing those the admin can achieve the data backup he wish.

If we rely on application-level-parameters such as wbtip_timetolive we may find situation where is more than 2 years and we would be accumulating backups at each run.

**Comment by NSkelsey** [comment]
@fpietrosanti ACK on the idea for reading a config file written by the globaleaks process.

The idea about making decisions about a backup policy for the platform based on the data retention policy is to remove the need for an system administrator to manually implement the choice. This is clearly apart of the OTF grant section 4.3: 

> - Removal of any file-based configuration by moving config
storage to the database controllable via a web-based
interface.
> - Remove any kind of Linux command line knowledge for
deployment and maintenance
> - Implementation of upgrade mechanisms resilient to failures
and with embedded roll-back capabilities

How often a backup gets stored can be to preserve a running backup that preserves keeps around something like:

7 backups from the last 2 weeks
11 backups for every month in the last year
1 backups for each year for all the previous years.

This leads to a nice constant 18 + (num active years - data retention delete date) x multiplier for disk space usage, but covers storing the application for the long term.

**Comment by fpietrosanti** [comment]
@NSkelsey we can gives a default settings, but then the parameters that can be understood by a non technical person taking the choice to do a backup are always "how often you do a backup" and "how many backup copies do you want keep" that's the oversimplification approach

**Comment by NSkelsey** [comment]
Yes sure, the first implementation will *simplify* the configuration to phrase the configuration questions to "how long would you like to backup and how many backups do you want." The program can just evenly spaces backups along the requested time period and shred the ones that are expiring.

See *oversimplify* [definition](https://www.merriam-webster.com/dictionary/oversimplify)

**Comment by evilaliv3** [comment]
GlobaLeaks is now performing a backup of the /var/globaleaks directory in the debian ```postinst```.

The fiie is stored in /var/globaleaks/backup/ in a file with the name globaleaks-$version-$timestamp.zip

The files are now automatically deleted after 15 days of operation by a the cleaning job.

I would suggest to complete this ticket by:
- Making the backup time configurable via the web interface:
- Adding the possibility to enable: daily, weekly and monthly backups with a simple policy:

daily: retained for 1 week before reusing
weekly: retained for 4 weeks before reusing
montly: retained for 12 months before recycling

calling the files with the number of the (day), (week), (month).

**Comment by evilaliv3** [comment]
Deprecate in favour of https://github.com/globaleaks/GlobaLeaks/issues/528
