### ISSUE TITLE
Add HTTPS configuration to the startup wizard

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#2075]
**Current behavior**

The user must wait until after the initial setup of the application to enable Let'sEncrypt.

**Expected behavior**

It should be very easy and straightforward for a user to setup and protect their site publicly on the Internet.

**Steps to reproduce the problem or feature illustration**

Structuring the user interface of the wizard to include a hostname with the automatic HTTPS setup is probably all we will do. And if so, we will have the ability to display a popup saying the transfer has failed for some specific region.

**Comment by fpietrosanti** [comment]
#2019

**Comment by NSkelsey** [comment]
Closing as duplicate
