### ISSUE TITLE
Problem with characters such as 'șățâî' when uploading a custom homepage

### ISSUE THREAD

**Issue by mihaisavezi** [globaleaks/GlobaLeaks#2079]
**Current behavior**

As an admin if I want to use the custom homepage feature and I upload an HTML file with characters such as  'șățâî', they don't get displayed as expected.

Strings like:
```html
<div>RomâniaIncognito</div>
<div>Cum funcționează</div>
<div>Întrebări frecvente</div>
<div>Siguranță pentru surse</div>
<div>Contact</div>
```

Are currently shown as:
```
RomÃ¢niaIncognito
Cum funcÈioneazÄ
ÃntrebÄri frecvente
SiguranÈÄ pentru surse
Contact
```

**Expected behavior**

The strings should be shown with the right encoding:
```
RomâniaIncognito
Cum funcționează
Întrebări frecvente
Siguranță pentru surse
Contact
```

**Steps to reproduce the problem or feature illustration**

- Go to admin dashboard, theme-customization, upload a custom homepage that looks like the expected behaviour above and see for yourself.

**Proposed solution**

The problem I found is the base64 decoding function native to the browser ( window.atob) which doesn't seem to handle some characters properly. This seems to be the culprit

```javascript
// client/app/js/app.js( line 554)
...
if (result.node.homepage) {
  $templateCache.put('custom_homepage.html', atob(result.node.homepage));
}
...
```

What worked for me is using another function instead of the native window.atob

https://developer.mozilla.org/en-US/docs/Web/API/WindowBase64/Base64_encoding_and_decoding
```javascript
function b64DecodeUnicode(str) {
    // Going backwards: from bytestream, to percent-encoding, to original string.
    return decodeURIComponent(atob(str).split('').map(function(c) {
        return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
    }).join(''));
}
```

**What is the motivation or use case for changing the behavior?**

Prevent other users experiencing this.

**GlobaLeaks version:**

No clue how to check this

**Browser:**

Chrome 59

**Server Operating System and Version (if applicable):**
 

This is happening in a development environment running Ubuntu 14.04

**Client Operating System and Version (if applicable):**

This is happening in a development environment running Ubuntu 14.04

**Comment by evilaliv3** [comment]
Thank you @mihaisavezi for reporting this issue;

We will test your fix and evaluate its inclusion in the next release.

**Comment by evilaliv3** [comment]
Thanks @mihaisavezi, i've reproduced the issue and tested your suggestion.

The patch has been integrated in the devel branch and will be included in the next release.
