### ISSUE TITLE
Unhandled Exception twisted.web._newclient.ResponseFailed 

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2089]
**Current behavior**
Platform: xxxx.xxxx.yy (xxxx.onion)
Version: 2.72.3

twisted.web._newclient.ResponseFailed 
    L{ResponseFailed} indicates that all of the response to a request was not
    received for some reason.

    @ivar reasons: A C{list} of one or more L{Failure} instances giving the
        reasons the response was considered to have failed.

    @ivar response: If specified, the L{Response} received from the server (and
        in particular the status code and the headers).
    

Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 44, in run
    yield self.operation()

ResponseFailed: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>, <twisted.python.failure.Failure twisted.web.http._DataLoss: >]

**Comment by NSkelsey** [comment]
This exception has been seen on both tor enabled and hosts with tor disabled.

It is very similar to #2092 with the only difference being that the underlying HTTPClientParser has received content at the time of the connectionLost [call](https://github.com/twisted/twisted/blob/twisted-16.0.0/twisted/web/_newclient.py#L545-L546).

So it should be handled similarly.

**Comment by NSkelsey** [comment]
Resolved in `ccf84e2`
