### ISSUE TITLE
Unhandled exception: AttributeError Attribute not found. "Private"

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#2091]
**Current behavior**

```
Version: 2.72.3

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 183, in process
    self.render(resrc)

  File "/usr/local/lib/python2.7/dist-packages/twisted/web/server.py", line 234, in render
    body = resrc.render(self)

  File "/usr/lib/python2.7/dist-packages/globaleaks/rest/api.py", line 307, in render
    if self.should_redirect_https(request):

  File "/usr/lib/python2.7/dist-packages/globaleaks/rest/api.py", line 211, in should_redirect_https
    if GLSettings.memory_copy.private.https_enabled and \

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/objectdict.py", line 9, in __getattr__
    raise AttributeError(name)

AttributeError: private
```

**Steps to reproduce the problem or feature illustration**

This looks like it could be a timing issue from the time the memory copy is refreshed and the a request arriving on the backend.

**What is the motivation or use case for changing the behavior?**

There may be a way to prevent the application from responding to queries as it is refreshing the memory copy.

**GlobaLeaks version:**

v2.72.3

**Comment by NSkelsey** [comment]
Outlining a test case for confirming if the race condition exists:

1. Setup handler TC that evaluates the rest/api.py functionality
2. Schedule repeated node memory refreshes in the main thread
3. Repeatedly fire handler with a `yield` in main thread
4. Fail test if attribute error exception is thrown while executing yield 1000 times.

I think that if the `db_memory_refresh` function blocks and releases control in the right place, the api request handler will not have the state objects it needs and throw this kind of exception.

**Comment by NSkelsey** [comment]
Seen in 2.71.3, 2.72.3, 2.72.5. Nothing indicates that this exception was introduced in v2.71.3. I believe it is just a rare race condition.

**Comment by evilaliv3** [comment]
By the current status i would suggest to postpone further work on this ticket waiting for reproducibility.

**Comment by evilaliv3** [comment]
Closing as outdated
