### ISSUE TITLE
Make it possible to disable admin notifications for software exceptions

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2099]
Various adopters are requesting for the possibility for disabling admin notifications for software exceptions.

It would be valuable to implement the following:
- make it possible to disable admin notifications for software exceptions
- make it possible to disable developers notifications for software exceptions.

**Comment by evilaliv3** [comment]
I'm about to finalize the implementation of the feature;

I'm suggesting not adding a per-user setting for the moment as it would require a change of the database and a migration script.

For the moment i'm going to add just global booleans which addition is possible without any db edit and we will evaluate in the future if taking the feature to user level.

**Comment by NSkelsey** [comment]
It should be noted that encryption of exception notifications was removed in 1a5a730.

**Comment by NSkelsey** [comment]
This is only partially the case actually. The encryption of email notification has been removed only for mails sent to the developer mailing list. Admin mails sent out are still encrypted using their mail key.
