### ISSUE TITLE
Anomaly mails are not templated correctly

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#2106]
**Current behavior**

The produced mails from the `AnomalyKeywordClass` are missing template tags and are poorly formatted as they are sent on the wire. For example look at the mail that just arrived in my inbox with the subject line `Anomaly detected in TestNode`:

```
Dear {RecipientName},

GlobaLeaks technology includes a server status checking component which will alert you in case something requires your attention.

Dear {RecipientName},

500MB of 24GB available diskspace used.



Please consider asking your technical support to create more disk space on the server.

Unless the issue is resolved this email will be resent in a few hours.

This is a MEDIUM level alarm. Don’t panic, but deal with it as soon as possible.

Kind regards,
TestNode



For more information, log in to the Administration interface and look at the "System Stats" and "Anomalies" sections.

Kind regards,
TestNode
```

The issue is that the base template `admin_anomaly_mail_template.txt` includes a full subtemplate in the variable interpolation.

1)  `{AnomalyDetailDisk}` which is used to include the templates `data/txt/admin_anomaly_disk_low`, `_medium`, `_high`
2) `{AnomalyDetailActivities}` which contains `data/txt/admin_anomaly_activities.txt`

These templates just need to be trimmed.

**Expected behavior**

The template vars are used interpolated correctly and the mails don't include two templates.

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

The template var issue was added in 8b2a9d01c1f525439b048c5205f696dc02a380a8. It is not clear for how long the disk_anomaly mails have been formatted like this.

**GlobaLeaks version:**

template vars broken in `v2.72.6`

**Comment by NSkelsey** [comment]
Mails now sent out look like this:

```
Dear Admin,

GlobaLeaks technology includes a server status checking component which will alert you in case something requires your attention.

500MB of 34GB available diskspace used.

Please consider asking your technical support to create more disk space on the server.

Unless the issue is resolved this email will be resent in a few hours.

This is a MEDIUM level alarm. Don’t panic, but deal with it as soon as possible.


For more information, log in to the Administration interface and look at the "System Stats" and "Anomalies" sections.

Kind regards,
TestNode
```

**Comment by evilaliv3** [comment]
I confirm the bug and that the fix is right.

I applied minor correction to mistakes performed when committing the patch https://github.com/globaleaks/GlobaLeaks/commit/e5684693fadcd701ab6420b9353d826e083c6438

**Comment by NSkelsey** [comment]
@fpietrosanti @evilaliv3, as of de6e1a9 the sent mail now looks like this:

```
Dear Admin,

A software update is available.
It is good security practice to keep the platform up to date.

Installed version: 2.72.5
Latest version: 2.72.7

To learn about new features and bug fixes in the new version consult the ch=
ange log at: https://raw.githubusercontent.com/globaleaks/GlobaLeaks/master=
/CHANGELOG
For update instruction please refer to the documentation at: https://global=
eaks.readthedocs.io/en/latest/UpgradeGuide.html

Kind regards,
TestNode
```
