### ISSUE TITLE
Unhandled FindField recursion depth exceeded

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2109]
**Current behavior**
Platform: xxx.xxx
Version: 2.72.7

URL: /submission

User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 11_0_1 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A402 Safari/604.1

Error Message: RangeError: Maximum call stack size exceeded.

Stacktrace:
[
  {
    "source": "~~~~~~@~~~~~~://xxx.xxx/js/scripts.js:10589:26", 
    "columnNumber": 26, 
    "fileName": "https:/xxx.xxx/js/scripts.js", 
    "functionName": "findField", 
    "lineNumber": 10589

**Comment by evilaliv3** [comment]
@fpietrosanti i've removed the exception notification asthe label is intended to be used for code related to excption notification.

The right labeling in this case is: Bug + Client as the exceptions seems to be related to an a bug on the client affecting iOS 11

**Comment by NSkelsey** [comment]
This is an issue with new code. `findField` is our recursive function to identify a field related to a hierarchical field trigger. It would be very helpful to get the structure of the questionnaire for this site to investigate what broke here.

**Comment by NSkelsey** [comment]
Here is the [/public](http://sprunge.us/cDDX) that may be causing the issue.

**Comment by fpietrosanti** [comment]
Also on Android on /submission
User Agent: Mozilla/5.0 (Linux; Android 6.0.1; SM-J710F Build/MMB29K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.98 Mobile Safari/537.36

**Comment by evilaliv3** [comment]
The bug is confirmed and is actually a regression i introduced in commit: https://github.com/globaleaks/GlobaLeaks/commit/1b8c48a6

The simple revert of part of the commit does fix the issue.
