### ISSUE TITLE
Improve install script to proxy Tor repository trough GlobaLeaks one to bypass blocking

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2115]
**Current behavior**
Certain countries block Tor, and we got feedback of installation failure on apt-get update from UAE that block deb.torproject.org, thus making the overall GlobaLeaks installation to fail.

**Expected behavior**
This ticket is to implement a workaround by proxying the repository deb.torproject.org trough http://deb.globaleaks.org/deb.torproject.org/ subdirectory, effectively unblocking the installation of Tor Debian packages during installation where Tor https download is blocked.

The installation script will then configure this new URL under deb.globaleaks.org as Tor repository.

**Comment by fpietrosanti** [comment]
Related to #2068

**Comment by evilaliv3** [comment]
Deprecated since the whole application is packaged in order to use only the globaleaks repository and the official distribution repository.
