### ISSUE TITLE
Handle SSL handshake failure in ExternNetJobs

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#2116]
**Current behavior**

The latest version can throw the following failure:

```
Version: 2.72.11

twisted.web._newclient.ResponseNeverReceived
    A L{ResponseFailed} that knows no response bytes at all have been received.


Traceback (most recent call last):

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/base.py", line 76, in run
    yield self.operation()

ResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', 'ssl3_read_bytes', 'ssl handshake failure')]>]
```

Let's handle it, in ExternNetJob.

**Comment by evilaliv3** [comment]
@NSkelsey: agreed there is anyhow nothing we can do or anaylize better for the moment on this kind of error.

I've a bit fear that all this notification bypass on the long run may lead to just hide possible bugs but we will eventually cope with this offering the admin to recheck failures on the platform because anyhow the exception will be logged.

\cc @fpietrosanti

**Comment by NSkelsey** [comment]
The ResponseNeverReceived failure of external network failure is only thrown when the `connectionLost` method of a `HTTPClientParser` while the `_everReceivedData` property is still `false`.

Ref: `twisted/web/_newclient.py:548`

From OpenSSL.SSL.Error wrapped inside of the failure, which arrived via a rejected deferred, the network failure is clear in this case. The `ssl handshake failure` could be caused by any number of external factors.

From [section 7.2](https://tools.ietf.org/html/rfc5246#section-7.2) of the TLS 1.2 spec we can see that `handshake_failure`s are fatal. 

The failure is thrown within the [ssl3_read_bytes](https://github.com/openssl/openssl/blob/master/ssl/record/rec_layer_s3.c#L1143) function within openssl. That function while processing packets and constructing valid message frames will raise `SSL_F_SSL3_READ_BYTES` errors whenever it encounters unexpected input.

This indicates to me that the other side of the network connection is occasionally providing garbage on machines that are running SSLv3 instead of TLS1.2. A look at deb.globaleaks.org shows that it is accepting connections via SSLv3. So this is totally resonable failure to encounter

```bash
openssl s_client -debug -connect deb.globaleaks.org:443
...
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
...
```

**Comment by NSkelsey** [comment]
Closing for now.
