### ISSUE TITLE
Bug in update notification sending notification with the same version of "installed/latest"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2120]
**Current behavior**
I received this notification by email with the installed version:

Dear Fabio Pietrosanti (Whistleblowing Solutions),

A software update is available.
It is good security practice to keep the platform up to date.

Installed version: 2.72.14
Latest version: 2.72.14

To learn about new features and bug fixes in the new version consult the change log at: https://www.globaleaks.org/r/changelog
For instructions on software updates, please refer to the documentation at: https://www.globaleaks.org/r/upgrade-guide

Kind regards,
XXXXXXXXX

**Comment by NSkelsey** [comment]
@fpietrosanti please use the issue template. What is the actual version of the node?

**Comment by fpietrosanti** [comment]
@NSkelsey eh, i don't know the version installed, it was the antimatch-fixing one, just got this email being one of the test-recipient

**Comment by evilaliv3** [comment]
I confirm the issue received on some of the nodes i'm managing.

Going to investigate this issue tonight.

**Comment by evilaliv3** [comment]
Issue fixed, will be shipped in 2.72.16

At the base of the failure the fact that the check on the latest version was taking in consideration just the previous check but not that the node could have been already updated to the the latest release; this is the case immediately after an update.
