### ISSUE TITLE
Receiver tip does not show receiver list when context.show_recipients_display is toggled

### ISSUE THREAD

**Issue by NSkelsey** [globaleaks/GlobaLeaks#2122]
**Current behavior**

An adopter's platform is not displaying the receivers attached to a specific tip for contexts that have turned show_recipients_display off and then back on.

**Expected behavior**

Tips should show receivers when the context setting is selected.

**Steps to reproduce the problem or feature illustration**

1) Migrate a node with context.show_recipients_display set to false.

2) Set it to true for a context.

3) Create a submission.

4) Observe the receivers are not displayed.

**GlobaLeaks version:**

v2.72.15

**Comment by NSkelsey** [comment]
The issue is on the receiver side.

**Comment by evilaliv3** [comment]
Issue fixed with release 2.72.16
