### ISSUE TITLE
Can't delete voices in the questionnaire

### ISSUE THREAD

**Issue by faffa42** [globaleaks/GlobaLeaks#2126]
When configuring the questionnaire, 

on a question, if delete is pressed it would expand or close the relative window without deleting it. Experienced with some checkboxes so far

**Comment by evilaliv3** [comment]
@faffa42: could you retry the following?

- 1. Open your question
- 2. Delete your checkbox clicking on the red X
- 3. Click the 'Save' button on the Field.

i've the doubt that you could be missing to perform the third operation above.

**Comment by NSkelsey** [comment]
@evilaliv3 its possible the `data-ng-click` is missing a needed `$event.preventDefault()`

@faffa42 what version of GL are you running?

**Comment by faffa42** [comment]
Hi Nick, it's 2.72.15 here

**Comment by evilaliv3** [comment]
@NSkelsey: already fixed going to commit the fix in a bit.

**Comment by evilaliv3** [comment]
Fix released in version 2.72.19
