### ISSUE TITLE
grunt protractor_coverage doesn' t work

### ISSUE THREAD

**Issue by humanitiesNerd** [globaleaks/GlobaLeaks#2138]
**Current behavior**

This happens when running `grunt protractor_coverage` in `GlobaLeaks/client`

```
[12:05:48] E/direct - Error code: 135
[12:05:48] E/direct - Error message: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
[12:05:48] E/direct - Error: Could not find update-config.json. Run 'webdriver-manager update' to download binaries.
```

**Expected behavior**
I expected the client tests to run

It may be something very simple but I am new to nodejs so I' m not sure

**Steps to reproduce the problem or feature illustration**
Follow the instructions for preparing a development setup step by step.
This is raised by the step for running tests in the client folder

**What is the motivation or use case for changing the behavior?**
I connected to the web site manually and browsed it briefly so it seems to work
But I'd still prefer the tests to run flawlessly

**GlobaLeaks version:**
I don' t know, I'm writing this on 13th december 2017

**Browser:**
doesn' t apply

**Server Operating System and Version (if applicable):**
Ubuntu 16.04.3

**Client Operating System and Version (if applicable):**
Ubuntu 16.04.3

**Comment by evilaliv3** [comment]
In order to run the tests with protractor, protractor need to first download it's browser drivers.

you can make it by issuing the command:
```./node_modules/protractor/bin/webdriver-manager update```

(for issuing the above commands you should be inside the client directory)

**Comment by humanitiesNerd** [comment]
Thanks

I did that and I get

```
...
[11:49:05] I/launcher - Running 1 instances of WebDriver
[11:49:05] I/direct - Using ChromeDriver directly...
[11:49:05] E/launcher - unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.34.522913 (36222509aa6e819815938cbf2709b4849735537c),platform=Linux 4.10.0-28-generic x86_64)
[11:49:05] E/launcher - WebDriverError: unknown error: cannot find Chrome binary
...

```

**Comment by evilaliv3** [comment]
You are welcome @humanitiesNerd 

Probably you do not have Chrome installed in your system? 

try with ```sudo apt-get install chromium-browser```

**Comment by fpietrosanti** [comment]
Are there any kind of dependency checking that can be done before starting that procedure, to communicate what's missing?

**Comment by evilaliv3** [comment]
nope @fpietrosanti and it would not make that much sense, but we can add some preliminar commands to make this work out of the box.

but currently all this aspected are managed best effort and there has been never any investment in this documentation.

**Comment by humanitiesNerd** [comment]
@evilaliv3 thanks again

I installed chromium-browser and now I get this

```
~$ grunt protractor_coverage
grunt-cli: The grunt command line interface (v1.2.0)

Fatal error: Unable to find local grunt.

If you're seeing this message, grunt hasn't been installed locally to
your project. For more information about installing and configuring grunt,
please see the Getting Started guide:

http://gruntjs.com/getting-started
```

Also
```
:~$ which grunt
/usr/bin/grunt
```

I' m not sure what is going on here

The installation of Chromium made the global grunt unsuitable ? 
How so ?

**Comment by humanitiesNerd** [comment]
I' m sorry for the bothering, the frontend stuff is not exactly my thing

**Comment by evilaliv3** [comment]
```sudo npm install -g grunt-cli``` is the command that i think you should issue.

I would recomend you to follow precisely the guide https://github.com/globaleaks/GlobaLeaks/wiki/setting-up-globaleaks-development-environment.

This would help us to fix that guide for the benefit of all the users.

Thank you!

**Comment by humanitiesNerd** [comment]
2017-12-15 16:45 GMT+01:00 Giovanni Pellerano <notifications@github.com>:

> sudo npm install -g grunt-cli is the command that i think you should
> issue.
>
> I would recomend you to follow precisely the guide
> https://github.com/globaleaks/GlobaLeaks/wiki/setting-up-
> globaleaks-development-environment.
>
> This would help us to fix that guide for the benefit of all the users.
>
> Thank you!
>

Ok, I managed to run the tests on the frontend right now, I saw Chrome
popping up and forms being filled in.

Startig from now, I can successfully run the tests both on the backend and
on the client

Thanks !

**Comment by evilaliv3** [comment]
Great!

which kind of feature are you interested to develop? 
is there something i can help you on?

**Comment by humanitiesNerd** [comment]
@evilaliv3 for now I'm busy with something else, I hope to be back on Globaleaks soon

Anyway, I think I'd prefer to start from the backend

Specifiically, I'm interested in how to set up a proper workflow

I see you use an IDE, how do you connect your IDE to the server process ?

My dream is to have a prompt and to work interactiively with the server while it's running

Lisp people call that a REPL (Read Evaliate Print Listen or something)

How are these things done iin Python, these days ?
