### ISSUE TITLE
Introduce support for Privacy Policy

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2145]
**Current behavior**
Any website, especially those managing confidential information such as whistleblowing sites, must have a clearly documented privacy policy in order to comply with data protection law and regulations.

**Expected behavior**
This ticket is to introduce support for Privacy Policy in GlobaLeaks.
The software should provide the ability to:
- Either up-load a pdf as a privacy policy document
- Either to copy-paste in a textbox the privacy policy

The Privacy Policy must be visible from within the footer from #2144 only when juridical ownership information are defined #2143 .

The admin interface should provide a section to enable/display/configure the privacy policy.

The Privacy Policy document text support a variable to describe the ${DATARETENTION} configured value, that can be re-used within the policy document.

It should be possible to configure the Privacy Policy to be a warning that the whistleblower must accept before proceeding.

**Comment by fpietrosanti** [comment]
Also required for EAT project accordingly to the GDPR compliance requirement defined as per:
"Furthermore, the Policy should be published in all the pages of the Website with the
Whistleblowing Mailbox; usually a link to the Policy is published at the bottom of every page of
the Website."

**Comment by evilaliv3** [comment]
Deprecated by:
- Current Terms and Conditions feature of questionnaires
- https://github.com/globaleaks/GlobaLeaks/issues/3510 for internal users
