### ISSUE TITLE
Custom field validation with regular expression doesn't work

### ISSUE THREAD

**Issue by PiemP** [globaleaks/GlobaLeaks#2150]
**Current behavior**
When I insert a regular expression like "^([a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12})$" or "/^([a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12})$/" or "/^([a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12})$/gi" in the field validation of a questionnaire I've receive an error:

https://docs.angularjs.org/error/ngPattern/noregexp?p0=validator&p1=%7B%22type%22:%22unicode%22,%22id%22:%229037f596-f73b-45e5-97ee-b53d1140889f%22,%22value%22:%22%5E(%5Ba-z0-9%5D%7B8%7D-%5Ba-z0-9%5D%7B4%7D-%5Ba-z0-9%5D%7B4%7D-%5Ba-z0-9%5D%7B4%7D-%5Ba-z0-9%5D%7B12%7D)$%22,%22name%22:%22regexp%22%7D&p2=%3Cinput%20id%3D%22step-0-field-0-0-input-0%22%20name%3D%22input-0%22%20class%3D%22form-control%20inputelem%20ng-pristine%20ng-untouched%20ng-valid%22%20data-ng-init%3D%22maxlength%20%3D%20field.attrs.max_len.value%20%3E

Sorry for my written english. I hope is a real bug and not a problem generated by my fault. 

**Expected behavior**
The field validation with the custom instruction 

**Steps to reproduce the problem or feature illustration**
Set up a custom field validation with a regular expression

**GlobaLeaks version:**
v. 2.72.30

**Browser:**
Chrome 63.0.3239.132
Firefox 57.0.4

**Server Operating System and Version (if applicable):**
Debian (8.10)

**Client Operating System and Version (if applicable):**
Windows 10 Pro (version 1709)

**Comment by fpietrosanti** [comment]
Hello, may i ask which is an example entity you are trying to validate, in order to replicate and test it? Tnx

**Comment by PiemP** [comment]
I try to validate a code like this: 

6d9dc139-4e99-40b0-9d8b-f48431c8e012

But I think is not important what I try to validate. I believe that the code who pass the regular expression to angularjs pass all of this structure:

{
"type": "unicode",
"id": "9037f596-f73b-45e5-97ee-b53d1140889f",
"value": "^([a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12})$",
"name": "regexp"
}

And not the regular expression only and angularjs return an error (the link in the first message). 

The structure I've attached to this message is taken from the json file generated by the questionnaire export operation.

Sorry for my written english I hope is understanble.

Thank you.

**Comment by evilaliv3** [comment]
Thanks @PiemP,

I'm going to perform some tests about this and i will report the updates on this ticket.

**Comment by evilaliv3** [comment]
Bug confirmed, it affect the client only. Going to produce a patch that will be included in release  2.72.32
