### ISSUE TITLE
tor setup

### ISSUE THREAD

**Issue by humanitiesNerd** [globaleaks/GlobaLeaks#2157]
**Current behavior**
when I launch the server I see these lines in the terminal

```
2018-01-31 18:42:31+0100 [-] Starting factory <txsocksx.client.SOCKS5ClientFactory instance at 0x7fc16a06cbd8>
2018-01-31 18:42:31+0100 [-] Starting factory <txsocksx.client.SOCKS5ClientFactory instance at 0x7fc16a027cf8>
2018-01-31 18:42:31+0100 [-] [E] Failed to initialize Tor connection; error: Unable to access /var/run/tor/control; manual permission recheck needed
2018-01-31 18:42:37+0100 [-] Stopping factory <txsocksx.client.SOCKS5ClientFactory instance at 0x7fc16a06cbd8>
2018-01-31 18:42:39+0100 [-] Stopping factory <txsocksx.client.SOCKS5ClientFactory instance at 0x7fc16a027cf8>
2018-01-31 18:42:41+0100 [-] Starting factory <txsocksx.client.SOCKS5ClientFactory instance at 0x7fc16a0e2c20>
2018-01-31 18:42:49+0100 [-] Stopping factory <txsocksx.client.SOCKS5ClientFacto
```

I also experience a problem in running the tor browsers, as you can see in this picture
![under attack](https://user-images.githubusercontent.com/283791/35639311-1f68ea56-06ba-11e8-96bd-9771a3afec08.png)

I hopend to be able to go through the setup wizard, but without tor I' m not allowed, as you can see here
![no_wizard](https://user-images.githubusercontent.com/283791/35639346-3d0567b0-06ba-11e8-93dd-1e14808fb506.png)

**Expected behavior**
The expected behaviour is a working tor and a working setup wizard

**Steps to reproduce the problem or feature illustration**
I installed tor with apt-get
I launch the Globaleaks backend following the Gloabaleaks instructions

**What is the motivation or use case for changing the behavior?**
doesn' t apply

**GlobaLeaks version:**
I checked out the repo in december
I didn't git pulled since then

**Browser:**
it' s the Firefox provided by the Ubuntu 16.04 installation

**Server Operating System and Version (if applicable):**
it' s a Ubuntu 16.04 installation

**Client Operating System and Version (if applicable):**
it' s a Ubuntu 16.04 installation

Thanks

**Comment by fpietrosanti** [comment]
That's a development environment, not a production environment right where Tor has been configured by the GlobaLeaks post-installation debian script right?

**Comment by humanitiesNerd** [comment]
it' s a dev env, not a production one, yes

I don' t know if tor has been configured by the GlobaLeaks post-installation debian script

I could check. Just tell me how

**Comment by fpietrosanti** [comment]
Check if use user "globaleaks" has been added to the "group" debian-tor, so that it have the permission to run it:
X:~#  ls -arlt /var/run/tor/control
srw-rw---- 1 debian-tor debian-tor 0 Jan 25 17:28 /var/run/tor/control
X:~# grep debian-tor /etc/group
debian-tor:x:114:globaleaks

**Comment by humanitiesNerd** [comment]
the result is

`debian-tor:x:129:`

**Comment by fpietrosanti** [comment]
Then, add the user "globaleaks" to that group or the user you are running the GlobaLeaks backend, so the process will be able to connect and speak to Tor trough it's /var/run/tor/control socket

**Comment by humanitiesNerd** [comment]
ahem...

I can' t find the user "globaleaks"

I listed the users with this line
`cut -d: -f1 /etc/passwd`

and I couldn' t see the "globaleaks" user


So, to be sure I grepped the result like this
cut -d: -f1 /etc/passwd | grep globaleaks

and there' s no globaleaks user

This is the complete list of users

```
root
daemon
bin
sys
sync
games
man
lp
mail
news
uucp
proxy
www-data
backup
list
irc
gnats
nobody
systemd-timesync
systemd-network
systemd-resolve
systemd-bus-proxy
syslog
_apt
messagebus
uuidd
lightdm
whoopsie
avahi-autoipd
avahi
dnsmasq
colord
speech-dispatcher
hplip
kernoops
pulse
rtkit
saned
usbmux
catonano
debian-tor
```

**Comment by evilaliv3** [comment]
@humanitiesNerd could you clarify about the step used for installing and running the backend?

if you have a development environment and you are lunching globaleaks with your user with username "XXX" is "XXX" that should be added to the debian-tor group. \cc @fpietrosanti

**Comment by humanitiesNerd** [comment]
of course I am using my user to launch the backend
Yeterday evening I was probably a bit tired, I apologize

I' ll be able to check this only later today

Thanks so much

**Comment by humanitiesNerd** [comment]
I managed to add my user (catonano) to the debian-tor group

```
catonano@catonano-ubuntu:~$ grep debian-tor /etc/group
debian-tor:x:129:catonano
```


but the sympthom persists

```
...
2018-02-08 19:33:39+0100 [-] - [LOCAL HTTP]	--> http://127.0.0.1:8082
2018-02-08 19:33:39+0100 [-] - [LOCAL HTTP]	--> http://127.0.0.1:8083
2018-02-08 19:33:39+0100 [-] - [REMOTE HTTP]	--> http://0.0.0.0
2018-02-08 19:33:40+0100 [-] Starting factory <txsocksx.client.SOCKS5ClientFactory instance at 0x7fb465776d40>
2018-02-08 19:33:40+0100 [-] Starting factory <txsocksx.client.SOCKS5ClientFactory instance at 0x7fb465776758>
2018-02-08 19:33:40+0100 [-] [E] Failed to initialize Tor connection; error: Unable to access /var/run/tor/control; manual permission recheck needed
2018-02-08 19:33:44+0100 [-] Stopping factory <txsocksx.client.SOCKS5ClientFactory instance at 0x7fb465776758>
2018-02-08 19:33:45+0100 [-] Stopping factory <txsocksx.client.SOCKS5ClientFactory instance at 0x7fb465776d40>
```

This is something I attempted (to no avail)
```

catonano@catonano-ubuntu:~$ sudo ufw allow 9151
Regole aggiornate
Regole aggiornate (v6)
```



And this is the mentioned unaccessible file

```

catonano@catonano-ubuntu:~$ ls -lha /var/run/tor/control
srw-rw---- 1 debian-tor debian-tor 0 feb  8 19:26 /var/run/tor/control
```

**Comment by gabrieloandco** [comment]
I was having the same problem in Ubuntu 17 and 16, here is the fix:
First uninstall tor and install the latest version:
```
sudo apt-get purge tor
deb http://deb.torproject.org/torproject.org [distro] main
deb-src http://deb.torproject.org/torproject.org [distro] main
gpg --keyserver keys.gnupg.net --recv A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | sudo apt-key add -
$ apt update
$ apt install tor deb.torproject.org-keyring
```


Then you should edit the config to enable control protocol:
`sudo /etc/tor/torrc`
Remove the `#` character from lines` ControlPort 9051` and `CookieAuthentication 1` (line ~57)

Restart Tor
`/etc/init.d/tor restart`

Add permission yourself to read the auth cookie by 
`usermod -a -G debian-tor [yourlinuxuser]`
this should work in ubuntu, however if the permission doesn't exist you can check by:
`ls -al /var/run/tor/control.authcookie`
Logout/Login with your user to apply group changes

Now instead of the error you should see something like this:
```
2018-02-25 16:11:29+0100 [-] [I] [1] Creating new onion service
2018-02-25 16:11:29+0100 [TorControlProtocol,client] Created hidden-service at iubqrpjaqqaw6mpq.onion
2018-02-25 16:11:29+0100 [TorControlProtocol,client] Created 'iubqrpjaqqaw6mpq.onion', waiting for descriptor uploads.
```

**Comment by humanitiesNerd** [comment]
@gabrieloandco 

thanks

these were already in the sources list
deb http://deb.torproject.org/torproject.org [distro] main
deb-src http://deb.torproject.org/torproject.org [distro] main

but the control protocol was not enabled

Now I don' t see that error in the terminal anymore

But the torbrowser keeps not working

**Comment by evilaliv3** [comment]
Closing the ticket as outdated.
