### ISSUE TITLE
Automate configuration of Hostname, if condition applies

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2159]
**Current behavior**
Actually, when a user access GlobaLeaks at wizard time using a valid hostname/domain name, it yet have to configure a valid "Hostname".

**Expected behavior**
This ticket is to detect if the user is accessing the whistleblowing site using an hostname and pre-configure it in GlobaLeaks.

This is a pre-requisite of #2158

**Comment by evilaliv3** [comment]
This has been already implemented in previous development.

currently the hostname is defined by the hostname accessed by the user during the wizard.
