### ISSUE TITLE
Improve login page accessibility with /login URL

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2160]
**Current behavior**
Actually if a user need to access the recipient or admin platform, he is said to access /login, but the platform is only accessible with the AngularJS /#/login and that's a usability issue.

If user access /login it receive this error:
{"error_message": "Resource not found", "error_code": 6, "arguments": []}

**Expected behavior**
This ticket is to let the system be accessible with /login giving a redirect to /#/login .

**Comment by fpietrosanti** [comment]
Also for /admin

**Comment by evilaliv3** [comment]
implemented! i've made the same also for /submission

**Comment by ZorakIT** [comment]
Hello Fabio and Giovanni,
can also be done for /password too?

Thanks

**Comment by evilaliv3** [comment]
Hello @ZorakIT, this could be definitely done if useful.

Would you please please clarify about the use case?

**Comment by ZorakIT** [comment]
Hello @evilaliv3,
a customer uses a proxy that can't handle the # in the URL so when they receive password reset emails they don't work

Thanks
