### ISSUE TITLE
No requirements written for artful in setup

### ISSUE THREAD

**Issue by gabrieloandco** [globaleaks/GlobaLeaks#2164]
**Current behavior**
`cp: cannot stat 'requirements/requirements-artful.txt': No such file or directory`

**Expected behavior**

The setup of the development enviroment should run without errors

**Steps to reproduce the problem or feature illustration**
Running setup_development_environment.sh in Ubuntu 17.10 (Artful)

**Possible Solution**
Create requirements-artful.txt in GlobaLeaks/backend/requirements with same values as  requirements-xenial.txt

**GlobaLeaks version:**
 v2.67.5

**Client Operating System and Version**
Ubuntu 17.10

**Comment by evilaliv3** [comment]
Thanks you @gabrieloandco 
Actually in the software we generally include official support only for Long Term Support version of the platform.

The next version that will be supported is Ubuntu 18.04 (bionic) and the activities for its retesting and bugfixing are tracked by: https://github.com/globaleaks/GlobaLeaks/issues/2165
