### ISSUE TITLE
Add support for bionic the upcoming LTS version of Ubuntu: 18.04 (bionic)

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2165]
This ticket is to keep track of the activities of testing and eventual bugfixing for making possible to install GlobaLeaks on the upcoming LTS version Ubuntu 18.04 (bionic) that will be released in Aprl 2018.

**Comment by evilaliv3** [comment]
@NCommander: do you think feasible to get globaleaks officially inside bionic?

which steps do you recommend for making this possible?

**Comment by NCommander** [comment]
We're likely too late to reach bionic, as it's past feature freeze (https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule); it's *possible* a feature freeze exception (FFE) could be granted to let it in. In general, it's doable abet some pain and suffering.

However, being in archive means the release of the software would essentially be frozen in time. Stable release updates/security fixes (in general) don't typically allow pushing wholesale new versions. There are also options to use Juju Charms (https://jujucharms.com) which can be rapidly deployed in the cloud.

If you want to be in archive, the best way to do so is to have an LTS branch and then support that branch for the life of LTS. Interim releases (aka, non-LTS ones) can act as stepping stones to the next major release but a lot of folks really like stabilizing on an LTS.

**Comment by fpietrosanti** [comment]
Regardless being included officially by Ubuntu archive, useful liks on distributions:
On juju charms implementation #1841
On Snap/Ubuntu Core implementation #2134 
On having an icon on desktop-programs on ubuntu #1964 
On having screenshots of the apps in the package in the graphical installer #1965

**Comment by NCommander** [comment]
As far as distribution with Ubuntu, it mostly depends on what the best fit for the typical GL deployment. I've done some work with charms, but I left Canonical after we created Core but before Snaps were a thing so this is mostly what I remember and Googling.

Charms work well for cloud deployments (i.e. EC2, or a local cloud via MAAS), though I'm unclear how common deploying GL to a cloud environment is given the inherent privacy issues with it.

Snaps on the other hand are interesting. However, they're essentially designed to be self-contained, and when they're removed/upgraded, data goes with them. Snap 2.x appears to have an unversioned data directory, but I'm not sure how it interacts with upgrades. Normally, this wouldn't be a problem as most web applications can use *SQL databases and thus are unaffected by having application data deleted. GL as far as I can tell only supports SQLite, though it probably isn't a big deal to get it to run on Postgres or MySQL given the underlying SQLAlchemy code.

As for desktop/screenshots, that's generally only possible for "in archive" apps which goes back to the point of dealing with Ubuntu's stable release update policy.

**Comment by NCommander** [comment]
Bionic support landed.
