### ISSUE TITLE
modal on submission can close without select an option

### ISSUE THREAD

**Issue by damian-garrido** [globaleaks/GlobaLeaks#2168]
**Current behavior**

when you wanna to send a submission without use Tor Browser, a modal appear warning you about that. this modal have 4 options and a disabled button which is active when you select the correct option, but, if you click on the button without select and option, the modal dismiss and you can continue with the submission

**Expected behavior**

the modal do not be closed

**Steps to reproduce the problem or feature illustration**

* go to /#/submission without Tor Browser
* no select any option and press the disabled button
* the modal close

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

2.72.28

**Browser:**

Firefox

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

Fedora

**Comment by evilaliv3** [comment]
Thank you @damian-garrido !

Actually i've already retested what you reported and i confirm the presence of this bug.

I'm about to produce a patch and i will update the ticket when ready.

**Comment by evilaliv3** [comment]
The bug lies in the usage of angular data-ng-disabled on a link; It seams that when applied on a link the directive do not disable the directive data-ng-click.

I'm producing a patch where in place of the <a> tag will be used the <button> tag.

**Comment by evilaliv3** [comment]
Fixed, the patch will be shipped out with release 3.0.1
