### ISSUE TITLE
gl-admin TypeError: 'bool' object has no attribute '__getitem__' 

### ISSUE THREAD

**Issue by PiemP** [globaleaks/GlobaLeaks#2169]
**Current behavior**
when i run in the terminal the command:

gl-admin getvar reachable_via_web 

it returns:

ERROR
Traceback (most recent call last);
  File "/usr/bin/gl-admin", line 292, in <module> args.func(args)
  File "/usr/bin/gl-admin", line 181, in get_var raise e
TypeError: 'bool' object has no attribute '__getitem__' 

I've notice this error because the globaleaks service start in sandboxing mode and in the syslog I've seen that: 

Feb 23 11:34:23 globaleaks1 systemd[1]: Started LSB: Start the GlobaLeaks server..
Feb 23 11:34:23 globaleaks1 systemd[1]: Reloading.
Feb 23 11:34:23 globaleaks1 systemd[1]: Started ACPI event daemon.
Feb 23 11:34:23 globaleaks1 systemd[1]: Listening on ACPID Listen Socket.
Feb 23 11:34:23 globaleaks1 systemd[1]: Activated swap /dev/mapper/vg-lv_swap.
Feb 23 11:34:23 globaleaks1 systemd[1]: Found device /dev/mapper/vg-lv_swap.
Feb 23 11:34:23 globaleaks1 systemd[1]: Mounted /.
Feb 23 11:34:23 globaleaks1 systemd[1]: Found device /sys/devices/virtual/block/dm-1.
Feb 23 11:34:23 globaleaks1 systemd[1]: Found device /dev/dm-1.
Feb 23 11:34:23 globaleaks1 systemd[1]: Found device /dev/disk/by-id/dm-name-vg-lv_swap.
Feb 23 11:34:23 globaleaks1 systemd[1]: Found device /dev/disk/by-id/dm-uuid-LVM-yUXAG0mqWmCgCumj9oSEItMobZyUD2fIRY4EH1VM5bcDa7sgXGSeiWJPcLH5sP25.
Feb 23 11:34:23 globaleaks1 systemd[1]: Found device /dev/disk/by-uuid/b58531ea-be50-44fa-b561-60ed44d3cf60.
Feb 23 11:34:23 globaleaks1 systemd[1]: Found device /dev/vg/lv_swap.
Feb 23 11:34:23 globaleaks1 systemd[1]: Activated swap /dev/dm-1.
Feb 23 11:34:23 globaleaks1 systemd[1]: Activated swap /dev/disk/by-id/dm-name-vg-lv_swap.
Feb 23 11:34:23 globaleaks1 systemd[1]: Activated swap /dev/disk/by-id/dm-uuid-LVM-yUXAG0mqWmCgCumj9oSEItMobZyUD2fIRY4EH1VM5bcDa7sgXGSeiWJPcLH5sP25.
Feb 23 11:34:23 globaleaks1 systemd[1]: Activated swap /dev/disk/by-uuid/b58531ea-be50-44fa-b561-60ed44d3cf60.
Feb 23 11:34:23 globaleaks1 systemd[1]: Activated swap /dev/vg/lv_swap.
Feb 23 11:35:01 globaleaks1 CRON[6313]: (root) CMD (command -v debian-sa1 > /dev/null && debian-sa1 1 1)
Feb 23 11:39:50 globaleaks1 systemd[1]: Stopping LSB: Start the GlobaLeaks server....
Feb 23 11:39:50 globaleaks1 systemd[1]: Failed to reset devices.list on /system.slice: Invalid argument
Feb 23 11:39:50 globaleaks1 systemd[1]: Failed to reset devices.list on /system.slice/system-tor.slice: Invalid argument
Feb 23 11:39:52 globaleaks1 globaleaks[6784]: WARNING: Missing Apparmor Sandboxing support
Feb 23 11:39:52 globaleaks1 globaleaks[6784]: Stopping GlobaLeaks daemon: globaleaks.
Feb 23 11:39:52 globaleaks1 globaleaks[6784]: Disabling GlobaLeaks Network Sandboxing...done.
Feb 23 11:39:52 globaleaks1 systemd[1]: Stopped LSB: Start the GlobaLeaks server..
Feb 23 11:39:55 globaleaks1 systemd[1]: Starting LSB: Start the GlobaLeaks server....
Feb 23 11:39:57 globaleaks1 globaleaks[6830]: WARNING: Missing Apparmor Sandboxing support
Feb 23 11:39:57 globaleaks1 globaleaks[6830]: Starting GlobaLeaks daemon: globaleaksEnabling GlobaLeaks Network Sandboxing...Bad argument `8083'
Feb 23 11:39:57 globaleaks1 globaleaks[6830]: Try `iptables -h' or 'iptables --help' for more information.
Feb 23 11:39:57 globaleaks1 globaleaks[6830]: Bad argument `8083'
Feb 23 11:39:57 globaleaks1 globaleaks[6830]: Try `iptables -h' or 'iptables --help' for more information.
Feb 23 11:39:57 globaleaks1 globaleaks[6830]: Bad argument `443'
Feb 23 11:39:57 globaleaks1 globaleaks[6830]: Try `iptables -h' or 'iptables --help' for more information.
Feb 23 11:39:57 globaleaks1 globaleaks[6830]: Bad argument `443'
Feb 23 11:39:57 globaleaks1 globaleaks[6830]: Try `iptables -h' or 'iptables --help' for more information.
Feb 23 11:39:57 globaleaks1 globaleaks[6830]: done.
Feb 23 11:39:58 globaleaks1 globaleaks[6830]: .
Feb 23 11:39:58 globaleaks1 systemd[1]: Started LSB: Start the GlobaLeaks server..

After a fix in the /etc/init.d/globaleaks file the error disappear but the service is accessible only on 127.0.0.1

**Expected behavior**
I don't know

**Steps to reproduce the problem or feature illustration**
upgrade from 2.7.32 to 3.0.0

**GlobaLeaks version:**
3.0.0

**Browser:**
every browser

**Server Operating System and Version (if applicable):**
Debian 8.10

**Comment by evilaliv3** [comment]
Bug confirmed;

The failure lies in commit: https://github.com/globaleaks/GlobaLeaks/commit/a982939003761ca3adeb8a27588552ad03d86316

gl-admin should be aligned to the implementation of the Config model.

**Comment by evilaliv3** [comment]
The bug should be fixed, the patch will be shipped in release 3.0.1

**Comment by evilaliv3** [comment]
@PiemP: what to you get if you issue ```gl-admin getvar reachable_via_web``` ?

**Comment by PiemP** [comment]
![sketch](https://user-images.githubusercontent.com/2736009/36680662-b2691a5e-1b16-11e8-8b34-8c1161e2a224.png)

**Comment by evilaliv3** [comment]
@PiemP apparently your binary in /usr/bin/gl-admin is not up to date with latest version.

Are you sure you are sunning on 3.0.2?

**Comment by PiemP** [comment]
I've done the update in this way: 

- archive /var/globaleaks with tar -zcvf globaleaks.tar.gz /var/globaLeaks

- install globaleaks using regular script
```
wget https://deb.globaleaks.org/install-globaleaks.sh
chmod +x install-globaleaks.sh
./install-globaleaks.sh
```

In this image I show to you the difference between the master branch on github (left side) and the version on my server (right side)

![sketch](https://user-images.githubusercontent.com/2736009/36682127-9be36ace-1b1a-11e8-8cf9-ae96d9c8e056.png)

**Comment by PiemP** [comment]
installed the version 3.0.5 all working well 👍 

![sketch](https://user-images.githubusercontent.com/2736009/36795498-7715c5fe-1ca3-11e8-8303-8af1d9f18efa.png)
