### ISSUE TITLE
Add support for stretch the current latest LTS version of Debian: 8.10

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2171]
This ticket is to keep track of the activities of testing and eventual bugfixing for making possible to install GlobaLeaks on the current LTS version Debian 8.10 (stretch) that was be released in June 2017.

**Comment by evilaliv3** [comment]
This tickets comes in supported to some of our users like @PiemP that are currently experimenting on Debian jessie, the previous LTS version of debian for which we are still offering a poor package using PIP.

**Comment by evilaliv3** [comment]
@Piemp: we just released a package for stretch (http://deb.globaleaks.org/stretch/) and updated the install script.

When you want you can update your setup to it and benefit a fulll debian package with no pip dirties.

To migrate the best path to follow is:
- archive /var/globaleaks with ```tar -zcvf globaleaks.tar.gz /var/globaLeaks```
- setup stretch
- extract the archive in /var/globaleaks before installing globaleaks
- install globaleaks using the regular install script

during the first bootup globaleaks will then recognize your existing data and use it

**Comment by PiemP** [comment]
I've updated my globaleaks installation on my Debian 8.10 system and it's working well...no more the #2170 issue...I have the #2169 . Have I done something wrong?

**Comment by PiemP** [comment]
the 3.0.5 version fix the #2169. installation by apt-get working well from 3.0.2 to 3.0.5

**Comment by evilaliv3** [comment]
Thank you for the confirmation @PiemP
