### ISSUE TITLE
Changelog not updated from 3.0.0 to 3.0.2

### ISSUE THREAD

**Issue by alepartenza** [globaleaks/GlobaLeaks#2176]
After update Globaleaks from 3.0.0 to 3.0.2, changelog page are not updated.

![schermata 2018-02-26 alle 12 44 57](https://user-images.githubusercontent.com/4155187/36668861-f29dc832-1af2-11e8-9665-e4fd26585a6e.png)

**Comment by evilaliv3** [comment]
Thank you @alepartenza 

I confirm this bug probably related to a failure during the packaging process.

**Comment by evilaliv3** [comment]
Fixed, the patch will be shipped out today with release 3.0.3
