### ISSUE TITLE
Add January/2018 Penetration Test reports to Github Wiki

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2179]
**Current behavior**
This ticket is to add the Penetration test on GlobaLeaks that has been done in January 2018 to the archive https://github.com/globaleaks/GlobaLeaks/wiki/Penetration-Tests uploading the full PDF and linking the related fixed/open issues.

**Comment by evilaliv3** [comment]
There you go:
- https://github.com/globaleaks/GlobaLeaks/wiki/Penetration-Tests
- https://github.com/globaleaks/GlobaLeaks/wiki/Security-Audit-5:-Team-Subgraph
- https://drive.google.com/open?id=1GiHWMmOf5sJKpoM0o-OiSvOnqXq57wGL

About the two issues the first would not open a ticket as it has been already fixed and released.

For the second instead i'm about to create a ticket with the suggestion received by the Subgraph team.

**Comment by evilaliv3** [comment]
done!
