### ISSUE TITLE
Terms of service step's not work

### ISSUE THREAD

**Issue by alepartenza** [globaleaks/GlobaLeaks#2180]
GlobaLeaks version: 3.0.2

Terms of service step's not work:
![schermata 2018-02-26 alle 19 29 15](https://user-images.githubusercontent.com/4155187/36687991-66a39f12-1b2b-11e8-809b-65dd5dfc8a9f.png)

**Comment by evilaliv3** [comment]
Thank you for having notified this @alepartenza; let me look at the issue and i'll be back to you.

**Comment by evilaliv3** [comment]
Bug confirmed, i'm now working with the fix.

**Comment by evilaliv3** [comment]
Fix implemented, will be released by today with version 3.0.3
