### ISSUE TITLE
Unhandled  error in Deferred

### ISSUE THREAD

**Issue by gabrieloandco** [globaleaks/GlobaLeaks#2183]
**Current behavior**

When shutting down without connection this happens:
```
2018-02-27 13:32:47+0100 [-] Unhandled error in Deferred:
2018-02-27 13:32:47+0100 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/home/user/Installs/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 588, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/user/Installs/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 859, in _cbDeferred
	    self.callback(self.resultList)
	  File "/home/user/Installs/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 393, in callback
	    self._startRunCallbacks(result)
	  File "/home/userInstalls/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 501, in _startRunCallbacks
	    self._runCallbacks()
	--- <exception caught here> ---
	  File "/home/user/Installs/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 588, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/user/Installs/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 393, in callback
	    self._startRunCallbacks(result)
	  File "/home/user/Installs/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 494, in _startRunCallbacks
	    raise AlreadyCalledError
	twisted.internet.defer.AlreadyCalledError:
```

If we use set `defer.setDebugging(True)` (line 83, def shutdown `backend.py`) we will see:
```
2018-02-27 13:28:03+0100 [-] Unhandled error in Deferred:
2018-02-27 13:28:03+0100 [-] (debug:  C: Deferred was created:
.........................................................................................................
C:  File "/home/user/Installs/GlobaLeaks/backend/globaleaks/backend.py", line 89, in shutdown
	 C:    defer.DeferredList([d1, d2]).addCallback(d.callback)
	 C:  File "/home/user/Installs/GlobaLeaks/backend/glenv/local/lib/python2.7/site-packages/Twisted-16.0.0-py2.7-linux-x86_64.egg/twisted/internet/defer.py", line 826, in __init__
	 C:    Deferred.__init__(self)
	 I: First Invoker was:
	 I:  File "./bin/globaleaks", line 166, in <module>
	 I:    run_backend()
	 I:  File "./bin/globaleaks", line 152, in run_backend
	 I:    UnixApplicationRunner(config).run()

```
Then there is a problem in the defer on backend.py

**Expected behavior**

The program should shutdown cleanly.

**Steps to reproduce the problem or feature illustration**

Shutting down when there is no connection present when globaleaks was already run.

**What is the motivation or use case for changing the behavior?**

By [canceling the defer](http://twistedmatrix.com/documents/10.1.0/api/twisted.internet.defer.Deferred.cancel.html) we can avoid this exception,this would mean to add `d.cancel` to `def shutdown(self)` in `backend.py`:
```
    def shutdown(self):
        def _shutdown(_):
            self.state.orm_tp.stop()

        defer.setDebugging(True)
        d = defer.Deferred()
        d.addBoth(_shutdown)

        d1 = self.state.process_supervisor.shutdown()
        d2 = self.stop_jobs()
        d.cancel() #LINE ADDED
        defer.DeferredList([d1, d2]).addCallback(d.callback)
        reactor.callLater(30, d.callback, None)

        return d
```
This way the exception is [handled](http://twistedmatrix.com/documents/10.1.0/api/twisted.internet.defer.CancelledError.html).

**GlobaLeaks version:**

Last version

**Browser:**

Doesn't Apply

**Server Operating System and Version (if applicable):**
 
Doesn't Apply

**Client Operating System and Version (if applicable):**

Ubuntu 17.10 (Artful), Ubuntu 16.04 (Xenial)

**Comment by evilaliv3** [comment]
thank you @gabrieloandco!

could you please clarify about your analysis?

i'm unable to reproduce the bug you are reporting but i do not think that ```d.cancel()``` could be the solution.

let me explain what that code perform:
- it starts the shutdown
- it arms a timeout of 30 seconds so to kill the platform forcefully if it did not shut down gracefully.

if you perform a ```d.cancel()``` you are actually just immediately forcing the shut down, because on the cancel is attached the orm stop via the code ```d.addBoth(_shutdown)```

**Comment by gabrieloandco** [comment]
To reproduce the problem I ran without daemon one instance while having Internet , then I shut it down. Then I went off-line and ran another instance and shut it down with ^C, then an Unhandled error will be raised. When I did the change on the code and ran again there wasn't any unhandled errror.
 
However, probably as you said  there is a more elegant and useful way to handle the exception than just canceling the defer all together. To add an errback and using a error handler would do the trick:

```
    def shutdown(self):
        def _shutdown(_):
            self.state.orm_tp.stop()




        defer.setDebugging(True)
        d = defer.Deferred()

        def errorHandler(failure):
             failure.trap(SpamException, EggException)
             
             

        d.addBoth(_shutdown)
        d.addErrback(errorHandler)

        d1 = self.state.process_supervisor.shutdown()
        d2 = self.stop_jobs()
        defer.DeferredList([d1, d2]).addCallback(d.callback)
        reactor.callLater(30, d.callback, None)

        return d
```

**Comment by evilaliv3** [comment]
Thank you @gabrieloandco 

I debugged the issue in datail and understood what happens and implemented the above patch.

Basically if no connection is available the 30 seconds timeout is triggered.
At the trigger of the timeout d.callback() is called, that scatter the actual shutdown.
At the trigger of the shudtown d.callback() is called a second time and this causes the alreadyCalled error.

The patch i've produced ad a status flag to avoid to issue the callback twice.
