### ISSUE TITLE
upgrade from 2.67 to 3.05 fails

### ISSUE THREAD

**Issue by DrWhax** [globaleaks/GlobaLeaks#2186]
**Current behavior**

When attempting to upgrade Afri_Leaks to the latest version I run into the following problem:

```
Preparing to unpack .../globaleaks_3.0.5_all.deb ...
Creating backup of /var/globaleaks in /var/globaleaks/backups/globaleaks-3.0.5-1519828923.tar.gz
chown: invalid user: 'globaleaks:globaleaks'
dpkg: error processing archive /var/cache/apt/archives/globaleaks_3.0.5_all.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Selecting previously unselected package python-pam.
Preparing to unpack .../python-pam_0.4.2-13.2ubuntu2_amd64.deb ...
Unpacking python-pam (0.4.2-13.2ubuntu2) ...
Selecting previously unselected package python-serial.
Preparing to unpack .../python-serial_3.0.1-1_all.deb ...
Unpacking python-serial (3.0.1-1) ...
Selecting previously unselected package python-sqlalchemy-ext.
Preparing to unpack .../python-sqlalchemy-ext_1.0.11+ds1-1ubuntu2_amd64.deb ...
Unpacking python-sqlalchemy-ext (1.0.11+ds1-1ubuntu2) ...
Selecting previously unselected package torsocks.
Preparing to unpack .../torsocks_2.1.0-2_amd64.deb ...
Unpacking torsocks (2.1.0-2) ...
Selecting previously unselected package tor-geoipdb.
Preparing to unpack .../tor-geoipdb_0.3.2.9-1~xenial+1_all.deb ...
Unpacking tor-geoipdb (0.3.2.9-1~xenial+1) ...
Processing triggers for systemd (229-4ubuntu21.1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Errors were encountered while processing:
 /var/cache/apt/archives/globaleaks_3.0.5_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
For Professional Support requests please visit: https://www.globaleaks.org/contact/
Please report encountered issues to the Community Forum at https://forum.globaleaks.org
```

It seems it doesn't create the user and group, maybe this should be moved earlier to the installation script?

**Expected behavior**

It creates the user and grroup and the installation finishes without problem.

**Steps to reproduce the problem or feature illustration**

Move globaleaks directory from trusty to new server, install globaleaks and run into this issue.

**What is the motivation or use case for changing the behavior?**

I want a recent globaleaks version.e

**GlobaLeaks version:**

globaleaks                       2.67.4

**Server Operating System and Version (if applicable):**
 

Xenial 16.04 (xenial)

**Comment by DrWhax** [comment]
```
chown: invalid user: 'globaleaks:globaleaks
```

I think it tries to chown too early, it doesn't create a user nor a group:

```
root@afrileakshs:/var/log# cat /etc/group | grep globaleaks
root@afrileakshs:/var/log# cat /etc/passwd | grep globaleaks
```

**Comment by evilaliv3** [comment]
Thanks @DrWhax 

Actually the issue is caused by the addition of a backup procedure in debian.preinst.

The backup script create some directorries and fixes the permissions;
If this is done on a system with GlobaLeaks already installed the procedure will work fine.
If instead one is migrating the node and installing globaleaks with an existing directory in /var/globaleaks the script will fail.

As a fix i'm about to move the code in preinst directly inside the postinst after the check and creation of the user/group.

**Comment by DrWhax** [comment]
Thank you!
