### ISSUE TITLE
Unable to access server after disabling SSL

### ISSUE THREAD

**Issue by charlesthompson916** [globaleaks/GlobaLeaks#2187]
I was in the process of removing the LetsEncrypt self signed SSL cert in order to install our Wild Card cert. After disabling SSL I am now unable to access the server via HTTP. Thank you for any help.

**Comment by evilaliv3** [comment]
Hello @charlesthompson916 

GlobaLeaks, when you enable HTTPS enforces strict transport security.
This depending on the browser may:
- accept from that moment on only HTTPS connections with no downgrade
- accept only the certificate that has been provided

this is generally what happens on Chrome. Firefox works a bit differently so right now you have two options:
- us a browser with which you never accessed globaleaks
- reset your browser in relation to HSTS (here a detailed explaination: https://www.thesslstore.com/blog/clear-hsts-settings-chrome-firefox/)

Please let us know if this fixed your issue!

**Comment by charlesthompson916** [comment]
Thank you for such a quick response. Unfortunately I receive the Apache2 Ubuntu default page.

**Comment by evilaliv3** [comment]
@charlesthompson916: i guess from what you are saying that the Azure VM by default enables Apache; if this is not the case maybe you installed it by yourself?

Perform a shutdown of Apache with ```/etc/init.d/apache2 stop``` and reboot GlobaLeaks with ```/etc/init.d/globaleaks restart```

**Comment by charlesthompson916** [comment]
Thanks! Shutting down Apache and rebooting the Globaleaks service did the trick. I am now attempting to apply our GoDaddy cert. Thanks again!

**Comment by evilaliv3** [comment]
Great @charlesthompson916 !

Let us know if you would find any defect or if you have any suggestion!
