### ISSUE TITLE
Introduce notification of new web signup and new site activation

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2196]
**Current behavior**
Actually when a new site is activated trough built-in signup feature, no notification is sent.

**Expected behavior**
This ticket is to send a notification of all new web signup and site activation events to admin configured email of root tenant.
The email should contain the basic data collected at signup time.

**Comment by NCommander** [comment]
Took a first stab pass at this with PR https://github.com/globaleaks/GlobaLeaks/pull/2224, but it's not ready to be merged yet as I wanted to make sure I was on the right track before committing more time to this.

 - Right now, an alert email is generated when a new tenant signs up for the system, though the hostname for the system needs to be explicately set else the email comes out [NOT CONFIGURED].

 - I likely need to add an option to disable this notification

 - A database migration is needed(?) to apply the new templates to existing installs.

 - The reason isn't sent in the email (or recorded by the backend at all as far as I can tell)

Right now, I'm slightly questioning if there's value in sending an email for both creation/activation just to reduce message spam, and what information should be sent to the instance admins when added. Thoughts/comments welcome.

**Comment by evilaliv3** [comment]
Thank you @NCommander 
i'm going to leave here some answers to your question and to leave some comments on the pull request if i will have any :)

1. on signup the mail notification should use data of the signup + data of the root tenant; if the multi-site instance will be configured for signup i expect the hostname will be configured so do not mind to this issue as it would not require any particular correction in relation to this ticket. perfect as you did in relation to this.
2. this is a topic is a general topic that i will handle out of the ticket. we need to come out for a solution for offering an automatic boolean to each feature in the software without requiring too much manual code at the addition of each new boolean.
3. no data migration is needed; we have automatic migrations that already manage the addition of variables like these; i've still to check your PR but the current migration code is able to recognize this condition and add the missing template :) yes! yey!
4. i would not add anything particular for this addition; eventually in a separate ticket we may discuss how to improve the testing of the templating system in general? 

as for the number of emails i get your concern of sending a new email notification on signup / activation of the platform.

probably the one needed is the signup and we may probably export the data of the signup to the admin of the node: subdomain name, surname, email, use case.
This would help supporting the user that is experimenting with the platform.
The mail as usual will be implemented with PGP if the multitenant instance will be configured to use PGP.

\cc @fpietrosanti

**Comment by evilaliv3** [comment]
Issue addressed by pull request https://github.com/globaleaks/GlobaLeaks/pull/2224 thanks to @NCommander
