### ISSUE TITLE
Ability to create more than one receiver with the same email address

### ISSUE THREAD

**Issue by Stephane-FILTRALA** [globaleaks/GlobaLeaks#2211]
**Current behavior**

Now you can only have one receiver with every email address. 

**Expected behavior**

We would like to be able to create a number of different receivers with just one email address that would work as a catch all for those different receivers. 

**What is the motivation or use case for changing the behavior?**

Would help us to manage groups of journalists that would line to have a "personal" globaleaks mailbox but won't manage it. All this mailboxes would be managed by just one journalist in the organization. This has been repeatedly requested to us by media organizations.

**Comment by evilaliv3** [comment]
@Stephane-FILTRALA: it is currently already possible to use the same email address for multiple recipients.

could you please clarify around your request?

This possibility will be probably removed in the future when we will implement the password recovery via email: https://github.com/globaleaks/GlobaLeaks/issues/113

**Comment by Stephane-FILTRALA** [comment]
@evilaliv3 Right! i just tried and it worked. Maybe we did something wrong as we were triying to make a lot of users/receivers with different name but same email.

Thank you I close the issue. 
What a beginning! 
Sorry

**Comment by evilaliv3** [comment]
You are welcome @Stephane-FILTRALA !
