### ISSUE TITLE
Uploaded files bigger than 1MB result corrupted

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2226]
Regression on file uploader prevents file upload of files bigger than 1MB.

The files results corrupter.

The bug has been reported by an adopter.

**Comment by evilaliv3** [comment]
I've verified and i'm able to confirm and reproduce the bug that apply to any file upload bigger than 1MB regardless of the usage of PGP.

I've already identified the cause and i'm about to finalize a patch that will be included starting from release 3.0.14.

**Comment by Stephane-FILTRALA** [comment]
Ok, thank you!
We will update when it is available.
Cheers!

**Comment by evilaliv3** [comment]
Release 3.0.14 is out!

\cc @Stephane-FILTRALA
