### ISSUE TITLE
Whistleblower identity label field and required checkbox ignored when modified

### ISSUE THREAD

**Issue by rglauco** [globaleaks/GlobaLeaks#2230]
**Current behavior**

When saving the Whistleblower identity fieldgroup, the PUT request states:
`
label:"Inserisci i dati relativi alla tua identità"
...
required:true
`

The response is:
`label:"Do you want to provide your identification information?"
...
required:false
`

On the client, the fields are correctly displayed, unless you exit and enter the Questionnaire `section.`

**GlobaLeaks version:**
3.0.17

**Browser:**
Firefox ESR 52.6.0

**Server Operating System and Version (if applicable):**
Ubuntu 16.04.04

**Client Operating System and Version (if applicable):**
Windows 7

**Comment by evilaliv3** [comment]
Thank you @rglauco for your feedback!

we will take care of retesting this and get back to you if the bug is confirmed and a patch is available!

**Comment by evilaliv3** [comment]
The bug is confirmed for what relates to the 'required' configuration.

For what concern label, description and hint it was designed to not be an editable field but we are considering to make this configurable as well.

I've about to push a patch that will be included in release 3.0.18
