### ISSUE TITLE
Unhandled exceptions Error Message: Error: [ngModel:nopromise] http://errors.angularjs.org/1.6.9/ngModel/nopromise?p0=undefined

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2233]
Platform:
Version: 3.0.16

URL: /admin/users

User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

Error Message: Error: [ngModel:nopromise] http://errors.angularjs.org/1.6.9/ngModel/nopromise?p0=undefined

Stacktrace:
[
  {
    "columnNumber": 76, 
    "fileName": "http://whistleblowing.local/js/scripts.js", 
    "source": "    at http://whistleblowing.local/js/scripts.js:18:76", 
    "lineNumber": 18
  }, 
  {
    "columnNumber": 318, 
    "fileName": "http://whistleblowing.local/js/scripts.js", 
    "source": "    at http://whistleblowing.local/js/scripts.js:307:318", 
    "lineNumber": 307
  }, 
  {
    "source": "    at r (http://whistleblowing.local/js/scripts.js:19:197)", 
    "columnNumber": 197, 
    "fileName": "http://whistleblowing.local/js/scripts.js", 
    "functionName": "r", 
    "lineNumber": 19
  }, 
  {
    "source": "    at e (http://whistleblowing.local/js/scripts.js:307:246)", 
    "columnNumber": 246, 
    "fileName": "http://whistleblowing.local/js/scripts.js", 
    "functionName": "e", 
    "lineNumber": 307
  }, 
  {
    "source": "    at Object.$$runValidators (http://whistleblowing.local/js/scripts.js:308:395)", 
    "columnNumber": 395, 
    "fileName": "http://whistleblowing.local/js/scripts.js", 
    "functionName": "Object.$$runValidators", 
    "lineNumber": 308
  }, 
  {
    "source": "    at Object.$processModelValue (http://whistleblowing.local/js/scripts.js:312:136)", 
    "columnNumber": 136, 
    "fileName": "http://whistleblowing.local/js/scripts.js", 
    "functionName": "Object.$processModelValue", 
    "lineNumber": 312
  }, 
  {
    "source": "    at Object.$$setModelValue (http://whistleblowing.local/js/scripts.js:312:391)", 
    "columnNumber": 391, 
    "fileName": "http://whistleblowing.local/js/scripts.js", 
    "functionName": "Object.$$setModelValue", 
    "lineNumber": 312
  }, 
  {
    "columnNumber": 124, 
    "fileName": "http://whistleblowing.local/js/scripts.js", 
    "source": "    at http://whistleblowing.local/js/scripts.js:204:124", 
    "lineNumber": 204
  }, 
  {
    "source": "    at m.$digest (http://whistleblowing.local/js/scripts.js:159:310)", 
    "columnNumber": 310, 
    "fileName": "http://whistleblowing.local/js/scripts.js", 
    "functionName": "m.$digest", 
    "lineNumber": 159
  }, 
  {
    "columnNumber": 156, 
    "fileName": "http://whistleblowing.local/js/scripts.js", 
    "source": "    at http://whistleblowing.local/js/scripts.js:162:156", 
    "lineNumber": 162
  }
]

**Comment by evilaliv3** [comment]
I've been able to reproduce this bug in 3.0.17.

The bug scatters if the user pastes a malformed key or random input.
