### ISSUE TITLE
Small typo in Italian Translation

### ISSUE THREAD

**Issue by rglauco** [globaleaks/GlobaLeaks#2234]
In [/client/pot/it.po](https://github.com/globaleaks/GlobaLeaks/blob/master/client/pot/it.po) and [/client/app/l10n/it.json](https://github.com/globaleaks/GlobaLeaks/blob/master/client/app/l10n/it.json) "Cancel": "Annula" - should be Annulla

**Comment by evilaliv3** [comment]
Thank you @rglauco for reporting this.

The translation has been fixed on https://www.transifex.com/otf/globaleaks/dashboard/ and will be included in release 3.0.18

![image](https://user-images.githubusercontent.com/217034/38024440-4fbfd89e-3285-11e8-9d4e-59acd90b7bda.png)
