### ISSUE TITLE
Field "Surname" not translatable

### ISSUE THREAD

**Issue by comradekingu** [globaleaks/GlobaLeaks#2238]
https://try.globaleaks.org/#/signup

![surname](https://user-images.githubusercontent.com/13802408/38101662-31c87420-3381-11e8-96aa-6b5554432fb0.png)

**Comment by evilaliv3** [comment]
Thank you @comradekingu for reporting this.

Actually the placeholder is already under internationalization but the string is not on transifex.

going to issue a patch slightly different.
