### ISSUE TITLE
Enable admin to make a copy of an existing questionnaire

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2242]
**Current behavior**
Actually to make a copy of an existing questionnaire it's required to export it in json and import it in json.

**Expected behavior**
This ticket is to provide a functionality to copy an existing questionnaire.

The user should be able to copy also an existing questionnaire made available on instance 0, from admin of secondary instances.

**Comment by evilaliv3** [comment]
This feature has been implemented and a bugfixed version will released in 3.2.0.

Current implementation make it possible to create a copy of the existing questionnaire; when created the copy is available on the same tenant.

It is currently now possible to pass configurations to a different tenant that at the moment require the user to export the questionnaire and import it again on the tenant that requires the same configuration.
