### ISSUE TITLE
Tor Browser detection isn't working properly, not redirecting to .onion

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2244]
**Current behavior**
While testing the platform for a project we've identified that the platform didn't detected that the user was using Tor Browser and properly redirected to the .onion address.

The user was using a secondary instance in a multi-site environment.

**Expected behavior**
The platform should detect that the user is using Tor and redirect to the .onion, if and only if this is present and active.

**Steps to reproduce the problem or feature illustration**
Connect with Tor Browser to a website platform with a .onion active.

There should be a redirection, but it doesn't happen.

**Comment by evilaliv3** [comment]
The bug happened testing on multitenant instance and does probably not apply to the root tenant.

**Comment by fpietrosanti** [comment]
Possibly integrate new Tor Fingerprinting mainteined js library
https://github.com/jonaslejon/tor-fingerprint
https://github.com/jonaslejon/tor-fingerprint/blob/master/tor-fingerprint.js

**Comment by evilaliv3** [comment]
This bug was identified and fixed recently and appears to not be present in the up-to-date release (3.1.10)
