### ISSUE TITLE
Enable having a redirect on first tenant to the login for admin interface

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2247]
**Current behavior**
There are certain setup scenario where the first tenant of a GlobaLeaks platform is used only for administrative purposes.

In those scenarios, such as when the site is https://admin.DOMAIN.TLD, it should be possible to connect to the first tenant and just find a redirect to the login interface.

This ticket is to introduce a new settings, to be made available under site managements section:
Disable Whistleblowing on first site (redirect to admin's login interface)

If that's enabled, the first globaleaks site will not provide whistleblowing service on the main page (in a similar way, as if signup it's enabled, that just redirect to signup page).

**Comment by evilaliv3** [comment]
Sorry @fpietrosanti i was sure to have commented but probably i just forgot to send my comment and have noticed the ticket again thanks to @NCommander interest in implementing it.

By the current implementation, this ticket has been already deprecated for many reasons:
- administrators login is not separated from recipient logins; denying one would deny the other.
- implementing a redirect on the tenant would make not possible to log in on the secondary tenant to administrate it.

This ticket is superseaded by: https://github.com/globaleaks/GlobaLeaks/issues/2301 and https://github.com/globaleaks/GlobaLeaks/issues/2302
