### ISSUE TITLE
If the whistleblower identity is not given, in the recipient panel the identity is displayed

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2249]
**Current behavior**
If the whistleblower identity is not given, in the recipient panel the identity is displayed as show below:
<img width="670" alt="screen shot 2018-04-04 at 16 00 56" src="https://user-images.githubusercontent.com/770363/38312291-ad8cb75c-3821-11e8-9212-2b0f085802e7.png">

The bug maybe related to switching between yes/no on the whistleblower identity question.

**Expected behavior**
The identity panel on the recipient interface should be displayed if and only if the whistleblower identity has been given.

**Comment by evilaliv3** [comment]
Fixed!
