### ISSUE TITLE
Error when loging into GL with a non-existent/expired leak code

### ISSUE THREAD

**Issue by Stephane-FILTRALA** [globaleaks/GlobaLeaks#2259]
**Current behavior**
When an user tries to get into the GL to communicate with the receptor and enters a wrong 16-number code, the system opens the access for the receptors. ¿Could it be changed? It would be great if the user could receive a message saying that the code is not valid.

**Expected behavior**
There should be a message" the number entered is not correct or maybe your leak already expired. Please do send a new leak or, bla bla bla..."

**Steps to reproduce the problem or feature illustration**
Just put a wrong number in the login interface
Like this: 
![screenshot 2018-04-16 16 40 04](https://user-images.githubusercontent.com/37292195/38815784-fb1b2d42-4194-11e8-89ad-4b42737f124d.jpg)

And you get this:
![screenshot 2018-04-16 16 40 14](https://user-images.githubusercontent.com/37292195/38815777-f6f5374e-4194-11e8-898a-7d6eea32c40b.jpg)

**What is the motivation or use case for changing the behavior?**
The leaker can see all the different receivers accounts

**GlobaLeaks version:**

**Comment by evilaliv3** [comment]
Fixed!

Here is the interface with the regression fixed:
![image](https://user-images.githubusercontent.com/217034/38899098-2e182c60-4297-11e8-803a-96823e817a24.png)

**Comment by evilaliv3** [comment]
Released in 3.0.26
