### ISSUE TITLE
Remove Absolute Paths from File Uploads in Database

### ISSUE THREAD

**Issue by NCommander** [globaleaks/GlobaLeaks#2269]
**Current behavior**
Currently, filepaths in the database store the full absolute path. This drastically complicates relocating GlobaLeaks installs between systems and distributions especially for Developer Mode instances, and makes tenant import/export much more complicated as the paths need to be rewritten on the fly. This same quirk exists both in receivertip files and in whistleblower files,

**Expected behavior**
GlobaLeaks should use relative paths from the attachment directory and not use absolute paths.

**Steps to reproduce the problem or feature illustration**
Upload a file to the GL feature.

**What is the motivation or use case for changing the behavior?**
Simplification of tenant import/export.

**GlobaLeaks version:** devel

**Browser:** N/A

**Server Operating System and Version (if applicable):** Gentoo

**Client Operating System and Version (if applicable):** Gentoo

**Comment by evilaliv3** [comment]
@NCommander: i totally agree on this point.

Let's not tickets like this as a bug but as an enhancement.

For example this ticket is not a blocking ticket for any implementation even for the import/export and could be considered secondary priority to be implemented on the next database migration.

**Comment by evilaliv3** [comment]
This has been implemented and is not part of the devel branch.
