### ISSUE TITLE
Circular Database Dependency: fieldanswers<->fieldanswergroup

### ISSUE THREAD

**Issue by NCommander** [globaleaks/GlobaLeaks#2270]
Fieldanswers table, and the fieldanswergroup tables have a foreign key relation on them. That makes changing and deleting data here more difficult than it needs be. Fieldanswers allows a nullable FK, so it might be easier to drop the circular dependency there, but the codebase will have to be examined to make sure this doesn't introduce new regressions.

**Comment by evilaliv3** [comment]
@NCommander: could you elaborate on the folllwing?
- why do you recognize this as an issue?
- why did you find problematic to using the null as termination for a recursive alghorithm?
- "that makes changing and deleting data here more difficult than it needs be." the presence of foreign keys enables for example to drop a root and get the full hierarchy automatically (this is a design choice); can you elaborate what are you finding difficult to implement with an example?

this more of a bug is a design choice that should be just considered on the export considering that some foreign keys may be nullable.

This implementation finds its reason on some of the most proper and important setups of globaleaks that implement a rich questionnaire that involves sometimes multiple layers of nested fields (some complex setups arrive to 4).

This apply as well to the Field table in first stage, and then to FieldAnswers for storing answers and group of answers (e.g. for implementing multiple entries for same rich questions like "Involved Persons")

Who would you refactor this with no major db changes? Is there any know good approach to this aspect?

**Comment by NCommander** [comment]
Ugh, I was afraid you'd say that. I've already dealt with the loop in code which nulls out the FK, imports FAG, and then fixes the entries so its non-fatal. Just really really ugly.
