### ISSUE TITLE
Make it possible for users to change their Email address via preferences

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2272]
Many projects would benefit of making it possible for users to change their Email via preferences.

This feature would require to add this possibility to the existing user update API and add an input box to the user preferences UI.

**Comment by fpietrosanti** [comment]
This require also to confirm the access to the new email address, sending a confirmation email, before changing it, or the user by mistake can lock-him-out

**Comment by evilaliv3** [comment]
Implemented and merged in devel branch!

![image](https://user-images.githubusercontent.com/217034/40086797-1b2a6982-58a0-11e8-876f-317c4f682ec2.png)

To complete the mail validation the user has to click on a link received on the new specified email.
