### ISSUE TITLE
Implement interface for visualizing signup data

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2278]
When signup is enabled on the platform should expose an interface for visualizing them.

Current collected ideas are:
- the interface could be shown as a Tab inside "Site management" called "Signup list"
- the Signup list could be implemented with the same layout of tenants/context/recipients lists with compact and extended version on click
- in its compact version the list should show the summary of the information about the signup like:
  the name of the organization, the state of activation by the user, the state of validation by the root tenant admin, a link to the tenant, possibly a direct link to tenant management by the root tenant admin (this last feature should be probably postponed)
- in its extended version, when opened, the list should show show all the information of the signup and host

The preliminary above described feature should consider to support the following other features, detailed in specific tickets: 
- the list should offer a search filter like in the tip list (this could probably be added after to any interface like tenants, context, fields etc)
- the list should offer pagination like in tenant list (this could probably be added after to any interface like tenants, context, fields etc)
- the list should allow to easy filter and see the tenants that miss activation by the user
- the list should allow to easy filter to see the tenants that miss

**Comment by evilaliv3** [comment]
The ticket is designed to be a clientside ticket that do not require by the time of writing any additional backend development for any of the described feature;

The backend REST api to be used for fetching the data is: https://github.com/globaleaks/GlobaLeaks/blob/master/backend/globaleaks/handlers/admin/signup.py

**Comment by fpietrosanti** [comment]
It should also show and enable selection on:
- The use case (all "anticorruption" use cases)
- The language of the user that was signing up (Rif also #2256 for the language collection)
- If it has been activated or not (a user may signup but never confirm activation)

**Comment by evilaliv3** [comment]
@fpietrosanti:

It should also show and enable selection on:
- The use case (all "anticorruption" use cases): i agree; for the moment anyhow lets stay on a feature-set appliable whatever will be the signup form. the use case is a signup form that for example wont be present in whistleblowing.it so this requirement should not be handled in this ticket. This ticket will implement the generic search, that will anyhow be able to perform a grep as in the tip list on all the signup details.
- The language of the user that was signing up (Rif also #2256 for the language collection): right requirement to be added to what specified above.
- If it has been activated or not (a user may signup but never confirm activation): already defined above.

**Comment by evilaliv3** [comment]
Here some of the points analyzed in lates discussions on irc on a minimum implementation to 

- it has been considered that for simplicity the tenant handler may be extended to serialize signup data (https://github.com/globaleaks/GlobaLeaks/commit/b713f8f503e1df743b36c892c02523b8a3654eb3)
- the data should be visualized on the Sites interface inside each Tenant
- simmetrically to the code already implemented signup, given a signup.mode (currently 'default' or 'whistleblowing.it') multiple visualization templates may be supported;

this minimal implementation may be extended with further implementations with eventual different ticket in order to:
- make it possible to through tenants/signups data using a simple angular filter on their json descriptor.
- mark a tenant as 'validated' (requirement still to be analyzed with the end users)

**Comment by evilaliv3** [comment]
Closing as implemented long time ago.
