### ISSUE TITLE
AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_SINGLE_ECDH_USE'

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2281]
This ticket is to handle this exception, providing additional integrity check on the availability of the attribute OP_SINGLE_ECDH_USE by the OpenSSL.SSL module.

Exception below:

Platform: 
Host:  ()
Version: 3.0.29

AttributeError Attribute not found.

Traceback (most recent call last):

  File "/home/xxxxxxx/src/GlobaLeaks/backend/globaleaks/jobs/base.py", line 53, in run
    yield self.operation()

AttributeError: module 'OpenSSL.SSL' has no attribute 'OP_SINGLE_ECDH_USE'

**Comment by NCommander** [comment]
I'm closing this, this bug was caused by the fact the PyOpenSSL was out of date when working against a new(er) openssl. We dont' support pip installs anymore with 3.1.8 and this was caused by me working on Gentoo. It was also resolved by the version of pyopenssl we pinned to in bionic.

**Comment by fpietrosanti** [comment]
Please consider that, when something like this happen, regardless of the packaging, it's useful to implement a check of the capabilities we need to the underlying libraries. In that case an application check that OpenSSL.SSL has OP_SINGLE_ECDH_USE before using it, so the code will die gracefully in such a case
