### ISSUE TITLE
Signup can enable acceptance of contractual condition and gdpr-privacy rules separately

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2287]
**Current behavior**
Actually when a user signup to a globaleaks-enabled service there's no acceptance of contractual condition, neither of gdpr-privacy rules.

**Expected behavior**
This ticket is to enable and let configure acceptance of contractual condition and gdpr-privacy rule of the service, separately.

This should be a feature that can be enabled/disabled and the text (title and content) to be configured.

If enabled the end-user *must* accept both conditions.

For commercially-relevant service, in order to prove the acceptance of contractual condition by law, it must be collected:
- the IP address of who is signing up
- his user agent
- time/date of the acceptance
- in the db a flag that explicitly recorded that those two contracts has been accepted.

Possibly a warning that IP address of who's accepting the contractual condition will be recorded, should be displayed in a clear yet nice way during the signup interface (if and only if this feature is enabled).

**Comment by fpietrosanti** [comment]
@NCommander well, when this feature is in-use, a signup from Tor it's likely not expected, btw the signup doesn't have anything todo with "whistleblower" and the contractual agreement is about signing up a contract for a service online, so it's a common civil law rule. If someone signup from Tor, well, the platform does need to know about that?

**Comment by evilaliv3** [comment]
Update of what already implemented and released in 3.1.2.

Already the release include variables related to ToS that has been added as Config variables
- tos1_enable
- tos1_clause
- tos1_agreement
- tos2_enable
- tos2_clause
- tos2_agreement

Database support for Signup should be extended to include:
- client_ip_address
- client_user_agent

This addition will be possible at next database migration and i may take care of preparing this.

@NCommander: as clarification this ticket just deals with the Admin user that apply for a signup on a multitenant setup with signup enabled (like try.globaleaks.org); it does not apply to whistleblowers that has a similar but slightly different ticket to be still completely analyzed: https://github.com/globaleaks/GlobaLeaks/issues/2225

**Comment by NCommander** [comment]
Merged
