### ISSUE TITLE
Change tip sequence number to be absolute and incremental

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2288]
Current implementation of the tip sequence number has an implementation that is based on the date.

This implementation contains a not-solvable issue related to the fact that the the tip sequence number is statically bind to a timezone (UTC).

This ticket is to propose the change of implementation to make possible, for who need a sequence number, to keep an incremental absolute number.

**Comment by NCommander** [comment]
Merged
