### ISSUE TITLE
Introduce nscd as a globaleaks linux package dependency

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2291]
**Current behavior**
It has been found out in a project while debugging #657 condition that, by installing "nscd" package, everything started working back.

**Expected behavior**
Considering it an easy fix with no evident issues, this ticket is about introducing nscd as a GlobaLeaks Debian Linux dependency.

**Comment by NCommander** [comment]
I'm closing this bug report as adding nscd changes the behavior of resolving on the system and is not something we should be doing without solid reason to do so.
