### ISSUE TITLE
GlobaLeaks, before it's startup, should check the presence of all it's python dependencies

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2300]
**Current behavior**
Following https://forum.globaleaks.org/t/failed-to-load-application-cannot-import-name-jose/219 it appears that GlobaLeaks try to startup also if not all the python requirements are available and met.

**Expected behavior**
This ticket is to introduce (or re-introduce?) the dynamic checking, at startup, that each and all dependencies of GlobaLeaks are present, prompting a specific error on missing dependencies.

**Comment by evilaliv3** [comment]
Dependency checking is part of the natural debian packaging.

The issue was caused by a bad release now solved.
