### ISSUE TITLE
Problem after ssl certificate installation

### ISSUE THREAD

**Issue by francesco326** [globaleaks/GlobaLeaks#2304]
I installed the latest Globaleaks version on Ubuntu Xenial 16.04.04 LTS, following the instructions on this guide: https://github.com/globaleaks/GlobaLeaks/wiki/Setting-up-GlobaLeaks-development-environment - _Manual Setup_

Launching `./bin/globaleaks -z "Developer Name" -n` -> port 8082, 8082 locally, port 8080 remotely, everything works fine.

After installing a test certificate (self-signed SSL Certificate, generated with open ssl) from the administrative section and receiving confirmation, the machine is no longer reachable remotely.

If I try to launch the application with
`./bin/globaleaks -u globaleaks -l 'DEBUG' -n`

locally it continues to work, but remotely is no longer reachable, suggestions? Thanks

**Comment by evilaliv3** [comment]
Hello @francesco326 !

thank you for reporting this

i guess that for error you enabled the platform to be reachable only via Tor.
This settings is something you tweak in the Network settings.

In the meantime you can manually fix the issue by issuing the following command: ```iptables -F```

**Comment by francesco326** [comment]
Hi,
thanks for the reply.

I do not think the problem is related to tor, I have not enabled it. The problem occurs after installing the https certificate, the application is no longer accessible remotely

I have also make several tests on "clean" machines, always downloading GL with the git-clone, every time I install the certificate the machine stops working

Now, If download the application with apt-get, with the "automatic" setup, without "git-clone", the same certificate works perfectly and the the application work remotely on the 443

**Comment by francesco326** [comment]
![2](https://user-images.githubusercontent.com/38255539/40913767-e42f0bf8-67f5-11e8-9f4f-200096767bd6.png)

**Comment by francesco326** [comment]
![2](https://user-images.githubusercontent.com/38255539/40913836-2c430fb6-67f6-11e8-9020-b5dc6f7b7cbf.png)

**Comment by evilaliv3** [comment]
Thank you @francesco326 for this feedback.

Could you please try with the current release 3.1.6

We just fixed some issues in relation to the network sandboxing that due to a failure was always turned on causing the platform to accept only Tor connections.

**Comment by francesco326** [comment]
thank you for the reply but the new version, now, give me the error, after the command "pip install.....", "could not find a version that satisfies the requirement debian==0.1.27 requirements.txt (line 7)...."

always on ubuntu 16, thanks

cheers

**Comment by fpietrosanti** [comment]
@francesco326 join our slack chat https://slack.hermescenter.org to stay in touch with dev-team on the channel, so that the feature you're going to develop could become official software feature and we can have knowledge exchange on that

**Comment by francesco326** [comment]
Hi,

thank you for the support, I made the change to requirements.txt by removing the debian dependency 0.1.27 and now it works

however, now the system works properly by installing the ssl certificate in developer mode, but if I wanted to start it WITHOUT "-z developer mode" to open ports 80 and 443, how should I do it?

@fpietrosanti at the moment we have not yet shared the changes because we believe that they can not be useful, but as soon as we have a stable system, I will gladly share the code

**Comment by evilaliv3** [comment]
Closing as solved.
