### ISSUE TITLE
Regression: Tip export do not include submission files

### ISSUE THREAD

**Issue by Stephane-FILTRALA** [globaleaks/GlobaLeaks#2307]
**Current behavior**
Before we were able to download the whole leak with a click: a ZIP file with the text + encrypted documents.

Now the button just download the text of the leak and you have to download the documents one by one. 

**Expected behavior**
Pushing the button would download a zip with the text + the documents of the leak.

**Steps to reproduce the problem or feature illustration**
Just download a leak

**What is the motivation or use case for changing the behavior?**
¿?

**GlobaLeaks version:**
3.1.4

**Browser:**
Tor Browser 7.5.4 (Mac OSX) 

**Server Operating System and Version (if applicable):**
n/a

**Client Operating System and Version (if applicable):**
n/a

**Comment by evilaliv3** [comment]
Thank you for reporting this regression @Stephane-FILTRALA 

I confirm that the regression is present and in latest releases and it has been added starting from release 3.1.0.

**Comment by evilaliv3** [comment]
Patch issued, will be included starting from release 3.1.7
