### ISSUE TITLE
Unexpected internal server error (malformed client IP address)

### ISSUE THREAD

**Issue by gneotel** [globaleaks/GlobaLeaks#2313]
**Current behavior**

I have fresh installation, almost everything is still default. The server has been on for a couple of days. Suddendly I could not login anymore. On browser I have the error "Errore! Errore interno del server (Unexpected)"., this is the error reported by the server:
**********************************************************************************
Platform: Whistleblowing UNIVPM
Host: ******************.it (****************.onion)
Version: 3.1.7

ValueError Inappropriate argument value (of correct type).

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)

  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 408, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/authentication.py", line 147, in post
    request['token'])

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 110, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/authentication.py", line 106, in login
    client_ip_obj = ipaddress.ip_address(client_ip)

  File "/usr/lib/python3.6/ipaddress.py", line 54, in ip_address
    address)

ValueError: "b'193.205.xxx.xx'" does not appear to be an IPv4 or IPv6 address
**********************************************************************************

I've replaced my actual IP last digits, but the "b'" thing is in the error report (and his probable cause).
The error persists from a different IP address.
As an additional info, even when the login was working I could not reach the TOR address from a TOR browser.

**GlobaLeaks version:**

3.1.7

**Browser:**

Chrome 67.0.3396.79
Firefox  60.0.1 (64 bit)

**Server Operating System and Version (if applicable):**
 
Ubuntu (18.04)

**Client Operating System and Version (if applicable):**

Windows 10

Thanks.

**Comment by fpietrosanti** [comment]
@gneotel hello, is the problem still there? as it may seems to be a bug somewhere in the code

**Comment by gneotel** [comment]
I don't know the software well yes so I solved the problem reinstalling...
It was originated by the string to filter administrative networks (I don't have a computer now and I cannot recall the setting name). I did put two networks/24 and a single IP separated by commas. Maybe there is a problem in the parser.
Thanks

**Comment by gneotel** [comment]
The option was "Restringi l'accesso di utenze privilegiate a specifici indirizzi IP", on the DB: ip_filter_authenticated. The value was: '193.205.xxx.0/24,193.205.xxx.xxx,193.205.xxx.0/24' (with actual values instead of xxx).

**Comment by evilaliv3** [comment]
Thank you @gneotel on which distribution/version are you running this setup?

@NCommander: do you have an idea of what can be failing here?

**Comment by gneotel** [comment]
3.1.7 on ubuntu 18.04

**Comment by evilaliv3** [comment]
Thanks! going to test it now

**Comment by evilaliv3** [comment]
Issue fixed @gneotel, thank you so much for your feedback.

The patch will be included starting from release 3.1.9.
