### ISSUE TITLE
Whistleblower identity workflow: make it possible to avoid second question  with yes/no answer

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2314]
**Current behavior**
Actually when Whistleblower Identity is enabled, is possible in case of "no" answer, to ask another answer with a title and descriptive text (both configurable), that require confirmation with "yes" in order to move forward.

**Expected behavior**
A customer asked this second step, in case of "no" answer to "whistleblower identity" to only provide an additional informative text (not formulated as a "question" that require to further answer yes/no).

This should be configurable, and in case the whistleblower select "no" to the "whistleblower identity", the configured text should be posed as an informative text, not as a question.

**Comment by evilaliv3** [comment]
This ticket can be closed as the feature correction landed in the devel branch and will be released with upcoming release 3.2.0
