### ISSUE TITLE
Expiration date "null"

### ISSUE THREAD

**Issue by moadr** [globaleaks/GlobaLeaks#2328]
**Current behavior**
When recipient postpone submission expiration date, the popup says:
"Are you sure that you want to postpone the submission expiration date?
By confirming, you will postpone the expiration date to: null"

![screenshot-2018-6-19 1 - submission status](https://user-images.githubusercontent.com/38560917/41585928-b39f4f72-73ab-11e8-88f5-da01d917f3e1.png)

**Expected behavior**
The correct date instead "null"

**GlobaLeaks version:**
3.1.9

**Comment by evilaliv3** [comment]
Bug confirmed to be present in recent releases (3.2.2).

**Comment by evilaliv3** [comment]
Fixed.

The patch will be added to upcoming version 3.2.3
