### ISSUE TITLE
apparmor_error on file_mprotect on GlobaLeaks 3.1.9

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2334]
**Current behavior**
On GlobaLeaks 3.1.9 on Xenial the following error happens trough apparmor:

[11554159.163192] audit: type=1400 audit(1528697327.673:765800): apparmor="DENIED" operation="file_mprotect" profile="usr.bin.globaleaks" name="/usr/bin/python2.7" pid=17902 comm="python" requested_mask="r" denied_mask="r" fsuid=111 ouid=0

Actually it doesn't seems to have a functional impact, but who knows...

**Expected behavior**
There should be no error like this.

**Comment by evilaliv3** [comment]
This error seems to have been triggered on a server during a penetration testing.

I confirm that from the application logs there is nothing that confirm a possible malfunction and we are not using mprotect system call explicitly in any of the code except from when we explicitly disable the swap usage.

I've rechecked what eventually would be needed to fix this blindly adding the capability to the python binary and the capability is just a 'm' capability that i do not see applied in the most common softwares.

I would not consider this a bug and i would assign this low priority waiting for new situations.

**Comment by fpietrosanti** [comment]
Same kind of error of torbrowser-launcher https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=761663#22

**Comment by fpietrosanti** [comment]
on a server that messages keeps being reproduced thousands of time with +300MB /var/log/kern.log* .
changing the apparmor profile from:
    /usr/bin/python{,2,2.7,3,3.[0-9]} ix,
to
    /usr/bin/python{,2,2.7,3,3.[0-9]} ixr,

seems to have disabled the error from popping up

**Comment by fpietrosanti** [comment]
Other very similar issue due to kernel changes:
https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1655982
https://bugs.launchpad.net/ubuntu/+source/apparmor/+bug/1667751

**Comment by fpietrosanti** [comment]
verified on kern.log, no more continuous errors
fix with https://github.com/globaleaks/GlobaLeaks/commit/d52ad685b11c6ad5e920bc82b8acc6c354ebf6d2
