### ISSUE TITLE
The administrator should be able to reset the password for a user

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2340]
Current password reset enable the admin to manually set the password for the user.

This easy implementation is become more and more inadequate:
- on creation the admin has to manually notify users the password.
- on change the admin has to manually choose and set a password and notify users the password.

This ticket is about removing the possibility for the admin to set a password and replace the functionality with a Reset Password button.

The button should trigger the same automatic workflow of the user password reset sending and authentication token to the configured email.

This change impacts both usability and security of the plaftorm.

**Comment by NCommander** [comment]
The easiest way for this to work is to use the password reset codepaths, and simply disregard the setting if the platform is allowing PW resets.

It still has all the inherent problems of email based password resets, but TBH, I can't see how its worse than just requiring the admin to set a new password by hand ....

**Comment by evilaliv3** [comment]
I totally agree with your points and i think your proposal for the implementation is correct.

in my opinion the direction should always be the one that does not want tomorrow to enforce only the best security practices but the one that that looking at those best practices try to improve/kill in the real the existing widely used bad practices.

**Comment by evilaliv3** [comment]
@NCommander: after having thought a bit to this i think for the moment it would be valuable to still leave the possibility for the admin to manually set a password; this is required most of the time at least for developing and testing.

Under this ticket lets for the moment just implement a new button (e.g. "Reset" or just an icon with a popover "Reset") to automatically reset the password on behalf of the user and trigger the already implemented mail notification.

**Comment by evilaliv3** [comment]
As for the implementation of this let's user the same OperationHandler already implemente for other commands.

This additional command could be 'reset_password' and have as argument the user.id.

**Comment by evilaliv3** [comment]
Feature implemented in https://github.com/globaleaks/GlobaLeaks/pull/2343 and currently merged in branch devel.

Here the UI for the new feature:
![screenshot-127 0 0 1 8082-2018-07-01-11-32-00](https://user-images.githubusercontent.com/217034/42132989-a2c2bbf0-7d22-11e8-96bd-7b4d61b65696.png)
