### ISSUE TITLE
Make it possible to Enable/Disable tenant graphic customization

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2347]
In relation to specific projects like whistleblowing.it it become interesting requirement to make it possible to Enable/Disable tenant graphic customization and make the inherit CSS and JS from the root tenant.

This would enable the possibility to implement unified projects where each tenant would share the same configuration.

**Comment by NCommander** [comment]
I'm more in favor of the root tenant having special variables that don't exist in a child vs shoving them into the tenant table.

For one the design is more flexible as we only need to refresh the variables vs. do schema changes/migrations when we want to add a new root tenant feature.

Furthermore, if we ever have hierarchial chain of tenants (i.e., root tenant, child tenant, subchild tenant), we'd be able to safely reflect them in the database.

**Comment by evilaliv3** [comment]
I totally agree.

Just one clarification: we need a default, and a per tenant configuration.
For this reason we could add the variable to the Config table and have the following software behaviour:
- the variable in the root tenant will act as a default (at creation) for secondary tenants
- the variable in the child tenant will act as an actual configuration

We should then enable filtering so to make it possible to configure this variables only via privileged handlers on the root tenant.

**Comment by NCommander** [comment]
Merged
