### ISSUE TITLE
exported tip contain messages with the wrong timestamp

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2349]
**Current behavior**
When a tip is exposed, the messages in the .txt file included in the zip file, contain the wrong timestamp. The timestamp reported is the very same of the original date of the submission.
Reported by BIF user.

**Expected behavior**
The timestamp should be the right one.

**Comment by evilaliv3** [comment]
I've analyzed the bug as i was considering this solved and i've identified the fix that is due to a missing specific definition of the EventTime keyword for comments and messages.
