### ISSUE TITLE
Error Message: Method Not Allowed on /admin/case_management with v. 3.3.1

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2389]
Platform: Segnalazioni Whistleblow
Host:  
Version: 3.3.1

URL: /admin/case_management

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36

Error Message: Method Not Allowed

Stacktrace:
[
  {
    "url": "admin/submission_statuses/substatuses/cc3c9016-8ef9-4083-bb6a-43da64238ccf", 
    "method": "DELETE"
  }
]

**Comment by evilaliv3** [comment]
This bug is still present in 3.3.3 and lie in a a wrong variable name in the client.
