### ISSUE TITLE
Incorrect italian translations

### ISSUE THREAD

**Issue by moadr** [globaleaks/GlobaLeaks#2401]
**Current behavior**
"Last update": "Ultimo aggioramento",
"please enter a valid email address.": "si prega di inserire un indirozzo email valido.",

**Expected behavior**
"Last update": "Ultimo aggiornamento",
"please enter a valid email address.": "si prega di inserire un indirizzo email valido.",

**GlobaLeaks version:**
3.3.6

**Comment by evilaliv3** [comment]
Thank you @moadr, thanks to your notification i've corrected the translation on transifex and the correction will be included starting from release 3.3.12
