### ISSUE TITLE
Multitenancy support documentation

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2414]
While multi-tenancy support is very interesting, I haven't been able to locate any documentation whatsoever. Could you please direct me to existing documentation?  Apologies in advance if I'm missing something obvious!

**Comment by evilaliv3** [comment]
Hello @elbill; at the moment no documentation exists and we are working on it.

I will point you to the documentation as soon it will be available.

In the meantime may i help you on some specific issue?

**Comment by elbill** [comment]
Thanks. My technical skills do not allow me to do much without documentation. So I'mm really looking forward to any sort of documentation even something draft or indirectly relevant.
