### ISSUE TITLE
Unhandled exception in /login Error Message: TypeError: Cannot read property 'user_id' of undefined

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2418]
Platform:  
Host:  
Version: 3.3.5

URL: /login

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

Error Message: TypeError: Cannot read property 'user_id' of undefined

Stacktrace:
[
  {
    "columnNumber": 35,
    "lineNumber": 19690,
    "fileName": "https://xxxx.com/js/scripts.js",
    "functionName": "m.$scope.showDeleteWBFile",
    "source": "    at m.$scope.showDeleteWBFile (https://xxxx.com/js/scripts.js:19690:35)"
  },
  {
    "columnNumber": 35,
    "lineNumber": 261,
    "fileName": "https://xxxx.com/js/scripts.js",
    "functionName": "fn",
    "source": "    at fn (https://xxxx.com/js/scripts.js:261:35"
  },
  {

**Comment by evilaliv3** [comment]
Closed as outdated.

**Comment by fpietrosanti** [comment]
@evilaliv3 It does keeps happening on last GlobaLeaks, that's on ALAC

Platform: 
Host:  
Version: 3.9.1

URL: /login

User Agent: Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-G950F Build/PPR1.180610.011) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/9.2 Chrome/67.0.3396.87 Mobile Safari/537.36

Error Message: TypeError: Cannot read property 'user_id' of undefined
