### ISSUE TITLE
Support for Tor2Web removed in tor 0.3.5 (not yet stable)

### ISSUE THREAD

**Issue by hiromipaw** [globaleaks/GlobaLeaks#2429]
Hi,

I am getting in touch regarding your current option to enable Tor2Web in Globaleaks configs.

I see it is disabled by default, yet I wanted to let you know that support for Tor2Web is going to be removed from the code in tor 0.3.5 (not yet stable). Furthermore the current behaviour is that if Tor2Web is enabled, most relays will refuse you.

I think users should be warned that if they enable Tor2Web they might encounter in the issues described above. Maybe it's time to retire Tor2Web support at all.

Please let me know if I can help you in any ways with this.

**Comment by fpietrosanti** [comment]
Could you share with which is the use-case of Tor2web in your actual deployment?

As per our updated threat model, HTTPS has been integrated directly into GlobaLeaks itself (along with LetsEncrypt), as almost all deployments will slowly stopped using a separated Tor2web machine. 
So currently GlobaLeaks is used as a standalone machine, if it does require to have "Location Anonymity" property, it just uses Tor Onion only submission.

And yes, from official Tor code flow, Tor2web is going to be slowly removed (but that's an optimization at OR protocol, it doesn't mean that Tor2web code will stop working)

Let us know

**Comment by hiromipaw** [comment]
Hi Fabio,
I don't use Globaleaks. I am from the Tor Project. I noticed you still mention Tor2Web in your setup/troubleshoot guide and I was wondering if it wouldn't be better to let users known that this option is not ideal and why.
