### ISSUE TITLE
signup page can result in tenants

### ISSUE THREAD

**Issue by frozen-sky** [globaleaks/GlobaLeaks#2435]
**Current behavior**

At an installation, some random tenants appered in the database. First thought was a hacked account, but it seems in (some?) circuimstances a POST on /signup results in a tenant created

**Expected behavior**
/signup should not result in tenants

**Steps to reproduce the problem or feature illustration**

non. this was analyzed by using logs:

by using sqlite on globaleaks.db, we found 4 random tenants:
(times/names adjusted) 

```
- id 3, creationdate "2018-08-10 22:33:00"
- id 5, creationdate "2018-08-14 21:12:12"
- id 6, creationdate "2018-09-02 08:17:32"
- id 7, creationdate "2018-10-02 18:20:54"
```

At the same time we found in the access logs:

```
2018-08-11 00:33:00+0200 [-] [-] [1] 201 POST &#47;signup 0B 75ms
2018-08-14 23:12:12+0200 [-] [REMOVED_IP_ADDRESS] 1 201 POST /signup 0 78ms "[REMOVED_USER_AGENT]"
2018-09-02 10:17:31+0200 [-] [REMOVED_IP_ADDRESS] 1 201 POST /signup 0 68ms "[REMOVED_USER_AGENT]"
2018-10-02 20:20:54+0200 [-] [REMOVED_IP_ADDRESS] 1 201 POST /signup 0 100ms "[REMOVED_USER_AGENT]"
```

(please note, log files are CEST, database UTC, 2h difference)

**What is the motivation or use case for changing the behavior?**

No random tenants. I'm not aware of what the signup page is and does, but maybe this is done by forcing a different tenant id or so in that form

**GlobaLeaks version:**

3.4.1, database 44. But also with previous version (the logfile formatting is a bit different in the previous version) 

**Browser:**

unknown. based on logs

ubuntu xenial

**Client Operating System and Version (if applicable):**

64-bit linux

**Comment by evilaliv3** [comment]
Thank you @frozen-sky 

Is it possible that the users of this platform were simply experimenting creating multiple tenants?

We just completed some code review and testing for your issue as we were worried about possible vulnerabilities but the signup feature appear to be working correctly;

It enable a free signup (creation of a tenant) but it requires:
- that the feature is enabled
- that a complete signup request is issued

**Comment by evilaliv3** [comment]
After rechecking with @frozen-sky, it is confirmed that the issue was caused by a misconfiguration of the system.

This ticket can be closed.
