### ISSUE TITLE
Build System must archive all released version

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#244]
The current build system overwrite globaleaks build.

This make impossible to attempt testing of migration path from a version to another (that should be part of the release process's quality assurance).

This ticket is make the build system archive all the debian released build under a specific, publicly available and documented directory.

This archive will then be used to make testing upgrade from a release to another one.

**Comment by evilaliv3** [comment]
Done: https://github.com/globaleaks/GlobaLeaks/wiki#releases-archive

**Comment by fpietrosanti** [comment]
The instruction to access archived debian installation file are missing.
By clicking on https://deb.globaleaks.org and then clicking any link, gives out 404 not found

**Comment by evilaliv3** [comment]
@fpietrosanti the bug in this is in the ngix config.
it seems that it is serving the contents only over http and not in https.

@fpietrosanti / @mmaker can you take a look to it?

**Comment by mmaker** [comment]
you're leaking all `.db` files now…

**Comment by fpietrosanti** [comment]
@mmaker also before they was accessible, is that a security issue of some kind?

**Comment by evilaliv3** [comment]
@mmaker i've reverted the changes of @fpietrosanti that were changing a problem with an other problem.

the real problem was a missing ~ in this configuration:

        location ~ /(jessie|wheezy|precise|trusty)/ {
          autoindex on;
          root /srv/packages;
        }
