### ISSUE TITLE
Error Message: TypeError: $scope.signup.organization_name is undefined

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2445]
Platform: WhistleblowingPA
Host: registrazione.whistleblowing.it (qpaszzjw5hmgajdu.onion)
Version: 3.4.1

URL: /signup

User Agent: 

Error Message: TypeError: $scope.signup.organization_name is undefined

Stacktrace:
[
  {
    "columnNumber": 5,
    "lineNumber": 19086,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "$scope.updateSubdomain",
    "source": "$~~~~~~@~~~~~~://registrazione.whistleblowing.it/js/scripts.js:19086:5"
  },
  {
    "columnNumber": 162,
    "lineNumber": 4,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js line 254 > Function",
    "functionName": "fn",
    "source": "~~~~~~@~~~~~~://registrazione.whistleblowing.it/js/scripts.js line 254 > Function:4:162"
  },
  {
    "columnNumber": 235,
    "lineNumber": 158,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "$eval",
    "source": "$~~~~~~@~~~~~~://registrazione.whistleblowing.it/js/scripts.js:158:235"
  },
  {
    "columnNumber": 459,
    "lineNumber": 298,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "link/<",
    "source": "link/<@https://registrazione.whistleblowing.it/js/scripts.js:298:459"
  },
  {
    "columnNumber": 312,
    "lineNumber": 311,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "$$writeModelToScope/<",
    "source": "$$writeModelToScope/<@https://registrazione.whistleblowing.it/js/scripts.js:311:312"
  },
  {
    "columnNumber": 74,
    "lineNumber": 12,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "r",
    "source": "~~~~~~@~~~~~~://registrazione.whistleblowing.it/js/scripts.js:12:74"
  },
  {
    "columnNumber": 268,
    "lineNumber": 311,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "$$writeModelToScope",
    "source": "$$~~~~~~@~~~~~~://registrazione.whistleblowing.it/js/scripts.js:311:268"
  },
  {
    "columnNumber": 160,
    "lineNumber": 311,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "$$parseAndValidate/<",
    "source": "$$parseAndValidate/<@https://registrazione.whistleblowing.it/js/scripts.js:311:160"
  },
  {
    "columnNumber": 415,
    "lineNumber": 308,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "g",
    "source": "~~~~~~@~~~~~~://registrazione.whistleblowing.it/js/scripts.js:308:415"
  },
  {
    "columnNumber": 226,
    "lineNumber": 309,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "$$runValidators",
    "source": "$$~~~~~~@~~~~~~://registrazione.whistleblowing.it/js/scripts.js:309:226"
  },
  {
    "columnNumber": 47,
    "lineNumber": 311,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "$$parseAndValidate",
    "source": "$$~~~~~~@~~~~~~://registrazione.whistleblowing.it/js/scripts.js:311:47"
  },
  {
    "columnNumber": 1,
    "lineNumber": 310,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "$commitViewValue",
    "source": "$~~~~~~@~~~~~~://registrazione.whistleblowing.it/js/scripts.js:310:1"
  },
  {
    "columnNumber": 376,
    "lineNumber": 312,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "$$debounceViewValueCommit/<",
    "source": "$$debounceViewValueCommit/<@https://registrazione.whistleblowing.it/js/scripts.js:312:376"
  },
  {
    "columnNumber": 235,
    "lineNumber": 158,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "$eval",
    "source": "$~~~~~~@~~~~~~://registrazione.whistleblowing.it/js/scripts.js:158:235"
  },
  {
    "columnNumber": 477,
    "lineNumber": 158,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "$apply",
    "source": "$~~~~~~@~~~~~~://registrazione.whistleblowing.it/js/scripts.js:158:477"
  },
  {
    "columnNumber": 345,
    "lineNumber": 312,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "$$debounceViewValueCommit",
    "source": "$$~~~~~~@~~~~~~://registrazione.whistleblowing.it/js/scripts.js:312:345"
  },
  {
    "columnNumber": 451,
    "lineNumber": 311,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "$setViewValue",
    "source": "$~~~~~~@~~~~~~://registrazione.whistleblowing.it/js/scripts.js:311:451"
  },
  {
    "columnNumber": 433,
    "lineNumber": 192,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "l",
    "source": "~~~~~~@~~~~~~://registrazione.whistleblowing.it/js/scripts.js:192:433"
  },
  {
    "columnNumber": 156,
    "lineNumber": 44,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "og",
    "source": "~~~~~~@~~~~~~://registrazione.whistleblowing.it/js/scripts.js:44:156"
  },
  {
    "columnNumber": 105,
    "lineNumber": 44,
    "fileName": "https://registrazione.whistleblowing.it/js/scripts.js",
    "functionName": "d",
    "source": "~~~~~~@~~~~~~://registrazione.whistleblowing.it/js/scripts.js:44:105"
  }
]

**Comment by evilaliv3** [comment]
Closing as fixed in recent releases.

**Comment by fpietrosanti** [comment]
Last error message on 17 July on

Platform: WhistleblowingPA
Host: registrazione.whistleblowing.it (qpaszzjw5hmgajdu.onion)
Version: 3.9.11

URL: /signup

User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0

Error Message: TypeError: $scope.signup.organization_name is undefined

**Comment by evilaliv3** [comment]
The bug is dead now!
