### ISSUE TITLE
Unhandled client side exception /admin/mail on .$scope.addClosingSubmissionSubStatus

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2446]
Platform: try.globaleaks.org
Host: try.globaleaks.org (bvidswzoj322engc.onion)
Version: 3.4.1

URL: /admin/mail

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36

Error Message: TypeError: Cannot read property 'label' of undefined

Stacktrace:
[
  {
    "source": "    at m.$scope.addClosingSubmissionSubStatus (https://xxxx.try.globaleaks.org/js/scripts.js:21549:60)", 
    "columnNumber": 60, 
    "fileName": "https://xxxx.try.globaleaks.org/js/scripts.js", 
    "functionName": "m.$scope.addClosingSubmissionSubStatus", 
    "lineNumber": 21549
  }, 
  {
    "source": "    at fn (https://xxxx.try.globaleaks.org/js/scripts.js:254:35", 
    "columnNumber": 35, 
    "fileName": "https://xxxx.try.globaleaks.org/js/scripts.js", 
    "functionName": "fn", 
    "lineNumber": 254
  }, 
  {
    "source": "    at e (https://xxxx.try.globaleaks.org/js/scripts.js:201:262)", 
    "columnNumber": 262, 
    "fileName": "https://xxxx.try.globaleaks.org/js/scripts.js", 
    "functionName": "e", 
    "lineNumber": 201
  }, 
  {
    "source": "    at m.$eval (https://xxxx.try.globaleaks.org/js/scripts.js:158:239)", 
    "columnNumber": 239, 
    "fileName": "https://xxxx.try.globaleaks.org/js/scripts.js", 
    "functionName": "m.$eval", 
    "lineNumber": 158
  }, 
  {
    "source": "    at m.$apply (https://xxxx.try.globaleaks.org/js/scripts.js:158:482)", 
    "columnNumber": 482, 
    "fileName": "https://xxxx.try.globaleaks.org/js/scripts.js", 
    "functionName": "m.$apply", 
    "lineNumber": 158
  }, 
  {
    "source": "    at HTMLButtonElement.<anonymous> (https://xxxx.try.globaleaks.org/js/scripts.js:201:347)", 
    "columnNumber": 347, 
    "fileName": "https://xxxx.try.globaleaks.org/js/scripts.js", 
    "functionName": "HTMLButtonElement.<anonymous>", 
    "lineNumber": 201
  }, 
  {
    "source": "    at og (https://xxxx.try.globaleaks.org/js/scripts.js:44:158)", 
    "columnNumber": 158, 
    "fileName": "https://xxxx.try.globaleaks.org/js/scripts.js", 
    "functionName": "og", 
    "lineNumber": 44
  }, 
  {
    "source": "    at HTMLButtonElement.d (https://xxxx.try.globaleaks.org/js/scripts.js:44:105)", 
    "columnNumber": 105, 
    "fileName": "https://xxxx.try.globaleaks.org/js/scripts.js", 
    "functionName": "HTMLButtonElement.d", 
    "lineNumber": 44
  }
]

**Comment by evilaliv3** [comment]
Closing as probably fixed.
