### ISSUE TITLE
Enable admin to reset submissions database and counters 

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2447]
**Current behavior**
In public administration there's the need of a unique, progressive counter for each tip being managed.

Actually when a sysadmin install globaleaks and configure it for testing purposes, when it need to goes online, doesn't have a way to have a unique progressive counter and would require to reset it.

We got an inquiry to reset such a counter when the system is ready, tested before going online.

**Expected behavior**
This ticket is to provide a feature to delete all the tips and reset the internal counters about submissions.

**Comment by evilaliv3** [comment]
This ticket is partially duplicated and in overlap with:
- https://github.com/globaleaks/GlobaLeaks/issues/971
- https://github.com/globaleaks/GlobaLeaks/issues/972

**Comment by mryber** [comment]
I am being asked for this as well, is there a counter in the database that can be reset, until a more permanent solution has been worked out?

**Comment by evilaliv3** [comment]
I'm sorry @kituser, i just saw your comment now.

In a matter of days, hopefully today i will release a patch that would make this possible.

**Comment by evilaliv3** [comment]
Closing as implemented.
