### ISSUE TITLE
Username in the UserBox aren't the one of the logged-in user

### ISSUE THREAD

**Issue by davelip** [globaleaks/GlobaLeaks#2454]
**Current behavior**
The username show in the UserBox (in the right-high corner) doesn't update her value after log-in with different users.
The case that different users use the same computer and browser is a border line use case.

**Expected behavior**
The username showed in the UserBox are the one of the loggedin user.

**Steps to reproduce the problem or feature illustration**

1. Log-in with an user (p.e. admin).
2. See Admin in the UserBox
3. Log-out
4. Log-in with a different user (p.e. recipient).
5. See Admin in the UserBox

**What is the motivation or use case for changing the behavior?**
To show in the UserBox one name of the logged-in user.

**GlobaLeaks version:**
v3.4.1
devel

**Browser:**
Chrome 70
Firefox

**Server Operating System and Version (if applicable):**
Ubuntu(18.04)

**Client Operating System and Version (if applicable):**
Ubuntu(18.04)

**Comment by evilaliv3** [comment]
Thank you @davelip for the reporting and for the quality of your contribution.

Going to merge #2455
