### ISSUE TITLE
Error modifying context - additional_questionnaire_id type validation failure

### ISSUE THREAD

**Issue by gneotel** [globaleaks/GlobaLeaks#2456]
I tried to modify a custom context to increase the default expiration (from 15 to 180 days).
Saving I receive the following error:
Errore!
Errore di validazione
dell'input [Key
(additional_questionnaire_id)
type validation failure]

From then on I'm not able to save changes to context and questionnaires.
The changes looks like saved but are not applied. If I logout and login again I find the old settings. 

Just before this happened I updated  to globaleaks 3.5.1

I run globaleaks 3.5.1
on  Ubuntu 18.04.1 LTS

I have the same error from different browsers.

**Comment by gneotel** [comment]
This is the error in the log file:
2018-11-15 13:28:47+0000 [-] [E] -- Invalid python_type, in [None] expected ^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$|^[a-z_]{0,100}$|^$
2018-11-15 13:28:47+0000 [-] [E] Received key additional_questionnaire_id: type validation fail

**Comment by evilaliv3** [comment]
Thank you for reporting this @gneotel.

We are investigating the issue and will get back to you as soon the reason is identified.

**Comment by evilaliv3** [comment]
@gneotel: i'm currently not able to reproduce the failure.

Could you try to clear the cache of your browser, log in again and see if you still get this issue?

**Comment by evilaliv3** [comment]
@gneotel: We emitted a patch that should address the problem.

Could you try to update to the release 3.5.2 and if it works for you?

**Comment by gneotel** [comment]
I've tried with two different browsers, same issue.
Before saving, the first time I've got the error, I've opened the "Questionario aggiuntivo" dropdown and put it back to empty before saving.
This is a screenshot from my browser (incognito mode to follow your indication)
![context](https://user-images.githubusercontent.com/7541726/48567473-62fe4100-e8fd-11e8-89e8-aef9c2d7ddd3.JPG)

**Comment by gneotel** [comment]
I selected an existin questionnaire for "Questionario aggiuntivo", saved (successfully) and then changed back to emty and saved again.

Now I don't have the error when saving anymore but as you can see in the screenshot I have two empty lines in the select.

I'm still not able to save changes to questionnaires.

![context2](https://user-images.githubusercontent.com/7541726/48567994-af964c00-e8fe-11e8-8eb1-de8508d4f0d4.JPG)

**Comment by gneotel** [comment]
I've updated.
Maybe the update fixed the cause of the problem but I think that now something in my configuration is still inconsistent.
I still have the double empty Questionario aggiuntivo and I'm still not able to save changes to questionnaires.

**Comment by gneotel** [comment]
You are right , the problem with the context is gone, I don't have the double empty choice anymore and I can save the settings.

Anyway I'm still not able to save the questionnaire settings. Maybe is a different issue.
I made a small screen recording to show the problem:
[2018-11-16 09-45-03.zip](https://github.com/globaleaks/GlobaLeaks/files/2588557/2018-11-16.09-45-03.zip)
