### ISSUE TITLE
GL 3.5.5 the flag visibility_subject_to_authorization in whistleblower_identity field are not saved/retrieved correctly from the database

### ISSUE THREAD

**Issue by davelip** [globaleaks/GlobaLeaks#2463]
**Current behavior**
In /#/admin/questionnaires the standard field whistleblower_identity (in IT "Vuoi fornire i tuoi dati identificativi?") has a field visibility_subject_to_authorization (in IT "Assoggetta la visibilità della risposta all'autorizzazione da parte del custode"), the choise done over that checkbox doesn't are replied on the database, the value in the database aren't showed on that checkbox. 
Same on prompt_confirmation_upon_negative_answer (in IT "Chiedi conferma in caso di risposta negativa").

**Expected behavior**
Changes on the interface are reflected on the database.

**Steps to reproduce the problem or feature illustration**
With an admin profile go to /#/admin/questionnaires add a standard whistleblower_identity field to a questionnaire, set to true visibility_subject_to_authorization and prompt_confirmation_upon_negative_answer.
Reload the questionnaire, your choise are lost.

**What is the motivation or use case for changing the behavior?**
It's a bug, in GL 3.4.1 this works correctly.

**GlobaLeaks version:**
GL 3.5.5

**Browser:**
Chrome 70

**Server Operating System and Version (if applicable):**
Ubuntu 18.04

**Client Operating System and Version (if applicable):**
Ubuntu 18.04

**Comment by evilaliv3** [comment]
Thank you for reporting this @davelip.

We are investigating the issue.

**Comment by evilaliv3** [comment]
Closing as fixed, will be released in 3.5.6!

**Comment by evilaliv3** [comment]
Thank you @davelip !

If integrated your patch in place of mine to preserve the credits for your contribution: https://github.com/globaleaks/GlobaLeaks/pull/2464
