### ISSUE TITLE
Bug: SyntaxError: 'return' outside function

### ISSUE THREAD

**Issue by andy650429** [globaleaks/GlobaLeaks#2483]
Hi everyone
I'm using GL 3.5.8 on Ubuntu Server 18.04.01 LTS.
During the update (apt update / apt upgrade) the system tried to install GL 3.6.0 but it failed.

The error is as follows:

**Current behavior**

Preparativi per estrarre .../globaleaks_3.6.0_all.deb...
Traceback (most recent call last):
  File "/usr/bin/gl-admin", line 21, in <module>
    from globaleaks.db import get_db_file
  File "/usr/lib/python3/dist-packages/globaleaks/db/__init__.py", line 12, in <module>
    from globaleaks.db.appdata import db_load_default_questionnaires, db_load_default_fields
  File "/usr/lib/python3/dist-packages/globaleaks/db/appdata.py", line 8, in <module>
    from globaleaks.handlers.admin.field import db_create_field, db_add_field_attrs
  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/field.py", line 10, in <module>
    from globaleaks.handlers.base import BaseHandler
  File "/usr/lib/python3/dist-packages/globaleaks/handlers/base.py", line 16, in <module>
    from globaleaks.event import track_handler
  File "/usr/lib/python3/dist-packages/globaleaks/event.py", line 3, in <module>
    from globaleaks.state import State
  File "/usr/lib/python3/dist-packages/globaleaks/state.py", line 27, in <module>
    from globaleaks.utils.templating import Templating
  File "/usr/lib/python3/dist-packages/globaleaks/utils/templating.py", line 722
    return subject, body
    ^
SyntaxError: 'return' outside function
dpkg: errore nell'elaborare l'archivio /var/cache/apt/archives/globaleaks_3.6.0_all.deb (--unpack):
 new globaleaks package pre-installation script subprocess returned error exit status 1
Si sono verificati degli errori nell'elaborazione:
 /var/cache/apt/archives/globaleaks_3.6.0_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Steps to reproduce the problem or feature illustration**

apt update
apt upgrade

only GL 3.6.0 package is available

**GlobaLeaks version:** 

now 3.5.8 --> 3.6.0 failed

**Browser:**

System unavailable from all browser

**Server Operating System and Version (if applicable):**
 
Ubuntu server 18.04.01 LTS

Now the system is not working and I can not reactivate it.

What could be the problem?

Thanks and bye!

Andrew

**Comment by evilaliv3** [comment]
@andy650429: are you running the official globaleaks or a modified version?

Actually the stacktrace you are reporting has lines number that are not in line with the current globaleaks release.

Specifically: ```File "/usr/lib/python3/dist-packages/globaleaks/utils/templating.py", line 722
return subject, body```

**Comment by andy650429** [comment]
Hi Giovanni,

i running officiale globaleaks (3.5.8), with some minor changes I had read on this platform to manually try to manage the answers to the Custodian.
If this is, I try to restore the files I had edited.
If it does not work, I will do a reinstallation: in this case I ask you if the database is maintained or if it is completely overwritten.

Meanwhile, thanks and hello

**Comment by andy650429** [comment]
OK! now works! I restored the previous versions of the two files and everything went well.
Thank you!
At soon! 
Now test the new platform!
Bye!
