### ISSUE TITLE
First frontend access is too slow

### ISSUE THREAD

**Issue by FabrizioA** [globaleaks/GlobaLeaks#2487]
At every "first" (between about 1h of time) url open, the application takes very long time to returns response.
After first attempt, any other pages open correctly.

**Expected behavior**

Normal response time at every first access to the application.

**Steps to reproduce the problem or feature illustration**

Access the application trough url

**What is the motivation or use case for changing the behavior?**

Because the application takes a very long time to open at every first access, many users cosider the application broken.

**GlobaLeaks version:**

GlobaLeaks version 3.5.8
Database versione 45

Browser: any browser (I've tested with Chrome and Safari)
SO Server: Ubuntu 18.04.1

Client Operating System: Mac and Windows

**Comment by evilaliv3** [comment]
Thank you @FabrizioA for your feedback,

the application does initialize fully but definitely 1 hour of time of loading is too much.

the first load does take 2 seconds

we have in production like https://try.globaleaks.org that serve 1000 demos with just with a vps with two cores and 2GB of RAM.

can you provide the url to the site and clarify me about the capabilities of the server?

**Comment by FabrizioA** [comment]
Hi Giovanni,

Thank you for your reply.
Sorry, but I mean 1h between on session and another.
Anyway, you all right, by visiting the url you can get the problem:
http://whistleblowing.asp.sr.it

Please try it one time and the after many minutes... you will see that it take many seconds to load the first page at the beginning of each session.

Let me know what do you thing.
Thank you
Ciao!

**Comment by evilaliv3** [comment]
Thank you @FabrizioA,

actually i confirm that i found the first request very slow, but then changing browser or opening a different tab it was instantaneous with the correct timing of almost 2 seconds.

This make me thing that the issue could be related by a firewall in your network.

Could you try connecting locally (e.g. via an ssh tunnel or via curl) and thus bypassing the firewall?

**Comment by FabrizioA** [comment]
Hi,

Tomorrow morning I’ll try it, I’ll let know you.
Thank you for your suggestion.

Fabrizio

**Comment by FabrizioA** [comment]
Hi Giovanni,

You all right, it’s a problem of our proxy.
Thank you for your advice.

Ciao
Fabrizio

**Comment by evilaliv3** [comment]
You are welcome @FabrizioA, thank you for your feedback!
