### ISSUE TITLE
Make it possible to configure a different email for the 2FA

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2491]
It has been recognized valuable to make it possible for users to configure a different email for the two factors authentication.

The requirement would enable to set a different email dedicated to the 2FA on the phone and used only on the phone of the user. This email could be private and independent from the company official email.
This is really interesting also considering that many phone providers provide a mail-address to phone-number service.

This ticket extends the implementation as for ticket: https://github.com/globaleaks/GlobaLeaks/issues/2481

**Comment by webconexus** [comment]
Any updates on this ticket yet?

**Comment by evilaliv3** [comment]
No i'm sorry @webconexus; we've been dealing with many stabilization fixes and i still did not found the time.

I will try to put this implementation in the next version that will include database changes.

**Comment by evilaliv3** [comment]
@fpietrosanti: after discussing this with @webconexus we identified that making it possible to configure an additional email for the 2FA would lead to the issue of having to validate the email.

We propose to implement the same feature in a slightly different way:
- 1. Leaving the account email as it is (the email will continue to be the one related to 2FA)
- 2. Adding a "Notification email:" as a setting where to configure an email (that do not require any validation!)

**Comment by fpietrosanti** [comment]
After discussion at dinner we agreed that we will make the secondary 2FA email configurable only by the Admin, without self-service functionality of the recipient, as a way to prevent possible end-user lock-out.

**Comment by evilaliv3** [comment]
What do you think @webconexus? Would this be enough for your use case?

**Comment by webconexus** [comment]
Yes exactly I can completely understand your point of view @evilaliv3. We should aim for achieving this feature with the least amount of added complexity for the platform and end-user. So it is perfect for me :)

**Comment by webconexus** [comment]
Any updates yet on this @evilaliv3 :) ?

**Comment by evilaliv3** [comment]
I'm sorry @webconexus i just saw your message now.
Actually not, there is still no update for this at the moment.

**Comment by evilaliv3** [comment]
@webconexus with release 3.11.0 we deprecated email based 2FA in favor of the most secure TOTP based 2FA authentication: https://github.com/globaleaks/GlobaLeaks/issues/2664

This deprecates this ticket. 

When updating to 3.11.0 remember to inform your users to enroll with two factors authentication. They can do it by themselves in their user preferences.
