### ISSUE TITLE
Language error in warning email about disk usage

### ISSUE THREAD

**Issue by frozen-sky** [globaleaks/GlobaLeaks#2503]
**Current behavior**

GlobaLeaks sends emails if this usage is getting low. However, there is a small language error in that email, which is confusing. The email writes currently:

"
...

The disk usage is 5GB of 107GB.
...
"

**Expected behavior**

You would expect or:

The disk usage is 102 GB of 107GB

or 

The available disk space is 5 GB of 107GB

(in this example)

**Steps to reproduce the problem or feature illustration**

Get a full disk and wait for the email

**What is the motivation or use case for changing the behavior?**

Make it more clear what is going on

**GlobaLeaks version:**

 3.6.7

**Browser:**

Not applicable

**Server Operating System and Version (if applicable):**

Ubuntu 16.04

**Client Operating System and Version (if applicable):**

Not applicable

**Comment by evilaliv3** [comment]
Thank you @frozen-sky for reporting this.

I'm going to issue a patch and adopt your second suggestion: ```The available disk space is 5 GB of 107GB```.
