### ISSUE TITLE
Error in repository after upgrade to 3.6.8

### ISSUE THREAD

**Issue by frayber** [globaleaks/GlobaLeaks#2505]
Hi, I've just upgraded from 3.6.7 to 3.6.8
After this, when I perform "apt-get update" I get this error:

`Err:5 http://deb.globaleaks.org bionic/ Release.gpg
  The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>` 

so I cannot upgrade to 3.6.9
Thanks

**Comment by evilaliv3** [comment]
Thank you @fryber for reporting this.

would you please retry now?

I think you just tried to update in the exact moment we were releasing the 3.6.10 and due to this fact you found the repository not signed.

**Comment by frayber** [comment]
Yes, I got update! Thank you
