### ISSUE TITLE
Whitelisted IP adresses for Recipient not saved in configuration

### ISSUE THREAD

**Issue by mryber** [globaleaks/GlobaLeaks#2507]
**Current behavior**
When adding IP address to be whitelisted for Recipient access, the single IP or list of IP's is not saved. and there for the whitelist filter is not activated.
Admin, Custodian and Whistleblower whitelist works fine.

**Expected behavior**
Expect to see the list of IP addresses shown, and that the filter works.

**Steps to reproduce the problem or feature illustration**
I just type in 1 or multiple IP's (if multiple, seperated as instructed with a comma.) Click save and the checkmark box is cleared and the Whitelist IP addresses field is empty.
I was running 3.6.7, så I upgraded to 3.6.11 to ensure if the issue has been resolved, but it hasn't been resolved in newest version (at writing moment, it is 3.6.11).

**What is the motivation or use case for changing the behavior?**
The need for the feature, is to ensure that only allowed IP addresses will be able to access the Recipient interface, when recipient comes from specific adresses.

**GlobaLeaks version:**
v3.6.7 -> 3.6.11

**Browser:**
Chrome, Firefox, Internet Explorer

**Server Operating System and Version (if applicable):**
Ubuntu LTS 18.04.1

**Client Operating System and Version (if applicable):**
Linux, Windows 10

**Comment by mryber** [comment]
Hi, I have these screen shot of the issue:

When I add an IP address, I click the check mark for Recipient and add the IP address, then I click 'Save'
![adding_recipient_ip](https://user-images.githubusercontent.com/46743975/52198030-d8751000-2861-11e9-8901-39361b67a247.png)

When I clicked 'Save', the browser returns like nothing was changed:
![when_save_is_clicked_recipient_list_is_empty](https://user-images.githubusercontent.com/46743975/52198082-fe021980-2861-11e9-9338-54eb161b7d9b.png)

I have also tried to fill in IP's in both Admin and Custodian, and then Recipient, only Recipient will not be saved.

**Comment by evilaliv3** [comment]
Thank you for reporting this @mryber.

We will investigate the issue and get back to you here.

**Comment by evilaliv3** [comment]
Thank you @mryber, the bug is confirmed and corrected in https://github.com/globaleaks/GlobaLeaks/commit/d97f1fcfcf06f13ceaa29614a4f7e2c1201a3f34

The patch will be included in upcoming release 3.6.12
