### ISSUE TITLE
My App is off

### ISSUE THREAD

**Issue by fiyona** [globaleaks/GlobaLeaks#2509]
I was using Ubuntu trusty with the previous version of globaleaks  and now the app is off, i have tried updating and getting endless errors, 
Err:1 http://deb.globaleaks.org xenial/ globaleaks 3.6.11
404 Not Found
E: Failed to fetch http://deb.globaleaks.org/xenial/globaleaks_3.6.11_all.deb 404 Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by evilaliv3** [comment]
@fiyona: The release 3.6.11 for xenial is out but please follow the above instructions and pass to bionic.
