### ISSUE TITLE
Whitelist for Recipients does not work

### ISSUE THREAD

**Issue by mryber** [globaleaks/GlobaLeaks#2512]
**Current behavior**
The whitelist for recipients now correctly saves the IP adresses in the Database, but it does not block the recipient login, if it comes from an IP that is not in the whitelist.

==> access.log <==
Admin whitelist/block works, gives an 401 during login from an IP that is not whitelisted.
[08/Feb/2019:06:29:16 +0000] [REMOVED_IP_ADDRESS] 1 200 GET /sites 2 0ms "[REMOVED_USER_AGENT]"
[08/Feb/2019:06:29:28 +0000] [REMOVED_IP_ADDRESS] 1 401 POST /authentication 105 3616ms "[REMOVED_USER_AGENT]"

Recipient whitelist/block does not work, specified allowed IP: 192.168.0.1, but coming from any other IP still allowed access:
[08/Feb/2019:06:30:05 +0000] [REMOVED_IP_ADDRESS] 1 200 GET /sites 2 0ms "[REMOVED_USER_AGENT]"
[08/Feb/2019:06:30:17 +0000] [REMOVED_IP_ADDRESS] 1 201 POST /authentication 197 3634ms "[REMOVED_USER_AGENT]"
[08/Feb/2019:06:30:17 +0000] 10.172.17.13 1 200 GET /receiver/preferences 842 28ms "Mozilla/5.0 (X11; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"
[08/Feb/2019:06:30:19 +0000] 10.172.17.13 1 200 DELETE /session 0 0ms "Mozilla/5.0 (X11; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0"

From the database I have this:
sqlite> select * from config where var_name="ip_filter_receiver";
1|ip_filter_receiver|"192.168.0.1"|2019-02-08 06:42:51.017354
sqlite> 

So, the filter is configured and saved in the database, but the code that should block the access isn't working.

**Expected behavior**
Expected to get and error or 401 when trying to log in from an "disallowed" IP.

**Steps to reproduce the problem or feature illustration**
Adding a specific allowed IP in the IP Access control - Recipient list.

**What is the motivation or use case for changing the behavior?**
To make the solution ensure that recipient can only login from known/allowed IP adresses.

**GlobaLeaks version:**
v3.6.12

**Browser:**
Firefox, Chrome, Internet Explorer

**Server Operating System and Version (if applicable):**
Ubuntu 18.0.4 LTS

**Client Operating System and Version (if applicable):**
Windows, Linux

**Comment by mryber** [comment]
I wonder, since the code for adding the IP to the database changed the name of **ip_filter_recipient** to **ip_filter_reciever**, did the code that gets the IP from the database, to check against the whitelist in authentication, change as well?

**Comment by mryber** [comment]
backend/globaleaks/db/__init__.py:

The for-loop: for x in [('admin', 'ip_filter_admin_enable', 'ip_filter_admin'), where ip_filter_receiver* was changed, could it be that the recipient (first entry for recipients) need to be changed to receiver?

For the check for HTTPS (next for loop) receiver is used, so could it be that 'receiver' needs to be used for the check for recipient whitelist IP as well?

So the code would be:

```
for x in [('admin', 'ip_filter_admin_enable', 'ip_filter_admin'),
                  ('custodian', 'ip_filter_custodian_enable', 'ip_filter_custodian'),
                  ('receiver', 'ip_filter_receiver_enable', 'ip_filter_receiver'),
                  ('whistleblower', 'ip_filter_whistleblower_enable', 'ip_filter_whistleblower')]:
            if State.tenant_cache[tid].get(x[1], False) and State.tenant_cache[1][x[2]]:
                State.tenant_cache[tid]['ip_filter'][x[0]] = State.tenant_cache[1][x[2]]

```

**Comment by mryber** [comment]
I just tested on the updated 3.6.12 installation I have, by changing the file:

/usr/lib/python3/dist-packages/globaleaks/db/__init__.py:

by changing line 163 from:

('recpient', 'ip_filter_receiver_enable', 'ip_filter_receiver'),

to

('receiver', 'ip_filter_receiver_enable', 'ip_filter_receiver'),

And that makes the whitelist check working.

**Comment by mryber** [comment]
I have tried to make the change in a fork/branch which I have submitted for review... hopefully :-)

**Comment by evilaliv3** [comment]
Thank you @mryber!

I confirm the bug and the validity of your patch.

I'm going to proceed with the merge and a release of a 3.6.13 including your correction.

**Comment by evilaliv3** [comment]
@mryber: would you like to open a pull request?
