### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by wolfgangsalm** [globaleaks/GlobaLeaks#2516]
**Current behavior**

installation delivers:
Hit:1 http://at.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://at.archive.ubuntu.com/ubuntu bionic-updates InRelease
Ign:3 http://deb.globaleaks.org bionic/ InRelease
Hit:4 http://at.archive.ubuntu.com/ubuntu bionic-backports InRelease
Get:5 http://deb.globaleaks.org bionic/ Release [1.506 B]
Get:6 http://deb.globaleaks.org bionic/ Release.gpg [566 B]
Hit:7 http://security.ubuntu.com/ubuntu bionic-security InRelease
Ign:6 http://deb.globaleaks.org bionic/ Release.gpg
Reading package lists...
W: GPG error: http://deb.globaleaks.org bionic/ Release: The following signatures were invalid: **BADSIG** 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
E: The repository 'http://deb.globaleaks.org bionic/ Release' is not signed.

**Expected behavior**

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

**Browser:**

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
Thank you for notifying this @wolfgangsalm,

would you please recheck now?

**Comment by wolfgangsalm** [comment]
Works now, many thanks!
