### ISSUE TITLE
Getting error while compiling Apparmor for Raspberri Pi B3+

### ISSUE THREAD

**Issue by deepaksgh** [globaleaks/GlobaLeaks#2517]
**Current behavior**

I am trying to include apparmor to the yacto build system for the raspberry pi B3+. While building apparmor i am getting below error.

**Expected behavior**

Apparmor should build without compilation error.

**Steps to reproduce the problem or feature illustration**

downloaded meta security from 
#git clone git://git.yoctoproject.org/meta-security
move the complete folder into /poky/
added meta-security path in bblayers.conf
then build using below command
#bitbake rpi-basic-image

error_logs:
Wl,-Bdynamic -lpthread
| make[1]: Leaving directory '/home/ls-3121aa212162/Desktop/ramya/yocto_rpi/meta-raspberrypi-master/rpi/rpi-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/apparmor/2.12-r0/apparmor-2.12/parser'
| LANG=C "../apparmor_parser" -S -I errors >/dev/null errors/okay.sd
| ../apparmor_parser: 1: ../apparmor_parser: Syntax error: word unexpected (expecting ")")
| Makefile:32: recipe for target 'error_output' failed
| make: *** [error_output] Error 2
| make: Leaving directory '/home/ls-3121aa212162/Desktop/ramya/yocto_rpi/meta-raspberrypi-master/rpi/rpi-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/apparmor/2.12-r0/apparmor-2.12/parser/tst'
| ERROR: oe_runmake failed
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_compile_ptest_base (log file is located at /home/ls-3121aa212162/Desktop/ramya/yocto_rpi/meta-raspberrypi-master/rpi/rpi-build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/apparmor/2.12-r0/temp/log.do_compile_ptest_base.18563)
ERROR: Task (/home/ls-3121aa212162/Desktop/ramya/yocto_rpi/meta-raspberrypi-master/rpi/sources/poky/meta-security/recipes-security/AppArmor/apparmor_2.12.bb:do_compile_ptest_base) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1446 tasks of which 1445 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/ls-3121aa212162/Desktop/ramya/yocto_rpi/meta-raspberrypi-master/rpi/sources/poky/meta-security/recipes-security/AppArmor/apparmor_2.12.bb:do_compile_ptest_base
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

**Browser:**

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
Closing as not related to GlobaLeaks

**Comment by deepaksgh** [comment]
Hi Evilaiv,
If this build error is not related to GlobaLeak, then to whom i need to contact?
