### ISSUE TITLE
 Warning! The platform does not seem to be reachable with the configured hostname. 

### ISSUE THREAD

**Issue by mryber** [globaleaks/GlobaLeaks#2518]
**Current behavior**
We are having an issue with access to the GlobaLeaks site, I try to verify hostname, but get the following error:

` Warning! The platform does not seem to be reachable with the configured hostname. `

The host is NAT'ed behind a firewall, meaning that the firewall reacts on the public IP, forwarding requests to the host itself.

We have tried to change the hostname of the server, to match the web-address being called,and we even tried putting it in the /etc/hosts file, it keeps coming up with the Warning. Issue is that from some connections we can reach it, and from some we can't, even though two client connections with direct internet access, one works, the other doesn't.

CURL output:

```
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* Operation timed out after 300729 milliseconds with 0 out of 0 bytes received
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
curl: (28) Operation timed out after 300729 milliseconds with 0 out of 0 bytes received
```

On host where we get through, CURL output gives us:

```
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
```

Due to the owner of the domain, we created a CSR which was signed, by the domain owner CA, for an internal test system I did the exact same procedure without any issues.

Errors seen in the globaleaks.log, and I'm not sure if it's related:

```
2019-02-26 07:49:34+0100 [-] Starting factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f33c50ab840>, <twisted.internet.endpoints.HostnameEndpoint object at 0x7f33c5000748>)
2019-02-26 07:49:34+0100 [-] Stopping factory _HTTP11ClientFactory(<function HTTPConnectionPool._newConnection.<locals>.quiescentCallback at 0x7f33c50ab840>, <twisted.internet.endpoints.HostnameEndpoint object at 0x7f33c5000748>)
2019-02-26 07:49:35+0100 [-] [E] Unhandled exception raised:
2019-02-26 07:49:35+0100 [-] [E] twisted.internet.error.ConnectionRefusedError Connection was refused by other side\n\ntwisted.internet.error.ConnectionRefusedError: Connection was refused by other side: 111: Connection refused.\n
```

I have asked the hosting site about any IDS/IPS or firewall configuration, related to any possible issues, the only thing we know, is that the host is NAT'ed.

I have tried to do a TCPdump on both client side, and got the dump from server side, alle we see is a lot of retransmissions and then a Reset and a FIN at the end.

In Firefox it stalls a Establishing TLS handshake, in Google Chrome it stalls with Establishing secure connection and Internet Explorer doesn't report anything....

**Expected behavior**
We expect it to validate the web-adress/hostname we define, and that all sources are able to load the site.

**Steps to reproduce the problem or feature illustration**
N/A

**What is the motivation or use case for changing the behavior?**
When we go live with the system, we have a strong motivation to get this issue solved, as we might not know if any possible whistleblowers will be able to access the site or not.

**GlobaLeaks version:**
v3.6.16

**Browser:**
Internet Explorer, Firefox, Google Chrome

**Server Operating System and Version (if applicable):**
Ubuntu 18.04.1 LTS

**Client Operating System and Version (if applicable):**
Linux, Windows

**Comment by mryber** [comment]
I can see that our internal dev/test host also has issues verifying it's hostname, we furthermore get these:

`/usr7lib/python3/dist-packages/globaleaks/handlers/admin/operaton.py, lin e75, in verify_hostname, raise EnvironmentError('Response unexpected')`

and

`endpoints.py line 954, no result for hostname lookup`

though the host is able to do hostname lookup-

**Comment by evilaliv3** [comment]
@fpietrosanti do you have any hint on this?

**Comment by mryber** [comment]
We have a proxy that we also go through, where the Proxy denies our request, once it reaches HTTPS. We are investigating that part, but unfortunately it doesn't give us much information, other than it has denied access to the live site. On this point we see the same issue as with the direct connection without a proxy, a lot of retransmissions and at the end a reset.

I just tested the live site through that same direct connection on a cellphone, no issues on that point, which I find very weird, I just wonder if there are others who have seen the same kind of issue?

Two basically identical Linux workstation, same patchlevel, same browser versions etc etc, both on direct connection without proxy, the one works fine, the other fails.

What are the requirement for outgoing traffic from the server (except from TOR service)?

**Comment by fpietrosanti** [comment]
We have many verify_hostname errors on #2373 and #2411 and #2193 .

Basically i think that before we call verify_hostname we must:
a) Verify on the backend, proactivelly and preliminary each technical / communication related requirement in advance
b) Report specific reason of failure following multiple technical / communication proactive and preliminary before going within the verify_hostname functions

A robust improvement on hostname validation is at #2139 .

We would miss to have preemptive checks on:
1. DNS Lookup (to check that hostname exists, it's valid and not bogus as per #2139)
2. Outgoing connection functionalities (to check that connection to LetsEncrypt Server works)
3. Incoming connection functionality (to check that inbound connection to the specified hostname works)

Only after those set of checks are preemptively executed and reported for success/failure, the system should trigger the LetsEncrypt certificate registration, giving a preemptive error diagnostic to the admin.

**Comment by mryber** [comment]
Okay, then this one can be closed. According to the issues we see about missing Server Hello, I think we have an issue at the hosting provider.

**Comment by mryber** [comment]
Some kind of MTU issue on infrastructure, can result in data package loss, regarding to the TLS handshake issue.
