### ISSUE TITLE
How to set up multiple sites

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2529]
I have set up a working test platform and trying to create multiple tenants but facing issues.
the central domain is for example testdomain.mydomain.eu 
The user creates the the site1.testdomain.mydomain.eu  
while the account can be accessed  testdomain.mydomain.eu/t/4/  (and tor as well)
When one is trying to access site1.testdomain.mydomain.eu gets the message

**This site can’t be reached 
site1.testdomain.mydomain.eu’s server IP address could not be found.**

Am I missing something obvious? I have no experience with multi domain services.

Version 3.6.30 on Ubuntu 18.04 lts, client win 10 chrome

**Comment by evilaliv3** [comment]
@elbill: first of all you should point a wildcard DNS entry to your server ip address.

e.g. *.testdomain.mydomain.eu should point to the IP of the multitenant infrastructure.

try to make this on your DNS settings and all should then by clear to you.

Feel free to make other questions for any of your doubts.

**Comment by elbill** [comment]
Great. It seems to be working.
Thanks!

**Comment by elbill** [comment]
@evilaliv3 
Sorry for reopening the issue. One more question that I believe is relevant on multi site documentation.
What is the best way to handle multi-site SSL. I have created a wildcard DNS entry *.testdomain.mydomain.eu and a user created site1.testdomain.mydomain.eu. The site seems that is not secure. Do I need to create or purchase a wildcard SSL for *.testdomain.mydomain.eu? I have tried but did not work. What is the best way to deal with this?

**Comment by evilaliv3** [comment]
You have to options:
- buy a wildcard certificate and configure it on the root tenant
- configure manually letsencrypt on the secondary tenants but depending on how many they are i guess you could reach easily a letsencrypt limit.

**Comment by elbill** [comment]
it all worked fine. thanks.

**Comment by evilaliv3** [comment]
You are welcome @elbill, and thank you for your confirmation!
