### ISSUE TITLE
Make it possible for the whistleblower to navigate through questionnaire steps with mandatory questions

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2547]
**Current behavior**
It has been noted by multiple stakeholders of EAT project that in a multi-step questionnaire with mandatory questions it would be very useful for a whistleblower to see which are the questions of the next-steps, before filling the first steps.

**Expected behavior**
This ticket is to enable a configurable behaviour (enable/disable it) to allow a whistleblower to navigate trough steps also in presence of mandatory questions not filled in.

When this behaviour is enabled, the wb must be able to see the step questions, but must not be able to click submit button, being informed on this attempt, about missing mandatory questions yet to be answered.

**Comment by evilaliv3** [comment]
Implementation corrected and already included in 3.9.X
