### ISSUE TITLE
Exception when activating site previously deactivated in admin panel

### ISSUE THREAD

**Issue by qertoip** [globaleaks/GlobaLeaks#2548]
```
Platform: signalli
Host: secure.signalli.com (k54fmn67brfw67uk.onion)
Version: 3.6.44

KeyError Mapping key not found.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)

  File "/usr/lib/python3/dist-packages/globaleaks/rest/decorators.py", line 13, in wrapper
    if self.state.tenant_cache[self.request.tid].basic_auth and not self.bypass_basic_auth:

KeyError: 3

```

**Current behavior**

Exception when activating site previously deactivated in admin panel.

**Expected behavior**

**Steps to reproduce the problem or feature illustration**

Activate multi-tenant, create a second site, deactivate it, activate it.

**Browser:**
Firefox 66.0.2

**Server Operating System and Version (if applicable):**
Ubuntu 18.04

**Comment by evilaliv3** [comment]
Thank you for reporting this @qertoip.

I guess no one currently has never used the activate/decactivate feature in production so its surely possible that the feature requires some stabilization.

We will investigate the issue and let you know.

**Comment by evilaliv3** [comment]
@qertoip: i've found one of the reason that was for surely preventing the application to work correctly in the activation/deactivation of secondary tenants.

I will include this patch in 3.6.64 but it is also possible that the feature will require some other fixes to work correctly.

than you for your patience and the support in reporting the malfunctions you are encountering.

**Comment by evilaliv3** [comment]
Fixed.
