### ISSUE TITLE
The /etc/globaleaks config seems unused

### ISSUE THREAD

**Issue by qertoip** [globaleaks/GlobaLeaks#2549]
**Current behavior**

The `settings.py` line `self.config_file_path = '/etc/globaleaks'` does not seem to be used anywhere in the source code.

**Expected behavior**

A working and documented way to configure global settings (like SMTP etc) that will be inherited by sites in a multi-site setup.

**Temporary fix**

Remove the misleading line from `settings.py`.

**Comment by evilaliv3** [comment]
Thank you for reporting this; i confirm that this line should be removed as outdated.
