### ISSUE TITLE
Selecting site default language is not effective

### ISSUE THREAD

**Issue by qertoip** [globaleaks/GlobaLeaks#2550]
**Current behavior**

Selecting site default language other than English has no effect. The fresh users will face the English version anyway and be forced to manually pick their language.

**Expected behavior**

The site default language setting should be effective.

**Steps to reproduce the problem or feature illustration**

1. Add a second language in admin / site settings / languages. For example `[pl] Polski`.
2. Set the `[pl] Polski` as default and save.
3. Start a fresh browser with no past cookies and access the site. The site will render in English.

**GlobaLeaks version:**

3.6.44

**Browser:**

Firefox 66.0.2

**Server Operating System and Version (if applicable):**

Ubuntu 18.0.4

**Comment by evilaliv3** [comment]
@qertoip: GlobaLeaks, for usability reasons, implement detection of the browser language and perform automatic selection of the language on bahalf of the user. This is why you are probably getting the page in english.

**Comment by qertoip** [comment]
Yes this is indeed the browser locale!

In that case:
- per-user language setting is ineffective; probably should override browser locale if set explicitly by the user?
- per-site language setting has unclear purpose; maybe should be removed or explained?

Thanks a lot for your support!

**Comment by evilaliv3** [comment]
@qertoip: currently the user setting is used only for email notifications.

We should probably improve the user setting feature to make it possible to:
- configure "AUTO" as the default option
- if the user set a language different from "AUTO" load this setting immediately after the user login.

would this work for you?

**Comment by qertoip** [comment]
Yes, that would be awesome.

**Comment by evilaliv3** [comment]
Closing as the issue resulted to be a misunderstanding.

The above feature request will be moved to a new ticket.
