### ISSUE TITLE
Onion subdomains are treated as HTTP resulting in two big warnings (connection not secure, connection not anonymous)

### ISSUE THREAD

**Issue by qertoip** [globaleaks/GlobaLeaks#2551]
**Current behavior**

`http://subdomain.k54fmn67brfw67uk.onion/` - this kind of addresses are not recognized as Onion service. This results in two big warnings for the user.

**Expected behavior**

Recognize subdomains of the root onion domain as Tor connection.

**Steps to reproduce the problem or feature illustration**

Admin / Site management / (pick a second site) / Edit / (enter hostname) / Save

Go to http://hostname.youronionaddress.onion/

**GlobaLeaks version:**

3.6.44

**Browser:**

Tor Browser

**Server Operating System and Version (if applicable):**
Ubuntu 18.04

**Comment by evilaliv3** [comment]
@qertoip: which browser are you using while performingthis test?

Onion addresses and onionsubdomains could be accessed only via the Tor Browser that implements a different transport layer encryption that do not require nor benefit of HTTPS.

Could you try to access your onion subdomain via the Tor browser and check if your error persists?
In case the error persists would you please colllect screenshots and attach them to this ticket?

**Comment by qertoip** [comment]
I am using the Tor Browser. Here is the screenshot. 
![Screenshot from 2019-04-11 10-18-58](https://user-images.githubusercontent.com/109363/55960140-76bf9080-5c6c-11e9-8c09-5f8656c4d3ad.png)

**Comment by evilaliv3** [comment]
Thank you @qertoip,

with this screenshoot the but is clear to me.

i'm going to issue a patch that will be included in the next minor releae (3.6.45).

**Comment by qertoip** [comment]
Great to hear the fix is incoming.

One more thing, possibly related: when connecting via Tor to the **clearnet** domain the black warning is still present, which is misleading as the user is already using Tor. While using the onion version of the site is superior, this shouldn't result in that kind of loud warning in my opinion. One way is to simply to remove the warning in this case.

**Comment by evilaliv3** [comment]
@qertoip: the warning is shown every time we cannot guarantee that the user is using the tor browser.
