### ISSUE TITLE
Not possible to create new line or new paragraph on site presentation

### ISSUE THREAD

**Issue by kituser** [globaleaks/GlobaLeaks#2554]
**Current behavior**
New lines or paragraphs in the Presentation (found under 'Site Settings' in the admin part) are replaced with just a regular space, leaving a presentation in a not so nice looking presentation.
Likewise any URL's written are not recognized as and URL, and I have no idea and can not find information on how to specify an URL - fx. linking to ordinary guidelines.

**Expected behavior**
I expected that new lines in the text field (Presentation) will insert a new line or start a new paragraph, and that either URL's are automatically recognized, or that URL's can be specified by a specific code.

**Steps to reproduce the problem or feature illustration**
Reproducing is easy, when writing text in the Presentation field in Site settings and inserting new lines, they are not shown as new lines.

**What is the motivation or use case for changing the behavior?**
To be able to write a good presentation, which can be easier to read, and which can be split into different paragraphs for various reasons, and that linking to fx. guidelines using an URL, will be clickable, instead of a visitor has to mark the URL and copy/paste it into a new browser window.

**GlobaLeaks version:**
v3.6.16+

**Browser:**
This is not related to any browsers, but we see the same thing in Internet Explorer, Firefox and Google Chrome.

**Server Operating System and Version (if applicable):**
N/A

**Client Operating System and Version (if applicable):**
N/A

**Comment by evilaliv3** [comment]
Thank you @kituser for reporting the issue about the impossibility to add newlines in the node presentation.

This is a regression in relation to previous releases and i'm going to fix immediately in the next stable release (3.6.45).

As for the possibility to add links this instead will be managed in the future as there are many concerns to be solved in relation to add a feature like this; lets move this discussion here: https://github.com/globaleaks/GlobaLeaks/issues/914
