### ISSUE TITLE
Give temporary exclusivity of tips to a group of recipients

### ISSUE THREAD

**Issue by SylvainFPU** [globaleaks/GlobaLeaks#2556]
This is relevant for GL implementation for several media outlets who also are competitors.

**Current behavior**
The whistleblowers select several recipients based on personal/political/tactical affinity with the recipients. The tip is received by a bulk of recipients which might be competitors as media outlets.

As these media can't know which of the other recipients is working on the tip nor can they communicate among themselves, this situation is demotivating from a journalist point of view. 

**Expected behavior**
New feature: The whistleblower can give a preferential access to its tips to one or several recipients, for a limited amount of time. (3-4 days?)
The content of the tip (text + document is then normally shared with all the other recipient.

**What is the motivation or use case for changing the behavior?**
Some tips receive less attention and investigation due to this setup.

**Comment by evilaliv3** [comment]
Thank you for your input @SylvainFPU.

I consider the feature a bitt complicated if it involves the whistleblower choice.
Maybe this could be a random choice or a 'exclusive' feature for some of the recipients of publeaks.

I consider anyhow that even if this could be interesting for a journalistic project like publeaks, it would not fit in a general software use case.

What do you think?

**Comment by SylvainFPU** [comment]
I agree with you @evilaliv3 this is request exclusively from journalists in one of the platform where they prefer not to cooperate but to compete on the leaks. It is a very specific case.

It was agreed that I would raise the proposal anyway if some other users would have a similar interest. Maybe something for the future. Or a user behaviour to take into account§
