### ISSUE TITLE
Error when trying to duplicate a quetionaire containing "Selection box" or "Checkboxes"

### ISSUE THREAD

**Issue by obiuan81** [globaleaks/GlobaLeaks#2557]
**Current behavior**
When trying to duplicate a quetionaire containing "Selection box" or "Checkboxes" the system gives error

**Expected behavior**
No error

**Steps to reproduce the problem or feature illustration**
Create a questionaire whith some steps and inside to one of them put a question of "Selection box" or "Checbox" type, whit some options specified, save, and then try to duplicate the questionaire.

**GlobaLeaks version:**
3.6.45

**Browser:**
All

**Server Operating System and Version (if applicable):**
Ubuntu LTS 18.04

**Comment by evilaliv3** [comment]
Thank you for reporting tis @obiuan81 

I will investigate the issue in the next week as possible regression of recent versions.

As far that i i know many deployments are using this feature without any issue with very complex questionnaires.

**Comment by evilaliv3** [comment]
@obiuan81: I have just retested the functionality with the upcoming 3.7.0 that i expect to release by tomorrow and i confirm that the import/export/clone of your questionnaire should be be functional.

**Comment by obiuan81** [comment]
Hi @evilaliv3 ,
I've just updated the platform version to the 3.7.1 one and the issue seems to be resolved. 
I'll let you know if it's all ok in the next days

**Comment by evilaliv3** [comment]
Closing as fixed.
