### ISSUE TITLE
Implement detection of mobile users

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2574]
It would be valuable to implement detection of mobile users;

This could be reasonable for two reasons:
- online optimization of the interface depending on the user device;
- social research reasons in relation to the typical whistleblower

**Comment by evilaliv3** [comment]
This is useful feature for projects like: EAT, WhistleblowingPA, and probably all the Publeaks-like projects.

**Comment by fpietrosanti** [comment]
Reference to ticket #2207

**Comment by evilaliv3** [comment]
Implemented.

The feature will be merged in master starting from release 3.9.0
