### ISSUE TITLE
Implement URL redirects

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2575]
For different reasons, many projects had during time the necessity to implements some resources overrides necessary for implementing tweaks and customizations.

As well many multitenant projects are now requiring to be able to provide a different customized client for different tenants.

To accomodate this need i would propose to change the current "Short URL" feature (https://github.com/globaleaks/GlobaLeaks/issues/1527) to be a general redirect feature.
This would enable for example that that an administrator of a tenant could configure the platform to serve a custom client hosted on the tenant.

**Comment by fpietrosanti** [comment]
I’d suggest to “add url redirect” rather than change short url behaviors.

All those web utilities maybe useful in different contexts

Sent from mobile

>

**Comment by evilaliv3** [comment]
I totally agree @fpietrosant and do not worry i never considered removing the short url feature.

The current short feature was forcing to write a url under the path /u/xxx

I'm just extending the feature to make it possible to override the full path of the application.

So basically im remodeling the existing feature, under the more generic name URL redirect and implementing all the features

**Comment by evilaliv3** [comment]
Here is the interface of the current implementation:
![screenshot-127 0 0 1-8082-2019 05 27-16-27-42](https://user-images.githubusercontent.com/217034/58431335-8d4f6900-80ad-11e9-914c-e34140e65c0e.png)

The code will be merged in master with release 3.8.0
