### ISSUE TITLE
Receiver welcome screen customisation 

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2593]
Is there a way to customise the receiver welcome screen? The text can be customised for different languages, however there are also some links. Can one add additional links or modify/hide the existing ones?

**Comment by evilaliv3** [comment]
@Elbill this could be used by uploading a Custom Javascript in the ```Site settings``` section and using the javascript fuction function ```GLClient.mockEngine.addMock```

For you needs you could keep as reference this ticket: https://github.com/globaleaks/GlobaLeaks/issues/2363

You could start from loading the following example:

```javascript
GLClient.mockEngine.addMock('/#/receiver/home', '#RecipientHomepage', function(scope, elem) {
  if (document.getElementById('RecipientHomepageCustomization') === null) {
    elem.innerHTML = '<div id="RecipientHomepageCustomization">Example</div>';
  }
});

**Comment by elbill** [comment]
@evilaliv3   Haven't looked into the more advanced implementations, however the basic info you provided is adequate at the moment. Thanks!
