### ISSUE TITLE
Make it possible for recipients to add a new recipient to their submissions

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2595]
In many projects it is now necessary to make it possible for a recipients to pass their submissions to a new recipient.

This is particularly needed in relation to turnover or when a new user joins the team.

**Comment by evilaliv3** [comment]
Here are the current mockups for the feature:

Button that enables a user to add new users to the submission:
![Screenshot_2021-09-13 GLOBALEAKS - Report(4)](https://user-images.githubusercontent.com/217034/133130193-18690c2f-aa3e-42d3-b217-cf8d596e8373.png)

Search box that enable to search and select users to which grant access:
![Screenshot_2021-09-13 GLOBALEAKS - Report(4)](https://user-images.githubusercontent.com/217034/133130231-3bf0e69b-9f0a-4162-902c-3cf0c09ba5fa.png)

Interface during the selection of the user to which grant access:
![Screenshot_2021-09-13 GLOBALEAKS - Report(6)](https://user-images.githubusercontent.com/217034/133130249-fd6411bf-b86d-437c-813a-9e7172804f69.png)

Interface after granting access to a new user. The interface show a remove icon enabling to revoke access to one user. To prevent errors the interface does not enable users to revoke access to themeselves:
![Screenshot_2021-09-13 GLOBALEAKS - Report(7)](https://user-images.githubusercontent.com/217034/133130408-c0fa8336-ec0b-4e36-965c-781c9ebe0ca5.png)

\cc @larrykind @elbill

**Comment by evilaliv3** [comment]
\cc @larrykind @elbill @maxmois: Do you think this basic interface would work? What are your suggestions? Is there something you would implement differently?

**Comment by schris-dk** [comment]
Hi!
I think this looks fairly simple and good - fully in line with the General "feel" of GL :-) I'd like to suggest the following features along with this (if they aren't already):

1. Full audit logging of this procedure
2. E-mail send to the  added recipeint
3. E-mail to all other recipient/administrators on the new recipient in the case
4. Same points for any removal of a recipient

I have one question - the added user - Is he/she added as general user for the particular context or only for the particular case?

A case specific adding of a user could come in handy. This way a supervisor/legal specialist/case specialist could be involved in one particular case, hence, data will reside in the platform and keep them safe.

/soren

**Comment by larrykind** [comment]
Hi @evilaliv3, 
thank you for sharing, a couple of questions about:

1. when the eneabled recipent choose other recipients, do you plan some sort of logic to choose the recipient? For example: do in the select box will appear every receiver but itself, or for example receivers who don't belong to the same context / not previously selected receivers within the questionnaire?

2. In my opinion there shoud be a confirm message to choose to send the email notification or not (_You are about to grant a receiver to access this report. Do you want to send an email notification to this user?_). Either to give the possibility to the grantee to recover from a wrong receiver selection, or to intentionally choose to not send an email to the receiver.

3. Maybe there should be an email notification to revoke the access with the confirm message at point 2

Thank you for considering it,

**Comment by giorgiofraschini** [comment]
I think the interface is clear and the process to add/remove new recipients works.
I am wondering about a specific circumstance: as I see, the coordinator needs to enable a secondary recipient on each existing report he needs to give access to. would it possible to grant access to all the reports related to a specific context, too?

**Comment by evilaliv3** [comment]
Thank you both @schris-dk, @larrykind and @giorgiofraschini ! Your suggestions are all great!

Here are my evaluations point by point:

@schris-dk:
> Hi!
> I think this looks fairly simple and good - fully in line with the General "feel" of GL :-) I'd like to suggest the following features along with this (if they aren't already):
> 
>     1. Full audit logging of this procedure
I think we should add this right away both for addition and removal of the access. This is a very fundamental need.

> 
>     2. E-mail send to the  added recipeint
This has been implemented and will be included in first release.

> 
>     3. E-mail to all other recipient/administrators on the new recipient in the case
This is interesting. At the moment i've limited the implementation to the basic also to not overload current translation work with so many new texts that will be studied and defined in the future. We have infact an ongoing translation activity and globaleaks will be full translated in probably 70 languages or more in less than a month! :)

> 
>     4. Same points for any removal of a recipient
At the moment only the audit log will be implemented for revocation.

> 
> 
> I have one question - the added user - Is he/she added as general user for the particular context or only for the particular case?

Currently the feature is case by case.

> 
> A case specific adding of a user could come in handy. This way a supervisor/legal specialist/case specialist could be involved in one particular case, hence, data will reside in the platform and keep them safe.
> 
> /soren


@larrykind:

> Hi @evilaliv3,
> thank you for sharing, a couple of questions about:
> 
>     1. when the enabled recipient choose other recipients, do you plan some sort of logic to choose the recipient? For example: do in the select box will appear every receiver but itself, or for example receivers who don't belong to the same context / not previously selected receivers within the questionnaire?

Currently there is no logic implemented. The system will offer to select every enabled user that does currently not have access to the report.

> 
>     2. In my opinion there shoud be a confirm message to choose to send the email notification or not (_You are about to grant a receiver to access this report. Do you want to send an email notification to this user?_). Either to give the possibility to the grantee to recover from a wrong receiver selection, or to intentionally choose to not send an email to the receiver.
> 
This is interesting but would require more analysis and to study well the interface and the texts so that i consider we should postpone this if we agree that the priority is to have a fully functional basic implementation. do you all agree on this?

>     3. Maybe there should be an email notification to revoke the access with the confirm message at point 2
Same considerations.
> 
> 
> Thank you for considering it,
You are welcome! thank you for your feedback!


> I think the interface is clear and the process to add/remove new recipients works.
> I am wondering about a specific circumstance: as I see, the coordinator needs to enable a secondary recipient on each existing report he needs to give access to. would it possible to grant access to all the reports related to a specific context, too?

At the moment i consider a priority to have this simple feature that will work case by case. 
As next step among all your suggestion i consider that we could have an option to offer a user the possibility to grant an other users access to ALL or SELECTED reports. This would enable to:
- transfer all tips
- transfer a particular selection of tips based on the search / context

I consider that this would be fair simple and i will try to implement this already. I will be back shortly with a mockup for this.

**Comment by larrykind** [comment]
@evilaliv3 just a clarification, 
what do you mean with _"transfer"_ :
> - transfer all tips
> - transfer a particular selection of tips based on the search / context

once access is granted will the grantee have yet access to the report or not?

**Comment by evilaliv3** [comment]
Thank you for the question @larrykind ; Actually i used the wrong term and i currently intend to say grant.

**Comment by evilaliv3** [comment]
I've currently reworked all the interfaces following the suggestions of you all and i came to this solution. 

Please let me know you feedback.

1) I implemented a dedicated modal for granting access to one report from the report page; The modal is now open from a button that you see on top of the tip page. This way the user will have to select a user and then confirm, reducing possible mistakes.
This same feature has been extended to the page that lists all the report so that it will be now possible to grant access to a selection or all the reports at once

![Screenshot_2021-09-14 GLOBALEAKS - Reports](https://user-images.githubusercontent.com/217034/133248407-181e1499-3880-492e-8a3c-ddf25dea45cd.png)

![Screenshot_2021-09-14 GLOBALEAKS - Reports(3)](https://user-images.githubusercontent.com/217034/133248462-576b6299-2a7b-4c59-8e19-f363966805c6.png)

![Screenshot_2021-09-14 GLOBALEAKS - Reports(2)](https://user-images.githubusercontent.com/217034/133248482-2e9ace06-760e-4850-b720-ae5257583c80.png)

2) I implemented a dedicated modal for revoking permissions that ask for confirmation before revoking the access and this would probably reduce possibilities of mistakes. 

![Screenshot_2021-09-14 GLOBALEAKS - Report(9)](https://user-images.githubusercontent.com/217034/133249776-41ddcb21-a181-4104-a480-b75d261ae6dc.png)

**Comment by evilaliv3** [comment]
I've extended the feature to make it possible to revoke access on multiple reports at once directly from the page that lists the reports.

To do this i've considered useful to add a dedicated button for the removal, with popover texts "Revoke access". 

After clicking the button the system will open a modal to ask to the user which is the recipient to which revoke the access.

![Screenshot_2021-09-17 Slack Giorgio Fraschini GLOBALEAKS](https://user-images.githubusercontent.com/217034/133782259-e64f24e0-568e-4e54-aade-7962c29c44c6.png)

![Screenshot_2021-09-17 GLOBALEAKS - Reports(1)](https://user-images.githubusercontent.com/217034/133782293-f3a8f080-b6d9-42e6-a829-96fb464f2030.png)

![Screenshot_2021-09-17 GLOBALEAKS - Reports(2)](https://user-images.githubusercontent.com/217034/133782277-403abe62-4b9e-41a6-ba40-d4889a2cd98d.png)

**Comment by larrykind** [comment]
@evilaliv3 Maybe should also be useful to have in the reports list page, a new column that tells the receiver which reports are shared with other receivers, because it seems that this is not shown in the report list.

In my opinion by selecting more reports it's not easy to recover which receivers the ticket is shared with. If the selected tickets are shared with different administrators, I think this popup should primarily list the union of all administators involved in the selected reports, if possible with a reference to the managed ticket.

As alternative to the last point - in every ticket of the grid, there should be the name list of its managers with the revoke icon aside to them to clearly revoke the access, an then the simple "are you sure?" modal to confirm the revoke.

**Comment by elbill** [comment]
@evilaliv3 and everybody sorry for my late feedback. Everything looks great so far. I agree with @larrykind that it should be in some way eveident in the reports lits which are shared and which are not.
It would also be a good idea the recepient to know the owner that initiated teh sharing of the report (it would be nice to have but not essential)
@larrykind second remark sounds a bit complicated, if I understand well.
The way it is implemented is that by revoking access for one person in multiple reports, the acces will be revoked if it exists in the first place. This is fine with me and makes sense.

**Comment by larrykind** [comment]
@elbill ok so if I well understood this is kind of "blind" selection: if the selected receiver is a sharer for the selected reports it will be disallowed froim access the reports. If it's not, no action will be done. Right?

**Comment by evilaliv3** [comment]
Thank you @larrykind and @elbill 

I confirm that the intepretation of @elbill is what i've actually implemented.

At the moment if users will need to check who has already access they will need to open the submission.

For the outside they will be able to "blindly" grant or revoke access:
- access will be granted only if the recipient does not have access
- revocation will be performed only if the recipient does not have already access.

Please let me know if you consider that this implementation would suffer of major issues.

**Comment by elbill** [comment]
@larrykind ideed.
I believe this is fine. 
Even if a user does not comprehend the logic 100%, no harm will be done.

**Comment by evilaliv3** [comment]
Closing this as implemented and part of the current release 4.3.3
