### ISSUE TITLE
The installation guide link on the website need to be updated

### ISSUE THREAD

**Issue by andrewhh** [globaleaks/GlobaLeaks#2596]
**Current behavior**

**Expected behavior**

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

**Browser:**

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
@andrewhh: where have you found this link?

The correct link is: https://globaleaks.readthedocs.io/en/latest/setup/InstallationGuide.html

**Comment by andrewhh** [comment]
Hello, it's on the front page where it says "Fight corruption and advocate
..." with a button that says "Installation guide" (Bottom right button on
the screen shot I sent).

It redirects to the link I sent.  Thanks for the correct link!

Andrew
[image: image.png]

**Comment by evilaliv3** [comment]
Thank you @andrewhh, link corrected!
