### ISSUE TITLE
Problem to installation script

### ISSUE THREAD

**Issue by zazzati** [globaleaks/GlobaLeaks#2605]
**Current behavior**

Installation script not working

Checking preliminary packaging GlobaLeaks requirements
 + apt-key requirement met
 + apt-get requirement met
 + gpg requirement met
Detected OS: Ubuntu - bionic
Running: "apt-get -y update"... FAIL
Ouch! The installation failed.
COMBINED STDOUT/STDERR OUTPUT OF FAILED COMMAND:
Ign:1 http://deb.globaleaks.org bionic/ InRelease
Get:2 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Get:3 http://deb.globaleaks.org bionic/ Release [1506 B]
Get:4 http://deb.globaleaks.org bionic/ Release.gpg [566 B]
Ign:4 http://deb.globaleaks.org bionic/ Release.gpg
Hit:5 http://nova.clouds.archive.ubuntu.com/ubuntu bionic InRelease
Get:6 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:7 http://nova.clouds.archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Reading package lists...
W: GPG error: http://deb.globaleaks.org bionic/ Release: The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
**E: The repository 'http://deb.globaleaks.org bionic/ Release' is not signed**
For Professional Support requests please visit: https://www.globaleaks.org/contact/

**Expected behavior**
The installer complete installation

**Steps to reproduce the problem or feature illustration**

```shell
wget https://deb.globaleaks.org/install-globaleaks.sh
chmod +x install-globaleaks.sh
./install-globaleaks.sh
```

**GlobaLeaks version:**
latest

**Server Operating System and Version (if applicable):**
Ubuntu Bionic Ubuntu 18.04.2 LTS

**Comment by evilaliv3** [comment]
Thank you for reporting this @zazzati 
It seems that we forgot to sign the repository on latest release.

would you please retry now?

**Comment by zazzati** [comment]
@evilaliv3 

Now the installer is working. 
Thx.
