### ISSUE TITLE
Problem with mail and account receiver

### ISSUE THREAD

**Issue by annibale93** [globaleaks/GlobaLeaks#2606]
**Current behavior**
Hi i have 3 problems with Globaleaks. When i insert smtp parameters of my mail server aruba i receive the error "Timeout waiting for smtp server response". I try more configurations but all of they don't work.
The second problem is that when i set the password of receiver account if i want to access in the login page i receive the error "Invalid credential" and i can't access to visualize the reports.
Finally, when i am an user and i create the report i visualize the code and the page but if i access in the admin page or the account of receiver i don't visualize the report that the user have created.
How can i resolve these 3 problems?

I use the version of software: 3.9.7
O.S.: ubuntu bionic

**Expected behavior**

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

**Browser:**

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
Thank you @annibale93 for reporting this.

Please try when opening tickets to split every issue in a separate ticket.

1) SMTP configuration issue: i suggest you to reckeck that the port and the protocols are correctly set and verify to not have configured "Anonymize outgoing connections" in the Network Settings/Tor settings. This in fact may be one of the reasons of your failures and probably for your setup you could avoid this. Which is the host of your smtp? is it a local ip address? if yes for sure the "Anonymize outgoing connections" option may be the reason of your failure; that option makes globaleaks connect to the smtp server via Tor.

2) As for the other topics if possible could you share a link to the testing platform? i would like to try to make a submissions and enter myself to get proper understanding. is it a fresh / default setup?

**Comment by annibale93** [comment]
Hi thanks for the answer. For the configuration of the mail i use the parameters of aruba: smtps.aruba.it with port 465 with authentication and for security smtp/tls.
I haven't select anonymize outgoing connection in network settings/tor.
I have the server in local. I use an ubuntu machine on vmware and it is only in local for the moment.
I use all the setting default. I modify only the image and the text on the homescreen

**Comment by evilaliv3** [comment]
Dear @annibale93, do you have any update from your side with the debugging of this issue?

thank you!

**Comment by evilaliv3** [comment]
Closing as probably fixed.
