### ISSUE TITLE
"Title of the receipt page" not coresponding to entered string

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2610]
Minor bug.
In the advances settings the custom "title of the receipt page" entered does not correspond to actual, neither in english nor in any other language. "Your submission was successful!" always appears.

Latest version of globaleaks on Ubuntu 18.04LTS, chrome client on windows 10

**Comment by evilaliv3** [comment]
Bug confirmed @elbill , probably the feature was not complete.

Going to fix this and include it into the next release.
