### ISSUE TITLE
Force reset password doesn't work

### ISSUE THREAD

**Issue by davelip** [globaleaks/GlobaLeaks#2611]
**Current behavior**
With the administrator user on the user detail I check "Force password change" ("Forza il cambiamento della password")

![image](https://user-images.githubusercontent.com/946249/60607472-9e327f00-9dbd-11e9-8709-912080727618.png)

When the user login the site doesn't ask him to change the password.

**Expected behavior**
At the first user login i expect that the system force to change the password. 

**Steps to reproduce the problem or feature illustration**
- Login with administrator user;
- Check the checkbox "force password change" on an user userA, save;
- Login with userA;

**GlobaLeaks version:**
3.9.8 (also 3.9.7)

**Browser:**
Chrome 70
Firefox

**Server Operating System and Version (if applicable):**
Ubuntu 18.04

**Client Operating System and Version (if applicable):**
Ubuntu 19.04
Windows 10

**Comment by evilaliv3** [comment]
Thank you @davelip for reporting this. I will try to replicate the issue and get back to you.

**Comment by evilaliv3** [comment]
Bug confirmed. it is a regression added in commit: https://github.com/globaleaks/GlobaLeaks/commit/fe583e33b4

**Comment by evilaliv3** [comment]
Fixed. The patch will be released starting from verion 3.9.10
