### ISSUE TITLE
Password reset link with invalid token

### ISSUE THREAD

**Issue by davelip** [globaleaks/GlobaLeaks#2613]
**Current behavior**
The link received by user after a "Reset password" by administrator are invalid.

When the user click on the link receive a "Invalid or expired token"

![image](https://user-images.githubusercontent.com/946249/60609061-19e1fb00-9dc1-11e9-8df9-e95557efee35.png)

**Expected behavior**
Got a valid reset password link.

**Steps to reproduce the problem or feature illustration**
- Login with administrator user;
- Use "Reset password" button on user userA detail page;
- Click on the link in the received mail (by userA)

**GlobaLeaks version:**
3.9.8

**Browser:**
Chrome 70
Firefox

**Server Operating System and Version (if applicable):**
Ubuntu 18.04

**Client Operating System and Version (if applicable):**
Ubuntu 19.04
Windows 10

**Comment by evilaliv3** [comment]
Thank you @davelip for reporting this. I will try to replicate the issue and get back to you.

**Comment by evilaliv3** [comment]
Bug confirmed. This regression has been introduced in commit: https://github.com/globaleaks/GlobaLeaks/commit/5cb1ae3c33

**Comment by evilaliv3** [comment]
Fixed. The patch will be included starting fro mrelease 3.9.10
