### ISSUE TITLE
Change password with an already used one  

### ISSUE THREAD

**Issue by davelip** [globaleaks/GlobaLeaks#2614]
**Expected behavior**
After the expiration period the user should change his password.

The system ask him to change after login.

The user can submit the same password (also the expired one).

In the user profile view (password tab) the behavior is correct:

![image](https://user-images.githubusercontent.com/946249/60609559-3e8aa280-9dc2-11e9-82b7-d0fa32ca93cc.png)

**Steps to reproduce the problem or feature illustration**
- Set the expiration password time to 1 day;
- The day after login
- In the change password view insert the current one;
- The system accept that.

**GlobaLeaks version:**
3.9.8 (also 3.9.7)

**Browser:**
Chrome 70
Firefox

**Server Operating System and Version (if applicable):**
Ubuntu 18.04

**Client Operating System and Version (if applicable):**
Ubuntu 19.04
Windows 10

**Comment by evilaliv3** [comment]
Thank you @davelip 

This is a known point of improvement.

During the enforced password change we are currently not asking for the old password and this is what prevents on the client to be able to check if the user is choosing the same password.

I think that to solve this, we could probably pass the old password hash in the session of a logged user so to be able to compare that clientside. 

What do you think @fpietrosanti ?

**Comment by fpietrosanti** [comment]
> Thank you @davelip
> 
> This is a known point of improvement.
> 
> During the enforced password change we are currently not asking for the old password and this is what prevents on the client to be able to check if the user is choosing the same password.
> 
> I think that to solve this, we could probably pass the old password hash in the session of a logged user so to be able to compare that clientside.
> 
> What do you think @fpietrosanti ?

Make sense.
Just ensure to add this new security feature to the one of the Application Security Document while implemented

**Comment by davelip** [comment]
Why not save the last 5 (configurable) password hash and check that at password change?

**Comment by evilaliv3** [comment]
Thank you @davelip for the feedback.

For the moment we have implemented the following:
- The password change verify that the new password has is not equal to the previous one.
- The error message is more generic informing the user that the system do not accept reused password.

The following is a screenshot of the current implementation:
![screenshot-127 0 0 1_8082-2019 09 27-08_40_12](https://user-images.githubusercontent.com/217034/65747737-7758c000-e102-11e9-9122-9db8e1659f50.png)
