### ISSUE TITLE
Link for upgrade instructions in email is wrong

### ISSUE THREAD

**Issue by andrewhh** [globaleaks/GlobaLeaks#2615]
![Screen Shot 2019-07-03 at 2 22 10 PM](https://user-images.githubusercontent.com/636650/60619374-2b65db80-9d9e-11e9-9bed-9bc0b7f875f8.png)

Clicking the link redirects to:
https://globaleaks.readthedocs.io/en/latest/UpgradeGuide.html

Which shows the Sorry this page does not exist yet ASCII hallway.

**Current behavior**

**Expected behavior**

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

**Browser:**

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
Thank you @andrewhh for noticing and reporting this.

This is due to the recent update of the documentation that caused the link to change.

I've now fixed and it now correctly points to: https://globaleaks.readthedocs.io/en/latest/user/admin/UpgradeGuide.html
