### ISSUE TITLE
412 precondition failed error while logging in as admin from a root tentant to a secondary tenant

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2618]
**Current behavior**
When logging in as admin from a root tentant to a secondary tenant, clicking the button "Configure" from "Sites Management" under the Sites section, the interface trigger a 412 precondition failed error . 

The login to the secondary tenant works, but while doing a redirect, this error message is displayed.

**Expected behavior**
The error message should not be present.

**Comment by evilaliv3** [comment]
This has been already fixed in latest release.

**Comment by evilaliv3** [comment]
Removing as well the EAT label as the bug is general.
