### ISSUE TITLE
EAT Configuration profile should create tenant that include customized footer

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2619]
**Current behavior**
Actually, when a new platform is create under the multi-tenant EAT project, the footer itself isn't inheriting the footer configured on the toot tenant.

**Expected behavior**
The footer under the EAT profile should inherit the root tenant one.

**Comment by evilaliv3** [comment]
@fpietrosanti: this should be already the behaviour. Is there a regression?

https://github.com/globaleaks/GlobaLeaks/blob/master/backend/globaleaks/handlers/public.py#L151

It is planned that in EAT mode the footer is always configured and inherited from the root tenant.

**Comment by fpietrosanti** [comment]
@evilaliv3 after some digging we found out that's available only in english, while it should be available multi-language. IE: Model-B sample tenant https://modelb.disclosers.eu
On root tenant's admin those has been configured at the time, but now are not visibile/configurable anymore

**Comment by evilaliv3** [comment]
@fpietrosanti the footer variable actually is s a multilanguage variable actually.

It is up to you to configure it in multiple language.

Currently it seems to me it has been configured only in English , but I cannot confirm any regression here

**Comment by fpietrosanti** [comment]
@evilaliv3 it has been configured in multiple languages some versions ago, but now the settings to configure it is not available anymore for proper language maintenance , maybe it' a misalignment when the EAT profile has been implemented

**Comment by fpietrosanti** [comment]
This has been done and is confirmed to be working, only missing the EU logo at #2622
