### ISSUE TITLE
EAT should include a JS customised footer with EU flag that should be available across all tenant

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2622]
**Current behavior**
In the EAT platform the footer should contain the EC Logo as a requirement and this graphical customisation should be made available across all secondary tenants.

The configuration approach and how to should be documented in the Graphical section of the Setup HowTo
https://docs.google.com/document/d/1rbEEVgMHh-kBxA8WOYVJ4t_VudENM6PSCx6HEvemFaE/edit#heading=h.meg6nlvma4ij

**Comment by fpietrosanti** [comment]
Sample Code from WBPA to achieve that goal:

GLClient.mockEngine.addMock('*', '#FooterBox', function(scope, elem) {
  if (document.getElementById('FooterBoxCustomization') === null) {
    elem.innerHTML = '<div id="FooterBoxCustomization">' +
                     '  <div><a href="https://www.whistleblowing.it">WhistleblowingPA</a> è un progetto di <a href="https://www.transparency.it">Transparency International Italia</a> e del <a href="https://www.hermescenter.org">Centro Hermes per la Trasparenza e i Diritti Umani e Digitali</a></div>' +
                     '  <br />' +
                     '  <div>' +
                     '    <img src="https://registrazione.whistleblowing.it/s/logo1.png" />' +
                     '    <img src="https://registrazione.whistleblowing.it/s/logo2.png" />' +
                     '  </div>' +
		     '  <br />' +
		     '  <div>Powered by <a href="https://www.globaleaks.org">GlobaLeaks</a></div>' +
                     '</div>';
  }
});

**Comment by evilaliv3** [comment]
@fpietrosanti : actually already if you configure the JavaScript I passed you and that to you reported in the previous comment it is already doable all that you are asking in the ticket.

What is this ticket for exactly?

**Comment by fpietrosanti** [comment]
@evilaliv3 to do it and test the adjustment result of the the visualization and testing, here we lack the proper technical knowledge to do it properly, because the localized text are configured in the database, but if we overwrite the entire footer like in WBPA, i expect that those localization will be lost.

So as far as we technically understood actually we would need to do a JS customization different from WBPA, that place the EU logo only without overwriting the entire footer. 

Is that interpretation correct?

**Comment by fpietrosanti** [comment]
EU official logo http://publications.europa.eu/code/en/en-5000200.htm

**Comment by evilaliv3** [comment]
Exactly if you override in JavaScript you need to take care of implementing all the if/else logic for the language in JavaScript. I would anyhow not recommend to implement a multi language footer for branding reasons but up to you the choice and possibilities.

**Comment by fpietrosanti** [comment]
Related #2626

**Comment by fpietrosanti** [comment]
@evilaliv3 the footer language should be the one of the platform, the text has been already translated and localised in globaleaks configuration (e.g. A Romanian public agency would complain to use an entirely romanian language platform with the footer in english language). 
But how to do it without overwriting the entire footer?

**Comment by fpietrosanti** [comment]
Maybe there's a variable available/accessible from the JS that contain the configured footer text in the current language that can be printed out in making a custom JS for that purpose in a multi-language footer scenario?

**Comment by evilaliv3** [comment]
Yep, the variable you are looking for is accessible via ```GLClient.language```

It could be used like:

```javascript

var footerText = '';
if (GLClient.language === 'it') {
  footerText = '<div>Ecco qua il Mock!</div>';
} else {
  footerText = '<div>Here comes the Mock!</div>';
}

**Comment by fpietrosanti** [comment]
"22.1.2 Information on EU funding — Obligation and right to use the EU emblem

Unless the Commission requests or agrees otherwise, any communication activity related to the action

(including at conferences, seminars, in information material, such as brochures, leaflets, posters,

presentations, etc., in electronic form, via social media, etc.) and any infrastructure, equipment or

major result funded by the grant must:

- display the EU emblem and

- include the following text:

“This [insert appropriate description, e.g. report, publication, conference, infrastructure, equipment, insert

type of result, etc.] was funded by the European Union’s Internal Security Fund — Police.”

When displayed in association with another logo, the EU emblem must have appropriate prominence.

For the purposes of their obligations under this Article, the beneficiaries may use the EU emblem

without first obtaining approval from the Commission.

This does not, however, give them the right to exclusive use.

Moreover, they may not appropriate the EU emblem or any similar trademark or logo, either by

registration or by any other means.

22.1.3 Disclaimer excluding Commission responsibility

Any communication activity related to the action must indicate the following disclaimer:

“The content of this [insert appropriate description, e.g. report, publication, conference, etc.] represents the

views of the author only and is his/her sole responsibility. The European Commission does not accept any

responsibility for use that may be made of the information it contains.”"

**Comment by evilaliv3** [comment]
Closing as outdated and already implemented within the EAT project as a customization using the JS Mock functionalities
