### ISSUE TITLE
On EAT tenant the recipient user can't self-configure it's Ricochet address

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2623]
**Current behavior**
While testing EAT project tenant setup with feature #2513 we found out that it's not possible for the recipient to self-configure it's ricochet address.

Otherwise when a recipient generate it's ricochet address, would need to ask to the technical maintainer to login as admin to configure it.

**Expected behavior**
As per #2513 the recipient need to be able to configure it's ricochet address from preference panel

**Comment by evilaliv3** [comment]
This is currently doable but probably a regression exists.

**Comment by evilaliv3** [comment]
@fpietrosanti: check better!

![screenshot-platform disclosers eu-2019 07 07-18-25-30](https://user-images.githubusercontent.com/217034/60771206-a273da80-a0e4-11e9-8446-1758b770b66f.png)

i see definitely no issue on this.

**Comment by fpietrosanti** [comment]
💙
