### ISSUE TITLE
EAT disclaimer is not configurable from the root tenant

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2625]
**Current behavior**
The disclaimer of EAT is not configurable from the root tenant from proper translation language management cycle:
<img width="754" alt="Screen Shot 2019-07-07 at 13 07 09" src="https://user-images.githubusercontent.com/770363/60768346-857adf80-a0c3-11e9-88c8-ed4b7490b72f.png">

The settings can be enabled/disabled but the corresponding text can't be visualised/modified

**Expected behavior**
The disclaimer text should be configurable from within the root tenant

**Comment by evilaliv3** [comment]
@fpietrosanti: fixed and updated in production!
