### ISSUE TITLE
"Files" upload under site settings does not work

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2626]
**Current behavior**
Uploading a file (http://publications.europa.eu/code/images/scan/5000200-flag-cl.jpg) from Site Settings -> Files -> Upload, the UX does nothing (should ask which file to upload):
<img width="1203" alt="Screen Shot 2019-07-07 at 14 47 37" src="https://user-images.githubusercontent.com/770363/60768651-a55fd280-a0c6-11e9-9656-73eb4d0ff65b.png">

From debugging with Chrome Developer Console it shows that trigger this error when clicking upload:
<img width="1911" alt="Screen Shot 2019-07-07 at 14 47 26" src="https://user-images.githubusercontent.com/770363/60768657-b4468500-a0c6-11e9-91b1-c51675e7c555.png">

**Comment by evilaliv3** [comment]
@fpietrosanti : I just updated your setup to the latest release, would you please check if this issue is solved?

P.s.: Sometimes, since always the button requires multiple clicks to work but this is an other story

**Comment by evilaliv3** [comment]
Removing the EAT label as the bug is eventually general

**Comment by fpietrosanti** [comment]
@evilaliv3 After the upgrade, the button started the file upload dialog, but once a file has been selected it trigger this in the JS console:
![5000200-flag-cl](https://user-images.githubusercontent.com/770363/60768779-28355d00-a0c8-11e9-95dc-ea71b27f2783.jpg)

p.s. Let's keep the EAT tag as we'll use it later on for EU reporting for any corrective or evolutive maintenance stuff

**Comment by evilaliv3** [comment]
@fpietrosanti: fixed!
