### ISSUE TITLE
After upgrade of GlobaLeaks to 3.9.11 on EAT platform the signup doesn't show up anymore

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2627]
**Current behavior**
After upgrade of GlobaLeaks to 3.9.11 on EAT platform the signup doesn't show up anymore, but it does redirect to admin interface instead.

The signup should be available on http://platform.disclosers.eu with absolute URL of http://platform.disclosers.eu/#/signup .

The signup is activated under site settings of the root tenant:
<img width="708" alt="Screen Shot 2019-07-07 at 15 21 17" src="https://user-images.githubusercontent.com/770363/60769013-36d14380-a0cb-11e9-95be-9c96895fd101.png">

**Expected behavior**
The signup should be available when enabled

**Comment by evilaliv3** [comment]
Dear @fpietrosanti, as you are reporting you have enabled the option "Use the first site for administrative purposes only and thus the signup has been disabled.

**Comment by evilaliv3** [comment]
@fpietrosanti: For clearness i'm going to not show anymore the other options when you select that option so that it will be more clear the effect of that option.

**Comment by evilaliv3** [comment]
![screenshot-127 0 0 1-8082-2019 07 07-18-46-50](https://user-images.githubusercontent.com/217034/60771382-b5d47500-a0e7-11e9-8f9b-d838cac8cabf.png)

Done!
