### ISSUE TITLE
 Make it possible to bind contexts to a set of languages

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2628]
**Current behavior**
In Whistleblowing Initiatives that span with many multiple languages, such as the EAT project in 9 languages, it could be useful to display a specific context on the submission interface, only if the whistleblower language is one of the languages "enabled for that context" .

For example for Model-C of EAT (documented here https://docs.google.com/document/d/1rbEEVgMHh-kBxA8WOYVJ4t_VudENM6PSCx6HEvemFaE/edit#heading=h.gjukybk6d8ag), there will be 9 contexts and each of them will be representing a specific country/language pair, delivering submissions to a number of receivers (investigative media partners) that are specific of that language.

Actually when a Whistleblower approach the submission interface of model-C platform, will be presented the full list of context, regardless of his language, but if the whistleblower is using a Spanish speaking browser or selected Spanish language, it doesn't make much sense to show also the Hungarian context.

Additionally, the context configuration in such a situation need to be localised in all 9 languages (9 context in 9 languages) with a set of unusefull string (for example, translating in Hungarian "Report here submission on Spain").

So the feature would be to enable a new Context configuration setting:
"Show context only in the following language: Click/Uncheck" that if checked, let specify the configured language from the enabled one.

When configured those context would be visible only on the languages for which they have been enabled.

It would be a nice to have general feature to improve those kind of configuration requiring better UX for Whistleblower and reduced localisation effort/cost.

**Comment by evilaliv3** [comment]
Implemented and will be included in the next viable release.

Languages are now configurable via a filter where one could write a comma separated list of languages.
An empty list (the default) would mean that the context is valid for each language.

![Screenshot_2020-01-30 Contexts](https://user-images.githubusercontent.com/217034/73473602-542e6d80-438d-11ea-99bd-a7049b1ab4fe.png)
