### ISSUE TITLE
"Reset notification templates to default" does nothing

### ISSUE THREAD

**Issue by qertoip** [globaleaks/GlobaLeaks#2629]
**Current behavior**
"Reset notification templates to default" ticked and saved has no result. The templates remain as they were.

**Expected behavior**
Notification templates to be reset to appdata.json source.

Currently the appdata.json modifications are only effective for new sites within the instance. There should be a way to apply it to existing sites.

**Steps to reproduce the problem or feature illustration**
1) Modify appdata.json
2) Restart the web server
3) Tick "reset notification templates to default" checkbox and save settings
4) Force any notifcation

**GlobaLeaks version:**
3.9.11

**Browser:**
Firefox 67.0.4

**Comment by evilaliv3** [comment]
Regression fixed! The patch will be included starting from release 3.9.12.

Thank you for reporting this @qertoip
