### ISSUE TITLE
Password reset link has always the first-domain in a multi-site setup

### ISSUE THREAD

**Issue by qertoip** [globaleaks/GlobaLeaks#2630]
**Current behavior**
In a multi-site setup when nth-site admin requests password reset on behalf of the user, the mail template has a confirmation link with the domain related to the first site, instead of the domain for which password reset has been requested.

**Expected behavior**
Password reset to work correctly in a multi-site setup.

**Steps to reproduce the problem or feature illustration**
If simple reproduction won't do it then try with the same email across multiple sites. Like, the same natural person is a recipient on more than one site.

**GlobaLeaks version:**
3.9.11

**Comment by evilaliv3** [comment]
Thank you for reporting this @qertoip, it seems that this bug was there since the first implementation of the password reset functionality.

The issue should be now fixed and the patch will be included starting from release 3.9.12
