### ISSUE TITLE
Support for PROXY protocol

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#2636]
Hi

We've been considering using GlobaLeaks by intentionally putting it behind a reverse proxy to increase security by network segmentation, and generally to gain more control

And, as it is, it works fine except that Globaleaks doesn't get clients real IP which is needed for  IP filtering. And possibly there are other issues, as all the traffic comming from one IP could trigger some other built in limitations.

I'm wondering if it is possible to implement support for PROXY protocol to support this use case, where lets say an admin could opt in by setting a flag inside /etc/defaults/globaleaks

Twisted supports it and I guess it's trivial to implement:
https://twistedmatrix.com/documents/current/api/twisted.protocols.haproxy.html
https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt

**Comment by evilaliv3** [comment]
Hello @aetdr,

Actually there is no particular support needed from twisted to implement this but it would be definitely trivial to read the IP from X-Forward-For header.

As for your use case please keep into consideration to configure your proxy server to discard any log and to act fully in streaming.

A logging proxy or a proxy implementing local caches or temporary files could seriously harm the security of globaleaks  and this is why proxies are generally not implemented.

**Comment by aetdr** [comment]
Hi @evilaliv3 

The issue is that we can't add HTTP headers without decrypting/encrypting traffic and working at layer 7.
Support for PROXY protocol allows working with TCP, transport layer only, and since it's supported by twisted it feels like the only right solution.

The PROXY protocol is invented by people behind HAProxy but is supported by all major reverse proxies, it's kind of misleading that twisted refer to it as HAProxy protocol.

We are very aware of how wrong implementation can do damage, that shouldn't be a problem, thanks.

**Comment by evilaliv3** [comment]
I see, thank you @aetdr 

Are you able to make a patch and provide a pull request?

**Comment by aetdr** [comment]
Unfortunately I'm not able to make a patch.
If you guys can do it, it's also important to define and check if a proxy traffic is coming from is trusted, something like:

proxy_enable = True
proxy_trusted_ips = 1.2.3.4, 1.2.3.5

**Comment by evilaliv3** [comment]
Closed.

See reason: https://github.com/globaleaks/GlobaLeaks/issues/2736#issuecomment-861457634
