### ISSUE TITLE
Improve admin interface to notify administrator the contexts that miss configured users

### ISSUE THREAD

**Issue by CarloSolari** [globaleaks/GlobaLeaks#2642]
This ticket is to discuss the possibility of improvements for the admin interface to notify administrator the contexts that miss configured users.

Was previously reported as "Submit button doesn't work after upgrade to 3.9.12"

**Current behavior**
Submit button doesn't work. When I click on it, nothings happening.

**Expected behavior**
Expect the site to move on to the reciept page, stating the submission has been sent in.

**Steps to reproduce the problem or feature illustration**
- update GL from 3.9.11 to 3.9.12
- test the sending procedure, filling the mandatory fields. When I click the Submit button, doesn't happen.

Attempts performed to resolve by myself
- reboot VM, nothing happens.
- run the complete GL install script, following this: Thttps://docs.globaleaks.org/en/latest/user/admin/UpgradeGuide.html , nothing happens
- clean re-installation of VM and GL, nothing happens.
- change DNS record in my provider management panel (from "whistleblowing.my-company.org" to "segnalazioni.my-company.org"), nothing happens.
- change the VM IP and name, nothing happens.
- check my company firewall policies, nothing changed in the last months.

Notes:
- when the VM rebooting, the following message appears during shutdown: "a stop job is running for lsb start the globaleaks server (XXs / 5min)"; after 30 seconds or so, the reboot procedure continues and the VM is rebooted.
- when VM rebooting, the following message appears during power up: "failed to start postfix mail transport agent".

**What is the motivation or use case for changing the behavior?**
Whistleblowers must submit their reports.

**GlobaLeaks version:**
3.9.12

**Browser:**
Chrome, Firefox

**Server Operating System and Version (if applicable):**
Ubuntu 18.04.2 bionic

**Client Operating System and Version (if applicable):**
Windows 10
-->

**Comment by evilaliv3** [comment]
Thank you @CarloSolari 

Actually the release 3.9.12 do not include any modification possibly related to your issue and probably the reason of your failure is to be searched in something else.

Would you please share a link to the platform so that I can check it or share a copy of the /public research to recheck the public part of the configuration?

**Comment by CarloSolari** [comment]
Hi,
this is the link to my site's whistleblowing section: https://whistleblowing.antas.org

Regarding the "copy of the /public research": sorry, but I have no idea how to do it.
I'm a beginner with Linux.

Available for any clarification, bye.
Carlo

**Comment by evilaliv3** [comment]
Thank you @CarloSolari,

this is more than enough.

The public configuration is accessible here: https://whistleblowing.antas.org/public

i've identified the issue and actually it is not related to the new version; uour submission context is missing any recipient.

From the admin interface select your context and attach to it at least one recipient.

This is visible also in the first submission tab if you click submit and open it.

![screenshot-whistleblowing antas org-2019 07 18-14-18-52](https://user-images.githubusercontent.com/217034/61456810-4b34fc00-a967-11e9-9482-16e3f6cc8fe3.png)

**Comment by CarloSolari** [comment]
My God, I'm a complete dumb!  :-(
You're right, the problem was here. I was searching almost in any sub-menu of the admin interface but I missed the right one.
But, in my defense, I swear to you that the recipient was set, before the last GL update.
Anyway, thanks again for your support.
I think that I can close this issue.  :-)

Carlo

**Comment by evilaliv3** [comment]
No worry @CarloSolari! you are more than welcome.

Actually it is really strange that the recipient lost its connection to the context.

Is it possible that recently you created and now you are using that?

**Comment by CarloSolari** [comment]
I don't know.
Maybe, within the many tests I tried to resolve the issue, I could modify account name and/or mail address, and in that moment the link context-user broke.
Anyway, now It all works fine.

Carlo
