### ISSUE TITLE
Enable a specific recipient on a specific context to be selected by default and unselectable

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2644]
**Current behavior**
Actually in the Whistleblower selection configuration on the context is possible to:
- Enable Recipient Select
  "Allow whistleblowers to select their recipients"

- Decide whenever Recipient are by default selected or un-selected by default
  "Select all recipients by default" 

However it doesn't seems to be possible to have a specific recipient to be selected by default, and un-selectable (be always a recipient for that context).

For Model-B variant of EAT (there will be 3 variant) https://modelb.disclosers.eu it would be needed to have Beneficiary (recipient 1) to always receive report, while the Partner (recipient 2), to be optionally selectable.

Does it require an additional feature or can be done with actual feature?

**Comment by fpietrosanti** [comment]
Fixed, it's a configuration to be done under:
Users -> User -> Configuration -> Forcefully selected

**Comment by evilaliv3** [comment]
Additional improvement would be to move the configuration from the user configuration to the configuration of the user-context association.
