### ISSUE TITLE
Cannot read property 'score_threshold_medium' of undefined

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2645]
Platform: WhistleBlowingAdmin
Host: xxxxx.it 
Version: 3.9.8

URL: /status/76819c2c-3435-47e3-89a4-fe7401a6bfc1

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

Error Message: TypeError: Cannot read property 'score_threshold_medium' of undefined

Stacktrace:
[
  {
    "source": "    at Object.calculateScore (https://xxxxx.it/t/2/js/scripts.js:11307:43)", 
    "columnNumber": 43, 
    "fileName": "https://xxxxx.it/t/2/js/scripts.js", 
    "functionName": "Object.calculateScore", 
    "lineNumber": 11307
  }, 
  {
    "columnNumber": 22, 
    "fileName": "https://xxxxx.it/t/2/js/scripts.js", 
    "source": "    at https://xxxxx.it/t/2/js/scripts.js:11343:22", 
    "lineNumber": 11343
  }, 
  {
    "source": "    at Object.r [as forEach] (https://xxxxx.it/t/2/js/scripts.js:12:76)", 
    "columnNumber": 76, 
    "fileName": "https://xxxxx.it/t/2/js/scripts.js", 
    "functionName": "Object.r [as forEach]", 
    "lineNumber": 12
  }, 
  {
    "columnNumber": 23, 
    "fileName": "https://xxxxx.it/t/2/js/scripts.js", 
    "source": "    at https://xxxxx.it/t/2/js/scripts.js:11342:23", 
    "lineNumber": 11342
  }, 
  {
    "source": "    at Object.r [as forEach] (https://xxxxx.it/t/2/js/scripts.js:12:76)", 
    "columnNumber": 76, 
    "fileName": "https://xxxxx.it/t/2/js/scripts.js", 
    "functionName": "Object.r [as forEach]", 
    "lineNumber": 12
  }, 
  {
    "source": "    at Object.updateAnswers (https://xxxxx.it/t/2/js/scripts.js:11320:19)", 
    "columnNumber": 19, 
    "fileName": "https://xxxxx.it/t/2/js/scripts.js", 
    "functionName": "Object.updateAnswers", 
    "lineNumber": 11320
  }, 
  {
    "columnNumber": 18, 
    "fileName": "https://xxxxx.it/t/2/js/scripts.js", 
    "source": "    at https://xxxxx.it/t/2/js/scripts.js:11417:18", 
    "lineNumber": 11417
  }, 
  {
    "source": "    at Object.r [as forEach] (https://xxxxx.it/t/2/js/scripts.js:12:76)", 
    "columnNumber": 76, 
    "fileName": "https://xxxxx.it/t/2/js/scripts.js", 
    "functionName": "Object.r [as forEach]", 
    "lineNumber": 12
  }, 
  {
    "source": "    at Object.onAnswersUpdate (https://xxxxx.it/t/2/js/scripts.js:11414:19)", 
    "columnNumber": 19, 
    "fileName": "https://xxxxx.it/t/2/js/scripts.js", 
    "functionName": "Object.onAnswersUpdate", 
    "lineNumber": 11414
  }, 
  {
    "columnNumber": 22, 
    "fileName": "https://xxxxx.it/t/2/js/scripts.js", 
    "source": "    at https://xxxxx.it/t/2/js/scripts.js:20348:22", 
    "lineNumber": 20348

**Comment by evilaliv3** [comment]
Closing as already solved in recent releases.

**Comment by fspegni** [comment]
I'm having this same bug, apparently, with a just installed release (see below). The problem arises when the recipient user presses on the button for asking the custodian the authorization to access the identity of the whistleblower. The button invokes a javascript function called `file_identity_access_request()` and from the browser console a I receive the following error:

```
stacktrace.js:228 POST https://xxx.yyy.it/api/rtip/a6ce391f-d9c7-45dd-90f9-ce70debc6071/iars 501
(anonymous) @ stacktrace.js:228
sendReq @ stacktrace.js:228
serverRequest @ stacktrace.js:228
processQueue @ stacktrace.js:228
(anonymous) @ stacktrace.js:228
$digest @ stacktrace.js:228
$apply @ stacktrace.js:228
(anonymous) @ stacktrace.js:228
defaultHandlerWrapper @ stacktrace.js:228
eventHandler @ stacktrace.js:228
stacktrace.js:228 TypeError: Cannot read property 'score_threshold_medium' of undefined
    at Object.calculateScore (stacktrace.js:228)
    at stacktrace.js:228
    at Object.forEach (stacktrace.js:228)
    at stacktrace.js:228
    at Object.forEach (stacktrace.js:228)
    at Object.updateAnswers (stacktrace.js:228)
    at stacktrace.js:228
    at Object.forEach (stacktrace.js:228)
    at Object.onAnswersUpdate (stacktrace.js:228)
    at stacktrace.js:228 undefined

```
On the administrator mailbox I receive the following error trace message:

```
Platform: ZZZ
Host: xxx.xxx.it (yyy)
Version: 4.1.12

URL: /status/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36

Error Message: TypeError: Cannot read property 'score_threshold_medium' of undefined

Stacktrace:
[
  {
    "columnNumber": 41,
    "lineNumber": 94999,
    "fileName": "https://xxx.xxx.it/js/scripts.js",
    "functionName": "self.calculateScore"
  },
  {
    "columnNumber": 20,
    "lineNumber": 95037,
    "fileName": "https://xxx.xxx.it/js/scripts.js",
    "functionName": "angular.forEach"
  },
  {
    "columnNumber": 20,
    "lineNumber": 7830,
    "fileName": "https://xxx.xxx.it/js/scripts.js",
    "functionName": "isArray"
  },
  {
    "columnNumber": 21,
    "lineNumber": 95036,
    "fileName": "https://xxx.xxx.it/js/scripts.js",
    "functionName": "angular.forEach"
  },
  {
    "columnNumber": 20,
    "lineNumber": 7830,
    "fileName": "https://xxx.xxx.it/js/scripts.js",
    "functionName": "isArray"
  },
  {
    "columnNumber": 17,
    "lineNumber": 95012,
    "fileName": "https://xxx.xxx.it/js/scripts.js",
    "functionName": "angular.forEach"
  },
  {
    "columnNumber": 16,
    "lineNumber": 95111,
    "fileName": "https://xxx.xxx.it/js/scripts.js",
    "functionName": "angular.forEach"
  },
  {
    "columnNumber": 20,
    "lineNumber": 7830,
    "fileName": "https://xxx.xxx.it/js/scripts.js",
    "functionName": "isArray"
  },
  {
    "columnNumber": 17,
    "lineNumber": 95108,
    "fileName": "https://xxx.xxx.it/js/scripts.js",
    "functionName": "angular.forEach"
  },
  {
    "columnNumber": 22,
    "lineNumber": 103659,
    "fileName": "https://xxx.xxx.it/js/scripts.js",
    "functionName": "scope.$watch"
  }
]
```

I would appreciate any hint on how to fix this problem. Thanks in advance.

**Comment by evilaliv3** [comment]
Thank you @fspegni for your feedback.

Is your setup new or updated from a previous version? In this second case which was your previous version?

**Comment by fspegni** [comment]
It is a new setup. I noticed that if I disable the scoring system in the admin interface, the error disappears
