### ISSUE TITLE
Implement /.well-known/security.txt resource

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2647]
This ticket is to discuss and implement the [/.well-known/security.txt resource](https://securitytxt.org/) specified by @edoverflow and proposed as RFC standard to allow websites and web applications to define their security policies.

**Comment by evilaliv3** [comment]
@EdOverflow @nightwatchcyber: In the context of GlobaLeaks as software do you think good that the software embeds in any setup the contact address for our Red Team or do you think that the software should enable the administrator of the setup to configure their own details ? Which is your advice on this?

**Comment by evilaliv3** [comment]
While we collect some feedback, i've considered valuable that GlobaLeaks by default will ship its own ./well-know/security.txt policy that in the future we may evaluate to make configurable/customable.

The policy is defined as following:
```
Policy: https://github.com/globaleaks/GlobaLeaks/security/policy
Contact: mailto:security@globaleaks.org
Encryption: https://raw.githubusercontent.com/globaleaks/GlobaLeaks/main/keys/security.asc
Expires: 2022-11-24T19:46:03.774007Z```

The expiration date is generated dynamically and set to be valid for 1 year, following the recommendations of the specification.

**Comment by nightwatchcyber** [comment]
> @EdOverflow @nightwatchcyber: In the context of GlobaLeaks as software do you think good that the software embeds in any setup the contact address for our Red Team or do you think that the software should enable the administrator of the setup to configure their own details ? Which is your advice on this?

I think it would make the most sense to configure this with the administrator's information instead of your team.

**Comment by evilaliv3** [comment]
Thank you so much for your feedback @nightwatchcyber! 

If you do not have contraindications i would plan the following:
- For the moment i will include the information above so that at least people could at least find those in case of need; Considered the aim our project overall i would not consider it bad.
- For the future we will evaluate to make it configurable via the software, but this unfortunately would need time for studying a proper UI and to translate it in the current 90~ languages so unfortunately we need to give priority to other features.

**Comment by nightwatchcyber** [comment]
As long as you are prepared to triage the reports, that should be fine.
