### ISSUE TITLE
Unhandled exception in case management Error Message: TypeError: $scope.editableStatusesList is not a function

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2653]
Platform: Whistleblowing XXXXXX
Host:  
Version: 3.9.7

URL: /admin/case_management

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

Error Message: TypeError: $scope.editableStatusesList is not a function

Stacktrace:
[
  {
    "columnNumber": 34,
    "lineNumber": 22227,
    "fileName": "https://whistleblowing.xxxx.it/js/scripts.js",
    "functionName": "swap",
    "source": "    at swap (https://whistleblowing.xxxxx.it/js/scripts.js:22227:34)"
  },

**Comment by evilaliv3** [comment]
Solved in the upcoming release 3.10.0
