### ISSUE TITLE
signup page and tenants sites show a warning and it's impossible to proceed

### ISSUE THREAD

**Issue by vodkina** [globaleaks/GlobaLeaks#2654]
**Current behavior**
<img width="1111" alt="Screenshot 2019-07-27 14 52 11" src="https://user-images.githubusercontent.com/2151323/61994719-76fa6500-b07e-11e9-8f43-50a82868afab.png">

**Comment by evilaliv3** [comment]
Thank you @vodkina.
Actually i was implementing the footer as for your needs and i you hit the moment in which i was doing some live debugging.

It should be solved now.
