### ISSUE TITLE
Footer text modification not applied after changing them in the admin interface

### ISSUE THREAD

**Issue by vodkina** [globaleaks/GlobaLeaks#2656]
**Current behavior**
Changing the content of Footer text in Settings - Main Settings and saving the modification does not achieve any changement in the footer text

**Expected behavior**
When modifying footer text in Settings - Main Settings and saving the modifications should achieve modification of the footer text

**Steps to reproduce the problem or feature illustration**

- log in the platform as an admin
- go to Settings, Main settings, Footer 
- change footer text
- click save button
- check on platform if footer text modification is done

**What is the motivation or use case for changing the behavior?**
Should be an expected behaviour and it worked till some time ago

**GlobaLeaks version:**
Project EAT version actually installed

**Browser:**
Chrome 75.0.3770.142

**Comment by evilaliv3** [comment]
@vodkina : your footer is implemented via a custom javascript as foor: https://github.com/globaleaks/GlobaLeaks/issues/2622

To edit it you should download the custom javascript, edit it manually and re-upload it.
