### ISSUE TITLE
Unhandled exception Cannot read property 'files' of undefined

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2660]
Platform: WhistleblowingPA
Host: registrazione.whistleblowing.it  
Version: 3.10.3

URL: /submission

User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36

Error Message: TypeError: Cannot read property 'files' of undefined

Stacktrace:
[
  {
    "columnNumber": 28,
    "lineNumber": 11017,
    "fileName": "https://xxx.whistleblowing.it/js/scripts.js",
    "functionName": "Object.isUploading",
    "source": "    at Object.isUploading (https://xxx.whistleblowing.it/js/scripts.js:11017:28)"
  },
  {
    "columnNumber": 27,
    "lineNumber": 22529,
    "fileName": "https://xxx.whistleblowing.it/js/scripts.js",
    "functionName": "m.$scope.submissionHasErrors",
    "source": "    at m.$scope.submissionHasErrors (https://xxx.whistleblowing.it/js/scripts.js:22529:27)"
  },
  {
    "columnNumber": 41,
    "lineNumber": 22629,
    "fileName": "https://xxx.whistleblowing.it/js/scripts.js",
    "functionName": "m.$scope.displayErrors",
    "source": "    at m.$scope.displayErrors (https://xxx.whistleblowing.it/js/scripts.js:22629:41)"
  },
  {
    "columnNumber": 1,
    "lineNumber": 1,
    "fileName": "https://xxx.whistleblowing.it/js/scripts.js",
    "functionName": "fn",
    "source": "    at fn (https://xxx.whistleblowing.it/js/scripts.js:1:1"
  },
  {
    "columnNumber": 381,
    "lineNumber": 155,
    "fileName": "https://xxx.whistleblowing.it/js/scripts.js",
    "functionName": "m.$digest",
    "source": "    at m.$digest (https://xxx.whistleblowing.it/js/scripts.js:155:381)"
  },
  {
    "columnNumber": 35,
    "lineNumber": 159,
    "fileName": "https://xxx.whistleblowing.it/js/scripts.js",
    "functionName": "m.$apply",
    "source": "    at m.$apply (https://xxx.whistleblowing.it/js/scripts.js:159:35)"
  },
  {
    "columnNumber": 125,
    "lineNumber": 202,
    "fileName": "https://xxx.whistleblowing.it/js/scripts.js",
    "functionName": "HTMLButtonElement.<anonymous>",
    "source": "    at HTMLButtonElement.<anonymous> (https://xxx.whistleblowing.it/js/scripts.js:202:125)"
  },
  {
    "columnNumber": 158,
    "lineNumber": 44,
    "fileName": "https://xxx.whistleblowing.it/js/scripts.js",
    "functionName": "sg",
    "source": "    at sg (https://xxx.whistleblowing.it/js/scripts.js:44:158)"
  },
  {
    "columnNumber": 105,
    "lineNumber": 44,
    "fileName": "https://xxx.whistleblowing.it/js/scripts.js",
    "functionName": "HTMLButtonElement.d",
    "source": "    at HTMLButtonElement.d (https://xxx.whistleblowing.it/js/scripts.js:44:105)"
  }
]

**Comment by evilaliv3** [comment]
Closing as outdated.
