### ISSUE TITLE
Hostname for HTTPS doesn't support "subdomain.domain.tld/pathname"

### ISSUE THREAD

**Issue by RrOoSsSsOo** [globaleaks/GlobaLeaks#2663]
**Current behavior**

Into web configuration for Network settings > HTTPS I can insert `subdomain.domain.tld` but no `subdomain.domain.tld/pathname`.
But I can have multiple site of Globaleaks in the same (https) site distinct from pathname...
`subdomain.domain.tld/pathname1`
`subdomain.domain.tld/pathname2`

**Expected behavior**

The possibility to insert `subdomain.domain.tld/pathname`, with the "data-ng-model" of any URL, not only `data-ng-model="admin.node.hostname"`.

**What is the motivation or use case for changing the behavior?**

The same file is reported into notification emails.

**GlobaLeaks version:**

v3.10.8

**Browser:**

Any

**Comment by evilaliv3** [comment]
@RrOoSsSsOo: Thank you for your feedback.

Actually an HTTPS certificate do not allow to write ```"subdomain.domain.tld/pathname"``` as COMMON name.

Currently you could reach them using a wildcard certificate at name.domain.tld.

Alternatively, currently you can already serve all the tenants under the same domain by reaching then like:
-```"subdomain.domain.tld/t/1/"``` 
-```"subdomain.domain.tld/t/2/"``` 
-```"subdomain.domain.tld/t/3/"```

Maybe in the future will be valuable to extend this possibility making it possible to reach them by name as:
-```"subdomain.domain.tld/t/name1/"``` 
-```"subdomain.domain.tld/t/name2/"```
-```"subdomain.domain.tld/t/name3/"```
