### ISSUE TITLE
Implement 2FA based on TOTP (RFC 6238)

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2664]
For both usability and security reasons it would be worth replacing the current 2FA based on email with a 2FA authentication based on TOTP  ([RFC 6238](https://tools.ietf.org/html/rfc6238))

As for the python implementation i consider that we could use https://github.com/pyauth/pyotp by @pyauth that is already packaged for ubuntu starting from Bionic.

As for the frontend side there are instead many alternatives to be still evaluated.

Suggestion originally provided by @gdassori

**Comment by evilaliv3** [comment]
This ticket would actually deprecate https://github.com/globaleaks/GlobaLeaks/issues/2481 for a matter of both security and usability.

In my opinion then , in the context of globaleaks, it would make unnecessary https://github.com/globaleaks/GlobaLeaks/issues/1352

The implementation would require changes to the database:
- adding a ```2fa_enabled``` (boolean) flag in the User model
- adding a ```2fa_secret```  (string) secret in the User model

In case the encryption module is enabled, the secret could be kept encrypted as common best practice using the User public key so to keep it in pleaintext in RAM only during login.

**Comment by gdassori** [comment]
Thanks for the mention and kudos for the velocity :-)

Since it is common to lose TOTP seeds, I've seen is rather adopted on 2FA based authentications to use implementations like #2481 as a fallback system.

I see the point to deprecate email 2FA for increased security, but could a 1D delay between the fallback method login request and the ability to do it (with proper email notifications of the process) be a good trade-off between security and independence? Or is only the system administrator deputy to reset lost 2FA methods?

**Comment by evilaliv3** [comment]
You are welcome @gdassori 

Actually making it possible for the user to enable this fallback would open in my opinion to an important protocol downgrade possibility that would actually make the system security be the constantly equal to the one of @2481. 

As for the reset problem i think the independency could be achieved, in addition to the possibility for the admin to reset the config, with
2) feature https://github.com/globaleaks/GlobaLeaks/issues/2649 where we could make that the "Encryption recovery key" when used would reset as well the two factor authentication.
3) show to the user the secret of the 2FA so that it can be written down but maybe. we could write the secret below the barcode.

what do you think?

what do you think?

**Comment by evilaliv3** [comment]
In the meantime i've verified the availability of python-pyotp on Ubuntu and Debian:
- Ubuntu Bionic: the package exist: 2.2.6
- Ubuntu Xenial: the package do not exists but the Bionic package works like a charm.
- Debian Stretch: the package exists: 2.2.1

**Comment by evilaliv3** [comment]
Interface currently designed:

![screenshot-127 0 0 1_8082-2019 08 29-08_14_34](https://user-images.githubusercontent.com/217034/63914961-11aae280-ca35-11e9-94c3-bfdd20ecb7d3.png)

**Comment by gdassori** [comment]
Very nice, I definitely agree that is important to show the seed to enable paper backups.

I have to agree too that the security model would not take all the benefits of removing the email as 2FA. Even if a delay is a mitigation, a successful attacker could actually manage to hide the notifications email to the victim. The potential weakness would be still there.

About the behaviour you defined with 2649, as is up to the user to manage all the recovery credentials (assuming you want to reduce the admin interventions as less as possible), this is just a UI\UX challenge: users have to be warned to really take care of the credential. 

This could be easily achieved adding another step into the instructions to warn about the irreproducibility of the credential, as it's common to just scan the QR and forgot to write down the seed. 

This could also help users understand that is a good practice to manage different credentials (the recovery key and the TOTP seed, in this case) with different policies (imho users should reduce the usage of the recovery key as much as possible, for a lot of reasons, as long as there is an option).

**Comment by vodkina** [comment]
Great implementation, @evilaliv3 
I would just add, for the sake of usability, a suggestion of some of the well known existing authenticator apps aside the "• Install an authenticator app on your phone", so to help users that are not familiar with it.
Sure, more details about 2FA could be added in the documentation, but I feel that a hint could improve usability from users point of view

**Comment by evilaliv3** [comment]
Thank you @vodkina, we have considered that but for the moment we would prefer to not mention an app inside of the software and keep the text of the application easy internationalizable. We may cope with this in the documentation.

**Comment by evilaliv3** [comment]
Closing as implemented.

Will be shipped in upcoming 3.11.0

**Comment by SylvainFPU** [comment]
@evilaliv3 When I implement it I could not see the QR code image but only the code blow (which also works, but it is a bit confusing at first.

Sorry I can't find my screenshot again

Platform: Publeaks
Version: 4.11.44

**Comment by evilaliv3** [comment]
Which is the code below?

I just retried the feature and i currently do not see malfunctions; would you please retry when you will have the time and pass me screenshot?

**Comment by SylvainFPU** [comment]
Is 2FA available for Admin? If so, where?

**Comment by SylvainFPU** [comment]
![Screenshot from 2019-12-11 12-19-58](https://user-images.githubusercontent.com/46898563/70617311-95699300-1c10-11ea-88b1-a81de8761024.png)

**Comment by SylvainFPU** [comment]
Also happening in the English version

**Comment by evilaliv3** [comment]
@SylvainFPU: if you open the developers console in chrome with ctrl+shift+j do you read any error in the javascript console?

**Comment by SylvainFPU** [comment]
Recipients and Admin are restricted to Tor browser to access the accounts. No Chrome involved here
