### ISSUE TITLE
Encrypt file upload metadata

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2665]
Current implementation maintains the following metadata of the uploaded files in plaintext in the InternalFile table:
- name
- size
- mime-type

Thanks to the current encryption implementation this metadata could be now encrypted by using the submission key following the same design pattern implemented for other Tip information.

**Comment by evilaliv3** [comment]
This ticket would require minor database changes changing all the attributes that contains metadata to be of type JSON in order to possibly host plaintext data or encrypted data in form of text.

**Comment by fpietrosanti** [comment]
> This ticket would require minor database changes changing all the attributes that contains metadata to be of type JSON in order to possibly host plaintext data or encrypted data in form of text.

Consider maintaining all SQL db that will be likely needed for database interrogation, like the "subject to statistics" of questionnaire field to keep them in DB in clear in a SQL entry.

**Comment by evilaliv3** [comment]
@fpietrosanti: this ticket deals specifically with files,  where size, mimetype and name could leak important information.

For what relates submissions metadata (like tor/http, desktop/mobile) i agree with your point of view.

**Comment by fpietrosanti** [comment]
> @fpietrosanti: this ticket deals specifically with files, where size, mimetype and name could leak important information.
> 
> For what relates submissions metadata (like tor/http, desktop/mobile) i agree with your point of view.

Yes, i mean that we'll likely have functionalities that would need to be able to query on those filename, size, mimetype, so better to keep the encryption that can be enabled/disabled on those, like for the submission questionnaire answers subject to statistics.

**Comment by evilaliv3** [comment]
Closing as implemented.

Will be shipped in upcoming 3.11.0
