### ISSUE TITLE
Implement HTTP Feature-Policy Header

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2667]
A HTTP Feature-Policy is HTTP header defined by @w3c for instructing the browser about which features the application intends to make use of and to lock down access to others. This is a new security mechanism that ensures that should an application become compromised or a third party
attempts an unexpected action, the browser will override it and maintain the intended UX.

WICG specification: https://wicg.github.io/feature-policy/

As of today Chrome and Safari and Edge have public support for this and Firefox working on its support.

In the context of application of GlobaLeaks i would suggest to disable alll the functionalities that could lead to deanonimizations of the user like the following:
- camera
- display-capture
- document-domain
- fullscreen
- geolocation
- microphone
- speaker

This could be achieved by setting the following header:
```Feature-Policy: camera 'none'; display-capture 'none'; document-domain 'none'; fullscreen 'none'; geolocation 'none'; microphone 'none; speaker 'none';```

**Comment by fpietrosanti** [comment]
Remember to update the Application Security Document including all those technical details specs

**Comment by evilaliv3** [comment]
Its is always kept up to date since a while now man!

**Comment by evilaliv3** [comment]
Closing as implemented.

Will be shipped in upcoming 3.11.0
