### ISSUE TITLE
Regression in the questionnaire import in version 3.11.0

### ISSUE THREAD

**Issue by zazzati** [globaleaks/GlobaLeaks#2672]
**Current behavior**

Function import questionnaires **not working**
Click on button import doesn't fire any event. The button seems disabled. 

**Expected behavior**

You can import questionnaires  from json export.
It works in 3.10 

**Steps to reproduce the problem or feature illustration**

Questionnaires, import button

**GlobaLeaks version:**

3.11.0 

**Browser:**

Chrome, Firefox 

**Server Operating System and Version (if applicable):**
 
Ubuntu Bionic 

![image](https://user-images.githubusercontent.com/28624698/64599095-1a969f00-d3b9-11e9-93eb-3aca7451d2dd.png)

Button import is inactive.

**Comment by evilaliv3** [comment]
Thank you @zazzati 

The bug has been already identified and fixed.

It will be released by tomorrow.

**Comment by evilaliv3** [comment]
@zazzati: we just released a version 3.11.1 that fixes this bug

would you please test yourself?

**Comment by evilaliv3** [comment]
@zazzati: i think you are importing a questionnaire that is already loaded.

If you need to make a copy of an existing questionnaire use the Clone functionality instead.

**Comment by zazzati** [comment]
> @zazzati: i think you are importing a questionnaire that is already loaded.

My mistake. 
Now import is OK. 
Thx.

**Comment by evilaliv3** [comment]
Thank you so much @zazzati for your support in the retesting.
