### ISSUE TITLE
The 'Upload' botton form the 'Files' section doesn't work anymore

### ISSUE THREAD

**Issue by tsundokul** [globaleaks/GlobaLeaks#2675]
Tested with Firefox and Chrome both on Ubuntu and Windows. Clicking it doesn't pop up the upload dialog box. GlobaLeaks version 3.11.2.

**Comment by evilaliv3** [comment]
Thank you for reporting this @tsundokul 

We will emit a release 3.11.3 ti fix this regressione.

**Comment by evilaliv3** [comment]
Closing as the patch has been included for release 3.11.3
