### ISSUE TITLE
Terms of service "checkbox label" has disapperaed

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2683]
after recent updates (not sure which one)  the "therms of service" checkbox label has disappeared  in 2 out of 3 sites.

When I create a terms of service type of question and put agree or disagree as Checkbox label this is not vsible on WB platform. One can see only the checkbox. 
I have also created a test domain on the try.globaleks domain and shows the same behaviour.
https://testme2.try.globaleaks.org

The strange thing is that one of my sites is not affected (however since it is operational I have just updated it but haven't edited it for a while) multiple instances on the same main domain

I'm using the current version of globaleaks on Ubuntu 18.04 with chrome and edge clients on win 10

**Comment by evilaliv3** [comment]
Thank you for reporting this @elbill 

Actually on https://testme2.try.globaleaks.org the texts appear to not be configured. Maybe there is regression not making it possiule to save them correctly?

I will try go give it a look an let you know

**Comment by elbill** [comment]
the terms of service text does not appear at all as well. it is not only the checkbox label.

**Comment by evilaliv3** [comment]
@elbill: bug confirmed thank you.

It is a regression introduced in https://github.com/globaleaks/GlobaLeaks/commit/52f63823ec8de883108299f269aae63e554975c2

It causes that any special question attribute is not saved (e.g. the lable of a term of service

I'm about to commit a fix and issue a new release

**Comment by evilaliv3** [comment]
@elbill : You can now update to release 3.11.19 that should fix the issue.

Would you please let us know if it works?

**Comment by elbill** [comment]
thanks. Seems to be working fine now

**Comment by evilaliv3** [comment]
thank you @elbill !
