### ISSUE TITLE
Can't update - deb.torproject.org forbidden

### ISSUE THREAD

**Issue by loxely** [globaleaks/GlobaLeaks#2684]
**Current behavior**
Updating from 3.10.8 to 3.11.20

**Steps to reproduce the problem or feature illustration**
even using "apt-get update && apt-get install globaleaks"
or install script 
wget https://deb.globaleaks.org/install-globaleaks.sh
chmod +x install-globaleaks.sh
./install-globaleaks.sh

**GlobaLeaks version:**

Updating from 3.10.8 to 3.11.20

**Server Operating System and Version (if applicable):**
ubuntu 16.04

**errore**
root@GlobaLeaks:/home/administrator# apt-get update && apt-get upgrade
Ignorato:1 http://deb.globaleaks.org xenial/ InRelease                         
Scaricamento di:2 http://deb.globaleaks.org xenial/ Release [1.506 B]          
Ignorato:3 http://deb.torproject.org/torproject.org xenial InRelease           
Trovato:4 http://security.ubuntu.com/ubuntu xenial-security InRelease        
Trovato:5 http://it.archive.ubuntu.com/ubuntu xenial InRelease                 
Scaricamento di:6 http://deb.globaleaks.org xenial/ Release.gpg [833 B]        
Errore:6 http://deb.globaleaks.org xenial/ Release.gpg                         
  Le seguenti firme non erano valide: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
Trovato:7 http://it.archive.ubuntu.com/ubuntu xenial-updates InRelease         
Ignorato:8 http://deb.torproject.org/torproject.org xenial Release             
Trovato:9 http://it.archive.ubuntu.com/ubuntu xenial-backports InRelease       
Ignorato:10 http://deb.torproject.org/torproject.org xenial/main amd64 Packages.diff/Index
Ignorato:11 http://deb.torproject.org/torproject.org xenial/main i386 Packages.diff/Index
Ignorato:12 http://deb.torproject.org/torproject.org xenial/main all Packages
Ignorato:13 http://deb.torproject.org/torproject.org xenial/main Translation-it_IT
Ignorato:14 http://deb.torproject.org/torproject.org xenial/main Translation-it
Ignorato:15 http://deb.torproject.org/torproject.org xenial/main Translation-en
Ignorato:16 http://deb.torproject.org/torproject.org xenial/main amd64 DEP-11 Metadata
Ignorato:17 http://deb.torproject.org/torproject.org xenial/main DEP-11 64x64 Icons
Ignorato:18 http://deb.torproject.org/torproject.org xenial/main amd64 Packages
Ignorato:19 http://deb.torproject.org/torproject.org xenial/main i386 Packages
Ignorato:12 http://deb.torproject.org/torproject.org xenial/main all Packages
Ignorato:13 http://deb.torproject.org/torproject.org xenial/main Translation-it_IT
Ignorato:14 http://deb.torproject.org/torproject.org xenial/main Translation-it
Ignorato:15 http://deb.torproject.org/torproject.org xenial/main Translation-en
Ignorato:16 http://deb.torproject.org/torproject.org xenial/main amd64 DEP-11 Metadata
Ignorato:17 http://deb.torproject.org/torproject.org xenial/main DEP-11 64x64 Icons
Ignorato:18 http://deb.torproject.org/torproject.org xenial/main amd64 Packages
Ignorato:19 http://deb.torproject.org/torproject.org xenial/main i386 Packages
Ignorato:12 http://deb.torproject.org/torproject.org xenial/main all Packages
Ignorato:13 http://deb.torproject.org/torproject.org xenial/main Translation-it_IT
Ignorato:14 http://deb.torproject.org/torproject.org xenial/main Translation-it
Ignorato:15 http://deb.torproject.org/torproject.org xenial/main Translation-en
Ignorato:16 http://deb.torproject.org/torproject.org xenial/main amd64 DEP-11 Metadata
Ignorato:17 http://deb.torproject.org/torproject.org xenial/main DEP-11 64x64 Icons
Ignorato:18 http://deb.torproject.org/torproject.org xenial/main amd64 Packages
Ignorato:19 http://deb.torproject.org/torproject.org xenial/main i386 Packages
Ignorato:12 http://deb.torproject.org/torproject.org xenial/main all Packages
Ignorato:13 http://deb.torproject.org/torproject.org xenial/main Translation-it_IT
Ignorato:14 http://deb.torproject.org/torproject.org xenial/main Translation-it
Ignorato:15 http://deb.torproject.org/torproject.org xenial/main Translation-en
Ignorato:16 http://deb.torproject.org/torproject.org xenial/main amd64 DEP-11 Metadata
Ignorato:17 http://deb.torproject.org/torproject.org xenial/main DEP-11 64x64 Icons
Ignorato:18 http://deb.torproject.org/torproject.org xenial/main amd64 Packages
Ignorato:19 http://deb.torproject.org/torproject.org xenial/main i386 Packages
Ignorato:12 http://deb.torproject.org/torproject.org xenial/main all Packages
Ignorato:13 http://deb.torproject.org/torproject.org xenial/main Translation-it_IT
Ignorato:14 http://deb.torproject.org/torproject.org xenial/main Translation-it
Ignorato:15 http://deb.torproject.org/torproject.org xenial/main Translation-en
Ignorato:16 http://deb.torproject.org/torproject.org xenial/main amd64 DEP-11 Metadata
Ignorato:17 http://deb.torproject.org/torproject.org xenial/main DEP-11 64x64 Icons
Ignorato:18 http://deb.torproject.org/torproject.org xenial/main amd64 Packages
Ignorato:19 http://deb.torproject.org/torproject.org xenial/main i386 Packages
Ignorato:12 http://deb.torproject.org/torproject.org xenial/main all Packages
Ignorato:13 http://deb.torproject.org/torproject.org xenial/main Translation-it_IT
Ignorato:14 http://deb.torproject.org/torproject.org xenial/main Translation-it
Ignorato:15 http://deb.torproject.org/torproject.org xenial/main Translation-en
Ignorato:16 http://deb.torproject.org/torproject.org xenial/main amd64 DEP-11 Metadata
Ignorato:17 http://deb.torproject.org/torproject.org xenial/main DEP-11 64x64 Icons
Errore:18 http://deb.torproject.org/torproject.org xenial/main amd64 Packages
  403  Forbidden [IP: 116.202.120.165 80]
Ignorato:19 http://deb.torproject.org/torproject.org xenial/main i386 Packages
Recuperati 2.339 B in 29s (78 B/s)
Lettura elenco dei pacchetti... Fatto
W: Si è verificato un errore nel verificare la firma. Il repository non è aggiornato e verranno usati i file indice precedenti. Errore GPG: http://deb.globaleaks.org xenial/ Release: Le seguenti firme non erano valide: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Il repository "http://deb.torproject.org/torproject.org xenial Release" non ha un file Release.
N: I dati da tale repository non possono essere autenticati e può essere pericoloso utilizzarli.
N: Consultare la pagina man apt-secure(8) per la creazione di un repository e la configurazione utente.
W: Impossibile recuperare http://deb.globaleaks.org/xenial/Release.gpg  Le seguenti firme non erano valide: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
E: Impossibile recuperare http://deb.torproject.org/torproject.org/dists/xenial/main/binary-amd64/Packages  403  Forbidden [IP: 116.202.120.165 80]
W: Impossibile scaricare alcuni file di indice: saranno ignorati o verranno usati quelli vecchi.

**Comment by evilaliv3** [comment]
@loxely : actually tor remote the xenial support
Just edit your apt source file removing the tor repository and use only our repository. (deb.globaleaks.org).

**Comment by loxely** [comment]
Thanks a lot
Now working on TLS update 👅 
I'm getting "Obsolete TLS error" browsing from external PC (Chrome/firefox/IE)
and "unsupported browser" browsing on local server using firefox v69 ..
.. Stuck

**Comment by evilaliv3** [comment]
I see, try to just free the browser cache. In my opionion you have just a cache that is preventing you to load.

As soon that you do this, if you still have an error please send me the full error log and some screenshots with the different browsers on which you have problem.

p.s. : if you can discuss specific topic on specific tickets; feel free to open new one if necessary.
