### ISSUE TITLE
Introduce support for automatic priority of Onion Website for Tor using Alt-Svc 

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2687]
**Current behavior**
Actually the detection of a user coming from Tor or not, with consequential redirect to .onion, is done with server-side detection of IP addresses, leading sometime to false negative.

**Expected behavior**
This ticket is to keep track and then implement support for Alt-Svc based priority of Onion based services as per https://trac.torproject.org/projects/tor/ticket/27502

**Comment by evilaliv3** [comment]
@fpietrosanti: Would you please clarify with an example what you mean with false negative?

For semplicity (KISS principle) GlobaLeaks is currently supporting only one kind of onion service: current version 3

Old platforms with an already generated onion address version 3, are enabled to upgrade resetting the onion service. They can as well continue to use onion service version 3 if they want.

**Comment by fpietrosanti** [comment]
False negative = not detecting a user coming from Tor because of the imperfect way Tor detection works. 
That doesn't have anything to do with Onion service v2 or v3, but as the way to have end users browsing with Tor, being 100% sure to load GlobaLeaks from .onion rather than HTTPS.

**Comment by evilaliv3** [comment]
Deprecated by https://github.com/globaleaks/GlobaLeaks/issues/2847
