### ISSUE TITLE
customising text in different languages not working as expected

### ISSUE THREAD

**Issue by vodkina** [globaleaks/GlobaLeaks#2688]
**Current behaviour**
Applying a customised text translation on a generated instance (modela,disclosers.eu) of disclosers.eu does not work

**Expected behaviour**
when applying customisation of texts in languages it has to work and be applied

**Steps to reproduce the problem or feature illustration**
login in the main platform as an admin and apply the desired customised change to text translation in Greek language, then log in as an admin in the modela,disclosers.eu instance and apply the same customised translation.
When checking for applied customised translation it does not appear to be applied in modela,disclosers.eu

**What is the motivation or use case for changing the behaviour?**
EAT project requires customisation of some texts in different languages

**GlobaLeaks version:**
Software version: 3.11.21

**Comment by evilaliv3** [comment]
@vodkina: thank you for your feedback.

which text are you trying to customize?

I'm asking this because currently the feature does show every text of td platform but it is not possible to override them al because some text are configurable with specific  variables or some texts are not customable. 

If you could be more specific I could try to guide you through.

**Comment by vodkina** [comment]
thanks @evilaliv3 ,
I'll send you the mail from the Greeks partners with the required modifications; it's easier than rewrite it here.
It's a urgent request and also other partners are requiring similar modifications.

**Comment by evilaliv3** [comment]
Thank you @vodkina 

From the email I confirm that the solution should be the one above.

Read again message above and retry with my instructions. I'm almost sure this is the case. As well I've tried to be more clear in my email.

**Comment by evilaliv3** [comment]
Closing as the user confirms that no bug exists and with the above instruction the issues is solved.

To be eventually betterly documented.
