### ISSUE TITLE
Fix Google crawling support of GlobaLeaks sites

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2697]
**Current behavior**
Actually in all GlobaLeaks sites, when google (and other search engine) pass trough for crawling, it does display as a preview the Tor warning that's not informative of the whistleblowing sites information:
"You are running an unsupported and potentially vulnerable browser. You are strongly advised to download and install the Tor Browser. "

es1: 
<img width="648" alt="Screen Shot 2019-10-11 at 20 12 54" src="https://user-images.githubusercontent.com/770363/66674582-89d70b80-ec63-11e9-9946-abfa556a1e1f.png">

es2:
<img width="625" alt="Screen Shot 2019-10-11 at 20 21 01" src="https://user-images.githubusercontent.com/770363/66675002-b0497680-ec64-11e9-9f95-a56b704e28d7.png">

**Expected behavior**
This ticket is about improving the search engine presence of a GlobaLeaks site, enabling the Whistleblower find useful information on the site from the title and description on search engine.

**Comment by evilaliv3** [comment]
This would be probably pretty easy to fix but in my opinion we should focus our research and effort in more valuable aspects.

e.g. just looking at the statistics of this, there would be really 0 value in implementing this ticket.

https://gs.statcounter.com/search-engine-market-share

![Screenshot-2019-10-11 Search Engine Market Share Worldwide StatCounter Global Stats](https://user-images.githubusercontent.com/217034/66678685-be02fa00-ec6c-11e9-8d26-af91613c84af.png)

**Comment by fpietrosanti** [comment]
Hint for debugging from previous evening:
- https://search.google.com/search-console/about
- https://developers.google.com/search/docs/guides/fix-search-javascript

It's maybe going in "BrowserNotSupported" Div of index.html from js/loader.js code-flow, that would need some debugging

**Comment by evilaliv3** [comment]
Closing as fixed.
