### ISSUE TITLE
GLClient request a HEAD on /public triggering a 501 not implemented

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2702]
**Current behavior**
On latest version 3.11.27 of GlobaLeaks the /public request is always requested two time, one issuing a HEAD that return a 501 not implemented, and after some 10-15 seconds a GET and works correctly.

**Expected behavior**
This ticket is to track down why it's issuing two requests.

Log except from access.log from try.globaleaks.org .

[REMOVED_IP_ADDRESS] - - [12/Oct/2019:13:44:42 +0000] "HEAD /public HTTP/1.1" 501 0 -1ms - "[REMOVED_USER_AGENT]" 1
[REMOVED_IP_ADDRESS] - - [12/Oct/2019:13:45:02 +0000] "GET /public HTTP/1.1" 200 14315 1ms - "[REMOVED_USER_AGENT]" 1

[REMOVED_IP_ADDRESS] - - [12/Oct/2019:13:50:02 +0000] "HEAD /public HTTP/1.1" 501 0 -1ms - "[REMOVED_USER_AGENT]" 1
[REMOVED_IP_ADDRESS] - - [12/Oct/2019:13:50:22 +0000] "GET /public HTTP/1.1" 200 14315 0ms - "[REMOVED_USER_AGENT]" 1

[REMOVED_IP_ADDRESS] - - [12/Oct/2019:13:55:23 +0000] "HEAD /public HTTP/1.1" 501 0 -1ms - "[REMOVED_USER_AGENT]" 1
[REMOVED_IP_ADDRESS] - - [12/Oct/2019:13:55:43 +0000] "GET /public HTTP/1.1" 200 14315 0ms - "[REMOVED_USER_AGENT]" 1

[REMOVED_IP_ADDRESS] - - [12/Oct/2019:14:00:43 +0000] "HEAD /public HTTP/1.1" 501 0 -1ms - "[REMOVED_USER_AGENT]" 1
[REMOVED_IP_ADDRESS] - - [12/Oct/2019:14:01:03 +0000] "GET /public HTTP/1.1" 200 14315 1ms - "[REMOVED_USER_AGENT]" 1

**Comment by fpietrosanti** [comment]
Possibly is the "must-revalidate" header being sent by GlobaLeaks:
https://stackoverflow.com/questions/18148884/difference-between-no-cache-and-must-revalidate

Maybe we need to use the new immutable cache control header, telling the browser that even if not cached, the resource will always be that way (so no need to check if it's going to change or not):
https://webmasters.stackexchange.com/questions/25342/headers-to-prevent-304-if-modified-since-head-requests
https://engineering.fb.com/web/this-browser-tweak-saved-60-of-requests-to-facebook/
https://www.keycdn.com/blog/cache-control-immutable
https://bitsup.blogspot.com/2016/05/cache-control-immutable.html

**Comment by evilaliv3** [comment]
@fpietrosanti: telling the resource that will be permanent if it is not the case could lead to failure in my opinion.

**Comment by fpietrosanti** [comment]
@evilaliv3 as there is the "no-cache", it should likely means that this resource will be "immutable" only during this GLClient session, and that make sense, because the GLClient will fetch /public over it's entire life only once.

**Comment by evilaliv3** [comment]
@fpietrosanti: This HEAD request is set by us intentionally on uptime robot.

No other client, in any of our setups, seems to be performing any of the above mentioned behaviors.

Actually i think it is worthless to investigate this more.

**Comment by evilaliv3** [comment]
Legit ticket but still a feature request, not a bug.
