### ISSUE TITLE
It's not possible to understand which hostname received a certain HTTP request from access.log

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2703]
**Current behavior**
In a modern multi-tenant setup the webserver of GlobaLeaks is shared among many different websites with different hostname, yet the access.log useful for debugging purposes is only one.

**Expected behavior**
This ticket is to extend the access.log format in order to include also the hostname of the tenant that received a specific HTTP request, enabling specific tenant debugging.

The same debugging issue is present on unhandled exception as per #2466

**Comment by evilaliv3** [comment]
Legit ticket but still a feature request, not a bug.

**Comment by evilaliv3** [comment]
Implemented and released at least since v3.11.36
