### ISSUE TITLE
Unhandled exception "Producer was not unregistered for b'/'"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2706]
**Current behavior**
There are multiple errors in globaleaks.log as per:
2019-10-11 18:47:59+0000 [-] [E] Unhandled exception raised:
2019-10-11 18:47:59+0000 [-] [E] RuntimeError Unspecified run-time error.\n\nRuntimeError: Producer was not unregistered for b'/'\n
2019-10-11 18:47:59+0000 [-] Unhandled Error
	Traceback (most recent call last):
	Failure: builtins.RuntimeError: Producer was not unregistered for b'/'

**Comment by fpietrosanti** [comment]
Only reference on google of this problem is https://github.com/matrix-org/synapse/issues/4933 

and it's said to be caused by OPTIONS CORS headers missing, don't know if that's the case.

**Comment by fschatz** [comment]
We do also face this error.

Version: 4.7.11

RuntimeError Unspecified run-time error.

RuntimeError: Producer was not unregistered for b'/js/scripts.min.js'

Can you help?

**Comment by evilaliv3** [comment]
@fschatz : the commit above should actully silence the exception and will be included in  4.7.15
