### ISSUE TITLE
I can't access the Site via public IP after installation

### ISSUE THREAD

**Issue by draft1** [globaleaks/GlobaLeaks#2710]
What could be the problem?

# ./install-globaleaks.sh
Checking preliminary packaging GlobaLeaks requirements
 + apt-key requirement met
 + apt-get requirement met
 + gpg requirement met
Detected OS: Debian - buster
Running: "apt-get -y update"... SUCCESS
 - curl requirement not met. Installing curl
Running: "apt-get -y install curl"... SUCCESS
 + netstat requirement met
Running: "is_tcp_sock_free_check 0.0.0.0:80"... SUCCESS
Running: "is_tcp_sock_free_check 0.0.0.0:443"... SUCCESS
Running: "is_tcp_sock_free_check 127.0.0.1:8082"... SUCCESS
Running: "is_tcp_sock_free_check 127.0.0.1:8083"... SUCCESS
 + required TCP sockets open
Adding GlobaLeaks PGP key to trusted APT keys
Running: "apt-key add /tmp/tmp.gAb6gXOzMx/globaleaks_key"... SUCCESS
Running: "rm /tmp/tmp.gAb6gXOzMx/globaleaks_key"... SUCCESS
Installing software-properties-common
Running: "apt-get -y install software-properties-common"... SUCCESS
Updating GlobaLeaks apt source.list in /etc/apt/sources.list.d/globaleaks.list ...
Running: "apt-get update -y"... SUCCESS
Running: "apt-get install globaleaks -y"... SUCCESS
Install script completed.
GlobaLeaks should be reachable at:
+ http://127.0.0.1
+ http://159.89.139.143
+ http://10.46.0.5
For Professional Support requests please visit: https://www.globaleaks.org/contact/
Please report encountered issues to the Community Forum at https://forum.globaleaks.org
root@debian-c-2-4gib-sfo2-01:~# service globaleaks status
● globaleaks.service - LSB: Start the GlobaLeaks server.
   Loaded: loaded (/etc/init.d/globaleaks; generated)
   Active: active (running) since Sat 2019-10-19 06:25:27 UTC; 4min 51s ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 1 (limit: 4719)
   Memory: 62.4M
   CGroup: /system.slice/globaleaks.service
           └─4512 /usr/bin/python3 /bin/globaleaks --ip=0.0.0.0 --user=globaleaks --group=globaleaks --working-path=/var/globaleaks/

Oct 19 06:25:26 debian-c-2-4gib-sfo2-01 systemd[1]: Starting LSB: Start the GlobaLeaks server....
Oct 19 06:25:27 debian-c-2-4gib-sfo2-01 globaleaks[4479]: Starting GlobaLeaks daemon: globaleaks.
Oct 19 06:25:27 debian-c-2-4gib-sfo2-01 systemd[1]: Started LSB: Start the GlobaLeaks server..
root@debian-c-2-4gib-sfo2-01:~# service globaleaks restart 
root@debian-c-2-4gib-sfo2-01:~# service globaleaks status
● globaleaks.service - LSB: Start the GlobaLeaks server.
   Loaded: loaded (/etc/init.d/globaleaks; generated)
   Active: active (running) since Sat 2019-10-19 06:31:23 UTC; 5s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 4605 ExecStart=/etc/init.d/globaleaks start (code=exited, status=0/SUCCESS)
    Tasks: 1 (limit: 4719)
   Memory: 56.5M
   CGroup: /system.slice/globaleaks.service
           └─4668 /usr/bin/python3 /bin/globaleaks --ip=0.0.0.0 --user=globaleaks --group=globaleaks --working-path=/var/globaleaks/

Oct 19 06:31:22 debian-c-2-4gib-sfo2-01 systemd[1]: Starting LSB: Start the GlobaLeaks server....
Oct 19 06:31:23 debian-c-2-4gib-sfo2-01 globaleaks[4605]: Starting GlobaLeaks daemon: globaleaksEnabling GlobaLeaks Network Sandboxing...done.
Oct 19 06:31:23 debian-c-2-4gib-sfo2-01 globaleaks[4605]: .
Oct 19 06:31:23 debian-c-2-4gib-sfo2-01 systemd[1]: Started LSB: Start the GlobaLeaks server..
root@debian-c-2-4gib-sfo2-01:~# curl -vvv localhost:8082
* Expire in 0 ms for 6 (transfer 0x55e303690f50)
* Expire in 1 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 1 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 1 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 1 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 1 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 1 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 1 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 1 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 2 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
* Expire in 0 ms for 1 (transfer 0x55e303690f50)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55e303690f50)
* Connected to localhost (127.0.0.1) port 8082 (#0)
> GET / HTTP/1.1
> Host: localhost:8082
> User-Agent: curl/7.64.0
> Accept: */*
> 

root@debian-c-2-4gib-sfo2-01:~# netstat -tap
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:http            0.0.0.0:*               LISTEN      4668/python3        
tcp        1      0 localhost:8082          0.0.0.0:*               LISTEN      4668/python3        
tcp        0      0 localhost:8083          0.0.0.0:*               LISTEN      4668/python3        
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN      447/sshd            
tcp        0      0 localhost:9050          0.0.0.0:*               LISTEN      4033/tor            
tcp        0      0 0.0.0.0:https           0.0.0.0:*               LISTEN      4668/python3        
tcp        0      0 159.89.139.143:48290    136.32.240.23:9001      ESTABLISHED 4033/tor            
tcp        0    232 159.89.139.143:ssh      58.69.250.82:37716      ESTABLISHED 463/sshd: root@pts/ 
tcp        0      0 localhost:45136         localhost:8082          FIN_WAIT2   -                   
tcp       79      0 localhost:8082          localhost:45136         CLOSE_WAIT  -                   
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN      447/sshd            
root@debian-c-2-4gib-sfo2-01:~# less /var/globleaks/logs/globaleaks.log
/var/globleaks/logs/globaleaks.log: No such file or directory

**Comment by evilaliv3** [comment]
Thank you @draft1 

Are you able to reach GlobaLeaks from the local ip? From your debugging information it is not clear to me.

Would you please clarify this?

If yes, maybe your vps provider has some firewall enabled by default?

**Comment by draft1** [comment]
What port should I white list?
I guess port 80/443 are not blocked by default on Vultr VPS.

**Comment by draft1** [comment]
Service is running fine.

# service globaleaks status
● globaleaks.service - LSB: Start the GlobaLeaks server.
   Loaded: loaded (/etc/init.d/globaleaks; generated)
   Active: active (running) since Sat 2019-10-19 16:53:20 UTC; 34s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 781 ExecStart=/etc/init.d/globaleaks start (code=exited, status=0/SUCCESS)
    Tasks: 1 (limit: 1108)
   CGroup: /system.slice/globaleaks.service
           └─894 /usr/bin/python3 /usr/bin/globaleaks --ip=0.0.0.0 --user=globaleaks --group=globaleaks --working-path=/var/global

Oct 19 16:53:18 jamii_globaleaks systemd[1]: Starting LSB: Start the GlobaLeaks server....
Oct 19 16:53:19 jamii_globaleaks globaleaks[781]:  * Starting GlobaLeaks daemon globaleaks
Oct 19 16:53:19 jamii_globaleaks globaleaks[781]:  * Enabling GlobaLeaks Network Sandboxing...
Oct 19 16:53:19 jamii_globaleaks globaleaks[781]:    ...done.
Oct 19 16:53:20 jamii_globaleaks globaleaks[781]:    ...done.
Oct 19 16:53:20 jamii_globaleaks systemd[1]: Started LSB: Start the GlobaLeaks server..

**Comment by draft1** [comment]
Curl on localhost failed.

curl -vvv localhost:8082
* Rebuilt URL to: localhost:8082/
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8082 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8082 (#0)
> GET / HTTP/1.1
> Host: localhost:8082
> User-Agent: curl/7.58.0
> Accept: */*
>

**Comment by draft1** [comment]
# netstat -tap
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:http            0.0.0.0:*               LISTEN      1188/python3        
tcp        1      0 localhost:8082          0.0.0.0:*               LISTEN      1188/python3        
tcp        0      0 localhost:8083          0.0.0.0:*               LISTEN      1188/python3        
tcp        0      0 localhost:domain        0.0.0.0:*               LISTEN      658/systemd-resolve 
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN      802/sshd            
tcp        0      0 localhost:9050          0.0.0.0:*               LISTEN      733/tor             
tcp        0      0 0.0.0.0:https           0.0.0.0:*               LISTEN      1188/python3        
tcp        0     36 149.28.132.50.vultr:ssh 58.69.250.82:60108      ESTABLISHED 919/sshd: root@pts/ 
tcp        0      0 149.28.132.50.vul:44332 li306-193.members.:9001 ESTABLISHED 733/tor             
tcp       79      0 localhost:8082          localhost:55256         CLOSE_WAIT  -                   
tcp        0      0 localhost:55256         localhost:8082          FIN_WAIT2   -                   
tcp        0      0 149.28.132.50.vul:49808 93.115.86.6:https       ESTABLISHED 733/tor             
tcp        0      0 149.28.132.50.vul:44334 li306-193.members.:9001 ESTABLISHED 733/tor             
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN      802/sshd

**Comment by draft1** [comment]
Tried on Debian 10 and Ubuntu 18.04, the same issue / Vultr and DigitalOcean.

Thanks!

**Comment by evilaliv3** [comment]
Is it possible that you are completing the platform wizard via Tor?

If you are doing this the platform is automatically set to be reachable only via Tor.

If this is the case you can change this setting by:
- loging in as admin
- going in the Tor settings inside Network Settings
- switching the setting that makes the platform reachable only via Tor

Alternatively reinstall and perform the wizard using a normal browser

**Comment by draft1** [comment]
No, I'm trying to visit the Public IP using a normal browser.
I can't visit the platform via TOR or Normal browser, so I can't proceed :-(.

**Comment by evilaliv3** [comment]
I see, this is actually strange.

Our unit tests in production seems all ok.

Can you try with a Scaleway?

**Comment by evilaliv3** [comment]
Anyway if you could debug the issue a little more, it would be really helpful for the project.

In your current install what do you read in /var/globaleaks/log/globaleaks.log?

thank you!

**Comment by draft1** [comment]
# less /var/globleaks/logs/globaleaks.log
/var/globleaks/logs/globaleaks.log: No such file or directory

Thank you so much!

**Comment by evilaliv3** [comment]
do you have any error in dmesg? e.g. in relation to apparmor.

Its is actually strange that the logfile do not exists.

**Comment by draft1** [comment]
Hm, it works fine on Linode but with very powerful server Specs/CPU.
Maybe this script doesn't work much with low end VPS?

Thanks!

**Comment by evilaliv3** [comment]
Actually it runs on scaleway with the cheapes vps (~3euros a month).

Which were the specs of the platform that you tried to use?

**Comment by draft1** [comment]
$5 and $6 per month on Vultr, $5 per month on DigitalOcean, both not working.
I'll close this ticket now.
Thanks a lot!

**Comment by evilaliv3** [comment]
You are welcome! Please let us know if you find out the reason of the failure
