### ISSUE TITLE
Input Validation Disregarding Regular Expression

### ISSUE THREAD

**Issue by dustin-fci** [globaleaks/GlobaLeaks#2720]
**Current behavior**

In our questionnaire one of the steps requires a custom input of [a-z][a-z][a-z][a-z][0-9][0-9]. This was created using the template "Please enter your organization's login ID.". Currently you can submit a report entering any combination of characters.

**Expected behavior**

You would only be able to submit if your logon ID matched the regex of [a-z][a-z][a-z][a-z][0-9][0-9]. Any other combination would result in a notification that that field is incorrect.

**Steps to reproduce the problem or feature illustration**

On the first step (Login) of any questionnaire enter any combination of characters. You will be able to submit the report without following the required input .

**What is the motivation or use case for changing the behavior?**

This helps to keep the number of unauthorized reports down.

**GlobaLeaks version:**

v3.11.35

**Browser:**

Chrome 77.0.3865.120

**Server Operating System and Version (if applicable):**
 
Ubuntu 18.04.02

**Client Operating System and Version (if applicable):**

Windows 10 Pro

**Comment by evilaliv3** [comment]
thank you for reporting this and feel free to dig in to our ticketing system to comment on everything needed by your project.

I will try to retest this regression by today and emit a patch if possible.

**Comment by evilaliv3** [comment]
Thank you @dustin-fci, i just rechecked on this issue and issued a patch.

Would you pleae try if release 3.11.38 works well for you?

Thank you!

**Comment by dustin-fci** [comment]
Thank you @evilaliv3 this is back working now.

**Comment by dustin-fci** [comment]
This issue has popped up again in version 3.11.42. I updated to 3.11.54 and none of the contexts were showing up, so reverted back to 3.11.42

**Comment by dustin-fci** [comment]
Hey @evilaliv3 , looks like this is an issue again


GlobaLeaks version:

v4.0.49

Browser:

Chrome 83.0.4103.116

Server Operating System and Version (if applicable):

Ubuntu 18.04.02

Client Operating System and Version (if applicable):

Windows 10 Pro

Cheers!

**Comment by evilaliv3** [comment]
Thank you @dustin-fci for reporting this.

Actually i've now identified the issue that was this patch: https://github.com/globaleaks/GlobaLeaks/commit/39532aa991e4c01af3c1803f50e7a4b9f6ab5bbc

Custom and and default validators where implemented differently so that while fixing the functioning of one i impacted the functioning of the other. Let me emit a patch and include it in a new release 4.0.50
