### ISSUE TITLE
Can't update because "The repository 'http://deb.globaleaks.org bionic/ Release' is no longer signed."

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2729]
when updating on Ubuntu 18.04 I get the following output

Hit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:5 http://deb.globaleaks.org bionic/ InRelease
Hit:6 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
Get:7 http://deb.globaleaks.org bionic/ Release [1506 B]
Ign:8 http://deb.globaleaks.org bionic/ Release.gpg
Reading package lists... Done
E: The repository 'http://deb.globaleaks.org bionic/ Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by evilaliv3** [comment]
Thank you for reporting this @elbill 

I've just signed the repository and you could now proceed with the update.

**Comment by elbill** [comment]
Great @evilaliv3 . Thanks
