### ISSUE TITLE
Sticky footer problem persists 

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2733]
Despite being patched sticky footer issue persists on Chrome, windows 10 client on globaleaks version 3.11.41

I had to rollback to an older version to maintain receiver functionality.

**Comment by evilaliv3** [comment]
This is actually very strange @elbill 

Have you tried to clean you cache before retesting?

Are you able to reproduce the issue on try.globaleaks.org and send me a screenshot?

Thank you!

**Comment by elbill** [comment]
Do you mean the browser cache?
try.globaleaks is on version 3.11.39 while the issue was patched on 3.11.40

**Comment by elbill** [comment]
I tried try.globaleaks and the issue did not occur.
I have a modified CSS and have added some text on the footer in the "main configuration" tab in teh footer textbox. This textbox does not appear in the try.globaleaks to be able to recreate

**Comment by evilaliv3** [comment]
@elbill: what is included in your CSS?

I doubt that yoour CSS include a copy of our old CSS and that for this reaoson you are including all the outdated CSS rules.

Just be sure to create a css file with only your rules and try to updote it.

Eventually share it to me if you want me to check it.

**Comment by evilaliv3** [comment]
@elbill: would you please confirm this?

If the error on the sticky footer is related to this we are considering re-adding the code that we originally removed trying to fix it for you as all the recent failure could be caused by you that were including a very old css file.

thank you!

**Comment by evilaliv3** [comment]
@elbill: did you reead my previous messages? thank you!

**Comment by elbill** [comment]
Yes. I'm working on it now and will will come back within the day. thanks

**Comment by elbill** [comment]
@evilaliv3 you were correct. There were some elements of the old css that affected the footer. I attach the new one, quite simple that is working properly. Please check and close the thead. Thanks.
[main3_3.txt](https://github.com/globaleaks/GlobaLeaks/files/3902975/main3_3.txt)

**Comment by evilaliv3** [comment]
great! i'm happy to hear this. Thank you @elbill 

All working fine with version 3.11.42?

**Comment by elbill** [comment]
Just updated the opperational whistleblowing site (I was working on a test installation). No problem with teh footer whatsoever. Everything seems fine. I will run some more tests tommorow. Thanks @evilaliv3
