### ISSUE TITLE
Ricochet tab display also if ricochet address is not configured

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2734]
**Current behavior**
If a whistleblower make a submission on a ricochet enabled platform (es: modelb.disclosers.eu) but ricochet address is not configured, the platform display anyhow a message (that's misleading, in this case) to invite the user to get touch.

**Expected behavior**
If ricochet address is not configured, even if enabled, does not show/display the ricochet tab on the submission workflow/UX.

<img width="891" alt="Screenshot 2019-11-28 at 08 24 47" src="https://user-images.githubusercontent.com/770363/69785774-3429d480-11b9-11ea-8f3e-465ef0074f21.png">

**Comment by evilaliv3** [comment]
Fixed.

As every other situation like this the fix is applied during configuration in order to reduce the runtime overhead so that probably existing platforms will require manual fix disabling the address or configuring the ricochet address.
