### ISSUE TITLE
Content Security Policy - media-src 'self'

### ISSUE THREAD

**Issue by emanuelegreco** [globaleaks/GlobaLeaks#2737]
Our [Globaleaks home page](https://speakup.nadoitalia.it/) has a <video> which is served by the same webserver, but it is blocked by the browser for the Content Security Policy configuration

**Current behavior**

Actually this video isn't showed in the browser. 

The console displays this message "Refused to load media ... because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback"

Globaleaks http header is: “content-security-policy: default-src 'none';script-src 'self';connect-src 'self';style-src 'self';img-src 'self' data:;font-src 'self' data:;frame-ancestors 'none';”

**Expected behavior**

Adding **media-src 'self'** header would allow the display of video in the page.

**Steps to reproduce the problem or feature illustration**
Browse [https://speakup.nadoitalia.it/](https://speakup.nadoitalia.it/)

**What is the motivation or use case for changing the behavior?**
Browsing media served from the same server doesn't represent a security threat.

**GlobaLeaks version:**
Last version available v.3.11.43

**Browser:**
Test made with Chrome  78.0.3904.108, same problem on Firefox and Edge.
Internet Explorer works.

**Comment by evilaliv3** [comment]
Thank you @emanuelegreco for reporting this; i will take care of including your proposal in the next days in the next viable update. 

I really appreciate your feedback and the design of your project that is quire successful; I'm already aware of the project and i've recommended it many times as good for its communicative aspects.

I invite you to join us on slack.hermescenter.org where you can find me and other members of our community.

Thank you!

**Comment by evilaliv3** [comment]
@emanuelegreco: The patch is ready. Would you please test it and confirm if it does work?

This way we could proceed emitting a new release emitting it being sure it works for your project.

**Comment by evilaliv3** [comment]
As agreed with @emanuelegreco, a new release )3.11.45) will be released tomorrow including this patch.

**Comment by evilaliv3** [comment]
Ticket related to: #2534, #2535, #2536

**Comment by evilaliv3** [comment]
@emanuelegreco: I just released the package 3.11.45, when you like feel free to proceed with your tests

**Comment by emanuelegreco** [comment]
Updated to 3.11.45
Problem solved
Great work!
