### ISSUE TITLE
Make it possible for Recipients to configure a Public Name to be shown to whistleblowers

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2739]
**Current behavior**
Actually when a recipient send a message with the "Comment" interface on a Tip, the sender name that's displayed can be:
- The Project Name, for example "RAI - Segnalazioni (whistleblowing)"
- The Name of the recipient

There are organizational situation when the name of the sender has to be represented differently from the two above, for example in this case "Team Segnalazioni", that represent the identity of the group managing the submissions (not the project name, neither the individual user name).

**Expected behavior**
This ticket is to enable a Recipient user to have configured it's own custom public/whistleblower visibile recipient name.

**Comment by evilaliv3** [comment]
@fpietrosanti: https://github.com/globaleaks/GlobaLeaks/issues/2609

Check this. We have already this feature that do now apply just comments but to the whole app.

When enabled the project name is used in place of the recipient name.

**Comment by fpietrosanti** [comment]
@evilaliv3 this feature extend #2609 that's not applicable in this case, because the project name is the "publicly visible on the website" while we are actually referring in this ticket to the "identity of the team managing the submission"

**Comment by evilaliv3** [comment]
@fpietrosanti: we could revise it by decoupling the project name from the alternative name to show implementing something like https://github.com/globaleaks/GlobaLeaks/issues/1642 but at global level.

Would this work?

**Comment by evilaliv3** [comment]
Lets so revert https://github.com/globaleaks/GlobaLeaks/issues/1642 taking this back as a configurable recipient option set by default to the recipient name and then possibly customable.

**Comment by evilaliv3** [comment]
Closing this ticket as the feature was implemented long time ago.
