### ISSUE TITLE
Extend apparmor profile enabling globaleaks to generate a crashdump

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2748]
**Current behavior**
Following ticket #2747 it popup that GlobaLeaks was not able to generate a crashdump:
Dec  9 16:50:48 glpplaaf globaleaks[29537]: PermissionError: [Errno 13] Permission denied: '/var/crash/_usr_bin_globaleaks.0.crash'

**Expected behavior**
This ticket is to enable GlobaLeaks to generate a crash dump in such circumstances

**Comment by evilaliv3** [comment]
Actually this is currently specific only of Ubuntu that uses Apport.

This requires the possibility to write and read files of which globaleaks is owner.

The required priviledge is similar to what we are currently granting globaleaks to write in /tmp that is:
```    owner /var/crash/** rwkl,```

**Comment by evilaliv3** [comment]
Fix applied in release 3.11.48
