### ISSUE TITLE
Change default for outgoing email/smtp notifications to not use Tor, unless submissions are only-Tor

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2751]
**Current behavior**
Actually, by default, email notifications sent via SMTP going trough Tor, leading to spam problems in certain situations.

**Expected behavior**
This ticket is to evaluate change the default settings, not to use Tor, eventually to use Tor by default when submissions are only allowed via Tor.

**Comment by evilaliv3** [comment]
@fpietrosanti: Actually this ticket is referring to a previous implementation.

Current implementation (of november 20) already do exactly what you are telling: 32528c40b0acbf4c0c80d65b429f53c7ff6417ed

I expect that probably the configuration on the EAT project was oudtated as the project started before this setting change.
