### ISSUE TITLE
Site will not redirect from HTTP to HTTPS

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2752]
Sites will not redirect to https. 
for example http://s.fraudline.gr and http://test.s.fraudline.gr will not redirect to https://s.fraudline.gr and https://test.s.fraudline.gr 
I have done a manual ssl configuration obtained trough sslforfree for s.fraudline.gr and *.s.fraudline.gr .
I have exactly the same isue on 2 different sites, installed on different servers that I have managed ssl the same way.
Software version: 3.11.54 on ubunty 18.04lts. The problem persists through various versions.
client various browsers on Windows 10
![SMESEC - Network settings - Google Chrome 17_12_2019 12_56_58 μμ](https://user-images.githubusercontent.com/23246886/70990441-33a49f80-20ce-11ea-9fd2-ada15d0b567c.png)

**Comment by evilaliv3** [comment]
Thank you @elbill 

I'm just rechecking this with Chrome from my phone and all seems to be working correctly.

I'm visiting the two HTTP sites that you mentioned and I'm getting redirected to HTTPS.

Maybe the error is due to some caching in your browser or to some failures in your network?

**Comment by elbill** [comment]
@evilaliv3 I have tried several browsers in various devices on different networks without success. Also during trainings many users can not connect with their mobile device (mostly using chrome on android) unless they type the whole https:// address. 
On the contrast on my test site testme2.try.globaleaks.org redirect works as expected so I assume there is no issue with network or browser.
Can you please try another browser?
this is what I'm getting on edge
![Microsoft Edge 17_12_2019 2_27_51 μμ](https://user-images.githubusercontent.com/23246886/70995522-6dc76e80-20d9-11ea-99c4-b36c09064dae.png)

**Comment by elbill** [comment]
@evilaliv3 I tried with the automatic ssl configuration however I get an internal server error so I can not compare between manual and automatic.

**Comment by evilaliv3** [comment]
@elbill; I just tried again and i confirm your behaviour.

My phone was already trying to connect as https as first option.

From what i see a firewall is blocking the reachability of port 80. would you please verify to have not enabled a firewall rule on your VPS provider interface?

**Comment by elbill** [comment]
@evilaliv3 you were correct. There was no firewall but I had disallowed http access at all thinking  it was not necessary since there was "only" https and I had forgot. Thanks and apologies for your time.
