### ISSUE TITLE
Context cards have disappeared 

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2754]
When upgraded to version 3.11.54 context cards are not visible any more. They are visible only when viewed in list mode
https://testme2.try.globaleaks.org/#/

**Comment by evilaliv3** [comment]
Thank you for reporting this elbil, currently this interface is not under unit texts and it is likely that i introduced a failure in the recent update. Wil lcheck it by today and emit a patched minor release.

**Comment by evilaliv3** [comment]
Fixed @elbill , will be released in few minutes in version 3.11.55

**Comment by evilaliv3** [comment]
@elbill: For more direct communication and for possible collaborations with our users and partners i would like to invite you on our slack: slack.hermescenter.org

**Comment by elbill** [comment]
@evilaliv3 can you send me an invite for vstamatopoulos@gmail.com? Thanks

**Comment by evilaliv3** [comment]
@elbill: actually i see already one account with your email address. try to ask a password reset yourself.
