### ISSUE TITLE
Input Validation Disregarding Regular Expression

### ISSUE THREAD

**Issue by dustin-fci** [globaleaks/GlobaLeaks#2755]
**Current behavior**

In our questionnaire one of the steps requires a custom input of [a-z][a-z][a-z][a-z][0-9][0-9]. This was created using the template "Please enter your organization's login ID.". Currently you can submit a report entering any combination of characters.

This is exactly the same as my previous issue #2720 

I had updated to version 3.11.54. None of the contexts were showing up so I ended up reverting back to 3.11.42

**Expected behavior**

You would only be able to submit if your logon ID matched the regex of [a-z][a-z][a-z][a-z][0-9][0-9]. Any other combination would result in a notification that that field is incorrect.

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

On the first step (Login) of any questionnaire enter any combination of characters. You will be able to submit the report without following the required input.

**GlobaLeaks version:**

v3.11.42

**Browser:**

Chrome 79 and Firefox 71

**Server Operating System and Version (if applicable):**
 
Ubuntu 18.04.02

**Client Operating System and Version (if applicable):**

Windows 10 Pro

**Comment by evilaliv3** [comment]
Thank you @dustin-fci .

The issue with contexts is solved in version 3.11.55

This issue will be solved with 3.11.56.

May I ask you why did you closed the issue to reopen the same issue? Which is the difference?

**Comment by dustin-fci** [comment]
Great Thanks!

I had reopened the original issue from version 3.11.35 and hadn't seen any movement on it. I thought it may had been buried.

**Comment by evilaliv3** [comment]
I see thank you, each ticket is always considered but the project has to prioritize activities covered by a busget. For that time please just update the ticket with eventual new information.

Feel free to open tickets for your needs or feedback for feature requests collected withing your project.

**Comment by evilaliv3** [comment]
Fixed, the patch will be included in release 3.11.55
