### ISSUE TITLE
Preview feature affects width/heigth of Tips inbox

### ISSUE THREAD

**Issue by SylvainFPU** [globaleaks/GlobaLeaks#2759]
**Current behavior**
The preview feature mixes encryption and searchability. In the questionnaire definition you can currently mark some questions as subject to preview. The answers to this question will appear in the tip interface in the column preview and will be as well searchable.

The issue is that if the text preview is long (eg. a multi-line text input) it extracts the preview from the full answers. The layout of the Tips inbox appears to be too wide (height), which is annoying from a UX point of view.

**Expected behavior**
A maximum height for each tips is set, disregarding the amount of text/characters) contained in the Preview column

**Steps to reproduce the problem or feature illustration**
A recipient with several tips (more than 3-4), will have its screen fully set by only two or 3 tips on the inbox interface.

**What is the motivation or use case for changing the behavior?**
UX, practicality.

**GlobaLeaks version:**
Installed version: 3.11.44

**Browser:**
Tor browser on Tails 4.1

**Comment by evilaliv3** [comment]
It should be solved by the current date.

Please feel free to re-open if not and eventually please add a screenshot or a way to reproduce the bug.
