### ISSUE TITLE
GLobaLeaks Backend transifex translation support for default database data

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#276]
The GlobaLeaks Backend by default is populated with a database containing:
- templates for email notifications
- example contexts pre-configured
- example descriptions in fields to be properly configured

Those kind of data (stored into the database) should have support to be internationalized by translating it with transifex.

This ticket is about implementing the support and import/export procedure to/from transifex.

This ticket is related to #6 

Next step is to comment with an idea on how complex it would be and could be done

**Comment by evilaliv3** [comment]
implemented since time!
