### ISSUE TITLE
Globaleaks fail to start: 'OSError' 

### ISSUE THREAD

**Issue by svendber** [globaleaks/GlobaLeaks#2766]
Hi
Hi! 
Trying to run Globaleaks on Debian 10, however it cannot start somehow and I can't find anyone else with the same issue.. 

The installation says it's complete, but fails to start. 

Ouch! The installation is complete but Globaleaks failed to start.

The logs says the following: 

[-] twisted 18.9.0 (/usr/bin/python3 3.7.3) starting up. 
[-] reactor class: twisted.internet.epollreactor.EPollReactor. 
[-] Unable tor start GlobaLeaks: 'OSError' object is not subscriptable 
[-] twisted 18.9.0 (/usr/bin/python3 3.7.3) starting up. 
[-] reactor class: twisted.internet.epollreactor.EPollReactor. 
[-] Unable tor start GlobaLeaks: 'OSError' object is not subscriptable 

What's the issue here? Hope you can help! 

//svendber

**Current behavior**

**Expected behavior**

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

**Browser:**

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
Thank you for reporting this @svendber 

Was this a setup on a fresh new vps or it is a system coming from debian 9?

We experienced this issue in systems that were running python2 before updating to python3.

Have you collected any additional debug info? e.g. it would be helpful if you could share /var/globaleaks/log/globaleaks.log and the dmesg output.

thank you!

**Comment by svendber** [comment]
Hi @evilaliv3 
Thank you for fast replay! 

It's on a fresh new Debian 10.2 as far as I know. I'll try to test the installation on another computer later tonight..

It was the full log I posted earlier. Below is the full installation and log. Is there anything else that I can give you? 

./install-globaleaks.sh
Running the GlobaLeaks installation...
In case of failure please report encountered issues to the ticketing system at: https://github.com/globaleaks/GlobaLeaks/issues

Detected OS: Debian - buster
Running: "/etc/init.d/globaleaks stop"... SUCCESS
Running: "apt-get -y update"... SUCCESS
 + curl requirement met
 + netstat requirement met
Running: "is_tcp_sock_free_check 0.0.0.0:80"... SUCCESS
Running: "is_tcp_sock_free_check 0.0.0.0:443"... SUCCESS
Running: "is_tcp_sock_free_check 127.0.0.1:8082"... SUCCESS
Running: "is_tcp_sock_free_check 127.0.0.1:8083"... SUCCESS
 + required TCP sockets open
Adding GlobaLeaks PGP key to trusted APT keys
Running: "apt-key add /tmp/tmp.kW5LUFmmWB/globaleaks_key"... SUCCESS
Running: "rm /tmp/tmp.kW5LUFmmWB/globaleaks_key"... SUCCESS
Installing software-properties-common
Running: "apt-get -y install software-properties-common"... SUCCESS
Updating GlobaLeaks apt source.list in /etc/apt/sources.list.d/globaleaks.list ...
Running: "apt-get update -y"... SUCCESS
Running: "apt-get install globaleaks -y"... SUCCESS
Ouch! The installation is complete but GlobaLeaks failed to start.

--- LOG --- 

cat /var/globaleaks/log/globaleaks.log
2020-02-03 08:53:47+0000 [-] twistd 18.9.0 (/usr/bin/python3 3.7.3) starting up.
2020-02-03 08:53:47+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2020-02-03 08:53:47+0000 [-] Unable to start GlobaLeaks: 'OSError' object is not subscriptable
2020-02-03 08:59:39+0000 [-] twistd 18.9.0 (/usr/bin/python3 3.7.3) starting up.
2020-02-03 08:59:39+0000 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2020-02-03 08:59:39+0000 [-] Unable to start GlobaLeaks: 'OSError' object is not subscriptable

**Comment by svendber** [comment]
Hi @evilaliv3 
I got it to work! Not really sure what the issue was.. 

I do however have a follow up question. I'm finding it hard to setup tor2web correctly with GlobaLeaks. As for now, I've got the proxy with apache to work and can remotely access my server, which shows the onion logo.. 
I'm not sure how to go further from here, but I do think that it might be the Hidden Services and Tor itself, that I'm missing to implement.. Would you mind assist me on that? See the following website https://github.com/hellais/GlobaLeaks/wiki/Globaleaks-installation 

It seems abit outdated for some of it, but is that the correct approach regarding the Hidden Services? 

Ty in advance! 

//Svendber9

**Comment by Kotegaeshi** [comment]
Hi!
I have the same problem. 
It is on a fresh Ubuntu 18.04.4 LTS‬ (VPS)
And the same error.....Unable to start GlobaLeaks: 'OSError' object is not subscriptable
Any suggestion?

**Comment by evilaliv3** [comment]
@Kotegaeshi: On which provider? This is so strange. Which version of python is installed on the system?

**Comment by Kotegaeshi** [comment]
Python 2.7.17
And provider: strato

**Comment by evilaliv3** [comment]
@Kotegaeshi : i suspected this actually. Ubuntu 18.04 comes with python3.

Please ask to the provider why your system is running python2, as this is the problem.

I hope this helps.

**Comment by Kotegaeshi** [comment]
Hi again,
Sorry python 2.7 an 3, I try to install again and I have it !!!!
Now ...I got it installed and running... but i can't reach port 8082.....

● globaleaks.service - LSB: Start the GlobaLeaks server.
   Loaded: loaded (/etc/init.d/globaleaks; generated)
   Active: active (running) since Tue 2020-03-10 00:19:23 CET; 7s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 23535 ExecStop=/etc/init.d/globaleaks stop (code=exited, status=0/SUCCESS)
  Process: 25161 ExecStart=/etc/init.d/globaleaks start (code=exited, status=0/SUCCESS)
    Tasks: 5 (limit: 105)
   CGroup: /system.slice/globaleaks.service
           └─25196 /usr/bin/python3 /usr/bin/globaleaks --ip=0.0.0.0 --user=globaleaks --group=globaleaks --working-path=/var/globaleaks/

......

**Comment by evilaliv3** [comment]
@svendber: The port 8082 should be reachable locally on 127.0.0.1 while from the outside should be reachable on the port 80/443.

**Comment by Kotegaeshi** [comment]
Hello Again,
But If I load in port 80, I get the plesk web page.  Not globaleaks...
How can I change this port?
Thank you very much!

**Comment by Kotegaeshi** [comment]
I attach some info from log.... when I start the service......
 twistd 17.9.0 (/usr/bin/python3 3.6.9) starting up.
2020-03-10 12:29:27+0100 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2020-03-10 12:29:27+0100 [-] [E] Could not reserve socket for 98 (error: Address already in use)
2020-03-10 12:29:27+0100 [-] [E] Could not reserve socket for 98 (error: Address already in use)
2020-03-10 12:29:30+0100 [-] [E] Found an already initialized database version: 52
2020-03-10 12:29:30+0100 [-] Starting factory <Site object at 0x7f1c7da462b0>
2020-03-10 12:29:30+0100 [-] GlobaLeaks is now running and accessible at the following urls:
2020-03-10 12:29:30+0100 [-] - [HTTP]   --> http://0.0.0.0
2020-03-10 12:29:30+0100 [-] - [Tor]:   --> http://2r3xbrq4a7sefibtytg3sd66u2qar6njao3bmuwvnk475u7bawiibtqd.onion
2020-03-10 12:29:31+0100 [-] [E] Successfully connected to Tor control port

**Comment by evilaliv3** [comment]
@Kotegaeshi: GlobaLeaks is designed to work on port 80 and 443 and the port is currently not configurable. The requirement for port 80 and 443 is necessary due to the integration with LetsEncrypt

**Comment by Kotegaeshi** [comment]
Hello!
Ok, there is no problem to work with port 80, but I can not load globaleaks in port 80. I get plesk page. I don't know if it is right!
Is there any other option to access to login page?
Thank you very much!

**Comment by Kotegaeshi** [comment]
What is the url login page? the IP:80, ...81.169.X.X:80 ? is right?

**Comment by Kotegaeshi** [comment]
Evilaliv3: I do a new install of Ubuntu 18.04 without plesk, and we have Globaleaks running. 
Thank you very much for your help!

**Comment by evilaliv3** [comment]
You are welcome, thank you for the update.

**Comment by ximo99** [comment]
Hello good morning,

First of all, thank you very much for your work. I have a problem with the Globaleaks installation. He says "The installation is complete but GlobaLeaks failed to start". I add photographs where you can verify the error, that I have Python3 installed and that the browser says "unable to connect". I use an Ubuntu 20.04.1 LTS virtual machine.

Thank you very much in advance,
greetings.

![Captura de pantalla 2023-11-27 115907](https://github.com/globaleaks/GlobaLeaks/assets/125189091/68717719-0918-4784-9e7a-fade12d9de74)
![Captura de pantalla 2023-11-27 115925](https://github.com/globaleaks/GlobaLeaks/assets/125189091/4c240982-fc97-446f-831f-cff3cbf5e9c3)
![Captura de pantalla 2023-11-27 120438](https://github.com/globaleaks/GlobaLeaks/assets/125189091/c3349514-12e9-47fd-896c-a95c2d6d1350)

**Comment by ximo99** [comment]
Hello again,

I have already solved the error. This was a bug with the installation of Tow Browser. Again, thank you very much for your work.

Greetings.
