### ISSUE TITLE
Attachment URL not changing for different languages

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2773]
Not sure this is a new feature or bug!
I expected the attachment type of question url to have the possibility to be different for different languages.
The same way that the text label can be different. The context is that different langauages can have different translations of their whistleblowing or other policies.

**Current behavior**

So now the document url is the same for all languages.

I would expect to be able to have diferent attachments for differet languages.

Software version: 3.11.69 on Ubuntu 18.04

**Expected behavior**

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

**Browser:**

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
@elbill, this has already been implemented in https://github.com/globaleaks/GlobaLeaks/commit/ee5e3e110bbaebf2d692eaf569e0e3938041ca15 and will be released at the end of the month with GlobaLeaks version 4

**Comment by elbill** [comment]
Great. Thanks @evilaliv3 !
