### ISSUE TITLE
PAM 2 more autentification failure

### ISSUE THREAD

**Issue by yohohoro** [globaleaks/GlobaLeaks#2777]
journalctl -xe
PAM 2 more autentification failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=22.186.15.166 user=root

**Comment by evilaliv3** [comment]
Thank you @yohohoro! Would you please clarify about this ticket and what you would like to report?

**Comment by yohohoro** [comment]
ok. see screenshot.
https://cdn1.savepice.ru/uploads/2020/2/26/554373054048881fd2374765af1e243a-full.png

**Comment by evilaliv3** [comment]
@yohohoro: i'm sorry this is not the repository of Tor2web.

In case you need assistance please open the ticket on the respective repository.
