### ISSUE TITLE
Users default password

### ISSUE THREAD

**Issue by Cainor** [globaleaks/GlobaLeaks#2782]
This is not a bug, however a security concern.

In "backend\globaleaks\handlers\admin\user.py" the method "db_create_user" on line number 54:

```python
    password = 'password'
    if request['password']:
        password = request['password']
```

For some reason, if password was not inputted by the user, then a weak password will be assigned to them.

I think the better way of handling this is to either refuse to continue the method of "request['password']" was not provided. Or at least, put a key word "CHANGE_ME" so that developers can change the default password to the one they desired.

What do you think?

**Comment by evilaliv3** [comment]
Thank you for the feedback @Cainor but actually i think you may be looking to an outdated version of the software. Your feedback is correct and the softare already implements your recomendations.

Which software version are you running?

**Comment by Cainor** [comment]
You are correct. two weeks ago I cloned this project and started to review the source code. I haven't noticed that this issue was resolved.

Thank you.

**Comment by evilaliv3** [comment]
Thank you @Cainor.

Do you have any other finding that you would like to share? Is your audit going to be published?
We would be interested in publishing it here for the valuae of the project: https://www.globaleaks.org/docs/en/penetration-tests.pdf

please let me know, thank you!

**Comment by Cainor** [comment]
I don't have other findings, yet. Can't assure you if I'll be able to publish my audit or not. 
Happy to help the open source community :)
