### ISSUE TITLE
User Enumeration

### ISSUE THREAD

**Issue by HashimAlsharref** [globaleaks/GlobaLeaks#2784]
**Current behavior**

the Attacker can use the forget password by sending the request and show to the attacker in the response different massage if the user is exists or not

Message on the response when the user is exists : 

{"redirect":"/login/passwordreset/requested"}

No Message on the response when the user is not exists : 

**Expected behavior**

Same Message for if the user is exists or not

**Comment by evilaliv3** [comment]
Thank you for your feedback @HashimAlsharref, but i think that what you are reporting is not correct.

The system in fact already implement the policy that you are mentioning and always answer "Password reset requested. Please check your inbox for further instructions." regardless if the user exists or not.

would you please recheck?

**Comment by evilaliv3** [comment]
@HashimAlsharref ?

**Comment by HashimAlsharref** [comment]
Dears 

the message its become on the response of the Burp-Suite tool 

and for my application  my users is : 
1- admin 

i recommended to test it from your side :+1:  
anyway this is a screenshot for the Enumeration : 


Here the test user is not found : 
![not-find-user](https://user-images.githubusercontent.com/62054784/76701274-de7a2900-66d0-11ea-992c-c0c03051af5e.png)

and Here we can see the massage for the admin user from the response that show its redirect 
"{"redirect":"/login/passwordreset/requested"}" 

![user-find](https://user-images.githubusercontent.com/62054784/76701319-42045680-66d1-11ea-8f8e-b1fb8c764a25.png)

**its mean that user admin is exists** 

Regards. 
Hashim Alshareef.

**Comment by evilaliv3** [comment]
After rechecking on the issue it seems that this issue was not present on the version published at the time of the issue reporting. I've anyhow improved the code in relation to a similar possible error on the admin interface.
