### ISSUE TITLE
Installation script outputs error "GPG error: https://deb.globaleaks.org bionic/ Release: The following signatures were invalid"

### ISSUE THREAD

**Issue by linen101** [globaleaks/GlobaLeaks#2786]
Today I tried to install Globaleaks on vps (Ubuntu 18.04) following the installation guide from the official documentation and I got this:

Detected OS: Ubuntu - bionic
WARNING: GlobaLeaks is actively developed and tested specifically for Debian 10 (Buster)
WARNING: The software lifecycle of the platform includes full support for all Debian and Ubuntu LTS versions starting from Debian 9 Ubuntu 16.04
Do you wish to continue anyway? [y|n]?y
Running: "apt-get -y update"... SUCCESS
 - curl requirement not met. Installing curl
Running: "apt-get -y install curl"... SUCCESS
 + netstat requirement met
Running: "is_tcp_sock_free_check 0.0.0.0:80"... SUCCESS
Running: "is_tcp_sock_free_check 0.0.0.0:443"... SUCCESS
Running: "is_tcp_sock_free_check 127.0.0.1:8082"... SUCCESS
Running: "is_tcp_sock_free_check 127.0.0.1:8083"... SUCCESS
 + required TCP sockets open
Adding GlobaLeaks PGP key to trusted APT keys
Running: "apt-key add /tmp/tmp.BsNjNxeF9O/globaleaks_key"... SUCCESS
Running: "rm /tmp/tmp.BsNjNxeF9O/globaleaks_key"... SUCCESS
Installing software-properties-common
Running: "apt-get -y install software-properties-common"... SUCCESS
Updating GlobaLeaks apt source.list in /etc/apt/sources.list.d/globaleaks.list ...
Running: "apt-get update -y"... FAIL
Ouch! The installation failed.
COMBINED STDOUT/STDERR OUTPUT OF FAILED COMMAND:
Hit:1 http://mirror.transip.net/ubuntu/ubuntu bionic InRelease
Hit:2 http://mirror.transip.net/ubuntu/ubuntu bionic-updates InRelease
Hit:3 http://mirror.transip.net/ubuntu/ubuntu bionic-backports InRelease
Get:4 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Ign:5 https://deb.globaleaks.org bionic/ InRelease
Get:6 https://deb.globaleaks.org bionic/ Release [744 B]
Get:7 https://deb.globaleaks.org bionic/ Release.gpg [833 B]
Hit:8 http://software.virtualmin.com/vm/6/gpl/apt virtualmin-bionic InRelease
Hit:9 http://software.virtualmin.com/vm/6/gpl/apt virtualmin-universal InRelease
Ign:7 https://deb.globaleaks.org bionic/ Release.gpg
Reading package lists...
W: GPG error: https://deb.globaleaks.org bionic/ Release: The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
E: The repository 'http://deb.globaleaks.org bionic/ Release' is not signed.

Globaleaks version: ?

Server Operating System and Version (if applicable): Ubuntu 18.04

(The weird thing is that I followed the same instructions for my desktop and the installation was succesfull on VM with ubuntu 18.04)

**Comment by larrykind** [comment]
Same here

**Comment by evilaliv3** [comment]
Thank you for reporting this @linen101 and @larrykind.

The issue should be solved now for release 4.0.3.

**Comment by larrykind** [comment]
-e Running the GlobaLeaks installation...
In case of failure please report encountered issues to the ticketing system at: https://github.com/globaleaks/GlobaLeaks/issues

./install-globaleaks.sh: 11: ./install-globaleaks.sh: Syntax error: "(" unexpected

**Comment by evilaliv3** [comment]
@larrykind on which system are you running the install ? 

I'm currently not able to reproduce your bug, would you please fy distrubution/version/provider and which exact command are you running ? thank you!

**Comment by larrykind** [comment]
![syntax](https://user-images.githubusercontent.com/61267901/76617459-9d461580-6526-11ea-8374-4df170be7032.png)

**Comment by evilaliv3** [comment]
Thank you @larrykind 

Actually i see thay you are running the script via 'sh'; use bash instead or just write ./install-globaleaks.sh and your issue will be solved.

P.s.: Please next time use different tickets for different errors.

**Comment by linen101** [comment]
Installation was successful, thank you @evilaliv3 !
