### ISSUE TITLE
I can't access Globaleaks after installation "Forbidden  You don't have permission to access this resource."

### ISSUE THREAD

**Issue by linen101** [globaleaks/GlobaLeaks#2787]
Hello again,

I installed globaleaks on ubuntu 18.04 LTS VPS and after that I tried to connect to it through my Dedicated IP but I got Error 403 Forbidden.

Expected behavior: Platform wizard opens on firefox

GlobaLeaks version: 4.0.3

Browser: Mozilla Firefox

Server Operating System and Version (if applicable): Ubuntu 18.04 LTS
Control Panel: Virtualmin (with LAMP)

I tried also the following:

service globaleaks status
● globaleaks.service - LSB: Start the GlobaLeaks server.
   Loaded: loaded (/etc/init.d/globaleaks; generated)
   Active: active (running) since Fri 2020-03-13 12:49:14 CET; 22min ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 6 (limit: 4661)
   CGroup: /system.slice/globaleaks.service
           └─3137 /usr/bin/python3 /usr/bin/globaleaks --ip=0.0.0.0 --user=globaleaks --group=globaleaks --working-path=/var/glob

Mar 13 12:49:12 server.lalala.com systemd[1]: Starting LSB: Start the GlobaLeaks server....
Mar 13 12:49:12 server.lalala.com globaleaks[3098]:  * Starting GlobaLeaks daemon globaleaks
Mar 13 12:49:14 server.lalala.com globaleaks[3098]:    ...done.
Mar 13 12:49:14 server.lalala.com systemd[1]: Started LSB: Start the GlobaLeaks server..

curl -vvv localhost:8082
* Rebuilt URL to: localhost:8082/
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8082 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8082 (#0)
> GET / HTTP/1.1
> Host: localhost:8082
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Server: Globaleaks
< Date: Fri, 13 Mar 2020 12:11:53 GMT
< Content-Security-Policy: default-src 'none';script-src 'self';connect-src 'self';style-src 'self';img-src 'self' data:;font-src 'self' data:;media-src 'self';frame-ancestors 'none';
< X-Frame-Options: deny
< Feature-Policy: camera 'none';display-capture 'none';document-domain 'none';fullscreen 'none';geolocation 'none';microphone 'none';speaker 'none';
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, must-revalidate
< Pragma: no-cache
< Expires: -1
< Referrer-Policy: no-referrer
< X-Check-Tor: False
< Content-Language: en
< Content-Encoding: gzip
< Content-Type: text/html
< 

[curl-port-443.txt](https://github.com/globaleaks/GlobaLeaks/files/4329585/curl-port-443.txt)

[globaleaks.log](https://github.com/globaleaks/GlobaLeaks/files/4329589/globaleaks.log)

I am wondering.. Is that a problem of the platform, of my VPS provider, or have I messed up with configuration?

**Comment by fpietrosanti** [comment]
It's the same problem we already had due to TCP ports already used by other process:
2020-03-13 12:49:14+0100 [-] [E] Could not reserve socket for 98 (error: Address already in use)
2020-03-13 12:49:14+0100 [-] [E] Could not reserve socket for 98 (error: Address already in use)

We need to enforce checking that those TCP ports are not used, preventing starting GlobaLeaks, providing an error to the console to let you know how to fix the problem.

**Comment by linen101** [comment]
Okk, so I'm waiting :)
Another question is.. Isn't it weird that I can establish connection through port 443 but not through 80?

**Comment by linen101** [comment]
Okk, so I 'm waiting :)

**Comment by evilaliv3** [comment]
@linen101: Actually the patch of which @fpietrosanti will help user identifying which is the reason of the failure but wont solve automatically the problem.

This is to say that you do not need to wait for this patch but you could just stop the service that is using the ports 80 and 443; maybe you installed apache or nginx?

**Comment by linen101** [comment]
Yes, I installed virtualmin which uses LAMP

**Comment by linen101** [comment]
Yes, I installed virtualmin which uses LAMP

**Comment by evilaliv3** [comment]
@linen101: Actually this is not supported. The GlobaLeaks server is expected to run just GlobaLeaks and eventually backup routines. Which is the use case of virtualmin here?

**Comment by linen101** [comment]
I intended to make the server more user friendly (configuration, etc)
*Sorry for not replying sooner, i was away for the weekend

**Comment by linen101** [comment]
removed virtualmin and still didnt work so I reinstalled OS and now I see again the same error as before  https://github.com/globaleaks/GlobaLeaks/issues/2786

**Comment by linen101** [comment]
Now fixed
