### ISSUE TITLE
Deleting a tenant website not possible in recent update

### ISSUE THREAD

**Issue by webconexus** [globaleaks/GlobaLeaks#2788]
See the attached video, deleting tenant instances does not seem to work. I tried it with an empty cache as well.

https://drive.google.com/file/d/1pGCS1HmOSJXo-45ttKIwlQU_3FJD7TS1/view?usp=sharing

**GlobaLeaks version:**
4.0.2

**Browser:**
Chrome

**Comment by evilaliv3** [comment]
Fixed, thank you @webconexus for reporting this.

The patch will be included starting from release 4.0.4
