### ISSUE TITLE
Small UI bug when having multiple lines of custom translations

### ISSUE THREAD

**Issue by webconexus** [globaleaks/GlobaLeaks#2789]
![ui-bug](https://user-images.githubusercontent.com/217034/76704953-bf819400-66dc-11ea-93c4-9537b39d7cc6.png)

**GlobaLeaks version:**
4.0.2

**Comment by evilaliv3** [comment]
Thank you @webconexus, would you please clarify with a description what you perceive as a bug here?

(p.s. please when loading images or other files on github use directly the github functionality to reduce risks for other users opening externali links. thank you)

**Comment by evilaliv3** [comment]
@webconexus: I tried to replicate the issue but i still cannot do it.

Whould you please try to do it yourself and explain me better?

**Comment by webconexus** [comment]
Hi @evilaliv3 sorry for the delayed answer. I tried this on a clean install and I also can not seem to reproduce this issue. It is only occuring on a client website that is already running. Can this be a CSS issue because of custom styling?

**Comment by evilaliv3** [comment]
Yep i think this could be possible @webconexus

**Comment by webconexus** [comment]
Im closing this issue then.
