### ISSUE TITLE
Invalid package reference in setup_development_environment.sh

### ISSUE THREAD

**Issue by gianlucagilardi** [globaleaks/GlobaLeaks#2790]
**Current behavior**

in setup_development_environment.sh reference to libopenssl-dev under Buster returns error

**Expected behavior**

 no error in package installation

**Steps to reproduce the problem or feature illustration**

Under Buster simply run the script

**What is the motivation or use case for changing the behavior?**

bug fixing 

replacing libopenssl-dev with libssl-dev fixes the issue

**Comment by evilaliv3** [comment]
Thank you for reporting this @gianlucagilardi; I now wonder if the package was really necessary and why it was currently working. Was the setup proceeding anyhow?
