### ISSUE TITLE
Missing wiki page to explain Continuous Integration and Unit-Testing

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#280]
Write a wiki page in the Release Procedure to explain:
- Continuous Integration
- Unit-Testing

how we are using it with external links and procedures.

This should be useful for a developer approaching globaleaks and willing to understand how to get engaged / properly code with us.
##

**Comment by evilaliv3** [comment]
This is documented by: https://github.com/globaleaks/GlobaLeaks/wiki#wiki-unit-testing
