### ISSUE TITLE
Package GlobaLeaks for USB Armory

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#2803]
**Current behavior**
This ticket is to package GlobaLeaks to run on a USB Armory secured device with no effort, to run the software self-hosted at home or office https://inversepath.com/usbarmory.html

**Comment by evilaliv3** [comment]
@fpietrosanti i'm waiting for the support for Debian Buster (10) in order to actually start working on this.

@abarisani: do you know if there is any existing effort to support this? thank you!

**Comment by abarisani** [comment]
We are working on it.

**Comment by abarisani** [comment]
There you go:

https://github.com/f-secure-foundry/usbarmory-debian-base_image/releases/tag/20200406

**Comment by abarisani** [comment]
Please check this [updated release](https://github.com/f-secure-foundry/usbarmory-debian-base_image/releases/tag/20200408) to address this [issue](https://github.com/f-secure-foundry/usbarmory-debian-base_image/issues/30)

**Comment by evilaliv3** [comment]
With this simple revision to the official packaging for debian i've been able to successfully run globaleaks on the MKII: https://github.com/globaleaks/globaleaks-usbarmory-image/commit/175a8516251b4387416a6b32cf78ef1d9b3ce60a

I'm preparing a repository and a release to offer other volurneers the possibility to experiment with it.

@abarisani: All seems to be working fine except that i find it more slow of what i would have expected (the system, not globaleaks). Do you see any major optimization that could be done? 

The RAM occupancy is 50% (256 mb)

I've removed currently some unused support that actually have binaries actively running (like iw and wpasupplicant) that in the context of globaleaks just raise the attack surface.

**Comment by abarisani** [comment]
It is difficult to me to assess your speed expectations. Overall Python is not a great performer on embedded systems in terms of memory footprint and I/O.

Performance using the eMMC (vs the uSD) should improve concerning file access.

For any other performance consideration you have to evaluate if your bottleneck is the CPU, disk or memory.

**Comment by evilaliv3** [comment]
Thank you @abarisani for thefast feedback! Really appreciated!

Actually mine was a small feedback in general; it seems all to work all really great!

I discovered i was building an image for the imx6ulz while the board i'm testing on is a imx6ul.

I suggest that we you could could be probably work on retesting it to release and document a version of Debian for all both the MKII platforms and as well for the MKI. This would help users to experiment and before producing their own image. I will try to provide my feedback and support for the retesting on your official repository.

**Comment by evilaliv3** [comment]
Packaging implemented and released on dedicated repository: https://github.com/globaleaks/globaleaks-usbarmory-image

Image published on: https://github.com/f-secure-foundry/usbarmory/wiki/Available-images

**Comment by evilaliv3** [comment]
Reopening this since it would be interesting to update the packaging made long time ago issuing a new release based on current Debian and featuring Globaleaks 5
