### ISSUE TITLE
Make the automatic e-mail that an user gets after an admin adds them, configurable

### ISSUE THREAD

**Issue by webconexus** [globaleaks/GlobaLeaks#2806]
As previously talked about with @evilaliv3 , it would be nice if the admin is able to configure the automatic e-mail a user gets after an admin succesfully ads a user.

That is the following e-mail:

![email](https://user-images.githubusercontent.com/46351981/78533535-67c0df00-77e9-11ea-8c99-4b60cba7acbf.png)

**Comment by evilaliv3** [comment]
@webconexus: This has been actually already implementedand has been relkeased since release 4.0.6.

Would you please retest updating to the latest version?

**Comment by webconexus** [comment]
@evilaliv3 Oh sorry, I see it now after the update. I was watching the changelog but it did not appear in there explicitly. Thankyou though!
