### ISSUE TITLE
Assigned report labels are not visible 

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2809]
**Current behavior**

Assigned report labels are not visible in list view.
This is a new report (not migrated from previous versions) and there is only one recipient.
update: Label is visible when private label feature is enabled

**Client Operating System and Version (if applicable):**

version 4.07 & 4.08 on ubuntu 18.04lst. Client chrome on windows 10 (both updated)

![Globaleaks - Google Chrome 7_4_2020 2_37_46 μμ](https://user-images.githubusercontent.com/23246886/78665506-97054800-78de-11ea-87de-0922cb839b12.png)
![Globaleaks - Google Chrome 7_4_2020 2_39_20 μμ](https://user-images.githubusercontent.com/23246886/78665510-98cf0b80-78de-11ea-8b2a-eef1e892899b.png)

**Expected behavior**

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

**Browser:**

**Server Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
Thank you @elbill, this is actually an issue that has been already been reported and fixed: https://github.com/globaleaks/GlobaLeaks/issues/2800

I will issue by today a new release for this.
