### ISSUE TITLE
Give a whistleblower the option to reload the report page

### ISSUE THREAD

**Issue by E2RD0** [globaleaks/GlobaLeaks#2812]
**Current behavior**

In order for the user to view the newest comments and private messages on a report, he has to reload the page and reenter the receipt.

**Expected behavior**

Give a whistleblower the option to reload the report page by putting a button similar to the one recipients have, or make comments and private messages work in real time.

**What is the motivation or use case for changing the behavior?**

Make the submission review process for a whistleblower, easier and more intuitive.

**GlobaLeaks version:**
4.0.9

**Comment by evilaliv3** [comment]
Thank you for the valuable suggestion @E2RD0.

Actually sooner or later we will implement automatic update of messages upon arrival but let me add the button in the meantime.

**Comment by evilaliv3** [comment]
Here a screenshot of the current implementation to be included in release 4.0.10:

![Screenshot_2020-04-09 Report](https://user-images.githubusercontent.com/217034/78865163-68ea4a00-7a3d-11ea-91ed-ac9277e9d6e2.png)
