### ISSUE TITLE
Recipient's name on private messages

### ISSUE THREAD

**Issue by E2RD0** [globaleaks/GlobaLeaks#2815]
**Current behavior**

Private messages on the report page sent by the whistleblower, do not show which recipient was sent to.

**Expected behavior**

The messages should have a label showing the recipient's name.

**What is the motivation or use case for changing the behavior?**

The whistleblower might forget to whom he sent a private message, so putting the recipient's name could be helpful.

For example:
![Example](https://imgur.com/Bu5kGP7.png)

Here the whistleblower cannot distinguish to which recipient he sent each message.

**GlobaLeaks version:**
 v4.0.12

**Comment by evilaliv3** [comment]
Thank you for reporting this @E2RD0 

This should be actually a regression; The interface is originally designed only to show messages with the currently selected recipient. Let me check it.

**Comment by evilaliv3** [comment]
Would this interface work for you @E2RD0 ? What do you think?

From whistleblower side:
![Screenshot_2020-04-12 Report](https://user-images.githubusercontent.com/217034/79066009-c89e5a80-7cb4-11ea-94b1-e9ee2965058e.png)

From recipient side:
![Screenshot_2020-04-12 Globaleaks](https://user-images.githubusercontent.com/217034/79066007-c4723d00-7cb4-11ea-9124-fe3ed92d7307.png)

**Comment by evilaliv3** [comment]
Implemented and released in package version 4.0.13
