### ISSUE TITLE
Recipient list doesn't show recipients in report page

### ISSUE THREAD

**Issue by E2RD0** [globaleaks/GlobaLeaks#2818]
**Current behavior**

In the report page, either for the whistleblower or the recipient, the recipient list shows nothing
![](https://imgur.com/14W4yx4.png)

**Expected behavior**

Recipient list should show the recipients of a given submission.

**GlobaLeaks version:**
 v4.0.13

**Comment by evilaliv3** [comment]
Thank you for notifying this @E2RD0.

I've produced a patch and i'm going to include this in 4.0.14.
