### ISSUE TITLE
Attachments from mobile device

### ISSUE THREAD

**Issue by dustin-fci** [globaleaks/GlobaLeaks#2819]
**Current behavior**

Currently unable to add attachments from a mobile device. I have tested .txt and .m4a. On the submission form it shows that the file was uploaded successfully. Checking this from mobile and on PC shows no attachment. I have tried regular and incognito mode.

**Expected behavior**

Files is attached from a mobile device.

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

This would allow users to attach any file through a mobile device. We are primarily trying to get an audio recording attached.

**GlobaLeaks version:**

4.0.5

**Browser:**

Chrome 80.0.3987.162

**Server Operating System and Version (if applicable):**
 
Ubuntu 18.04.2

**Client Operating System and Version (if applicable):**

Android 10

**Comment by evilaliv3** [comment]
Thank you for reporting this @dustin-fci,  we will check on the issue and let you know

**Comment by evilaliv3** [comment]
Dear @dustin-fci , i just retried and it worked for me. Would you please retry?

**Comment by dustin-fci** [comment]
Hi @evilaliv3 , I updated to the latest version last night and still was unable to upload from my mobile.

**Comment by evilaliv3** [comment]
@dustin-fci: Is the server public? May i try with my mobile to connect to it?

**Comment by dustin-fci** [comment]
I did not see anything in the log. The server is public however one of the questions requires specific criteria. I can send you the info in an email if you would like. I will put mine in my bio for the time being.

**Comment by evilaliv3** [comment]
@dustin-fci:feel free to reach me and my team at https://slack.globaleaks.org

**Comment by evilaliv3** [comment]
@dustin-fci: Is it possible that you where testing on a setup without HTTPS?

**Comment by dustin-fci** [comment]
@evilaliv3 This was on an https connection. I have just tested again with the same result.

**Comment by evilaliv3** [comment]
Thank you for the update. Would you please update to 4.0.30 and see if the
issue is still present?

If you could pass me the link i will try to test it by myself.

**Comment by evilaliv3** [comment]
Closing as probably outdated.
