### ISSUE TITLE
Can not update from v 4.0.12 to 4.0.14

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2820]
**Current behavior**
when using apt-get update from root i get teh following message

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://deb.globaleaks.org bionic/ Release: The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Failed to fetch http://deb.globaleaks.org/bionic/Release.gpg  The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Expected behavior**
I woild expect to download repository and be able to install

**Steps to reproduce the problem or feature illustration**
root@XXXXX:~# apt-get update

**GlobaLeaks version:**
4.0.12

**Server Operating System and Version (if applicable):**
 Ubuntu(18.04)

**Comment by evilaliv3** [comment]
Thank you for notifying this @elbill, you can now proceed updating.

**Comment by elbill** [comment]
@evilaliv3 
could not update
globaleaks is already the newest version (4.0.12)
can you please check?

**Comment by evilaliv3** [comment]
@elbill: Would you please retry with: ```apt-get update && apt-get install globaleaks```

I've in fact verified updating many production setups and i did not encounter any failure.

Thank you!
