### ISSUE TITLE
Make it possible to enable some recipients to have immediate access to the whistleblower identity

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2821]
A feature that could be useful would be to have  an option in the recipient set up to authorise them to have access to identification information by default and not have to ask access by custodian. An example would be that the HR would have access while the second recipient should not. Having a custodian role introduces an additional step and a role that often may not be necessary.

**Comment by evilaliv3** [comment]
Thank you for the valuable feedback @elbill . This is actually pretty interesting.

**Comment by evilaliv3** [comment]
This has been recently implemented with a small difference with what originally described in the ticket.

In the current implementation, if the whistleblower provides the identity and no custodian user is present on the system, every recipient will be able to access the identity by clicking a "View" button. Access to the identity is logged by the system.
