### ISSUE TITLE
Identity shows as undeclared

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2822]
**Current behavior**
Identity shows as undeclared in recipient cms.
When whistleblowers review their submission, identification information is there

**Expected behavior**
There should be a button to ask for custodian permission to access whistleblowers information. however it shows 
Identity
Undeclared

Custodian case management is empty.

**Steps to reproduce the problem or feature illustration**
I am pretty sure I have set up the custodian role properly.
I have enabled custodian role in advanced site settings, I have created a custodian user and have also checked Subject answer visibility to custodian authorization (Am I missing something)

**What is the motivation or use case for changing the behavior?**
Playing around with functionalities. No use case yet.

**GlobaLeaks version:**
4.0.15 on Ubuntu, 
updated chrome and windows

**Comment by evilaliv3** [comment]
Thank you for this feedback @elbill 

Do you mind trying to insert a new submission  and see if this apply also to a new submission on the current globaelaks?
In fact i think this bug has been already solved and maybe is impacting submissions inserted before the fix was implemented.

**Comment by larrykind** [comment]
@evilaliv3 Hello, same problem here with 4.0.16 version. 
I opened the issue you refer to #2810 and tried to add a comment after issue was closed. 
Referring to #2810 , point 2 was solved, point 1 not yet. So identity is never shown to the receiver, either for standard and custom identity template, and avery record appears to receiver user as anonymous.

**Comment by evilaliv3** [comment]
Thank you @larrykind for this feedback, let me check it.

**Comment by evilaliv3** [comment]
Fixed! The patch will be included by today in a minor release 4.0.17.

Thank you @larrykind and @elbill
