### ISSUE TITLE
Scoring system not functioning properly for questions within a group of questions

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2825]
**Current behavior**
When having a group of questions, (in my case a group triggered by a question - I believe it is the same with a group not triggered by any question) the scoring of questions within group of questions does seem to contribute to the overall score when trying to trigger another question based on score.

**Expected behavior**
O would expect the questions within the group to contribute to the score as all questions. Unless I'm missing something on how scoring works.

**Steps to reproduce the problem or feature illustration**
create a question
create a group of questions
trigger group of questions by the first question
put scores in group question answers

create a question
try to trigger the question by the high score. Not behaving as expected (tried everything with a work around avoiding the creation of group and worked fine)

**What is the motivation or use case for changing the behavior?**
trying to created more complex questionnaire with dependencies

**GlobaLeaks version:**
4.0.15

**Server Operating System and Version (if applicable):**
ubuntu 18.04

**Comment by evilaliv3** [comment]
Thank you @elbill for reporting this we will try to verify what you are reporting and in case i wont be able to reproduce it come back to you for asking more feedback.

**Comment by evilaliv3** [comment]
Fixed; the patch will be included starting from release 4.0.19
