### ISSUE TITLE
Error when trying to set up check box (or other multiple choice questionnaire) to trigger single or multi line text input question

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2826]
**Current behavior**
Internal server error when trying to set up selectbox (or other multiple choice questionnaire) to trigger single or multi line text input question

**Expected behavior**
I would expect the text input type of question to be able to be triggered by check box question.
When instead of a text input question I used question group with text input questions it worked as expected (used this workaround for the time being).

**Steps to reproduce the problem or feature illustration**
create a check box type of question with 3 options. Then within the same step create a single line text input question ant try to trigger it from one of the options of the check box question. When trying to save I get an error message. 

**What is the motivation or use case for changing the behavior?**
Trying to make more interactive questionnaires.

**GlobaLeaks version:**
4.0.15, 4.0.5
on Ubuntu 18.04

[error1.txt](https://github.com/globaleaks/GlobaLeaks/files/4509217/error1.txt)
[error2.txt](https://github.com/globaleaks/GlobaLeaks/files/4509218/error2.txt)

**Comment by evilaliv3** [comment]
Thjank you for the valuable feedback @elbill, this seems to be a regression on release 4. I will revise it and get back to you.

In your setup have you made use of question templates or all has been implemented inside a question without using any question template?

**Comment by elbill** [comment]
@evilaliv3 no I havent used any question templates.

**Comment by evilaliv3** [comment]
Thank you @elbill it seems there was a regression in commit 1d6bc464dd

**Comment by evilaliv3** [comment]
@elbill: You could now update to 4.0.16 where this issue is solved.
