### ISSUE TITLE
Identity template - text in case of negative answer and confirm text are not shown to the whistleblower

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2829]
**Current behavior**

Within identity question setting, text to show to the whistleblower in case of negative answer, and confirm text are not shown to the whistleblower during questionnaire flow.

**Expected behavior**

 Text to show to the whistleblower in case of negative answer, and confirm text should be shown to the whistleblower during questionnaire flow. 

**Steps to reproduce the problem or feature illustration**

1. Set a questionnaire with step containing identity template
2. Fill the fields referring to "text to show in case of negative answer" and "text to show to confirm"
3. Fill the questionnaire choosing "No" in the identity step
-> **Text set at point 1 is not shown and the following confirm part is not shown**

**What is the motivation or use case for changing the behavior?**

To recovery a working and useful feature to make aware the whistleblower some legal/privacy notes

**GlobaLeaks version:**

v4.0.16

**Browser:**

Firefox 75.0, Chrome 81.0.4044.122

**Server Operating System and Version (if applicable):**
 
Debian 10.3 buster

**Client Operating System and Version (if applicable):**

Windows 10, Windows 7

**Comment by evilaliv3** [comment]
Fixed! The patch will be included by today in a minor release 4.0.17.

Thank you @larrykind
