### ISSUE TITLE
Update from 3.11.68 to 4.0.16

### ISSUE THREAD

**Issue by Roberto-Papa** [globaleaks/GlobaLeaks#2830]
**Current behavior**

After update, the browser show this:
This page does not redirect properly

**Expected behavior**

**Steps to reproduce the problem or feature illustration**

apt-get update && apt-get install globaleaks

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

3.11.68

**Browser:**

Firefox, Edge, Chrome

**Server Operating System and Version (if applicable):**
 
Debian 10.2

**Client Operating System and Version (if applicable):**

[mgr-231.log](https://github.com/globaleaks/GlobaLeaks/files/4529302/mgr-231.log)

**Comment by evilaliv3** [comment]
Dear @Roberto-Papa 

Thank your reporting and for the log attached.

I tried to reach your system via Tor and via HTTPS and all seems to bme to work fine.

What i notice is that there could be misconfigurations in your HTTPS certificate. I advise you to check on this and add the full certificate chain because i think the issue you are facing is due to the fact that your browser seems to not recognize the certificate signature.

Please feel free to get back to us if this do not fix the issue.

**Comment by Roberto-Papa** [comment]
Thanks for immediate response,

this site is into the our internal farm, the certificate is autofirmed (chained with Sophos certificate) and with rev. 3.11.68 run correctly (with warning, but correctly).

Why dont run with 4.0.6?

 

Da: Giovanni Pellerano <notifications@github.com> 
Inviato: venerdì 24 aprile 2020 16:17
A: globaleaks/GlobaLeaks <GlobaLeaks@noreply.github.com>
Cc: Roberto-Papa <roberto.papa@email.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [globaleaks/GlobaLeaks] Update from 3.11.68 to 4.0.16 (#2830)

 

Dear @Roberto-Papa <https://github.com/Roberto-Papa> 

Thank your reporting and for the log attached.

I tried to reach your system via Tor and via HTTPS and all seems to bme to work fine.

What i notice is that there could be misconfigurations in your HTTPS certificate. I advise you to check on this and add the full certificate chain because i think the issue you are facing is due to the fact that your browser seems to not recognize the certificate signature.

Please feel free to get back to us if this do not fix the issue.

**Comment by evilaliv3** [comment]
Thank you for this clarification @Roberto-Papa 

actually from your log i do not identify any issue.

Would you please run ```apt-get update && apt-get install globaleask``` and share us the globaleaks.log after you run it? as well we would like to see the apparmor log after this. thank you
