### ISSUE TITLE
Custom Identity Template with attachment - attachment is not part of identity 

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2834]
**Current behavior**

In Custom Identity template, if built with an attachment field (for ID card scan, etc.), the attachment is shown and notified via email to the receiver as a normal attachment, not hidden as it should be as a part of identity block, waiting for custodian authorization.

**Expected behavior**

Attachments as part of WBer identity, should be hidden to the receiver until custodian authrization

**Steps to reproduce the problem or feature illustration**

1. Create a custom identity template with an attachment and replace it into a questionnaire
2. As a WBer, fill the questionnaire and upoload a file as attachment -> notification of new attachment is sent to the receiver 
3. As a receiver, access to the ticket -> Attachment is not hidden to the receiver

**What is the motivation or use case for changing the behavior?**

Attachment can be part of custom identity template (ID card scan, other ID scans).

**GlobaLeaks version:**

4.0.18

**Browser:**

Firefox 75, chrome 81.0.4044.122

**Server Operating System and Version (if applicable):**
 
debian 10.3 buster

**Client Operating System and Version (if applicable):**

Windows 10

**Comment by evilaliv3** [comment]
Thank you for reporting this @larrykind 

Actually this is a know limitation of the currenct whistleblower identity / custodian implementation that do not have a simple solution.

By the current design in fact attachments are not part of any question but just part of the submission so that their access could not be limited only to users granted for access by the custodian.

**Comment by larrykind** [comment]
Hi @evilaliv3,
In a multitenant context, especially for tenants requesting a strong identification of the WBer, this feature could be very important, I hope to see it in next releases. Thanks

**Comment by evilaliv3** [comment]
Sure thing. We recognize the value as well and we will plan for this addition trying to raise funds for the needed refactor. Thank you for your important feedback.

**Comment by larrykind** [comment]
closed as implemented

**Comment by evilaliv3** [comment]
@larrykind : i see that you closed the ticket, but actually this is not implemented.

Do you mean dupliacated by https://github.com/globaleaks/GlobaLeaks/issues/3161 ?

**Comment by larrykind** [comment]
@evilaliv3 : Yes I was wrong: this is duplicated by #3161
