### ISSUE TITLE
Whistleblower identity form is shown again and again after its filling

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2835]
**Current behavior**

Identity form inside the WBer ticket is shown again and again in the bottom part, once it's filled and submitted. If you fill more than one time, the identity shown to the receiver is the last inserted.
This problem refers I think to closed issue #2810, point 2. 

**Expected behavior**

WBer Identity should be filled and submitted just once. No further form should be shown once it has been submitted

**Steps to reproduce the problem or feature illustration**

1. As a WBer, fill a questionnaire **without** initially declaring identity (standard or custom template) and submit.
2. Perform access to that ticket with ticket-id, and insert identity data
3. At identity submit time, identity is submitted and another empty identity form is shown tho the WBer. Ifyou fill identity form again, it's submitted again
4. If accessing as a receiver (with or without custodian clearance), identity shown is related to the last filled form

**What is the motivation or use case for changing the behavior?**

Identity of a whistleblower should be declared just once.

**GlobaLeaks version:**

4.0.18

**Browser:**

Firefox 75 Chrome 81.0.4044.122

**Server Operating System and Version (if applicable):**
 
debian 10.3 buster

**Client Operating System and Version (if applicable):**

windows 10

**Comment by evilaliv3** [comment]
Thank you for  reporting this @larrykind.

The bug is now fixed and the patch will be included in next release.
