### ISSUE TITLE
Checkboxes in user configuration/setup are not working

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2841]
**Current behavior**

1. Logged as tenant's admin:
Checkbox for "force user to change password" is disabled anc checked and administrator can't never changes its status

2. In new user creation (also in the wizard)
Checkbox for "don't send email with activation link" is not working: email is sent

3. In administrator (the user itself) panel:
chackbox for "force user to change password" is empty. if you click it checks, but it becomes also disabled and it cannot be changed.

**Expected behavior**

Checkboxes in the config panel should do what they claim to do, and they should be never disabled to the admin user.

**Steps to reproduce the problem or feature illustration**

Login as tenant admin:

1. Go to users setup section: Checkbox for "force user to change password" is disabled permanently
2. Create a brand new tenant / receiver user: eve if you check the box to not send email with activation link, email is sent
3. Go to administrator panel (the logged user itself), checkbox for "force user to change password" is unchecked: if checked it checks and it becomes disabled also.

**What is the motivation or use case for changing the behavior?**

Those checkboxes are a standard toolset for user management. Tenant's Administrator should check and uncheck whenever it would.

**GlobaLeaks version:**

v4.0.18

**Browser:**

Firefox 76 Chrome 81.0.4044.129 

**Server Operating System and Version (if applicable):**
 
debian 10.3 buster

**Client Operating System and Version (if applicable):**

windows 10

**Comment by evilaliv3** [comment]
Thank you for reporting this @larrykind.

We will recheck on the described behaviours.
Actually only one befaviour was intended that was the mechanism that when the password change was enforced was preventing the administrator to revert it but based on your feedback i'm considering to revert this.

**Comment by larrykind** [comment]
@evilaliv3 Thank you for consider it.

**Comment by evilaliv3** [comment]
@larrykind: I've fixed the issue 1 and 3 but i'm not able to reproduce 2.

Would you please retry? I guess while completing the wizard you may have eventually pressed the keyboard and switched the checkbox configuration. thank you!

**Comment by larrykind** [comment]
@evilaliv3 you are right.
Issue no. 2 is valid just for users created from admin backend, not for the first receiver created with the wizard. 
I apologize for my mistake.

**Comment by evilaliv3** [comment]
I see, thank you for the clarification. Let me fix this.

**Comment by evilaliv3** [comment]
Fixed! thank you!
