### ISSUE TITLE
After user/whistleblower session expires, interaction with client still continues

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2842]
**Current behavior**

if a user/whistleblower session expires, page remains there, and if some link or button is clicked in the page, it seems to load something, but really it does nothing. You cannot move anymore from there, the only solution is to delete  browser cookies, go to login page and restart the session.

**Expected behavior**

Every click done in a page with an expired session shoud redirect to the default page of the previously logged user. Or better, it should be done automatically, or it should be some alert of expired user session.

**Steps to reproduce the problem or feature illustration**

Login as a user (receiver/admin/custodian/whistleblower), let the session expires, do some button/link click: page seems to load, but it does noting and client remains stuck in that page.

**What is the motivation or use case for changing the behavior?**

A system like Globaleaks should hide at session expire time the prevoiusly logged users information.

**GlobaLeaks version:**

v4.0.18

**Browser:**

Firefox 75 Chrome 81.0.4044.129 

**Server Operating System and Version (if applicable):**
 
debian 10.3 buster

**Client Operating System and Version (if applicable):**

windows 10

**Comment by evilaliv3** [comment]
The implementation in commit https://github.com/globaleaks/GlobaLeaks/commit/85e583de77eedc1d43d29b353d88b6140a2ae9ba  addresses this ticket by:
- recognizing user activities (usage of mouse and keyboard) and implementing keep alive of sessions.
- recognizing if the session is expired and closing the application by redirecting the user to the homepage.
