### ISSUE TITLE
After saving the tenant hostaname, a page refresh should be issued to make the Letsencrypt section to appear

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2843]
**Current behavior**

After tenat's hostname has been set, click save and nothing more happens until page is refreshed.
When page is refreshed and LE certificate installed page is going to freeze.

**Expected behavior**

Let's encrypt part and new domain should appear when tenant's domain name is saved
When Certificate is installed a modal should appear with the new link of the tenant

**Steps to reproduce the problem or feature illustration**

1. From main tenant, create a new tenant.
2. go to network config and give the hostname. Click save. -> Notghing happens
3. If a page refresh is issued, LE section appears and certificate can be installed
4. Once certificate is installed, page freezes: a modal is expected containing the new tenant's link

**What is the motivation or use case for changing the behavior?**

LE ceritifate section is an important section that ensures HTTPS security for the tenants. The risk is that LE certificate will not be installed

**GlobaLeaks version:**

4.0.18

**Browser:**

Firefox 76 Chrome 81.0.4044.129

**Server Operating System and Version (if applicable):**
 
debian 10.3 buster 

**Client Operating System and Version (if applicable):**

windows 10

**Comment by evilaliv3** [comment]
Thank you for reporting this.

Actually we consider the modal to be deprecated and we removed it but it is
likely that removing it we introduced some sort of failures.

do you have any feedback on this? do you consider the modal to be necessary?

**Comment by larrykind** [comment]
The modal in my opinion is a "happy ending" and easy system feedback that saved hostname is working and LE certificate is installed correctly. In the modal version I liked that certificate activation was working in the darker background, while modal was appearing: it gives you the control of what system is doing.
If you consider it deprecate, I think that there should be something like an automatic redirect to the new hostname in the same browser tab with a "wait please" message to the user.

**Comment by evilaliv3** [comment]
Fixed! thank you @larrykind

**Comment by larrykind** [comment]
**In v.4.0.20:**
After issusing Letsencrypt request page freezes after clicking "enable" button.
A redirect to login page seems to be done by changing hostname only if it's already assigned at the time of issuing LE certificate.
Just to know, from my experience, to issue LE certificate "enable" button must be clicked couple of times. The second time it seems to fire LE requests.

**Steps to reproduce the problem or feature illustration**    

1.     Create new tenant
2.     Assign an hostname
3.     Assign a letsencrypt certificate. After clicking (two times ?) "enable" button, the page freezes.
4.     If request is done from an existing assigned hostname, there is a redirect to login page

A redirect or modal was expected. Otherwise user is not aware of what is happening on the system

**Comment by evilaliv3** [comment]
Thank you @larrykind; it should be fixed now and the software should now correctly redirect to the homepage by using HTTPS immediately after clicking enable.
