### ISSUE TITLE
Error when attempting to move context up or down in list

### ISSUE THREAD

**Issue by dustin-fci** [globaleaks/GlobaLeaks#2848]
**Current behavior**

I have created a new context and tried to move it up in the list. When clicking on the arrow the context shows that it has moved but there is an error that pops up and the position is not saved. The error is "Error! Internal Server Error (Unexpected)"

**Expected behavior**

The context would move and save its position

**Steps to reproduce the problem or feature illustration**

Create a new context and try to adjust its position in the list.

**What is the motivation or use case for changing the behavior?**

We have an "Other" context which should really be the last on the list.

**GlobaLeaks version:**

4.0.18

**Browser:**

Firefox 76.0.1

**Server Operating System and Version (if applicable):**
 
Ubuntu 18.04.2

**Client Operating System and Version (if applicable):**

Windows 10

**Comment by evilaliv3** [comment]
Thank you @dustin-fci, i will try to check on this by tomorrow evaluatingthe possibilty to include the fix in the upcoming release 4.0.19.

**Comment by evilaliv3** [comment]
Fixed and fix included in release 4.0.19
