### ISSUE TITLE
After Letsencrypt enable request is issued, page freezes

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2850]
This issue refers to closed issue #2843.
After assigning an hostname to a new tenant, LE section freezes, a redirect to new hostname in https version should be expected.

**Current behavior**

After issusing Letsencrypt request page freezes and you can click "enable" button indefinitely.
Referring to #2843, a redirect to login page seems to be done by changing hostname only if it's already assigned at the time of issuing LE certificate.
Just to know, from my experience, to issue LE certificate "enable" button must be clicked couple of times. The second time it seems to fire LE requests.

**Expected behavior**

Redirect should be done for newly assigned or changed hostnames

**Steps to reproduce the problem or feature illustration**

1. Create new tenant
2. Assign an hostname
3. Assign a letsencrypt certificate. After clicking (two times ?) "enable" button, the page freeze. 
4. If request is done from an existing assigned hostname, everything seems to work

**What is the motivation or use case for changing the behavior?**

referring to #2843, a redirect to new hostname in https version should be done. Otherwise user is not aware of what is happening on the system

**GlobaLeaks version:**

4.0.20

**Browser:**

Firefox 76, chrome 81.0.4044.138

**Server Operating System and Version (if applicable):**
 
debian 10.3 buster

**Client Operating System and Version (if applicable):**

windows 10

**Comment by evilaliv3** [comment]
Thank you @larrykind! we will recheck on this.

When you identify that the topic has been already discussed on a closed ticket, please just update that ticket and we will evaluate the possibility to re-open it to maintain the know-how on the same ticket.

Thank you for your understanding.

**Comment by larrykind** [comment]
Thank you @evilaliv3. I'm sorry for increasing enthropy.

**Comment by evilaliv3** [comment]
You are welcome @larrykind and thank you for your understanding.
