### ISSUE TITLE
Link of "tenant management" appears in sub-tenants / multi-tenant checkbox not working

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2851]
1) Link for multi tenant management should appear only when multi tenant checbox is enabled
2) multi tenant checkbox change doesn't seem to work. Multi tenant link does not toggle.

**Current behavior**

1) From main tenant the multi tenant feature is not toggled when multi tenant feature chackbox is toggled in "advanced settings" section. The link is always there. System is already in multi-tenant mode and cannot be disabled.
 2) Link for multi tenant feature appears also in sub tenants, but, if clicked in a sub tenant it throws an error. So final behaviour is working

**Expected behavior**

1) Checkbox for multi tenant-feature should toggle the "tenant management" link and tht multi-tenant sub-section
2) Tenant managment link shold not be shown in sub- tenants

**Steps to reproduce the problem or feature illustration**

1.1) from main tenant go to advanced settings:
1.2) toggle "enable multi tenant feature" -> not working; 

2.1) From main tenant create a new sub tenant
2.2) link "Tenant management" link is shown

**What is the motivation or use case for changing the behavior?**

Tenant management should be done just form main tenant. 
Checkbox for "enable multi tenant" should work

**GlobaLeaks version:**

4.0.20

**Browser:**

firefox 76, chrome  81.0.4044.138 

**Server Operating System and Version (if applicable):**
 
debian 10.3 buster

**Client Operating System and Version (if applicable):**

windows 10

**Comment by evilaliv3** [comment]
Fixed with commit: https://github.com/globaleaks/GlobaLeaks/commit/3835a55e19212136d14b1a4614c41a4183589cbc
