### ISSUE TITLE
Flag for user's "force password change" not working

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2852]
**Current behavior**

This issue refers to closed issue #2841 
1) If admin changes the password to a user, and before saving, ungflag the "force password change", at save time the flag "force password change" is set again
2) If admin  changes the password to a user, saves, and then unflags the "force password change",
ite remains unflagged, but at user's login time system asks to change user's password

**Expected behavior**

1) The flag for "force password change" should be saved as is whatever other action is issued before
saving the user's settings
2) If the flag is unchecked, the system should not ask to the user to change the password.

**Steps to reproduce the problem or feature illustration**

1.1) As admin, change an user's password and unflag "force password change". Then save
1.2) Reopen the setting for the user just created --> flag is checked

2.1) As admin, change an user's password. Save
2.2) unflag "force password change". Save -> checkbox remains unflagged
2.3) If user performs a login, system asks to change password.

**What is the motivation or use case for changing the behavior?**

Flag for "force password change" should work as expected -  this is an administrator key feature - and also when the flag is saved with other setting are changed for the user. 

**GlobaLeaks version:**

4.0.20

**Browser:**

Forefox 75,  chrome 81.0.4044.138

**Server Operating System and Version (if applicable):**
 
debian 10.3 buster

**Client Operating System and Version (if applicable):**

windows 10

**Comment by evilaliv3** [comment]
Thank you @larrykind; we were considering to eforce this behaviour in order to be sure that the users know that the password has been changed by the administrator and that ne new password probably communicated manually should be changed.

I understand this in practice could make things harder for a provider. For this reason we will roll back this change and we will consider adding a mail notification to the user to inform that the password has been changed and as well track this optarion in the audit log.

**Comment by evilaliv3** [comment]
Fixed!

Fix will be released with release 4.0.21

**Comment by larrykind** [comment]
@evilaliv3 issue point 2 is still in 4.0.24: If an admin changes an users password without force password change flag, at user login time system asks for password change. 
More, after user changes successfully the password, if as admin password is set again (without force flag) system throws **Error (unexpected)**.

**Comment by evilaliv3** [comment]
Thank you @larrykind, it is likely that the bug you encountered was a bug affecting all version from 4 to 4.0.25 in relation to key escrow that is now fixed: https://github.com/globaleaks/GlobaLeaks/commit/fa1e06c56f39d9379fbc9ba789b6e52129256c84

For new setups all is automatically working

For existing setups this can be solved by disabling key escrow and re-enabling it. Admin will lose temporary possibilty to reset users password but they will be back able to do it after recipient will have logged in.

Thank you

**Comment by larrykind** [comment]
@evilaliv3 in 4.0.24 If the setting you refer to is "advanced option -> enable encryption" it doesn't seem it can be disabled in the main tenant and in sub-tenants. Checkbox is checked and disabled.
