### ISSUE TITLE
Context order not changes

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2853]
**Current behavior**

This issue refers to closed issue #2848 .
If a context is moved up or down, system seem to save, but in the home page they are shown in default order

**Expected behavior**

Different context should be shown in the saved order

**Steps to reproduce the problem or feature illustration**

1) As admin, create three contexts
2) change the context order, the system seems to save.
3) Go in the default whistleblowing page, order is as default

**What is the motivation or use case for changing the behavior?**

Context order should change as set 

**GlobaLeaks version:**

4.0.20

**Browser:**

Firefox 76, Chrome 81.0.4044.138

**Server Operating System and Version (if applicable):**
 
debian 10.3 buster

**Client Operating System and Version (if applicable):**

windows 10

**Comment by evilaliv3** [comment]
@larrykind: Have you disabled the option "Show contexts in alphabetical order" in advanced settings?

Anyway probably we could hide the ordering interface if this option is set so that the interface would result more simple.
