### ISSUE TITLE
Globaleaks exception notifications

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2859]
**Current behavior**
I'm getting globaleaks exception notification emails (see end of this message) when using the whistleblowers interface. Functionality doesn't seem to be affected. started a few days ago for no apparent reason (I can think of).

**Expected behavior**
no exception

**Steps to reproduce the problem or feature illustration**
just filling in questionaires without submitting will cause the notifications

**GlobaLeaks version:**
4.0.19, 4.0.24

**Browser:**
chrome, opera

**Server Operating System and Version (if applicable):**
ubuntu 18.04

**Client Operating System and Version (if applicable):**
 Windows 10

**notification email**
Platform: Fraud Line
Host: sec.fraudline.gr (sng2i4qxzadqswvkc4kvkxfokwdih7js65uhmvk5imugccsy6srbxsad.onion)
Version: 4.0.24

URL: /

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36

Error Message: Error: [$interpolate:interr] http://errors.angularjs.org/1.7.9/$interpolate/interr?p0=%7B%7Bitem.native%20(item.name)%7D%7D&p1=TypeError%3A%20r.value.apply%20is%20not%20a%20function

Stacktrace:
[
  {
    "columnNumber": 167,
    "lineNumber": 2305,
    "fileName": "https://feel.sec.fraudline.gr/js/scripts.js"
  },
  {
    "columnNumber": 327,
    "lineNumber": 2525,
    "fileName": "https://feel.sec.fraudline.gr/js/scripts.js",
    "functionName": "Ma"
  },
  {
    "columnNumber": 448,
    "lineNumber": 2413,
    "fileName": "https://feel.sec.fraudline.gr/js/scripts.js",
    "functionName": "interr"
  },
  {
    "columnNumber": 459,
    "lineNumber": 2385,
    "fileName": "https://feel.sec.fraudline.gr/js/scripts.js",
    "functionName": "p"
  },
  {
    "columnNumber": 133,
    "lineNumber": 2315,
    "fileName": "https://feel.sec.fraudline.gr/js/scripts.js",
    "functionName": "apply"
  },
  {
    "columnNumber": 149,
    "lineNumber": 2387,
    "fileName": "https://feel.sec.fraudline.gr/js/scripts.js",
    "functionName": "a"
  },
  {
    "columnNumber": 457,
    "lineNumber": 2370,
    "fileName": "https://feel.sec.fraudline.gr/js/scripts.js",
    "functionName": "Ba"
  },
  {
    "columnNumber": 476,
    "lineNumber": 2362,
    "fileName": "https://feel.sec.fraudline.gr/js/scripts.js",
    "functionName": "c"
  },
  {
    "columnNumber": 493,
    "lineNumber": 2362,
    "fileName": "https://feel.sec.fraudline.gr/js/scripts.js",
    "functionName": "f"
  },
  {
    "columnNumber": 99,
    "lineNumber": 2362,
    "fileName": "https://feel.sec.fraudline.gr/js/scripts.js",
    "functionName": "f"
  }
]

**Comment by evilaliv3** [comment]
Thank you @elbill, i confirm the presence of the bug. It affects the language selector when exactly 2 or 3 languages are enabled.

**Comment by evilaliv3** [comment]
Fixed, patch will be included starting from release 4.0.25
