### ISSUE TITLE
[UI improvement] Wrong visualization of disabled notifications state

### ISSUE THREAD

**Issue by gianlucagilardi** [globaleaks/GlobaLeaks#2862]
**Current behavior**

Nella UI del ricevente l'icona "disabilita email di notifica" riporta lo stato "notifiche abilitate" nel menu visulizzato aprendo una segnalazione, anche se la ricezione delle notifiche e' stata disattivata dall'admin

**Expected behavior**

Coerenza tra impostazione e UI

**Steps to reproduce the problem or feature illustration**

1) Disabilitare le notifiche via email per un ricevente da admin panel
2) loggarsi come ricevente
3) aprire una segnalazione
4) verificare lo stato dell'icona della disabilitazione notifiche

**What is the motivation or use case for changing the behavior?**

UI improvement

**GlobaLeaks version:**

4.0.32

**Browser:**

any

**Server Operating System and Version (if applicable):**
 
Buster

**Client Operating System and Version (if applicable):**

Win10

**Comment by evilaliv3** [comment]
Thank you @gianlucagilardi.

I've still to analyze the issue but i think to confirm that currently the interface of the recipient does not consider the global setting applied to the platform.

Will proceed adding a patch for this that can be easily included in next minor release.
