### ISSUE TITLE
Audit log functionality

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2863]
I see that "user" tab in audit log registers just the last access of each user.
How about "activities" and "stats"? They dont seem to register anything.
Is this normal behaviour?
I have checked the " Log accesses of internal users" checkbox. Anything else that needs to be configured to activate the audit log?

Just to add that I'm using the multisite feature and I have set teh "Logging level" on INFO on the main site.

Globaleaks v 4.0.32 on Ubuntu 18.04lts

**Comment by evilaliv3** [comment]
Thank you @elbill for your question.

Current implementation of this feature is tracked by ticket https://github.com/globaleaks/GlobaLeaks/issues/2579

It would be important if you could provide your feedback on the data collected and provide examples of the visualization that you would like to see in the interfaces.

As for the documentation this is unfortunately incomplete and supported best effort by the community. if you would like we welcome your contribution on this section topic.
 - https://docs.globaleaks.org
 - https://github.com/globaleaks/GlobaLeaks/tree/master/documentation (sources)

**Comment by elbill** [comment]
Thanks @evilaliv3 I have gone trough ticket #2579 many times however I still do not understand.
Is the audit log feature inactive? Is the table tehre to accomodate future implementation? If yes when is it going to be activated?
If it is active how do we actualy see logging information? Are there specific settings to enable it?

**Comment by evilaliv3** [comment]
I see, actually the feature is enabled by default but currently that much complete as it requires important user feedback to better understand how to properly implement it in a privacy preserving way. The table with basic capabilities is there to accomodate future implementation and we are adding time to time some logging.

**Comment by evilaliv3** [comment]
Moving forward this topic we are adding back a previous implementation that could provide the administrators insight in relation to reports to make it possible to verify the well-functioning of the platform.

Here an example of the prototyped interfaces:
![Screenshot_2020-06-16 Audit log](https://user-images.githubusercontent.com/217034/84751418-d6c26d00-afbc-11ea-90fb-2fd33e45b90a.png)

As well here is attached an example of the exported data in the CSV format
[report.txt](https://github.com/globaleaks/GlobaLeaks/files/4785396/report.txt)

(the file has actually extension csv but here on github i had to rename it as txt)
