### ISSUE TITLE
error on build 

### ISSUE THREAD

**Issue by abraralmadi** [globaleaks/GlobaLeaks#2867]
when i git clone then try to build the image 

**Expected behavior**

**Steps to reproduce the problem or feature illustration**

W: GPG error: https://deb.globaleaks.org buster/ Release: The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
E: The repository 'http://deb.globaleaks.org buster/ Release' is not signed.

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

**Browser:**

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
thank you @abraralmadi; would you please retry now?

May i ask you which is your current interest in building a custom image?
Have you developed a patch that you would like to suggest for integration?

Thank you!

**Comment by abraralmadi** [comment]
it works now thank you

**Comment by abraralmadi** [comment]
can I ask about v4.0.15 does it have a problem with forget password email notification does not work?

**Comment by abraralmadi** [comment]
May I ask you which is your current interest in building a custom image?
Have you developed a patch that you would like to suggest for integration?
no, I am just testing because I just learn docker

**Comment by abraralmadi** [comment]
May I ask you which is your current interest in building a custom image?
Have you developed a patch that you would like to suggest for integration?
sure, we use the app and I need it in image form to fit our environment

**Comment by evilaliv3** [comment]
I see. Thank you for clarifying.

Please consider ths possibility to prepare a pull request with your edits
so that we may evaluate to release officially the package in you format.

This would guarantee to your setup the setup the same review and security
and assure that all your edits are inserted in our continuous retesting and
won't require separated penetration tests. Would this help.

We shall in fact discourage any custom build as it would not satisfy same
security and whould not enable you to update the software as in the
official release.

**Comment by abraralmadi** [comment]
We shall in fact discourage any custom build as it would not satisfy same
security and whould not enable you to update the software as in the
official release.
I totally understand + agree with you. we are facing an issue with the update each time you update we build a new image with the update but this is our environment requirement.

**Comment by abraralmadi** [comment]
thank you

**Comment by evilaliv3** [comment]
@abraralmadi: Did you solve your build issue? could this ticket be closed?

**Comment by abraralmadi** [comment]
Yes, thank you
