### ISSUE TITLE
v4.0.15 does it have a problem with forget password email notification

### ISSUE THREAD

**Issue by abraralmadi** [globaleaks/GlobaLeaks#2868]
**Current behavior**

can I ask about v4.0.15 does it have a problem with forget password email notification does not work?

**Expected behavior**

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

**Browser:**

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
Thank you @abraralmadi. Actually many defects on this topic has been fixed recently.

Would you please update to current release 4.0.32 and let us know if the bug you are reporting is still present?

**Comment by abraralmadi** [comment]
Thank you so much @evilaliv3

**Comment by evilaliv3** [comment]
@abraralmadi : do you have any update on your retesting?

**Comment by abraralmadi** [comment]
@evilaliv3 yes it is working perfectly
