### ISSUE TITLE
Context card icon renderring issue in context selection screen

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2869]
**Current behavior**
Context cards icons look deformed in teh context selection screen. They look fine within a context.

**Expected behavior**
Would expect context icons to render properly.

**Steps to reproduce the problem or feature illustration**
create contexts, assign (square eg 512x512) png icon and open card selection screen

**GlobaLeaks version:**
v4.0.32

**Browser:**
up to date chrome 

**Server Operating System and Version (if applicable):**
ubuntu 18.04 lts

**Client Operating System and Version (if applicable):**

win 10
card selection
![παίΖω Τίμια - Blow the whistle - Google Chrome 15_6_2020 1_23_36 μμ](https://user-images.githubusercontent.com/23246886/84647463-272dc200-af0c-11ea-9616-eaaa32beca0c.png)
context
![παίΖω Τίμια - Blow the whistle - Google Chrome 15_6_2020 1_23_55 μμ](https://user-images.githubusercontent.com/23246886/84647481-2c8b0c80-af0c-11ea-8b59-4b07de0b1742.png)

**Comment by evilaliv3** [comment]
Thank you for the feedback @elbill,  we will fix proportions by the next release.

**Comment by evilaliv3** [comment]
@elbill considering your feedback and the fact that the interface is now benefits of well refined margin and is maximizing the use of the space, i've refactored the layout to flexible to the content and this is the result.

Big screen:
![Screenshot_2020-06-16 Blow the whistle](https://user-images.githubusercontent.com/217034/84715429-b53b9400-af70-11ea-9690-415afc3f61cc.png)

Small screen:
![Screenshot_2020-06-16 Blow the whistle(1)](https://user-images.githubusercontent.com/217034/84715440-b967b180-af70-11ea-81d9-1e555aa4bab9.png)


What do you think? Would this work for you?

**Comment by evilaliv3** [comment]
(This icons refers to receivers but actually i'm applying them as well to context and this would improve as well https://github.com/globaleaks/GlobaLeaks/issues/2870 in relatin to your comments.

**Comment by evilaliv3** [comment]
![Screenshot_2020-06-16 Blow the whistle(7)](https://user-images.githubusercontent.com/217034/84745562-11280c00-afb5-11ea-98d9-1f66d2140d27.png)

Fixed! Here shown images of size 160px*160px and 160px*320px.
Images are shown with a height of 10rem and a max width of 20rem.

This fix is performed while addressing as well: https://github.com/globaleaks/GlobaLeaks/issues/2870

**Comment by evilaliv3** [comment]
@elbill: When you like feel free to test 4.0.36 and provide your feedback on the changes.

**Comment by elbill** [comment]
@evilaliv3 everything looks fine. I will complete a project by teh end of this month and see how it works in practice. thanks
