### ISSUE TITLE
Small context selection card setting missing

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2870]
**Current behavior**
No setting for small context card apears in the advanced settings

**Expected behavior**
Would expect the possibility to ahve small context selection cards. 

**What is the motivation or use case for changing the behavior?**
Small context selection cards, in case they were removed, were very convenient and beautiful.

**GlobaLeaks version:**
4.0.32

**Browser:**
chrome

**Server Operating System and Version (if applicable):**
ubuntu 18.04lts 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
Thank you for your feedback @elbill.

Following a recent research on the software and interviews with existing users it has been identified that many feature were too complicated and affecting usability. Among these for example the small recipient/context card selection.

In addition the complexity of their design was making not possible to retest their compatibility with small screens in all the possibilities, while the existing interface is now well retested in every possible condition.

For this and other reasons it has been decided to remove these feature that you could eventually achieve by applying a custom CSS.

Please let me know if you have any feedback.

**Comment by elbill** [comment]
@evilaliv3 I did not personaly see any issues with the mobile devices I tested the feature with (small and large, mid and high resolution), and did not see any issues registered on git hub. If users found it complicated I supposteh they could disable it, since it was not enabled by default. On the contrary it gave a great advantage for desktop computers as users do not have to scroll all the way down and made much better use of the screen pixels for ~6 contexts. I'm not sure how custom css could achieve this. Is there any example; 
I would personaly suggest to bring it back!

**Comment by evilaliv3** [comment]
Thank you @elbill, maybe we could work together to improve the current visualization where you dont like it? what would you change?

We would prefer in fact to maintain only one visualization and eventually improve it.

**Comment by elbill** [comment]
@evilaliv3 a typical multicontext setup is shown in the pictures below. Ite represents a FHD monitor and a FHD smartphone. Just the icon/logo of the context is needed and the name of the organisation, category.
There is a tone of screen space wasted ~70%. Even if you put a lot of text as a description of the context still ~40% of screen space is wasted and not symetrical at all. For the mobile phone it is not as bad but still not symetrical and pixels wasted.
This is not in line with the curent aestetics of modern web sites and the rest of the platform that is at a very good level. 
I considered small context cards pixel perfect, in a tile style, no need to scroll down a lot and was very impressed by the way they looked and also in some testing I received very good remarks by other people. I was very surprised that the were removed. I signed up for the usability survey, but unfortunately was not contacted.
![παίΖω Τίμια - Blow the whistle - Google Chrome 15_6_2020 9_06_42 μμ](https://user-images.githubusercontent.com/23246886/84692518-a9d77100-af4e-11ea-8f13-959b4ba1e973.png)
![104078680_208068990241130_3179399587653659489_n](https://user-images.githubusercontent.com/23246886/84692637-e0ad8700-af4e-11ea-8c95-1defe16b558d.jpg)

**Comment by evilaliv3** [comment]
Thank you for reporting this that actually more than related to the removal of small cards, seems a defect. (here there should be 2 elements per line already)

**Comment by evilaliv3** [comment]
Here the revised layout that without the complexity of choice among small and normal cards effectively resize i think it makes good use of the space.  hope you like it!

Images have been configured to tall 160px and have a max with of 320px. Sizes in reality are expressed in terms of rem unit so to not be binded to pixel and scale depending on the resolution of the screen.

Contexts selection:
![Screenshot_2020-06-16 Blow the whistle(7)](https://user-images.githubusercontent.com/217034/84745066-526bec00-afb4-11ea-8058-74f345b17494.png)

Context with multiple recipients selectable:
![Screenshot_2020-06-16 Blow the whistle(7)](https://user-images.githubusercontent.com/217034/84745077-5861cd00-afb4-11ea-9e70-3b401743f89b.png)

Context with just a recipient:
![Screenshot_2020-06-16 Blow the whistle(6)](https://user-images.githubusercontent.com/217034/84745088-5d268100-afb4-11ea-9024-829c4ed590d5.png)

**Comment by elbill** [comment]
@evilaliv3 looks much better. Sorry I thought the defect was bad design :-) Let me know when this will be fixed to get back to you with feedback and close the issue if everything looks fine.

**Comment by evilaliv3** [comment]
It will be released by today.

**Comment by evilaliv3** [comment]
@elbill: When you like feel free to test 4.0.36 and provide your feedback on the changes.

**Comment by elbill** [comment]
@evilaliv3 everything looks fine on mobile and desktop. Thanks
