### ISSUE TITLE
Reporting 

### ISSUE THREAD

**Issue by abraralmadi** [globaleaks/GlobaLeaks#2874]
Dears

first of all, thank you for this amazing platform

We are currently using it and want to ask if there is a way I can extract all reported cases in one CSV file format or if we can use any other way to extract the data for all cases together 

**Current behavior**
it only allows us to download  individual cases 

**Expected behavior**
 extract all reported cases in one CSV file format

**What is the motivation or use case for changing the behavior?**
we want to do report and statics 

**GlobaLeaks version:**
v4.0.30

**Comment by evilaliv3** [comment]
Thank you @abraralmadi 

Actually at the moment this is not possible but soon or later we will try work on this but I invite to check on https://github.com/globaleaks/GlobaLeaks/issues/2824, https://github.com/globaleaks/GlobaLeaks/issues/2824 that already deal with this topik and provide your feedback.

Does your team have any developer that would like to work on this topic and perform a patch to be integrated into the software?

I invite you to join our slack channel (https://slack.globaleaks.org) for possible cooperation.
