### ISSUE TITLE
Install script not found

### ISSUE THREAD

**Issue by joanix** [globaleaks/GlobaLeaks#2875]
**Current behavior**

wget https://deb.globaleaks.org/install-globaleaks.sh

produces a 404 error

**Expected behavior**

Either

wget should download the file 

or 

The documentation at https://docs.globaleaks.org/en/latest/setup/InstallationGuide.html should be updated to reflect the new installation method.

**Steps to reproduce the problem or feature illustration**

Use wget as indicated, or try to download the file using a web browser.

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

**Browser:**

**Server Operating System and Version (if applicable):**
 

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
It should be all working now, thank you for reporting this @joanix 

The issue was due to a change in the name of the branch from 'master' to 'main' that we applied in relation to https://tools.ietf.org/html/draft-knodel-terminology-02 that affected the reverse proxy.
