### ISSUE TITLE
Email change confirm links in notification emails are not working

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2878]
**Current behavior**

If attempting to change receiver's  and custodian's email address, logged as receiver/custodian user itself, link in the email is not working. If link is clicked, that's the output in the web page (that's for receiver):

`{"error_message": "Resource not found", "error_code": 6, "arguments": []}`

More: by clicking "modify" the tiny alert panel to check the email to verify is not shown anymore
 
**Expected behavior**

Clicking email confirm link should bring to email confirm page. It should be fine to see again the alert to check the new email address for a new email containing confirm link

**Steps to reproduce the problem or feature illustration**

1. log in as a receiver/custodian
2. modify email address -> yellow alert to check email is not shown
3. in notification email, click the link to confirm address change.

**What is the motivation or use case for changing the behavior?**

User cannot change email address by itself.

**GlobaLeaks version:**

4.0.40

**Browser:**

Firefox 77

**Server Operating System and Version (if applicable):**
 
ubuntu bionic

**Client Operating System and Version (if applicable):**

windows 10

**Comment by evilaliv3** [comment]
Thank you for reporting this @larrykind 

this is probably a recent regression related to the fact that we have renamed the API to be on the /api path.

**Comment by larrykind** [comment]
Thank you for the prompt feedback @evilaliv3 . Right now administrators only can change users email addresses. Could you put this fix in the next release, if possible

**Comment by evilaliv3** [comment]
Fixed, will be release 4.0.48

**Comment by larrykind** [comment]
Hi @evilaliv3, tested with 4.0.50, point 2 of the issue is not restored: yellow label that tells user to check new email address. 
Receivers are not aware that they are about to receive a mail to validate the new mail address, while they are viewing on the UI the old mail address until validation will be complete.
