### ISSUE TITLE
Hint for adding additional answers in group questions not showing for template group questions

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2882]
**Current behavior**
Hint for adding additional answers in group questions not showing for template group questions. Just the plus sign is showing

**Expected behavior**
I would expect the hint for adding additional answers in group questions to be showing for template group questions alike it shows for the normal group questions

**Steps to reproduce the problem or feature illustration**
Create a group question template with the add additional answers enabled. Add it in a questionnaire and use the questionnaire in a context. No hint is showing.

**GlobaLeaks version:**
4.0.49

** operating system **
Ubuntu(18.04)

**Comment by evilaliv3** [comment]
Thank you for reporting this. This is probably a bug that has been always present.

I will try to see if i can this easily fixed within the next release.
