### ISSUE TITLE
You were added to awesome-humane-tech

### ISSUE THREAD

**Issue by aschrijver** [globaleaks/GlobaLeaks#2887]
This is just a FYI issue to notify that you were added to the curated awesome-humane-tech in the 'Freedom' category, and - if you like that - are now entitled to wear our badge:

[![Awesome Humane Tech](https://raw.githubusercontent.com/humanetech-community/awesome-humane-tech/main/humane-tech-badge.svg?sanitize=true)](https://github.com/humanetech-community/awesome-humane-tech)

By adding this to the README:

```markdown
[![Awesome Humane Tech](https://raw.githubusercontent.com/humanetech-community/awesome-humane-tech/main/humane-tech-badge.svg?sanitize=true)](https://github.com/humanetech-community/awesome-humane-tech)
```

https://github.com/humanetech-community/awesome-humane-tech

**Comment by evilaliv3** [comment]
Thank you @aschrijver ! We really appeciate this!

For the moment we are limiting the usage of badges to what necessary for continous integrations but we will surely We will considering adding the badge of your project or to sponsor it.

Thank you again!
