### ISSUE TITLE
Recipient activation email

### ISSUE THREAD

**Issue by Deharteloos** [globaleaks/GlobaLeaks#2888]
**Current behavior**
I installed Globaleaks and proceed to the platform wizard successfully. But the recipient have not yet received any email about globaleaks. So he can not do the first login

**Server Operating System and Version:**
Ubuntu 20.04

**Comment by larrykind** [comment]
Hi @Deharteloos. I think I had similar problem. Please check globaleaks logs, it could be possible that your globaleaks doesn't send emails because it requires that the mailserver you are using needs a CA released SSL certificate. A self signed certificate will not work.

**Comment by evilaliv3** [comment]
Closing as probably outdated. Please feel free to re-open it if you still have issues on this topic.
