### ISSUE TITLE
If PGP key is expired, disable encryption (file/notification) and send a notice to the Receiver and Admin

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#289]
If a PGP key is expired, disable encryption (file/notification) and send a notice to the Receiver.

**Comment by evilaliv3** [comment]
This has been suggested by @DrWhax as an useful thing to be implemented also for the admin.

The admin should receive an email the list of all the PGP keys expired or expiring.

**Comment by evilaliv3** [comment]
i've created the following mail template for the admin: https://github.com/globaleaks/GlobaLeaks/blob/080b73d221b1cf6833a4fb8a8b1e26e3996cc9ed/client/app/data/txt/admin_pgp_expiration_alert.txt

**Comment by evilaliv3** [comment]
implemented and intefrated. released in version 2.60.57
