### ISSUE TITLE
Imported questionaire fails viewing correctly when a user is diabaled

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#2892]
We’ve encountered a bug relating to an imported questionaire. We’ve followed the procedure described below:

1: Created a duplicate of a previously made questionaire (from other site)
2: Exported the duplicate questionaire
3: Deleted the duplicate questionaire
4: Imported the exported questionaire into new site
5: added the questionaire to the Context

The import works fine, but only the first lines of each questionaire page was shown. Editing the questionaire showed, that all lines were present.
A search round the site showed, that we had one disabled recipient, and when enabling this recipient, the full questionaire was shown.
A little oddity to take care of

**Comment by evilaliv3** [comment]
Thank you @schris-dk

Is it possible for you to attach a copy of this questionnare or of a questionnaire reproducing the issue?
If not would you please describe the main features used within your questionnaire? (e.g. are you using questionnaire templates).
As well if you could some screenshots could help.

Actually questionnares do not have connection with recipients and their enabling state and this feedback would be helpful to debug the bug.

Thank you!

**Comment by schris-dk** [comment]
Will send documentation toorrow

/soren

Sendt fra min iPhone

Den 8. sep. 2020 kl. 18.05 skrev Giovanni Pellerano <notifications@github.com>:

﻿

Thank you @schris-dk<https://github.com/schris-dk>

Is it possible for you to attach a copy of this questionnare or of a questionnaire reproducing the issue?
If not would you please describe the main features used within your questionnaire? (e.g. are you using questionnaire templates).
As well if you could some screenshots could help.

Actually questionnares do not have connection with recipients and their enabling state and this feedback would be helpful to debug the bug.

Thank you!

**Comment by schris-dk** [comment]
[Documentation of error pertaining questionaires.docx](https://github.com/globaleaks/GlobaLeaks/files/5193237/Documentation.of.error.pertaining.questionaires.docx)

Hi Giovanni!

Find the documentation attached

br

Soren

**Comment by schris-dk** [comment]
[Chrome Console output.docx](https://github.com/globaleaks/GlobaLeaks/files/5194733/Chrome.Console.output.docx)

Hi Giovanni!!

Find output from Chrome Console

/soren

**Comment by evilaliv3** [comment]
Thank you so much @schris-dk, this contains actually valuable information for the fix!

**Comment by evilaliv3** [comment]
This commit would fix your issue. It will be released starting from version 4.0.55.

Thank you!
