### ISSUE TITLE
Error configuring new tenant while Globaleaks retrieves onion link

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2898]
**Current behavior**

After creating a brand new tenant, if you suddenly go to "configure", while it retrieves onion link, it fails to open the new tenant's wizard, giving "resource not found". 
Noticed that retrieving onion link takes about 3 or 4 minutes, in that time window if you go configuring new tenant it fails. After it installs the link everything goes fine. I attach a log screenshot.

From the log I don't understand also the multiple entries "creating onion link" for the same tenant. 

![onion](https://user-images.githubusercontent.com/61267901/94116620-93915900-fe4b-11ea-92c6-4b49b70a7dde.JPG)

**Expected behavior**

Onion link retrieval should not block new tenant configuration.

**Steps to reproduce the problem or feature illustration**

1. Create new tenant
2. While create onoin link -> Suddenly configure it -> resource not found

**What is the motivation or use case for changing the behavior?**

Configuring a new tenant should be independent from onion link retrieval.

**GlobaLeaks version:**

4.0.54

**Browser:**

Firefox 80.0.1 - Chrome  85.0.4183.121

**Server Operating System and Version (if applicable):**
 

ubuntu bionic

**Client Operating System and Version (if applicable):**

windows 10

**Comment by evilaliv3** [comment]
Thank you for reporting this @larrykind 

Typically all cpu-intensive operations are delegated to a job but it is likely that something is failing here. I will try to recheck on this and fix it within the next release.

**Comment by evilaliv3** [comment]
This should be solved now.
