### ISSUE TITLE
Enabling a tenant 2FA enabled the 2FA on the admin account of the first site used for admin purposes on a multitenant setup

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2899]
**Current behavior**
I believe enabling a tenant 2FA enabled the 2FA on the admin of the fist site used for admin purposes. It was a scary moment. 
The reset password button was not working. Is this normal to disable reset password button when 2FA is enabled? 2FA eventually worked so I have access.
I am a bit confused on how 2FA works on multiple accounts. If I enable it on 2 accounts (tenants) it will save them under the same name?
I am using Microsoft authenticator.
What is the best way to make sure **never** to lock ourselves out of our first admin account?

**GlobaLeaks version:**
e.g.: v4.0.45

**Browser:**
Chrome

**Server Operating System and Version (if applicable):**
Ubuntu 18.04LTS
Microsoft authenticator

**Comment by evilaliv3** [comment]
@elbill : Actually each user has a private 2FA mechanism.

What i think you have encountered is the following current bug:
- you enabled 2fa for a user on a secondary tenant
- you performed a login on the root tenant and clicked 'configure' on a secondary tenant
- you found the system asking you the 2FA of the secondary tenant admin

This is a know bug of the current implementation that will be solved by the upcoming update.
