### ISSUE TITLE
Repository Issue installing GlobaLeaks

### ISSUE THREAD

**Issue by mathxsyn** [globaleaks/globaleaks#2900]
**Current behavior**
Receiving the error listed below whne running the Installation script.

> Running the GlobaLeaks installation...
> In case of failure please report encountered issues to the ticketing system at: https://github.com/globaleaks/GlobaLeaks/issues
> 
> Detected OS: Debian - buster
> Running: "apt-get -y update"... FAIL
> Ouch! The installation failed.
> COMBINED STDOUT/STDERR OUTPUT OF FAILED COMMAND:
> Hit:1 http://security.debian.org/debian-security buster/updates InRelease
> Hit:2 http://deb.debian.org/debian buster InRelease
> Hit:3 http://deb.debian.org/debian buster-updates InRelease
> Ign:4 https://deb.globaleaks.org buster/ InRelease
> Get:5 https://deb.globaleaks.org buster/ Release [744 B]
> Get:6 https://deb.globaleaks.org buster/ Release.gpg [833 B]
> Ign:6 https://deb.globaleaks.org buster/ Release.gpg
> Reading package lists...
**> W: GPG error: https://deb.globaleaks.org buster/ Release: The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
> E: The repository 'http://deb.globaleaks.org buster/ Release' is not signed.**

**Expected behavior**

Expecting it to install as normal without issues

**GlobaLeaks version:**

Currently trying to install the version up on the site for download at https://deb.globaleaks.org/install-globaleaks.sh
Couldn't find what version it is.

**Server Operating System and Version (if applicable):**
 
Currently running Debian GNU/Linux 10 (buster)

**Comment by evilaliv3** [comment]
Thank you @mathxsyn , actually we don't have any automatic retesting on signatures and sometimes during signing process the signature stalls resulting ineffective.

**Comment by evilaliv3** [comment]
Fixed! It should work now! Thank you again @mathxsyn

**Comment by mathxsyn** [comment]
Thank you, it worked now!
