### ISSUE TITLE
Multimedia type of questions missing

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2901]
**Current behavior**
Multimedia type of questions missing. Have they been removed? 
I see it was introduced a few months ago and was a very interesting feature (such features need some time to catch on).
If they have been removed is there an alternative way to embed multimedia?

**GlobaLeaks version:**
v4.0.55

**Comment by evilaliv3** [comment]
Thank you for reporting this @elbill 

If they have been removed is due to an error. I will recheck on this and get sure they work on next update.

**Comment by evilaliv3** [comment]
@elbill: I just rechecked on this issue and actually i think you were using a previpous version where we added a specific multimedia question that has now been removed.

You can now add multimedi content to any of the questions of type "Group of questions".
Try the feature and please provide feedback, we consider that it should work better and offer more possibilities.
