### ISSUE TITLE
Identity templates settings are lost after creation of new tenant

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#2904]
**Current behavior**

In a multitenat contest, with inherited questionnaries or customized, standard identity templates or customized, this is happening:

- all identity templates (inherited from the master tenant, customized, or recreated for customized questionnaire) after some days simply disappear, questionnaires does not have identity section anymore:that section becomes empty. 

- Setting is lost for all tenant in the platform

- restarting globaleaks didn't work, the only thing worked was to reassign identity template for all tenants.

**Expected behavior**

Once identity template is assigned, setting should not be lost

**Steps to reproduce the problem or feature illustration**

1. Create a questionnaire with standard identity template (or customized)
2. Don't really know how to fire the bug, but after some days it come up. Maybe attached log could help.
![error-1](https://user-images.githubusercontent.com/61267901/95741502-a3ec6500-0c8e-11eb-83da-7fd9c6eb6c1a.JPG)

**What is the motivation or use case for changing the behavior?**

Fully available to give further details.

**GlobaLeaks version:**

4.0.54

**Browser:**

firefox 81, chrome 85

**Server Operating System and Version (if applicable):**
 
ubuntu bionic

**Client Operating System and Version (if applicable):**

windows 10

**Comment by evilaliv3** [comment]
@larrykind: Does this happen in relation to software updates or also if the software is not updated?

**Comment by larrykind** [comment]
@evilaliv3 even if it's not updated. I'm on to 4.0.54 updated in september. It happened also on 4.0.50.

**Comment by larrykind** [comment]
Available also on slack if further detail is needed

**Comment by larrykind** [comment]
Finally I found how to reproduce the bug on 4.0.50 - 4.0.54:

1) Create a new tenant
2) EVERY identity settings on all questionnaires on the platform are lost !! ( identity setting for inherited questionnaires is lost, identity settings for tenant specific questionnaires are lost, translations also are lost) 

The result is that when I create new tenant, there is a damage on every tenants identity settings

Restarting globaleaks won't work. The only thing that worked was to reassign identity setting to all questionnaries on the platform.

Please help

**Comment by larrykind** [comment]
Hi @evilaliv3, 
same problem also on 4.1.0

**Comment by evilaliv3** [comment]
Fixed @larrykind , the patch will be included in 4.1.9
