### ISSUE TITLE
Multilanguage site's default language does not work properly

### ISSUE THREAD

**Issue by maxmois** [globaleaks/GlobaLeaks#2905]
**Current behavior**
When several languages are in use and one of them is english, public site's language is always english by default, even if any other language is set as a default in admin. When english is deactivated - functionality works as it should.

**Expected behavior**
When opening public site - default language should be the language, that have been chosen as a default language in admin and not English. 

**Steps to reproduce the problem or feature illustration**
1. Create new site
2. Chose for example 3 languages from admin as site languages (for example English, Swedish and Finnish)
3. Set Swedish as a default language
4. Go to public site and verify default language is still english.

**What is the motivation or use case for changing the behavior?**
Bug?

**GlobaLeaks version:**
4.0.54

**Browser:**
Safari Version 14.0 (15610.1.28.1.9, 15610)
Chrome Version 86.0.4240.75 (Official Build)

**Server Operating System and Version (if applicable):**
Ubuntu 18.04

**Comment by evilaliv3** [comment]
Hi @maxmois,

Thank you for reporting this.
Actually this is not a bug but a feature not well clarified.

GlobaLeaks recognize the language of the browser of the user and tries to serve a language that most likely the user would like to see.

Follow me on this example, supposing that the software is enabled in English and Finnish and that the language default is set on Finnish
- In the case the user will use a Finnish browser, as finnish is available the user will see Finnish
- In the case the user will use an English browser, as english is available the user will see English (this is probably your case)
- In the case the user will use an Italian browser the default will be shown: Finnish

Could you please confirm if my guess is right and this is your case?

thank you

**Comment by maxmois** [comment]
Hi @evilaliv3,

Thank for clarifying, this is the case and works completetly righ, just as you described. Sorry for the irrelevant bug report.

**Comment by evilaliv3** [comment]
Don't worry @maxmois and thank you for reporting the issue as soon that you noticed it!
