### ISSUE TITLE
Failed to set domain names with a hyphen to embed inside iframes

### ISSUE THREAD

**Issue by PetziAt** [globaleaks/GlobaLeaks#2910]
**Current behavior**

Advanced settings -> Main configuration ->
Allow the following websites to embed the platform inside iframes

Can't include domains with a hyphen.

**Expected behavior**
Including domains with hyphen should be possible

**GlobaLeaks version:**
Software version: 4.0.58

**Comment by evilaliv3** [comment]
Thank you for reporting this @PetziAt.

I would like to inform you that the upcoming version 4.1.0 that we will be releasing in few days wont support iframe inclusion any longer that will be replaced with a more proper plugin working via CORS requests.

This would be a more proper solution supporting featuring history free loading.

If you would like to share a link to your current platofrm i may give it a look and provide you some feedback for proper intregration.

I invite you as well to join our slack channel: https://slack.globaleaks.org
