### ISSUE TITLE
Sorting of reports based on status does not work properly

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2911]
**Current behavior**

When clicking on "Status" in the case management system does not sort reports based on status. It rather sorts reports based on IDentity (ascending or descending) .

**Expected behavior**
One would expect when clicking on "Status" in the case management system to sort and group reports based on status.
(It would also be useful to be able to sort based on ascending or descending ID this is rather a feature by clicking on ID).

**GlobaLeaks version:**
4.0.58

**Comment by evilaliv3** [comment]
Thank you for notifying this @elbill.

We will be including a fix for this in the upcoming release 4.1.0 to be released within a week from now.
