### ISSUE TITLE
unable to resolve host address ‘deb.globaleaks.org’

### ISSUE THREAD

**Issue by fran6q** [globaleaks/GlobaLeaks#2912]
**Current behavior**
On install globalleaks wget is unable to resolve host address ‘deb.globaleaks.org’

**Expected behavior**
Download the resource

**Steps to reproduce the problem or feature illustration**
run docker-compose up --build

docker on windows10

**Comment by evilaliv3** [comment]
Hi @fran6q , i think that its likeky that in your setup you did not enable outgoing network connections.

Could you confirm this? 

Thank you
