### ISSUE TITLE
Make it possible for whistleblowers to see still their receipt on the first access to the report

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2915]
One adopter of globaleaks has just suggested a possibility to make it possible for whistleblowers to see the recipt on the first access to the report.

The idea came to the doubt that users accessing the platform and performing a submission may click the button 'view the report' before actually saving the code.

By providing the recipt to the user this 'fast' users would have still the chance to see the suggestion about the receipt and have a second chance to annotate it.

A different approach instead could be to remove entirely that could be a good idea to be sure that the user could not leave the receipt page except from clicking an explicit logout button.

**Comment by evilaliv3** [comment]
![Screenshot_2020-11-13 Antani - Report](https://user-images.githubusercontent.com/217034/99115511-d1f8f800-25f2-11eb-9ff8-d604c59b56e0.png)

**Comment by evilaliv3** [comment]
@elbill @SylvainFPU @emartinborregon: Based on the experience with your projects what do you think of this proposal?

Would you find it useful or do you have any alternative suggestion?

**Comment by elbill** [comment]
@evilaliv3 a customer asked for this feature (first aproach) like a month ago. I made up an excuse that it has not been implemented for security reasons, it is like having your password on your screen.
Anyway I believe that it would be useful to have such a feature and my security consideration, while "true", is not that important.
The alternative aproach would rather be a combination with the first aproach. If one tries to close the page or tab a warning (like maketing sites do) "have you noted the code to be able to have access" would also be useful. 
The first aproach or the combination between first and second would be good. 
Trying to think of any other alternatives, just brainstorming, maybe something involving a qr code or a save bookmark URL that contains the receipt code and leads the WB to his submission without having to login?
Or to prompt them to enter their email to receive notifications assuring them the address will be encrypted with no access by recipients or admin (if this is technically possible).

**Comment by SylvainFPU** [comment]
I like it. Simple and clear for users. It can raise the amount of WB coming back to their submission.
Is i permanently visible @evilaliv3 or only the first time you click on 'view the report'?

Not sure about the security issue raised by @elbill . This code appears anyway when submitting something on Globaleaks, and people should submit this in a safe environment. Is your security concern based on someone potentially looking at the screen from behind?

**Comment by elbill** [comment]
@SylvainFPU as I said the security concern is not that important. The issue could have implications when someone is not very careful forgetting to close the tab (to a smaller extent when someone looking behind). I agree that in a safe environment there would be no issue. The risk to someone forgetting to take down the code, especially when stessed, is much higher.

**Comment by emartinborregon** [comment]
I like the idea, it seem a great way to increase the whistleblowing - reception interaction.

**Comment by evilaliv3** [comment]
Thank you everybody for your feedback! I think we could proceed on this.

I share the concern of @elbill that the less the code remain visible the better it is. For testing this improvements i've already considered to show it only during the initial whistleblowing session if the user immediately proceed on the report by clicking the button 'view the report'.

**Comment by evilaliv3** [comment]
Closing as implemented and part of the stable release since version 4.1.0
