### ISSUE TITLE
Hosting service for GlobaLeaks platform

### ISSUE THREAD

**Issue by bharat715** [globaleaks/GlobaLeaks#2921]
Wanted to know if Globaleaks offers hosting service for real use (Not Demo). 
Is there any list of providers in USA who are experienced and offering hosting service for private and secured GlobaLeaks platform?

**Comment by evilaliv3** [comment]
Dear @bharat715, thank you for your request. Actually this ticketing system deals only with the software.

There are many providers that actually provides globaleaks professionally but unfortunately we do not know any based in USA.

I invite you to join our slack where you can find other users and possibly some providers: https://slack.globaleaks.org
