### ISSUE TITLE
Make it possible to filter submissions searching inside the full submission content

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2922]
**Current behavior**
When using search it gives as a result all the preview text as well as all the questionnaire text.

**Expected behavior**
I would expect to search through the preview answer text (and even better even the non previewed answer text).

**Steps to reproduce the problem or feature illustration**
When I search using keyword contained in a question text, gives as a result all the cases rather than those cases which answer contain the keywors

**GlobaLeaks version:**
4.0.58

**Browser:**
Chrome 

**Server Operating System and Version (if applicable):**
Ubuntu 18.04LTS

**Client Operating System and Version (if applicable):**
 Windows 10

**Comment by evilaliv3** [comment]
@elbill: Actually in that interface the content of the submission is not available so that the search can look only into the metadata and into the fields subject to preview.

**Comment by elbill** [comment]
I understand that it is not looking in the whole content of the submission.
It can look into the content of the preview questions submission.
My issue that I believe doesn't make sense is that if a word is contained in the question text, the search gives all cases as a result.
example:
Question: type of misconduct: 
FreeText answer: fraud

When you search with keyword "type" or "misconduct" the results will contain ALL cases (this should not be happening, is very confusing) regardless if questionnaire is preview or not.
If you search for "fraud" it will give you indeed the one case that contains it (if the question is in preview mode).
The search functionality could be definitely improved in the long.  In the short term just looking into answers and avoiding to look into questionnaire text would be an improvement.

**Comment by evilaliv3** [comment]
Ah! i see, i actually misunderstood the aim.

What you propose is surely doable, i will try to work on this within the next updates.

**Comment by evilaliv3** [comment]
Closing this ticket as current releases perform the search inside the full submission content as suggested within the ticket.

Thank you @elbill
