### ISSUE TITLE
Travis build automation should test newly built-package on a clean machine

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#293]
Currently implement travis build testing system does install the debian package build on the same machine used to build the debian package itself.

This ticket is about implementing a procedure/scripts to test the debian package build on a clean machine. 

The test should check that installation works, that globaleaks startup properly and answer to /node interface.

Please keep in mind that the "commands" executed on the install procedure and the commands executed on the travis should be aligned exactly (consider wrapping all of them into a single shell script).
##

**Comment by evilaliv3** [comment]
Closing as outdated
