### ISSUE TITLE
Font type and size of title in header area of web page

### ISSUE THREAD

**Issue by bharat715** [globaleaks/GlobaLeaks#2930]
Is there a way to change font type and size to match with customizable site logo text and size?

**Comment by evilaliv3** [comment]
Thank you @bharat715.

Actually you could change anything you prefer by uploading a custom CSS file within the Site Settings configuration section.

I would advise to stusy your customization using a browser debugging console like the one of Chrome that is quite practical to identify CSS id and classes to be customized up to your needs.

P.s. for questions like this if possible please use https://forums.globaleaks.org that is more intended for creating a common user knowledge base; this ticket is more for feature requests and bug reporting. Feel free to open a new ticket if you consider that you would like to propose this as an important feature. Thank you!
