### ISSUE TITLE
Cannot update Globaleaks

### ISSUE THREAD

**Issue by jacoblarsen** [globaleaks/GlobaLeaks#2941]
**Current behavior**

Cannot update Globaleaks 

 sudo apt-get update
Hit:1 http://10.35.0.52 focal InRelease
Hit:2 http://10.35.0.52 focal-updates InRelease
Hit:3 http://10.35.0.52 focal-backports InRelease
Hit:4 http://10.35.0.52 focal-security InRelease
Ign:5 https://deb.globaleaks.org focal/ InRelease
Get:6 https://deb.globaleaks.org focal/ Release [741 B]
Get:7 https://deb.globaleaks.org focal/ Release.gpg [833 B]
Err:7 https://deb.globaleaks.org focal/ Release.gpg
  The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
Fetched 1,574 B in 1s (1,635 B/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://deb.globaleaks.org focal/ Release: The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Failed to fetch http://deb.globaleaks.org/focal/Release.gpg  The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Expected behavior**

**Steps to reproduce the problem or feature illustration**

 sudo apt-get update

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

We updated to Version 4.1.2 on the 25th of november without this issue. 

**Browser:**

**Server Operating System and Version (if applicable):**
 
Ubuntu 20.04.

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
Thank you @jacoblarsen , actually the release was still not signed. Please proceed now.

**Comment by jacoblarsen** [comment]
Perfect - that fixed it. Thanks
