### ISSUE TITLE
Richiesta inserimento enti

### ISSUE THREAD

**Issue by GloriaTomasini** [globaleaks/GlobaLeaks#2943]
Si richiede l'inserimento dei seguenti enti come utilizzatori nel file publiccode.yml:
Consorzio BIM del Chiese, codice IPA BIMCHIE
Comune di Sella Giudicarie, codice IPA c_m360
Comune di Pieve di Bono-Prezzo, codice IPA c_m365
Comune di Borgo Chiese, codice IPA c_m352
Comune di Valdaone, codice IPA m343

Grazie

**Comment by evilaliv3** [comment]
Gentilissima @GloriaTomasini la ringrazio molto per questo suggerimento, potrebbe gentilmente guidarmi a come farlo? 

Contiamo circa 900 enti che usano globaleaks direttamente tramite whistleblowing.it e sarebbe molto bello riuscire in effetti a poterli mostrare tutti.

@alranel @ruphy @liberamente: quali sono i vostri migliori suggerimenti per un progetto ambizioso come il nostro che volesse dare risalto ai risultati ottenuti? (credo di fatto si sia attualmente uno dei pochi software su portale a vantare cosi tanta diffusione!) grazie!

\cc @larrykind: potreste lato vostro raccogliere i codici IPA delle amministrazioni che usano globaleaks tramite voi?

**Comment by evilaliv3** [comment]
Buonasera @GloriaTomasini,
Le confermo siamo disponibili a listare le vostre piattaforme. Gentilmente potrebbe fornirmi anche gli indirizzi web delle stesse?
Vorremmo sincerarci che il software installato sia quello ufficiale e che sia mantenuto aggiornato secondo i criteri di licenza (https://github.com/globaleaks/GlobaLeaks/blob/main/CHANGELOG)

Al momento ho avuto modo di visionare il solo portale del "Consorzio BIM del Chiese" che vedo essere configurato per richiedere una password che le segnalo essere un approccio in antitesi con la best practice e contro la nostra stessa filosofia di progetto volta a tutelare i segnalanti. Posso chiederle chi sia l'installatore?

La ringrazio molto.

**Comment by evilaliv3** [comment]
Aggiornamento: Credo che il codice IPA non sia di fatto necessario, vedo che la corrente versione del file publiccode.yml richiede di specificare nomi a piacimento e accetta il codiceip solo per indicare la prima pubblica amministrazione che ha sviluppato il codice mettendolo in riuso.

**Comment by GloriaTomasini** [comment]
Buongiorno.

Ho inviato la segnalazione in base alle istruzioni trovate su
https://developers.italia.it/it/riuso/dichiarazione.
Sto adempiendo alla scadenza del Piano triennale per l'informatica di AGID
2020-2022, la n. CAP1.PA.LA03. È vero che viene indicato il software a
riuso, ma ho visto che anche per quelli open source è presente la sezione
"La mia amministrazione lo usa".

Il vostro prodotto è stato adattato per conto della maggior parte delle
amministrazioni trentine attraverso il Consorzio dei Comuni Trentini. So
che si sono interfacciati con una terza parte (dovrebbe essere ISWEB Spa),
ma sentiti i nostri consulenti del Consorzio dei Comuni, questi ci hanno
confermato che la soluzione adottata è la vostra.

Spero di essere stata chiara ed esauriente. Così non fosse ci risentiamo.

Un cordiale saluto

*Gloria Tomasini*

Responsabile Transizione Digitale


 tel. (+39) 0465.621048 int. 6     cell. 328 1176471

mail: digitale@bimchiese.tn.it    pec: bimdelchiesecondino@legalmail.it



*Informativa privacy ai sensi del Regolamento UE 2016/679*

*I dati e contenuti nella presente email sono raccolti e trattati nel
rispetto del Regolamento UE 2016/679 sulla protezione dei dati personali
(GDPR). Gli interessati possono rivolgersi  in qualsiasi momento al
Titolare del trattamento, Consorzio BIM del Chiese, per esercitare i
diritti previsti dal GDPR. Il Responsabile per la Protezione Dati (RPD) è
il Consorzio Comuni Trentini con sede a Trento in via Torre Verde, 23. I
dati di contatto sono i seguenti: tel. 0461.920717, mail: servizio
RPD@comunitrentini.it <RPD@comunitrentini.it>, PEC:
consorzio@pec.comunitrentini.it <consorzio@pec.comunitrentini.it>*




Il giorno gio 3 dic 2020 alle ore 16:07 Giovanni Pellerano <
notifications@github.com> ha scritto:

**Comment by evilaliv3** [comment]
@GloriaTomasini: abbiamo proceduto ad aggiungere ora la lista dei vostri enti che credo saranno già visualizzabili da domani non appena il sito developersitalia si sarà aggiornato.

Gentilmente posso chiederle di notificare ai suoi contatti al Consorzio la possibilità di comunicarci direttamente anche l'intera lista dei comuni aderenti? Di fatto noi non siamo una pubblica amministrazione, ma un gruppo di attivisti che pro-bono stanno mettendo a disposizione questo progetto della pubblica amministrazione e questo ci aiuterebbe a diffondere il progetto e usare efficientemente le scarse risorse di progetto. Eventualmente segnali pure la presenza di questo ticket cosi the i suoi referenti possano caricare anche qui direttamente una pull request di aggiunta.

La ringrazio molto.

**Comment by GloriaTomasini** [comment]
Grazie mille.

Sarà fatto. Manderò una mail al Consorzio dei Comuni con la vostra
richiesta.

Buona giornata

*Gloria Tomasini*

Responsabile Transizione Digitale


 tel. (+39) 0465.621048 int. 6     cell. 328 1176471

mail: digitale@bimchiese.tn.it    pec: bimdelchiesecondino@legalmail.it



*Informativa privacy ai sensi del Regolamento UE 2016/679*

*I dati e contenuti nella presente email sono raccolti e trattati nel
rispetto del Regolamento UE 2016/679 sulla protezione dei dati personali
(GDPR). Gli interessati possono rivolgersi  in qualsiasi momento al
Titolare del trattamento, Consorzio BIM del Chiese, per esercitare i
diritti previsti dal GDPR. Il Responsabile per la Protezione Dati (RPD) è
il Consorzio Comuni Trentini con sede a Trento in via Torre Verde, 23. I
dati di contatto sono i seguenti: tel. 0461.920717, mail: servizio
RPD@comunitrentini.it <RPD@comunitrentini.it>, PEC:
consorzio@pec.comunitrentini.it <consorzio@pec.comunitrentini.it>*




Il giorno mer 9 dic 2020 alle ore 11:51 Giovanni Pellerano <
notifications@github.com> ha scritto:

**Comment by evilaliv3** [comment]
La ringrazio molto @GloriaTomasini 
Ho provveduto ad inviare una mail al consorzio suggerendo questa possibilità. Sperando di fare cosa gradita ho indicato che l'idea mi sia scaturita dalla sua richiesta che ritengo molto meritevole.

Grazie!

**Comment by evilaliv3** [comment]
Gentile @GloriaTomasini , le segnalo che l'indirizzo email RPD@comunitrentini.it  presente nella sua firma sembrerebbe di fatto non esistere; la invito a correggerlo o a segnalare la problematica ai suoi referenti. Corcialmente,
Giovanni Pellerano
