### ISSUE TITLE
Release not signed (again?)

### ISSUE THREAD

**Issue by kwiatekp** [globaleaks/GlobaLeaks#2946]
Cannot update repository while installation because of error:
`GPG error: https://deb.globaleaks.org buster/ Release: The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>`

Debian 10
using https://deb.globaleaks.org/install-globaleaks.sh as install script.

**Comment by evilaliv3** [comment]
Thank for notifying this @kwiatekp; the repository is now signed.

Yes unfortunately we do not have a very reliable infrastructure and we are not able to identify if during the release process one of the repories failed on the release process.

Do you have any resource? Does your project have any resource that you could devolve to this kind of improvementes? 

Thank you!
