### ISSUE TITLE
Focal release 4.1.9 mu

### ISSUE THREAD

**Issue by bernd316** [globaleaks/GlobaLeaks#2947]
**Current behavior**

code seams not to be signetd / release sources missing at https://deb.globaleaks.org/focal/

Err:5 http://deb.globaleaks.org focal/ Release.gpg The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>

**Expected behavior**

installation fails

**Steps to reproduce the problem or feature illustration**

**What is the motivation or use case for changing the behavior?**

**GlobaLeaks version:**

4.1.9

**Browser:**

**Server Operating System and Version (if applicable):**
 
ubuntu 20.04

**Client Operating System and Version (if applicable):**

**Comment by evilaliv3** [comment]
Thank you @bernd316 , it should be all fine now!
