### ISSUE TITLE
Platform license, permissions, terms and name use related question

### ISSUE THREAD

**Issue by creativeanalyst** [globaleaks/GlobaLeaks#2948]
Checking if any formal license, permissions, terms including using GlobaLeaks name use permissions are required to install GlobaLeaks software platform, configure, customize, support and offer any related services on commercial and/or non commercial basis to any organizations in USA. US based organizations may have some concerns and issues in using any software platform hosted on a server which is not physically located in USA so checking to explore options to install software platform with a hosting provider located in USA or hosted by US based provider to try.

Any known list of US based hosting providers currently offering or have hosted software platform available for use to try?

**Comment by evilaliv3** [comment]
Hi @creativeanalyst, thank you for your question.

GlobaLeaks is distributed with an AGPLv3 License: https://github.com/globaleaks/GlobaLeaks/blob/main/LICENSE

It could be hosted anywere, for free and without limitations and we are currently not aware of US based hosting providers based in the states.

**Comment by creativeanalyst** [comment]
Thank you for clarifying.
Need to know if there are any set of questionnaires for US compliance like corporate compliance laws as an example are available or documented anywhere.

**Comment by evilaliv3** [comment]
@creativeanalyst, unortunately not i've many examples to provide but not relate to the US.

If you would like to share me some official documents i may try to reproduce them or try to guide you on this.

I invite you and your team to join us on lur slack at: https://slack.globaleaks.org

**Comment by creativeanalyst** [comment]
I am new to this software platform but so far what I have learned it seems very stable and promising so learning customization features mainly to setup custom questions so plan to research to fine real use case examples to try for corporate compliance. 
We can close this issue. If needed any help for questions setup, I will create new issue with appropriate title.
