### ISSUE TITLE
Some try site settings options are not working

### ISSUE THREAD

**Issue by creativeanalyst** [globaleaks/GlobaLeaks#2949]
Noticed that following site setting are not working when site is setup using. 
Don't see any changes as per setting values entered for those fields.

https://try.globaleaks.org/#/

Question to solicit possible whistleblowers

Whistleblowing button 
 Enable disclaimer

Title 

Text

Footer

**Comment by evilaliv3** [comment]
The settings configured would change your instance. If you would like to pass me the address of your demo instance i may verify that it is working properly.

thank you

**Comment by creativeanalyst** [comment]
Thank you. Here is instance name starting with anonymous.try.......

**Comment by creativeanalyst** [comment]
You can submit test submission if you want to try and see.

**Comment by creativeanalyst** [comment]
Initially when I noticed these settings were not working, I assumed some of those settings may not be designed or disabled to work with multitenancy.

**Comment by evilaliv3** [comment]
Thank you! It should be working now.

**Comment by creativeanalyst** [comment]
Thank you for quick fix and response. 
I tested and some are fixed but noticed footer is still not displayed as per footer text settings.

**Comment by evilaliv3** [comment]
You are right, i was thinking to have unlocked this. Please try again now.

**Comment by creativeanalyst** [comment]
Thanks and this issue can be close now. I tested those settings and site works fine.

**Comment by creativeanalyst** [comment]
All issues seems resolved.
