### ISSUE TITLE
Try site signup use case field question

### ISSUE THREAD

**Issue by creativeanalyst** [globaleaks/GlobaLeaks#2950]
During signup of any new try site, system asks to select use case option from available choices for use case field. 
Question - Is site created differently based on choice selected for use case field?

For example one of the choice available for use case field is 'Corporate Compliance' so wondering does that selection change list of available default set of questions for the trial site created.

**Comment by evilaliv3** [comment]
The use case question is intended to be used for statistic reasons but is actually not ussed.

**Comment by creativeanalyst** [comment]
Thank you and that helps to know.
