### ISSUE TITLE
New feature - Question Type of Lookup type

### ISSUE THREAD

**Issue by creativeanalyst** [globaleaks/GlobaLeaks#2951]
Requesting to allow additional question type of 'Lookup' 

This will allow user to select item from long list of available choices which are stored in a separate table.
I believe this request will impact functionality for these two main areas of application user interface,
1. Allow admin user to maintain a table with list of available choices via UI or import from text file containing list of choices
2. Allow admin user to use this new question type in building templates and questionnaires

It looks currently following list of questions types are supported.
Single-line text input
Multi-line text input
Selection box
Multiple choice input
Checkbox
Attachment
Terms of service
Date
Date range
Map
Question group

**Comment by evilaliv3** [comment]
Thank you for your feedback @creativeanalyst 

Actually your feature is in overlap with the one already defined in https://github.com/globaleaks/GlobaLeaks/issues/1389.
I will then close this issue and feel free to eventually annotate your ideas there.
