### ISSUE TITLE
Question about 'Additional questionnaire'

### ISSUE THREAD

**Issue by creativeanalyst** [globaleaks/GlobaLeaks#2953]
Noticed 'Additional questionnaire' option at two places with the same label so wondering how they are different.
I see these option when I select any context and also see same option under advance settings for a selected context.

**Comment by evilaliv3** [comment]
Actually the option is the same but duplicated when we decided to move the configuration to the advanced settings.

**Comment by creativeanalyst** [comment]
Okay so what is happening if settings are not same? Which one takes precedence?

**Comment by evilaliv3** [comment]
actually there are the same but just duplicated and i'm going to remove one of the two

**Comment by creativeanalyst** [comment]
Thank you very much @evilaliv3 
Yes, that will be helpful

**Comment by evilaliv3** [comment]
Correction implemented in commit https://github.com/globaleaks/GlobaLeaks/commit/8914e9e2a9b470f1300fa28b33d58d7c8eef2eee

The patch will be included started from release 4.0.10
