### ISSUE TITLE
Domain forwarding Error/Refusing to connect

### ISSUE THREAD

**Issue by creativeanalyst** [globaleaks/GlobaLeaks#2954]
Getting following error when I try to set our domain forward with masking option selected to this trial site

anonymous.try.globaleaks.org refused to connect.

**Comment by evilaliv3** [comment]
Did you configure your DNS to point to try.globaleaks.org with a
configuration of type CNAME before trying this option?

**Comment by creativeanalyst** [comment]
Thank you! Forwarding is now working without masking name. I was trying masking option.
