### ISSUE TITLE
Questionnaires - Way to move any question from one set(Tab) to another set

### ISSUE THREAD

**Issue by creativeanalyst** [globaleaks/GlobaLeaks#2959]
Checking if there is any way to move any question from one set (tab) to other set.

**Comment by evilaliv3** [comment]
This is something still to be implemented.

I consider that it would be worth to be able to move  question to a different step (tab) or to a different field group.

**Comment by creativeanalyst** [comment]
Here is one possible approach I am thinking. Each question can be part of only one group and one set so two editable fields (Group and Set) at the question level on UI possibly can help to move questions between group and set by changing value in those two fields. 
There may be some other possible approach to add such feature.

**Comment by evilaliv3** [comment]
Yes, i consider as well that we could limit the group of questions to one single level.

would you like to develop this improvement or draft a possible UI?

**Comment by creativeanalyst** [comment]
Sure, I can create some draft UI mockup for your review.

**Comment by creativeanalyst** [comment]
It looks this will be major enhancement but for sure improve user experience mainly for admin user.

Adding two new editable 'Group' and 'Set' fields at the question level. 
Both fields will of drop-down type, required and allow single value select from the choice of available values.  
Available possible values these two new fields will need to be dynamical maintained by the system as user adds/removes group and set type questions or modifies its name.
Will have to restrict user creating duplicate name for both fields to avoid any confusing when they names as available option for respective field.
Anytime user makes changes for any of the field, will require rearranging questions in impacted groups and sets.

**Comment by evilaliv3** [comment]
Closing as duplicated ticket for: https://github.com/globaleaks/GlobaLeaks/issues/2714
