### ISSUE TITLE
Receiver welcome screen and footer customisation no longer working.

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2965]
**Current behavior**
This is related to a previous question #2593. I had managed to customise recipient welcome screen and footer using instructions you provided and a JavaScript file. Since updating to v4.1.xx this does not work any more.

**What is the motivation or use case for changing the behavior?**
It is important to provide specific instructions to recipients.

**GlobaLeaks version:**
v4.1.11

**Server Operating System and Version (if applicable):**
Ubuntu 18.04LTS

**Comment by evilaliv3** [comment]
The variable GLClient is now simply renamed GL.

Would you please check if this is the case of your failure?

**Comment by elbill** [comment]
@evilaliv3 thanks. That seems to do the trick.
