### ISSUE TITLE
Inclusion of case report text, not visible to the whistleblower.

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2969]
It would be great to have a feature that would allow the recipients to store a text, like a case report or conclusion, that will not be visible to the whistleblower. When a case is closed or even before that.

**What is the motivation or use case for changing the behavior?**
It would be useful to include such information since  case reports contain lessons learnt or other useful information that could be stored and evaluated later. Whistleblowers having access to this information could put the organisation in legal risk.

**Comment by evilaliv3** [comment]
Thank you @elbill; this is actually something discussed in https://github.com/globaleaks/GlobaLeaks/issues/1957.

Im closing this to keep the discussion on the same thread then we may identify specific tickets to be opened for proper specification.
