### ISSUE TITLE
After I've setup the HTTPS subdomain there is noting on it

### ISSUE THREAD

**Issue by DawieFouche** [globaleaks/GlobaLeaks#2971]
Hi All 

Please assist me 

After i've setup the domain blow.peyperwhislte.co.za (HTTPS in Network settings) and completed the SSL setup. The domain stays blank. The TOR domain is working great.

**Comment by evilaliv3** [comment]
Thank you @DawieFouche for your question.

Actually this ticketing system is not for project supprot but for reporting software bugs or discussing features.
For questions related to project support please use https://forum.globaleaks.org or https://slack.globaleaks.org that are the channels dedicated to community support. Thank you!
