### ISSUE TITLE
The seach function dosen't work

### ISSUE THREAD

**Issue by NoahBohme** [globaleaks/GlobaLeaks#2978]
In the recepients overview there is a search function. The search function doen't seem to work properly 

![billede](https://user-images.githubusercontent.com/43778295/112482729-a6dc9d00-8d78-11eb-9047-9a793598e7e9.png)

**Comment by evilaliv3** [comment]
Hi @NoahBohme , thank you for reporting this

Does the name of some of this recipient include special characters?

**Comment by evilaliv3** [comment]
Corrected! The fix will be included in upcoming version 4.2.0

**Comment by NoahBohme** [comment]
When will 4.2.0. be publiched?

**Comment by evilaliv3** [comment]
In the upcoming weeks, with no precise schedule as it does not include any security fix.
