### ISSUE TITLE
"Mark as important" gives an error when activated in list view

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2979]
**Describe the bug**
"mark as important" gives an error when activated in report list view
It works ok when activated in report view.

**To Reproduce**
Using multiple contexts
in an existing report select the "mark as important star" gives an error.
When selecting the report and press the little star in the report view it works OK.
We get an error when deselecting the mark as important.  

**Expected behavior**
Would expect to work without error.
**Screenshots**

**Desktop (please complete the following information):**
win 10
latest chrome browser

ver 4.1.17

**Comment by evilaliv3** [comment]
Thank you for reporting this @elbill; I confirm that this could be retested and fixed to be added in 4.2.0

**Comment by evilaliv3** [comment]
Corrected! Thank you!
