### ISSUE TITLE
File upload cancels on submit

### ISSUE THREAD

**Issue by FlokiNET** [globaleaks/GlobaLeaks#2986]
**Describe the bug**
Fileupload breaks while pressing submit in case the upload is still active.
If the upload is 100% but not yet fully uploaded (the last 1-2 seconds) and you press submit the case will be created without the file to be attached.

**To Reproduce**
1. Upload a file via tor or clearnet
2. Click on submit while uploading
3. For a second warning appears that the upload is still in progress but then the report without the upload is submitted.

**Expected behavior**
The warning prevents the user from submitting an upload while the upload is still active

**Comment by evilaliv3** [comment]
Thank you for reporting this @FlokiNET 

After you reported this to me i actually issued this patch that should resolved this bug: https://github.com/globaleaks/GlobaLeaks/commit/985f095d17891e4c202a2caa78634a5bc4355993

The patch has been included in release 4.2.0 and is now installed as well on try.globaleaks.org. Do you mind to check if it works for you to solve the issue?

Thank you!

**Comment by evilaliv3** [comment]
Closing as the patch has been confirmed to be working
