### ISSUE TITLE
Malfunction of graphic file changes for context in Globaleaks 4.2.1

### ISSUE THREAD

**Issue by oeleaks** [globaleaks/GlobaLeaks#2990]
In the newest version of Globaleaks 4.2.1

Now the graphics for contexts are working again.

Unfortunately it is not possible to change the graphic, if one was selected.

The new file is not displayed.

It is only possible to delete the context, and make a new one with a new graphic.

**Comment by evilaliv3** [comment]
Thank you @oeleaks , i think this bug that you are encountering is only affecting who have installed 4.2.0 and configured an image on 4.2.1.

Given this particular condition i would suggest you to delete the offending entry in the File table manually so to not complicate the implementation.

would it work for you? Reach me on slack if you need assistance. Thank you for your patience and i'm sorry for the inconvenience.

**Comment by evilaliv3** [comment]
If you want just to try fixing the db try just deleting every entry in
the file table by using "sqlitebrowser"

I'm interestred as well if you could do a plain intall of globaleaks
4.2.2 to see if you sill get this issue or if it is solved for you.

Thank you!
