### ISSUE TITLE
Names of uploaded files are not shown, instead of that alphanumeric strings

### ISSUE THREAD

**Issue by oeleaks** [globaleaks/GlobaLeaks#2993]
In Globaleaks 4.2.2 the real names of uploaded files are not shown in settings any more, but alphanumeric strings like

**Comment by evilaliv3** [comment]
Thank you for reporting this @oeleaks. This is actually a visual defect instroduced since 4.2 that we will fix in the next viable update.

**Comment by evilaliv3** [comment]
Actually the issue here lies in the fact that the files that are loaded to customize contexts and users shall not be shown in this interface.

I confirm that we are going to be issuing a patch for this that will be included starting from version 4.2.3.
