### ISSUE TITLE
Submit button showing Error message

### ISSUE THREAD

**Issue by agboat** [globaleaks/GlobaLeaks#2994]
We have recently created installed the GlobaLeaks application 
https://amanah.bukhatir.ae/#/

Once the questions are filled and submitted and "Error" message is displayed on the top of the screen.

In the context the user has been added as well.

![image](https://user-images.githubusercontent.com/82876188/115380149-558ec480-a1e3-11eb-8d0c-84640dc294e9.png)

Please advise.

Thanks

Adeel

**Comment by evilaliv3** [comment]
Thank you @Almad 

I just tried to look at your system and perform a submission and i noticed that submissions appear disabled due to a failure.

Please check that you have enough space on the disk and try to restart the system to see if the error resolves.

**Comment by Almad** [comment]
That would be for @agboat

**Comment by evilaliv3** [comment]
Ah! thank you!

**Comment by agboat** [comment]
Thank you very much. We have assigned 50Gb space for this. I there any minimum requirement that we need to allocate.

Regards


Adeel Agboatwala
Head of Group Internal Audit

Phone: +971 6 512 6032
Mobile: +971 55 1513043
Email: ***@***.******@***.***>

**Comment by evilaliv3** [comment]
Actually all depends on the amount of submissions and the expected file size of the attachment you estimate to receive and as well on the data retention policy that you have defined in your organizations.

In globaleaks you could set some threshold limits for this situations here:
![Screenshot_2021-04-21 GLOBALEAKS - Advanced settings](https://user-images.githubusercontent.com/217034/115548924-53db0480-a2a8-11eb-8ab1-d30d367435bd.png)
