### ISSUE TITLE
Recipient can not dowload uploaded files from other recipients

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2996]
**Describe the bug**
One recipient when pressing the download button for the file that one other recipient has upladed for teh whistleblower, this does not download.
The recipient can download only the files he/she has uploaded.
Have not tested what happens on whistleblower side (if teh WB can download those files)

**To Reproduce**
one recipient upload a file on an existing submission
the other recipient can not download

**Expected behavior**
would expect all recipients to be able to downoad all files by pressing download

**Comment by evilaliv3** [comment]
Fixed in https://github.com/globaleaks/GlobaLeaks/commit/1e5b8143a866052bdc01eed14b5b43240622ef64

Patch included starting from GlobaLeaks 4.2.0
