### ISSUE TITLE
Can not update from 4.1.17 to current version

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#2997]
**Describe the bug**
Can not update from 4.1.17 to current version

**To Reproduce**
apt-get update && apt-get upgrade

apt-get update && apt-get install globaleaks

I get the error

Err:8 https://deb.globaleaks.org bionic/ Release.gpg
  The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
Fetched 164 kB in 1s (165 kB/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://deb.globaleaks.org bionic/ Release: The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Failed to fetch http://deb.globaleaks.org/bionic/Release.gpg  The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree
Reading state information... Done
globaleaks is already the newest version (4.1.17).

**Expected behavior**
would expect to update to current version

**Comment by evilaliv3** [comment]
Duplicated https://github.com/globaleaks/GlobaLeaks/issues/2985
