### ISSUE TITLE
A bug on database migration 54 of version 4.2.0-3 is causing corruption of file customizations

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#2998]
A user has just reported that due to a bug in the database migration 54 of version 4.2.0-3 is causing corruption of file customization.

The bug has been identified and we are issuing a patch to be included in release 4.2.4 by today,

We notify to have stopped the repository to prevent accidental customization lost due to missing backup copies of the customization.

**Comment by evilaliv3** [comment]
@elbill: This patch works for a system passing from 4.1.X to 4.2.X.

Platforms that have already updated to 4.2.X should recover the damaged files uplodated as customizations via a backup copy.

**Comment by elbill** [comment]
ok.. I understand

**Comment by evilaliv3** [comment]
Fixed since version 4.2.7
