### ISSUE TITLE
Submissions disabled

### ISSUE THREAD

**Issue by agboat** [globaleaks/GlobaLeaks#2999]
Ever since we have installed this system we have not been able to submit any reports as an "Error" message  is displayed. Based on the previous ticket raised we thought his might be a space allocation issue and accordingly the space has been increased from 50 GB to 140GB in the server. However, the issue still persists and the following email is received from the system every few minutes:

![image](https://user-images.githubusercontent.com/82876188/116030502-be0af500-a66c-11eb-9ece-14dacc82a057.png)

The following anomalies were noted in the system: 

![image](https://user-images.githubusercontent.com/82876188/116030660-1fcb5f00-a66d-11eb-9c02-250e5e19ecc4.png)

The link to the site is :

https://amanah.bukhatir.ae/

Appreciate your advise on how to resolve this. Please note we have not been able to raise a single log yet and hence the space should be available in the server.

Thanks

**Comment by evilaliv3** [comment]
@agboat : Actually the notification says that your system has less than the free space on your system is less than the 10% of the total. This is probably the case for your exceptions notification.

Maybe one program on the system is failing and saturating the system with big log files?

**Comment by agboat** [comment]
Many thanks.

We have now changed the anomaly detection thresholds to 0 from the initial 3200 MB and the system now is accepting new submissions. We seem to have ample disk space (see screenshot below); however, the system seems to be picking an incorrect dick space and reporting an error (see screenshot).

We have the following questions:


  1.  Why would the system be picking an incorrect disk space?
  2.  Is the current fix sufficient for the system to work or we may face some issues in the future.

Thanks
Adeel



***@***.***D73C0F.8A8A3B90]

ERROR in LOGS was for Disk space:

***@***.***D73C0F.8A8A3B90]

But lot of disk space was free, it’s installed on root:

***@***.***D73C0F.8A8A3B90]

***@***.***D73C0F.8A8A3B90]

Settings for anomaly detection were:

***@***.***D73C0F.8A8A3B90]

Then we changed the settings to zero:

***@***.***D73C0F.8A8A3B90]

After restart of service error from logs was gone and we were able to do the submission:

***@***.***D73C0F.8A8A3B90]

***@***.***D73C0F.8A8A3B90]

Question are:

  1.  Why it’s not able to get the correct value for free disk space?
  2.  What we have done is workaround – what is fix or how to resolve this issue?

**Comment by evilaliv3** [comment]
Actually the filesystem diskspace is evaluated with this specific checks: 
```
def get_disk_space(path):
    statvfs = os.statvfs(path)
    free_bytes = statvfs.f_frsize * statvfs.f_bavail
    total_bytes = statvfs.f_frsize * statvfs.f_blocks
    return free_bytes, total_bytes
```

This returns the available diskspace in /var/globaleaks.

I suspect that due to some virtualization (docker) or other configurations specific to your system the value of this function could be inaccurate.

I would invite your sysadmin to think about this and do check if this is the case.
