### ISSUE TITLE
GPG error

### ISSUE THREAD

**Issue by rcolombow** [globaleaks/GlobaLeaks#3000]
**Describe the bug**
We want to upgrade from version  4.1.17 to 4.2.4 but in Debian 10.9 there is a GPG error when I do "apt-get update":
root@whistleblowingstg:/var/lib/apt/lists#  apt-get update
......                     
Ign:8 https://deb.globaleaks.org buster/ InRelease                        
Get:9 https://deb.globaleaks.org buster/ Release [744 B]
Get:10 https://deb.globaleaks.org buster/ Release.gpg [833 B]
Hit:11 http://apt.puppetlabs.com buster InRelease
Ign:10 https://deb.globaleaks.org buster/ Release.gpg
Reading package lists... Done
W: GPG error: https://deb.globaleaks.org buster/ Release: The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
E: The repository 'http://deb.globaleaks.org buster/ Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

Can you tell me if there is a problem on the repository and if can be resolved?
Thanks a lot
Bye

**Comment by evilaliv3** [comment]
Duplicated. See https://github.com/globaleaks/GlobaLeaks/issues/2985
