### ISSUE TITLE
Audit log not showing post upgrade

### ISSUE THREAD

**Issue by rcolombow** [globaleaks/GlobaLeaks#3001]
Hi, post upgrade from version  4.1.17 to 4.2.5  in Debian 10.9, we have a problem with "Audit log" menu: when selected, we have an error "Resource not found" and the page isn't showing.
Before the upgrade, the menu worked well showing the various accesses correctly.
There are no evident errors in the globaleaks.log for the upgrade process or after (see attach log).
Logging level in set to DEBUG and "Log accesses of internal users" option is enable.

Unfortunataly we don't find info in github or forum; can you give us some suggestions? 
Thanks a lot
[globaleaks.log](https://github.com/globaleaks/GlobaLeaks/files/6383484/globaleaks.log)

**Comment by evilaliv3** [comment]
Thank you for reporting this. Probably this is a bug introduced in 4.2.X and we will try to fix it in the next minor release.

**Comment by evilaliv3** [comment]
@rcolombow: Would you please share as well a copy of the file access.log? 

I just retested in our development enviroments and i'm currently not able to reproduce the bug.

Is globaleaks started via its own install script? Does the log files exist in the directory /var/globaleaks/logs/?

**Comment by rcolombow** [comment]
Hi,
I don't know why but now is all ok: same browser as before but now "Audit log" menu is ok (and in the new page there are data).
I honestly don't know why: maybe it's because I reopened the browser? I notice that the first entry I have in the "Audit log" tab is my first login post update. I suspect thatthere were no such entry before the update but I can not remember.

For your question:
- log in attach (access log is 2 hour behind)
- Yes, is started via its own install script
- Log files are in /var/globaleaks/log (without s)

Thanks 
rc
[access.log](https://github.com/globaleaks/GlobaLeaks/files/6385829/access.log)
[globaleaks.log](https://github.com/globaleaks/GlobaLeaks/files/6385830/globaleaks.log)

**Comment by evilaliv3** [comment]
The audit log in 4.2.0 is quite different and is now logging more
information.  For this reason you see only logs that were previously not
present.

I will close the ticket as solved. Feel free to re-open it if you will
re-encounter this bug.

thank you
