### ISSUE TITLE
release gpg signature invalid

### ISSUE THREAD

**Issue by TjebbeVQ** [globaleaks/GlobaLeaks#3002]
I was updating some packages on my ubuntu 20.04 server and https://deb.globaleaks.org focal/ Release.gpg pops with a:

"The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>"

This is probably due to the manually signing step upon release?

Can this be fixed or should I run the installation.sh script to update?

T.

**Comment by evilaliv3** [comment]
Duplicated. See #2985
