### ISSUE TITLE
Missing pyotp dependency causes failure in setup and startup of GlobaLeaks version 4.2.8

### ISSUE THREAD

**Issue by saxman717** [globaleaks/GlobaLeaks#3007]
Hello, I am trying to install globaleaks on a Debian 10 server and receive errors during the installation. Here’s what I see:

<PRIOR SUCCESSFUL INSTALLATION STEPS EXCLUDED>

systemd/system/haveged.service.
Setting up python3-setuptools (40.8.0-1) ...
Setting up python3-pbr (4.2.0-5) ...
update-alternatives: using /usr/bin/python3-pbr to provide /usr/bin/pbr (pbr) in                                                                              auto mode
Setting up tor-geoipdb (0.3.5.14-1) ...
Setting up python3-mock (2.0.0-4) ...
Setting up python3-pyasn1-modules (0.2.1-0.2) ...
Setting up python3-cryptography (2.6.1-3+deb10u2) ...
Setting up apparmor-utils (2.13.2-10) ...
Setting up python3-nacl (1.3.0-2) ...
Setting up python3-openssl (19.0.0-1) ...
Setting up python3-service-identity (16.0.0-2) ...
Setting up python3-josepy (1.1.0-2) ...
Setting up python3-acme (0.31.0-2) ...
Setting up python3-twisted (18.9.0-3) ...
Setting up python3-txtorcon (18.3.0-1) ...
Setting up globaleaks (4.2.8) ...
Job for globaleaks.service failed because the control process exited with error                                                                              code.
See "systemctl status globaleaks.service" and "journalctl -xe" for details.
invoke-rc.d: initscript globaleaks, action "start" failed.
● globaleaks.service - LSB: Start the GlobaLeaks server.
   Loaded: loaded (/etc/init.d/globaleaks; generated)
   Active: failed (Result: exit-code) since Wed 2021-05-12 15:03:32 UTC; 15ms ag                                                                             o
     Docs: man:systemd-sysv-generator(8)
  Process: 4577 ExecStart=/etc/init.d/globaleaks start (code=exited, status=1/FA                                                                             ILURE)

May 12 15:03:24 vultr.guest systemd[1]: Starting LSB: Start the GlobaLeaks serve                                                                             r....
May 12 15:03:24 vultr.guest globaleaks[4577]: Starting GlobaLeaks daemon: global                                                                             eaksEnabling Globaleaks Network Sandboxing...done.
May 12 15:03:31 vultr.guest globaleaks[4577]: Starting ...
May 12 15:03:31 vultr.guest globaleaks[4577]: Failed to load application: No mod                                                                             ule named 'pyotp'
May 12 15:03:32 vultr.guest globaleaks[4577]: failed.
May 12 15:03:32 vultr.guest systemd[1]: globaleaks.service: Control process exit                                                                             ed, code=exited, status=1/FAILURE
May 12 15:03:32 vultr.guest systemd[1]: globaleaks.service: Failed with result '                                                                             exit-code'.
May 12 15:03:32 vultr.guest systemd[1]: Failed to start LSB: Start the GlobaLeak                                                                             s server..
dpkg: error processing package globaleaks (--configure):
 installed globaleaks package post-installation script subprocess returned error                                                                              exit status 1
Processing triggers for systemd (241-7~deb10u7) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for libc-bin (2.28-10) ...
Errors were encountered while processing:
 globaleaks
E: Sub-process /usr/bin/dpkg returned an error code (1)

Any help with troubleshooting this error will be greatly appreciated. This happened when I tried installing on Debian 10 as well as Ubuntu 20.04 servers.

**Comment by evilaliv3** [comment]
Thank you for reporting this, this is a known bug that we are solving in 4.2.8.

It seems to be affecting only new setups where the pyotp is no longer setupped.

Release 4.2.8 had to remove the pyotp dependency but some components of the software were not updated accordingly.

This is the patch that will be released by today and will solve the issue: https://github.com/globaleaks/GlobaLeaks/commit/987deeb4a821424551d44e1a816853101174ed1d

**Comment by saxman717** [comment]
Great to hear that this is a known is and being worked.  Thank you very much for the update, evilaliv3!  Looking forward to the patch release

**Comment by strinux** [comment]
Helloe @evilaliv3  this is still a bug i also got it today this bug so what can i do ?

**Comment by evilaliv3** [comment]
We are going to release today a package 4.2.9 that fixes the issue.

You can temporarily install python3-pyotp to fix the issue on 4.2.8

**Comment by strinux** [comment]
ty @evilaliv3 , srr for bothering you guys you doing a really good work i love the software and the community take care <3
