### ISSUE TITLE
Unable to upload enable https 

### ISSUE THREAD

**Issue by riyesh** [globaleaks/GlobaLeaks#3014]
**Describe the bug**
The issue started after reissuing the letsencrypt SSL, always throwing an error " 
Error on input validation [" 

Bought another wildcard SSL from namecheap.com also giving the same error while uploading. 

For automatic update now showing an error on :-  
##########################

acme.messages.Error ACME error.\n\n    https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-00\n\n    :ivar unicode typ:\n    :ivar unicode title:\n    :ivar unicode detail:\n\n    \n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1416, in _inlineCallbacks\n    result = result.throwExceptionIntoGenerator(g)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/failure.py", line 491, in throwExceptionIntoGenerator\n    return g.throw(self.type, self.value, self.tb)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 479, in post\n    yield tw(db_acme_cert_request, self.request.tid)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 140, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 171, in tw\n    return f(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/https.py", line 461, in db_acme_cert_request\n    cert_str, chain_str = letsencrypt.request_new_certificate(hostname,\n\n  File "/usr/lib/python3/dist-packages/globaleaks/utils/letsencrypt.py", line 87, in request_new_certificate\n    order = client.new_order(csr)\n\n  File "/usr/lib/python3/dist-packages/acme/client.py", line 666, in new_order\n    response = self._post(self.directory['newOrder'], order)\n\n  File "/usr/lib/python3/dist-packages/acme/client.py", line 95, in _post\n    return self.net.post(*args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/acme/client.py", line 1171, in post\n    return self._post_once(*args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/acme/client.py", line 1184, in _post_once\n    response = self._check_response(response, content_type=content_type)\n\n  File "/usr/lib/python3/dist-packages/acme/client.py", line 1042, in _check_response\n    raise messages.Error.from_json(jobj)\n\nacme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many certificates already issued for exact set of domains: wb.masaood.abudhabi: see https://letsencrypt.org/docs/rate-limits/\n

###############################

installed the latest with update  ./install-globaleaks.sh still the same and the new update removed the Header. 

the current version : globaleaks-4.2.10
previous version globaleaks-4.1.6

total two  issues  
1, unable to activate the SSL
2, header removed after Update.

**Comment by evilaliv3** [comment]
Than you @riyesh 

Actually i consider that what happened on your system is the following:
- you were running 4.1.6 that is know to not be up-to-date with letsencrypt updates and this was causing you to have failing renewal attempts
- you are now using 4.2.0 but your system is prevented to get a new certificate due to an exceeded limit of attemps

I would just suggest you to wait 24 and retest or to try the renewal on an alternative temporary dns name.

**Comment by riyesh** [comment]
hi

is it possible to use the third party SSL certificate which I bought?

**Comment by evilaliv3** [comment]
Yes, you need just to use the manual https configuration instead of the automatic one.

Jusr reset the HTTPS configuration and select manual configuration.

**Comment by riyesh** [comment]
thank you.  One more doubt... The header bar is removed on the new version ?

**Comment by evilaliv3** [comment]
No, the header bar is implemented like the previous but we considered to change the default background color that is more neutral.

p.s.: if possible please open different tickets per different issues and prefer the [forum](https://forum.globaleaks.org) or [slack](https://slack.globaleaks.org) for questions like this.
