### ISSUE TITLE
Issue with reports when disabling a hidden context

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3015]
**Describe the bug**
Having multiple contexts, I have 1 activated and one hidden. When making a report through the url of the hidden context everything works fine. The report shows with the hidden context name in the case management list.
When deactivating the hidden context, multiple reports, even from active context are affected. No context name is shown and no status as well.

**To Reproduce**
Make some submissions to the active context.
Then make some submission to the hidden context.
Deactivate the hidden context.
Some of the active context repots will be affected.
I also have the impression that when a hidden context is deleted then some of the active context reports may also disappear.

**Expected behavior**
I would not expect any reports to be affected by deactivating a hiden or any context.
When deactivating a context I would like all repots (from hidden or other contexts) to stay as they are  

**Additional context**
up to date version of globaleaks and chorome

![screen2](https://user-images.githubusercontent.com/23246886/119983625-106f6680-bfc9-11eb-8d0b-977d596733ab.png)
![screen1](https://user-images.githubusercontent.com/23246886/119983631-1402ed80-bfc9-11eb-8dac-5b757cbe980e.png)

**Comment by evilaliv3** [comment]
@elbill : in your reporting you use both the word "deactivating" and the word "deleting".

would you please clarify among the two:
1) the error is generated when deactivating the context
2) the error is generated when deleting the context

than you

**Comment by elbill** [comment]
the error is generated when deactivating the context.
(I suspect that issues may arise when deleting a context)

**Comment by evilaliv3** [comment]
ok thank you for clarifying.

Let me check. I expect the issue to be only visual and i think to confirm that there should not be any issue in relation to context deletion as well.

let me verify right away and get back to you.

**Comment by evilaliv3** [comment]
@elbill : I confirm that the error was only visual.

The platform was failing to show the data of disabled contexts and thus impacting subsequent report visualization.

The above patch fixes the problem and will be included in a new minor release 4.0.11.

(p.s.: please do not consider hidden contexts as private; the globaleaks API is /api/public is a public resource that transparently shows this informations to users that would eventually query it; the full software is built with transparency in mind)
