### ISSUE TITLE
Recipients give temporary access to specific reports for non authorised recipients or other persons 

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3024]
**Is your feature request related to a problem? Please describe.**
This is loosely related with #2556, however with no whistleblowing choice or action. 
A recipient may have to share the content of a report through the platform with another person or group of persons in the organisation.
that person may be a signed up recipient (with no access to the specific context) or any other person within or outside the organisation.

**Describe the solution you'd like**
A solution where someone would be able to "share a report" to a specific person (recipient or not registered).
That would happen through a bullet menu that you would tick the recipients that you want to share the report with and untick to withdraw. Or for a limited time. The new recipient should receive a notification through their email.

**Describe alternatives you've considered**
The only alternative so far is to export and email which is not optimal.

**Additional context**

**Comment by evilaliv3** [comment]
Thank you @elbill  for your feedback.

Would you please help me clarifying your needs so that we could eventually split this ticket in more or analyze if others tickets are already tracking this requirements?

- The possibility to grant access ex post to a submission to an existing or new sytem user is tracked by https://github.com/globaleaks/GlobaLeaks/issues/2595 and is already considered in the next development as part of current roadmap
- The possibility to grant an external user access to a submission is tracked by and still requires significative analysis
- In your ticket you use the word "temporarily": whould you please clarify if you just intend that you want to share access ex post the submission or if really mean that the access should be time-limited ?

**Comment by elbill** [comment]
The possibility to grant access ex post to a submission to an existing or new sytem user is tracked by Make it possible for recipients to add a new recipient to their submissions #2595 and is already considered in the next development as part of current roadmap
**-> This is great news. I did not see the ticket before when searching . We could integrate the comments in that ticket I suppose. If you had a very rough timeline, it would be appreciated.**

The possibility to grant an external user access to a submission is tracked by and still requires significative analysis
**-> I understand the complexirties of it. Would be nice to have however the previous case would cover most user cases I can think of.**

In your ticket you use the word "temporarily": whould you please clarify if you just intend that you want to share access ex post the submission or if really mean that the access should be time-limited ?
**-> The temporarily would be either time restricted, and/or to be able to stop the access. If I had to choose between the two I would choose to be able to retract access, in a similar way it was granted.**

**Comment by evilaliv3** [comment]
Thank you.

In relation to ticket #2595 actually we do not have a timeline at the moment unfortunatelybut i would say by 2021.

The feature considered evaluate the possibility that a recipient could grant other recipients visibility to tickets that they have access to but it was never considered to make it possible to revokate access that i consider could be abused by recipients to silence some corruption case that involve them. For this reason the only revocation considere is the full revocation of privileges that an administrator could operate on the entire user account.

**Comment by elbill** [comment]
Fair enough. Revocation is not that important as the feature itself, and I can see the complexities. Could actualy agree more with the aproach you take.
Would be great indeed if you can implement the feature this year!

**Comment by evilaliv3** [comment]
Thank you for the feedback.

I have your same ideas.

I think we need a new priviledge for this like "Enable this recipient to
grant user access to reports"


This is necessary to limit who can extend/revoke access. In fact you may
want user A to grant access to user B but you do not want user B to revoke
access to user A.

**Comment by elbill** [comment]
Indeed! Something like only first level authorisation to grant/revoke. Whoever has been granted access can not further grant/revoke access. Simple and neat. Sounds great.

**Comment by evilaliv3** [comment]
@elbill: i'm thinking to add this configuration option in the user configuration of recipients: "Give this recipient ability to grant user access to reports"

Would you understand it?

\cc @larrykind

**Comment by elbill** [comment]
@evilaliv3 I'm biased, but I believe I would understand it. A longer version could be :
Give this recipient ability to grant non authorised user access to reports

**Comment by larrykind** [comment]
Hi everyone and thank you @evilaliv3 to invite me to this discussion.
I agree about everything has been said, I try to add our thoughts to contribute to this feature:

- In the admin user configration there should be a checkbox to choose which receiver can grant/revoke access to other receivers
- Think about a "per ticket" or full grant, choosing into allowed users (the upsaid "elected" users) obviously except receiver itself, even though for the purposes of ANAC regulatory compliance, it could be sufficient to allow one or more users to handle the report, even jointly with the original operator.
- a flag to "follow" the ticket for the user that grants, this should eventually enable email advertisements to him for ticket status change, chat, attachments.
- when a users is elected to manage a ticket, it should receive an email that tells the user it can manage the ticket.
- **(to evaluate...)** Per user granted there could be a menu to choose if the grant will be: 
    - enable ticket status change to the granted user _(yes by default)_
    - enable chat and file exchange to the granted user _(yes by default)_
- Think about put receiver itself as "read-only" for some tickets, and ticket can't be revoked while in this status.

Interesting thing that could be done in this way is that user that grant only could be the default receiver for the context, and the other ones, they will be collaborators. So they will manage only assigned tickets, and the "master recievers" will mainly receive tickets.

**Comment by elbill** [comment]
@larrykind I very much agree with your last bullet that it would be desirable to have the possibility of a read only access for the grantees (if technically feasible). 
Regarding the (to evaluate) I believe the grantee should be responsible for disabling notifications, in the same way as all users do). A separate menu I believe would overcomplicate things in many ways(if I understand well your suggestion).

**Comment by evilaliv3** [comment]
Thank you for your feedback @larrykind  and @elbill

Within this ticket i propose we could work on implementing a first simple feature with the following simple characteristics: the future shall make it possible for a user enabled with a specific privilege to extend or revoke access to other users.

Do you agree that this is the main need that could satisfy your use cases?

Then eventually  we could try to work on the rest of the proposed features (if really needed), but i think the will require more analysis and much more development.

**Comment by elbill** [comment]
@evilaliv3 I agree and I'm looking forward to it!

**Comment by larrykind** [comment]
Thank you @evilaliv3 and @elbill for considerations about my scratch.
@evilaliv3 yes the main need is the on you exposed, but if it could be possible I suggest also to put in the roadmap the mentioned "read-only" feature. 

I just add one other consideration: 
In this use case, there should be a chat between administrators: in large companies there usually are lots of receivers (20-30 recerivers) with more role partialization of anti-corruption managament, and these roles could be managed not only by the company itself, but also lawyers, generically externals. 
So chat between administrators in my opinion should fit very well whitin this use case, so they can manage the ticket just using globaleaks. 
As a worst alternative to the chat should be ok initially also to have a note field aside to the status change box.
Please consider it. Thanks.

**Comment by evilaliv3** [comment]
Closing as the main feature has been implemented. If you consider that some changes to be applied please open specific tickets.
