### ISSUE TITLE
Include whistleblower login key code box in the submissions page. 

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3026]
**Is your feature request related to a problem? Please describe.**
While the key code box exists only in the landing page. Sometimes it is required that the landing page is the submissions page, to avoid an extra step. However no key code box exists there. I have the impression that in older versions it also existed in the submissions page.

**Describe the solution you'd like**
It would be useful to give an option to include it somewhere up right in the submissions page.

**Describe alternatives you've considered**
Sideloading it in the header of page if possible, not sure if this is doable.
**Additional context**

**Comment by evilaliv3** [comment]
The feature was actually removed from the top right section while re-enginering a component and then we considered to not re-add it as not significatively useful.

Considering your feedback we will try to re-add during next development. Thank you.

**Comment by elbill** [comment]
Just to add that I suspect that when whistleblowers may go to submit button by mistake, and when they realise that they need to enter the key code, they have to go back, refresh the page. So a non intrusive but evident keycode box, as it was before will be useful. Would be nice if you could reintegrate it.

**Comment by evilaliv3** [comment]
Thank you. I just looked at the changelog in order to understand which where the suggestions that we received that lead us to change this interface.

The reasons are actually in relation to usability on mobile phones that make the application not well responsive as you could see in the example below.

![Screenshot 2021-07-08 at 16-38-39 GLOBALEAKS](https://user-images.githubusercontent.com/217034/124941291-fdf63d00-e00a-11eb-832d-3e83f2b19c98.png)


![Screenshot 2021-07-08 at 16-33-28 GLOBALEAKS](https://user-images.githubusercontent.com/217034/124941113-d69f7000-e00a-11eb-9e36-14aad4fbafbf.png)

Probably before re-integrating this as it was we should evaluate alternatives that could use less space and be responsive.

**Comment by elbill** [comment]
To be honest the keycode box looks fine to me in both examples.
The privacy warning is huge, so it takes some additional space. However it does not discourage the user to scroll. Scrolling is easy on mobile devices.
The alternative would be to hide it through settings, or I suppose you can hide it using css (or will that hide the landing page box?)
I'm not a UI UX expert, but as a user looks fine to me (and previously never crossed my mind it takes unnecessary space).

**Comment by evilaliv3** [comment]
I understand you feedback .

Actually from usability perspective both the two screenshots are wrong. The first show that a general misalignment happends in any situation, while the second shows that the layhow could even break (look at the white space created on the right side that provese the layout is compleyely disaligned from the border of the device)

**Comment by evilaliv3** [comment]
The following design seems to work well on both wide and small screens:

![Screenshot 2021-07-08 at 22-09-00 GLOBALEAKS](https://user-images.githubusercontent.com/217034/124984651-c81c7d00-e039-11eb-9700-2b83051d1df8.png)

![Screenshot 2021-07-08 at 22-09-43 GLOBALEAKS](https://user-images.githubusercontent.com/217034/124984672-ce125e00-e039-11eb-92ca-6b313dd257a2.png)

Would it work for you @elbill if the receipt interface will show up only when the direct link to /#/submission will be used?

**Comment by elbill** [comment]
Aesthetically I prefer for first screenshot the box to be aligned with the
language pull down menu. Both aligned right to where the language menus is
The second looks fine.
I suppose it would be fine to work only for /#/submissions

**Comment by elbill** [comment]
Something like this.
Now that I looked your original picture on my laptop and not on my mobile, your version looks ok, if what I have designed is difficult to implement. 

![124984651-c81c7d00-e039-11eb-9700-2b83051d1df8](https://user-images.githubusercontent.com/23246886/124988194-5eef3680-e046-11eb-9a42-4d7482580843.png)

**Comment by elbill** [comment]
Appart from the #/submission link it should be integrated in the individual
context links. The lack of key code box renders them useless.

**Comment by evilaliv3** [comment]
Thank you for your feedback.

Actually my examples are not alternatives. I just shown to you how the interface behave on a big and on a small screen.

I will try to work on your suggestion, in the meantime i invite you to look at your setups on mobilephones and see how they behave on the different pages.

**Comment by evilaliv3** [comment]
Ok i think to manage the way out to handle responsiveness of this components in a way that it works better.

Here the same new layout applied on: desktop, galaxy s9, iphone 8, iphone xs

![Screenshot 2021-07-09 at 08-10-17 GLOBALEAKS](https://user-images.githubusercontent.com/217034/125037187-1bbbb480-e094-11eb-9d24-a5ae10e2b3bb.png)
![Screenshot 2021-07-09 at 08-57-33 GLOBALEAKS - Whistleblowing Portal of Antani](https://user-images.githubusercontent.com/217034/125037022-f62eab00-e093-11eb-9a75-55a099b04c0c.png)
![Screenshot 2021-07-09 at 08-57-12 GLOBALEAKS - Whistleblowing Portal of Antani](https://user-images.githubusercontent.com/217034/125037023-f6c74180-e093-11eb-9c09-5b8988e568a4.png)
![Screenshot 2021-07-09 at 08-57-00 GLOBALEAKS - Whistleblowing Portal of Antani](https://user-images.githubusercontent.com/217034/125037025-f6c74180-e093-11eb-8cfe-5c309dad3bcf.png)

**Comment by elbill** [comment]
Everything looks great!
