### ISSUE TITLE
No notifications received

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3031]
**Describe the bug**
From 4.2.10 in a specific platform no notifications were received. When updated to 4..2.12 all notifications came at once. I thought the problem was solved. However I still get no status updates.
When I test the notification configuration through admin interface I receive a confirmation email.
I also reset the notification configuration to default but no change. 
When I set up a new user, I get through email the relevant link.
On an other tenant the configuration works just fine and I receive updates.
The platform with the issue is only in Greek.

**To Reproduce**
Comment on existing report and no update notification received through email

**Expected behavior**
Would expect to receive notifications when commenting or updating a report

**Comment by evilaliv3** [comment]
Thank you for reporting this @elbill 

Do you see any error in the file /var/globaleaks/log/globaleaks.log ?

Would you please try to reset the notification templates to default and tell me if this fixes the issue?

**Comment by elbill** [comment]
@evilaliv3 apologies. The problem has been resolved with the 4.2.12 update. I mistakenly was expecting to receive a notification for my test report.
