### ISSUE TITLE
Unlock "blow the whistle" button only if "informations" pop-up button has been clicked

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3040]
Hi, 
"informations" pop-up section could be sometimes very important or mandatory to be read from the whistleblower before to proceed with the ticket.
In this case the "blow the whistle" button should be unlocked only after "informations" (if present) pop-up button has been clicked. This way, receivers are sure that whistleblowers accepted what is written in that pop up.

**Comment by evilaliv3** [comment]
Thank you for the feedback @larrykind.

I applied the following changed:
1) The submission page now opens only when the proceed button is clicked.
2) In case the user will click cancel the user will remain on the home page of the application
3) Further clicks of the button will scatter new modal openings.
