### ISSUE TITLE
Blocking accounts after multiple logon errors

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3042]
Currently there is no blocking of accounts, when a user is submitting false credentials multiple times. Would it be possible to add a counter and block an account after a given number of retries? (account should still be retrievable by using the recovery key)

Currently only a "slow down" process is invoked cf. the manual:

**Slowdown on Failed Login Attempts**
The system identifies multiple failed login attempts and implement a slowdown procedure where an authenticating client should wait up to 42 seconds to complete an authentication.

This feature is intended to slow down possible attacks requiring more resources to users in terms of time, computation and memory.

**Comment by evilaliv3** [comment]
Thank you for your feedback @schris-dk; This feature is actually described and analyzed on ticket https://github.com/globaleaks/GlobaLeaks/issues/532

I would invite you to read the current evaluations and add your suggestions.
