### ISSUE TITLE
Whistleblower policy page

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3046]
Hi!

Request for an option that EVERY site needs - a whistleblower policy page.

Accoridig to the directive, all whistleblower sites need a whistlebloer policy, thatr users can refer to before submitting a report.

Currently we ar only able to create a link to a filer for download or add it to a questionaire page in a thext field.

I'd suggest, that a seperate page containing the policy should be shown right after the first click on the "report" button on the first page. This way it is ensured, that the policy is shown and accepted before the whistlebloswer is heading on with the reporting.

The content of the policy could be added as an extra field (or pane) on the "Site Settings" page. This fiels would then be able to leverage on the other system fields, making it possible to create a generic policy using info from the fields - e.g. using {NodeName} as name of the company, which then automatically is added to the policy

Just an idea :-)

/soren

**Comment by evilaliv3** [comment]
Thank you @schris-dk; i actually think that you may be not aware.

1) The disclaimer feature that enable to configure a disclaimer modal that is shown when the button report is clicked.

configuration in site settings:
![Screenshot_2021-09-14 GLOBALEAKS - Site settings](https://user-images.githubusercontent.com/217034/133253542-39762abb-74a9-42da-8a38-97f460dc22ea.png)

result:
![Screenshot_2021-09-14 GLOBALEAKS](https://user-images.githubusercontent.com/217034/133253566-163b510e-4350-4ee9-84df-97eb4eefafa7.png)

2) The questions of type "Terms and Conditions" that enable you to configure custom terms and conditions questions with related acceptance.

questionnaire configuration:
![Screenshot_2021-09-14 GLOBALEAKS - Questionnaires](https://user-images.githubusercontent.com/217034/133253480-763c26b8-1e96-481c-a6c7-fded4c0680ee.png)

result:
![Screenshot_2021-09-14 GLOBALEAKS(2)](https://user-images.githubusercontent.com/217034/133253523-9b22d87b-674b-43f2-8d59-35af00692bd3.png)
Please let me know if this is what you need and if you confirm that this ticket is not necessary.

**Comment by schris-dk** [comment]
Ahh - of course - this is just smth we have disabled - thnx for clarifying :-)

**Comment by evilaliv3** [comment]
Thank you. I will close the issue then, please let me know if you have any question.
