### ISSUE TITLE
Possible regression on 4.3 in relation to TLS implementation: ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3049]
Hi

After upgrading to v4.3, all sites are unaccessible. I get the folowing error in browser:

```
The connection for this site is not secure *** uses an unsupported protocol.
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
Unsupported protocol
The client and server don't support a common SSL protocol version or cipher suite.
```

**Comment by aetdr** [comment]
previous information is from MS Edge, In Firefox I get this:

```
Secure Connection Failed

An error occurred during a connection to ***. Cannot communicate securely with peer: no common encryption algorithm(s).

Error code: SSL_ERROR_NO_CYPHER_OVERLAP

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the web site owners to inform them of this problem.
```

**Comment by evilaliv3** [comment]
Thank you for reaching our @aetdr 

Would you please share me a link to the platform?

I would like to test it with: https://www.ssllabs.com/ssltest

**Comment by aetdr** [comment]
- ssllabs only return this "Assessment failed: Failed to communicate with the secure server"
- tried to acces the server (127.0.0.1) using openssl and wget localy from the machine, I still get an error
- the server is running

**Comment by evilaliv3** [comment]
Try to access via the onion address of the server and re-generate a certificate for the server.

Would you pleae provide me the following informations?
1) issue this command against your server: echo -n | openssl s_client -connect www.google.com:443
2) are you using letsencrypt or a certificate issued by your provider?

**Comment by aetdr** [comment]
openssl output:

```
openssl s_client -connect 127.0.0.1:443
CONNECTED(00000003)
140284021499200:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../ssl/record/rec_layer_s3.c:1543:SSL alert number 40
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 283 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---

```

**Comment by aetdr** [comment]
seem like the server is not sendig the certificate

**Comment by aetdr** [comment]
we are not using letsencrypt

**Comment by evilaliv3** [comment]
I would suggest to log in via the onion service and try to perform a full reconfiguration of HTTPS.

**Comment by aetdr** [comment]
Hi @evilaliv3  
No there should be no proxy involved. The openssl output is directly from localhost.
I am going to restore to an earlier snapshot and see if I can reproduce the issue.

**Comment by evilaliv3** [comment]
Okay!

If you could, after restoring your system please send me a full screenshot of the report by ssllabs. You could reach me on slack. Accessing the report would make it possible to debug the issue identifying what we could have changed in release 4.3.0

Thank you

**Comment by aetdr** [comment]
np, I will reach you via slack

**Comment by evilaliv3** [comment]
@aetdr: Do you have any update on this issue? Do you confirm that the issue has been resolved?

**Comment by aetdr** [comment]
Yes, the issue is resolved by reinstalling globaleaks.
Prior reinstalling globaleaks we had to run `apt-get update` to work with the most recent globaleaks version.
