### ISSUE TITLE
Test notification settings bug

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3051]
In a multitenant setup, when an user login to a secondary site with a global admin account and try to test SMTP settings by clicking on "Test the configuration" button, an error pops up. Seems like the backend is expecting the admin to be local user.

Response:
`{"error_message": "InternalServerError [Unexpected]", "error_code": 1, "arguments": ["Unexpected"]}`

**Comment by evilaliv3** [comment]
Thank you for reporting this @aetdr, i've actually been able to reproduce the bug and i'm going to issue a patch that will be included in release 4.3.1.
