### ISSUE TITLE
"Request support" feature - links not shown in WebUI

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3052]
Hi

Tried to test the new "Request support" feature. I log in as an user with the recipient role, but the link is not present anywhere.
Could reproduce the issue with two separate globaleaks instances.

**Comment by aetdr** [comment]
can actually see the link when accessing /login/passwordreset site as an anonymous user , but not the other links that require an authenticated user.

**Comment by evilaliv3** [comment]
Thank you for reporting this @aetdr, this is probably a bug introduced during the finalization of the feature where we considered to limit this feature to recipients users.

Let me fix this right away.
