### ISSUE TITLE
Unable to create new tenant after upgrade to v4.3.2

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3054]
Hi

I am not able to create new tenants after upgrade to v4.3.2
Seem related to removal of the enable_rc_to_wb_files flag

From the log:

`
[E] sqlalchemy.exc.IntegrityError Wraps a DB-API IntegrityError.\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context\n    self.dialect.do_execute(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute\n    cursor.execute(statement, parameters)\n\nsqlite3.IntegrityError: NOT NULL constraint failed: context.enable_rc_to_wb_files\n\n\nThe above exception was the direct cause of the following exception:\n\n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext\n    result = inContext.theWork()\n\n  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>\n    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext\n    return self.currentContext().callWithContext(ctx, func, *args, **kw)\n\n  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext\n    return func(*args,**kw)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 152, in _wrap\n    result = function(session, *args, **kwargs)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/tenant.py", line 98, in create_and_initialize\n    db_wizard(session, tenant.id, '', wizard)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/wizard.py", line 112, in db_wizard\n    context = db_create_context(session, tid, context_desc, language)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/admin/context.py", line 150, in db_create_context\n    context = db_add(session, models.Context, request)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 77, in db_add\n    session.flush()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2479, in flush\n    self._flush(objects)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2617, in _flush\n    transaction.rollback(_capture_exception=True)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__\n    compat.reraise(exc_type, exc_value, exc_tb)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 153, in reraise\n    raise value\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2577, in _flush\n    flush_context.execute()\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute\n    rec.execute(self)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 586, in execute\n    persistence.save_obj(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 239, in save_obj\n    _emit_insert_statements(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements\n    result = cached_connections[connection].execute(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 982, in execute\n    return meth(self, multiparams, params)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1095, in _execute_clauseelement\n    ret = self._execute_context(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context\n    self._handle_dbapi_exception(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception\n    util.raise_from_cause(sqlalchemy_exception, exc_info)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 152, in reraise\n    raise value.with_traceback(tb)\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context\n    self.dialect.do_execute(\n\n  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 581, in do_execute\n    cursor.execute(statement, parameters)\n\nsqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: context.enable_rc_to_wb_files\n[SQL: INSERT INTO context (id, tid, show_steps_navigation_interface, show_recipients_details, allow_recipients_selection, maximum_selectable_receivers, select_all_receivers, enable_comments, enable_messages, enable_two_way_comments, enable_two_way_messages, enable_attachments, tip_timetolive, name, description, show_receivers_in_alphabetical_order, score_threshold_high, score_threshold_medium, score_receipt_text_custom, score_receipt_text_l, score_receipt_text_m, score_receipt_text_h, score_threshold_receipt, questionnaire_id, additional_questionnaire_id, languages, status, "order") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]\n[parameters: ('c28fccf2-f5ad-4974-a984-28bfbcb94538', 28, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 90, '{"en": "Default"}', '{"en": ""}', 1, 0, 0, 0, '{"en": ""}', '{"en": ""}', '{"en": ""}', 0, 'default', '', '', 1, 0)]\n(Background on this error at: http://sqlalche.me/e/gkpj)\n`

**Comment by evilaliv3** [comment]
Thank you @aetdr 

This regression was not spotted by unit tests because related only to existing platforms migrated to the new version.

The above patch will fix the issue and is going to be included in release 4.3.3

**Comment by evilaliv3** [comment]
@aetdr: Actually verifying this issue in more details i noticed that to fix it properly we need to implement a database migration.

For this reason the previous fix would work bad with different results depending if users hava already updated to 4.3.1 or not.

For this reason in order to fix tis properly i'm just going to issue a new pagage 4.4 implementing an empty migration script that will work as a fix for both the conditions.
