### ISSUE TITLE
Unable to upload file bigger than 1MB on release 4.4.0

### ISSUE THREAD

**Issue by ArminLaschet** [globaleaks/GlobaLeaks#3055]
I can't download documents uploaded by the whistleblower. The whole layout of attachments changed. I can now see only the document title - no upload date, no button for download. I've tried multiple browsers, but it's the same problem everywhere.

**Comment by evilaliv3** [comment]
Thank you for reporting this @ArminLaschet 

I've already debugged the issue and will issue a fix by today in a release 4.4.1.

The bug actually lies in the impossibility of uploading files bigger than 1MB.

If you try to upload a file that is smaller you shoud be in fact be able to see the file download button correctly.

**Comment by ArminLaschet** [comment]
Thank you, that was really quick. I'll try again later today or during the week and let you know.

**Comment by evilaliv3** [comment]
@ArminLaschet: you could now update to version 4.4.1 that fixes this regression.

Thank you for reporting it

**Comment by ArminLaschet** [comment]
Thank you for the update. It fixed the problem in most cases. However, we've still got one case with over 80 uploaded attachments, which still does not work. I suppose we are over the capacity of GL.
