### ISSUE TITLE
Missing LogEntries

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3057]
Hi!

Just been asked for a log from one of our clients. The site has been running for more than one year, but oldest log entry is 030521.  No entries on user creation, login etc - only 4 entries with login faliure - shouldn't logs be kept indefinitely?

**Comment by evilaliv3** [comment]
Thank you for your question @schris-dk 

Actually:
- The GlobaLeaks AuditLog is a recent feature that is carefully implemented in a privacy preserving way to get sure logging do not impact on the privacy of the whistleblowing process
- The log on your system depends on the date on which you updated to the version that added the log capability and added the log types that were added.
- I confirm that in the actual implementation the log is currently preserved indefinitely and we are not aware of any bug in the implementation.
- On ticket #2579 you could find the list of the up to date tracked operations.  We welcome your suggestions on the log entries that should be added and we will try to collect funding for further improve this feature.
