### ISSUE TITLE
Impossibile rinnovare certificati automaticamente con Certification Authority Let's Encrypt

### ISSUE THREAD

**Issue by AntasIT** [globaleaks/GlobaLeaks#3059]
Buongiorno,
in Impostazioni di rete sotto alla voce HTTPS, provando ad procedere con la Configurazione automatica  dell'hostname whistleblowing.antas.org, riceviamo il seguente messaggio: Errore! Errore interno del server (Unexpected).

![image](https://user-images.githubusercontent.com/91600659/135246808-1842bd9a-9970-4003-9cbd-3074c781e6d0.png)

Il software è aggiornato alla versione 4.4.1. 
OS: Windows 10 Pro 2004 19041.1237
Browser: Microsoft Edge 94.0.992.31

Chiediamo Vostro supporto per capire e risolvere il problema.

Grazie
AntasIT

**Comment by evilaliv3** [comment]
Gentile @AntasIT, è possible che abbiate aggiornato ora dopo un lungo periodo di mancato aggiornamento?

Siamo a conoscenza di un solo malfunzionamento presente in versoni inferiori alla 4.2.6, In tale versioni il rinnovo del certificato dava esito in un fallimento e il ripetersi della situazion portava ad un blocco temporaneo del fornitore LetsEncrypt per 24 ore.

Se la condizione fosse questa potete ora semplicemente attendere 24 ore e il problema dovrebbe risolversi automaticamente.

Dovreste avere conferma di questo anche nel file di log /var/globaleaks/log/globaleaks.log in cui dovreste avere registrata una eccezione che dice che non è possibile rinnovare il certificato a causa di troppi tentativi falliti.

**Comment by AntasIT** [comment]
Buongiorno @evilaliv3, confermo che siamo passati recentemente dalla versione 4.1.6 alla versione 4.4.1.

Abbiamo provato questa mattina a rieseguire il comando per la Configurazione automatica, purtroppo continuiamo a ricevere lo stesso messaggio di errore:

![image](https://user-images.githubusercontent.com/91600659/135586013-a03548e3-8d33-42ee-9171-e5535804c717.png)

[globaleaks.log](https://github.com/globaleaks/GlobaLeaks/files/7265281/globaleaks.log)

Allego il file di log aggiornato a poco fa, il problema sembra essere proprio quello da voi citato:

There were too many requests of a given type :: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: whistleblowing.antas.org: see https://letsencrypt.org/docs/rate-limits/

Purtroppo il periodo di attesa nel nostro caso è di 168 ore, è possibile azzerare questo periodo di attesa prendendo contatto con  Let's Encrypt?

Grazie per il supporto

**Comment by evilaliv3** [comment]
Buongiorno @AntasIT, non so dirle purtroppo circa letsencrypt perchè non vi siamo in contatto ma un tentativo può valere la pena.

In alternativa se vuole ripristinare temporaneamente può mettere un certificato self signed o acquisirne uno alternativo.

Impotante che non facciate molti tentativi durante il periodo di blocco o temo incorrerete in un aumento del periodo di attesa.
