### ISSUE TITLE
Messages appears in recipient and whistleblower interface even when private annotations  is disabled 

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3060]
**Describe the bug**
Messages appears in recipient and whistleblower interface even when private annotations  is disabled 

**To Reproduce**
I believe I had enabled private annotations at some point to test. Can not disable.

**Expected behavior**
I would expect the private annotations checkbox to enable or disable messages

Globaleaks version 4.4.1

**Comment by evilaliv3** [comment]
Hey @elbill !

Actually this is designed intentionally this way to support real situations where users changed configurations.

Imagine to real life scenarios where you enable both comment and messages, you receive some submissions and then you discover that you do not want anymore to enable messages; In this situation you will probably want anyhow to show users the messages that arrived before flipping the configuration.

Please let me know if this makes sens to you and the issue could be closed.

**Comment by elbill** [comment]
Its clear. Thanks.
