### ISSUE TITLE
Error on input validation on manual SSL upload

### ISSUE THREAD

**Issue by dustin-fci** [globaleaks/GlobaLeaks#3062]
**Describe the bug**
We are trying to upload a new SSL cert and keep receiving 'Error on input validation []'. It doesn't matter which we try to upload.

**To Reproduce**
Try to upload any of the SSL files manually

**Expected behavior**
Upload SSL files

**Desktop (please complete the following information):**
 -  W10
 - Chrome (v94.0.4606) Brave (v1.29.81)
 
**Additional context**
Server
Ubuntu 18.04
GL 4.4.3

**Comment by evilaliv3** [comment]
Thank you @dustin-fci for notifying this.

Would you please confirm that the files that you are trying to load are in PEM format?

If you would like please reach me on slack and share the certificate file so that i could look at it.

**Comment by dustin-fci** [comment]
@evilaliv3 

Found it. There was an issue with the PEM files. This is working now.
Thanks!
