### ISSUE TITLE
Make it possible for recipients to see real user names 

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3064]
**Is your feature request related to a problem? Please describe.**
When recipients send messages to whistleblowers and "do not expose users names" is activated in the advanced settings whistleblower does not see the recipient name which makes sense. However the recipients can not see the other recipients' names either which may be confusing in terms of who replied.
The same happens when a user grands access to another recipient. They only see the generic name which can be very confusing and lead to errors.
The workaround would be to use a public alias (without hiding the public name), which can also be confusing sometimes (who is user 1, user 2 ? etc) and lead to error. This also takes some time to communicate with everybody to set up their public names.

**Describe the solution you'd like**
I believe it would make sense the recipients to be able and see the other recipients'' names when "do not expose users names" while the whistleblowers to see the generic platform name.

**Comment by evilaliv3** [comment]
Thank you for this feedback @elbill, it definitely makes sense.

I will try to revise this with priority.

**Comment by elbill** [comment]
@evilaliv3 It would also be great if the same was the case for comments. The recipints would be able to see real names while the whistleblower would be able to see the generic platform name. And when a recipent exports the report the text file to contain the real recipient names.

**Comment by evilaliv3** [comment]
Feature implemented and released in package 4.4.4
