### ISSUE TITLE
Unable to download attachments

### ISSUE THREAD

**Issue by ArminLaschet** [globaleaks/GlobaLeaks#3065]
In some cases, the layout of the table of uploaded documents is broken - I can only see the name of the document, but not the upload date, no download button. The problem is still basically the same as described in #3055. The upade following #3055 helped in some cases, but there are still a couple of cases with a lot of attached documents, where the table does not work.

**Comment by evilaliv3** [comment]
@ArminLaschet: Are you able to replicate the issue on try.globaleaks.org?

Would you please try to document the steps to reproduce the issue and attach some screenshots?

Thank you if you could make it.

**Comment by evilaliv3** [comment]
After discussing with @ArminLaschet  we identified that the issue was just a visualization problem that has been fixed in release 4.4.4 improving the responsiveness of the interface.
