### ISSUE TITLE
Ability to change content on recipient home page

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3072]
When a recipient logs in to Globaleaks they land on the /recipient/home page with following hardcoded content:

```
Welcome!

    For the user documentation, visit: docs.globaleaks.org
    If you need technical support, have general questions, or have new ideas for the software: forum.globaleaks.org
    If you want to contribute to software development or report a bug, please open an issue in our ticketing system: github.com/globaleaks/GlobaLeaks
    Join our chat: slack.globaleaks.org
    Follow the project on: Twitter
```

It is possible to translate it but not to remove or change the text/links.

We want to add our own text and we want recipients to contact our own support. 
The text they see now is misleading. We should be able to control this.

**Comment by evilaliv3** [comment]
Thank you for your feedback @aetdr, we wil try to keep this into consideration during the next development.

Currently this is only doable with a Javascript configuration using the Mock utilities: https://github.com/globaleaks/GlobaLeaks/issues/2363

**Comment by aetdr** [comment]
The js approach does it quite well, it fixes our problem.

**Comment by evilaliv3** [comment]
Re-opening this ticket to possibly implement in the future of configuration of this page.
