### ISSUE TITLE
The Close button in the "Request support" window is not translated.

### ISSUE THREAD

**Issue by JackBRN** [globaleaks/GlobaLeaks#3084]
When any other than English language is set, the "Request support" window is translated except the Close button, which is always in English.

![Request-support](https://user-images.githubusercontent.com/93597718/139867361-91f4f736-8f6c-45ef-a462-105a339d9470.jpg)

The "Request support" window is accessible via lifebuoy icon from backend (next to logout) and frontend, on the Password reset page.

GlobaLeaks version: 4.4.4

**Comment by evilaliv3** [comment]
Thank you for reporting this @JackBRN. The issue will be fixed starting from release 4.4.6
