### ISSUE TITLE
javascript issue since upgrade to v4.4.5

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3086]
Hi

Admins are recieveing this error message by mail since upgrade to v4.4.5

```
Error Message: Error: [$compile:ctreq] Controller 'flowInit', required by directive 'flowDrop', can't be found!
https://errors.angularjs.org/1.8.2/$compile/ctreq?p0=flowInit&p1=flowDrop
```

**Comment by evilaliv3** [comment]
Thank you @aetdr

On which page are you when you get this exception?

**Comment by aetdr** [comment]
Hi @evilaliv3 

It happens on different pages as /admin/users or /recipient/preferences
Could it be a js caching issue?
