### ISSUE TITLE
Can not update from 4.4.4 to 4.4.6

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3089]
**Describe the bug**
Can not update from 4.4.4 to 4.4.6

Error message
CW: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://deb.globaleaks.org bionic/ Release: The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Failed to fetch http://deb.globaleaks.org/bionic/Release.gpg  The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by evilaliv3** [comment]
Thank you @elbill

Actually release 4.4.6 is still not officially released but you could now update correctly to 4.4.5
