### ISSUE TITLE
File size not accepted: "undefined" in error message.

### ISSUE THREAD

**Issue by JackBRN** [globaleaks/GlobaLeaks#3090]
**Describe the bug**

Word "undefined" appears in error message that inform about too big file. 

![file_size](https://user-images.githubusercontent.com/93597718/140296828-240d2cb5-4208-40e0-a40e-ee82b2b271ea.jpg)

**To Reproduce**
In the new report, attach file bigger than limit set for file attachments.

GlobaLeaks 4.4.4

**Comment by evilaliv3** [comment]
Thank you for reporting this.

This issue seems related to a regression introduced with commit https://github.com/globaleaks/GlobaLeaks/commit/73985880ee71457f9919ee994534ea0c21854d95 and present since release 4.1.0
