### ISSUE TITLE
Context requires double click to open

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3093]
Pertaining GL v. 4.4.5

We have encountered an issue with context pages which  on click opens and shuts immediately here after. A second click will open the page.

The error is ramdomely occurring, and no patern is seen yet.

/soren

**Comment by evilaliv3** [comment]
@schris-dk: What you mean with "context pages"?  Do you get this issue when using the application as administrator or whistleblower?

I got a similar issue as whistleblower if i'm visiting the platform after changing the language. Do you get the same?

**Comment by evilaliv3** [comment]
Closing; This fix will be released in release 4.5.2
