### ISSUE TITLE
No user public name admin option is given in the admin interface

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3094]
**Describe the bug**
No public name configuration option is given in the admin interface for users.
While I believe hide identity feature has been disabled, admin can not configure the public name of a recipient.
 
**Expected behavior**
I would expect both admin and user to be able to configure the public names.

**Comment by evilaliv3** [comment]
Thank you for reporting this @elbill 

Actually the "public name" feature has not been deprecated but is simplified to the possibility to configure public names by recipients.

I'm going to extend this capability to the admin user so that administrators could configure it.

**Comment by evilaliv3** [comment]
Implemented.

I will be released starting from 4.5.2
