### ISSUE TITLE
autologout issue

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3096]
If a recipient logs in, navigates to a specific submission, than is inactive for a while, the session expires.
When the session is expired, the recipient is still able to click around and see limited cached content, without beeing notified that the session is expired.

Expected behavior: When the session is expired, the user is notified and redirected to /login page.

**Comment by evilaliv3** [comment]
Thank you for your feedback @aetdr.

I will close this ticket as partially duplicated with https://github.com/globaleaks/GlobaLeaks/issues/2842 and https://github.com/globaleaks/GlobaLeaks/issues/603
