### ISSUE TITLE
Disable/enable the whistleblower's access to Private messages

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3099]
Hi!

Currently it is not an option to disable the view of the Private messages on the page shown to the whistleblower. This would be a really nice feature, as this will leverage the recipients to discuss the matter internally within the platform - but without showing this discussion to the whistleblower.

Giving this option, we will provide a full "ecosystem" for the recipients and later added experts etc. to have all their communication in one secure platform.

**Comment by evilaliv3** [comment]
Thank you for the feedback @schris-dk 

Actually this feature is already disscused here: https://github.com/globaleaks/GlobaLeaks/issues/2452

We consider that possibly the messages feature could be extended to support communications among recipients
