### ISSUE TITLE
error when can_edit_general_settings user flag is enabled

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3101]
Hi

In case where a recipient has `can_edit_general_settings` flag turned on, and a site uses translation other than the default en - when the user clicks on "Site Settings", GET request is sent to `/api/admin/l10n/lc` that returns following error:

`{"error_message": "Not Authenticated", "error_code": 10, "arguments": []}`

**Comment by evilaliv3** [comment]
Thank you let me fix this right away!
