### ISSUE TITLE
link issue introduced with commit 79e6f3f

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3102]
Hi

there is one `target="_target"` in tab1.html

`<a data-ng-if="resources.node.rootdomain" class="badge badge-primary" data-ng-href="https://{{tenant.subdomain}}.{{resources.node.rootdomain}}" target="_target" isolate-click>{{tenant.subdomain}}.{{resources.node.rootdomain}}</a>`

commit:
79e6f3f - Replace automatic link sanitizer with an explicit rel=noreferror target=_blank attributes

**Comment by evilaliv3** [comment]
thank you for noticing this @aetdr .

I'm going to fix this right away.

**Comment by evilaliv3** [comment]
Thank you!
