### ISSUE TITLE
recipient not able to delete submission attachments uploadet by themselves

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3105]
Hi

In relation to #3100 , if recipient uploads an attachment to a submission, even if the delete button is visible, they are not able to delete the file by clicking on the button.

Behavior we expect:

- If the file has not been viewed or downloaded by the whistleblower, uploading recipient should be able to delete the file
- If the file is viewed or downloaded by whistleblower, recipients should not be able to delete the file

**Comment by evilaliv3** [comment]
Thank you for spotting this @aetdr !

**Comment by evilaliv3** [comment]
Corrected. The fix fillw be included in relese 4.5.4
