### ISSUE TITLE
Add URL to support requests emails

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3107]
Hi!

The current support request mail only contains the email address of the requestee and the request it self.

Would it be possible to add the portal name to this mail - it will make the identification  of the user easier (e.g. in the case where a generic mail like Gmail or Hotmail is used as recipient address)

**Comment by evilaliv3** [comment]
Thank you for your valuable feedback @schris-dk!

This is definitely a good suggestion. Let me implement a patch right away.

**Comment by evilaliv3** [comment]
@schris-dk: Actually i consider that the functionality could be even improved to collect the original URL that the user is navigating when asking for support.

This will make it possible not only to know the site that the user is using but also the exact page on which the user had trouble.

What do you think?

**Comment by schris-dk** [comment]
Would be absolutely perfect 😊

I admire the speed that you react on our reporting and requests 😊 – Highly appreciated 😊

/soren

Fra: Giovanni Pellerano ***@***.***>
Sendt: 15. november 2021 11:06
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Add portal name to support request (Issue #3107)


@schris-dk<https://github.com/schris-dk>: Actually i consider that the functionality could be even improved to collect the original URL that the user is navigating when asking for support.

This will make it possible not only to know the site that the user is using but also the exact page on which the user had trouble.

What do you think?

**Comment by evilaliv3** [comment]
Thank you Soren! This software has grown slowly but successfully thank to a large set of significant use cases.

I'm now learning how to interact with you all to be more fast and get fast and relevant suggestions and this simplify our work so that we could proceed more fast as well but still in a safe manner.
