### ISSUE TITLE
No warning given when system asks user to change password and user uses same password.

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3108]
**Describe the bug**
This is a minor bug where no warning is given when system asks user to change password and user uses same password.

**To Reproduce**
System asks to user (admin) to change password.
User uses same password.
Nothing happens.
Password is not changed but user may be confused.

**Expected behavior**
Would expect system to issue a warning that password will have to be different (this was the case before if I remember well).

**Comment by evilaliv3** [comment]
Thank you @elbill, the issue that yo uare reporting is actually a regression just introduced in 4.5.4 :/

Let me fix it right away and the interface should be like the following:
![Uploading Screenshot_2021-11-15 GLOBALEAKS - Change your password.png…]()
