### ISSUE TITLE
Language on headline in form switches from local language to English

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3109]
Just discovered a minor bug. When switching from the "case overview" to a selected case, the headline switches to English - see pictures below (this is not a severe thing :-))
![image](https://user-images.githubusercontent.com/70965554/141765391-5f3fb5c9-ca6c-4ad6-8590-6fcdc847fa74.png)

![image](https://user-images.githubusercontent.com/70965554/141765539-d45c36d3-dfd4-4290-88d2-fda16833faba.png)

**Comment by evilaliv3** [comment]
Thank you @schris-dk for notifying it.

Actually even if the string was previously translated it seems that by mistake we removed it from our localization index.

I'm going to fix this that will be correct in the next release.
