### ISSUE TITLE
Some platforms have been affected after upgrade to 4.5.4

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3110]
**Describe the bug**
Landing page works ok. 
Nothing happens after entering platform 

**Screenshots**

**Additional context**
Version: 4.5.4

URL: /

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

Error Message: TypeError: Cannot read properties of undefined (reading 'forcefully_selected')

Stacktrace:
[
  {
    "columnNumber": 244768,
    "lineNumber": 64,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "source": "    at https://epathla.fraudline.gr/js/scripts.min.js:64:244768"
  },
  {
    "columnNumber": 1541,
    "lineNumber": 8,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "functionName": "Object.x [as forEach]",
    "source": "    at Object.x [as forEach] (https://epathla.fraudline.gr/js/scripts.min.js:8:1541)"
  },
  {
    "columnNumber": 244678,
    "lineNumber": 64,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "functionName": "Object.t.setContextReceivers",
    "source": "    at Object.t.setContextReceivers (https://epathla.fraudline.gr/js/scripts.min.js:64:244678)"
  },
  {
    "columnNumber": 263362,
    "lineNumber": 64,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "functionName": "Object.onAnswersUpdate",
    "source": "    at Object.onAnswersUpdate (https://epathla.fraudline.gr/js/scripts.min.js:64:263362)"
  },
  {
    "columnNumber": 662963,
    "lineNumber": 64,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "source": "    at https://epathla.fraudline.gr/js/scripts.min.js:64:662963"
  },
  {
    "columnNumber": 101422,
    "lineNumber": 8,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "functionName": "d.$digest",
    "source": "    at d.$digest (https://epathla.fraudline.gr/js/scripts.min.js:8:101422)"
  },
  {
    "columnNumber": 103102,
    "lineNumber": 8,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "functionName": "t.$apply",
    "source": "    at t.$apply (https://epathla.fraudline.gr/js/scripts.min.js:8:103102)"
  },
  {
    "columnNumber": 151932,
    "lineNumber": 8,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "functionName": "HTMLButtonElement.<anonymous>",
    "source": "    at HTMLButtonElement.<anonymous> (https://epathla.fraudline.gr/js/scripts.min.js:8:151932)"
  },
  {
    "columnNumber": 17501,
    "lineNumber": 8,
    "fileName": "https://epathla.fraudline.gr/js/scripts.min.js",
    "functionName": "Rt",
    "source": "    at Rt (https://epathla.fraudline.gr/js/scripts.min.js:8:17501)"
  },
  {
    "columnNumber": 20371,

**Comment by elbill** [comment]
It happens when a user is disabled. I had reported this bug once more.

**Comment by elbill** [comment]
I enabled the use and it worked. However it also happens in a platform with no disabled users.

**Comment by evilaliv3** [comment]
Thank you @elbill , is it possible for you to pass me a link to a platform and some credentials that i could use to retest this bug?

If you can, please send me this information via slack and i will check this right away.

**Comment by evilaliv3** [comment]
Nevermind @elbill, i should have found the bug and i confirm that it is just a visual bug related to platforms with users that are disabled but attached to a context.

I'm about to issue a patch that will be included in 4.5.5

**Comment by elbill** [comment]
On the other platform there is no disabled user. Does this make sense?

**Comment by elbill** [comment]
I've messaged you on slack

**Comment by evilaliv3** [comment]
Thank you. I confirm that this issues has been solved and the fix will be included today in release 4.5.5
