### ISSUE TITLE
Minor issue with autologout feature

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3111]
Hi

In multisite setup, when I log in to TID 1 as an admin, if the session expires I do get redirected to the login page. Works fine.

In the same context, if I have open a secondary site from TID 1 as global admin, when the secondary-site session expires I don't get redirected. Instead an error is shown in uper left part of the screen each time I try to navigate around by clicking on a link.

Response:
`{"error_message": "Not Authenticated", "error_code": 10, "arguments": []}`

**Comment by evilaliv3** [comment]
Thank you, i've corrected this behavior and the fix will be included today in 4.5.5.
