### ISSUE TITLE
Page description not editable

### ISSUE THREAD

**Issue by timopitt** [globaleaks/GlobaLeaks#3113]
Unable to change the text for the description at page settings in tab main configuration.

**To Reproduce**
1. Go to 'page settings' > 'tab main configuration'
2. Change language
2. Change the text in field  'description'
3. Save
4. Text doesn't change and was reset to the default

**Expected behavior**
Save translated text or the 'descrition' is not an editable input

**Screenshots**
![image](https://user-images.githubusercontent.com/61874821/142404116-17b35ce9-dedf-40b3-9322-dd0213fdb88e.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser chrome

**Comment by evilaliv3** [comment]
Thank you for reporting this @timopitt 

I've just fixed the issue and the patch will be included in upcoming release 4.5.6.
