### ISSUE TITLE
error The repository 'http://deb.globaleaks.org focal/ Release' is no longer signed.

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3114]
Hi

When trying to update to newest Globaleaks release, we get this error:
```
Reading package lists... Done
E: The repository 'http://deb.globaleaks.org focal/ Release' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

**Comment by pawelek-org** [comment]
Same here, tried to add a key again but no luck.

`curl -L https://deb.globaleaks.org/globaleaks.asc | apt-key add`

**Comment by evilaliv3** [comment]
Thank you for reporting this. This happened during some maintainance of the repository.

All should work now.

**Comment by pawelek-org** [comment]
`Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  globaleaks
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 2386 kB of archives.
After this operation, 2048 B of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 https://deb.globaleaks.org bullseye/ globaleaks 4.5.6 [2386 kB]
Err:1 https://deb.globaleaks.org bullseye/ globaleaks 4.5.6
  File has unexpected size (2385344 != 2385792). Mirror sync in progress? [IP: 51.15.240.96 443]
  Hashes of expected file:
   - SHA512:7c472594f5729f4f66ca5bd0a4fbe7571953aae1151c6b2d5e92d2bee999014262c1531db86833b3a56c4f6b37be7ae15dbbc3c0f70bc757da622e043238cec3
   - SHA256:b439ef787ab64193918179b63ae7df34191dce51c4f1939209ce2ddf6ff83d2b
   - Filesize:2385792 [weak]
E: Failed to fetch https://deb.globaleaks.org/bullseye/globaleaks_4.5.6_all.deb  File has unexpected size (2385344 != 2385792). Mirror sync in progress? [IP: 51.15.240.96 443]
   Hashes of expected file:
    - SHA512:7c472594f5729f4f66ca5bd0a4fbe7571953aae1151c6b2d5e92d2bee999014262c1531db86833b3a56c4f6b37be7ae15dbbc3c0f70bc757da622e043238cec3
    - SHA256:b439ef787ab64193918179b63ae7df34191dce51c4f1939209ce2ddf6ff83d2b
    - Filesize:2385792 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?`

**Comment by pawelek-org** [comment]
> All should work now.

`File has unexpected size (2385344 != 2385792). Mirror sync in progress? [IP: 51.15.240.96 443]`

**Comment by evilaliv3** [comment]
Would you please issue apt-get update before issuing apt-get upgrade?

Please let me know if it won't work.
