### ISSUE TITLE
2FA appear not enforced on first login

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3117]
We have 2FA enforced on all secondary tenants (via advanced tenant settings).
When a new user registers, they are not prompted for 2FA registration at all.

Used to work before - current version 4.5.6

**Comment by aetdr** [comment]
Maybe this is related to that 2FA enforcing was switched off on TID 1 recently

**Comment by evilaliv3** [comment]
Thank you for reporting this @aetdr, i will check on this and keep you posted.

**Comment by evilaliv3** [comment]
@aetdr: Actually i just retested the feature using 2 tenants, enabling two factor authentication on both and then disabling the feature on the root tenant and all seems to work correctly.

Would you please perform your test again and let me know if it still won't work? It would be very helpful if you manage if you could pass me some instructions to reproduce the issue.

**Comment by aetdr** [comment]
hi @evilaliv3 

Before v4.5.6, when an user clicks on the invite link, og right after the password is provided and confirmed - the user gets prompted to complete 2FA creation. The user was not allowed to proceed before 2FA creation was done if 2FA was enforced site-wide.

The current behaviour  is that the user gets right in after password is created an confirmed. 
It happens first second time the user logs in that 2FA prompt shows up. 
Is this normal expected behaviour?

**Comment by evilaliv3** [comment]
Thank you for your feedback. I'm now able to reproduce the issue and could work on the fix.

I consider valuable to restore that the users are requested to configure two factor authentication as soon the activate their own accout.
