### ISSUE TITLE
The software should properly validate incorrect CIDR addresses provided as IP filters

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3118]
Hi

When there is defined an IP allow filter, it only works with up to two ranges separated by comma:

Will work:
```
10.0.0.0/8
10.1.0.0/16,10.2.0.0/16
```

Will not work (user get access denied):
```
10.1.0.0/16,10.2.0.0/16,10.3.0.0/16
```

**Comment by evilaliv3** [comment]
Thank you for reporting this @aetdr, i will check on this and keep you posted.

**Comment by evilaliv3** [comment]
@aetdr: Actually i just retested the feature using your ip ranges and all seems to work like a charm.

Here you could find the unit tests that specifically tests a configuration like your: https://github.com/globaleaks/GlobaLeaks/blob/main/backend/globaleaks/tests/utils/test_ip.py

Would you please recheck and let me know if you notice the reason of your issue?

**Comment by aetdr** [comment]
Hi @evilaliv3

We are not using those exact ranges.  
There is mix of internal and external ranges (first one is internal /8, second and third are external with netmask /21)
My test shows that error happens first when the third range is added (testing with filters on recipient user)

**Comment by evilaliv3** [comment]
@aetdr : Are you sure that when testing you are reaching the application with an IP address that fell inside the range?

Please verify exacly which is the IP received by the application.

**Comment by aetdr** [comment]
Hi @evilaliv3 

Jus did some additional testing.
Seem that the issue is triggered when provided IP ranges overlap.

**Comment by aetdr** [comment]
An example with overlapping ranges
```
10.0.0.0/8,80.80.122.0/21,80.80.126.0/21
```

**Comment by evilaliv3** [comment]
I've identified the bug.

The software currently is ignoring the two proposed ranges ```80.122.0/21``` and ```80.80.126.0/21``` because they are correct CIDR address as they have  some host bit set. 

I will issue a patch in order to refuse such a configuration by providing an error to the user.
