### ISSUE TITLE
Identity section - whistleblower identity in anonymous context exception

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3119]
**Describe the bug**
(Version 4.5.6) - If in questionnaire  wthistleblower identity default templete is set, if wber accesses to his report with 16digit code there are couple of issues:
1. only the first field is available to fill
2. if the  field is compiled and click enter or "submit" button is hit nothing happens and the attached exception is generated
3. tested with default or custom identity form

**To Reproduce**
1. Set a questionnnaire with default or custom wistleblower_identity and identity not mandatory
2. file an anonymous report
3. access the report with 16digit code
4. ----> identity template is like the attached one, and system generates attached exception when filled

**Expected behavior**
Identyt should be filled and submitted as in the questionnaire

**Screenshots**
Exception stack, identity field once accessed to report

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: pc
 - OS: w10
 - Browser firefox91
![identity](https://user-images.githubusercontent.com/61267901/142873750-0e4af819-1649-4e4e-943e-ffafb5821fa0.JPG)
[stack.txt](https://github.com/globaleaks/GlobaLeaks/files/7581668/stack.txt)

**Comment by evilaliv3** [comment]
@larrykind: At the moment i'm not able to reproduce the issue, would you please see if you are able replicate this issu by registeringa demo on try.globaleaks.org? Eventually if you manage you could just tell me the name of the created site and will then directly check it.

Thank you

**Comment by evilaliv3** [comment]
@larrykind ?

**Comment by larrykind** [comment]
@evilaliv3 
i tried to create an instance on try.globaleaks.org but when I set "whistleblower_identity" field, system seems to assign a single-line field to that template . So I can't test this issue on 4.5.8.

**Comment by larrykind** [comment]
closed as deprecated.

**Comment by evilaliv3** [comment]
Thank you!
