### ISSUE TITLE
Broken donations link in the github homepage of the project

### ISSUE THREAD

**Issue by iliasbartolini** [globaleaks/GlobaLeaks#3120]
**Describe the bug**
You have a link in the "Sponsor this project" section of github https://github.com/globaleaks/GlobaLeaks (on the right side)
pointing to https://www.globaleaks.org/donate/ that returns a 404 error

**Comment by evilaliv3** [comment]
Thank you so much @iliasbartolini for noticing and reporting this. I really appreciate your support.

Let me fix this right away!
