### ISSUE TITLE
Private annotations

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3124]
Hi

Some of our users are a bit upset about recent removal of private annotations 6e3ed6a899f48b1b66c29f9d84b84a3840e526c4
They used tags to privately link submissions to internal system IDs.

Is there any chance of getting it back?

**Comment by evilaliv3** [comment]
Hello @aetdr

Actually the labels have not been removed. There was just a bug on 4.6.0.

If you enable 4.6.1 they should be able to see all their label again.

When i refer to the removal of private annotations i refer to the fact that now labels are visible to all recipients that in the context of globaleaks are always part of the same team.

Please let me know if you have any question.

**Comment by aetdr** [comment]
Good news, thanks!

**Comment by evilaliv3** [comment]
Closing the ticker for now, please let me know if you will still have issues on this.
