### ISSUE TITLE
Perfomance issue on platforms with large number of reports

### ISSUE THREAD

**Issue by georgehndz** [globaleaks/GlobaLeaks#3125]
**Describe the bug**
When trying to see the alerts, it takes a long time to load the list of alerts.

**To Reproduce**
1. Ingress to login and password
2. Click in reports to recipient
3. Load the list to alert

**Expected behavior**
Response time must be less than 5 seconds

**Screenshots**
![image](https://user-images.githubusercontent.com/30553679/144510187-3e7de0e6-5b6e-40b1-9c1b-804a35219146.png)
![image](https://user-images.githubusercontent.com/30553679/144510227-b1018488-ff93-453c-9454-bdafa07779f0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Chrome 
 - Version:Versión 96.0.4664.45 (Build oficial) (64 bits)

**Additional context**
alerts currently do not expire.

**Comment by evilaliv3** [comment]
Thank you for your feedback.

This is a know performance issues that could be addressed by implementing pagination on the reports page.
Unfortunately at the moment we do not have suggestions to advise because our developers are focused on more general topics; what we could do is to check if some queries could be optimized to at least reduce the issue.

**Comment by evilaliv3** [comment]
@georgehndz: I'm generating a testing platform with 10.000 submissions in order to identify where is the main bottleneck and if a short term remediation could be applied.

**Comment by georgehndz** [comment]
@evilaliv3 Thank you very much for your attention

We are waiting for your tests to know the next step that we could apply.

**Comment by georgehndz** [comment]
Hi @evilaliv3 

I send you the specifications:
There are 9 recipient accounts and these are the characteristics of the server
![image](https://user-images.githubusercontent.com/30553679/144905389-b33882e1-05c6-4e54-ad30-a5515bb673ff.png)

**Comment by evilaliv3** [comment]
@georgehndz : Would you please update to 4.7.1 and let me know if this is enough to consider the issue fixed?

**Comment by evilaliv3** [comment]
@georgehndz : i'm going to close this ticket as fixed. Please let us know if you consider other improvements could be made.

**Comment by georgehndz** [comment]
Hi @evilaliv3 
I have applied all the changes except for the last one since the database version is very old and I think it would be better to update the product to its latest version as you recommended in your last comment.

I am going to verify if with the changes I improve the response of the platform.

**Comment by spaceracoon92** [comment]
Hello there. I`m working on the same system. It`s having performance issues again. Do You have new information that could help me to resolve the issue?
