### ISSUE TITLE
user creation and deletion is not logged in the audit log

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3126]
Hi

Currently, user creation and deletion is not logged in the audit log. 
Is this something that can get implemented?

**Comment by evilaliv3** [comment]
Thank you @aetdr.

I consider this a valid addition that could be added to the software.

Actually current status of the implementation is tracked here: https://github.com/globaleaks/GlobaLeaks/issues/2579

Do you have developers that could implement this features or customers that would be interested in support us in our roadmap?

**Comment by aetdr** [comment]
Hi @evilaliv3 

At this moment we are still exploring.
If GL gets chosen, there will for sure come support from our side.

**Comment by evilaliv3** [comment]
Implemented in 4.7.0
