### ISSUE TITLE
When granting access, recipients see public names of other recipients instead of real ones

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3127]
**Is your feature request related to a problem? Please describe.**
This is related to closed issue #3064.
Still when granting access, recipients see public names of other recipients instead of real ones.
This may be confusing since often public names are generic and similar or same for all recipients.

Also when saving the report the recipient name shows as "recipient" not the real name in the text file.

**Describe the solution you'd like**
@evilaliv3 could you revise it so that they see real names when granting access to other recipints?

Also it would be preferable when saving a report the recipient comments to show with their real name rather with a generic "recipient".

**Comment by evilaliv3** [comment]
Implemented in 4.7.0
