### ISSUE TITLE
If project name stays empty, "Globaleaks" replaces it and shows as project name

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3129]
**Describe the bug**
Not sure if this is a bug.
There has been a change in behaviour.
Since "project name" can not be multilingual I left it empty and put only "homepage title" which showed nicely.
Since last update (4.6.1 I believe) if project name stays empty, "Globaleaks" replaces it and shows as project name.
Could you please either support a multilingual project name or allow the field to be empty without beeing replaced by something.

**Comment by evilaliv3** [comment]
Hey @elbill, actually this was intended but i considered as well to remove this behaviour.

You can now update to release version 4.7.0 that already included this change.

**Comment by elbill** [comment]
Great thanks
