### ISSUE TITLE
Recipients can not download files uploaded from other recipients. 

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3130]
**Describe the bug**
Recipients can not download files uploaded from other recipients.
when trying they receive the following error:
{"error_message": "InternalServerError [Unexpected]", "error_code": 1, "arguments": ["Unexpected"]}

V4.7.0

**Comment by elbill** [comment]
whistleblowers can download the files attached by recipients

**Comment by elbill** [comment]
Version: 4.7.0

ValueError Inappropriate argument value (of correct type).

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/rtip.py", line 750, in get
    name, filename, pgp_key = yield self.download_wbfile(self.request.tid, wbfile_id)

ValueError: too many values to unpack (expected 3)

**Comment by evilaliv3** [comment]
Thank you, i confirm that this regression has been just introduced in 4.7.0.

**Comment by elbill** [comment]
IS it safe to downgrade to previous version like this:
apt-get install globaleaks=4.6.1

**Comment by evilaliv3** [comment]
No. 

You can use this but you need first to have restored the original /var/globaleaks.db directory.

Anyway i'm issuing a release 4.7.1 that correct this.

**Comment by evilaliv3** [comment]
@elbill: You can now safely upgrade to 4.7.1 that includes just this fix.
