### ISSUE TITLE
Configurazione automatica HTTPS -  Errore interno del server (Unexpected)

### ISSUE THREAD

**Issue by salvolaiacona** [globaleaks/GlobaLeaks#3136]
Buongiorno,
solo per comunicare che la funzione di configurazione automatica HTTPS non è operativa.
Grazie

Salvo

**Comment by evilaliv3** [comment]
Dear @salvolaiacona,

thank you for your notification. Up to our verification all seems to work correctly on this aspect.

Is it possible that you have still not configured any DNS entry from your custom domain name to the IP of the server? 

Please get sure that the hostname points to the IP address of the server and that the firewall allows connections to port 80 and 443.

**Comment by evilaliv3** [comment]
Closing as probably resolved. Please let us know in case you still need assistance.
