### ISSUE TITLE
Multisite and logo link

### ISSUE THREAD

**Issue by mjakubowskilkr** [globaleaks/GlobaLeaks#3137]
I've set multisite option and created 2 sites. First has address https://my-domain/t/2 and second https://my-domain/t/3 . 
But logo in left top corner is still linked to https://my-domain (not created site).
How to fix it?

Second question: can you change multisite addresses to more user friendly? E.g. https://my-domain/my-own-site-name ??

**Comment by evilaliv3** [comment]
Thank you for your feedback.

If you assign a subdomain to your secondary siytes you will be able to access them as subdomain1.maindomain.tld and subdomain2.maindomain.tld.

Alternatively you can acquire and use a dedicated domain for every tenant.
