### ISSUE TITLE
An issue with editing and saving questionnaires

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3140]
Hi

When an user is editing a questionnaire, there is possibility to save progress at different levels: questionnaire, step or field level.

When a field is edited, and user saves at questionnaire level, the change does not get saved. 
If the user saves at field level, then the change is preserved.

This is somewhat confusing as users expect the change to get saved, and the change is visible in the WebUI for lifetime of the session.

An example: Attachment checkbox, in the TOS Question in a multi-step questionnaire 

Is this a known limitation or maybe a bug?

**Comment by evilaliv3** [comment]
Thank you @aetdr, this is actually a known limitation of the current implementation.

**Comment by aetdr** [comment]
Thanks @evilaliv3 

Not a big one. Just wanted to make you aware of it in case that was a bug.
