### ISSUE TITLE
Error when trying to update to 4.7.6

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3142]
**Describe the bug**
Error when trying to update to 4.7.6

**To Reproduce**
apt-get update
Hit:1 http://azure.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:5 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease
Hit:6 http://security.ubuntu.com/ubuntu bionic-security InRelease
Err:4 https://deb.globaleaks.org bionic/ InRelease
  502  Bad Gateway [IP: 95.174.23.119 443]
Reading package lists... Done
W: Failed to fetch http://deb.globaleaks.org/bionic/InRelease  502  Bad Gateway [IP: 95.174.23.119 443]
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by parvusville** [comment]
Getting this as well.

**Comment by evilaliv3** [comment]
Thank you.

All is back up. We are improving some aspects of our infrastructure and some small interruptions may follow.
