### ISSUE TITLE
Audit log should also contain the report # serial number

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3145]
**Is your feature request related to a problem? Please describe.**
The audit log while contains a unique ID (I'm not sure if we can use it somehow) does not contain the report serial number #.  So it it takes effort to match report to audit logged reports.
**Describe the solution you'd like**
It would be very useful the audit log to contain the # serial number. This would make it easier for an auditor to match existing or deleted reports to logged reports in the audit Log. 
**Describe alternatives you've considered**
Now date and time have to be used to make the match.

**Comment by evilaliv3** [comment]
Thank you @elbill for the suggestion, I've added the progressive number of the report to the audit log.

Here is the current interface:
![Screenshot_2022-01-19 GLOBALEAKS - Audit log(1)](https://user-images.githubusercontent.com/217034/150212949-f913f40e-9883-4d92-8333-d676a2ee9bb4.png)

**Comment by elbill** [comment]
@evilaliv3 Fantastic!
Will this show in the CSV export?
Any chance of integrating substatus name in the export instead of the code?
thanks!

**Comment by evilaliv3** [comment]
Yes, i confirm that this will show in the export. You will have an ID (the same as before) and a "progressive" that corresponds to the number of the case.

In relation to the export of the substatuses actually i plan to continue to list the code and make it possible to download as well the descriptors of all the platform. This will make it possible to be able to read the log in all the languages depending on the descriptors loaed and is prerequisite to be able to implement some sort of standard integration with SIEM systems like what specified in https://github.com/globaleaks/GlobaLeaks/issues/2580

**Comment by elbill** [comment]
@evilaliv3 this way it makes sense. Thanks.
