### ISSUE TITLE
Error when a question of type file upload is disable as consequence of change on an radio button trigger

### ISSUE THREAD

**Issue by TrarcoJob** [globaleaks/GlobaLeaks#3146]
Buongiorno,

sulla piattaforma che abbiamo in integrazione su Azure, riceviamo il seguente messaggio d'errore quando cambio la risposta da **Sì** a **No**.

Di seguito invio la mail che ricevo:

Platform:
Host: mysite.com (mysite.onion)
Version: 4.7.6

URL: /

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 Edg/97.0.1072.55

Error Message: TypeError: Cannot read properties of undefined (reading 'files')

Stacktrace:
[
  {
    "columnNumber": 256093,
    "lineNumber": 64,
    "fileName": "https://mysite.com/js/scripts.min.js",
    "functionName": "Object.isUploading",
    "source": "    at Object.isUploading (https://mysite.com/js/scripts.min.js:64:256093)"
  },
  {
    "columnNumber": 114534,
    "lineNumber": 8,
    "fileName": "https://mysite.com/js/scripts.min.js",
    "source": "    at https://mysite.com/js/scripts.min.js:8:114534"
  },
  {
    "columnNumber": 117383,
    "lineNumber": 8,
    "fileName": "https://mysite.com/js/scripts.min.js",
    "source": "    at https://mysite.com/js/scripts.min.js:8:117383"
  },
  {
    "columnNumber": 101305,
    "lineNumber": 8,
    "fileName": "https://mysite.com/js/scripts.min.js",
    "functionName": "d.$digest",
    "source": "    at d.$digest (https://mysite.com/js/scripts.min.js:8:101305)"
  },
  {
    "columnNumber": 103102,
    "lineNumber": 8,
    "fileName": "https://mysite.com/js/scripts.min.js",
    "functionName": "t.$apply",
    "source": "    at t.$apply (https://mysite.com/js/scripts.min.js:8:103102)"
  },
  {
    "columnNumber": 160026,
    "lineNumber": 8,
    "fileName": "https://mysite.com/js/scripts.min.js",
    "functionName": "Object.$$debounceViewValueCommit",
    "source": "    at Object.$$debounceViewValueCommit (https://mysite.com/js/scripts.min.js:8:160026)"
  },
  {
    "columnNumber": 159602,
    "lineNumber": 8,
    "fileName": "https://mysite.com/js/scripts.min.js",
    "functionName": "Object.$setViewValue",
    "source": "    at Object.$setViewValue (https://mysite.com/js/scripts.min.js:8:159602)"
  },
  {
    "columnNumber": 142786,
    "lineNumber": 8,
    "fileName": "https://mysite.com/js/scripts.min.js",
    "functionName": "HTMLInputElement.<anonymous>",
    "source": "    at HTMLInputElement.<anonymous> (https://mysite.com/js/scripts.min.js:8:142786)"
  },
  {
    "columnNumber": 17501,
    "lineNumber": 8,
    "fileName": "https://mysite.com/js/scripts.min.js",
    "functionName": "Rt",
    "source": "    at Rt (https://mysite.com/js/scripts.min.js:8:17501)"
  },
  {
    "columnNumber": 20371,
    "lineNumber": 8,
    "fileName": "https://mysite.com/js/scripts.min.js",
    "functionName": "HTMLInputElement.n",
    "source": "    at HTMLInputElement.n (https://mysite.com/js/scripts.min.js:8:20371)"
  }
]

Grazie per il supporto.

A disposizione

**Comment by evilaliv3** [comment]
Gentile @TrarcoJob,

grazie per la segnalazione. Provvedo a verificare se riesco a riprodurre la situazione sui nostri sistemi.

Potresti gentilmente chiarmi il tipo di domanda su cui vari la risposta da Si a No? Si tratta della nostra domanda predefinita per la raccolta dell'identità o state utilizzando una vostro questionario con domande tutte da voi create?

Se hai modo per tua utilita ti invito a venire sul nostro canale slack dove poter eventualmente interagire anche direttamente con maggior comodità. L'indirizzo è https://slack.globaleaks.org

**Comment by TrarcoJob** [comment]
Egr.io Dott. Pellerano,

la ringrazio per la celerità della risposta e provvederò a seguire il Vostro canale slack.

Il questionario è stato creato totalmente da noi.

La domanda è di tipo **Scelta multipla**, non obbligatoria ed è di primo livello.

A volte (non succede sempre) quando selezione **No** la piattaforma esegue un redirect a mysite.com/login

**Comment by evilaliv3** [comment]
Grazie per il feedback.

Probabilmente il redirect è dovuto all'eccezione che si genera e a una richiesta che scatta verso il vostro server che porta GlobaLeaks a redirigervi al login.

Laddove tu tu potessi, condivimi pure su slack in privato l'indirizzo della vostra piattaforma che provo a navigarla e vedere se ottengo medesimo risultato.

Mi confermi che stai utilizzando windows in abbinamento a Chrome giust? cosi provvederò (ormai domani) a riverificare tutto in medesime tue condizioni

**Comment by evilaliv3** [comment]
After discussing with the user and testing the specific user questionnaire i've identified that the error is generated when question of type file upload is deactivated via a radio button condition that leads to the generation of the following exception:
```js
angular.js:15697 TypeError: Cannot read property 'files' of undefined
    at Object.isUploading (services.js:928)
    at angular.js:17073
    at angular.js:17261
    at Scope.$digest (angular.js:19262)
    at angular.js:19562
    at TaskTracker.completeTask (angular.js:21403)
    at angular.js:6879 undefined
(anonymous) @ angular.js:15697
(anonymous) @ angular.js:11956
(anonymous) @ app.js:69
$digest @ angular.js:19288
(anonymous) @ angular.js:19562
completeTask @ angular.js:21403
(anonymous) @ angular.js:6879
setTimeout (async)
Browser.self.defer @ angular.js:6877
$evalAsync @ angular.js:19560
(anonymous) @ angular.js:17947
scheduleProcessQueue @ angular.js:18123
then @ angular.js:18044
catch @ angular.js:18050
Resource.<computed> @ angular-resource.js:817
Resource.<computed> @ angular-resource.js:898
notifyException @ services.js:1103
(anonymous) @ app.js:79
Promise.then (async)
(anonymous) @ app.js:71
$digest @ angular.js:19288
$apply @ angular.js:19630
$$debounceViewValueCommit @ angular.js:31072
$setViewValue @ angular.js:31046
listener @ angular.js:27318
defaultHandlerWrapper @ angular.js:3891
eventHandler @ angular.js:3879
services.js:925
```

**Comment by evilaliv3** [comment]
Fixed. The correction will be included starting from minor release 4.7.7
