### ISSUE TITLE
Possible to enumerate active users if ip-filtering or 2FA is present

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3149]
Hi

- On a tenant where user password is only form of authentication (no 2FA involved) and ip-filtering rules are not present, it is not possible to enumerate existing valid users. When trying with both, a valid and a non-existent user, if used password is wrong, both attempts result in "Authentication failed" message showing in the UI.

- If ip-filtering is present and requesting IP belongs to a blocked range:
    - valid username with wrong password gets the red "Error" message in in upper left corner
    - invalid username with wrong password gets "Authentication failed" 

- if 2fa is activated:
    - valid username with wrong password continues to the 2FA dialog
    - invalid user with wrong password gets "Authentication failed"

**Comment by evilaliv3** [comment]
Thank you for your valuable feedback @aetdr 

Actually the reason why this enumeration is possible is that we verify the password only after the validation of the 2fa. This has the advantage to not enabling to know if the password is valid or not, before of the IP check and of the 2fa check.

I could easily revert the order of the check but we would achieve your result loosing this property.

Let's try to find out some references where this two conditions are evaluated. Please let me know if you have already some suggstions on this.
