### ISSUE TITLE
An user is able to set weak password by bypassing javascript client validation

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3150]
Hi

An user, when logged in to Globaleaks is able to change their password.
In this process the javascript client is validating password complexity and makes sure weak passwords can not be set.

But, if the user send modified PUT request directly to the API, bypassing the javascript client, weak passwords, for example a single character password can be set. Later on it is possible to use this single character password to log on to the system.

**Comment by evilaliv3** [comment]
Hello @aetdr, thank you for your feedback.

As discussed on #3151 features like this where implemented to enforce operational best practice for internal parties.

I agree that the implementation could be improved to get sure this sets of best-practice are enforced on the backend and that the backend should raise an exception,

In the case of this ticket i recognize the value of adding a check for password validation ensuring the password achieve the minumum accepted level.

**Comment by evilaliv3** [comment]
As an update actually this feature is no longer possible since the password in the current implementation is never sent to the server.
