### ISSUE TITLE
Build the project

### ISSUE THREAD

**Issue by GeorgePeros** [globaleaks/GlobaLeaks#3153]
Hi,

I have made this process https://docs.globaleaks.org/en/main/developer/Environment.html#run and run globaleaks normally

I have then made a change in GlobaLeaks/client/app/views/login/default.html and run it again using 

source ./env/bin/activate
./bin/globaleaks -z -n

But I see no changes. Am I doing something wrong? Please advise.

Thank you and Kind Regards,
George

**Comment by evilaliv3** [comment]
Hello @GeorgePeros 

Following the guide, with the step ```grunt build``` you have built the client in a more compressed an optimize format.

You have the following two possibilies:
- delete the build directory (in this case restart globaleaks that need to know the directory does not exist anymore)
- re-run ```grunt build``` anytime you apply a change to the client

P.s.: Are you looking to develop some additional features? In case it could be helpful please feel free to reach out to us on our slack.

**Comment by pogeorge** [comment]
Hi evilaliv3 

Thanks a lot for the answer. It works.

Sure I will register in slack as well

KR
George
