### ISSUE TITLE
Make it possible for secondary tenants to not be exposed via HTTPS

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3155]
**Describe the bug**
In platform options, disabling flag "Let the platform be reachable without Tor" is not working, platform is reachable using https also.

**To Reproduce**
1. Go to backend "Tor" options
2. Disable flag "Let the platform be reachable without Tor"
3. In a standard browser, try to get https://your_gl_instance
4. Platform is reachable

**Expected behavior**
Platform should not be rachable with standard browser

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser firefox 96, chrome 97

**Smartphone (please complete the following information):**
-

**Additional context**
GL version 4.7.6

**Comment by evilaliv3** [comment]
Thank you @larrykind

Have you tried to restart the application after changing the setting? If i remember correctly this is not a new bug but a limitation of the current implementation.

I will recheck this and see what we could do.

**Comment by larrykind** [comment]
Hi @evilaliv3, 
tried to restart but it won't work. Tenant is reachable with https.

**Comment by evilaliv3** [comment]
@larrykind : You talk about the tenant, maybe you are activating this setting on a secondary tenant?

Actually i think this setting is currently available and working on the root tenant but i may be wrong.

In anycase i will recheck on this and see what we could do.

**Comment by evilaliv3** [comment]
@larrykind: I just retested this and i confirm my current guess.

Actually this setting was studied in relation to single setup that requires strong anonymity where you do not want to expose the system at all via HTTPS considering that it would be not acceptable to expose the system without Tor in an high security profile and makes actually not particular sens on a multitenant system were the root tenant administrators has exposed the root tenant system.

I will make anyhow a patch to not expose the system via the the configured domain as soon that the flag is disabled.

**Comment by evilaliv3** [comment]
I remodeled the ticket with the goal: Make it possible for seconary tenants to not be exposed via Tor

**Comment by evilaliv3** [comment]
Implemented, the feature will be included in release 4.4.8
