### ISSUE TITLE
Report "doubled" in receiver backend in case of additional questionnaire

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3160]
**Describe the bug**

1. In case of an additional qestionnaire is applied to the context, if a report is sent just from the main questionnaire, report is shown as single row in the receiver's backend. When whistleblower fills the additional questionnaire and submit, the receiver sees two reports in the backend, they are linked to the same report.

2. If a receiver open the report before the additional questionnaire is filled, it normally goes in "open" status and in the report board fonts switch from bold to normal. When the additional questionnaire is filled the whistleblower, fonts become bold again: it could make sense as an "updated report", but don't know this is the desired behaviour. 

3. On the additional questionnaire whistleblower interface, there is the same form validation issue described in #3157

**To Reproduce 1**
1a. Set a additional questionnaire to the context
1b. File a report -> receiver sees on row in the report board
1c Access the ticket as a whistleblower and fill the additional questionnaire, submit
1d. Receiver sees two rows with the same ticket content

**To Reproduce 2**
2a. follow 1a and 1b and open the ticket as a receiver -> ticket goes to "open" state -> font goes to normal
2b. As a whistlelbower file the additional questionnaire
2c. As a receiver you will see two rows for the same ticket in the report list, the two rows are marked in bold font

**To Reproduce 2**
look at #3157 form validation problem

**Expected behavior**
- Additional questionnaire should not generate two row referring to the same report.
- After filling additional questionnaire it make sense to have the same behaviour as the new ticket, but don't know if it's the intended behaviour.

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser firefox 96, chrome 97

**Additional context**
GL v 4.7.7

**Comment by evilaliv3** [comment]
Thank you @larrykind:

1. seems a bug in the reports list generation, i'm going to check on this and get sure it's fixed in the next minor release
2. yes it is intentional, any update to the report take the report in bold state except if the update has been done by the recipient. In case the update is performed by a recipient the report become bold only for other recipients but not for the one that made the update.
3. will recheck on this

**Comment by evilaliv3** [comment]
Corrected. The correction will be included starting from minor release 4.7.8
