### ISSUE TITLE
Date format mix

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3167]
Hi!

In the "prolong expity date" box, the shown date is YYYY-MM-DD while the date in the report view is DD-MM-YYYY

![image](https://user-images.githubusercontent.com/70965554/153207193-a58a4839-4cfe-4c1c-b95c-c2d1ad4fad79.png)

**Comment by evilaliv3** [comment]
Thank you @schris-dk for reporting this.

i've just issued a patch that will be included in release 4.7.11.

With this patch all the dates will be in format dd-mm-yyyy
