### ISSUE TITLE
GL01-017 Readable hard-coded credentials might compromise users

### ISSUE THREAD

**Issue by vodkina** [globaleaks/GlobaLeaks#317]
The Globaleaks settings file must be saved with world-readable permissions or, at the very least, the permissions that allow the Globaleaks user to run it. 

However, this file also contains credentials in clear-text, which might be edited by those users who forward emails to themselves:

$ ls -l /usr/share/pyshared/globaleaks/settings.py
-rw-r--r-- root root 19548 Jun 6 16:29 /usr/share/pyshared/globaleaks/settings.py

Inside the settings file the following information might be edited by desperate administrators trying to debug a problem:
# unhandled Python Exception are reported via mail

```
   self.error_reporting_username= "stackexception@globaleaks.org"
   self.error_reporting_password= "stackexception99"
   self.error_reporting_server = "box549.bluehost.com"
   self.error_reporting_port = 465
```

To approach this potentially damaging scenario, these credentials should be saved in an alternative location (perhaps in the database), and should ideally be protected with encryption, regardless of the key being probably located on the same server.

##

**Comment by vecna** [comment]
This is closed right?

**Comment by NSkelsey** [comment]
@vecna nope

**Comment by NSkelsey** [comment]
This is relate to #724 and #1611 as well.

**Comment by vecna** [comment]
Thanks, I was updating this https://github.com/globaleaks/GlobaLeaks/wiki/Cure53-Report

**Comment by evilaliv3** [comment]
Default credentials are not anymore written inside python files or configurable via them;
The default credentials are now instead written in SQL files used for initialization and we are not aware of situations in which exceptions may contain them.

Closing as outdated;
