### ISSUE TITLE
Failure on sorting of reports by report number

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3175]
**Describe the bug**
Sorting of reports by report number is not working properly.

**To Reproduce**
In the Reports page when clicking on # the reports are not sorted properly.

**Expected behavior**
I would expect to sort report by serial number smaller to larger or the other way around
**Screenshots**
![test - Reports - Google Chrome 17_2_2022 3_07_57 μμ](https://user-images.githubusercontent.com/23246886/154488338-911808f0-b07e-4651-878e-17c52deea167.png)

**Comment by evilaliv3** [comment]
Corrected, thank you @elbill !

I'm going to include this fix in release 4.7.11
