### ISSUE TITLE
To comply with license add release date to node config

### ISSUE THREAD

**Issue by fdobrovolny** [globaleaks/GlobaLeaks#3178]
**Is your feature request related to a problem? Please describe.**
License 7(c) states that I need to state "This server is running a modified version of the GlobaLeaks software version
VERSION_NUMBER released on RELEASE_DATE. Download the modified version of the
source code."  on user screens.

**Describe the solution you'd like**
I want to add `__release_date__` into `globaleaks.__init__` which would be updated during a new release. And then save it to the database in `globaleaks.db.migration.perform_data_update`. And add it as default in `globaleaks.models.config_desc.ConfigDescriptor`

And change `app/views/admin/home.html` to include it:
```
<label><span data-translate>Software version:</span> {{resources.node.version}}</label>
<label><span data-translate>Released on:</span> {{resources.node.release_date}}</label>
```

**Describe alternatives you've considered**
Hardcoding release date on every release.

**Additional context**
I'm able to do PR just wanted to check if this way is okay and if I have your blessing before starting it.

**Comment by fdobrovolny** [comment]
@evilaliv3

That makes sense it could be used as an attack vector :thinking: However, I'm a bit confused by your wording the version is currently being exposed at least to the admin page.

---

However, as I understand the license I'm required to state:

>  This server is running a modified version of the GlobaLeaks software version VERSION_NUMBER released on RELEASE_DATE. Download the modified version of the
source code.

in every case and after six months I had to change it to

> This server is running a modified version of the GlobaLeaks software
VERSION_NUMBER released on RELEASE_DATE, which has not been updated for more
than 6 months and might include security vulnerabilities. Download the modified
version of the source code.

Or am I wrong?

My company believes in OSS and I definitely plan to put as many features we develop upstream. However, there are some Czech law requirements that I don't think make sense to be putting them upstream and some are cosmetics. I wanted to reach out to you on your slack and ask for your opinion however it does not seem like your slack is open to the public.

**Comment by evilaliv3** [comment]
Yes your intepretation is correct.

The version is know to administrators but never exposed to end users.

Our advice is to keep the platform up to date, and is for this reason that we enforced that who does not shall at least inform which version is running.

Please feel free to reach me on slack at slack.globaleaks.org

**Comment by fdobrovolny** [comment]
OFFTOPIC:
![Snímek z 2022-02-21 18-22-53](https://user-images.githubusercontent.com/1249759/155002146-9b7005b7-6895-40dc-9e16-a0fedcc575bd.png)

@evilaliv3

**Comment by evilaliv3** [comment]
@fdobrovolny : what if you use these links? https://slack.globaleaks.org / https://globaleaks.slack.com/ ?

**Comment by fdobrovolny** [comment]
> @fdobrovolny : what if you use these links? https://slack.globaleaks.org / https://globaleaks.slack.com/ ?

@evilaliv3 

It does the same on both links.

**Comment by evilaliv3** [comment]
Ah i see, actually something changed in slack and our invite links do not work anymore.

while we resolve this please feel free to drop me an email at: giovanni.pellerano@globaleaks.org and i will send you an invite to join.

thank you
