### ISSUE TITLE
admin password lost, gl-admin resetpass admin bugs

### ISSUE THREAD

**Issue by fwppe** [globaleaks/GlobaLeaks#3179]
**Describe the bug**
Hello,
i have lost the admin password,
i use this command:
# gl-admin resetpass admin
but i recived this error:
Failed! The user 'admin' does not exist or encryption key is set
the admin user exists!

my version OS: Ubuntu 20.04.2 LTS (GNU/Linux 5.8.0-63-generic x86_64)
My version globaleaks 4.2.12

please help me,
thanks

**Comment by fwppe** [comment]
Hello,
thanks for your replay.
i have the account recovery key.
please help me.

how should i use recovery key to reset admin password?
thanks

**Comment by evilaliv3** [comment]
Yes you can do this from the web interface asking a password reset and you will receive an email with a link.

You will need to access that link and insert your account recovery key.

**Comment by fwppe** [comment]
Hello,
I solved the problem by asking the password reset from the gui.

**Comment by sergioamsilva** [comment]
Same problem here after enable custodian, no recover key enabled for admin.
How can i solve it ?

**Comment by erwindegrave** [comment]
@evilaliv3 I do have lost the password as well as the recovery key as admin.

You have mentioned above that there is an advanced procedure to recover admin account. Could you please tell me the steps? I don't mind losing all the info as it is a project under development.

Thanks

**Comment by erwindegrave** [comment]
@evilaliv3 Where do I find the database file? Is that the globaleaks.db file in /var/globaleaks?

**Comment by evilaliv3** [comment]
yes

**Comment by erwindegrave** [comment]
Thanks @evilaliv3 

Something strange is happening. When I do scp user@at_server:/var/globaleaks/globaleaks.db /path/to/local,
I get the following message: scp: /var/globaleaks/globaleaks.db: No such file or directory

Do I do something wrong?

**Comment by evilaliv3** [comment]
The command is correct

**Comment by erwindegrave** [comment]
@evilaliv3 Thank you for your help!
Retrieved the admin access again.

**Comment by paolo987** [comment]
Hi, I have the same problem.
I go through the password recovery procedure, he sends me an email with a link, I enter the key (I'm sure it's right) and then he goes back to the login page where underneath he writes "The code is invalid or expired.".

I just finished configuring everything yesterday... have I lost all my work?

Please help me.

**Comment by paolo987** [comment]
my concern is: why did this happen?
I haven't done anything since yesterday and I'm sure the password and key are correct.
Furthermore, even for the "non-admin" user I get the same error if I try to log in.
