### ISSUE TITLE
Recipient can remove themselves from report even if they are the only one assigned.

### ISSUE THREAD

**Issue by fdobrovolny** [globaleaks/GlobaLeaks#3182]
**Describe the bug**
When a recipient has "Give this recipient ability to grant user access to reports" permission and there is a report that is only assigned to them they can remove themselves from the report with no ability to get back to it.

**To Reproduce**
Steps to reproduce the behaviour:
Given a recipient with the permission "Give this recipient ability to grant user access to reports"
1. Create a new report to context with only one recipient assigned.
2. Go to the report and press the revoke access button.
3. Select the recipient themselves.
4. The report is still viewable from the reporter but not visible to any recipient.

**Expected behaviour**
The user themselves won't be on the list to choose from or there will be an error message when trying to do so.

**Comment by evilaliv3** [comment]
Thank you for reporting this @fdobrovolny, i will check into this and get sure the platform will at least prevent this with an error.

**Comment by evilaliv3** [comment]
Thank you @fdobrovolny 

I confirm the remediation that will prevent the action to be performed.

The fix will be included in the next stable release (4.7.12)
