### ISSUE TITLE
Issue when adding new user as "recipient"

### ISSUE THREAD

**Issue by wh1t3h4tstyl3** [globaleaks/GlobaLeaks#3183]
Hello,

after adding the first "recipient" user which is working fine, all other users, created as recipients, cannot view the submitted reports.

The software ( version 4.7.11) is installed on Ubuntu 20.04.3 LTS.

Thanks for your support.

Best Regards,

Francesco

**Comment by evilaliv3** [comment]
Thank you @wh1t3h4tstyl3 

I understand from your reporting that possibly you could have not assigned your recipients to the submission context.

Open the Context section, locate and open the default submission context and add attach your new users to it.

This would solve your issue.

In this case I would kindly ask you to confirm the resolution.

**Comment by wh1t3h4tstyl3** [comment]
> Thank you @wh1t3h4tstyl3
> 
> I understand from your reporting that possibly you could have not assigned your recipients to the submission context.
> 
> Open the Context section, locate and open the default submission context and add attach your new users to it.
> 
> This would solve your issue.
> 
> In this case I would kindly ask you to confirm the resolution.

It was exactly what you suggested! I'm new to globaleaks and I didn't know it. Thank you very much!

**Comment by evilaliv3** [comment]
Thank you for confirming @wh1t3h4tstyl3
