### ISSUE TITLE
4.7.15 states version as 4.7.14

### ISSUE THREAD

**Issue by emka-nh** [globaleaks/GlobaLeaks#3188]
**Describe the bug**
After installing 4.7.15 software version is still on 4.7.14

**To Reproduce**
Install update, login as admin, see tab "Changelog". Software version is 4.7.14, but log shows Changes in version 4.7.15.

**Expected behavior**
Software version should be 4.7.15

**Screenshots**
![image](https://user-images.githubusercontent.com/98522373/156356398-21cd69ee-2343-405d-bfbf-e8ff1513a255.png)

**Comment by evilaliv3** [comment]
Thank you @emka-nh 

This is a know issue that actually do not causes any impact, is just a wrong statement.

We are about to issue a 4.7.16 that will fix this along other minor aspects.
