### ISSUE TITLE
Default context receiver doesn't receive reports if further receivers are set in a select question

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3189]
**Describe the bug**
If in a cotext is specified a default receiver user, and in the applied questionnaire there are further receivers selected by a select field,
the default receivere doens'n receive the ticket.
If the select option has no receivers, defaul receiver will receive th report

**To Reproduce**
1. set a default context receiver and
2.  in the questionnaire set a select question with two options, in one of them set a receiver
3. Send a report selecting first option (with reciver) -> report is sent to the selected receivere only, not to the context default one
4. Send a report selecting second option (without reciver) -> report is sent to the default receiver (correct behaviour)

**Expected behavior**
In case n.3 report should be sent to dafault receiver also: the point is that default receiver should receive everytime a report is done.

**Desktop (please complete the following information):**
 - OS: ubuntu 18
 - Browser firefox 97
 - GL Version 4.7.17

**Comment by evilaliv3** [comment]
Thank you @larrykind 

Actually what you are reporting as a possible bug is exactly the intended behaviour.

The feaure that you are testing on dropdown is designed to handle situations of conflict of interest where you want that if that option is selected the submission goes to the set of recipients configured instead of the default ones.

I will close the ticket but feel free to add any question if there is something that you would like to be clarified.

**Comment by larrykind** [comment]
Thank you for the clarification @evilaliv3. 
My thought about that keeping in mind a best effort management of this conflict, personally I continue to prefer the logic that default receiver will receive everytime, because the replace logic doesn't catch the use case to add another (set of) receiver for a specific select option.

Hence I could suggest to add a flag option when a receiver is added in a select field to choose if default receiver will be replaced or not, this could be nice.
In this case, the only conflict that should be managed will be to not send duplicate emails if default receiver is doubled somewhere.
Thanks.

**Comment by evilaliv3** [comment]
Thank you for this feedback @larrykind 

We will consider the possibility to edit the functionality to make it possible to configure the behaviour (add/replace).

In the meantim i think you could use the featue by configure there the full set of recipients (default + the additional conflict of interest persons)

p.s. typically on a conflict of interest situation we have been requested specifically to exclude the default recipient and this is why the feature does currently work with a replacement mode.
