### ISSUE TITLE
Configurable Default Configuration for Sites

### ISSUE THREAD

**Issue by fdoe** [globaleaks/GlobaLeaks#3190]
**Is your feature request related to a problem? Please describe.**
When creating a new site based on the multisite feature, the default configuration settings defined in [1] are applied to this new site. Any changes to these settings must be applied after the site was created, either manually via UI or via REST. Currently, there is no way to configure the default configuration settings, as they are hard coded [1].

**Describe the solution you'd like**
As an administrator, I would like to be able to configure the default configuration settings in order for them to be applied automatically upon site creation. 
This could be achieved in multiple ways, not limited to but including:
1) Storing all default configuration settings in an editable configuration file / database table. 
2) Overriding individual configuration settings from an editable configuration file or database table.

**Describe alternatives you've considered**
It was considered to create a JS file, upload it to a newly created site and have it execute REST calls to update settings. A clear limitation of this approach would be that e.g. the SMTP password or SSL certificates would have to be stored in plain text in such a JS file.

**Additional context**
[1] https://github.com/globaleaks/GlobaLeaks/blob/main/backend/globaleaks/models/config_desc.py

**Comment by evilaliv3** [comment]
Thank you this suggestion @fdoe;

Actually within GlobaLeaks we have alredy identified this need and we have implemented some initial support for such a "profile" feature but unfortunately it is still not ready for production use: https://github.com/globaleaks/GlobaLeaks/issues/2039

**Comment by evilaliv3** [comment]
Thank you for your question @fdoe.

No at the moment not unfortunately as our active development is focused on other duties but we will consider your input for future roadmapping.

By any chance in your team there is active development on globaleaks and you would like to support the development of this aspect?
