### ISSUE TITLE
Leave the whistleblower key-code access active when new submission are disabled

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3191]
**Is your feature request related to a problem? Please describe.**
If a tenant has disabled submissions because of various motivations, there should be the possiblity for whistleblower to continue to manage his submitted reports and interact with receivers until the end of its management / expiration

**Describe the solution you'd like**
Possibility to access to reports with key-code access when new submissions are disabled.

**Comment by evilaliv3** [comment]
Thank you for reporting this. I agree on this aspect and i think we could implement this within the next minor update.

**Comment by evilaliv3** [comment]
@larrykind : would you please clarify about this issue?

Actually after verifying this ticket i've found that it is actually possible to access the platform when the submissions are disabled.

I guess you may be using a very outdated version of the system. Which version are you using

Here is the the interface on the up to date globaleaks when submissions are disabled:

![Screenshot 2022-03-10 at 17-49-06 GLOBALEAKS -](https://user-images.githubusercontent.com/217034/157713246-43b7bdaf-8b74-468c-9833-c44ebaa5f995.png)

**Comment by larrykind** [comment]
@evilaliv3 thank you, just tested successfully. ticket closed
