### ISSUE TITLE
Problems on theme files migration from version 4.0.54 to 4.7.17

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3192]
**Describe the bug**
1. After upgrade from 4.0.54 to 4.7.17 theme attachments are not found. FIles are not downloadable, workaround is to delete and re-upload the file. Not suitable solution if you have many tenants with lots of customizations.

2. Fields of old default whistleblower_identity and new default are shown together

**To Reproduce** 
1. upgrading GL from 4.0.54 to 4.7.17 using tenants with theme attachments (my case is simply to customize "HeaderBox" element)
2. attachment image is not shown on web page (console gives error), 
3. going to step identity -> whistleblowing identity templates fields are shown together
4. accessing backend attachment is shown but not downloadable
5. Workaround is to delete the attachment and re-upload -> unfeasible solution for hundreds of tenants

**Expected behavior**
Theme attachments should preserve their link after GL upgrade

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser firefox 98
 - GL Version 4.7.17

**Comment by evilaliv3** [comment]
Thank you for reporting this @larrykind, i will test the situation and get to understand the reason of the failure trying to see if we could issue a patch

**Comment by larrykind** [comment]
@evilaliv3 I changed the ticket label to add another issue found under the same upgrade. 
![wb_id](https://user-images.githubusercontent.com/61267901/157711253-98c426ee-c313-44bb-a98e-657efa197f63.JPG)

**Comment by evilaliv3** [comment]
@larrykind: please keep different issues reporting divided by topic not by release.

I is typically more easy to handle them one by one. 

Thank you.

**Comment by evilaliv3** [comment]
@larrykind: I've just created a setup based on 4.0.54, instantiated a root and a main tenant and loaded on both a css file, a javascript file, and a font.

After updating to the latest system found very file still present.

I would need, if you can, your assistance to try to identify more precisely a path for the reproducibility of this bug.

**Comment by larrykind** [comment]
ok @evilaliv3 I send you images about my browser tools on slack

**Comment by larrykind** [comment]
@evilaliv3 problem solved! thank you for your support
