### ISSUE TITLE
Fields of old default whistleblower_identity and new default are shown together after version upgrade

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3193]
**Describe the bug**
After upgradin GL from 4.0.54 to 4.7.17 Fields of old default whistleblower_identity and new default are shown together in identity section of a previously installaed tenant.

1.   upgrading GL from 4.0.54 to 4.7.17 
2.  going to step identity -> whistleblowing identity templates fields are shown together

**Expected behavior**
The old default whistleblower_identity should be shown only, or just the new one

**Desktop (please complete the following information):**
 - OS: ubuntu 20
 - Browser ffx 97
 - GL Version 4.7.17

**Screenshots**

![wb_id](https://user-images.githubusercontent.com/61267901/157713314-72dc503e-dcaa-424f-8a0b-ad8a569f6162.JPG)

**Comment by evilaliv3** [comment]
Bug reproduced and fixed. The patch will be included in release 4.7.18
