### ISSUE TITLE
Improve audit log adding information about software updates

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3194]
Hi!

Would it be possible to add version update to the Globaleaks.log file?

Currently I cannot find a way to document the updates has taken place . This info is needed for audit purposes.

Currently the only way is to manually take notes of this along with an overview of the potential backups before upgrades on the server :-)

The logging of the updates help on documenting these (to verify the updates on audits of the overall security of the system) :-)

**Comment by evilaliv3** [comment]
Thank you for your feedback that is actually very valuable @schris-dk

I think we could definitely improve the audit log adding log entries for the update process.

**Comment by evilaliv3** [comment]
@schris-dk Thank you for your suggestion.

The new release include logging of the time of updates and of the version change.
We have still to implement visualization of this information but at least the logging is there!
