### ISSUE TITLE
After updating to 4.8.0 questionnaire is reset to default "GLOBALEAKS"

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3196]
**Describe the bug**
After an update from 4.7.17 to 4.8.0 the questionnaire set for all tenants is the default "GLOBALEAKS" , non the one set before th update.

**Expected behavior**
After update the questionnaire should be the one set before.

**Desktop (please complete the following information):**
 - OS: ubuntu
 - Browser firefox 98
 - GL version 4.8.0

**Comment by evilaliv3** [comment]
Hi @larrykind,

Actually this is not a regression or a bug but is intended.

We have update the globaleaks default questionnaire that is now renamed from DEFAULT to GLOBALEAKS.

The new questionnaire is designed to be able to support users that prefer a default configuration with our reccomentations.

**Comment by larrykind** [comment]
Thank you @evilaliv3 for the clarification.
maybe I wasn't clear in the ticket rollout: in my opinion the GLOBALEAKS questionnaire should have been overwritten in the only case the previous questionnaire was DEFAULT, not a customized one. The issue was about customized questionnaires.

**Comment by evilaliv3** [comment]
Thank you for the clarification @larrykind

This is actually pretty strange and doesnt seems to happen on our own setups or testbeds.

Do you confirm that this is happen on all your setups or only on one in particular?

**Comment by larrykind** [comment]
@evilaliv3 my setup was about a 4.0.54 upgarded to various versions. From 4.7.17 I found this problem in tenants with multiple contexts

**Comment by evilaliv3** [comment]
Did it affect only tenants with multiple contexts? 

Did it affect all your globaleaks setups or only some ?

**Comment by larrykind** [comment]
It affects tenants with multiple context only, in may case it seems it affects tenants with customized identity templates, but need to verify. I try to better define the occurrences and let you know

**Comment by SStefano92** [comment]
Sorry, I completely forgot about that step. Now everything works. 

Thanks so much

**Comment by larrykind** [comment]
@evilaliv3 i tried to reupgrade from 4.0.54 straight to 4.8.0 and I didn't found the issue, For questionnaires I created in versions 4.7.10/15 for test purposes I found the questionnaire reset issue when updating from 4.7.17 to 4.8.0. For now I can't say more.

**Comment by evilaliv3** [comment]
Thank you @larrykind , i will try to setup a 4.7.10, add 2 tenants, add 2 context and 2 custom questionnaire each and retest the update trying to replicate your situation.

If you are able to please share a database file where i could replicate the issue.

**Comment by SStefano92** [comment]
I installed the platform on a virtual machine to test with version 4.7.17 and then, with the various confirmations, I bought a VPS with 4core, 8Gb Ram and 80gb storage. Ubuntu 20.04. and I installed your GlobaLeaks, version 4.8.0, configured it and exported the questionnaire from the local VM and imported it to the VPS.

**Comment by evilaliv3** [comment]
I see, if i understand it correctly, you actually did not migrate from 4.7.17 to 4.8.0 but you have exported and reimported the questionnaire.

Do you confirm @SStefano92 ?

 In this case i think your issue was just not understanding where to assign the questionnaire but i think is not related to what @larrykind  experienced.

**Comment by SStefano92** [comment]
Exactly

**Comment by larrykind** [comment]
@evilaliv3 I did other tries but right now I am not able to replicate this problem, so for me ticket can be closed for now. If I will succeed to replicate this problem I'll write down here. Thanks

**Comment by evilaliv3** [comment]
Thank you @larrykind for this update!
