### ISSUE TITLE
Change the type of the ID attribute of Audit Log to be an autoincremented integer

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3198]
We are trying to integrate Globaleaks to our SIEM. 
In order to do that, SIEM agent requires an autoincremented ID column (to be able to fetch changes and raise alerts if there are missing rows).

Globaleaks uses UUIDs as PRIMARY KEY, which makes it difficult to track the log.
Is it possible to create such column in the table?

**Comment by evilaliv3** [comment]
Implemented; the improvement will be included starting from release 4.9.0
