### ISSUE TITLE
GL01-010 Admin role does not have a username

### ISSUE THREAD

**Issue by vodkina** [globaleaks/GlobaLeaks#320]
The admin user level does not have a valid username. 
To authenticate with admin privileges you only need to supply a valid password and admin role type. With no valid username, this increases the likelihood of a brute force attack.
 In a nutshell, an attacker only has to try password combinations rather than username/password combinations.
 If account lockout procedures were in place for the admin account, it would be possible to DoS this account by repeatedly triggering protection. 
Additionally, because the admin account is not changeable and is publicly known, there would be no countermeasure other than IP filtering and increasing the failed login attempts count.
We recommend that the role of “admin” is customizable on installation and randomized. Alternatively, admin accounts should have usernames which are customizable and contain a blacklist of known admin accounts.

**Comment by evilaliv3** [comment]
This feature has been finally implemented as part of September milestone and is now included in devel branch.

Now it is possible to:
- create multiple admins with the role 'admin'
- change the username of the first admin user.
