### ISSUE TITLE
Disabled "Let whistleblowers add attachments onto existing reports" doesnt'allow to send files from the questionnaire

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3214]
**Describe the bug**
When the context setting "Let whistleblowers add attachments onto existing reports" is off and a report is sent using a questionnaire that requires files, the system seems to send files, but really hiddenly disallows the whistleblower to send files through the questionnaire. So Files seem to be sent when report is submitted, but they aren't.

**To Reproduce**
1. Set off the context flag "Let whistleblowers add attachments onto existing reports"
2. Send a report using a questionnaire with a file
3. file is not received from the receiver and it's not shown in the whistleblower account

**Expected behavior**
This setting should disallow the whistleblower to upload files for existing reports, not for new ones. So files sent through the questionnaire should be sent.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04 bionic
 - Browser - ff 97
 - GL Version 4.8.0

**Additional context**

**Comment by evilaliv3** [comment]
Thank you @larrykind 

Actually this all works as intended and if you disable the file upload API as you made the file API is effectively disabled.

As already clarified in the other ticket https://github.com/globaleaks/GlobaLeaks/issues/3213 these features should only be used when you do not want to enable the the comment APIs and have been designed for very risky scenarios (e.g. war crimes reporting) where whistleblowers are persons at risk and recipients want to get sure to not collect their identity that could be leaked by mistake by the user within a comment or a message.
In such scenarios recipients are offering whistleblowers only dropdown questions and avoid to offer any free text area or any file upload and occasionally are enabling some users to upload information after validating the answers to the dropdowns.

In a platform dealing with anticorruption and corporate compliance reporting files and comments should be always available to users to foster the collaboration with whistleblower.

We consider that there is only one situation when recipients of an anticorruption/corporate compliance platform do not need anymore feedback from users and is whenthe report is fake or the platform is abused. In this case the recipient can just close the report that would disable any action.
