### ISSUE TITLE
Regression on Tenant Auth Switch introduced in 4.9.1

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3218]
**Describe the bug**
After updating to latest version from 4.7 today I receive an error when accessing configuration of multi tenat sites through the admin site.

**Comment by evilaliv3** [comment]
Thank you @elbill , i confirm that this seems to be a regression introduced in 4.9.1.

I'm going to work on a patch and include it in a new release 4.9.3

**Comment by evilaliv3** [comment]
Closing as fixed.
