### ISSUE TITLE
"Logout" link is shown when wrong route is called 

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3221]
**Describe the bug**
When you are filling the questionnaire as a whistleblower, after you click "proceed", if you put a casual string after the domain name in the browser, the "Logout" link is shown, with no apparent effects.

**To Reproduce**
1. Open your WB link (i.e. https://<your_wb_site>) and go ahead to fill the questionnaire
2. On the browser after domain name, call a casual string https://<your_wb_site>/#/a
3. "Logout" link is shown.

**Expected behavior**
logout link should not be shown in case of wrong route

**Desktop (please complete the following information):**
 - OS: ubuntu 18 bionic
 - Browser : FF 100, chrome 100
 - GB Version 4.9.5

**Comment by evilaliv3** [comment]
Fixed.

The fix will be included starting from release 4.10.8

**Comment by evilaliv3** [comment]
Actually we have currently reverted the correction because it was impacting some other more important functionalities.

We will study a different correction with the next development.

**Comment by evilaliv3** [comment]
Fixed in upcoming release 4.10.11
