### ISSUE TITLE
FIDO based authentication

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3223]
Hi @evilaliv3 

As the industry is moving away from the less secure password-based authentication towards FIDO https://fidoalliance.org/ I was wondering if it is something Globaleaks were considering.

I can see it was mentioned a couple of times in 2015

**Comment by evilaliv3** [comment]
Thank you @aetdr.

Yes it is surely considered as an alternative to the current two factor authentication based on TOTP.

I think there should be some valid components to be used for implementing it both for client and the backend components.

Is there anyone in your team that would be interested in developing it? Please possibly refer to existing tickets: https://github.com/globaleaks/GlobaLeaks/issues/1352
