### ISSUE TITLE
Errori in console all'apertura

### ISSUE THREAD

**Issue by MarcoAppleby** [globaleaks/GlobaLeaks#3226]
Buongiorno,

abbiamo installato una piattaforma Whistleblowing con Globaleaks e abbiamo notato che quando entro sulla piattaforma per compilare il questionario vengono generati due errori in console:

Il 1°:
```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'sha256-fwyo2zCGlh85NfN4rQUlpLM7MB5cry/1AEDA/G9mQJ8='". Either the 'unsafe-inline' keyword, a hash ('sha256-uD+9kGdg1SXQagzGsu2+gAKYXqLRT/E07bh4OhgXN8Y='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

ut @ scripts.min.js:8
ft @ scripts.min.js:8
ft @ scripts.min.js:8
xn @ scripts.min.js:8
(anonimo) @ scripts.min.js:8
(anonimo) @ scripts.min.js:8
(anonimo) @ scripts.min.js:8
$digest @ scripts.min.js:8
$apply @ scripts.min.js:8
(anonimo) @ scripts.min.js:8
Ut @ scripts.min.js:8
n @ scripts.min.js:8

```
Il 2°
```
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'sha256-fwyo2zCGlh85NfN4rQUlpLM7MB5cry/1AEDA/G9mQJ8='". Either the 'unsafe-inline' keyword, a hash ('sha256-4IfJmohiqxpxzt6KnJiLmxBD72c3jkRoQ+8K5HT5K8o='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

ut @ scripts.min.js:8
ft @ scripts.min.js:8
ft @ scripts.min.js:8
xn @ scripts.min.js:8
(anonimo) @ scripts.min.js:8
(anonimo) @ scripts.min.js:8
(anonimo) @ scripts.min.js:8
$digest @ scripts.min.js:8
$apply @ scripts.min.js:8
(anonimo) @ scripts.min.js:8
Ut @ scripts.min.js:8
n @ scripts.min.js:8
```

Inoltre, ho notato che quando modifico la risposta di alcune domande a scelta multipla, i due errori si ripresentano in copia.

Non sono state effettuate modifiche al codice o aggiunti file Javascript.

Sono sati inseriti solo file di font, css e loghi/favicon.

Altresì (non so se è collegato) quando accedo a delle sezioni che non contengono campi obbligatori, il pulsante **Successivo** non funziona e non è possibile passare alla sezione successiva. Il pulsante **Precedente** funziona correttamente.

Vi ringrazio per il supporto.

La versione installata è la 4.9.5.

**Comment by evilaliv3** [comment]
Dear Marco, thank you for your question. You can safely ignore this console log that is part of the default setup. GlobaLeaks uses some Content Security Policies that prevents inline styles to be applied and one of the components that we use get the use blocked.

Gentile Marco, grazie per la tua domanda. Puoi ignorare questo log in console che è parte del normale comportamento dell'applicativo. GlobaLeaks implementa delle Content Security Policies che impediscono di usare stili inline che sono usati anche in alcuni dei suoi stessi componenti.

**Comment by MarcoAppleby** [comment]
Gentile Giovanni, 
grazie per la risposta.

Per quanto riguarda la navigazione con il pulsante **Successivo** che non funziona in determinate sezioni. Da cosa potrebbe essere dovuto?

Ho notato che il pulsante non funziona se non seguo il flusso della compilazione.

Ad esempio, se volessi partire a compilare dalla sezione 4 e poi cliccare sul pulsante **Successivo** per passare alla sezione 5, quando clicco sul pulsante la pagina torna solo in cima ma non procede avanti.

Inoltre, sarebbe possibile vincolare la compilazione di modo che non si salti da una sezione all'altra verificando che tutti i dati obbligatori della sezione precedente siano stati compilati?

Potrei ovviare a questa problematica inserendo un campo obbligatorio di "Conferma" alla fine di ogni sezione e verificare che sia stata spuntato, ma se ci fosse una possibilità dinamica/automatica sarebbe ottimo.

Grazie ancora per il supporto.

P.S. E' meglio aprire un'altra issue per quanto detto sopra?

**Comment by evilaliv3** [comment]
La ringrazio, in generale sì meglio aprire un ticket specifico per ogni specifica domanda. Per quanto già richiesto non si preoccupi le rispondo qui. 

1. La piattaforma se si segue navigazione ordinata degli step premendo il bottone successivo implementà già validazione delle domande e impedisce di proseguire se non si sono compilate le domande dello step corrente.
2. In relazione al punto 1 è possibile da quanto mi dice che ci sia un problema nella procedura se l'utente salta uno step andando subito ad uno step successivo. L'applicazione dovrebbe in caso di buon funzionamento andare al primo step che manchi di compilazione e mostrare gli errori relativi a tale step. Provvediamo a verificare.

**Comment by MarcoAppleby** [comment]
La ringrazio.

Ho aperto la nuova issue relativa.
