### ISSUE TITLE
Form validation is inconsistent when the user bypass a step and then clicks proceed button

### ISSUE THREAD

**Issue by MarcoAppleby** [globaleaks/GlobaLeaks#3227]
Buongiorno, 

Ho riscontrato un problema durante la navigazione con il pulsante **Successivo** in quanto non funziona in determinate sezioni. Da cosa potrebbe essere dovuto?

Ho notato che il pulsante non funziona se non seguo il flusso della compilazione.

Ad esempio, se volessi partire a compilare dalla sezione 4 e poi cliccare sul pulsante **Successivo** per passare alla sezione 5, quando clicco sul pulsante la pagina torna solo in cima ma non procede avanti.

Il pulsante **Precedente** funziona correttamente in qualunque caso.

Grazie ancora per il supporto.

_Originally posted by @MarcoAppleby in https://github.com/globaleaks/GlobaLeaks/issues/3226#issuecomment-1134489785_

**Comment by evilaliv3** [comment]
Gentile Marco

La piattaforma se si segue navigazione ordinata degli step premendo il bottone successivo implementà già validazione delle domande e impedisce di proseguire se non si sono compilate le domande dello step corrente.
Da quanto mi dice è possibile ci sia un problema nella procedura se l'utente salta uno step andando subito ad uno step successivo. L'applicazione dovrebbe in caso di buon funzionamento andare al primo step che manchi di compilazione e mostrare gli errori relativi a tale step. Provvediamo a verificare.

**Comment by evilaliv3** [comment]
Fixed and released in 4.9.6
