### ISSUE TITLE
Vincolare la navigazione tramite sezioni al completamento di tutti i campi obbligatori della sezione precedente

### ISSUE THREAD

**Issue by MarcoAppleby** [globaleaks/GlobaLeaks#3228]
Buongiorno,

con la presente a chiedere se potesse essere implementata la funzionalità per cui il questionario deve essere obbligatoriamente compilato in modo sequenziale.

Ho visto che il pulsante **Successivo** effettua un controllo su tutti i campi obbligatori presente nella sezione attiva, ma se il Whistleblower dovesse cliccare sul numero della sezione può eludere tale controllo.

Al momento, poiché ne avevamo la necessità, abbiamo inserito un semplice css **pointer-events: none** sulla barra di navigazione, ma, ovviamente, potrebbe essere aggirato facilmente non essendoci un controllo lato server.

Potrebbe essere una funzionalità utile da implementare?

Grazie per il supporto.

**************************************************************************************************************

Hi,

with this **Feature request** to ask if it is possibile to improve the solution with the sequential navigation and prevent the jumps between sections that a user can do by clicking on the section's number of the navigation menu.

The **Next** button does a check on all required field and if someone is not compiled, the whistleblower can't proceed to the next section.

This could be an useful improvement?

Thanks for the support.

**Comment by evilaliv3** [comment]
Hello @MarcoAppleby, thank you for this suggestion.

Actually from the user perspective it is evaluated that for many reasons users need to have the possibility to navigate the questionnaire to get mor understanding of what they would need to fill or possibly revise the answers.

Actually the issue in which you incurred (https://github.com/globaleaks/GlobaLeaks/issues/3227) will be solved with the release 4.9.6 that we are publishing today.

In any case even if the user will bypass some steps, the form validation will always be applied preventing the user to complete the form if the validation fails.

This said, do you consider your proposal still interesting and if yes for which aspects?

**Comment by MarcoAppleby** [comment]
Hi @evilaliv3, thanks for reply.

No, your arguments convinced me and i totally agree with you.

If the problem #3227 is been resolved, I think that this **feature request** can be closed.

Thanks again.
