### ISSUE TITLE
Multisite personalization

### ISSUE THREAD

**Issue by guigsilva** [globaleaks/GlobaLeaks#3230]
Hello Guys,

First of all, Great work on the software congratulations to the team.

We are trying this to make a whistleblower platform for our community.

We create a multsite, change some things on site settings> Main configuration and save. But the changes are not reflected on the frontend.

Maybe something with translations? We are using the portuguese PT-PT language

Thanks in advance
Guilherme

**Comment by evilaliv3** [comment]
Thank you for your question and feedback!

Actually if you are running Globaleaks in multiple languages you should
configure the text in multiple languages.

To do this , operating as administrator, switch to the language selector to
the language that you want to configure and configure your text.

Basically when you operate using Portuguese, the text will be saved for
Portuguese, and when you operate in English the text will be saved for
English


Please feel free to give it a try and let us know if you need any other
clarification.

**Comment by guigsilva** [comment]
Perfect!
