### ISSUE TITLE
signatures were invalid during update

### ISSUE THREAD

**Issue by fintechestenberg** [globaleaks/GlobaLeaks#3231]
**Describe the bug**
When updating globaleaks the following error occurs

**To Reproduce**
apt update

**Expected behavior**
For updates to be pulled

**Screenshots**
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://deb.globaleaks.org focal/ Release: The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Failed to fetch http://deb.globaleaks.org/focal/Release.gpg  The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by evilaliv3** [comment]
Thank you @fintechestenberg , the new focal release was still to be signed.

All should be correct not.
