### ISSUE TITLE
Jammy release not found by installing Globaleaks

### ISSUE THREAD

**Issue by vkouam** [globaleaks/GlobaLeaks#3232]
**Bug Description**
Hi, i try to install Globaleaks on Ubuntu 22.04. I tipped the given commands on the installation page of the official Website. I received the following error message from my terminal:
**The repository "http://deb.Globaleaks.org jammy/ Realase" does not contain a release file**

**To Reproduce**
1. Go to '. https://docs.globaleaks.org/en/main/setup/InstallationGuide.html'
2. Copy the commands there
3. execute them in the command line of your newly installed Ubuntu 22.04

**Expected behavior**
I should receive a confirmation of successful installation of Globaleaks

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 22.04

**Comment by stgitdeploy** [comment]
I have faced the same issue, I have tried to install on ubuntu 22.04 and 20.04 and received this message

Err:6 https://deb.globaleaks.org jammy/ Release
  404  Not Found [IP: 95.174.23.119 443]
Reading package lists...
E: The repository 'http://deb.globaleaks.org jammy/ Release' does not have a Release file.

**Comment by evilaliv3** [comment]
Thank you, this should be fixed now.
