### ISSUE TITLE
"Request support" feature's functionality

### ISSUE THREAD

**Issue by evariitta** [globaleaks/GlobaLeaks#3236]
We've got a problem with the "request support" feature.

I added a new admin user to one site of our multitenant platform in order to them to receive support requests sent on that site. They have activated the account and have e-mails enabled. 

Result is, requests come to other, older admins of that site but not to the new admin. 

I have tested this on a couple of sites.

Shouldn't the support requests come to all admins of a site?

**Comment by evilaliv3** [comment]
@evariitta: Would you please share the version of the software that you are using?

Please always include at least this detail that is fundamental for us to perform debu.

Thank you!

**Comment by evariitta** [comment]
Thank you for reminding! We are using version 4.9.5.

**Comment by evilaliv3** [comment]
@evariitta: may i ask you to test the following?

- try to issue a new request of support and check if the mail arrive to the new user or not eventually checking the spam box
- if the mail do not arrive restart the application with "/etc/init.d/globaleaks restart"
-  try to issue a new request of support; if the mail will arrive it may be related to the fact that caches were not correctly invalidated when the user was added.

**Comment by evariitta** [comment]
I will do this and let you know if it helped. Thank you.

**Comment by evilaliv3** [comment]
@evariitta: Do you have any update on this?

**Comment by evariitta** [comment]
Yes, restarting the application solved the issue! Thank you!
