### ISSUE TITLE
Copy-to-clipboard of receipt no. not working

### ISSUE THREAD

**Issue by gianlucagilardi** [globaleaks/GlobaLeaks#3238]
**Describe the bug**
After submission is completed copy to clipboard function as far as receipt no does not seem to work and receipt number selection is not possible

**Expected behavior**
Possibility to copy receipt number 

**Desktop (please complete the following information):**
 - OS: win10 21h2 fully updated
 - Browser Edge
 - Version 102.0.1245.41 (Official build) (64-bit)
)

**Additional context**
GL 4.9.9 running on ubuntu 18.04.6

**Comment by evilaliv3** [comment]
Thank you for your question @gianlucagilardi 

Do you confirm that your tests were made on a remote platform not featuring HTTPS?

The copy-to-clibpoard functionality rely on a standard browser API that is either available on what browser calls a secure context (HTTPS) or localhost

**Comment by evilaliv3** [comment]
Thank you @gianlucagilardi
