### ISSUE TITLE
Error during clean installation - Repository not signed

### ISSUE THREAD

**Issue by serberci** [globaleaks/GlobaLeaks#3240]
I made clean installation using the following:

wget https://deb.globaleaks.org/install-globaleaks.sh
chmod +x install-globaleaks.sh
./install-globaleaks.sh

When execute the .sh failed:

E: The repository 'http://deb.globaleaks.org focal/ InRelease' is not signed.

What can i do?

Thanks

**Comment by evilaliv3** [comment]
Thank you for reporting this @serberci 

The issue on the signature should be fixed now. Please feel free to retry and it should work!
