### ISSUE TITLE
"BAD signature" for Debian bulleys 

### ISSUE THREAD

**Issue by ship3262** [globaleaks/GlobaLeaks#3250]
gpg --verify Release.gpg globaleaks_4.9.9_all.deb
gpg: Signature made Thu 30 Jun 2022 08:35:21 AM UTC
gpg:                using RSA key B353922AE4457748559E777832E6792624045008
gpg: BAD signature from "GlobaLeaks software signing key <info@globaleaks.org>" [unknown]

from my machine 
 lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

**Additional context**
I'm new! I think the signature for the debian bulleys has not be updated. but I dont know.

**Comment by evilaliv3** [comment]
@ship3262: could you please try to install using our official installation guide and let me know if it works for you?

https://docs.globaleaks.org/en/main/setup/InstallationGuide.html

**Comment by ship3262** [comment]
Id like to check the keys and signature of the files before I install. 
especially if I must run the script as root.

"Error: GlobaLeaks install script must be run by root"

**Comment by evilaliv3** [comment]
Thank you. 

If you want you could do that. Keys are public and listed inside the install script.

**Comment by ship3262** [comment]
Thank you
