### ISSUE TITLE
Cant find views folder

### ISSUE THREAD

**Issue by JimpoTEDY** [globaleaks/GlobaLeaks#3251]
Hello, unfortunately I cannot find the footer and header.html in File Zilla after the installation. How can I access it? Unfortunately, I don't have that much knowledge about this topic. Thanks in advance.

**Comment by evilaliv3** [comment]
Thank you for your question.

Actually Globaleaks is not meant to be manually customized by editing
files. That would actually invalidate the security of the system.

If you would like please elaborate what you would like to do and we may try
to support you implementing it via the functionalities offered by the web
interface.

**Comment by evilaliv3** [comment]
@zangels: Which is you username on transifex?

**Comment by zangels** [comment]
@evilaliv3 it's "jose.anjos"
Thkz

**Comment by zangels** [comment]
> * Actually original files of the application are not meant to be customized but you can upload your custom css via the web interface.

but is it possible to have the 'class' name given to the elements?
so I could use them in a/the new css file?

**Comment by evilaliv3** [comment]
Sure thing.

Actually i would invite you to check current classes and ids assigned to HTML elements and let us know if you need anything that you could not customize and make suggestions.

**Comment by zangels** [comment]
> 

Thank you so much!
And where can I do that? or how?

**Comment by zangels** [comment]
> 

Thank you so much!
And where can I do that? or how?

**Comment by evilaliv3** [comment]
By using the javascript console of a common browser

E.g. try to digit CTRL + SHIFT + J on Google Chrome
