### ISSUE TITLE
about Boostrap CSS Framework

### ISSUE THREAD

**Issue by zangels** [globaleaks/GlobaLeaks#3254]
Hello!

In search for a better control over de UX/UI design, I noticed that the radio-button element is misconfigured (the space between de button and the text).
![image](https://user-images.githubusercontent.com/109809253/182650928-29cef6fe-8606-41e6-af91-8080814bf818.png)

So I understod that GL uses the Boostrap CSS Framework, and noticed that the radio-button elements shown here: https://getbootstrap.com/docs/5.2/forms/checks-radios/
is diferent from the one in GL. I wonder if the version of Boostrapp CSS used in GL is updated?

If this doesn't work I would like some help to know which element/class/id property I should change to correct the detail.

Thank you in advance

**Comment by evilaliv3** [comment]
We currently use Bootstrap 4

**Comment by zangels** [comment]
So is it possible to update it?

**Comment by evilaliv3** [comment]
Globaleaks at the moment is built on bootstrap 4 and we are planning to
update in future releases.

As GlobaLeaks is an open source software please feel free if you like to
contribute to it with pull requests for improvements like this.

**Comment by zangels** [comment]
Sure!!
I think this platform is wonderful and it realy matches our needs for compliance of the wistleblower protection directive

I've already translated more than 200 entrys (everything there was to translate) in transifex.
PT-PT is now 100% translated. Just wayting for the reviewers (I already sent each one a msg, and the coordinators too).

I'm not a coder but if you think I can help in something specific, please tell me, i'm available.

**Comment by evilaliv3** [comment]
Thank for for your feedback and for the support on completing the translations.

Those will be reviewed and included in the next release.
