### ISSUE TITLE
Favicon upload failed with 403 Forbidden

### ISSUE THREAD

**Issue by lasat** [globaleaks/GlobaLeaks#3258]
**Describe the bug**
I try to upload a customized favicon, but the upload request return 403 Forbidden.

**To Reproduce**
1. New Setup, Wizard completed
2. Go to "Site Settings" -> "Theme Customization"
3. Upload Favicon.ico 
4. See error in logs and nothing changed on frontend

**Expected behavior**
The uploaded favicon could be uploaded and displayed (as for logo and other files)

**Screenshots**
- Headers: ![grafik](https://user-images.githubusercontent.com/8647114/184901176-969695da-0545-4938-b39d-e8fed94a4c17.png)
- Request: ![grafik](https://user-images.githubusercontent.com/8647114/184900759-b6ddd379-4580-407c-8e8a-b84dfda5ea89.png)
- Response: ![grafik](https://user-images.githubusercontent.com/8647114/184900372-58354fbb-ad62-49fb-83a8-9c2a4404781c.png)

**Desktop:**
 - OS: Ubuntu
 - Browser: Firefox 103.0.2

**Comment by evilaliv3** [comment]
Thank you for your feedback. Which version of the software of Globaleaks
are you running?

**Comment by gianlucagilardi** [comment]
I am afraid the fix did not address the issue completely, there is still the same problem in 4.10.3 (clean install).... Tried with both .ico and .png files, same result.

**Comment by evilaliv3** [comment]
Thank you @gianlucagilardi 

The only file accepted should be the .ico, let me check what went wrong.

**Comment by gianlucagilardi** [comment]
patch in 4.10.4 works like charm, thanks! :)

**Comment by plrunner** [comment]
Looks like this problem is back in v4.14.8.
