### ISSUE TITLE
I18N: Translation failure DE (SMTP settings require auth)

### ISSUE THREAD

**Issue by lasat** [globaleaks/GlobaLeaks#3262]
**Describe the bug**
SMTP-Settings -> Require Authentication is translated to de "Erfordert Bestätigung" but should be "Erfordert Anmeldung"

[GitHub Search](https://github.com/globaleaks/GlobaLeaks/search?q=Erfordert+Best%C3%A4tigung)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/8647114/185067319-4a15ea63-a09d-4322-9fc9-8da398c7e49e.png)

**Comment by evilaliv3** [comment]
Thank you!

I've appied the change that will be included in the next minor release.
