### ISSUE TITLE
Duplicate options in advanced settings

### ISSUE THREAD

**Issue by gianlucagilardi** [globaleaks/GlobaLeaks#3263]
Hi :)
there are apparently some duplicated entries in the advanced settings section of admin panel, namely the "disable privacy panel" and "enable custom privacy panel" :) [rel. 4.10.1]

![2022-08-17 10_58_58-Sourcetree](https://user-images.githubusercontent.com/2210991/185079361-db28a02a-c557-41af-b800-50025c730d05.png)

**Comment by evilaliv3** [comment]
Thank you @gianlucagilardi, this was already reported and is fixed in the development branch.

https://github.com/globaleaks/GlobaLeaks/issues/3260

The fix will be included in the next minor release 4.10.2
