### ISSUE TITLE
Error using conditional activation in questions

### ISSUE THREAD

**Issue by frayber** [globaleaks/GlobaLeaks#3265]
Hello, this is what I do:

1. create a new question with one multiple choice (d1 and d2)
2. create another question with one multiple choice (d3 and d4)
3. I add an activation condition on the second question, based on the choice d2 of the first question
4. I save the question 
5. I save the form, but if I open again the form and second question, no activation condition is displayed

Moreover, if I delete the questions and I create other 2 new questions, If I try to add a conditional activation, in the select that appear I only see the old choices that I deleted before. 

Maybe is it related to https://github.com/globaleaks/GlobaLeaks/issues/3264 ?
Thank you

**Comment by frayber** [comment]
I tried to delete the questionairre and recreate a new one, but the problem is still present.

**Comment by evilaliv3** [comment]
Thank you fryber.

Would you please try the following:
- create the questions
- close the browser
- open the browser again
- add the conditions of activation

I suspect in fact that the bug exists only if you create the conditions immediately after creating the questions

Thank you if you could check this that would help identifying the condition properly and fix it.

**Comment by frayber** [comment]
If I can help you, we have 4.10.5 version, but we started with an old 3.x version upgraded many times.

**Comment by frayber** [comment]
When I click on the save button of the question, conditions are saved, but after that, when I click on save button of the questionnaire it isn't saved. Other ideas? Thanks

**Comment by evilaliv3** [comment]
1) Options of questions and conditions on options are saved only when you
click the save button at question level.

Does this work?

2) which are the configurations that you are looking to save when you click
the save button of the questionnaire and in which problem are you incurring?

**Comment by frayber** [comment]
1) yes, it works
2) I click on the save button of the questionnaire, and I reopen for editing the questionnaire, I reopen for editing the question with options and conditions, conditions are not present anymore. If I open the questionnaire as user, I see all options without conditions.
Thanks

**Comment by evilaliv3** [comment]
Did you save the conditions using the question button before saving the
questionnaire?

> Message ID: ***@***.***>
>

Thank you for supporting this understanding.
As soon that the issue will be well clear i will proceed with the fix.

**Comment by frayber** [comment]
Yes, I saved the question and then the questionnaire.
Thank you

**Comment by evilaliv3** [comment]
@frayber : i just tried to reproduce this issue with no success.

would it be possible for you to record a small video of the procedure.

**Comment by frayber** [comment]
I recorded 2 videos, can I send them at your email giovanni.pellerano@globaleaks.org?
Thank you

**Comment by frayber** [comment]
I sent videos at you email, thank you.

**Comment by frayber** [comment]
I've just realized that we didn't click on the second "Add" button at the bottom of conditions, I'm sorry, it isn't a bug.

**Comment by evilaliv3** [comment]
Do you confirm that after adding the conditions you are saving using the
save button at question level?
