### ISSUE TITLE
blank page when after installing package version 4.10.5 on Ubuntu Focal Fossa (22)

### ISSUE THREAD

**Issue by stgitdeploy** [globaleaks/GlobaLeaks#3266]
I have tried to install globaleaks on tree diferent OS ubuntu 22, 20 and when I try to visit in setup panel by ip:80 it gives me a blank white page

**Comment by evilaliv3** [comment]
Thank you @stgitdeploy; This has been already reported and has been fixed with commit https://github.com/globaleaks/GlobaLeaks/commit/581248795759c853f95c7aea111430cdaa0d10ca

You could now update to release version 4.10.6 that includes the fix.
