### ISSUE TITLE
Installation of 4.10.7 fails when run in a container

### ISSUE THREAD

**Issue by cdlh** [globaleaks/GlobaLeaks#3267]
Tried to install in a fresh container today (Debian GNU/Linux 11 \n \l). Result:

Setting up globaleaks (4.10.7) ...
Job for globaleaks.service failed because the control process exited with error code.
See "systemctl status globaleaks.service" and "journalctl -xe" for details.
invoke-rc.d: initscript globaleaks, action "start" failed.
^[[0;1;31m*^[[0m globaleaks.service - LSB: Start the GlobaLeaks server.
     Loaded: loaded (^[]8;;file://whistleproof/etc/init.d/globaleaks^G/etc/init.d/globaleaks^[]8;;^G; generated)
     Active: ^[[0;1;31mfailed^[[0m (Result: exit-code) since Fri 2022-08-26 08:13:10 UTC; 4ms ago
       Docs: ^[]8;;man:systemd-sysv-generator(8)^Gman:systemd-sysv-generator(8)^[]8;;^G
    Process: 3793 ExecStart=/etc/init.d/globaleaks start ^[[0;1;31m(code=exited, status=1/FAILURE)^[[0m
        CPU: 39ms

Aug 26 08:13:10 whistleproof systemd[1]: Starting LSB: Start the GlobaLeaks server....
Aug 26 08:13:10 whistleproof globaleaks[3793]: Starting GlobaLeaks daemon: globaleaksStarting ...Enabling Globaleaks Network Sandboxing...done.
Aug 26 08:13:10 whistleproof globaleaks[3793]: GlobaLeaks Apparmor Sandboxing Failure: requires apparmor ...
Aug 26 08:13:10 whistleproof globaleaks[3834]:  failed!
Aug 26 08:13:10 whistleproof systemd[1]: ^[[0;1;39m^[[0;1;31m^[[0;1;39mglobaleaks.service: Control process exited, code=exited, status=1/FAILURE^[[0m
Aug 26 08:13:10 whistleproof systemd[1]: ^[[0;1;38;5;185m^[[0;1;39m^[[0;1;38;5;185mglobaleaks.service: Failed with result 'exit-code'.^[[0m
Aug 26 08:13:10 whistleproof systemd[1]: ^[[0;1;31m^[[0;1;39m^[[0;1;31mFailed to start LSB: Start the GlobaLeaks server..^[[0m
dpkg: error processing package globaleaks (--configure):
 installed globaleaks package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for libc-bin (2.31-13+deb11u3) ...
Errors were encountered while processing:
 globaleaks
E: Sub-process /usr/bin/dpkg returned an error code (1)

Result of systemctl status globaleaks.service
* globaleaks.service - LSB: Start the GlobaLeaks server.
     Loaded: loaded (/etc/init.d/globaleaks; generated)
     Active: failed (Result: exit-code) since Fri 2022-08-26 08:13:10 UTC; 4min 8s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 3793 ExecStart=/etc/init.d/globaleaks start (code=exited, status=1/FAILURE)
        CPU: 39ms

Aug 26 08:13:10 whistleproof systemd[1]: Starting LSB: Start the GlobaLeaks server....
Aug 26 08:13:10 whistleproof globaleaks[3793]: Starting GlobaLeaks daemon: globaleaksStarting ...Enabling Globaleaks Network Sandboxing...done.
Aug 26 08:13:10 whistleproof globaleaks[3793]: GlobaLeaks Apparmor Sandboxing Failure: requires apparmor ...
Aug 26 08:13:10 whistleproof globaleaks[3834]:  failed!
Aug 26 08:13:10 whistleproof systemd[1]: globaleaks.service: Control process exited, code=exited, status=1/FAILURE
Aug 26 08:13:10 whistleproof systemd[1]: globaleaks.service: Failed with result 'exit-code'.
Aug 26 08:13:10 whistleproof systemd[1]: Failed to start LSB: Start the GlobaLeaks server..

Result of journalctl -xe
-- Subject: A start job for unit globaleaks.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- A start job for unit globaleaks.service has finished with a failure.
-- 
-- The job identifier is 313 and the job result is failed.
Aug 26 08:13:10 whistleproof Tor[3521]: Bootstrapped 10% (conn_done): Connected to a relay
Aug 26 08:13:22 whistleproof Tor[3521]: Bootstrapped 14% (handshake): Handshaking with a relay
Aug 26 08:13:22 whistleproof Tor[3521]: Bootstrapped 15% (handshake_done): Handshake with a relay done
Aug 26 08:13:22 whistleproof Tor[3521]: Bootstrapped 20% (onehop_create): Establishing an encrypted directory connection
Aug 26 08:13:22 whistleproof Tor[3521]: Bootstrapped 25% (requesting_status): Asking for networkstatus consensus
Aug 26 08:13:23 whistleproof Tor[3521]: Bootstrapped 30% (loading_status): Loading networkstatus consensus
Aug 26 08:13:31 whistleproof Tor[3521]: I learned some more directory information, but not enough to build a circuit: We have no usable consensus.
Aug 26 08:13:31 whistleproof Tor[3521]: Bootstrapped 40% (loading_keys): Loading authority key certs
Aug 26 08:13:32 whistleproof Tor[3521]: The current consensus has no exit nodes. Tor can only build internal paths, such as paths to onion services.
Aug 26 08:13:32 whistleproof Tor[3521]: Bootstrapped 45% (requesting_descriptors): Asking for relay descriptors
Aug 26 08:13:32 whistleproof Tor[3521]: I learned some more directory information, but not enough to build a circuit: We need more microdescriptors:>
Aug 26 08:13:32 whistleproof Tor[3521]: Bootstrapped 50% (loading_descriptors): Loading relay descriptors
Aug 26 08:13:32 whistleproof Tor[3521]: The current consensus contains exit nodes. Tor can build exit and internal paths.
Aug 26 08:13:33 whistleproof Tor[3521]: Bootstrapped 56% (loading_descriptors): Loading relay descriptors
Aug 26 08:13:33 whistleproof Tor[3521]: Bootstrapped 63% (loading_descriptors): Loading relay descriptors
Aug 26 08:13:34 whistleproof Tor[3521]: Bootstrapped 73% (loading_descriptors): Loading relay descriptors
Aug 26 08:13:34 whistleproof Tor[3521]: Bootstrapped 75% (enough_dirinfo): Loaded enough directory info to build circuits
Aug 26 08:13:34 whistleproof Tor[3521]: Bootstrapped 80% (ap_conn): Connecting to a relay to build circuits
Aug 26 08:13:34 whistleproof Tor[3521]: Bootstrapped 85% (ap_conn_done): Connected to a relay to build circuits
Aug 26 08:13:34 whistleproof Tor[3521]: Bootstrapped 89% (ap_handshake): Finishing handshake with a relay to build circuits
Aug 26 08:13:34 whistleproof Tor[3521]: Bootstrapped 90% (ap_handshake_done): Handshake finished with a relay to build circuits
Aug 26 08:13:34 whistleproof Tor[3521]: Bootstrapped 95% (circuit_create): Establishing a Tor circuit
Aug 26 08:13:34 whistleproof Tor[3521]: Bootstrapped 100% (done): Done

**Comment by evilaliv3** [comment]
Dear @cdlh, thank you for your feedback.

Actually in the last release we have enforced the use of apparmor and iptables that are probably components not present inside your container technology (which is?)

To resolve the issue you can create a file /etc/default/globaleaks with the content:
```
APPARMOR_SANDBOXING=0
NETWORK_SANDBOXING=0
```

**Comment by evilaliv3** [comment]
@cdlh : If you manage to succed in a containerized setup, do you mind support the improvement of these scripts?

https://github.com/globaleaks/globaleaks-docker-scripts

Thank you if you could

**Comment by cdlh** [comment]
Hi @evilaliv3,
thank you for your answer.

I have a proxmox-installation on a intel-nuc and installed a debian-lxc on it.  Do you need more information?

I added the content to the /etc/default/globaleaks file, with no success. I can start the service manually, but i don't feel comfortable with an error during setup ... ;)

**Comment by evilaliv3** [comment]
Can you paste the log after the addition of the lines that i gave to you?

Actually your previous log shows clearly that APPARMOR is non presente in your setup and globaleaks was failing for this reason

**Comment by cdlh** [comment]
Yes, of course:

systemctl status globaleaks.service
* globaleaks.service - LSB: Start the GlobaLeaks server.
     Loaded: loaded (/etc/init.d/globaleaks; generated)
     Active: failed (Result: exit-code) since Fri 2022-08-26 09:18:28 UTC; 18min ago
       Docs: man:systemd-sysv-generator(8)
    Process: 157 ExecStart=/etc/init.d/globaleaks start (code=exited, status=1/FAILURE)
        CPU: 1.258s

Aug 26 09:18:26 whistleproof systemd[1]: Starting LSB: Start the GlobaLeaks server....
Aug 26 09:18:28 whistleproof globaleaks[157]: Starting GlobaLeaks daemon: globaleaksStarting ...
Aug 26 09:18:28 whistleproof globaleaks[326]: [E] ERROR: Cannot start GlobaLeaks. Please manually examine the exception.
Aug 26 09:18:28 whistleproof globaleaks[326]: [E] EXCEPTION: [Errno 13] Permission denied: '/var/globaleaks/log/globaleaks.log'
Aug 26 09:18:28 whistleproof globaleaks[326]: Failed to load application: '>=' not supported between instances of 'PermissionError' and 'int'
Aug 26 09:18:28 whistleproof globaleaks[157]: failed.
Aug 26 09:18:28 whistleproof systemd[1]: globaleaks.service: Control process exited, code=exited, status=1/FAILURE
Aug 26 09:18:28 whistleproof systemd[1]: globaleaks.service: Failed with result 'exit-code'.
Aug 26 09:18:28 whistleproof systemd[1]: Failed to start LSB: Start the GlobaLeaks server..
Aug 26 09:18:28 whistleproof systemd[1]: globaleaks.service: Consumed 1.258s CPU time.

But don't invest too much time - i can install a normal debian-vm and work with that one if the problem is related to my lxc-setup.

**Comment by cdlh** [comment]
Yes! That was the problem. Thank you very much, also for your patience. 
Can be closed ...

**Comment by evilaliv3** [comment]
You are welcome.

Thank you for your feedback!
