### ISSUE TITLE
A way of managing presentation max width since v4.10.0

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3268]
Hi @evilaliv3 

I have been managing maximum width of the presentation value (text seen on the front page) by using HTML (see below), which is not possible since latest development.

The defaults, on a big screen is way too wide. 
Is there a chance to give end-users a way to manage max-width? Or maybe implement this snippet as default?

```
<div class="row">

  <div class="col-xl-1"></div>

  <div class="col-xl-10">

      Presentation content

  </div>

  <div class="col-xl-1"></div>

</div>
```

**Comment by evilaliv3** [comment]
Thank you for your feedback.

Such a change would impact existing setups and complicate the layout.

Maybe you could instead apply a CSS configuration on #Presentation and use some 'media' query in relation to the screen size?
