### ISSUE TITLE
Receiver welcome screen HTML customisation without function

### ISSUE THREAD

**Issue by itnavigator** [globaleaks/GlobaLeaks#3269]
Hello,
my GlobaLeaks config working fine under 4.7.10.
But since I've updated to 4.10.7 my custom welcome screen text formation with html doesn't workling anymore. 

No <b>, <a href= or so on is working. It's everytime only plain text.

Im not sure it's a bug or a feature.

Thank you for your assistant!

best regards

**Comment by evilaliv3** [comment]
Thank you for your question @itnavigator 

Actually before release 4.10.0 the application was accepting both markdown and html for configurations.

From release 4.10.0 instead the application accepts only markdown for a matter of security reasons.

If you want to add a link you can do it by using the syntax ```(link)[link title]```

**Comment by itnavigator** [comment]
Thank you for the information. The most of it is working fine.

The only problem now is the text alignment. All text is with align center. That's look a little bit strange...
In the Showdown Markdown Syntax I can't found a solution for that. 

Do you have an idea?

**Comment by zangels** [comment]
Hi!
I think you will have to use the CSS loading features.
I created and uploaded a CSS file with the code:
```
#HomePageBox {
    text-align: left;
}
#WhistleblowerSubmitBox {
    text-align: left;
}
#WhistleblowerLoginBox {
    text-align: left;
}
#FooterBox {
     text-align: left;
}
```
But[ the "login box" doesn't align to the left](https://forum.globaleaks.org/t/css-loginbox-alignment/726?u=jose.anjos).
If you sort this out please tell me.
