### ISSUE TITLE
Install on Amazon Linux 2 

### ISSUE THREAD

**Issue by stgitdeploy** [globaleaks/GlobaLeaks#3270]
Hi, Dear Globaleks team, How I can install globaleaks on Amazon Linux 2 machine? do you have a .rpm package for that? 
thank you

**Comment by evilaliv3** [comment]
Thank you for your question @stgitdeploy 

GlobaLeaks is actually currently packaged only for Debian/Ubuntu.
We have some tickets that discuss the possibility to extend support additional distributions and specifically in relation to [RPM packaging](https://github.com/globaleaks/GlobaLeaks/issues/786) but there is currently not active development on this.

**Comment by stgitdeploy** [comment]
ok thank you
