### ISSUE TITLE
Issues with removing and reinstalling globaleaks

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3272]
**Describe the bug**
When trying to remove platform (4.10.7) I use
apt-get remove --purge globaleaks

**when trying to reinstall I receive the following errors:**

8-29 14:52:22 (377 MB/s) - ‘install-globaleaks.sh.1’ saved [5411/5411]
                           ./install-globaleaks.sh
Running the GlobaLeaks installation...
In case of failure please report encountered issues to the ticketing system at: https://github.com/globaleaks/GlobaLeaks/issues

Detected OS: Ubuntu - focal
WARNING: The GlobaLeaks software lifecycle includes full support for all Debian and Ubuntu LTS versions starting from Debian 10 and Ubuntu 20.04
WARNING: The currently recommended distribution is: Debian 11 (Bullseye)
Do you wish to continue anyway? [y|n]?y
Running: "apt-get -y update"... SUCCESS
Reading package lists... Done
Building dependency tree       
Reading state information... Done
tzdata is already the newest version (2022a-0ubuntu0.20.04).
The following packages were automatically installed and are no longer required:
  geoip-database libgeoip1 python3-acme python3-geoip python3-gnupg python3-h2
  python3-hpack python3-hyperframe python3-josepy python3-mock python3-pbr
  python3-priority python3-requests-toolbelt python3-rfc3339
  python3-sqlalchemy python3-sqlalchemy-ext python3-txtorcon python3-tz
Use 'apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded.

Current default time zone: 'Etc/UTC'
Local time is now:      Mon Aug 29 14:52:35 UTC 2022.
Universal Time is now:  Mon Aug 29 14:52:35 UTC 2022.

Running: "apt-get -y install curl gnupg net-tools software-properties-common"... SUCCESS
Running: "is_tcp_sock_free_check 0.0.0.0:80"... SUCCESS
Running: "is_tcp_sock_free_check 0.0.0.0:443"... SUCCESS
Running: "is_tcp_sock_free_check 127.0.0.1:8082"... SUCCESS
Running: "is_tcp_sock_free_check 127.0.0.1:8083"... SUCCESS
 + required TCP sockets open
Adding GlobaLeaks PGP key to trusted APT keys
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5519  100  5519    0     0  37801      0 --:--:-- --:--:-- --:--:-- 37801
OK
Updating GlobaLeaks apt source.list in /etc/apt/sources.list.d/globaleaks.list ...
Running: "apt-get update -y"... SUCCESS
Running: "apt-get install globaleaks -y"... FAIL
Ouch! The installation failed.
COMBINED STDOUT/STDERR OUTPUT OF FAILED COMMAND:
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  globaleaks
0 upgraded, 1 newly installed, 0 to remove and 11 not upgraded.
Need to get 0 B/3551 kB of archives.
After this operation, 17.1 MB of additional disk space will be used.
Selecting previously unselected package globaleaks.
(Reading database ... 59389 files and directories currently installed.)
Preparing to unpack .../globaleaks_4.10.7_all.deb ...
Unpacking globaleaks (4.10.7) ...
Setting up globaleaks (4.10.7) ...
Job for globaleaks.service failed because the control process exited with error code.
See "systemctl status globaleaks.service" and "journalctl -xe" for details.
invoke-rc.d: initscript globaleaks, action "start" failed.
● globaleaks.service - LSB: Start the GlobaLeaks server.
     Loaded: loaded (/etc/init.d/globaleaks; generated)
     Active: failed (Result: exit-code) since Mon 2022-08-29 14:52:44 UTC; 9ms ago
       Docs: man:systemd-sysv-generator(8)
    Process: 8974 ExecStart=/etc/init.d/globaleaks start (code=exited, status=1/FAILURE)

Aug 29 14:52:44 CISvm globaleaks[9016]:     self.create_directory(dirpath)
Aug 29 14:52:44 CISvm globaleaks[9016]:   File "/usr/lib/python3/dist-packages/globaleaks/state.py", line 134, in create_directory
Aug 29 14:52:44 CISvm globaleaks[9016]:     raise excep
Aug 29 14:52:44 CISvm globaleaks[9016]:   File "/usr/lib/python3/dist-packages/globaleaks/state.py", line 130, in create_directory
Aug 29 14:52:44 CISvm globaleaks[9016]:     os.mkdir(path)
Aug 29 14:52:44 CISvm globaleaks[9016]: PermissionError: [Errno 13] Permission denied: '/var/globaleaks/'
Aug 29 14:52:44 CISvm globaleaks[8974]:    ...fail!
Aug 29 14:52:44 CISvm systemd[1]: globaleaks.service: Control process exited, code=exited, status=1/FAILURE
Aug 29 14:52:44 CISvm systemd[1]: globaleaks.service: Failed with result 'exit-code'.
Aug 29 14:52:44 CISvm systemd[1]: Failed to start LSB: Start the GlobaLeaks server..
dpkg: error processing package globaleaks (--configure):
 installed globaleaks package post-installation script subprocess returned error exit status 1
Processing triggers for systemd (245.4-4ubuntu3.17) ...
Errors were encountered while processing:
 globaleaks

**Comment by evilaliv3** [comment]
Thank you for reporting this @elbill 

This is actually a regression introduced in 4.10.0 by appliying a fix recommended by our last security audit.

I'm going to fix this right away with a patch that will be included in the next minor release
