### ISSUE TITLE
Installation inside lxc container

### ISSUE THREAD

**Issue by klu0** [globaleaks/GlobaLeaks#3274]
Hello, 
i can’t install recent releases of globaleaks inside lxc container.

Below the screenshot of the error message:

![gl_screen1](https://user-images.githubusercontent.com/112711606/188204248-87759ae5-2f48-40f3-b82e-ebf55375d8b9.png)

Thank you in advance

**Comment by evilaliv3** [comment]
Thank you @klu0 

I suspect this could be related to https://github.com/globaleaks/GlobaLeaks/issues/3267

try to create a file ```/etc/default/globaleaks``` with the content ```APPARMOR_SANDBOXING=0```
