### ISSUE TITLE
HTML-Tags in Footer are ignored in recent release

### ISSUE THREAD

**Issue by peterknapp** [globaleaks/GlobaLeaks#3275]
In previous releases it was possible to add HTML-Tags into e.g. the Footer via the Admin-Panel. For us, this was the best way to add a link (<a> tag) to our imprint and privacy policy etc.

This changed somehow in one of the recent versions.

Will this come back or is there another way to add this?

I am aware (now) that this is a security issue...

We need to add Links to our Imprint, Privacy Guidelines and to the Licence.

**Comment by evilaliv3** [comment]
Plain HTML is not accepted in any of the configuration inputs, but you could use markdown with the showdown syntax

E.g. add a link you could write ```[title](link)```
