### ISSUE TITLE
Change Port 443 to 8082 Debian 11

### ISSUE THREAD

**Issue by miguelpalma81** [globaleaks/GlobaLeaks#3279]
Hi!

How can I change port 443 to 8082.

Example https://server:8082

Thanks.

**Comment by evilaliv3** [comment]
Hello @miguelpalma81

At the moment we have designed a system that is always exposed publicly on port 80/443 where all the trat modeling and the potections applied (e.g. firewall configurations) take into considerations this and for this reason the software does not currently offer the possibility to be exposed on alternative ports.

Would you please clarify about your use case and why you would prefer to use an alternative port?
If you can and would like please feel free to propose a patch to make these aspects configurable.

**Comment by miguelpalma81** [comment]
Hello again @evilaliv3,

Ports 443 and 80 are already in use. We also don't have public IPs available to forward to the internal port 443. It would be a temporary solution.

Thank you very much for the feedback.

**Comment by evilaliv3** [comment]
I see. Thank you for clarifying.

In this case i will just temporarely close the ticket and eventually open a new one in the future specifically dedicate on making this aspects configurable in /etc/default/globaleaks
