### ISSUE TITLE
Forgot admin password and changed SMTP server

### ISSUE THREAD

**Issue by cantarod** [globaleaks/GlobaLeaks#3281]
Hi,

**Describe the bug**
I forgot the admin, password and at the same time I changed SMTP server.

**Expected behavior**
Is there any chance to reset admin password from OS, or change the SMTP settings on any config file from OS?

Thanks and regards,
Davide

**Comment by evilaliv3** [comment]
Dear Davide,

Thank you for your question.

In general all the settings are currently designed to be changed only via the web interface.
Knowing how the application works one can attempt to change some settigns by accessing the database with sqlitebrowser that could work for changing simple variables like an SMTP configuration (table config, the variables have prefix smtp_)

In relation specifically to the lost password if your system runs the latest globaleaks and encryption is enabled there is unfortunately no way for recovering the account password  if not asking an other administrator or having access to the account recovery key of your account.
If you could clarify more about your system i may try advise you more specifically.

**Comment by cantarod** [comment]
Hi,

Thanks for your quick reply.
if I can change SMTP settings I'll be able to reset my password using the web interface. Can you help me set up SMTP from the DB?

**Comment by evilaliv3** [comment]
Ok

As first attempt i would try issuing:
```gl-admin resetpass <username>```

If you system is old and you never enabled encryption  this command will give you a new password.

If this does not work you could change the following variables by accessing the Config table via ```sqlitebrowser``` or via the command ```gl-admin setvar <varname> <value>```:
- smtp_authentication
- smtp_password
- smtp_port
- smtp_security
- smtp_server
- smtp_source_email
- smtp_username

If you want you can read current settings using ```g-ladmin getvar <varname>```

**Comment by cantarod** [comment]
Hi, unfortunately encryption is enabled.
I've check variables and found that smtp server is mail.globaleaks.org. i tried with forgot password, but it didn't work. How can I check logs?

**Comment by evilaliv3** [comment]
Removing this ticket that is being handled privately.
