### ISSUE TITLE
SSL configuration in multisite istance

### ISSUE THREAD

**Issue by zazzati** [globaleaks/GlobaLeaks#3283]
**Describe the bug**
First subsite configuration in multi site configuration OK
Second site, after manual configuration of SSL certs, error 400 (bad request) in subsite

**To Reproduce**
Sites created in MODE "Default" (MODE WHISTLEBLOWINGPA throw Internal server error (Unexpected))
After creation:
[Sites management] -> Select 2nd subsite, [Network settings] -> Insert Hostname (save) -> Manual configuration, loading ssl private key, loading public CRT, press [Enable] -> redirection to site -> http 400 error

**version**
OS DEBIAN 11
GL version 4.10.10

**Additional info**
We tried to delete all the sites and also recreate them in different order. 
Only the first inserted after installing the new fresh instance of GL always works, even if it is inserted as the second or third. 
Others throw error 400 after SSL configuration.
There are no sub-site errors in the logs.

thx

**Comment by evilaliv3** [comment]
Thank you.

Could you please clarify about the configuration of the hostname of the
tenants?

I suspect this could be improperly configured that is why you are getting
error 400

**Comment by zazzati** [comment]
Actually hostname of tenants are

1  `a*********e.af***o.c**.it`   IT WORKS
2  `a*********e.af*****o.c******e.it` NOT WORKING 
3  `a*****e.t******i.it`  NOT WORKING

If we change the order
2  `a*********e.af*****o.c******e.it` NOT WORKING 
3  `a*****e.t******i.it ` NOT WORKING
1  `a*********e.af***o.c**.it`   IT WORKS

Only the 1 works.

Do you need additional info about the configuration of the hostname?

**Comment by evilaliv3** [comment]
Thank you for reporting this. Actually from this examples i could not understand.
We have a large set of similar multitenant systems and all are working correctly.

If you can please share to me privately some screenshots of the pages where hostnames are configured.


Thank you

**Comment by zazzati** [comment]
We have found the problem and it is caused by the particular network infrastructure we are operating in.
I close, thanks
