### ISSUE TITLE
Cannot file a report when recipients are not configured.

### ISSUE THREAD

**Issue by Nico82x** [globaleaks/GlobaLeaks#3284]
**Describe the bug**
Upon loading the homepage and when trying to submit an issue using the form, the form will not submit and in the developer console, I see the following errors:

[
](scripts.min.js:8 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'sha256-fwyo2zCGlh85NfN4rQUlpLM7MB5cry/1AEDA/G9mQJ8='". Either the 'unsafe-inline' keyword, a hash ('sha256-uD+9kGdg1SXQagzGsu2+gAKYXqLRT/E07bh4OhgXN8Y='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.)

This message appears multiple times on a completely fresh installation on Ubuntu 22.04 LTS from today using your setup script.

**To Reproduce**
1. Go to 'the main page'
2. Open the developer console
3. Click on 'File a report'

**Expected behavior**
The submit form should work.

**Screenshots**
<img width="551" alt="Screenshot at Sept 21 23-59-50" src="https://user-images.githubusercontent.com/46298448/191618170-3ff88348-c322-4689-b35a-1277f1444ae2.png">

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Chrome (Version 105.0.5195.102 (Offizieller Build) (arm64)
) and Firefox (104.0.1 (64-Bit)

**Additional context**
Similar issue was found here but with no solution: https://forum.globaleaks.org/t/cant-submit-report/705/3

I can share the actual website if required but prefferably via PN.

**Comment by Nico82x** [comment]
Update: I startet the daemon script with "-d" to disable content-security-policy for testing but interestingly the form still does not submit but the previous CSP errors are gone. The form does complain when required fields are not entered but when there are no more empty fields, the click on the button just does nothing.

**Comment by evilaliv3** [comment]
Thank you for reporting this @Nico82x 

Actually what you are reporting is not related to the Content Security Policy and this is why the system do not work even if you disable it.
The errors you get are perfectly fine and part of the standard applications that stops the functionality of some components.

Your issue is probably related to the fact that you currently have not recipients on the system attached to the submission context.
Please get sure to have already one recipient and to assign it to the default submission context

**Comment by Nico82x** [comment]
Thanks @evilaliv3 you were absolutely correct, after adding recipients it worked. Thanks for that! If you don't mind we can still keep this issue open for the probably fixable CSP errors but up to you of course!

**Comment by evilaliv3** [comment]
Thank you @Nico82x 

The content security errors that you see are normal errors that you will see in any setup.
Our content security policy is very strict and blocks som of our own software components that uses inline css styles.
