### ISSUE TITLE
Set tip data retention based on tip status

### ISSUE THREAD

**Issue by dmalacaria** [globaleaks/GlobaLeaks#3285]
In order to manage tips retention in a flexible way it could be useful to have the capability to set tip retention based on its status, something like: 
delete Tip after X days it is set to: "closed"

**Comment by evilaliv3** [comment]
Thank you for this feature suggestion @dmalacaria 

Actually it was already  specified here: https://github.com/globaleaks/GlobaLeaks/issues/2523

Closing this ticket as duplicate
