### ISSUE TITLE
description attribute for each attachment

### ISSUE THREAD

**Issue by dmalacaria** [globaleaks/GlobaLeaks#3286]
Multiple attachements are already permitted but it's not possible so far to set for each of them a description to be showed in the table with the list of attachments sent by whistleblower.
Have a "description" attribute for each attachment and let it will be showed with the other attachments information in the table could be better and useful.

**Comment by evilaliv3** [comment]
Thank you for this proposal @dmalacaria 

This was actually already specified in other ticket but we never implemented: https://github.com/globaleaks/GlobaLeaks/issues/1160

Closing this ticket as duplicate.
