### ISSUE TITLE
ubuntu14 apt-update  gnutls_handshake()  gnutls_handshake() 

### ISSUE THREAD

**Issue by useyangliu** [globaleaks/GlobaLeaks#3291]
/etc/apt/sources.list.d/globaleaks.list
deb https://deb.globaleaks.org buster/

`W: Failed to fetch https://deb.globaleaks.org/buster/Packages  gnutls_handshake() failed: Handshake failed`
`E: Some index files failed to download. They have been ignored, or old ones used instead.`

I created Ubuntu 14 to run install Give me an error when sh

By the way, which python version is the most suitable

**Comment by evilaliv3** [comment]
Hello, thank you for your question.

Ubuntu 14 is no longer supported.

If you are doing a new setup we recommend using Debian Bullseye (11) or Ubuntu Jammy (22.04).

The correct version of python will be automatically installed.

**Comment by useyangliu** [comment]
Thank you very much for your answer. I'll try Ubuntu 22
