### ISSUE TITLE
Hyperlinks on pages does not work anymore

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3297]
Hi!
We have various pages, were we have uploaded separeate WB policies and linked to the from the main page using HTML code. Suddenly we do not have acces to these files. When uploading files to the theme customization page, it seems, that a kind of UID has been added to the path of the files(which wasn't there in previous versions) - but the main issue is, that the links doesnt work at all.

The embedded code is just a typical HTML link like:

<a href="https://FQDN/1c4ff1d1-8c97-4db2-b87e-7fd46f1efd39/s/wb_policy.pdf" target="_blank">Click here</a>

The UID behind the FQDN is new to me

Are all links being disabled - or is this a bug?

**Comment by evilaliv3** [comment]
Hello @schris-dk 

Actually the link that you pasted is a link optained while operating on a tenant as root tenant admin and are valid only when fetching the file via the root tenant FQDN.

The uuid  identify the tenant when accessing via the root tenant FQDN.
If you are using the tenant FQDN, just remove the uuid and the link will work like a charm.

**Comment by schris-dk** [comment]
Hi Giovanni!

That is true – but our problem is currently, that the HTML tag for the link is not working – it is not clickable – it is like the linking is totally disabled


Fra: Giovanni Pellerano ***@***.***>
Sendt: 17. oktober 2022 16:04
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] Hyperlinks on pages does not work anymore (Issue #3297)


Hello @schris-dk<https://github.com/schris-dk>

Actually the link that you pasted is a link optained while operating on a tenant as root tenant admin and are valid only when fetching the file via the root tenant FQDN.

The uuid identify the tenant when accessing via the root tenant FQDN.
If you are using the tenant FQDN, just remove the uuid and the link will work like a charm.

**Comment by evilaliv3** [comment]
I see.

This is due to the fact that since the latest releases, following the latest penetration test reccomendations, we removed the possibility to use HTML directly.

Replace your HTML code with Markdown.

For example replace your links with ```[title](url)```
