### ISSUE TITLE
URL forwarding

### ISSUE THREAD

**Issue by cdlh** [globaleaks/GlobaLeaks#3298]
Hi,
i have the following situation:
A clients wants to use globaleaks for his company (and subsidiaries). Target is to have a (external hosted) server for globaleaks. The client wants to use an subdomain-url like leak.companycorp.com to link to the external server (where globaleaks is installed). The URL-Forwarding works, but the URL is (of course) resolved like "externalserver.hoster.com". That he doesn't want.
Is it possible to solve that situation, so that the URL "leak.companycorp.com" stays the same when redirected to the "externalserver.hoster.com"?
And of course the client wants to use the "Sites Management" to apply different sub-sites for the subsidiaries. They should be accessible via (i.e.) "leak.companycorp.com/t/....".
Can someone please advise?

**Comment by evilaliv3** [comment]
Hello!

Thank you for your question.

If i understand it well, what you want is fully supported but you do not
need to use the url forward feature and you do not need to use the
subdomain feature. These are options used in other situations.

In your case:
- create a tenant for your client
- ask your client to choose a domain for the project and to point it to
your server with a DNS configuration of type CNAME or A
- configure the domain name and the certificate in the tenant dedicated to
your client
- configure a full hostname for your client
- ask toue cli

**Comment by cdlh** [comment]
Hello and thanks a lot @evilaliv3! With your hints I succeeded.

For people with the same questions I'll post my conclusion:

Say we have the following (fictional) configuration:
leak.companycorp.com: Subdomain on Clients server, where i can change DNS-Settings
22.33.44.55: IP of the (working) Globaleaks server
server100.webhoster.com: URL of the (working) Globaleaks server

First step: change DNS-Settings of leak.companycorp.com, so that a CNAME-Record points to "server100.webhoster.com."
- OR -
Change the A-record to point on 22.33.44.55.

Second step: go to your Globaleaks-Server (in this case i. e. Server100.webhoster.com), log in as admin, go to network-settings and enter leak.companycorp.com as the Hostname. Save and you are done.

After a short period of time your globaleaks-Server should be reachable via leak.companycorp.com.

Next step is to use the globaleaks-tools to get the corresponding certificates.

Again: Thanks a lot @evilaliv3

**Comment by evilaliv3** [comment]
Thank you for this feedback @cdlh !
