### ISSUE TITLE
Image type JPG in logos

### ISSUE THREAD

**Issue by evariitta** [globaleaks/GlobaLeaks#3301]
Hi! I cannot upload a logo in JPG to a tenant. Should they work as a logo type?

Software version used is 4.10.14. 

**Steps to reproduce the behavior:**
1. Go to 'main configuration' at a tenant site
2. Click on edit in the logo field and upload an image in jpg type
3. See that the image doesn't function and doesn't appear at the site

![2022-10-24 jpg-logo](https://user-images.githubusercontent.com/103591617/197474471-1cf2a5b7-bcf1-4c8f-b9d8-97b2a78c1011.png)

**Desktop:**
 - OS: Microsoft
 - Microsoft Edge

**Comment by evilaliv3** [comment]
Thank you @evariitta for reporting this. Actually Jpeg files should work.

We will recheck an let you know if there is a regression.

In the meantime you should be able to upload a PNG file

**Comment by evariitta** [comment]
Thank you! Yes, PNG files work well.
