### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by goferit** [globaleaks/GlobaLeaks#3302]
502 bad gateway error, cannot visit site, Slack channel, community forum etc.

**Comment by evilaliv3** [comment]
Dear  @goferit 

Thank you for your question. 

We are actually setupping a corporative proxy and we still miss to configure it completely.

If you need to access slack you may access it via globaleaks.slack.com

**Comment by matteozoni** [comment]
I updated the site while you were down. Now my site is no longer reachable too. Can this be connected?

**Comment by evilaliv3** [comment]
Yes, will be solved shorty. We are sorry for the inconvenience

**Comment by evilaliv3** [comment]
No actually, this has nothing to do with your site actually.
If you want pass me one link and i will check it.

**Comment by matteozoni** [comment]
Thanks, I am writing to you in private.
