### ISSUE TITLE
Grant access to multiple reports

### ISSUE THREAD

**Issue by evariitta** [globaleaks/GlobaLeaks#3303]
Hello!
When I am logged in as a recipient and try to grant access to a report or multiple reports in "Reports" page, an error occures. It says "Error on input validation [Invalid command]".

**To Reproduce**
1. Go to 'reports' page at a tenant.
2. Select some report(s). Click 'grant access'.
3. See error

This function works well though when I am inside a report. The error occures only at the page of all reports.

**Screenshots**
![2022-10-26 13_52_00-Päivitys 4 10 14 - Kopio - Word](https://user-images.githubusercontent.com/103591617/198008887-69defa86-1d84-4e38-8395-c202e169f2f6.png)

**Desktop:**
 - OS: Microsoft
 - Browser: Microsoft Edge

**Comment by evariitta** [comment]
The software version used is 4.10.14.

**Comment by evilaliv3** [comment]
Thank you  @evariitta, this is a known issue of the current release and will be fixed shortly

**Comment by evilaliv3** [comment]
Closing this ticket as the new release 4.10.15 fixed this bug.
