### ISSUE TITLE
Error when uploading PEM file for https configuration

### ISSUE THREAD

**Issue by Elliot-12345** [globaleaks/GlobaLeaks#3305]
I have just finished installing the globaleaks internal site and need to configure https. I am trying to do this from the network settings area of the admin portal, but when uploading a PEM file to ‘Certificate (PEM)’, the error “Error on input validation []” is shown.

For context, the SSL certificate is currently stored in Azure in a pfx format. This is then converted into the required pem format using openssl.

Any suggestions on how to resolve this would be appreciated.

**Comment by evilaliv3** [comment]
@Elliot-12345: Would you please check if the file that you are trying to upload if encrypted with a password?

If yes you could remove the password by using openssl and then you should bne able to load the file correctly

**Comment by Elliot-12345** [comment]
Hi @evilaliv3, there is no encryption on the file, do you have any further suggestions?

**Comment by evilaliv3** [comment]
I'm sorry about the encryption i was referring to the key not to the certificate.

The certificate could be discarded because: 1) non corresponding to the loaded key 2) the key is encrypted and not usable by globaleaks 3) the file is not in the PEM format.

If you want get back to me at support@globaleaks.org and i will send an invite to our slack so that we could check on your issue directly.

**Comment by Elliot-12345** [comment]
Hi @evilaliv3, thanks for your response. We are considering an alternative route as per the article here https://www.ssldragon.com/blog/how-to-install-an-ssl-certificate-on-ubuntu. The setup specified relies on apache, does Globaleaks utilise apache for its back end web service and can this method be used? If not, what technologies are used and is there a way of applying the certificate that you can recommend (besides via the admin portal).

**Comment by Elliot-12345** [comment]
Hi @evilaliv3 are you able to advise?

**Comment by evilaliv3** [comment]
Hello @Elliot-12345 

I invite you to retry the full procedure of using the automated letsencrypt certificates that is the more simple option if you are not familiar with certificates.

When using GlobaLeaks we advise to NEVER use any proxy (e.g. apache) as this would impact  the security of the system.

**Comment by Elliot-12345** [comment]
Hi @evilaliv3,

Thank you, unfortunately when using the automated method, a loading icon is shown continuously and nothing happens, see below:

![image](https://user-images.githubusercontent.com/117072864/199707185-011dc9ad-fb5d-4a8d-b5b9-c5cec83d6603.png)

We have a DNS entry set up for the hostname, so I assume this will be happening due to the restrictions on our VM firewall preventing communication with the lets encrypt authority. Are you able to advise what specific IP range needs to be allowed through to facilitate this communication?

**Comment by Elliot-12345** [comment]
@evilaliv3 As a quick update on this, we have now managed to complete the certificate setup using the automated method, it looks as though the hostname specified in the network settings page was incorrect.

The issue we are now experiencing is that the admin portal and the front-end website are inaccessible after applying the automatic configuration, a 'ERR_CONNECTION_TIMED_OUT' error is shown.

Our DNS settings appear correct, so wondered if there was anything you can suggest to resolve this

**Comment by evilaliv3** [comment]
Thank you Elliot but unfortunately with my limited visibility with the configuration i cannot advise any further.

In any case if lets encrypt succeeded with the creation of the certificate i confirm that the DNS configuration is correct.

I would acces via Tor or locally as an admin to debug the situation.

**Comment by Elliot-12345** [comment]
@evilaliv3 Thanks, we were able to resolve this ultimately and the site is now up and running. The final step for us is to set up redirection from specific URL's to the live site address. I can see there is a mechanism for this under URL redirects, though having tried setting redirect from xyz.domain1.com --> livesite.domain2.com it doesnt seem to be working, is there anything specific that needs to be in place to get this working beyond a DNS entry for that domain? I cannot find any documentation on this.

**Comment by evilaliv3** [comment]
Thank you @Elliot-12345 

Actually this is not the proper channel where make this questions.Please use this ticket system

**Comment by evilaliv3** [comment]
Thank you @Elliot-12345

Actually this is not the proper channel where make this questions.
I kindly ask you if you could use this ticketing system, creating specific tickets about bugs or feature requests and always try to provide detail that would help assisting you.

The tickets should be dedicated to a specific topic and include details able for the community to support you.

I will close this ticket as it is now container for a large set of different discussions.

Please feel free to reach out to us on support@globaleaks.org if you would like an invite to our slack channel.
