### ISSUE TITLE
Error on buster certificate

### ISSUE THREAD

**Issue by faffa42** [globaleaks/GlobaLeaks#3306]
When updating a kinda old installation I get 
Err:1 deb.globaleaks,org buster/ globaleaks 4.7.5 Certificate verification failed: The Certificate is NOT trusted

**Comment by evilaliv3** [comment]
Hey @faffa42 

Actually i do not think this is related to globaleaks but maybe to something on your specific setup.

What i would do it to run the following three commands that would force your system to fetch the repository keys again and update your globaleaks setup:
```
wget https://deb.globaleaks.org/install-globaleaks.sh
chmod +x install-globaleaks.sh
./install-globaleaks.sh
```

**Comment by faffa42** [comment]
Hi @evilaliv3 ! 
The os might be out of date but running the wget you put above I get: 
```
ERROR: The certificate of 'deb.globaleaks.org' is not trusted
ERROR: The certificate of 'deb.globaleaks.org' ha expired
```
Any idea?

**Comment by evilaliv3** [comment]
Actually the certificate that we use is up to date, i suspect the time of the system may be incorrect or that you may have an out to date system.

**Comment by evilaliv3** [comment]
Closing as probably unrelated to globaleaks itself.

Please feel free to re-open the ticket if you manage to find the reason and you consider it would be helpful for other users. Thank you.
