### ISSUE TITLE
Regression on multimedia content visualization due to restricted Content Security Policy

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3307]
**Describe the bug**
Video multimedia content not playing. Images don't seem to have an issue. Have not tried audio.

globaleaks v4.14

**Comment by evilaliv3** [comment]
@elbill: Thank you, would you please describe something more?

Where and how did you load multimedia/audio?

**Comment by elbill** [comment]
Sure yes. 
Multimedia content within a question.
![Uploading test - Questionnaires - Google Chrome 03_11_2022 17_48_10.png…]()

**Comment by elbill** [comment]
![test - Questionnaires - Google Chrome 03_11_2022 17_48_10](https://user-images.githubusercontent.com/23246886/199769112-a5373f64-14c2-4db3-b864-b6e79877db66.png)

**Comment by elbill** [comment]
![test - Google Chrome 03_11_2022 17_52_01](https://user-images.githubusercontent.com/23246886/199769574-701e6367-3d00-4a17-bb70-24d45ab3c60c.png)

**Comment by evilaliv3** [comment]
Thank you.

Would you pleas tell me if you see any exception in the javascript console? 

I suspect the Content Security Policy could be too strict. It was changed during the security audit but maby we should change something in relation to enable this use.

**Comment by elbill** [comment]
Uncaught ReferenceError: GLClient is not defined
    at script:2:1
scripts.min.js:8 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'sha256-fwyo2zCGlh85NfN4rQUlpLM7MB5cry/1AEDA/G9mQJ8='". Either the 'unsafe-inline' keyword, a hash ('sha256-uD+9kGdg1SXQagzGsu2+gAKYXqLRT/E07bh4OhgXN8Y='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

ut @ scripts.min.js:8
scripts.min.js:8 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'sha256-fwyo2zCGlh85NfN4rQUlpLM7MB5cry/1AEDA/G9mQJ8='". Either the 'unsafe-inline' keyword, a hash ('sha256-4IfJmohiqxpxzt6KnJiLmxBD72c3jkRoQ+8K5HT5K8o='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

ut @ scripts.min.js:8
scripts.min.js:8 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'sha256-fwyo2zCGlh85NfN4rQUlpLM7MB5cry/1AEDA/G9mQJ8='". Either the 'unsafe-inline' keyword, a hash ('sha256-uD+9kGdg1SXQagzGsu2+gAKYXqLRT/E07bh4OhgXN8Y='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

ut @ scripts.min.js:8
scripts.min.js:8 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'sha256-fwyo2zCGlh85NfN4rQUlpLM7MB5cry/1AEDA/G9mQJ8='". Either the 'unsafe-inline' keyword, a hash ('sha256-4IfJmohiqxpxzt6KnJiLmxBD72c3jkRoQ+8K5HT5K8o='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

ut @ scripts.min.js:8
scripts.min.js:8 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'sha256-fwyo2zCGlh85NfN4rQUlpLM7MB5cry/1AEDA/G9mQJ8='". Either the 'unsafe-inline' keyword, a hash ('sha256-uD+9kGdg1SXQagzGsu2+gAKYXqLRT/E07bh4OhgXN8Y='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

ut @ scripts.min.js:8
scripts.min.js:8 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 'sha256-fwyo2zCGlh85NfN4rQUlpLM7MB5cry/1AEDA/G9mQJ8='". Either the 'unsafe-inline' keyword, a hash ('sha256-4IfJmohiqxpxzt6KnJiLmxBD72c3jkRoQ+8K5HT5K8o='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.

ut @ scripts.min.js:8
/#/:1 Refused to load media from 'https://epathla.fraudline.gr/s/epathla-small.mp4' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'media-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by evilaliv3** [comment]
Perfect thank you, we will fix this in the next release

**Comment by elbill** [comment]
Sound doesn't work either...

**Comment by elbill** [comment]
Sound doesn't work either...

**Comment by evilaliv3** [comment]
Fixed and the correction will be included in next minor release.

**Comment by elbill** [comment]
@evilaliv3 Are you sure this has been fixed? I still cant see the multimedia content.

**Comment by evilaliv3** [comment]
@elbill: would you please retry and check the error that you get inside the javascript console?

**Comment by elbill** [comment]
Can you please check
https://epathla.fraudline.gr/#/

**Comment by evilaliv3** [comment]
I think for some reason you could be still running a previous version
