### ISSUE TITLE
Globaleaks installed but not accessible on the network.

### ISSUE THREAD

**Issue by mr-no-body0** [globaleaks/GlobaLeaks#3314]
Successfully installed globaleaks and working on localhost. But it is not accessible to other machines. Even I changed the default Apache port which was 80..also is there any way to change the running Port for the globaleaks.

**Comment by evilaliv3** [comment]
Thank you @mr-no-body0 

GlobaLeaks in its current release requires to use port 80, 443 8082 and 8083 and this is unfortunately not configurable.

Port 80 and 443 are open for connection from any host
The other ports are only accessible on local host.

I suggest you to check it is correctly binded on these ports via the command ```netstat -nat```

**Comment by mr-no-body0** [comment]
When i check it with machine's ip address it is showing the default Apache page.... So that I changed the default Apache port 60 . now Apache page is found on port number 60 and nothing on 80

**Comment by evilaliv3** [comment]
Get sure to restart globaleaks now.

You can do it with : ```/etc/init.d/globaleaks restart```

**Comment by mr-no-body0** [comment]
Thanks for your seamless response and the issue is fixed after restarting globaleaks.
