### ISSUE TITLE
error in job.py

### ISSUE THREAD

**Issue by omardimarzio** [globaleaks/GlobaLeaks#3317]
Good morning.
For a few days now, the system that deals with timed operations has been sending out alerts almost daily.

____________________________________________
twisted.web._newclient.ResponseNeverReceived
    A L{ResponseFailed} that knows no response bytes at all have been received.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/globaleaks/jobs/job.py", line 49, in run
    yield self.operation()

twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
____________________________________________

what is "Connection to the other side"? 
Is it a bug? What can I do about it?

**Comment by evilaliv3** [comment]
Hello @omardimarzio 

I think that those exception were related to a downtime on our repository when your system tried to check for an update.

you can safely ignore this exception.

**Comment by agrr** [comment]
I have a problem similar to this:
when starting Globaleaks (v 4.10.14) I get spammed with a lot of emails with the following error message:

```
twisted.web._newclient.ResponseNeverReceived
    A L{ResponseFailed} that knows no response bytes at all have been received.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/globaleaks/jobs/job.py", line 49, in run
    yield self.operation()

twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure twisted.internet.error.ConnectionLost: Connection to the other side was lost in a non-clean fashion: Connection lost.>]
```

I disabled the e-mails by setting the smtp_server to localhost but this obviously breaks the useful e-mails that the platform may need to send to my recipients...

Is it the update check that's failing on startup?

**Comment by evilaliv3** [comment]
Thank you for your feedback @agrr 

Which is the period of the email that you are receiving?
If it is hourly probably this is related to the hourlty checks to verify if a new globaleaks release is available.
Maybe you firewall is blocking connections to deb.globaleaks.org?

**Comment by agrr** [comment]
I was receiving a lot of e-mails within minutes of starting up GlobalLeaks. It doesn't seem consistent with an hourly check.
And no, I don't have firewall rules to block outgoing connections.

**Comment by evilaliv3** [comment]
Are you still encountering this issue @agrr ?
