### ISSUE TITLE
Grant access to reports results in error when performed from report list

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3318]
**Describe the bug**
Grant access to reports results in error when performed from report list
error on input validation (invalisd command)
No problem when performed within individual reports

**To Reproduce**
goto reports list
check one or multiple boxes
click grant access to
select recipent
error occurs

**Expected behavior**
would expect o be able to grant access from report list 

**Additional context**
Software version: 4.10.14 on ubuntu 20.04

**Comment by evilaliv3** [comment]
Thank you @elbill , this is a known issue that will be fixed shortly with release 4.10.15

It was already reported here: https://github.com/globaleaks/GlobaLeaks/issues/3303
