### ISSUE TITLE
error:  translation to pt_PT 

### ISSUE THREAD

**Issue by zeadriano** [globaleaks/GlobaLeaks#3321]
Hello
[
![seção](https://user-images.githubusercontent.com/121095106/208651480-38bd6008-6c71-4e48-a574-2c3d6fe619de.png)
](url)

The word "**seção**" in the next sentence It is written in Brazilian Portuguese. In Portuguese from Portugal it is "**secção**"

msgstr "Recomendamos que aceda à seção “Preferências” para copiar a sua “Chave de recuperação de conta” e armazená-la em segurança. Esta chave será necessária para recuperar seu acesso à plataforma e aos seus dados caso se esqueça da sua palavra-passe."

This translation can be found on line 1380 of the pt_PT.pt file

**Comment by evilaliv3** [comment]
Thank you for reporting this.

We updated the translation on our localization platform: https://www.transifex.com/otf/globaleaks/

The correction will be added to the next stable release.

Please feel free to let us know if you notice other errors or if you could like to contribute directly to the revision of the full translations. In this case you could write us at: support@globaleaks.org
