### ISSUE TITLE
Strato V-Server, Apparmor etc.

### ISSUE THREAD

**Issue by cdlh** [globaleaks/GlobaLeaks#3326]
For a while now i'm trying to run Globaleaks on a hosted V-Server by German Hoster "Strato", OS is Ubuntu 20.04 LTS 64bit.
Problem: it's not possible to start globaleaks via systemctl.
For me it looks like Strato is not supporting apparmor, so i disabled it like evilaliv3 explained in issue #3267 
But still, i receive the following error-messages:

root@xyz-server:~# systemctl start globaleaks
Job for globaleaks.service failed because the control process exited with error code.
See "systemctl status globaleaks.service" and "journalctl -xe" for details.
root@xyz-server:~# systemctl status globaleaks
● globaleaks.service - LSB: Start the GlobaLeaks server.
     Loaded: loaded (/etc/init.d/globaleaks; generated)
     Active: failed (Result: exit-code) since Tue 2023-01-10 11:51:49 CET; 12s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 457 ExecStart=/etc/init.d/globaleaks start (code=exited, status=1/FAILURE)

Jan 10 11:51:49 xyz-server.stratoserver.net systemd[1]: Failed to start LSB: Start the GlobaLeaks server..
Dez 23 17:21:30 xyz-server.stratoserver.net globaleaks[655]:  * Starting GlobaLeaks daemon globaleaks
Dez 23 17:21:30 xyz-server.stratoserver.net globaleaks[655]:  * Starting ...
Dez 23 17:21:30 xyz-server.stratoserver.net globaleaks[655]:  * Enabling Globaleaks Network Sandboxing...
Dez 23 17:21:30 xyz-server.stratoserver.net globaleaks[655]:    ...done.
Dez 23 17:21:30 xyz-server.stratoserver.net globaleaks[655]:  * GlobaLeaks Apparmor Sandboxing Failure: requires apparmor
Dez 23 17:21:11 xyz-server.stratoserver.net systemd[1]: Starting LSB: Start the GlobaLeaks server....
Dez 23 17:21:26 xyz-server.stratoserver.net systemd[1]: globaleaks.service: Control process exited, code=exited, status=1/FAILURE
Dez 23 17:21:26 xyz-server.stratoserver.net systemd[1]: globaleaks.service: Failed with result 'exit-code'.
Dez 23 17:21:26 xyz-server.stratoserver.net systemd[1]: Failed to start LSB: Start the GlobaLeaks server..
root@xyz-server:~# globaleaks
WARNING: The current long term supported platform is Debian 11 (bullseye)
WARNING: It is recommended to use only this platform to ensure stability and security
WARNING: To upgrade your system consult: https://docs.globaleaks.org/en/main/user/admin/UpgradeGuide.html

At the end i run globaleaks direct - working.
What can i do to run globaleaks as intended?

**Comment by evilaliv3** [comment]
Thank you for reporting this @cdlh 

Actually settings APPARMOR_SANDBOXING=0 in /etc/default/globaleaks should work as intended and disable apparmor.

Would you please check if by mistake you could have added a typo in the configuration or in the filename? 

thank you

**Comment by cdlh** [comment]
Hi,
i attached a screenshot, in my opinion it is correct.
But, i also deactivated Network Sandboxing, and this setting is not applied neither, correct ?

![globaleaks_apparmor](https://user-images.githubusercontent.com/56454546/211545107-65e1337e-da8b-4dd2-b2d7-4d82aa999c10.png)

**Comment by evilaliv3** [comment]
Yes the file configuration is correct.

Would you please check if the filename is correct as well ? 

Should be "/etc/default/globaleaks"

**Comment by cdlh** [comment]
I'm afraid, but i think it's exactly the filename (see also in title-bar of the screenshot in my previous posting).

During searching i found another topic concerning Strato. There was the python-version used a problem.  Could that be the problem? 

"python --version" returns Python 2.7.18

**Comment by cdlh** [comment]
Thank you @evilaliv3 ,
I think of leaving that problem alone and switch to a server with Debian GNU/Linux 10 (buster). 

Is it possible to backup the globaleaks installation (including all subsites) from ubuntu and restore the data on a debian distribution? Or should i open a new issue for that question?

**Comment by evilaliv3** [comment]
Yes It is possible.

The procedure for migrating to a new version of a distribution or to a
different distribution is documented here:
https://docs.globaleaks.org/en/main/user/admin/UpgradeGuide.html#upgrade-of-the-distribution-version

**Comment by cdlh** [comment]
Okay. Installed a new server (different IP), copied /var/globaleaks on the new server and started installation. Installation failed:
● globaleaks.service - LSB: Start the GlobaLeaks server.
   Loaded: loaded (/etc/init.d/globaleaks; generated)
   Active: failed (Result: exit-code) since Wed 2023-01-11 12:05:23 CET; 8min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 5519 ExecStart=/etc/init.d/globaleaks start (code=exited, status=1/FAILURE)

Jan 11 12:05:22 serverxyz.stratoserver.net systemd[1]: Starting LSB: Start the GlobaLeaks server....
Jan 11 12:05:23 serverxyz.stratoserver.net globaleaks[5519]: Starting GlobaLeaks daemon: globaleaksStarting ...Enabling Globaleaks Network Sandboxing...done.
Jan 11 12:05:23 serverxyz.stratoserver.net globaleaks[5519]: mkdir: das Verzeichnis „/dev/shm/globaleaks“ kann nicht angelegt werden: Die Datei existiert bereits
Jan 11 12:05:23 serverxyz.stratoserver.net globaleaks[5519]: GlobaLeaks Apparmor Sandboxing Failure: requires apparmor ... failed!
Jan 11 12:05:23 serverxyz.stratoserver.net systemd[1]: globaleaks.service: Control process exited, code=exited, status=1/FAILURE
Jan 11 12:05:23 serverxyz.stratoserver.net systemd[1]: globaleaks.service: Failed with result 'exit-code'.
Jan 11 12:05:23 serverxyz.stratoserver.net systemd[1]: Failed to start LSB: Start the GlobaLeaks server..

I edited the /etc/default/globaleaks file and then tried to start the service again:

● globaleaks.service - LSB: Start the GlobaLeaks server.
   Loaded: loaded (/etc/init.d/globaleaks; generated)
   Active: failed (Result: exit-code) since Wed 2023-01-11 12:13:57 CET; 5min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 5876 ExecStart=/etc/init.d/globaleaks start (code=exited, status=1/FAILURE)

Jan 11 12:13:55 serverxyz.stratoserver.net systemd[1]: Starting LSB: Start the GlobaLeaks server....
Jan 11 12:13:56 serverxyz.stratoserver.net globaleaks[5876]: Starting GlobaLeaks daemon: globaleaksStarting ...mkdir: das Verzeichnis „/dev/shm/globaleaks“ kann nicht angelegt werden: Die Datei existiert bereits
Jan 11 12:13:57 serverxyz.stratoserver.net globaleaks[5876]: WARNING: The current long term supported platform is Debian 11 (bullseye)
Jan 11 12:13:57 serverxyz.stratoserver.net globaleaks[5876]: WARNING: It is recommended to use only this platform to ensure stability and security
Jan 11 12:13:57 serverxyz.stratoserver.net globaleaks[5876]: WARNING: To upgrade your system consult: https://docs.globaleaks.org/en/main/user/admin/UpgradeGuide.html
Jan 11 12:13:57 serverxyz.stratoserver.net globaleaks[5876]: Unable to start GlobaLeaks: [Errno 13] Permission denied: '/var/globaleaks/globaleaks.pid'
Jan 11 12:13:57 serverxyz.stratoserver.net globaleaks[5876]: failed.
Jan 11 12:13:57 serverxyz.stratoserver.net systemd[1]: globaleaks.service: Control process exited, code=exited, status=1/FAILURE
Jan 11 12:13:57 serverxyz.stratoserver.net systemd[1]: globaleaks.service: Failed with result 'exit-code'.
Jan 11 12:13:57 serverxyz.stratoserver.net systemd[1]: Failed to start LSB: Start the GlobaLeaks server..

Since i just tansferred the /var/globaleaks directory via sftp, what permissions do i have to set? Or is something else wrong?

**Comment by evilaliv3** [comment]
the directory /var/globaleaks  should be assigned to user globaleaks and the group globaleaks.

**Comment by cdlh** [comment]
Thank you, @evilaliv3 

With
chown -R globaleaks:globaleaks /var/globaleaks
i changed the ownership and then it works.

It works that good that all certificates and URLs are working, so that (i. e.) oldserver.test-cdlh.de is opened when i enter the ip. Is there any chance to edit the url via ssh, so i'm not redirected when entering the ip?

**Comment by evilaliv3** [comment]
these aspects are configurable only via the web console.

if fine for you i will close this ticket as addressed.

for eventual discussions please join our community space at community.globaleaks.org

**Comment by cdlh** [comment]
Yes, that's okay. Thanks again for your help!
