### ISSUE TITLE
Allow www and non-www with a TLS-certificate

### ISSUE THREAD

**Issue by NoahBohme** [globaleaks/GlobaLeaks#3330]
Allow users to create both www and non-www domains with a Let's Encrypt certificate to avoid any users entering without TLS.

**Comment by evilaliv3** [comment]
Thank you for your suggestion.

If possible please always consider to include more detail to discuss your
proposal and highlight your analysis of the possible implementation.

This way the community could discuss it and there are more chances that
some developers would find interesting to implement it.

I do not find this ticket particularly important but I consider even if I
recognize it could be valuable to reduce mistakes by non expert internet
users.

I consider we could implement the possibility to define a primary domain
and some aliases and implement s 301 from the alias to the primary domain.

As well we could improve the letsencrypt feature to require certificates
for all the configuted domains.

**Comment by evilaliv3** [comment]
Closing this ticket as it is actually a duplicate for https://github.com/globaleaks/GlobaLeaks/issues/3132
