### ISSUE TITLE
Email notifications not sent.

### ISSUE THREAD

**Issue by chiara-giorgieri** [globaleaks/GlobaLeaks#3331]
**Describe the bug**
When creating a new submission (or when a whistleblower adds a comment), assigned recipient doesn't receive the mail notification. 
Nothing is added to the log file, even with "Livello di verbosità dei log: DEBUG". 

The new submission is ok and the recipient find it in his web page. The only missing bit is the email. 

**To Reproduce**
Not sure how you can reproduce my misbehavior: I just
1. Create a new submission on the site (or add a comment to an existing submission) 

**Expected behavior**
1. Create a new submission on the site (or add a comment)
2. Receive an email notification to the mail address configured for the recipient

**Server:**
 - OS: Ubuntu 22.04
 - Globaleaks Version: 4.10.14

**Desktop:**
 - Browser: firefox 106.0.2 (64-bit), chrome 108.0.5359.124

**Additional context**
Users and questionnaire come from an old install, by copying /var/globaleaks. But the problem exists also with a recipient created in the new server. 

I unchecked all the "Disabilita le notifiche ai riceventi" and checked all the "Abilita le notifiche via email" I found in site/users settings. But perhaps there is something I missed... 

Notification test is ok (if I use default configuration, with globaleaks server) and in globaleaks logs I find
2023-01-23 11:08:52+0000 [-] [D] [1] Sending email to my.mail@my.site using SMTP server [mail.globaleaks.org:587] [TLS]
2023-01-23 11:08:52+0000 [-] Starting factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7f1103887370>
2023-01-23 11:08:52+0000 [-] Stopping factory <twisted.mail.smtp.ESMTPSenderFactory object at 0x7f1103887370>

**Comment by evilaliv3** [comment]
Thank you for your feedback @chiara-giorgieri 

During this morning we had a small outage due to a reconfiguration of the dns for maintenance.
All should be already fully working by now.

Would you please retry?

**Comment by chiara-giorgieri** [comment]
No, unfortunately I still don't receive the notification and nothing was added to /var/globaleaks/log/globaleaks.log . 
I submitted at 23-01-2023 12:38 from ip 193.205.247.136. 
What else can I check?

**Comment by evilaliv3** [comment]
Thank you @chiara-giorgieri .
I just veriefied and it seems that the antispam filter at inaf.it is rejectiong our emails.

I woud suggest to contact your mailserver administrators to check the reason. They seems to reject our server as sender.

**Comment by chiara-giorgieri** [comment]
But the mailserver on our side (no more "our mailserver", now it's google...) accept the mail test generated by our whistleblowing site, which should have the same path. 
Does the notification use the same Sender and IP than the test message? 
I'm one of the administrators for our domain and, in google maillogs, I can't find any attempt from notifications@globaleaks or from that ip, except for the test mails. And nothing with "Nuova segnalazione" in the subject. 
Are there problems with google?
Can you give me the error message you find in your log?

**Comment by evilaliv3** [comment]
Thank you @chiara-giorgieri 

No there are no problems with Google and i confirm that the email sent using our servers follows always the same path.

Here are logs that i find in relation to your server:
```
mail.info.1:Jan 20 11:07:17 mail postfix/smtpd[798908]: NOQUEUE: reject: RCPT from unknown[193.205.247.136]: 554 5.7.1 <chiara.giorgieri@inaf.it>: Sender address rejected: Access denied; from=<chiara.giorgieri@inaf.it> to=<chiara.giorgieri@inaf.it> proto=ESMTP helo=<whistleblowing>```

**Comment by chiara-giorgieri** [comment]
Yes, last week I tried many strange configurations... ;-)
But today I'm using the defaults in configurazione delle notifiche, so the sender should be notifications@globaleaks.org. Google rejected a sender with our domain coming from an unknown ip; a sender in @globaleaks.org is ok. 
(b.t.w., could you please Edit your post to redact the real email? Chopping the first letters should be enough to protect me from harvesters)
What do today logs say?

**Comment by evilaliv3** [comment]
Sure


The messoge for today is actually the same: NOQUEUE: reject: RCPT from unknown[193.205.247.136]: 554 5.7.1

**Comment by chiara-giorgieri** [comment]
That's very strange. The email my.mail@my.site is configured for the admin user, but changing admin's mail to n...@globaleaks.org doesn't help. 
In "Configurazione delle notifiche" today I have n...@globaleaks.org... 
So where do I configure the sender for the notifications?

**Comment by evilaliv3** [comment]
Thank you @chiara-giorgieri 

I suggest you reset the current configuration to the default and then you test if it works.

Customizing the sender is not possible when using our mail server.
Our mail server in fact apply some security check to prevent spam abuses.

**Comment by chiara-giorgieri** [comment]
I don't customize the sender (I did last week, understood it was a bad idea and stopped), I was just wondering why the maillog shows my personal email instead of notifications@globaleaks.org.

I reset the configuration: as you can see in the snapshot, the sender is notifications@globaleaks.org.
![230124at103006Configurazione delle notifiche](https://user-images.githubusercontent.com/49518501/214261014-bd1d37dc-7749-4dd2-906a-94ef7cfd9752.png)

I created a new submission at 10:41, but did't receive the notification. 
What check could I do to understand what is happening?

**Comment by evilaliv3** [comment]
Hello @chiara-giorgieri 

I'm sorry i missed the last question.

Are you still encountering issues?

Is it possible that inside the notifications settings you could have enabled the feature to anonymize outgoing connections?
When this setting the smtp connection is made via Tor and maybe this is preventing the delivery.

**Comment by chiara-giorgieri** [comment]
Ok, problem solved! 
This morning I still had the issue with globaleaks 4.10.14, but an update to the last version unlocked all 37 missing notifications. 
I don't know what the problem was, but Globaleaks 4.10.17 is sending notifications correctly. 

(no, I never enabled the feature to anonymize outgoing connections)

Thank you for solving the issue.

**Comment by evilaliv3** [comment]
Thank you for your feedback @chiara-giorgieri
