### ISSUE TITLE
Infinite forced password change

### ISSUE THREAD

**Issue by rusinov1** [globaleaks/GlobaLeaks#3334]
For https://acf.disclosers.eu/, whenever I try to login I am forced to change the password. When I do, it keeps asking me to change the password and I can never reach the dashboard with the reports. 

![image](https://user-images.githubusercontent.com/123728918/215051568-d940aa2f-3141-4848-82f6-6114ce6da841.png)

**Comment by evilaliv3** [comment]
Thank you for your feedback.

I've the doubt that this could be happening if you set the same old
password.

> Message ID: ***@***.***>
>

Would you please retry getting sure to type a completely different password?

**Comment by rusinov1** [comment]
Thank you! That worked!
________________________________
От: Giovanni Pellerano ***@***.***>
Изпратено: 27 януари 2023 г. 11:33
До: globaleaks/GlobaLeaks ***@***.***>
Як: Mario Rusinov ***@***.***>; Author ***@***.***>
Тема: Re: [globaleaks/GlobaLeaks] Infinite forced password change (Issue #3334)


Thank you for your feedback.

I've the doubt that this could be happening if you set the same old
password.

> Message ID: ***@***.***>
>

Would you please retry getting sure to type a completely different password?

**Comment by evilaliv3** [comment]
Thank you, i'm happy it worked.

I will close the ticket than, thank you for your feedback.
