### ISSUE TITLE
The page’s settings blocked the loading of a resource at inline (“script-src”)

### ISSUE THREAD

**Issue by pawelek-org** [globaleaks/GlobaLeaks#3340]
I have an issue after upgrading globaleaks from 4.10.14 to 4.10.15.

Now I can see only a blank web page. In Web Developer Tools --> console there's this message:

`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).`

Any ideas how to fix this?

**Comment by evilaliv3** [comment]
Thank you @pawelek-org 

We are aware of this issue in the latest release and we are going to fix it with a new release in the next hours.

**Comment by pawelek-org** [comment]
> We are aware of this issue in the latest release and we are going to fix it with a new release in the next hours.

Thank you @evilaliv3 for a quick reply!

**Comment by evilaliv3** [comment]
Fixed with release 4.10.16
