### ISSUE TITLE
Wizard cannot be completed

### ISSUE THREAD

**Issue by stefan-h3** [globaleaks/GlobaLeaks#3342]
When reinstalling, the wizard starts as usual. 
Unfortunately, it does not continue at step 5, the confirmation of the license. When pressing the "continue" button nothing happens and no error is displayed. We have tested it on different systems and with different browsers - unfortunately without any result. 
We tried to call the wizard via subdomain or IP address. Same result.
This is the output in the console: 

The Cross-Origin-Opener-Policy header has been ignored, because the URL's origin was untrustworthy. It was defined either in the final response or a redirect. Please deliver the response using the HTTPS protocol. You can also use the 'localhost' origin instead. See https://www.w3.org/TR/powerful-features/#potentially-trustworthy-origin and https://html.spec.whatwg.org/#the-cross-origin-opener-policy-header.

How can we complete the wizard?

**Comment by evilaliv3** [comment]
TThank you @stefan-h3 

Would you please provide the following information?
- version of the software
- address using for initiating the wizard

It would be then helpful if you cold attach a photo or a video of the procedure.

Thank you

**Comment by evilaliv3** [comment]
Fixed with commit: https://github.com/globaleaks/GlobaLeaks/commit/ebf21cc05674fbab9465608df1fc9120551fc83b
