### ISSUE TITLE
 Make it possible to visualize TXT files on the platform

### ISSUE THREAD

**Issue by pvigoseidor** [globaleaks/GlobaLeaks#3351]
As a recipient user I want to visualize the text files on GlobaLeaks without download the attachment.

It would be fantastic the possibility to view directly the attachment text files on platform.

Possible text files: TXT

**Comment by evilaliv3** [comment]
@pvigoseidor: i've reduced the scope of this ticket to support files of type TXT.

Eventually please open a specific ticket for DOCX and XLS.
I point out that supporting these two types is probably very difficult as they do not have native support in any browser yet. There are some libraries for this aim (WebODF and VISUALIZE.JS) but they don0t seems to be maintained at the moment.

**Comment by evilaliv3** [comment]
Closing as completed; the feature will be integrated in release 4.11.0
