### ISSUE TITLE
Error after loading a JS file

### ISSUE THREAD

**Issue by jpdionisio** [globaleaks/GlobaLeaks#3352]
Hello,

I have created a folder called "1" in _/var/globaleaks/scripts_ and I have uploaded the file _custom_script.js_ (example I have seen in the forum from _https://github.com/AjuntamentdeBarcelona/bustia-etica-bcn/tree/master/theme_ -changing GLClient by GL-).

I restart application with _service globaleaks restart_

But I dont see changes in home page and the console shows an error like this:

**Refused to execute script from 'http://127.0.0.1:8082/script' because its MIME type ('application/json') is not executable, and strict MIME type checking is enabled.**

I am using a Laptop with Debian 11 and the last version of Globaleaks (4.10.18).

Could you help me, please?

Thanks

**Comment by evilaliv3** [comment]
Thank you for the question.

The file should be called /var/GlobaLeaks/scripts/1

**Comment by jpdionisio** [comment]
What a mistake on my part! I didn't read it well. That's all OK now. It works! Thanks
