### ISSUE TITLE
ERR_SSL_VERSION_OR_CIPHER_MISMATCH

### ISSUE THREAD

**Issue by biometriars** [globaleaks/GlobaLeaks#3353]
Hey guys.

I'm new to the area.
I installed this excellent tool on an **Ubuntu Server 20.04 LTS linux server** following the steps in the documentation.

And the tool works perfectly, it's great.

I access it internally at **http://192.168.0.104**

I would like to access it here internally also through the HTTPS address, in this case **https**://192.168.0.104.

I saw that within the settings, there is the NETWORK menu, and within it the HTTPS option to create a certificate (private key, PEM certificate, etc.)

But I don't understand anything about.

I tried to click on the option where it does it automatically, but it didn't work, it gives the message **"ERR_SSL_VERSION_OR_CIPHER_MISMATCH"**

I then tried to use the manual option, generated the private key and got to the second option which is "Digital Certificate Signing Request (PEM)", but I'm very new to this part and I don't know what I'm doing wrong. The message still persists.

Could you please help me? I need it to work with HTTPS.

**Comment by evilaliv3** [comment]
Thank you for opening this question.

To use the automatic configuration you should first choose a domain and configure the DNS to be pointed to the public IP of the server.

Then you will be able to proceed with the automatic configuration.

**Comment by biometriars** [comment]
Perfect!

It worked perfectly!

After I published the site externally and made the DNS notes, I performed the HTTPS automatic configuration step again through the tool and it worked.

Thank you very much!
