### ISSUE TITLE
Remove possibility to close the Privacy Badget when clicked

### ISSUE THREAD

**Issue by pvigoseidor** [globaleaks/GlobaLeaks#3387]
### Proposal

currently clicking on the privacy badget forces hiding the bar and the download link for tor project is not clickable

### Motivation and context

Users that want to install Tor can't click to the download link.

**Comment by evilaliv3** [comment]
Thank you @pvigoseidor 

At the moment the widget is designed so that it can be closed and opened again.

Are you currently reporting a bug (as you are experiencing difficulties in re-opening the widget) or you are proposing to remove any user control on the widget?

**Comment by pvigoseidor** [comment]
Hi Giovanni,

I propose to leave it always opened.
The problem is that users can't click on the TorBrowser download link.

Thank you.

**Comment by evilaliv3** [comment]
Thank you, but actually they can click it again re-opening it and
downloading?

Have some users reported some problems with this behaviour? Thank you if
you could clarify the circumstances.

**Comment by pvigoseidor** [comment]
Yes, an user opened an issue about that.

At the moment when users click on the privacy badget, the bar closed and when they click again the bar opened, but users can't copy the text or click on the Tor link.

Thank you.

**Comment by evilaliv3** [comment]
Closing as implemented. It will be merged in release 4.11.0
