### ISSUE TITLE
Copy function of the report number

### ISSUE THREAD

**Issue by nicogithub22** [globaleaks/GlobaLeaks#3398]
### What version of GlobaLeaks are you using?

4.11.0 

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

When I have sent in a report. Then I click on the number to copy it to the cache, but that doesn't work. Also already in version 4.10.18.
There is an extra pop-up with click here to copy the code, that would be very practical.
Is there a special trick or do I have to activate it somewhere?
Thanks, 
Nico

**Comment by evilaliv3** [comment]
Thank you @nicogithub22 

I'm not sure if i get your question.
We have already a feature to copy the receipt number. Are you referring to that?
That feature works as long that the site is using HTTPS.

Eventually please feel free to load some screenshoots to explain what you suggest or what is not working
