### ISSUE TITLE
Make it possible to order the list of channels

### ISSUE THREAD

**Issue by pvigoseidor** [globaleaks/GlobaLeaks#3411]
### Proposal

As an administrator, I would like to be able to sort the listed channels in a particular order according to my preference (alphabetic, newer, older...)

### Motivation and context

Currently, there is no way to sort the listed channels. Adding the ability to manage and sort the channels would be a valuable improvement.

![Screenshot from 2023-03-29 12-07-06](https://user-images.githubusercontent.com/123653692/228501056-8c2c09e1-a325-4878-bba9-87982733c58b.png)

**Comment by evilaliv3** [comment]
Thank you @pvigoseidor  for your proposal.

Actually this feature is already available.
You should disable the option "Show contexts in alphabetical order" that you find in Settings/Advanced and you will have the possibility to reorder contexts up to you preference.
