### ISSUE TITLE
cannot change password of user: "Set up encryption by providing a PGP public key"

### ISSUE THREAD

**Issue by GerryCrooked** [globaleaks/GlobaLeaks#3415]
i have set up globaleaks via docker compose. when trying to change the password of an recipient and save this change, i get prompted to set up encryption, even tho it is disabled... and i can only save it AFTER i have setup PGP public key. 

![image](https://user-images.githubusercontent.com/19941398/230018919-e8bd86bc-543f-4674-9757-81ad080818cc.png)

deactivating and re-activating the option in advanced settings does not have any effect.

**Comment by evilaliv3** [comment]
Thank you for your feedback @GerryCrooked 

It seems yolu are running a veryu outdated version of globaleaks.

MAy i ask you if this setup is new or not?

**Comment by GerryCrooked** [comment]
its a new docker setup
im pulling it via:
version: "3"
services:
  globaleaks:
    image: ckeeney/globaleaks
    build: .
    cap_add:
      - NET_ADMIN
    ports:
      - 9080:80
      - 9543:443
    volumes:
      - /var/snap/docker/common/var-lib-docker/volumes/globaleaks:/var/globaleaks


god... i just saw, i used the first one on dockerhub... that is literally 5 years old... man... that was stupid... pulling now tsundokul/globaleaks

lets see how this works ;-)
