### ISSUE TITLE
Change of link in certain email templates

### ISSUE THREAD

**Issue by danielvaknine** [globaleaks/GlobaLeaks#3418]
### Proposal

In some email notifications, the link is only to the whistleblower side of the platform (when it could or should be a direct link to a report).

### **"Correct" link format (direct link)**
Here is an email notification with a direct link to the mentioned report:
<img width="972" alt="Screenshot 2023-04-12 at 20 43 27" src="https://user-images.githubusercontent.com/107921777/231540321-63d752f4-cee8-4083-b091-a6dc92fe951f.png">

### **Example 1 – Granted access**
Here is an email when a recipient has been granted access. As you can see, there is no direct link to the report but only to the whistleblower side of the platform. The recipient then needs to add /login themselves.
<img width="586" alt="Screenshot 2023-04-12 at 20 45 35" src="https://user-images.githubusercontent.com/107921777/231540854-c596410e-e9ce-47d7-b191-b1e6ad65f534.png">

### **Example 2 – reminder about unread report(s)**
<img width="493" alt="Screenshot 2023-04-12 at 20 46 35" src="https://user-images.githubusercontent.com/107921777/231541085-bcb73c04-0d13-4a54-9eaf-58d3af01da17.png">

There should be a direct link to the report in at least **Example 1**. Perhaps in **Example 2**, it should be a link to https://domain.com/#/login instead.

### Motivation and context

It can be confusing for recipients when some email links get them directly to the login page and some only to the whistleblower side (where they need to add /login in the link to get there themselves). When this happens, some recipients even try to log in through the whistleblower login (where they put the 16-digit code).

Email notifications should at least direct to https://domain.com/#/login , and preferably, when there is a certain report in question, a direct link to this report.

It could be a fairly simple fix with high ROI in terms of user friendliness!

**Comment by evilaliv3** [comment]
Thank you @danielvaknine for your suggestion.

Example 2 is already fixed in current release (4.11.4)

I'm going to fix Example 1 adding a link to the /login page. At the moment we could not load a direct link to the report because the email refer to one or more reports but we will evaluate how to improve this in the future.

**Comment by danielvaknine** [comment]
Great, thank you for your quick response!

**Comment by evilaliv3** [comment]
Closing the ticket as addressed.
