### ISSUE TITLE
Authentication error after upgrade to 4.11.4

### ISSUE THREAD

**Issue by kris877** [globaleaks/GlobaLeaks#3422]
### What version of GlobaLeaks are you using?

Hi All,
I'm currently using globeleaks version 4.11.1. After an upgrade to latest available version 4.11.4 I'm not able to authenticate /login to globaleaks.
Has anything changed in the login functionality? You must perform some additional administrative tasks before upgrading.
I did not find in the information about new versions that additional steps should be taken.
Problems occurs with or without 2FA on the account.
Application just displays "Error!" message and nothing more. Also there is no additionall information in log.

Regards
Kris

### What browser(s) are you seeing the problem on?

Firefox

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Hi All,
I'm currently using globeleaks version 4.11.1. After an upgrade to latest available version 4.11.5 I'm not able to authenticate /login to globaleaks.
Has anything changed in the login functionality? You must perform some additional administrative tasks before upgrading.
I did not find in the information about new versions that additional steps should be taken.
Problems occurs with or without 2FA on the account.
Application just displays "Error!" message and nothing more. Also there is no additionall information in log.

Regards
Kris

**Comment by evilaliv3** [comment]
Thank you for your question @kituser 

This is actually a know bug that is solved and will be released today.

There was a regression on the ip filtering function that is currently preventing any user to access when it is implemented.

The fix will be released by today emitting a release 4.11.5

**Comment by kris877** [comment]
Hi [evilaliv3]
thank you for quick response.
Yes I confirm that I'm using "Allowed IP addresses" feature.

Kris

**Comment by evilaliv3** [comment]
Release 4.11.5 fixed the issue.
