### ISSUE TITLE
Submitted reports report to print

### ISSUE THREAD

**Issue by kris877** [globaleaks/GlobaLeaks#3423]
### Proposal

Hi All, would it be possible to prepare report available to recipients to print summary  of submitted  reports ?
Also it will be an good idea to give the possibility to select channels and statuses to print summary report.

### Motivation and context

Such a report would be useful for the external auditors. During the inspection, they requested a summary of reported incidents.

**Comment by evilaliv3** [comment]
Thank you for your proposal @kris877 

Acutally this topic is already discussed in other tickets like https://github.com/globaleaks/GlobaLeaks/issues/1959

I'm closing as duplicate. Please feel free to contribute to the other existing tickets adding your suggestions.
