### ISSUE TITLE
Error upgrading to version 4.11.5

### ISSUE THREAD

**Issue by rmartinezgc** [globaleaks/GlobaLeaks#3425]
### What version of GlobaLeaks are you using?

4.11.4

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Hi everybody,

After upgrading to version 4.11.5, the application stopped working. I used the install-globaleaks.sh script, as you say in https://docs.globaleaks.org/en/main/user/admin/UpgradeGuide.html to fix it and it didn't work. I restored the backup made with your instructions and it didn't work either. Finally, I had to use the snapshot of my server that I had created before the upgrade to get the application working again in version 4.11.4.

Any idea why the update and backup restore didn't work?

Thank you.

Regards.

**Comment by evilaliv3** [comment]
Thank you @rmartinezgc for your question.

Would you please attach some more detail?

For example it would be valuable if you could clarify what you mean while saying that the application do not work anymore and if you could attach the file /var/globaleaks/log/globaleaks.log

**Comment by rmartinezgc** [comment]
When entering the access url in the browser, its response is typical of when a web page does not respond in a few minutes but the globaleaks service was running correctly.

Unfortunately, I do not have the logs for the rollback but I did not see anything unusual at the time.

**Comment by evilaliv3** [comment]
Is it posible that by mistakes during to the update you have anabled apache or nginx and that they are blocking globaleaks to bind on port 80?

Please look at the file /var/globaleaks/log/globaleaks.log

**Comment by rmartinezgc** [comment]
I don't know if this is the case. For my part, I just ran the command **apt-get update && apt-get install globaleaks**, if that command changed any settings, I couldn't tell you.

When I have a little more time, I'll try again in a development environment and we'll see.

Thank you.

**Comment by evilaliv3** [comment]
Thank you @rmartinezgc ; I'm going to close this ticket for the moment as non reproducible.

Please feel free to rech out if you would incur in this issue again and you manage to collect some more detail.
