### ISSUE TITLE
Not working online Globaleaks demo

### ISSUE THREAD

**Issue by Alicia-Unia** [globaleaks/GlobaLeaks#3438]
### What version of GlobaLeaks are you using?

demo version.

![error tryglobaleaks](https://user-images.githubusercontent.com/132290564/235493354-98bfd00d-a751-40f2-96ff-c5493a25e2e9.jpg)

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge, Safari

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android

### Describe the issue

From yesterday it does not work to access online demo globaleaks website nor can another demo page be created.

Al menos desde ayer no funciona acceder a la página web demo de Globaleaks que yo había creado ni se puede volver a crear otra página demo. 

![error tryglobaleaks2](https://user-images.githubusercontent.com/132290564/235495930-e379859f-d700-4aeb-8180-3262cbeef018.jpg)

### Proposed solution

Please, I need to know how solve this problem. Thank you

**Comment by evilaliv3** [comment]
Thank you. We just renewed the certificate. All should be fine now.
