### ISSUE TITLE
Tooltip button 'Set a reminder' not translated into Spanish

### ISSUE THREAD

**Issue by Jorge-CB** [globaleaks/GlobaLeaks#3441]
### What version of GlobaLeaks are you using?

Version 4.11.5

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Hello,

When you select the Spanish language. The tooltip of the 'Set a reminder' button of the recipient of the complaint does not appear translated.

![image](https://user-images.githubusercontent.com/132654228/236457468-ca927f29-200e-4808-a275-3295b8e9154b.png)

Thanks.

### Proposed solution

I think it's because in the file '/usr/share/globaleaks/client/data/l10n/es.json' the string key is: "Set a reminder date". The word 'date' would be left over.

![image](https://user-images.githubusercontent.com/132654228/236455964-e3ee810f-6f42-4f37-b46e-12b46029057c.png)

**Comment by evilaliv3** [comment]
Thank you. We will fix this in the next release updating the translations.

The correct text is "Set a reminder"

**Comment by evariitta** [comment]
Hello, I would like to report relating to the same issue that translations for the new feature "View" in the attachments seem to be missing as well. I can not find the string in Transifex either.
![image](https://github.com/globaleaks/GlobaLeaks/assets/103591617/f4f774ed-fc5b-46c6-ac24-b609a1195a4f)
