### ISSUE TITLE
Important discrepancies in mail templates

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3449]
### What version of GlobaLeaks are you using?

4.11.5

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### Describe the issue

The english version of the 'account_activation_mail_template' is missing the referende to {AccountRecoveryKeyInstructions}, which then not is shown to the new user.

This is very important information which is omitted.

Due to the fact, that we have had multiple issues with users omitting these steps, I suggest a stronger wording of these iunstructions. 

Current English version:

_We recommend that you access the “Preferences” section in order to retrieve your “Account Recovery Key” and store it safely. This key will be necessary to recover your access to the platform and to your data in case you forget your password._

I suggest a sligth stronger wording:

_We STRONGLY recommend that you immediately after your first login access the “Preferences” section in order to retrieve your “Account Recovery Key” and subsequently store it safely. This key is absolutely necessary to recover your access to the platform and to your data in case you forget your password. WITHOUT THIS KEY, YOU WILL NOT BE ABLE TO REGAIN ACCESS TO YOUR DATA!_

### Proposed solution

Add the reference in the template in a future release - considering the stronger wording

**Comment by evilaliv3** [comment]
Thank you for reporting this @schris-dk 

We will look into this and get sure the keyword AccountRecoveryKeyInstructions is correctly used.

In relation to the suggestion to change the wording of the message we will evaluate it but at the moment we are forced to keep it as it is because the text that you say is very critical would need proper revision and translation in all the languages supported by the software.

**Comment by evilaliv3** [comment]
At the moment but this could be an interesting feature to be added to the Profile feature (https://github.com/globaleaks/GlobaLeaks/issues/2039) to specificy if templates should be inherited from the primary tenant or be custom per-tenant

**Comment by evilaliv3** [comment]
@schris-dk: i just tested the software and i do not see any difference in the templates, especially for english.

I suspect you may have customized the template in the past and that this customization happened before we varied it.
To fix this issue at the moment you have either two possibilities: reset notification templates to the default or modify them manually to reflect the changes.
