### ISSUE TITLE
Small Typo in globaleaks.init

### ISSUE THREAD

**Issue by rglauco** [globaleaks/GlobaLeaks#3451]
https://github.com/globaleaks/GlobaLeaks/blob/dcc0378883814d55ae33f2aa3f4f7c60e7b67d46/debian/globaleaks.init#L185

By reinstalling globaleaks an error message appears:
` mkdir: cannot create directory ‘/dev/shm/globaleaks’: File exists`

**Comment by evilaliv3** [comment]
Bug fixed with commit: https://github.com/globaleaks/GlobaLeaks/commit/7f524c6b2c1820c8de1a1ecfa05d5e997cbbc264

The patch will be included starting from release 4.0.7
