### ISSUE TITLE
Possible bug in version 4.11.5 - Users not able to deactivate email notifications

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3456]
### What version of GlobaLeaks are you using?

4.11.5 

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Hi @evilaliv3 

Users have posibillity to disable email notifications from Globaleaks in their profiles when loogged on.
But, when the checkbox is cleared, and user click on the Save button, the checkbox reappears again.

**Comment by evariitta** [comment]
I must add, I have noticed that this happens in the older versions too. Only admins seem to be allowed to enable and disable email notifications for users. The selection is then forced for a user.
