### ISSUE TITLE
If no receivers are yet selected, clicks on "Next" give white page

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3460]
### What version of GlobaLeaks are you using?

4.11.5

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### Describe the issue

Until there are no receivers for the report, click "Next" on the questionnaire leads to a white page, where it "next" button only appears, and it's disabled.
In this situation, error validation seems to not be done, "send" button has the same issue.

If questionnaire stepper is active and you can step ahead the questionnaire and answer to a question that selects a reciever, the questionnaire will became ok.

If stepper is not active, whistleblower is stuck after it clicks "next".

![immagine](https://github.com/globaleaks/GlobaLeaks/assets/61267901/f8df35c8-32e8-4459-9274-7b6e9ed09bd4)

### Proposed solution

It seems that the old "please select a receiver" error is not working anymore.
I suggest to restore the previous behaviour, receiver checks should be done on the whole questionnaire since the first step. 
So this check should be done at "send" time.

**Comment by evilaliv3** [comment]
Thank you @larrykind:

- is this referring to the testing package that we passed you or to the stable version already released?
- is it correct that your issue apply to a setup where no recipients are assigned to the context and recipients are assigned dynamically based on the answers to the questionnaire?
