### ISSUE TITLE
Mission Impossible... configurate a https access

### ISSUE THREAD

**Issue by j3pc0m** [globaleaks/GlobaLeaks#3462]
### What version of GlobaLeaks are you using?

4.11.5

### What browser(s) are you seeing the problem on?

Tor Browser

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

I am trying to configurate a https access to our Globaleaks platform, but I can't do it..., **Error! Internal server error (Unexpected)** 

I check other issues, community, documentation, forum... 

Always log is:
2023-05-28 17:41:41+0200 [-] [E] exception mail suppressed for exception (<class 'acme.errors.ValidationError'>) [reason: special exception]

![image](https://github.com/globaleaks/GlobaLeaks/assets/53638302/cb6e098a-d0de-42e5-9374-d6eac2637ea2)

![image](https://github.com/globaleaks/GlobaLeaks/assets/53638302/eba88162-cc2a-4005-9c9d-84e4a96edfcf)

IP 81.38.27.80
Domain tuentidad.com.es

What am I doing wrong?

I other way, I try to install Globaleaks in other server with ubuntu 22.04, and apparmor 3.0.4, but Globaleaks script has a previous apparmor version and installation failed.

**Comment by j3pc0m** [comment]
Sorry, our server hasn't proxy

**Comment by evilaliv3** [comment]
Hello @j3pc0m 

The dns appears well configured.

Disable apache, and restart globaleaks.

GlobaLeaks to works require to be publicly reachable on the specified domain and accessible on both port 80 and 443

**Comment by j3pc0m** [comment]
Thanks a lot for your quickly answer, but the error continues

![image](https://github.com/globaleaks/GlobaLeaks/assets/53638302/58f5d7ee-5127-4750-9e44-6d8076a8e93f)

![image](https://github.com/globaleaks/GlobaLeaks/assets/53638302/ba420e7f-a76e-4dc3-8553-44234dfc2f05)

**Comment by j3pc0m** [comment]
Hi @evilaliv3. Sorry for bothering you again, but...

Can I do something else? Thansk again.

**Comment by j3pc0m** [comment]
Thansk a lot for the meeting @evilaliv3. I was GIWI, my Englidh is limited, especially spoken, but I have been able to follow your talk, more or less.
I wanted to see the content of the meetings and I want to congratulate you and thank you for your work.
