### ISSUE TITLE
Creating own template

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3468]
### Proposal

It would be very useful to be able to create your own template for new sites.

Currently we have to import our custom made questionaieres on every site we create. The same is  counting for other texts on front page etc :-)

### Motivation and context

This feature would make it possible to speed up the general time used to create the client sites :-)

**Comment by evilaliv3** [comment]
Thank you for yous suggestion @schris-dk 

Actually this proposal is already specified and @pnellikkaparambil is working on it and will be soon updating ticket https://github.com/globaleaks/GlobaLeaks/issues/2039 with the advancements.

I suggest you could follow that ticket and load there your requirements that will try to take into account during development

**Comment by schris-dk** [comment]
Great - thnx for info :)

Søren Christensen
Senior manager
BDO Risk Assurance - Forensic Services
