### ISSUE TITLE
Broken layout on context submission form 

### ISSUE THREAD

**Issue by DanWin** [globaleaks/GlobaLeaks#3471]
### What version of GlobaLeaks are you using?

4.11.5 both our production system and a fresh installation are affected

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Opening a context submission form shows a login form for prevoius submissions. The label is overlayed by the input field though.
![image](https://github.com/globaleaks/GlobaLeaks/assets/3327912/cb276c7a-1639-454d-a561-e30464035286)

### Proposed solution

Change HTML/CSS to properly allign the elements

**Comment by evilaliv3** [comment]
Thank you for reporting this @DanWin 

This is actually a minor defect that we already identified and that will be fixed in the next minor release in few days!

**Comment by evilaliv3** [comment]
Fixed, the correction will be included in release 4.11.6
