### ISSUE TITLE
Syntax error in db/migrations

### ISSUE THREAD

**Issue by gianlucagilardi** [globaleaks/GlobaLeaks#3479]
### What version of GlobaLeaks are you using?

4.11.5

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

installation of self compiled gl deb fails for syntax errors in db/migrations

Setting up globaleaks (4.11.5) ...
  File "/usr/lib/python3/dist-packages/globaleaks/db/migrations/update_44/__init__.py", line 1
    ../empty.py
    ^
SyntaxError: invalid syntax

  File "/usr/lib/python3/dist-packages/globaleaks/db/migrations/update_56/__init__.py", line 1
    ../empty.py
    ^
SyntaxError: invalid syntax

  File "/usr/lib/python3/dist-packages/globaleaks/db/migrations/update_61/__init__.py", line 1
    ../empty.py
    ^
SyntaxError: invalid syntax

dpkg: error processing package globaleaks (--install):
 installed globaleaks package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 globaleaks

**Comment by evilaliv3** [comment]
@gianlucagilardi : this error is actually quite strange and i would need your support to understand it better.

The files that are reported to be not correct are files that are just a link to a correct file. 
I suspect that in this setup links are not correctly working and are failing to reach the correct file to include.

Would you please clarify how this setup is made and how it is different from the previous that you made?
