### ISSUE TITLE
Write GlobaLeaks documentation on how to Upgrade globaleaks

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#348]
Write GlobaLeaks documentation on how to Upgrade globaleaks because the current upgrade process may have issues.

This ticket is about documenting the upgrade process with the following elements:
- First backup globaleaks data dir
- Then backup the original .deb of the currently installed version
- How to update globaleaks with apt-get
- What happen during the first start (database upgrade)
- How to rebuild the GLClient if the template design is customized.
- How to rollback if something went wrong
- How to update pip packages (not handled by debian) if needed

##

**Comment by vodkina** [comment]
The upgrade guide is existing and regularly updated. I'm closing this issue.
