### ISSUE TITLE
The function CopyToClipboard, when youre generating a report is not working

### ISSUE THREAD

**Issue by juherba** [globaleaks/GlobaLeaks#3490]
### What version of GlobaLeaks are you using?

4.11.5

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Yesterday i was trying to copy the id of the report but the function that copy the content to clipboard is not working.

**Comment by evilaliv3** [comment]
@juherba : have you enabled HTTPS?

this functions works only when https is enabled

**Comment by juherba** [comment]
@evilaliv3 I'm not using https, but i will try to see if it works

**Comment by evilaliv3** [comment]
Ok the problem is definitely that.

Chrome and safe browsers do not enable to copy from the page if the page is
not secured
