### ISSUE TITLE
Failed to load application: No module named 'pytz.exceptions' when starting with systemctl

### ISSUE THREAD

**Issue by visitlo** [globaleaks/GlobaLeaks#3492]
### What version of GlobaLeaks are you using?

4.11.5

### What browser(s) are you seeing the problem on?

Other

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

I'm trying to start the service but I get this error in the journals.
```
globaleaks[2226]: Failed to load application: No module named 'pytz.exceptions'
globaleaks[2161]:    ...fail!
```

I'm using 

- Ubuntu 20.04.6
- Python 3.8.10
- Globaleaks 4.11.5

I have the `pytz` module installed.

```
$ pip install pytz
Requirement already satisfied: pytz in ./.local/lib/python3.8/site-packages (2023.3)
```

**Comment by visitlo** [comment]
It appears I was starting it the wrong way. It works by running `globaleaks start` as the root user.
However there's still a weird error message:
```
[E] Could not reserve socket for 98 (error: Address already in use)
[E] Could not reserve socket for 98 (error: Address already in use)
```

**Comment by evilaliv3** [comment]
thank you for the question.

 I suggest that you check that your system is not running apache or nginx. 

Probably one of these is keeping the port busy
