### ISSUE TITLE
Content Security Policy: The options on this page have blocked the loading of an online resource ("script-src").Provide a general summary of the issue

### ISSUE THREAD

**Issue by aapian** [globaleaks/GlobaLeaks#3494]
### What version of GlobaLeaks are you using?

4.11.5

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

I was trying to create a file report and click on page output 

"Content Security Policy: The options on this page have blocked the loading of an online resource ("script-src").Provide a general summary of the issue" in web browser's console. So, the input to select receipt no show

**Comment by evilaliv3** [comment]
Thank you for reporting this.

Would you please check to have assigned at least one recipient to your
reporting channel?

I suspect you may have skipped this stepm

**Comment by aapian** [comment]
Oh, thank you for your answer.

**Comment by aapian** [comment]
i can create a report right now !!! but the alert "Content Security Policy: The options on this page have blocked the loading of an online resource ("script-src") keep going

**Comment by evilaliv3** [comment]
Thank you for confirming this. Actually that error is correct ans should stay.

closing the ticket as resolved!
