### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by zoko123** [globaleaks/GlobaLeaks#3500]
### What version of GlobaLeaks are you using?

Latest, auto update on.

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Ticket Nr. can not be copied to clipboard, but text when hovering over is "copy to clipboard"

### Proposed solution

Remove text over

**Comment by zoko123** [comment]
![image](https://github.com/globaleaks/GlobaLeaks/assets/32892833/12cf4c89-d63d-447c-bb3c-1c1f93263fbe)

**Comment by gianlucagilardi** [comment]
> ![image](https://user-images.githubusercontent.com/32892833/249125265-12cf4c89-d63d-447c-bb3c-1c1f93263fbe.png)

Are you on a HTTPS connection? Copy-to-clipboard works only on HTTPS, not plain HTTP.

**Comment by zoko123** [comment]
NO, thank you.

 

You can close this thread.

 

Best regards,

 

Zoran Kovačević
