### ISSUE TITLE
Revoke access gives error at the report list page

### ISSUE THREAD

**Issue by evariitta** [globaleaks/GlobaLeaks#3504]
### What version of GlobaLeaks are you using?

4.11.5

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

"Revoke access" gives an error when performed at the page of all reports.

![image](https://github.com/globaleaks/GlobaLeaks/assets/103591617/239d6358-8132-40e4-9184-d21316f15588)

"Grant access" works well, as well as the revoke access function at a single report's page.

**Comment by evilaliv3** [comment]
Thank you @evariitta 

We will check this and fix it in the next release 4.12 that will be issued in few days.

**Comment by evilaliv3** [comment]
Sould be solved since release 4.12
