### ISSUE TITLE
Custom Javascript management

### ISSUE THREAD

**Issue by emanuelegreco** [globaleaks/GlobaLeaks#3521]
### What version of GlobaLeaks are you using?

Globaleaks: 4.11.5

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

The button "Upload Javascript" is missing.

Changes in version 4.10.0 declares "Remove web possiblity to load javascript customization via web interface"

Is there a way to change custom javascript in some other way? Even a file already customized and uploaded before 4.10.0 was released...

**Comment by evilaliv3** [comment]
yes! Confirmed we are about to reintegrate this! 4.12 on arrival!
