### ISSUE TITLE
The selected answer hint (?) does not show when the answer is selected in selection box questions

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3546]
### What version of GlobaLeaks are you using?

4.12.2

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

For Selection box type of questionnaire (possibly other type of questions) the selected answer hint (?) does not show when the answer is selected.

**Comment by evilaliv3** [comment]
Thank you @elbill; this is actually a regression that i just noticed. 

There are some on the questionnaire validation that i'm fixing right now.
