### ISSUE TITLE
Mandatory question asterisk does not show properly for some type of questions

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3547]
### What version of GlobaLeaks are you using?

4.12.2

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Noticed that the mandatory question asterisk shows on the next line for Checkbox type of question.
Also for single line text question, while it seems to work properly, when making window smaller if goes to the next line even though  there is enough space.

**Comment by evilaliv3** [comment]
Solved in 4.12.3
