### ISSUE TITLE
Next button does not seem to move to next questionnaire tab

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3548]
### What version of GlobaLeaks are you using?

4.12.2

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

[Next] button does not seem to move to next questionnaire tab. 
In the specific questionnaire there is a conditional dependence between questionnaire tab 2 and a question in tab 1. 
When clicking the tabs it works, and submission also works

**Comment by evilaliv3** [comment]
This was a bug of releases rom 4.12.0 to 4.12.2. and was first reported by @gianlucagilardi  It should be solved in 4.12.3 with commit https://github.com/globaleaks/GlobaLeaks/commit/25709f0377f0389b0082b5ed85076bfbb535c289
