### ISSUE TITLE
"Skip to content" link appears left top 

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3549]
### What version of GlobaLeaks are you using?

4.12.2

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

"Skip to content" link appears very briefly left top when moving from landing page to the questionnaire. Not sure if this is a bug but it is a bit annoying and catches the eye of the user!

**Comment by evilaliv3** [comment]
This was added with @larrykind in relation to accesibility (it is the link that people with some eye deficiency will rely on) ive to see presin tab so the browser should see it. i've to see it we are able to hide it to the rest of the audience

**Comment by danielvaknine** [comment]
We've also noticed this

**Comment by evilaliv3** [comment]
Fixed and patch included in release 4.12.6
