### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by Gianca77** [globaleaks/GlobaLeaks#3551]
### What version of GlobaLeaks are you using?

4.12.2

### What browser(s) are you seeing the problem on?

Tor Browser, Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Dears
I completed the configuration of Settings, Channel and Notification. Still, when I try to send a report after filling all fields, it seems that I miss something and when I click submit nothing happens and I am returned to the top of the page without any error message.
I tried it with Chrome and Tor too and the behavior is the same

**Comment by gianlucagilardi** [comment]
Just a hunch, ave you configured at least one recipient in the channel setting?

**Comment by Gianca77** [comment]
damn...no! I'm a real newmbie, sorry!
It works, thank you
