### ISSUE TITLE
Move up/down does not work for case management substatuses  

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3555]
### What version of GlobaLeaks are you using?

4.12.3

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Move up/down does not work for case management substatuses 
I get the error

Version: 4.12.3

TypeError Inappropriate argument type.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 190, in maybeDeferred
    result = f(*args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/operation.py", line 25, in put
    return func(self, request['args'], *args, **kwargs)

TypeError: 'tuple' object is not callable

**Comment by evilaliv3** [comment]
Fixed in 4.12.4
