### ISSUE TITLE
Error on input validation on manual SSL certificate upload

### ISSUE THREAD

**Issue by poliveiraIPB** [globaleaks/GlobaLeaks#3559]
### What version of GlobaLeaks are you using?

GL 4.12.5
<img width="1709" alt="erro_globalleaks" src="https://github.com/globaleaks/GlobaLeaks/assets/14893611/71334c3e-d32a-450d-be67-c672084064ff">

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

macOS

### Describe the issue

Describe the bug
We are trying to upload a new SSL cert and keep receiving 'Error on input validation []'. It doesn't matter which we try to upload.

To Reproduce
Try to upload any of the SSL files manually

Expected behavior
Upload SSL files

Desktop (please complete the following information):

MacOS 12.5
    Firefox 115.0.2 (64-bit)

Additional context
Server
Debian 11.7
GL 4.12.5

**Comment by evilaliv3** [comment]
thank you

we just retested the functionality and we are not experiencing any issue.

Which kind of file are you loading? The systen accept keys and certificates in PEM format only.

**Comment by evilaliv3** [comment]
I see.

Can you look if you have any error in the file /var/globaleaks/log/globaleaks.log? 

Which kind of certificate are you using? Who emitted it?

**Comment by poliveiraIPB** [comment]
> I see.
> 
> Can you look if you have any error in the file /var/globaleaks/log/globaleaks.log?
> 
> Which kind of certificate are you using? Who emitted it?

The problem is that i have the Intermediate Certificates  in the same file.
