### ISSUE TITLE
CSS ID #ReceiptText removed in commit d6dbec5 - "Improve accessibility of receipt page"

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3579]
### What version of GlobaLeaks are you using?

4.12.6

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Hi @evilaliv3 

CSS ID #ReceiptText is removed in commit d6dbec5 - "Improve accessibility of receipt page".
We are using mockEngine to inject text here and this removal breaks it.

Is it possible to reintroduce #ReceiptText ?

**Comment by evilaliv3** [comment]
Ok!

**Comment by aetdr** [comment]
Thanks @evilaliv3

**Comment by evilaliv3** [comment]
Change reverted; it will be included in the next release.

**Comment by evilaliv3** [comment]
Going to be merged today in 4.13.0
