### ISSUE TITLE
Failure on migration of contexts from db versions <=61

### ISSUE THREAD

**Issue by enribar** [globaleaks/GlobaLeaks#3592]
### What version of GlobaLeaks are you using?

We upgraded from 3.6.40 to 4.12.9; installed also the update to version 4.13.0

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows, Linux

### Describe the issue

Hi, we upgraded our installation of Globaleaks from version 3.6.40 to 4.12.9 using `apt-get update && apt-get install globaleaks`.
Admin login works and all options are visible, but it is not possible to insert a new anonymous submission since the wizard is now blank: when an anonymous user clicks on "Enter submission", the disclaimer popup appears, when he clicks on "proceed" this empty page is displayed:

![image](https://github.com/globaleaks/GlobaLeaks/assets/6407955/6ddd6559-670b-4d7a-8432-5c8546e21758)

In our installation we have a single Questionnaire, that is correctly visible in admin panel.

We also tried to re-install globaleaks using install-globaleaks.sh, but the problem persists.
Browser console does not show any error; access.log seems to not contain any error, it has only lines containing HTTP 200. globaleaks.log does not write any line when the empty submission wizard is loaded by an user.

Do you have any clue?

**Comment by evilaliv3** [comment]
Do you have at least one enabled reporting channel with at least one recipient assigned to it?

**Comment by enribar** [comment]
> Do you have at least one enabled reporting channel with at least one recipient assigned to it?

I looked into admin options and our only reporting channel (named "Default") was marked as hidden! I de-selected that checkbox and now the wizard is visible. Maybe the upgrade procedure set it to hidden?

Thanks by the way!

**Comment by evilaliv3** [comment]
Thank you @enribar, this was actually the case. I'm producing a patch for the migration that we are issuing to prevent other users to incurr on the same issue.

Thank you for reporting this!

**Comment by evilaliv3** [comment]
Merged in release 4.13.1
