### ISSUE TITLE
possible bug with v4.13.2 - nacl.exceptions.CryptoError: An error occurred trying to decrypt the message

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3594]
### What version of GlobaLeaks are you using?

v4.13.2

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Hi @evilaliv3 

We have seen a few of these mails since upgrade to 4.13.2

```
Version: 4.13.2

nacl.exceptions.CryptoError 
    Base exception for all nacl related errors
    

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 733, in get
    filelocation = GCE.streaming_encryption_open('DECRYPT', files_prv_key, filelocation)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 297, in streaming_encryption_open
    return _StreamingEncryptionObject(mode, user_key, filepath)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 127, in __init__
    self.key = _GCE.asymmetric_decrypt(self.user_key, x)

  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 293, in asymmetric_decrypt
    return SealedBox(prv_key).decrypt(data)

  File "/usr/lib/python3/dist-packages/nacl/public.py", line 358, in decrypt
    plaintext = nacl.bindings.crypto_box_seal_open(

  File "/usr/lib/python3/dist-packages/nacl/bindings/crypto_box.py", line 310, in crypto_box_seal_open
    ensure(res == 0, "An error occurred trying to decrypt the message",

  File "/usr/lib/python3/dist-packages/nacl/exceptions.py", line 68, in ensure
    raise raising(*args)

nacl.exceptions.CryptoError: An error occurred trying to decrypt the message

```

**Comment by aetdr** [comment]
@evilaliv3 

Could it be that this one is somehow related to #3601 ?

**Comment by evilaliv3** [comment]
Done confirmed related to the download of files or granting of reports for platforms migrated from version <= 4.11 to 4.12.

The bug is actually introduced in the migration to 4.12 were keys of files were not migrated correctly.


I

**Comment by FlokiNET** [comment]
We noticed the bug now with an report a customer recived, however the backup from back then is not available anymore as to much time passed.

Did the keys got fully corrupted and only a backup is an option or would be to some reconverting an option?

`-] [E] nacl.exceptions.CryptoError \n    Base exception for all nacl related errors\n    \n\nTraceback (most recent call last):\n\n  File "/usr/lib/python3/dist-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks\n    result = g.send(result)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 729, in get\n    filelocation = GCE.streaming_encryption_open('DECRYPT', tip_prv_key, filelocation)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 309, in streaming_encryption_open\n    return _StreamingEncryptionObject(mode, user_key, filepath)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 139, in __init__\n    self.key = _GCE.asymmetric_decrypt(self.user_key, x)\n\n  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 305, in asymmetric_decrypt\n    return SealedBox(prv_key).decrypt(data)\n\n  File "/usr/lib/python3/dist-packages/nacl/public.py", line 361, in decrypt\n    self._private_key,\n\n  File "/usr/lib/python3/dist-packages/nacl/bindings/crypto_box.py", line 311, in crypto_box_seal_open\n    raising=exc.CryptoError)\n\n  File "/usr/lib/python3/dist-packages/nacl/exceptions.py", line 68, in ensure\n    raise raising(*args)\n\nnacl.exceptions.CryptoError: An error occurred trying to decrypt the message\n`
