### ISSUE TITLE
Error on accessing reports on release 4.13.2

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3599]
### What version of GlobaLeaks are you using?

4.13.2

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

After applying update 4.13.2 - on our test server, we get a server error and is not able to access the reports.

I've attached Globaleaks.log
[globaleaks (2).log](https://github.com/globaleaks/GlobaLeaks/files/12509843/globaleaks.2.log)

**Comment by evilaliv3** [comment]
Thank you for reporting this @schris-dk 

I'm looking into it now and will definitely be able to issue a patch in the next hours without any issue and resolving the inconvenience.

The preblem is probably introduced within this commit of optimization: https://github.com/globaleaks/GlobaLeaks/commit/ca0052d3c853a40c9aef41d85784b87410821c3c

**Comment by schris-dk** [comment]
Thnx Giovanni!

This is really great 😊

I unfortunately encountered the issue when doing a presentation really early this morning – we had updated the server during the weekend, and we didn’t notice the error before the presentation. Luckily, the client was very relaxed about the issue, so no worries there😊 (glad that I have done hundreds of these presentations, so I could “freestyle” my way out 😊)

Med venlig hilsen
Søren Christensen
Senior Manager
Telefon: +4539159901
Mobil: +4530934933
***@***.******@***.***>



Fra: Giovanni Pellerano ***@***.***>
Sendt: 4. september 2023 09:15
Til: globaleaks/GlobaLeaks ***@***.***>
Cc: Søren Christensen ***@***.***>; Mention ***@***.***>
Emne: Re: [globaleaks/GlobaLeaks] CRITICAL ISSUE - Server error when accessing reports (Issue #3599)


Ekstern afsender

Thank you for reporting this @schris-dk<https://github.com/schris-dk>

I'm looking into it now and will definitely be able to issue a patch in the next hours without any issue and resolving the inconvenience.

The preblem is probably introduced within this commit of optimization: ca0052d<https://github.com/globaleaks/GlobaLeaks/commit/ca0052d3c853a40c9aef41d85784b87410821c3c>

**Comment by evilaliv3** [comment]
Fixed in release 4.13.3
