### ISSUE TITLE
When creating an Let's Encrypt certificate System throws HTTP 500

### ISSUE THREAD

**Issue by NerdyBear90** [globaleaks/GlobaLeaks#3600]
### What version of GlobaLeaks are you using?

 4.13.2

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows, macOS

### Describe the issue

After Inserting the hostname for the tenant and clicking on the Automatic Deployment of Let's Encrypt it takes some Time and then the system Throws an HTTP 500 Error:

Log extraction: 
`2023-09-04 08:33:18+0200 [-] [E] exception mail suppressed for exception (<class 'acme.errors.ValidationError'>) [reason: special exception]`

**Comment by evilaliv3** [comment]
Thank you for reporting this.

Do you confirm that the DNS is configured to point to the server IP and
that the server is publicly exposed on both port 80 and 443?

If possible please feel free to share the domain name so that me or others
may check the configuration from an external point of view

**Comment by NerdyBear90** [comment]
@evilaliv3 Thanks for your advise its an typo in the ip -,- /close
