### ISSUE TITLE
Advanced settings not saved

### ISSUE THREAD

**Issue by enribar** [globaleaks/GlobaLeaks#3603]
### What version of GlobaLeaks are you using?

4.13.0

### What browser(s) are you seeing the problem on?

Firefox, Microsoft Edge

### What operating system(s) are you seeing the problem on?

Windows, Linux

### Describe the issue

Hi, in settings > advanced menu we try to set as enabled the following options

- Log accesses of internal users
- Notify administrators of software problems 

but when we click on "save" and reload the page, the two checkboxes appear as un-ticked.

Our globaleaks installation was recently updated from version 3.6.40 to 4.13.0 .

**Comment by evilaliv3** [comment]
Thank you @enribar

I just tried  to reproduce this bug but i'm acutally not able to.

Would you please try to reproduce it on try.globaleaks.org and eventually pass me the name of the platforms where you managed to reproduce it?

**Comment by enribar** [comment]
Hi, I registered on try.globaleaks.org, but i do not find the following options:
-     Log accesses of internal users
-     Notify administrators of software problems
in that test environment. I attach a screenshot showing the differences between try.globaleaks.org (on the left) and our Globaleaks (on the right). Both servers are on version 4.13.6 .
![Screenshot from 2023-09-11 13-51-08](https://github.com/globaleaks/GlobaLeaks/assets/6407955/893e43ff-5eb4-4150-8179-785150a67b75)
Our platform is: `https://whistleblowing.ausl.bologna.it/ `
I also attach a video showing our issue.

[Screencast from 2023-09-11 13-38-56.webm](https://github.com/globaleaks/GlobaLeaks/assets/6407955/cd3f7c55-fc5a-48a7-8888-6a7728768062)

**Comment by enribar** [comment]
Hi @evilaliv3, after further investigations we found the cause of the problem. It was not caused by Globaleaks, but the cause was a web application firewall that in our environment resides before sites exposed on internet. We added a custom allow rule and the problem disappeared.
Thank you for your help.
