### ISSUE TITLE
Possible bug with version 4.13.3 - nacl.bindings.crypto_box_seal_open() ValueError: negative array length

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3606]
### What version of GlobaLeaks are you using?

4.13.3

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Hi @evilaliv3 

We are now seeing this one after uypgrade to 4.13.3

```
Version: 4.13.3

ValueError Inappropriate argument value (of correct type).

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap
    result = function(session, *args, **kwargs)

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 140, in grant_tip_access
    if db_grant_tip_access(session, tid, user, user_cc, itip, rtip, receiver_id):

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/rtip.py", line 92, in db_grant_tip_access
    _files_key = GCE.asymmetric_decrypt(user_cc, base64.b64decode(rtip.deprecated_crypto_files_prv_key))

  File "/usr/lib/python3/dist-packages/globaleaks/utils/crypto.py", line 293, in asymmetric_decrypt
    return SealedBox(prv_key).decrypt(data)

  File "/usr/lib/python3/dist-packages/nacl/public.py", line 358, in decrypt
    plaintext = nacl.bindings.crypto_box_seal_open(

  File "/usr/lib/python3/dist-packages/nacl/bindings/crypto_box.py", line 307, in crypto_box_seal_open
    plaintext = ffi.new("unsigned char[]", _mlen)

ValueError: negative array length

```

**Comment by schris-dk** [comment]
Hi!
I have a question pertaining the "fix procedure"

Ive atached a flow chart as I understand the directions - please let me know if it is correct :-)

[WB update flow.pdf](https://github.com/globaleaks/GlobaLeaks/files/12871610/WB.update.flow.pdf)

**Comment by evilaliv3** [comment]
@schris-dk: the chart is totally correct.

Regarding step2, you actually need a backup copy for a system < 4.12

**Comment by schris-dk** [comment]
I've run into a permission error when trying to use SCP to transferthe files between the machines. I'm no Linux expert, but I assume to "chown" the attachment files - but I'm not sure how to do so. Iv'e elevated to root when trying to use SCP.

Help would be highly appreciated

![scp session](https://github.com/globaleaks/GlobaLeaks/assets/70965554/e3f21438-e8fe-40c1-b0b6-f79887acc77e)

**Comment by schris-dk** [comment]
Hi!

Ive finally been able to run the script (after editing permissions and ownership of the files and folders) - but it does'nt really help out. I can see, that no alteration has been made to globaleaks.db.

The timestamps for access and modify stays the same - like no interaction with the file at all.

globaleaks.db and backup.db are in the same folder as the fix_db.py script - owner on files set to root:root - chmod to 777

what to do?

**Comment by schris-dk** [comment]
Hi all of you who might struggle with applying the procedurees :-)

Find attached a walk through of the steps to apply the fix.

Please note, that there is a slight update to the fix_db.py (new version is at the end of the attached manual)

[Database repair.pdf](https://github.com/globaleaks/GlobaLeaks/files/12926757/Database.repair.pdf)

**Comment by evilaliv3** [comment]
Thank you @schris-dk ! The version of the script published above has been already updated
