### ISSUE TITLE
Failure on visualization of identity access requests on releases 4.13.1-4

### ISSUE THREAD

**Issue by lucagabbrielli76** [globaleaks/GlobaLeaks#3609]
### What version of GlobaLeaks are you using?

4.13.3

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

When a Receiver send a request for details to the Custodian, Custodian can't see the Request on his panel

### Proposed solution

It was working before, maybe a bug in the latest release?

**Comment by evilaliv3** [comment]
Thank you for notifying this.

May I ask you when did you update and which version where you using before
updating?

**Comment by lucagabbrielli76** [comment]
We were using version 4.11.5 before; we just reinstalled everything and we started to use the actual version now.

PS.: se vuoi possiamo scriverci in italiano :)

**Comment by evilaliv3** [comment]
Thank you for this detail. We will look into this in the next days trying to replicate the bug.

Are you able to replicate this on try.globaleaks.org? do you experience it there as well ?

**Comment by lucagabbrielli76** [comment]
yes, I tried also on try.globaleaks.org, same issue; custodian role is enabled, but I can't see any request sent from the recipient

**Comment by evilaliv3** [comment]
@lucagabbrielli76 may i ask you which is the tenant that you have configured? this way i may check if it is a matter of wrong configuration or bug

**Comment by lucagabbrielli76** [comment]
yes, sure: esseti.try.globaleaks.org and whistleblowing.essetiweb.it

**Comment by evilaliv3** [comment]
Thank you, bug confirmed.

I'm going to issue a patch that will be included by today in a release 4.13.5

**Comment by lucagabbrielli76** [comment]
All right, thanks!

**Comment by evilaliv3** [comment]
Fixd and released in 4.13.5
