### ISSUE TITLE
"Site settings" Title label is not translated

### ISSUE THREAD

**Issue by JaviAlama** [globaleaks/GlobaLeaks#3610]
### What version of GlobaLeaks are you using?

4.13.5

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Even if you add other languages such as Spanish or Valencian, when you switch between the main menu options (Home, Settings, Users, etc...) the "Site Settings" menu title always appears in English. 

I attach screenshots.

![Captura2](https://github.com/globaleaks/GlobaLeaks/assets/126556000/e11d5431-9470-4622-bee3-611beee87860)
![Captura1](https://github.com/globaleaks/GlobaLeaks/assets/126556000/88e897f7-1832-4bf4-b4c6-4fba9f265424)

### Proposed solution

Modify the "Site Settings" label so that it also changes according to the selected language.

**Comment by evilaliv3** [comment]
Thank you @JaviAlama 

This has been just fixed in commit https://github.com/globaleaks/GlobaLeaks/commit/cf39b614d03c911130e879454135c16cc4ea3442

The correction has been included in a minor release 4.13.5

**Comment by evilaliv3** [comment]
Actually the previous fix was only partial and apply only to some users.
I'm going to issue a new patch will apply to all users
