### ISSUE TITLE
Enable branching in forms

### ISSUE THREAD

**Issue by flo-assling** [globaleaks/GlobaLeaks#3614]
### Proposal

At the moment, forms seem to be very static.
It would be great to have an option for dynamically active field.
Example:
In which company did this happen?
  in my company -> no changes to the form
  in another company -> additional text field "Name of external company" appears

### Motivation and context

This would give much more flexibility when creating forms

**Comment by evilaliv3** [comment]
Thank you @flo-assling 

This is actually implemented.

Try to look at the Trigger options of questions and try to use them in combination with questions of type Selection Box
