### ISSUE TITLE
No answer on HTTP(S) ports since 4.13.6

### ISSUE THREAD

**Issue by GeoffreyFrogeye** [globaleaks/GlobaLeaks#3622]
### What version of GlobaLeaks are you using?

4.13.6

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

When upgrading to Globaleaks 4.13.6, or installing it on a fresh Ubuntu 20.04 VPS  following the [instructions](https://docs.globaleaks.org/en/main/setup/InstallationGuide.html), ports ports 80 or 443 no longer answer from the outside and any request times out. Accessing those from the inside (`curl http://localhost`) or from Tor still work. Downgrading to 4.13.5 is a workaround.

**Comment by evilaliv3** [comment]
Hello @GeoffreyFrogeye 

Thank you for your feedback.

The current release has implemented a significant update making the process rootless and we are binding on port 80 and 443 using the init script.

I've some questions for you:
- which distribution / version are you running?
- are you running globaleaks via it's init script or in a different way?

**Comment by GeoffreyFrogeye** [comment]
> which distribution / version are you running?

Ubuntu 20.04 (also it's the same on Ubuntu 18.04 but I understand this is not supported by GlobalLeaks). I could check others if needed.

> are you running globaleaks via it's init script or in a different way?

I assume via its own init script, I just ran the installation script and now it starts automatically on boot.

**Comment by evilaliv3** [comment]
can you show my your configuation of /etc/default/globaleaks?

**Comment by GeoffreyFrogeye** [comment]
It's empty (just comments):

```
# This is a configuration file for /etc/init.d/globaleaks;
# it allows you to perform common modifications to the behavior
# of the globaleaks daemon.
#
# Default settings can be found at: /usr/share/globaleaks/default
```

**Comment by evilaliv3** [comment]
Thank you.

I'm going to spawn an ubuntu version 20.04 to check the situation directly.

In this release we removed the necessary for globaleaks to bind on port 80 and 443, but we are just implementing a forwarding with iptables inside the install script.

**Comment by evilaliv3** [comment]
@GeoffreyFrogeye would you please run the this command?
```iptables -t nat -nvL```

The output should be like:
Chain PREROUTING (policy ACCEPT 320 packets, 16817 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    4   269 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* globaleaks */ tcp dpt:80 redir ports 8080
    5   260 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* globaleaks */ tcp dpt:443 redir ports 8443

Chain INPUT (policy ACCEPT 329 packets, 17346 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 44 packets, 4126 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 REDIRECT   tcp  --  *      lo      0.0.0.0/0            0.0.0.0/0            /* globaleaks */ tcp dpt:80 redir ports 8080
    0     0 REDIRECT   tcp  --  *      lo      0.0.0.0/0            0.0.0.0/0            /* globaleaks */ tcp dpt:443 redir ports 8443

Chain POSTROUTING (policy ACCEPT 23 packets, 2866 bytes)
 pkts bytes target     prot opt in     out     source               destination

**Comment by GeoffreyFrogeye** [comment]
```
[root@globaleaks ~]$ iptables -t nat -nvL
Chain PREROUTING (policy ACCEPT 1042 packets, 48842 bytes)
 pkts bytes target     prot opt in     out     source               destination
   16   836 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* globaleaks */ tcp dpt:80 redir ports 8080
   26  1344 REDIRECT   tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* globaleaks */ tcp dpt:443 redir ports 8443

Chain INPUT (policy ACCEPT 48 packets, 2264 bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 358 packets, 25607 bytes)
 pkts bytes target     prot opt in     out     source               destination
    0     0 REDIRECT   tcp  --  *      lo      0.0.0.0/0            0.0.0.0/0            /* globaleaks */ tcp dpt:80 redir ports 8080
    0     0 REDIRECT   tcp  --  *      lo      0.0.0.0/0            0.0.0.0/0            /* globaleaks */ tcp dpt:443 redir ports 8443

Chain POSTROUTING (policy ACCEPT 274 packets, 20567 bytes)
 pkts bytes target     prot opt in     out     source               destination
 ```

Btw I also just tried on Debian 12 as it was the recommended one, same issue.

**Comment by frewsxcv** [comment]
Is this related to https://try.globaleaks.org/ being down?

**Comment by simon-src** [comment]
My suggestion is to look at the `OUTPUT` chain. The current `OUTPUT` chain in the `filter` table would not allow traffic to port 8080 or 8443:

This is output of the `iptables -L -vn` `OUTPUT` table with globaleaks 4.13.4
```
Chain OUTPUT (policy ACCEPT 944K packets, 61M bytes)
 pkts bytes target     prot opt in     out     source               destination         
4732K 4687M ACCEPT     all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* globaleaks */ state RELATED,ESTABLISHED owner UID match 1200
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* globaleaks */ owner UID match 1200 tcp dpt:25
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* globaleaks */ owner UID match 1200 tcp dpt:80
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* globaleaks */ owner UID match 1200 tcp dpt:53
   82  4920 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* globaleaks */ owner UID match 1200 tcp dpt:443
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* globaleaks */ owner UID match 1200 tcp dpt:465
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* globaleaks */ owner UID match 1200 tcp dpt:587
    0     0 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* globaleaks */ owner UID match 1200 tcp dpt:9050
    0     0 ACCEPT     udp  --  *      *       0.0.0.0/0            0.0.0.0/0            /* globaleaks */ owner UID match 1200 udp dpt:53
    0     0 DROP       all  --  *      !lo     0.0.0.0/0            0.0.0.0/0            /* globaleaks */ owner UID match 1200
```

**Comment by simon-src** [comment]
I've installed `4.13.6` on a fresh bookworm and got the same results as @GeoffreyFrogeye

Running `tcpdump`  on `lo` yielded 0 packets. There is no NAT configured or any external firewalling.

We do have a standard `iptables` filter table configuration where the policy on `INPUT` is `DROP`:

```
root@globaleaks-test:~# iptables -L -vn
Chain INPUT (policy DROP 1 packets, 588 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     0    --  lo     *       0.0.0.0/0            0.0.0.0/0           
  107 21037 ACCEPT     0    --  *      *       0.0.0.0/0            0.0.0.0/0            state RELATED,ESTABLISHED
    0     0 ACCEPT     6    --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:22
    0     0 ACCEPT     6    --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80
    0     0 ACCEPT     6    --  *      *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443
    0     0 ACCEPT     1    --  *      *       0.0.0.0/0            0.0.0.0/0            icmptype 8
```

If i flush this table the redirection in the `NAT` table works.

You would expect the first `lo` ACCEPT rule would suffice for the redirection to work. 

Maybe there are `sysctl.conf` we need to set.

**Comment by evilaliv3** [comment]
I see thank you @simon-src 

For your information the init script is https://github.com/globaleaks/GlobaLeaks/blob/main/debian/globaleaks.init

**Comment by simon-src** [comment]
Thanks @evilaliv3 

I've just tested with policy `DROP` set again on the filter `INPUT` chain but now with the following rules added:

```
iptables -I INPUT -p tcp  --dport 8443 -j ACCEPT
iptables -I INPUT -p tcp  --dport 8080 -j ACCEPT
```

Now I can connect to globaleaks without a problem. Limiting the rule to `lo` only gives me dropped connections.

**Comment by evilaliv3** [comment]
thank you. i was actually about to test this.

Which patch do you propose for the init script?

**Comment by simon-src** [comment]
Patch:

```
--- /root/globaleaks.4.13.6	2023-09-11 19:32:34.274415069 +0000
+++ /etc/init.d/globaleaks	2023-09-11 19:37:54.461120235 +0000
@@ -138,7 +138,7 @@
         ip6tables -m comment --comment "globaleaks" -t filter -A OUTPUT ! -o lo -m owner --uid-owner ${USERNAME} -j DROP
     else
 
-        # Enable enstablished connections, new connections on used tcp and udp ports
+        # Enable established connections, new connections on used tcp and udp ports
         iptables -m comment --comment "globaleaks" -A OUTPUT -m state --state RELATED,ESTABLISHED -m owner --uid-owner globaleaks -j ACCEPT
         ip6tables -m comment --comment "globaleaks" -A OUTPUT -m state --state RELATED,ESTABLISHED -m owner --uid-owner globaleaks -j ACCEPT
 
@@ -170,6 +170,13 @@
     iptables -m comment --comment "globaleaks" -t filter -A OUTPUT ! -o lo -m owner --uid-owner ${USERNAME} -j DROP
     ip6tables -m comment --comment "globaleaks" -t filter -A OUTPUT ! -o lo -m owner --uid-owner ${USERNAME} -j DROP
 
+    # Allow redirected ports on the filter table INPUT chain
+    iptables -m comment --comment "globaleaks" -t filter -A INPUT -p tcp --dport 8080 -j ACCEPT
+    ip6tables -m comment --comment "globaleaks" -t filter -A INPUT -p tcp --dport 8080 -j ACCEPT
+
+    iptables -m comment --comment "globaleaks" -t filter -A INPUT -p tcp --dport 8443 -j ACCEPT
+    ip6tables -m comment --comment "globaleaks" -t filter -A INPUT -p tcp --dport 8443 -j ACCEPT
+
     log_action_end_msg 0
 }
 
```

**Comment by evilaliv3** [comment]
It makes sense. This will enable who has a policy that is drop by default to automatically open it.

I wonder why it was working for you before; The process was binding on port 80 and 443 (bind that now does not exist) but your DROP rule should have blocked it anyway. What am i missing?

**Comment by simon-src** [comment]
> What am i missing?

We open port 22, 80 and 443 by default on every new instance.

https://github.com/globaleaks/GlobaLeaks/issues/3622#issuecomment-1714423151

**Comment by simon-src** [comment]
Looks good https://github.com/globaleaks/GlobaLeaks/commit/21a82df979eccdf89d07f69fd31e7f6dc93d1de6

Thanks!
