### ISSUE TITLE
Allow changing of communication tab names

### ISSUE THREAD

**Issue by TjebbeVQ** [globaleaks/GlobaLeaks#3629]
### Proposal

Currently the communication tabs for recipients are: "Public" / "Internal" / "Personal".

Could these fields be added to the text customization wizard? So we can change the fields our selves?

### Motivation and context

Mostly the "Public" tab seems to have the wrong connotation to most of our recipients, thinking when they use this tab the communication is Public to the internet to see. (Even though it's just the whistleblower and other recipients to see)

We've had multiple clients request to have this field changed.

**Comment by evilaliv3** [comment]
Thank you @TjebbeVQ for your feedback.

More than allowing to change this, i suggest we discuss a possible better naming.

Which are the suggestions by your clients?

I include here other users that with me designed the current naming. I agree myself that Public may be confused. 

Lets see what others that were involved in the design of this feature have also suggestios: @gianlucagilardi @larrykind @giorgiofraschini @danielvaknine

**Comment by TjebbeVQ** [comment]
We were thinking in the line of:
External - Internal - Private or Personal.

But are happy to receive other suggestions.

**Comment by danielvaknine** [comment]
Completely agree, we've been hearing the same and were just about to give this suggestion.

It is primarily the "Public" one that is misunderstood.

We've received some suggestions from our clients and here are a few:

External/Everyone/Whistleblower
Internal/For case handlers
Personal/Private/Annotations (or "Private annotations", "Personal notes" or something like that)

However, it could be difficult to sum it all up in just one word... Another suggestion would therefore be to have some kind of explanation text that shows when you hover, as there currently are on symbols.

There, it could be explained more in detail who exactly sees each "tab".

E.g., when hovering over each it could say:
Public/External: "Visible by the whistleblower and all case handlers with access to the case"
Internal: "Visible only be the case handlers with access to the case"
Private/Personal: "Visible only to you and no one else"

**Comment by giorgiofraschini** [comment]
I agree with External/Internal/Personal

**Comment by evilaliv3** [comment]
Thank you all.

Are you sure External do not have the same misunderstanding of Public?
In english i would have preferred the proposal of "Everyone" but if not translated correctly it may be very deceiving may be deceiving as well so also for me at the moment i consider that the best option we have is "External"

**Comment by gianlucagilardi** [comment]
Well, a possibility could be:
External/recipients/me

it's difficult to be clearer than this (apart from "everyone" which I agree would be the best fit) IMHO :D

**Comment by giorgiofraschini** [comment]
I agree with Gianluca

**Comment by evilaliv3** [comment]
@danielvaknine "Whistleblower & recipients" asctually is difficult to be translated, the strig as a whole does not exists.

@susannaferro proposes:
- Whistleblower
- Recipients
- Personal

would this work for you all ?

**Comment by danielvaknine** [comment]
"Whistleblower" could mean only to the whistleblower too, but it is still better than "Public"!

With the alternatives you proposed, one could just merge "Whistleblower" and "Recipients" to create a "whistleblower & recipients" (just adding a "&" between the translated strings)

**Comment by evilaliv3** [comment]
If we want to have Whistleblower & Recipients we need forcefully to put in translation "Whistleblower &  Receipients" because grammar changes in languages so composing a string from two indepentent translations would not work at all 

Given the two options:
1. "External | Internal | Personal"
2. "All | Recipients only | Only me" ?

What would you all prefer ?

**Comment by danielvaknine** [comment]
I think alternative 2 is a very interesting one!

**Comment by gianlucagilardi** [comment]
> If we want to have Whistleblower & Recipients we need forcefully to put in translation "Whistleblower & Receipients" because grammar changes in languages so composing a string from two indepentent translations would not work at all
> 
> Given the two options:
> 
> 1. "External | Internal | Personal"
> 2. "All | Recipients only | Only me" ?
> 
> What would you all prefer ?

I'd vote for option 2 by a long shot :)

**Comment by evilaliv3** [comment]
If you think the option 2 translated in your own language, do you think it would be nice?

**Comment by danielvaknine** [comment]
Sounds OK in Swedish!

**Comment by evilaliv3** [comment]
For sure to translators we should say: "All" referred to users for example, because the translations can be different in reference to objects.

**Comment by evilaliv3** [comment]
This issue can be solved using "Everyone" in place of all.

**Comment by gianlucagilardi** [comment]
> This issue can be solved using "Everyone" in place of all.

I understood that this option was off the table.... If this is not the case, "everyone" would be perfect

**Comment by danielvaknine** [comment]
We've received feedback that it still feels unclear which is which and what they do... 

Perhaps we could explore having a hover-explanation text or something like that?

**Comment by evilaliv3** [comment]
This is definitely a possibility.

With the next version we are shipping out the revised text so to test the general user reaction.
