### ISSUE TITLE
Can't open "Reports"

### ISSUE THREAD

**Issue by eresegame** [globaleaks/GlobaLeaks#3637]
### What version of GlobaLeaks are you using?

Clicking on "reports" voice on receiver menu we get an error 

"Error!
Internal server 
error (Unexpected)"

And so we receive an error by mail (attached).

We are starting with whistlebolwing, so we tryed to reinstall debian an so the Globaleaks but the error is the same.

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Platform: whistleblowing.maioranaspa.it
Host: whistleblowing.maioranaspa.it (ewf6mchdmhwomoht4plzmij6bc7j3rk7z7ygjruwjajtzlaggihlseqd.onion)
Version: 4.13.10

OverflowError Result too large to be represented.

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 244, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
             ^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/threadpool.py", line 260, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 117, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 82, in callWithContext
    return func(*args, **kw)
           ^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/globaleaks/orm.py", line 185, in _wrap
    result = function(session, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3/dist-packages/globaleaks/handlers/recipient/__init__.py", line 37, in get_receivertips
    updated_before = datetime.fromtimestamp(int(args.get(b'updated_before', [b'32503680000'])[0]))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

OverflowError: timestamp out of range for platform time_t

**Comment by evilaliv3** [comment]
Thank you for reporting this;

Have you changes operating system or server? Which are the details of the previous and current setup?

**Comment by eresegame** [comment]
The same S.O., Debian 12

**Comment by evilaliv3** [comment]
This is pretty strange actually; we will try to undertand better.

**Comment by eresegame** [comment]
I install Debian 12 on VmWare VM, only one partition, using debian-12.1.0-i386-netinst.iso
So I put it in DMZ, publicated with the same ip used by public dns "whistleblowing.maioranaspa.it".
In setup wizard i create a WBAdmin as receiver of the report, i used the same my email for the admin and the WBAdmin.
So when i try to send a report, we receive the e.mail notification, the link open the case and it is all right.
But if I Sign-in as WBAdmin and click on "reports" i get the error.
Something to check ?

**Comment by evilaliv3** [comment]
I'm thinking this could be related to i386 instead of 64bits, but i will confirm doing some tests.

Is this a new setup or a setup updated?

**Comment by evilaliv3** [comment]
Would you please give it a try? Thank you

**Comment by eresegame** [comment]
Yes, which iso you sugguest ?
intel (Intel(R) Xeon(R) CPU E5-2660 v3 @ 2.60GHz), using Esxi 7.0.3
On VmWare i can select Debian 11 64bit (12 is not in list)

**Comment by eresegame** [comment]
Ok, i am downloading amd64

**Comment by evilaliv3** [comment]
@eresegame: do you have any update?

**Comment by eresegame** [comment]
> @eresegame: do you have any update?

sorry for the late update, i was lost the link.
Yes i fixed, the IOS version was the problem

**Comment by evilaliv3** [comment]
IOS ?

**Comment by eresegame** [comment]
Debian I386 vs amd64
Just another question, if i have more than one receipt, how can let them receive the notification and visibility on new case ?
Now only the WBAdmin view the tickets.

**Comment by evilaliv3** [comment]
Thank you. So it is very likely that the software currently works only on 64bit architectures.

In relation to the second question (please use Discussion for questions and please keep topics separated) you need to add your recipient to the reporting channel.

**Comment by evilaliv3** [comment]
Closing as stale ticket. Please feel free to re-open it if you need assistance.
