### ISSUE TITLE
Update from 4.13.9 > 4.13.10 loss of complaints

### ISSUE THREAD

**Issue by n9898** [globaleaks/GlobaLeaks#3640]
### What version of GlobaLeaks are you using?

I initially installed version 4.13.9 but I received an email two days ago or so about the possible update to 4.13.10

Obviously I wasn't going to leave globaleaks without updating, I'm still new to this.

### What browser(s) are you seeing the problem on?

Tor Browser, Other

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

I decided to update version 4.13.9 to 4.13.10, look how to do it on the official website and did it.
I first made a backup of version 4.3.9 and proceeded to update according to the instructions on the official website.

I updated successfully, everything looks perfect and the previously created users, accounts and questions still exist.
My problem starts when I log into the recipient's account to check that everything is working correctly there as well.
And the complaints that previously appeared in version 4.13.9 are gone. They all disappeared after the update.

I wanted to know how I can recover these complaints from the previous version so I can see them in the new version 4.13.10, where am I supposed to save them? Does it do it through the database or in some directory and encrypt the content? If so, which one is it?

Thank you

**Comment by evilaliv3** [comment]
Thank you @n9898 

In the ticket you mention both 4.3.9 and 4.13.9, would you please clarify which version where you running before updating from 4.13.9?

In my opinion if you where updating from 4.3.9 to 4.13.9 and you are not viewing the reports this issue can be just cosmetic.
If it possible that you have disabled some channel recently?

I suggest you to access the Audit Log as admin  and check the Report section; if reports are there it is confirmed that the bug is only cosmetic.

Thank you if you could confirm this.

In any case then, if you have the backup from version 4.3.9 for the moment you may simply restore it while we understand with you what did not work.

**Comment by n9898** [comment]
Thanks for answering @evilaliv3 .
I installed globaleaks in version 4.13.9 and updated two days ago to version 4.3.10. 

Yes, it was possible that I deleted a channel recently but I think the complaints were still there anyway, although I'm not 100% sure.

This is all the log I have in the audit log tab

Presentation date | Type | Severity | User | Object
-- | -- | -- | -- | --
20-09-2023 08:54 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
18-09-2023 11:29 | login | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 |  
18-09-2023 11:28 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
18-09-2023 10:43 | login | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 |  
18-09-2023 10:43 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
18-09-2023 09:44 | login | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 |  
18-09-2023 09:11 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
18-09-2023 09:11 | version_update | 0 | system |  
18-09-2023 09:05 | logout | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
18-09-2023 09:03 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
15-09-2023 17:14 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
15-09-2023 17:13 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
15-09-2023 16:52 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
15-09-2023 16:33 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
15-09-2023 15:03 | whistleblower_login | 0 |   |  
15-09-2023 15:02 | whistleblower_new_report | 0 |   |  
15-09-2023 15:01 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | 9086847c-fc01-4cd7-a1f1-e82698d8c701
15-09-2023 15:01 | update_report_status | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | 9086847c-fc01-4cd7-a1f1-e82698d8c701
15-09-2023 15:01 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | 9086847c-fc01-4cd7-a1f1-e82698d8c701
15-09-2023 15:00 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | 9086847c-fc01-4cd7-a1f1-e82698d8c701
15-09-2023 15:00 | update_report_status | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | 9086847c-fc01-4cd7-a1f1-e82698d8c701
15-09-2023 14:50 | login | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 |  
15-09-2023 14:49 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
15-09-2023 13:47 | whistleblower_new_report | 0 |   |  
15-09-2023 13:31 | login | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 |  
15-09-2023 13:30 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
15-09-2023 13:29 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:29 | update_report_status | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:28 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:28 | update_report_status | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:28 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:28 | update_report_status | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:28 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:28 | update_report_status | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:28 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:28 | update_report_status | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:28 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:28 | update_report_status | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:28 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:27 | update_report_status | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:27 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:27 | update_report_status | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:27 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:18 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | d68120f8-395b-4bce-8c9a-ccd07f240348
15-09-2023 13:18 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:18 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 13:17 | login | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 |  
15-09-2023 13:15 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
15-09-2023 12:53 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
15-09-2023 12:53 | login | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 |  
15-09-2023 11:47 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | d68120f8-395b-4bce-8c9a-ccd07f240348
15-09-2023 11:43 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | d68120f8-395b-4bce-8c9a-ccd07f240348
15-09-2023 11:43 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | d68120f8-395b-4bce-8c9a-ccd07f240348
15-09-2023 11:43 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
15-09-2023 11:43 | login | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 |  
15-09-2023 11:43 | logout | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 |  
15-09-2023 11:37 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 11:32 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | d68120f8-395b-4bce-8c9a-ccd07f240348
15-09-2023 11:31 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 11:31 | update_report_status | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | bdb2d8d3-c215-4f4c-afc9-b3185449ee79
15-09-2023 11:29 | whistleblower_new_report | 0 |   |  
15-09-2023 11:24 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | d68120f8-395b-4bce-8c9a-ccd07f240348
15-09-2023 11:22 | whistleblower_login | 0 |   |  
15-09-2023 11:22 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | d68120f8-395b-4bce-8c9a-ccd07f240348
15-09-2023 11:22 | update_report_status | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | d68120f8-395b-4bce-8c9a-ccd07f240348
15-09-2023 11:22 | whistleblower_login | 0 |   |  
15-09-2023 11:21 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | d68120f8-395b-4bce-8c9a-ccd07f240348
15-09-2023 11:20 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | d68120f8-395b-4bce-8c9a-ccd07f240348
15-09-2023 11:19 | whistleblower_login | 0 |   |  
15-09-2023 11:19 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | d68120f8-395b-4bce-8c9a-ccd07f240348
15-09-2023 11:18 | access_report | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | d68120f8-395b-4bce-8c9a-ccd07f240348
15-09-2023 11:18 | update_report_status | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 | d68120f8-395b-4bce-8c9a-ccd07f240348
15-09-2023 11:17 | login | 0 | a18437ce-ad21-43a0-b32c-118a0dd85751 |  
15-09-2023 11:17 | logout | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
15-09-2023 11:08 | whistleblower_login | 0 |   |  
15-09-2023 11:08 | whistleblower_new_report | 0 |   |  
15-09-2023 11:06 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
15-09-2023 10:10 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
15-09-2023 09:09 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb |  
14-09-2023 16:56 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb
14-09-2023 16:52 | login | 0 | 0f997622-61a4-499b-a6fe-a68baf1097cb

There is no type of record in the complaints tab.

![Captura de pantalla 2023-09-20 090503](https://github.com/globaleaks/GlobaLeaks/assets/145135665/6af09d31-004a-4aa0-b1d6-0e26d89323e1)

As you can see after this line 09-18-2023 09:11 version_update 0 system, which was when I updated from version 4.13.9 to 4.13.10, all the complaints I had disappeared.

**Comment by n9898** [comment]
I expand my information, I have a channel called complaints 2. I took the questionnaire on said channel and I already received the supposed complaint from the administrator.

<img width="940" alt="image" src="https://github.com/globaleaks/GlobaLeaks/assets/145135665/245e3214-a62c-4417-b63a-fdd3c94ec1cc">

I verify that said complaint is in the audit record tab and in turn in the complaints tab.

<img width="795" alt="image" src="https://github.com/globaleaks/GlobaLeaks/assets/145135665/92394b37-34f9-42c9-9f14-918399a6b7f4">

<img width="953" alt="image" src="https://github.com/globaleaks/GlobaLeaks/assets/145135665/e983fc93-4fd5-486e-a899-8dd372c9511f">

I proceed to delete the denunica channel 2 as attached in the image. It is found that it no longer exists

![image](https://github.com/globaleaks/GlobaLeaks/assets/145135665/16fd8973-4334-4abb-a637-b4c7c70ade21)

And entering the audit record tab again and in turn the complaints tab. Said complaint that had previously been created disappears.
So I understand that my update from version 4.3.9 to 4.3.10 has nothing to do with the loss of my complaints.
If not, the culprit was the elimination of a channel that had previously been created and where were these complaints made?

**Comment by n9898** [comment]
Thanks for responding I restored my backup from version 4.13.9

Follow the steps it says on the website:
be sure globaleaks is not running; globaleaks can be shut down with “service globaleaks stop”;
identify the version of globaleaks required for restoring globaleaks. the version is written in the backup filename;
extract the content of the archive in /var/globaleaks with the command tar -zxvf backup.tar.gz
install the required version of globaleaks with: apt-get install globaleaks=version (e.g. globaleaks=3)

But when I got to the last version I didn't understand it very well and it gave me the following error.
![image](https://github.com/globaleaks/GlobaLeaks/assets/145135665/421fceb8-4870-41c4-8e53-f2c69699c8fd)

**Comment by n9898** [comment]
Thank you @evilaliv3 

This worked for me now I have version 4.13.11 and it seems that the page works without problems and the complaints that I had in version 4.13.10 are still there.
With the conclusion that the update did not delete anything and it was a bad practice of mine to delete a channel.

**Comment by evilaliv3** [comment]
Thank you for this update @n9898
