### ISSUE TITLE
i can not report a file : unable to deliver the submission to least one recipient since update to 4.13.11

### ISSUE THREAD

**Issue by eikman2k** [globaleaks/GlobaLeaks#3664]
### What version of GlobaLeaks are you using?

4.13.11

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

macOS

### Describe the issue

I can not report a file 

I alway get the Failure: **unable to deliver the submission to least one recipient**

I installed the Version 4.13.x before, there it was possible to report file, then i updated to the newest version after the Info Mail from Globaleaks.
After the update i created a new Site and in this site i get this Failure, i installed several Time new, and now the First Site is even not able to sen a report file!

### Proposed solution

i have no Idea, installed everything new

**Comment by evilaliv3** [comment]
Hello @eikman2k 

thank you for your question.

Actually i think you may have forgot to assign at least one recipient to your reporting channels.

Add at least one recipient to any channel to resolve the issue.

**Comment by eikman2k** [comment]
THX a lot!
My fault!
