### ISSUE TITLE
Report export in English instead of recipient default language.

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3670]
### What version of GlobaLeaks are you using?

4.13.11

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Save report saves in English instead of recipient default language.
The recipient environment is set in Greek however the txt file saves in English (questionnaire).
Does this have to do with the report language or is this a bug?

### Proposed solution

I would expect the save language to be the env language of the recipient.

**Comment by elbill** [comment]
The solution is that the browser display settings should be in the desired language for export.

**Comment by evilaliv3** [comment]
Thank you @elbill 

Would you please clarify what you mean with "browser display settings" ?

**Comment by elbill** [comment]
In browser settings (example from chrome)

**Preferred languages**
Websites will show content in your preferred languages, when possible
1. English (United States)
This language is used to display the Google Chrome UI

(change that to your desired language for export)

![Settings - Languages - Google Chrome 9_11_2023 1_50_09 μμ](https://github.com/globaleaks/GlobaLeaks/assets/23246886/63c14db1-f20f-4118-adc9-11ca14e92315)
