### ISSUE TITLE
email change link returns error

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3674]
### What version of GlobaLeaks are you using?

4.13.12

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

When a password change is issued by a user in the preferences page, the link in the verification email doesn't work and comes with this error:
`{"error_message": "Resource not found", "error_code": 6, "arguments": []}`

### Proposed solution

pw change link shoud drive to a password change interface

**Comment by evilaliv3** [comment]
Thank you @larrykind ; will look into this and ensure it is fixed

**Comment by evilaliv3** [comment]
Fixed @larrykind ! Thank you!
