### ISSUE TITLE
Update/change log version showing wrong in 4.13.12

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3682]
### What version of GlobaLeaks are you using?

4.13.12

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

The update log/version log is showing that update is avaliable even after update.

![mstsc_iWDWzgfL2X](https://github.com/globaleaks/GlobaLeaks/assets/70965554/ac85e37e-b965-4cc6-a527-da8adb8aa5f3)

![5SNVsuo2Qi](https://github.com/globaleaks/GlobaLeaks/assets/70965554/ea762c3f-f0cf-4e12-a3b7-2abe3ace502a)

![E4rexluqmO](https://github.com/globaleaks/GlobaLeaks/assets/70965554/160a6086-d6ed-4683-91e5-8a7062adbc91)

As shown in the last picture - backup states, that he version is 4.13.12

**Comment by itasterix** [comment]
I'm having the same problem too!
I'm becaming crazy trying to understand what's wrong, then I read here.

**Comment by flashlight4** [comment]
Same with me.

Server
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         40 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  1
  On-line CPU(s) list:   0
Vendor ID:               GenuineIntel
  Model name:            Intel Xeon Processor (Skylake, IBRS)
    CPU family:          6
    Model:               85
    Thread(s) per core:  1
    Core(s) per socket:  1
    Socket(s):           1
    Stepping:            4

lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

Browser: Safari an Firefox Developer Edition (both latest version)

Client OS: Windows 11 and Mac OS Sonoma

Rebooting as well restarting the service globaleaks shows no effect.

**Comment by evilaliv3** [comment]
Thank you; this is a know just visual issue that we were considering to fix just at the next release opportunity.

As it seems to be confusing users we will issue a new release just to fix this visual issue.

**Comment by evilaliv3** [comment]
Fixed!
