### ISSUE TITLE
Wrong hompage in package description

### ISSUE THREAD

**Issue by flashlight4** [globaleaks/GlobaLeaks#3685]
### What version of GlobaLeaks are you using?

4.13.12

### What browser(s) are you seeing the problem on?

Other

### What operating system(s) are you seeing the problem on?

macOS

### Describe the issue

Due to the shell command 'dpkg -s globaleaks' the information of the installed package is presented. 

Actually it shows like this on Ubuntu 22.04:

Package: globaleaks
Status: install ok installed
Priority: optional
Section: web
Installed-Size: 87176
Maintainer: Giovanni Pellerano <giovanni.pellerano@globaleaks.org>
Architecture: all
Version: 4.13.12
Depends: python3:any, adduser, apparmor, apparmor-utils, gnupg, iptables, lsb-base, python3-acme, python3-debian, python3-cryptography, python3-h2, python3-nacl, python3-openssl, python3-gnupg, python3-priority, python3-pyotp, python3-sqlalchemy, python3-twisted, python3-txtorcon, tor
Conffiles:
 /etc/apparmor.d/usr.bin.globaleaks 42cc8bb81a4ff0706a6e7635b8cd5e56
 /etc/default/globaleaks 753092d375c0453441385ff18f364856
 /etc/init.d/globaleaks 436f0388680721cfe13dbfd069ce9f41
Description: Free and open-source whistleblowing software
 GlobaLeaks is free, open source software enabling anyone to easily set up and
 maintain a secure whistleblowing platform
Homepage: **https://www.globleaks.org/**

### Proposed solution

As a minor issue I like to recommend to correct the Homepage from www.globleaks.org to www.globaleaks.org

**Comment by evilaliv3** [comment]
oh, thank you! no one actually noticed this!

will be fixed in next release

**Comment by evilaliv3** [comment]
Fixed! Thank you again @flashlight4
