### ISSUE TITLE
Default questionnaire (different from GLOBALEAKS) is not selected in a new report

### ISSUE THREAD

**Issue by Hooteo** [globaleaks/GlobaLeaks#3688]
### What version of GlobaLeaks are you using?

4.13.12

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### Describe the issue

I created a new questionnaire and i want it to be the default on on new reports.
In Settings -> Advanced -> Default questionnaire i've already selected the new one:
![image](https://github.com/globaleaks/GlobaLeaks/assets/17424781/33fc6fe1-e513-4fdc-bc4e-b5e940b2363a)

The questionnaire has 2 new questions:
![image](https://github.com/globaleaks/GlobaLeaks/assets/17424781/59920013-0f3f-4354-842f-07a8b13bff02)
![image](https://github.com/globaleaks/GlobaLeaks/assets/17424781/cb4b8043-3999-4926-abcb-db0604d778d2)

When i try to create a new report i still have the default GLOBALEAKS:
![image](https://github.com/globaleaks/GlobaLeaks/assets/17424781/d704eeb1-a67d-44d9-a84d-4df906f48149)

I already restarted the server 2 times and the service globaleaks.
I really don't know how to fix this issue

**Comment by evilaliv3** [comment]
Hello @Hooteo, actually the default questionnaire that you configured has a different reason.

To do what you are trying to achieve you should change the questionnaire associated to your reporting channel.
This should be done in the "Channels" section
