### ISSUE TITLE
Cannot download uploaded files from cases (cases prior june 2023)

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3696]
### What version of GlobaLeaks are you using?

4.13.13

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

When trying to download the file, the users gets an "InternalServerError"

![image](https://github.com/globaleaks/GlobaLeaks/assets/70965554/bf60e7ea-1786-4c5b-b9e7-89cde7a07483)

I've attached the log from the "parent site"
[globaleaks (8).log](https://github.com/globaleaks/GlobaLeaks/files/12869905/globaleaks.8.log)

**Comment by evilaliv3** [comment]
Closing as duplicate.

Problem first reported on ticket: https://github.com/globaleaks/GlobaLeaks/issues/3606

Available solutions described in comment: https://github.com/globaleaks/GlobaLeaks/issues/3606#issuecomment-1706685069
