### ISSUE TITLE
Whistleblowing - GlobaLeaks Exception

### ISSUE THREAD

**Issue by garc-dev** [globaleaks/GlobaLeaks#3698]
### What version of GlobaLeaks are you using?

4.13.13

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Dopo installazione ultima versione, riceviamo dal server WB continui messaggi di questo tipo:
Platform: GARC Whistleblowing
Host: whistleblowing.garcspa.it (toluhacoehpm37j3zidynittsazk5hc6asz3ffvrwbx6zz3wprveuead.onion)
Version: 4.13.13

twisted.web._newclient.ResponseNeverReceived 
    A L{ResponseFailed} that knows no response bytes at all have been received.
    

Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/globaleaks/jobs/job.py", line 49, in run
    yield self.operation()

twisted.web._newclient.ResponseNeverReceived: [<twisted.python.failure.Failure OpenSSL.SSL.Error: [('SSL routines', '', 'unexpected eof while reading')]>]

### Proposed solution

risposta a m.garutti@garcspa.it
Grazie

**Comment by gianlucagilardi** [comment]
Not really troublesome, there have been some network issues and your instance failed to check if there was any new release of the software. Actually harmless albeit annoying :)

---- ITA
Non e' sostanzialmente problematico. Ci sono stati dei problemi di connettività lato server che ospita la deb repository e la tua istanza non e' riuscita a verificare se ci sono aggiornamenti software di GL. Innocuo anche se fastidioso :)

**Comment by evilaliv3** [comment]
I confirm what wrote by @gianlucagilardi 

We may in the future silence exceptions like these; for the moment we are not silencing exceptions in order to well improve the platform over the time

**Comment by garc-dev** [comment]
Excellent. Nice to keep updated your platform and contrib to reports for improvements.

**Comment by evilaliv3** [comment]
Issue resolved; it was caused by a wrong configuration on our secondary firewall.
