### ISSUE TITLE
Error update from 4.10.18 to 4.13.13

### ISSUE THREAD

**Issue by RDLRA** [globaleaks/GlobaLeaks#3700]
### What version of GlobaLeaks are you using?

current version 4.10.18 behind nginx reverse proxy

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

current configuration
![image](https://github.com/globaleaks/GlobaLeaks/assets/49749704/3369ff68-9bc9-4de7-bca1-162dfe11c38b)
behind reverse proxy not error
performed update from 4.10.18 as manual to 4.13.13

First error loop redirect  behind reverse

restore version 4.10.18 and delete hostname configuration
performed update 
error visit public url 404

**Comment by evilaliv3** [comment]
@RDLRA: Latest release enforce HTTPS.

Ensure to update your proxy configuration and point the proxy to port 8443.

**Comment by RDLRA** [comment]
thanks, resolved
