### ISSUE TITLE
Could not connect to deb.globaleaks.org

### ISSUE THREAD

**Issue by alexspanos-wide** [globaleaks/GlobaLeaks#3701]
### What version of GlobaLeaks are you using?

4.13.13

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

We keep getting this error during the installation process 
Failed to fetch http://deb.globaleaks.org/jammy/globaleaks_4.13.13_all.deb  Could not connect to deb.globaleaks.org:80 (95.174.23.119), connection timed out
the error is on Ubuntu 22 server

**Comment by gianlucagilardi** [comment]
see https://github.com/globaleaks/GlobaLeaks/issues/3698

**Comment by evilaliv3** [comment]
Issue resolved; it was caused by a wrong configuration on our secondary firewall.
