### ISSUE TITLE
Custom CSS in a multi site environment does not work for the admin area of sub-sites

### ISSUE THREAD

**Issue by csageder** [globaleaks/GlobaLeaks#3706]
### What version of GlobaLeaks are you using?

4.13.14

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### Describe the issue

I have a multi-site environment where the main page is for administration only. When I upload a custom CSS for the main page, it is used as expected for the main page on the administration page. 

Now if I add an sub site, the new site has the default GlobaLeaks style, no problem with that. 

Now when I add a CSS style to the new sub site, that style is used for the "client" part of the sub-site, so the reporting has the style, but the admin area still uses the GlobaLeaks style. 

### Proposed solution

I would expect either that the style of the main site is used for the adminstration or the custom style of the sub site itself.

**Comment by evilaliv3** [comment]
Hello @csageder 

Which domain are you using to access the sub-site? If you are accessing it directly via the management site the CSS wont be loaded for a matter of securirty.

**Comment by csageder** [comment]
Thanks, for the information, I am accessing the sub-site through the tenant managment /t/.. so through the main domain. I do not know understand why the CSS of the main site isn't used for security reason as this CSS is used for the main page already, but I am no security expert.

I close the issue, as the behaviour is by design and not a bug
