### ISSUE TITLE
Improve interface responsiveness by pre-loading all submission's data

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#371]
Improve interface responsiveness by pre-loading all submission's data .

When the user must apply a submission he:
- first load main page
- click blow the whistle
- submission page is shown (empty)
- loading window popup
- submission data get downloaded (receivers, context, etc) 
- submission interface is show up loaded

This ticket is to improve the interface responsiveness by pre-loading all elements needed to approach a submission (context, receivers, receivers images) while at the main page.

That way the WB does not need to wait for submission interface loading, when he click "Blow the Whistle" .
##

**Comment by evilaliv3** [comment]
Closing as really outdated. The /public API assolve all the current needs of optimization.
