### ISSUE TITLE
Error updating the identity in a report already submitted

### ISSUE THREAD

**Issue by SilviaDL** [globaleaks/GlobaLeaks#3710]
### What version of GlobaLeaks are you using?

4.13.14

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

During testing, there is an error when I try to enter personal data into a report I submitted anonymously.
The user should be able to enter their data even if they have previously submitted an anonymous report.
On the report detail page, the section "Do you want to provide your identification data?" does not allow modification because the form is not complete and the "submit" button does not work.

Attached is the photo showing the missing forms. The "submit" button doesn't work.
![errore_aggiungiIdentità](https://github.com/globaleaks/GlobaLeaks/assets/6919099/149f826e-1daf-4d3b-a26f-e92625a2cde0)

**Comment by evilaliv3** [comment]
Hello @SilviaDL; i do not see part of the interface.
Maybe you tried to hide some parts with CSS causing this failure?

**Comment by SilviaDL** [comment]
Ciao, 
Ho appena replicato l'errore facendo una segnalazione anonima ed entrando nel dettaglio della segnalazione appena effettuata.
Ho verificato nella sezione "allegati" delle impostazioni, non ho nessun css o javascript custom.
Allego uno screen che evidenzia la console nei browser Chrome e Edge (non so se può essere di aiuto).

![errore form identità](https://github.com/globaleaks/GlobaLeaks/assets/6919099/cea14311-f82a-4c21-8750-36daa1a17da9)
![errore form identità_edge](https://github.com/globaleaks/GlobaLeaks/assets/6919099/9206ca05-4de1-41d4-a9eb-f9e19dbdec46)

**Comment by evilaliv3** [comment]
Grazie

Provvediamo a verificare.

Che versione del software state utilizzando?

**Comment by SilviaDL** [comment]
versione 4.13.14

Sempre in questa versione sto riscontrando problemi nella pagina di dettaglio della segnalazione lato ricevente.
Preferite che apro due nuove segnalazione oppure mando le informazioni sempre in questo thread?

**Comment by evilaliv3** [comment]
Se possibile apra sempre ticket diversi e specifici, grazie

**Comment by SilviaDL** [comment]
Ciao,
Ho fatto una nuova installazione e la problematica non si è ripresentata.
le configurazioni sono le stesse, probabilmente qualcosa nell'installazione sull'ambiente non era andata a buon fine.

Grazie ancora per il supporto.
Chiudo la segnalazione.

**Comment by evilaliv3** [comment]
Grazie a lei per l'aggiornamento
