### ISSUE TITLE
cannot load the Logo

### ISSUE THREAD

**Issue by Giosafatv** [globaleaks/GlobaLeaks#3711]
### What version of GlobaLeaks are you using?

4.13.14

### What browser(s) are you seeing the problem on?

Tor Browser, Firefox

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Cannot load the Logo, after clicking "edit" a  not working semi-tranparent page is open but I cannot load any image.
Thanks for help

![Cattura](https://github.com/globaleaks/GlobaLeaks/assets/148575543/37db933f-b88a-4232-8988-75d257ff6b4e)

**Comment by evilaliv3** [comment]
Thank you for reporting this.

This seems to be a specific bug happening on the Tor browser. We will retest this soon.

**Comment by Giosafatv** [comment]
by accessing the Debian machine from outside where globaleaks is installed the problem does not occur, so having this workaround for me the problem is solved
Many Thanks
Giosafat

**Comment by evilaliv3** [comment]
Thank you; i'm going to close the ticket because anyhow i'm not able to reproduce it,

From what i see in general the Tor browser seems it was not loading correctly.
