### ISSUE TITLE
Voice message preview not usable from smartphone

### ISSUE THREAD

**Issue by marcomeneghin** [globaleaks/GlobaLeaks#3712]
### What version of GlobaLeaks are you using?

Versione del software: 4.13.14

![21-10-2023 17-46-18](https://github.com/globaleaks/GlobaLeaks/assets/131891399/1b31b168-f337-471e-bf93-ffd1fe5fd530)

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Android

### Describe the issue

Using site from smartphone: the preview box is too small and even by clicking on the three dots the menu appears all the way to the left and you can't see anything, so listening to the message again is difficult (you have to rotate the smartphone). I tried to set the field width in the questionnaire properties but the system accepts values up to 10 and in any case the substance does not change.

**Comment by evilaliv3** [comment]
Closing as addressed.
