### ISSUE TITLE
Only 3 users can be added to a case

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#3720]
### What version of GlobaLeaks are you using?

4.13.13

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

When trying to add a "sleeping user", it is only possible to see 3 users - seems like all subsequent users are omitted, and last added user is being removed.

**Comment by schris-dk** [comment]
Found the cause. Not all users had been logged in for the first time, which caused the error. The users were all visible in the drop-down, which might be confusing, as they cannot be added before they have logged in first time :-)

**Comment by evilaliv3** [comment]
Thank you @schris-dk  for this update. Closing the ticket then.
