### ISSUE TITLE
apt-key deprecation warning when updating with apt

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3723]
### What version of GlobaLeaks are you using?

4.13.15

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

on debian 12, when updating GL repository with apt, there is a deprecation message:

`http://deb.globaleaks.org/bullseye/Release.gpg: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.`

### Proposed solution

solution is to manually copy the apt keyring, something like:

`cp /etc/apt/trusted.gpg /etc/apt/trusted.gpg.d`

but a refactoring should be better.

**Comment by larrykind** [comment]
if this is left for compatibility purposes, it's ok.

**Comment by evilaliv3** [comment]
Thank you @larrykind 

I've updated our install script to follow the recommended best procedure.
