### ISSUE TITLE
GlobaLeaks overrides Apache virtual hosts

### ISSUE THREAD

**Issue by AlainL88** [globaleaks/GlobaLeaks#3728]
### What version of GlobaLeaks are you using?

4.13.15

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

When GlobaLeaks is running, the domain configured in the server open GlobaLeaks platform and all subdomains are broken.
Is there any way to install GlobaLeaks on a subdomain running multiple site on the same server with one IP address only?

**Comment by evilaliv3** [comment]
Hello Alain,

If i understand correctly you are running GlobaLeaks on the same server on wich you are running other sites.

GlobaLeaks requires a dedicated VPS.

**Comment by AlainL88** [comment]
Clear. Will it be changed in the future? Can I suggest as a future improvement?

**Comment by evilaliv3** [comment]
For reasons of threat modeling we consider that globaleaks requires at
least a virtual private server so I do not thinking on this aspect so much
could vary.

> Message ID: ***@***.***>
>

Please feel free to open tickets for any requirements improvement you would
like to suggest or to provide code improvements directly.

**Comment by AlainL88** [comment]
I understand. Thanks
