### ISSUE TITLE
Make it possible for whistleblowers to listen to their own audio recordings

### ISSUE THREAD

**Issue by Giosafatv** [globaleaks/GlobaLeaks#3736]
### Proposal

Could it be possible for the whistleblower who accesses a previous report via the 16-digit code to listen to the previously recorded message again? Or does this make no sense?

### Motivation and context

the whistleblower who wants to add additional information or read a response from the recipient may need to listen to the message again

**Comment by evilaliv3** [comment]
Hello @Giosafatv 

Thank you for your feedback.

We will be rolling out this feature soon.

**Comment by Giosafatv** [comment]
Hi, I'm experiencing that since the last update the recently implemented functionality no longer works, is it my problem or do you also have the same behavior?

**Comment by eleibr** [comment]
Hi @Giosafatv  I confirm that is not working: the whistleblower cannot listen to his own recording.

**Comment by evilaliv3** [comment]
Thank you, i will retest the feature with the current version and update the ticket.

**Comment by eleibr** [comment]
Hi @evilaliv3, I've just tested the audio recording in the version 4.14.3 and I confirm that the whistleblower is now able to listen to his own recording.
Thanks
