### ISSUE TITLE
Attachments are not deleted from the storage system

### ISSUE THREAD

**Issue by vjfernan** [globaleaks/GlobaLeaks#3748]
### What version of GlobaLeaks are you using?

v.4.13.16

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

When I delete a report with attachments, the files remain on the server's storage system and are not deleted.

### Proposed solution

When I delete a report the attachments in /var/globaleaks/attachments should be deleted.

**Comment by evilaliv3** [comment]
@vjfernan: there is a job that deletes files after five minutes since they are disconnected from the database.

Would you please wait 5 minutes and see if it works correctly?

**Comment by vjfernan** [comment]
Yes, I deleted the report more than 5 minutes ago and the attachments are still on the server.

**Comment by evilaliv3** [comment]
This is actually quite strange @vjfernan 

We have unit tests that cover this situation and we do not see any malfunctions.

Would you please recheck?

Are you able to reproduce the issue on a new setup?

If it possible that in your setup you could have changed by mistake the permissions on the files in /var/globaleaks/attachments?

**Comment by kairos322** [comment]
Hi everyone. 

I've been reproducing the behaviour explained by @vjfernan on a fresh docker instance running on a Windows 10 machine.

![docker_logs_2023-11-05_21-43](https://github.com/globaleaks/GlobaLeaks/assets/103898474/3611f081-0326-4284-87fd-bc0178c7257f)

![scheduled_jobs-2023-11-05_21-39](https://github.com/globaleaks/GlobaLeaks/assets/103898474/b8668354-7a1f-427e-a3a3-d75c287e0ec1)

**Comment by evilaliv3** [comment]
@kairos322 @vjfernan : as explained, files are logically deleted when the user delete the report or the report expire and physically deleted as soon that the CleaningSched runs.

The cleaning sched for a matter of efficiency is run once a day and as visible in your last screenshot it was still not run. Please let me know if you have any question.

**Comment by vjfernan** [comment]
Sorry. I confirm that the deletion is correct and is performed as you comment.
