### ISSUE TITLE
Allow formatting of the text in the Disclaimer field.

### ISSUE THREAD

**Issue by vjfernan** [globaleaks/GlobaLeaks#3761]
### Proposal

The information that can be given in this field can be extensive and it would be interesting if the text could be given a certain format in order to differentiate different sections of the disclaimer.

I think allowing a few HTML tags like `<b>,` `<strong>`, `<i>` and `<h1>` to `<h6>` would be enough to give some formatting to this field and make it easier to read.

### Motivation and context

Allowing some formatting in this field would make it easier to read.

**Comment by evilaliv3** [comment]
Thank you @vjfernan 

The application supports standard markdown

Allowing HTML in general opens to many risks so it was a design choice to prevent it.
