### ISSUE TITLE
Certificate chain is incorrect

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#3763]
### What version of GlobaLeaks are you using?

Generic issue

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Hi @evilaliv3 

When certificates are installed in Globaleaks, secure connection functions as it should.
But, when using online TLS test tools as Hardenize or SSLLabs  you get this error stating that the certificate chain is incorrect, and that the site is not secure.

Here is an example where the error is found on try.globaleaks.org:
https://www.hardenize.com/report/try.globaleaks.org/1699375620#www_certs

**Comment by evilaliv3** [comment]
@aetdr:

Would you please provide a different example? The setup of our try may be broken for other reasons.

**Comment by evilaliv3** [comment]
@aetdr: the error on try.globaleaks.org was the order of the certificates that i loaded in the chain.

I've now fixed the order and this fix had to be made manually:
https://www.ssllabs.com/ssltest/analyze.html?d=try.globaleaks.org

If you would like please feel free to pass me your site and will try to identify the reason of the failure.

**Comment by evilaliv3** [comment]
@aetdr ?

**Comment by aetdr** [comment]
Hi @evilaliv3 

The issue is that, when openssl converts a pfx container to a pem file, the order of intermediate certificates get mixed where the certificate is cross signed and there are multiple validation paths.

Reordering two intermediates, fixed the issue.

Sorry for the trouble, Saw the same issue on try.globaleaks.org and assumed there was something generic to it.

**Comment by evilaliv3** [comment]
@aetdr: GlobaLeaks expects a PEM containing all the intermediate certificates in order.

I do not think we have a solution to automatically re-order them on behalf of the user. Do you think so? Eventually would it be possible for you to author a patch?

Thank you!

**Comment by aetdr** [comment]
hi @evilaliv3 

I would gladly help, but I am not much of a python coder.
Anyway, the browsers will usually reorder certificates, and users never see the warning.

**Comment by evilaliv3** [comment]
Thank you; i'm going to close the ticket as a solution do not exist and users could load cerificates in order.
