### ISSUE TITLE
Incompatibility between scoring and whistleblowing identity features

### ISSUE THREAD

**Issue by petxya** [globaleaks/GlobaLeaks#3768]
### What version of GlobaLeaks are you using?

4.13.17

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Whistleblower not to able to provide identity at a leter time. Please see attached file.
![Képernyőkép 2023-11-08 202723](https://github.com/globaleaks/GlobaLeaks/assets/33585123/e28ba855-4f24-4a9e-9dc2-563c282ebb0d)

**Comment by evilaliv3** [comment]
Thank you @petxya 

An other user (@silviaDL) reported this in a discussion: https://github.com/orgs/globaleaks/discussions/3708

Are you able to reproduce this issue on try.globaleaks.org?

**Comment by petxya** [comment]
Thank you @evilaliv3 
I am using the latest version of the software, also updated and rebooted ubuntu server.
Intrestingly, the error is not present on try.globaleaks.org. The software on your site works as expected.

Do you have any idea what might be wrong?

Best regards,
Peter

**Comment by evilaliv3** [comment]
No actually.

Is it possible for you to share me an address so that I can make a test of
submission and experience the issue?
If I'm able to see the error I should   definitely be able to fix the bug.
Thank you if you could

**Comment by petxya** [comment]
Thank you!

Of course I can give you access.

 

Here is my test enviroment:

 

URL: https://sandbox.whistleblwr.hu/#/login 

 

Administrator:

username: sbadmin

password: my(FwT,$}e[>L9J6&tE;dP

 

Client:

username: sbclient

password: Xz&N7}r^!ynY#9`3;A5[p$

**Comment by evilaliv3** [comment]
Thank you for sharing the credential @petxya 

I've retested the bug that happens in combination with the scoring feature.

I will fix it and release a bugfixed version by today.

**Comment by evilaliv3** [comment]
Fixed in release 4.13.18 @petxya !
