### ISSUE TITLE
Can not set up SSL certificates

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#3769]
### What version of GlobaLeaks are you using?

Version: 4.13.17

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

I have got a paltform that has 2 sites. For both sites whn trying to upload certificates in manual mode or automatic mode I get unexpected errors. I have creted a different site th thried and worked fine.
In manual mode the error comes when trying to upload the certificates.

**Comment by evilaliv3** [comment]
Thank you @elbill 

Unfortunately the three errors are all unrelated to issue on the certificates that you are having.

Are you able to reproduce your error on try.globaleaks.org?

**Comment by elbill** [comment]
no. Everythid seems to work fine. The sites seem to have secure connection but no certificate seems to be instaled through the platform. It is a bit complicated to explain. I will send you the domains on slack

**Comment by elbill** [comment]
the certificates worked in some way even though they were not insalled through the platform
[10:51](https://globaleaks.slack.com/archives/DS3KQFBBL/p1699476696915769)
They were installed in an older version of the platform on the same VM
[10:51](https://globaleaks.slack.com/archives/DS3KQFBBL/p1699476711238389)
with the same IP
[10:52](https://globaleaks.slack.com/archives/DS3KQFBBL/p1699476774188689)
a wildcard certificate
[10:53](https://globaleaks.slack.com/archives/DS3KQFBBL/p1699476810208919)
so when redeployed it worked but I get errors whnt trying to renew
