### ISSUE TITLE
Latest release not signed

### ISSUE THREAD

**Issue by FlokiNET** [globaleaks/GlobaLeaks#3777]
### What version of GlobaLeaks are you using?

Latest

### What browser(s) are you seeing the problem on?

Firefox

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

W: GPG error: https://deb.globaleaks.org bookworm/ Release: The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
E: The repository 'http://deb.globaleaks.org bookworm/ Release' is not signed.

**Comment by evilaliv3** [comment]
Corrected thank you @FlokiNET !
