### ISSUE TITLE
Certificate Generation and Signing Request Errors

### ISSUE THREAD

**Issue by nigeltrego** [globaleaks/GlobaLeaks#3799]
### What version of GlobaLeaks are you using?

Software version: 4.13.18

Automatic Lets encrypt generation fails.  Manual generation of CSR fails.  No certs can be installed.

### What browser(s) are you seeing the problem on?

Safari

### What operating system(s) are you seeing the problem on?

macOS

### Describe the issue

Trying to install an SSL certificate, both automatic and manual.

**Comment by evilaliv3** [comment]
Hello @nigeltrego 

Thank you if you could provide more detail answering the following questions?

1. Regarding the automatic configuration do you confirm that you have pointed your domain name to the public IP address dedicated to the globaleaks server and that both ports 80 and 443 are publicly reachable?
2. Regarding the manual configuration, can you describe your steps and where do you get the first error?
Thank you!

**Comment by nigeltrego** [comment]
Thank you Giovanni,

Problem solved, it was port 80 blocked by the FW.

Nigel



From:        "Giovanni Pellerano" ***@***.***>
To:        "globaleaks/GlobaLeaks" ***@***.***>
Cc:        "nigeltrego" ***@***.***>, "Mention" ***@***.***>
Date:        21/11/2023 03:50
Subject:        Re: [globaleaks/GlobaLeaks] Certificate Generation and Signing Request Errors (Issue #3799)
________________________________



Hello @nigeltrego<https://lsems.gravityzone.bitdefender.com/scan/aHR0cHM6Ly9naXRodWIuY29tL25pZ2VsdHJlZ28=/9CD0689AEAB385CD0C33AFA6318649082F802EC9D0C7758B6C229DA704DB3DE1?c=1&i=1&docs=1>
Thank you if you could provide more detail answering the following questions?

  1.  Regarding the automatic configuration do you confirm that you have pointed your domain name to the public IP address dedicated to the globaleaks server and that both ports 80 and 443 are publicly reachable?
  2.  Regarding the manual configuration, can you describe your steps and where do you get the first error?
Thank you!

—
Reply to this email directly, view it on GitHub<https://lsems.gravityzone.bitdefender.com/scan/aHR0cHM6Ly9naXRodWIuY29tL2dsb2JhbGVha3MvR2xvYmFMZWFrcy9pc3N1ZXMvMzc5OSNpc3N1ZWNvbW1lbnQtMTgyMDE3NzYwMg==/AD7D661E5B24A0A92FE9EB6A6C2CC3657ED914A1882D9A62247DE6D164874240?c=1&i=1&docs=1>, or unsubscribe<https://lsems.gravityzone.bitdefender.com/scan/aHR0cHM6Ly9naXRodWIuY29tL25vdGlmaWNhdGlvbnMvdW5zdWJzY3JpYmUtYXV0aC9CRUVOTkEzTDVKSzJSTVQzQkY2VTRXRFlGUVFIWkFWQ05GU002QUFBQUFBN1RPVVBHNlZISTJEU01WUVdJWDNMTVY0M09TTFRPTjJXS1EzUE5WV1dLM1RVSE1ZVFFNUlFHRTNUT05SUUdJ/84D1BA4B190C7272C5F7FD70677BBFA23617658AEACEF752A96DAE90F8BC4D8C?c=1&i=1&docs=1>.
You are receiving this because you were mentioned.Message ID: ***@***.***>



This e-mail is confidential and may contain privileged information. If you are not the intended recipient you are notified that disclosing,
copying, distributing or taking any action in reliance on the contents of this information is strictly prohibited.

Any views or opinions presented in this email are solely those of the author and do not necessarily represent those of the company.
Employees of the company are expressly required not to make defamatory statements and not to infringe or authorise any infringement of copyright or any other legal right by email communications. Any such communication is contrary to company policy and outside the scope of the employment of the individual concerned.

The company will not accept any liability in respect of such communication, and the employee responsible will be personally liable for any damages or other liability arising.

The recipient should check this email and any attachments for the presence of viruses. The Zeon Group of Companies accepts no liability for any damage caused by any virus or other malicious content potentially transmitted in this email.

Zeon accepts no liability for the content of this email, or for the consequences of any actions taken on the basis of the information provided, unless that information is subsequently confirmed in writing.

No employee or agent is authorised to conclude any binding agreement on behalf of Zeon with another party by email without express written confirmation by Yoshihiro Kurashima.

Finally, Zeon privacy policy can be found at https://www.zeon.eu/privacy-policy.html

Zeon Europe GmbH, Hansaallee 249, 40549 Düsseldorf, Germany. Registered: Amtsgericht Düsseldorf, HRB 24962. Managing Director: Yoshihiro Kurashima

**Comment by evilaliv3** [comment]
Thank you for this update @nigeltrego
