### ISSUE TITLE
Download of multiple reports not working

### ISSUE THREAD

**Issue by eleibr** [globaleaks/GlobaLeaks#3802]
### What version of GlobaLeaks are you using?

4.13.18

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows, macOS

### Describe the issue

If you select all reports from the Reports home page and click to export them

![image](https://github.com/globaleaks/GlobaLeaks/assets/113996868/7007fae4-4003-4c7d-ae2d-5b619d325e45)

you only download the first of the list

![image](https://github.com/globaleaks/GlobaLeaks/assets/113996868/3e1ac50d-b716-46de-8c61-66698c6eae46)

**Comment by evilaliv3** [comment]
Hello @eleibr 

For security reasons we implement the download of files in new tabs, independent from the application.
Would you please check if your browsers is blocking opening of new tabs and asking you to authorize the opening?

**Comment by eleibr** [comment]
Hello @evilaliv3 and thanks for your kindly reply.
I confirm that it is working by authorizing the opening of news tabs.
