### ISSUE TITLE
Can't install, stopped on wizard

### ISSUE THREAD

**Issue by albertopisaroni** [globaleaks/GlobaLeaks#3818]
### What version of GlobaLeaks are you using?

[4.13.18]

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari, All

### What operating system(s) are you seeing the problem on?

macOS

### Describe the issue

When I arrive on the last page of wizard api/wizard give me ERR:REFUSED or error 502.
Tried with different IPs or hostname, always same result

**Comment by evilaliv3** [comment]
Hello Alberto,

this seems quite strange.

Do you have any proxy or web application firewall in tour setup?
Is it possible for you to share the link to the wizard so that we could try completing it?

**Comment by albertopisaroni** [comment]
I was on AWS, I did a lot of try, I fixed increase the size of the machine from "nano" to "micro", thank you.
