### ISSUE TITLE
Unable to deliver the submission to at least one recipient

### ISSUE THREAD

**Issue by pxtmc** [globaleaks/GlobaLeaks#3833]
### What version of GlobaLeaks are you using?

4.13.18

### What browser(s) are you seeing the problem on?

Tor Browser, Chrome

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Hello, I've just installed the software on a fresh VPS running Debian 12.
I've set up users (administrators and recipients) and the SMTP settings (verified sending test emails).
The problem is that as I try to submit I got the erorr in subjet.
No error found in log files.
<img width="1512" alt="Senza nome" src="https://github.com/globaleaks/GlobaLeaks/assets/4469997/760b9c2e-a2e9-4329-b406-ea23b4b0c3b0">

**Comment by evilaliv3** [comment]
Ensure to add at least one recipient to your repotting channels.

**Comment by pxtmc** [comment]
Many thanks, it solved the issue.
