### ISSUE TITLE
Minimizzazione - Eliminazione dati personali non rilevanti

### ISSUE THREAD

**Issue by marcomeneghin** [globaleaks/GlobaLeaks#3844]
### What version of GlobaLeaks are you using?

4.13.18

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Un Organismo di Vigilanza chiede che la piattaforma preveda la possibilità per il Ricevente di cancellare dati personali non pertinenti (è un tema legato alla minimizzazione). Quanto inviato dal segnalante (testi/file) ho visto che è inalterabile. C'è qualche modo (oltre alla possibilità di cancellare in toto una segnalazione) di permettere la cencellazione di dati non pertinenti?

**Comment by evilaliv3** [comment]
Salve Marco,

siamo in corso di ultimazione di una funzionalità avanzata che permetterà di:
- dare ad alcuni utenti la possibilità di mascherare dati non rilevanti: https://github.com/globaleaks/GlobaLeaks/issues/3420
- dare ad alcuni utenti la possibilità di cancellare indelebilmente dati non rilevanti: https://github.com/globaleaks/GlobaLeaks/issues/3429

Le due funzionalità descritte nei rispettivi ticket verranno rilasciate entro fine anno.
