### ISSUE TITLE
Firewall when smtp port is not standard

### ISSUE THREAD

**Issue by verbavolant** [globaleaks/GlobaLeaks#3854]
### What version of GlobaLeaks are you using?

Lastest

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

When using smtp port (for example port 26) not standard the mail can't start.

iptables -I OUTPUT -p tcp --dport 26 -j ACCEPT
works

**Comment by evilaliv3** [comment]
Thank you for your feedback @verbavolant 

We have just issued a revised sandboxing that deprecates some of the rules for this specific reason.

If interested to give it a try here you could find the up to date init script that will be included in globaleaks version 4.13.19: https://github.com/globaleaks/GlobaLeaks/blob/dd181892731c8c5c79805405572ddaf1bd49edcc/debian/globaleaks.init

Thank you if you could provide your feedback

**Comment by verbavolant** [comment]
Perfect, it works!
Thx a lot
