### ISSUE TITLE
Debian 12 (fresh install): Error after click Proceed button to complete the Platform wizard

### ISSUE THREAD

**Issue by pcinacio** [globaleaks/GlobaLeaks#3855]
### What version of GlobaLeaks are you using?

4.3.19

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Good evening.
I was following the documentation to install the platform on a fresh Debian 12. 
After filling the wizard, I get an Error message (red modal just saying Error!) after pressing the Proceed button of the Congratulations! 
You have completed the platform wizard.
<img width="845" alt="Captura de ecrã 2023-12-10, às 02 06 59" src="https://github.com/globaleaks/GlobaLeaks/assets/94837894/abafc6d5-d875-481b-bbd2-e3627df06f7f">

**Comment by evilaliv3** [comment]
Thank you.

Is it possible for you to share a link to the system or attach the file /var/glboaleaks/log/globaleaks.log?

**Comment by pcinacio** [comment]
[notas.txt](https://github.com/globaleaks/GlobaLeaks/files/13627876/notas.txt)

**Comment by enrico-torrente** [comment]
[globaleaks.log](https://github.com/globaleaks/GlobaLeaks/files/13634720/globaleaks.log)

**Comment by pcinacio** [comment]
What changes did you perform in order to get it to work?

**Comment by enrico-torrente** [comment]
It does not work yet, I prepared the vm in order to help "elivaliv3" to check issues

**Comment by pcinacio** [comment]
My apologies for the misinterpretation.

**Comment by enrico-torrente** [comment]
Could you confirm if someone has performed the wizard?
Now it seams executed and as expected if you try to connect it return empty page.

**Comment by enrico-torrente** [comment]
[access.log](https://github.com/globaleaks/GlobaLeaks/files/13634995/access.log)

**Comment by evilaliv3** [comment]
Thank you everyone; your input was very helpful to recognize the regression introduced in 4.13.20.

I'm issuing a patch and releasing a bugfixed 4.13.21.
