### ISSUE TITLE
Content-Security-Policy prevents the display of images

### ISSUE THREAD

**Issue by MarcMichalsky** [globaleaks/GlobaLeaks#3862]
### What version of GlobaLeaks are you using?

4.13.21
Ubuntu 22.04.3 LTS

### What browser(s) are you seeing the problem on?

Tor Browser, Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Windows, Android, Linux

### Describe the issue

First of all, thank you for your incredible work! I and my non-profit organization really appreciate it!

I'm aware that there are some related issues here, but I haven't found one that has to do with images.

When I try to upload an image, the preview picture does not display correctly. The JavaScrip console gives a:
```
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“style-src”).
```
![GlobaLeaks_Image_Error](https://github.com/globaleaks/GlobaLeaks/assets/24728186/7302b2d5-1663-47a4-aece-308f0dbc9e27)

**Comment by evilaliv3** [comment]
Thank you for reporting this.

This regression has been introduced restricting the content security policy to much.

i'm going to issue a fix that will be included in the next minor release.
