### ISSUE TITLE
How customise the receiver message

### ISSUE THREAD

**Issue by ghostlucius** [globaleaks/GlobaLeaks#3863]
### What version of GlobaLeaks are you using?

4.13.20

### What browser(s) are you seeing the problem on?

Tor Browser, Safari

### What operating system(s) are you seeing the problem on?

macOS

### Describe the issue

Hello and thanks for the great work with the platform GlobaLeaks. 

I'm trying to customise the welcoming message for the receiver with the javascript upload feature in the settings but apparently It don't work. 

I tried this [#2593](https://github.com/globaleaks/GlobaLeaks/issues/2593) and corrected with [#2965](https://github.com/globaleaks/GlobaLeaks/issues/2965)

``` 
GL.mockEngine.addMock('/#/receiver/home', '#RecipientHomepage', function(scope, elem) {
  if (document.getElementById('RecipientHomepageCustomization') === null) {
    elem.innerHTML = '<div id="RecipientHomepageCustomization">Example</div>';
  }
}); 

```

I also tried to restart the service with `service restart globaleaks` without success.     

What I'm doing wrong? 
Thanks

**Comment by evilaliv3** [comment]
@ghostlucius  /receiver/home is outdated. Would you please try with /recipient/home?

**Comment by ghostlucius** [comment]
Thanks for your answer

I changed the code but sadly still doesn't work. 

```
GL.mockEngine.addMock('/#/recipient/home', '#RecipientHomepage', function(scope, elem) {
  if (document.getElementById('RecipientHomepageCustomization') === null) {
    elem.innerHTML = '<div id="RecipientHomepageCustomization">Example</div>';
  }
}); 

```

I tried with the footer also but with the same result.

**Comment by ghostlucius** [comment]
Hello we solved this issue with with the following code:

```
GL.mockEngine.addMock('*', '#RecipientHomepage', 'Test<p></p><a href="https://" target="_blank" rel="noopener noreferrer" >TEST</a>');

```

Hope this could help someone else.
