### ISSUE TITLE
Password fail to all users

### ISSUE THREAD

**Issue by paolo987** [globaleaks/GlobaLeaks#3879]
### What version of GlobaLeaks are you using?

4.13.21 
latest version

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

#3319 

When a user tries to login with real passowrd it gives the message:

The code is either invalid or expired.

If a user tries to login with a random password it gives the message

Authentication failed

this is the access.log of a deliberately wrong authentication (wrong password):
`HOSTNAME [REMOVED_IP_ADDRESS] - - [14/Dec/2023:07:06:58 +0000] "POST /api/auth/token HTTP/2" 201 126 1ms - "[REMOVED_USER_AGENT]"
HOSTNAME [REMOVED_IP_ADDRESS] - - [14/Dec/2023:07:07:00 +0000] "POST /api/auth/authentication HTTP/2" 401 85 2875ms - "[REMOVED_USER_AGENT]"`

The same log for authentication with correct password (just changed to "gl-admin resetpass")
`HOSTNAME  [REMOVED_IP_ADDRESS] - - [14/Dec/2023:07:08:58 +0000] "POST /api/auth/token HTTP/2" 201 127 1ms - "[REMOVED_USER_AGENT]"
HOSTNAME  [REMOVED_IP_ADDRESS] - - [14/Dec/2023:07:09:01 +0000] "POST /api/auth/authentication HTTP/2" 403 112 2924ms - "[REMOVED_USER_AGENT]"
`

**Comment by evilaliv3** [comment]
I see that the error while loggin in is 403.

Maybe you enabled the ip based restriction or the Tor based restriction on authentciation?

**Comment by paolo987** [comment]
I am not aware of having activated these restrictions.
Except now I can't log in to check.
Where can I check on DB if these settings exist?

**Comment by evilaliv3** [comment]
1. First i would look on the client which message is returned on the failing authentication
2. Second i would try to connect via Tor
3. The Tor based block can be checked in the table config, variable reachable_via_web; ensure you have True

**Comment by paolo987** [comment]
1) 
![image](https://github.com/globaleaks/GlobaLeaks/assets/78037015/a8d9f24b-6497-483a-be9e-1a9a6ddaf032)

2) For now the server is not public and can only be reached from my internal network

3) 
![image](https://github.com/globaleaks/GlobaLeaks/assets/78037015/49fade05-b3f5-4a27-84b0-780997f6825a)

**Comment by evilaliv3** [comment]
può guardare anche le variabili che incominciano con ip_filter_* ?

**Comment by evilaliv3** [comment]
Nevermind, the last check.

Please check the variables https_* and set them all to False.
You have definitely blocked users to access via HTTPS.

**Comment by paolo987** [comment]
![image](https://github.com/globaleaks/GlobaLeaks/assets/78037015/df7e9340-5b1a-4e21-9e61-5a350795117d)

![image](https://github.com/globaleaks/GlobaLeaks/assets/78037015/191a2391-2a9b-4b9c-a77c-44e647d6d9ec)

https_custodian was true and I set it to false, reboot but nothing change.

**Comment by evilaliv3** [comment]
As previously written the variables should be set to True.

Correct this and the issue will be resolved. 

Probably you disabled this via the web interface by mistake.

**Comment by paolo987** [comment]
Thanks a lot @evilaliv3 
sorry, I was in a hurry and misunderstood.
I set the variables to true and now I log in correctly.
thanks for support
