### ISSUE TITLE
Permission denied error to /var/globaleaks/files in my Kubernetes Pod

### ISSUE THREAD

**Issue by Andrew-Moy** [globaleaks/GlobaLeaks#3899]
### What version of GlobaLeaks are you using?

4.13.22

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

I have containerized Globaleaks to be used in Kubernetes and was able to get the pod to successfully run locally via Kind, but when deployed to an actual Kubernetes cluster I am met with the following error:

`Traceback (most recent call last):
  File "/usr/bin/globaleaks", line 84, in <module>
    State.init_environment()
  File "/usr/lib/python3/dist-packages/globaleaks/state.py", line 114, in init_environment
    self.create_directories()
  File "/usr/lib/python3/dist-packages/globaleaks/state.py", line 155, in create_directories
    self.create_directory(dirpath)
  File "/usr/lib/python3/dist-packages/globaleaks/state.py", line 141, in create_directory
    raise excep
  File "/usr/lib/python3/dist-packages/globaleaks/state.py", line 137, in create_directory
    os.mkdir(path)
PermissionError: [Errno 13] Permission denied: '/var/globaleaks/files'`

Any thoughts/suggesstions on how to fix this error?

**Comment by RDiSa** [comment]
I have the exact same problem with 'normal' docker compose [Docker version 24.0.7, build afdd53b]
New container has the 'Permnission denied' error, upgraded container doesn't.

**Comment by Punkado** [comment]
I had the same problem, but i found how to fix. Just give the permission to the volume of the user and group 102.

**Comment by rglauco** [comment]
@Andrew-Moy Would you like to try my old custom Dockerfile? it works on my clusters (and includes numerical username, 102)
https://github.com/rglauco/globaleaks-helm/blob/main/docker/Dockerfile-glauco

**Comment by Andrew-Moy** [comment]
> I had the same problem, but i found how to fix. Just give the permission to the volume of the user and group 102.

Could you show me how you did this? I change the `USER` in the dockerfile to `102`, do I need to do anything in addition to this? I'm still getting the same permission denied error

**Comment by Andrew-Moy** [comment]
nevermind, looks like adding the fsgroup in the values.yaml has fixed the issue, thanks for the assistance here!

**Comment by Trapulo** [comment]
Hi,
I have a problem after an upgrade of Globaleaks on Docker. It was unable to access all files from local volume for permissions issues.

I found that assigning as owner "102" to whole directory, it works. Before, the directory was owned by user "1337"

But 102 on my host is a real user, so I think this environment is not a good idea. The "102" you wrote in your custom dockerfile can be changed with any arbitrary value and the I need only to assign ownership of folder to that userID?

thanks
