### ISSUE TITLE
Text customization does not apply to email content

### ISSUE THREAD

**Issue by michelegz** [globaleaks/GlobaLeaks#3902]
### What version of GlobaLeaks are you using?

4.13.22

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Text customization does not apply to email sent to users. For example, if I customize text for the activation email, the email content remains the same ignoring my customizations.

**Comment by evilaliv3** [comment]
Thank you for your question.

Do you confirm that your customization were made using the Notification Templates configuration inside the Notification Settings?

Are you able to reproduce the bug on try.globaleaks.org?

**Comment by michelegz** [comment]
> Thank you for your question.
> 
> Do you confirm that your customization were made using the Notification Templates configuration inside the Notification Settings?

Yes

> 
> Are you able to reproduce the bug on try.globaleaks.org?

Yes, I can reproduce the bug on try.globaleaks.org:

![Screenshot 2023-12-20 112738](https://github.com/globaleaks/GlobaLeaks/assets/126559173/cd92a2c5-b55d-4881-8087-aa080f31738c)

The email received has no "TEST 0123456789" appended on that text line.

**Comment by michelegz** [comment]
Sorry, the customization was made using "Text customization" under "Settings", it is misleading because it contains text lines of notifications sent by email. Using "Notification Templates" it works as expected.

**Comment by evilaliv3** [comment]
Than you for this update. I'm going to close the ticket then!
