### ISSUE TITLE
Globaleaks 4.13.22 incompatible with bionic invoke-rc.d

### ISSUE THREAD

**Issue by simon-src** [globaleaks/GlobaLeaks#3913]
### What version of GlobaLeaks are you using?

4.13.22

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Upgrading globaleaks to 4.13.22 on our bionic instances resulted in globaleaks not being started after the upgrade. A manual start of globaleaks worked.

The post-installation script seems to use an incompatible option when executing `invoke-rc.d`:
```
Setting up globaleaks (4.13.22) ...
invoke-rc.d: syntax error: unknown option "--skip-systemd-native"
dpkg: error processing package globaleaks (--configure):
 installed globaleaks package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 globaleaks
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### Proposed solution

Provide compatibility with bionic

**Comment by evilaliv3** [comment]
Thank you @simon-src 

This ssems to be a specific problem of ubuntu Bionic; We may try to fix it but we gihly discourage to run on this distribution version which LTS period ended last june: https://wiki.ubuntu.com/Releases

We invite you to update to Ubuntu Jammy 22.04

**Comment by simon-src** [comment]
LTS ended last June, but EOL will be April 2028.

**Comment by evilaliv3** [comment]
Have you identified which could be the solution?

**Comment by evilaliv3** [comment]
Can you try with: https://askubuntu.com/questions/1368464/there-are-some-errors-with-avahi-daemon-when-i-try-to-upgrade-xubuntu-21-04 ?

**Comment by simon-src** [comment]
Thank you for your quick response!

We see this when upgrading `globaleaks` on our bionic customers' instances:
```
invoke-rc.d: syntax error: unknown option "--skip-systemd-native"
```
So i think the solution would be to find another command line in case `bionic` is the release.

**Comment by simon-src** [comment]
Thanks for sharing the link, that looks like it has the fix for bionic users:

```
sudo dpkg -P --force-all sysv-rc
sudo apt-get install --reinstall init-system-helpe
```

In the meantime our instances are now upgraded to focal (20.04.6) and the issue is resolved in this version.

**Comment by evilaliv3** [comment]
Thank you for the feedback.
