### ISSUE TITLE
Demo - impossibile to stop email notifications

### ISSUE THREAD

**Issue by GDSappmynet** [globaleaks/GlobaLeaks#3915]
### What version of GlobaLeaks are you using?

demo

### What operating system(s) are you seeing the problem on?

macOS

### Describe the issue

Hi, I try demo of global leaks and I can't stop mail notification as user and also as recipient. 
This in global leaks demo link can you please delete it? 
https://giulia.try.globaleaks.org/

### Proposed solution

Delete demo ambient with link
https://giulia.try.globaleaks.org/

or let people unsubscribe form emails notifications

**Comment by evilaliv3** [comment]
Deleted, thank you!
