### ISSUE TITLE
Automatic report status from "new" to "open" doesn't trigger "last update time" change

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#3918]
### What version of GlobaLeaks are you using?

4.13.22, also previous versions

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android, iOS, Linux

### Describe the issue

As a receiver, clicking on a new report, there is automatic state change from "new" to "open". In this operation the "last update date" never changes. 

Pelase notice that:
1. Just changing to another state, which you have to create for that purpose, then the last update date changes.
2. From each other state, bringing the status back to "open" the last update time changes again
3. this is an important timing action feedback to give the whitleblower a "take in charge" feedback, that should have given within 7 days following italian regulation

### Proposed solution

The last update time should necessarily change at first click on a new report, bringing the state to "open"

**Comment by evilaliv3** [comment]
Implemented since 4.11.0
