### ISSUE TITLE
Error running installation script

### ISSUE THREAD

**Issue by massimo-tnsf** [globaleaks/GlobaLeaks#3921]
### What version of GlobaLeaks are you using?

4.14.0

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

I'm trying to install globaleaks on a  digitalocean droplet running debian 12 os.
Running the globaleaks installation script i got this error "E: Unable to locate package globaleaks".

Below you can find the entire log of the installation script:

`
Running the GlobaLeaks installation...
In case of failure please report encountered issues to the ticketing system at: https://github.com/globaleaks/GlobaLeaks/issues

Detected OS: Debian - bookworm
Running: "apt-get -y update"... SUCCESS
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages will be upgraded:
  tzdata
1 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.
Need to get 296 kB of archives.
After this operation, 5120 B of additional disk space will be used.
Get:1 file:/etc/apt/mirrors/debian.list Mirrorlist [39 B]
Get:2 http://mirrors.digitalocean.com/debian bookworm/main amd64 tzdata all 2023c-5+deb12u1 [296 kB]
Fetched 296 kB in 0s (2273 kB/s)
apt-listchanges: Reading changelogs...
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LC_TERMINAL = "iTerm2",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
Preconfiguring packages ...
(Reading database ... 24905 files and directories currently installed.)
Preparing to unpack .../tzdata_2023c-5+deb12u1_all.deb ...
Unpacking tzdata (2023c-5+deb12u1) over (2023c-5) ...
Setting up tzdata (2023c-5+deb12u1) ...

Current default time zone: 'Etc/UTC'
Local time is now:      Tue Jan  2 12:08:12 UTC 2024.
Universal Time is now:  Tue Jan  2 12:08:12 UTC 2024.
Run 'dpkg-reconfigure tzdata' if you wish to change it.

perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_TERMINAL = "iTerm2",
	LC_CTYPE = "UTF-8",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").

Current default time zone: 'Etc/UTC'
Local time is now:      Tue Jan  2 12:08:13 UTC 2024.
Universal Time is now:  Tue Jan  2 12:08:13 UTC 2024.

Running: "apt-get -y install gnupg net-tools software-properties-common wget"... SUCCESS
Adding GlobaLeaks PGP key to trusted APT keys
gpg: no valid OpenPGP data found.
Updating GlobaLeaks apt source.list in /etc/apt/sources.list.d/globaleaks.list ...
Running: "apt-get update -y"... SUCCESS
Running: "apt-get install globaleaks -y"... FAIL
Ouch! The installation failed.
COMBINED STDOUT/STDERR OUTPUT OF FAILED COMMAND:
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package globaleaks
`

Can you help!
Thank's.

**Comment by evilaliv3** [comment]
Thank you, the reason of the failure is that our repository i down due to some maintenance.

It will be back up by tomorrow morning.

**Comment by massimo-tnsf** [comment]
Ok. Thank you very much. I'll retry tomorrow.

**Comment by massimo-tnsf** [comment]
Hi. I retried  the installation this afternoon. The installation has completed successfully.
Thank'you
