### ISSUE TITLE
The signaller cannot listen to the audio of its  own signal.

### ISSUE THREAD

**Issue by mfagiolihi-net** [globaleaks/GlobaLeaks#3922]
### What version of GlobaLeaks are you using?
the latest version

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue
The signaller cannot listen to the audio of its signal.
Only the receiver can listen to it by updating the page otherwise it always hears the audio of the previous report
this i the signaler view
![noaudio](https://github.com/globaleaks/GlobaLeaks/assets/155471806/2d9e9b00-2c13-4bb2-ac8f-32511c609231)
this is the receiver view

![si_audio](https://github.com/globaleaks/GlobaLeaks/assets/155471806/f54813b4-9fa9-4c1e-922b-52eee04568d8)

i have the latest version of globaleaks
i see among issues that this is closed but the problem is still alive

**Comment by evilaliv3** [comment]
Thank you, we are reviewing the feature and we will fix it with 4.14.1

**Comment by evilaliv3** [comment]
This should be fixed in 4.11.1
