### ISSUE TITLE
Error ERR_SSL_VERSION_OR_CIPHER_MISMATCH while updating certificate

### ISSUE THREAD

**Issue by campo23** [globaleaks/GlobaLeaks#3923]
### What version of GlobaLeaks are you using?

4.10.14

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Good morning, I was trying to update the certificates but once I removed the old ones I can no longer access the portal. Trying to reconnect it gives me the error ERR_SSL_VERSION_OR_CIPHER_MISMATCH, how can I resolve it?

**Comment by evilaliv3** [comment]
Are you sure that the version you indicated is correct. 4.10.14?

**Comment by campo23** [comment]
yes, the last time it was updated was a while ago

**Comment by evilaliv3** [comment]
Solved?

**Comment by campo23** [comment]
By updating to a newer version I was able to access the portal in insecure mode, so i was able to install the certificates
