### ISSUE TITLE
The repository 'http://deb.globaleaks.org jammy/ Release' is not signed.

### ISSUE THREAD

**Issue by is-18** [globaleaks/GlobaLeaks#3924]
### What version of GlobaLeaks are you using?

4.14.0

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

I'm trying to install globaleaks.
Running the globaleaks installation script i got this error "E: The repository 'http://deb.globaleaks.org jammy/ Release' is not signed.".
Below you can find the entire log of the installation script:
'
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Ign:1 https://deb.globaleaks.org jammy/ InRelease
Hit:5 https://deb.globaleaks.org jammy/ Release
Hit:6 http://archive.ubuntu.com/ubuntu jammy-security InRelease
Get:7 https://deb.globaleaks.org jammy/ Release.gpg [833 B]
Ign:7 https://deb.globaleaks.org jammy/ Release.gpg
Reading package lists...
W: GPG error: https://deb.globaleaks.org jammy/ Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 32E6792624045008
E: The repository 'http://deb.globaleaks.org jammy/ Release' is not signed.
'
How is it possible to solve this issue?
Thanks.

**Comment by evilaliv3** [comment]
Thank you, we were updating the repository. It should be all working by now.
