### ISSUE TITLE
Change translation for a question from the provided models

### ISSUE THREAD

**Issue by pcinacio** [globaleaks/GlobaLeaks#3933]
### What version of GlobaLeaks are you using?

4.13.22

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows, Linux

### Describe the issue

Is it possible to change the "Would you like to tell us who you are?" translation for PT? I've tried to change it from "Gostaria de nos dizer quem você é?" to "Gostaria de nos dizer quem é?" inside de platform, but i can't do it.

![Captura de ecrã 2024-01-06, às 00 48 17](https://github.com/globaleaks/GlobaLeaks/assets/94837894/e2e35767-499c-432a-8f96-ecac6143462a)
![Captura de ecrã 2024-01-06, às 00 48 32](https://github.com/globaleaks/GlobaLeaks/assets/94837894/9a080cc5-3ba7-46e0-93df-ad9913108067)
![Captura de ecrã 2024-01-06, às 00 49 52](https://github.com/globaleaks/GlobaLeaks/assets/94837894/bf46160d-28f0-40d0-9329-4d9d356f75d4)

**Comment by evilaliv3** [comment]
Thank you @pcinacio 

These texts are not customizable but translations of globaleaks are made by contributors on https://app.transifex.com/otf/globaleaks/
Would you like to support some review of the existing translations?

In the meantime i will update the translation with the text that you revised that will be included in the next minor release
