### ISSUE TITLE
Proposal for "reason" in complaints in version 4.14.3

### ISSUE THREAD

**Issue by Natii9898** [globaleaks/GlobaLeaks#3935]
### Proposal

Right now there is another box in the change of status of a complaint, which is the "reason".

When you want to change the status of a complaint of the type open for review, for example in case you have more statuses added. We need to give it a reason, yes or yes, so that there is no server error. Wouldn't it be better if in any case this "reason" box was mandatory for all possible states that exist on our website?

### Motivation and context

I believe that only doing that could help ensure that if you do not provide a reason for the change, the server will stop giving an error and force you to enter the reason as you do if you want to close or reopen a complaint.

Thank you so much

**Comment by evilaliv3** [comment]
Thank you @Natii9898 for this feedback.

We will issue in the next minor release accepting that the user could avoid to type a motivation and fixing the server error in this condition.

**Comment by Natii9898** [comment]
Thank you so much @evilaliv3

**Comment by evilaliv3** [comment]
Closing since the feedback was considered and an implementation for the suggestion is present in current 4.15.5
