### ISSUE TITLE
Analysts preferences page not shown

### ISSUE THREAD

**Issue by maelaborazioni** [globaleaks/GlobaLeaks#3940]
### What version of GlobaLeaks are you using?

4.14.3

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

While logged as Analyst, if I click on the preferences icon I am redirected to the homepage intead of the correct page.

### Proposed solution

Nothing

**Comment by evilaliv3** [comment]
Thank you for reporting this @maelaborazioni

**Comment by evilaliv3** [comment]
Fixed. The correction will be included in next minor release.
