### ISSUE TITLE
Login in sub sites not work

### ISSUE THREAD

**Issue by aapian** [globaleaks/GlobaLeaks#3951]
### What version of GlobaLeaks are you using?

4.14.3

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Hi,

I have created subsites in globaleaks, but when creating users within these subsites, the login does not work. It only works if I create them on the base site and this causes them to have access on the rest of the subsites

**Comment by evilaliv3** [comment]
thank you. this is actually a very strange behaviour. could you provide instructions on how to reproduce the bug or make a small video?

**Comment by aapian** [comment]
Hi,

When create a new sub-site,  I click configure, it sends me to the administration panel  sub-site:

![gl1](https://github.com/globaleaks/GlobaLeaks/assets/74967353/7cda9d07-ea36-4bec-92ad-24825396daf3)


and in the Network option, I add the DNS that I want my subsite to have, but when accessing the test.es domain, it sends me to the base site. despite the fact that in the browser it is on https://test.es/#/admin and the users created in it cannot be authenticated.

Am I doing something wrong?

**Comment by evilaliv3** [comment]
At the moment i'm not able to reproduce the issue i'm sorry.
Please let me know if you find ways of reproducing it.

**Comment by evilaliv3** [comment]
@aapian: do you have any update on this issue ?
