### ISSUE TITLE
Status Change Request Shows Pending - Possible Frontend Error

### ISSUE THREAD

**Issue by faizanjaved38** [globaleaks/GlobaLeaks#3956]
### What version of GlobaLeaks are you using?

version 4.14.4

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

When attempting to change the status, the request processing time is resulting in a "pending" status. I suspect there might be an error on the frontend side. It seems that the parameters in the payload for status changes (specifically for "open" and "closed" statuses) might not be handled correctly, leading to unexpected behavior.

**Steps to Reproduce:**

1. Navigate to the page where status changes are initiated.
2. Attempt to change the status to "open" or "closed."
3. Observe that the request processing time is displaying a "pending" status.

**Expected Behavior:**

The status change request should be processed promptly, and the UI should reflect the updated status without any delay.
![Screenshot from 2024-01-16 11-29-31](https://github.com/globaleaks/GlobaLeaks/assets/101192444/6855917b-970d-4b54-9a30-3f997c4325dd)
![Screenshot from 2024-01-16 11-29-44](https://github.com/globaleaks/GlobaLeaks/assets/101192444/40baae95-0d4d-4be6-b7c1-41e1b9deeae9)

**Comment by evilaliv3** [comment]
Solved in 4.14.5
