### ISSUE TITLE
The repository 'http://deb.globaleaks.org jammy/ Release' is not signed

### ISSUE THREAD

**Issue by HeavyRainLQ** [globaleaks/GlobaLeaks#3958]
### What version of GlobaLeaks are you using?

4.14.4

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

Running the globaleaks installation script i got this error "E: The repository 'http://deb.globaleaks.org/ jammy/ Release' is not signed.".

Running: "apt-get -y update"... FAIL
Ouch! The installation failed.
COMBINED STDOUT/STDERR OUTPUT OF FAILED COMMAND:
Hit:1 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease
Ign:5 https://deb.globaleaks.org jammy/ InRelease
Get:6 https://deb.globaleaks.org jammy/ Release [741 B]
Get:7 https://deb.globaleaks.org jammy/ Release.gpg [833 B]
Ign:7 https://deb.globaleaks.org jammy/ Release.gpg
Reading package lists...
W: GPG error: https://deb.globaleaks.org jammy/ Release: The following signatures were invalid: BADSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
E: The repository 'http://deb.globaleaks.org jammy/ Release' is not signed.

**Comment by evilaliv3** [comment]
Solved thank you
