### ISSUE TITLE
Provide a general summary of the issue

### ISSUE THREAD

**Issue by Natii9898** [globaleaks/GlobaLeaks#3960]
### What version of GlobaLeaks are you using?

Globalekas version 4.14.4

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

In the last update, the pdfs uploaded in complaints do not allow you to see them correctly, and when downloading said pdf it gives an error as if it were corrupt or had not been decoded correctly when downloading.

<img width="851" alt="image" src="https://github.com/globaleaks/GlobaLeaks/assets/153637801/7f08f013-dcd0-4578-8f90-aeeb1093f888">

It does not allow any PDF to be viewed or downloaded, I tested it with several and in several browsers.

Thank you

**Comment by evilaliv3** [comment]
Thank you for reporting this @Natii9898; we will check an update the ticket.

**Comment by Natii9898** [comment]
Thanks for answering @evilaliv3
