### ISSUE TITLE
Unable to change network settings

### ISSUE THREAD

**Issue by msmannan00** [globaleaks/GlobaLeaks#3971]
### What version of GlobaLeaks are you using?

4.14.7

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

the error response from the server

{"error_message": "Invalid Input [Missing key ip_filter_analyst_enable]", "error_code": 3, "arguments": ["Missing key ip_filter_analyst_enable"]}

### Proposed solution

this issue occurs because network resolver doesn't sends "ip_filter_analyst_enable" key from server when sending network settings but expects "ip_filter_analyst_enable" in data sent. adding this key from server would resolve the issue

**Comment by evilaliv3** [comment]
Corrected, thank you @msmannan00 

To test the fix you should also regenerate the database.
