### ISSUE TITLE
Redirect of channels breaks things

### ISSUE THREAD

**Issue by maryisdead** [globaleaks/GlobaLeaks#3983]
### What version of GlobaLeaks are you using?

4.14.8 (can confirm this behaviour down to 4.14.3)

Edit: We found an instance that still works, running on 4.13.11. So the change must've been introduced after that.

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

macOS

### Describe the issue

I'm not exactly sure which version introduced this behavior, but as of now channels are being redirect from

`/#/submission?context=ed2e1c96-4984-4fd2-8838-2c59d7631ba6`

to

`/#/?context=ed2e1c96-4984-4fd2-8838-2c59d7631ba6`.

Note the missing "submission". This breaks at least one thing that I'm aware of and might break more.

In `client/app/js/services.js`, there's at least four places that check `$location.path()` for "/submission"; most notably in function `showWBLoginBox()`, which then removes the receipt box from channel pages.

### Proposed solution

Remove the redirect if it was inadvertent or properly check if we are on a channel page where necessary. Read, not relying on parsing a path.

**Comment by evilaliv3** [comment]
Closing since this issue was recently identified and is fixed in current 4.15.5
