### ISSUE TITLE
Problem with base url in notifications email

### ISSUE THREAD

**Issue by pgibe** [globaleaks/GlobaLeaks#3987]
### What version of GlobaLeaks are you using?

4.14.3

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge, Safari

### What operating system(s) are you seeing the problem on?

Windows, macOS, Android

### Describe the issue

The notification emails (e.g. the email sent by the server to the receivers when a new report is done) contain an url without the port of the server (e.g. https://my_server/#/reports/123456789 instead of https://my_server:8443/#/reports/123456789) and the receivers are unable to use the provided link.

### Proposed solution

Add the port to the hostname or allow to customize the notification email message.

**Comment by evilaliv3** [comment]
A proper and complete production of GlobaLeaks requires to expose the server on a public domain on port 80 and 443.

There are in fact many security constraints and checks that have this conditions at their base.

This is why for example email notification do not contain any port.

**Comment by pgibe** [comment]
I see.
The ticket can be closed.
However, it would be interesting to be able to customize the text of the various notification emails.

Regards,
