### ISSUE TITLE
Custom css and initialization is not executed when using relative paths, www.domain.com/myglobaleaks

### ISSUE THREAD

**Issue by yevon** [globaleaks/GlobaLeaks#4027]
### What version of GlobaLeaks are you using?

4.14.8

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

It seems that Globaleaks is unable to be installed within relative paths instead of a full domain or subdomain. All seems to work but it is unable to load the custom styles css files when doing so, and it seems to be due to this:

![1960a547-26f7-48d8-8212-cd057899c421](https://github.com/globaleaks/GlobaLeaks/assets/121157/9e25cdb7-f5bd-49ee-a9fa-e64d01fc1a81)

### Proposed solution

It checks that the url must be "/" with Javascript, but if you delete this condition it just works just fine and loads custom css sucessfully. Could it be possible to fix that condition? Or it may go wrong for other reasons?

**Comment by evilaliv3** [comment]
Thank you @yevon 

This is intended acutally, enabling a secondarty tenant administrator to load a CSS and Javascript and load it on the root tenant domain would represent a vulnarability where a malicious user of a secondary tenant could target an administrator of the root tenant.

**Comment by yevon** [comment]
Nice, I didn't think about that because we were just using css and not javascript and we just have one globaleaks instance. But we will just use a subdomain for globaleaks in this case. Thanks!
