### ISSUE TITLE
Backups

### ISSUE THREAD

**Issue by pcinacio** [globaleaks/GlobaLeaks#4034]
### Proposal

I'm not sure if it's possible, but apparently I'm not finding it. Can the administrator export/import data from the platform? (cases, users, etc.)

### Motivation and context

If there's any fatality with the machine hosting the platform, it would be interesting to restore it with a backup of the platform itself right away.

**Comment by evilaliv3** [comment]
Thank you @pcinacio for your feedback.

I'm closing this ticket since we have already some ticket dealing with this topic:
https://github.com/globaleaks/GlobaLeaks/issues/528
https://github.com/globaleaks/GlobaLeaks/issues/3393

Please feel free to add your ideas there.
