### ISSUE TITLE
Update - Signature Verification

### ISSUE THREAD

**Issue by jurdajrd** [globaleaks/GlobaLeaks#4040]
### What version of GlobaLeaks are you using?

4.14.8

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

I am trying to update from 4.14.8 to 4.15.0. I am using Ubuntu 20.04.6 LTS. You can see error on picture.
![image](https://github.com/globaleaks/GlobaLeaks/assets/54391873/a19be25c-a4e3-4903-9c62-35382683ef81)

**Comment by joaomarcosdm** [comment]
I also hade the same problem in debian bullseye:

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://deb.globaleaks.org bullseye/ Release: The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Failed to fetch http://deb.globaleaks.org/bullseye/Release.gpg  The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
```

**Comment by jurdajrd** [comment]
Had? Did you solve it?

**Comment by evilaliv3** [comment]
To resolve issue:
rm /etc/apt/trusted.gpg
wget -qO- https://deb.globaleaks.org/globaleaks.asc | gpg --dearmor >
/etc/apt/trusted.gpg.d/globaleaks.gpg
apt-get update

**Comment by jurdajrd** [comment]
I can confirm, it is working. Whistleblowing is up-to-date.
