### ISSUE TITLE
Mandatory fields on "Report page"  are not enforced

### ISSUE THREAD

**Issue by schris-dk** [globaleaks/GlobaLeaks#4043]
### What version of GlobaLeaks are you using?

4.15.0

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

We have sites, where there are multiple check boxes on the "Report page". The fields are set as mandatory - but only one of the have to be checked, to be able to submit the report.

Front end:
![image](https://github.com/globaleaks/GlobaLeaks/assets/70965554/6acd71fe-5bf5-437d-b8eb-805d034dfd25)

Back end:

![image](https://github.com/globaleaks/GlobaLeaks/assets/70965554/6719321e-4b2a-41b3-8586-8a01544eb5e3)

**Comment by evilaliv3** [comment]
Hello @schris-dk with that type of question we consider that the user could select more than one option but we consider as mandatory to select one option.

If you want to implement two manteatory questions, just implement multiple questions with one option as confirmation.

**Comment by schris-dk** [comment]
OK  :-)
