### ISSUE TITLE
It should be possible to aggregate contexts into categories/groups

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#405]
Following dealing with a GlobaLeaks Adopters a new requirements arise:

It should be possible to aggregate contexts into categories/groups.

The requirements has been expressed as to be able to configure submission form with:
- CATEGORY
  - CONTEXT (Effectively the context)
  - CONTEXT (Effectively the context)

The Whistleblower must be able to select a category/group and see all the context available for that category/group, then select the context and proceed with the submission.

The admin must be able to configure it.

It should be possible to associate a Context to multiple Category.

The Category has been defined, while discussing about it, as "tags" .
##

**Comment by evilaliv3** [comment]
This ticket is in my opinion a desiderata that was proposed just from an adopter that higly impact on the current design (just for the visualization and configuration).

Going to close the ticket, let's reopen it wheneer a new adopter will raise the point on it.

**Comment by fpietrosanti** [comment]
That's a requirement to provide default questionnaire into the database with a whistleblowing-commercial-grade-quality level, whereby the categories are aggregated and not flat. For example WhistleblowerSecurity

**Comment by evilaliv3** [comment]
In years actually ath the moment no one have expessed this need. Marking this ticket explicitly as discarded.
