### ISSUE TITLE
HTTP Exceptions that raise before HTTP Handler Calls can't be handled cleanly

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#408]
Some  HTTP excepitons that raise before the call self.request_callback(self._request) of httpserver.py (overridden in globaleaks/handlers/base.py) can't be handled cleanly.

This is due to the cyclone/twisted logic flow. If an exception is generated before of the resquest object construction the only thinks that can be done is a forced close of the connection. This is what cyclone/twisted do and we can do nothing different from be aware of this problem.

Currently this exceptions are:
- errors.HTTPRawLimitReach defined by us to track incorrect lens in requests.
  -_BadRequestException("Malformed HTTP version in HTTP Request-Line") native of cyclone
- probably a lot of others hidden in twisted/cyclone code.

for the current globaleaks code this exceptions are only logged on the backend side and thinks can't be different.
##

**Comment by NSkelsey** [comment]
Cyclone has been removed. This ticket is now outdated.
