### ISSUE TITLE
Update new version 4.14.8 to  4.15.5

### ISSUE THREAD

**Issue by esperti** [globaleaks/GlobaLeaks#4095]
### Discussed in https://github.com/orgs/globaleaks/discussions/4091

<div type='discussions-op-text'>

<sup>Originally posted by **esperti** June  3, 2024</sup>
Hi
I am trying to update the version of Globaleaks to 4.15.5 from 4.14.8, following the steps outlined in the documentation. When executing the command "apt-get update && apt-get install globaleaks" as root, I encounter the following error:
---------------------------------------
# apt-get update && apt-get install globaleaks
Hit:1 http://mirrors.gandi.net/debian bullseye InRelease
Hit:2 http://mirrors.gandi.net/debian bullseye-updates InRelease               
Ign:4 https://mirrors.gandi.net/gandi/debian bullseye InRelease                
Hit:5 http://security.debian.org/debian-security bullseye-security InRelease   
Hit:6 https://mirrors.gandi.net/gandi/debian bullseye Release                  
Ign:3 https://deb.globaleaks.org bullseye/ InRelease
Get:7 https://deb.globaleaks.org bullseye/ Release [750 B]
Get:8 https://deb.globaleaks.org bullseye/ Release.gpg [833 B]
Err:8 https://deb.globaleaks.org bullseye/ Release.gpg
  The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
Fetched 833 B in 2s (529 B/s)
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://deb.globaleaks.org bullseye/ Release: The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Failed to fetch http://deb.globaleaks.org/bullseye/Release.gpg  The following signatures were invalid: EXPKEYSIG 32E6792624045008 GlobaLeaks software signing key <info@globaleaks.org>
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
globaleaks is already the newest version (4.14.8).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
---------------------
Can you help me, please? Thank you.</div>

**Comment by evilaliv3** [comment]
Thank you for the question, @esperti 

Reasons and solutions are posted in ticket: https://github.com/globaleaks/GlobaLeaks/issues/4040

**Comment by esperti** [comment]
To resolve issue:
rm /etc/apt/trusted.gpg
wget -qO- https://deb.globaleaks.org/globaleaks.asc | gpg --dearmor > /etc/apt/trusted.gpg.d/globaleaks.gpg
apt-get update

I can confirm, it is working.  Thanks @evilaliv3
