### ISSUE TITLE
Act on behalf of a whistleblower not working

### ISSUE THREAD

**Issue by elbill** [globaleaks/GlobaLeaks#4099]
### What version of GlobaLeaks are you using?

4.15.5

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

When pressing "act on behald of whistleblower", instead of the landing page we are transfered to the first page of recipient after logon. The gray banner is up (you are acting on a behalf of a whistleblower).

**Comment by evilaliv3** [comment]
Thank you @elbill 

This was already reported on other channels, and we are including a patch in a release 4.15.6 that will be out by the weekend.

**Comment by evilaliv3** [comment]
Closing as the bug is fixed and the fix will be included in 4.15.6
