### ISSUE TITLE
Different default language for different browser language

### ISSUE THREAD

**Issue by CEDEssedi** [globaleaks/GlobaLeaks#4103]
I move my discussion to this section because the operation of my system seems to be incorrect.

I have set 3 languages ​​in my system (Italian as default then English and Spanish).

From indications found in other cases, the system should use the browser language when opening the home page, but whatever the language of my browser, the system always appears in Italian.

Do I need to change settings or is it a bug?

Hepl me

Thank you

Greetings

### Discussed in https://github.com/orgs/globaleaks/discussions/4102

<div type='discussions-op-text'>

<sup>Originally posted by **CEDEssedi** June 10, 2024</sup>
Hello everyone,

I would like to know if it is possible to set a parameter in the link to globalaks (e.g. ?lang=es) to ensure that the language displayed is the one indicated in the link and not the system default.

In my case I would need to have a link for Italian, one for Spanish and one for English.

At this moment, if a no Italian person opens the link, the page will open in Italian and you will have to "manually" select the preferred language.

You can help me.

Thank you</div>

**Comment by evilaliv3** [comment]
Hello @CEDEssedi 

As already answered on your previous discussion you could use ?lang=es,it,en to enforce the selection of a specific language.

Instead when you do not specify any selection i confirm that the language used will be the one that your browser will request (e.g. if your browser is a italian browser you should get the platform in italian)

**Comment by CEDEssedi** [comment]
Good morning,

thanks for replying.

I had opened an issue because the system does not detect the browser language, but always comes out in the system's default language.

For us the solution of using the indication of the language in the link is more than fine, but it could be of common interest to understand why it happens that the browser language is not detected.

Thanks again 

Greetings
