### ISSUE TITLE
Message An update is available: 4.15.6 (Changelog) is shown when GlobaLeaks is updated to 4.15.6

### ISSUE THREAD

**Issue by v-j-f** [globaleaks/GlobaLeaks#4131]
### What version of GlobaLeaks are you using?

GlobaLeaks 4.15.6

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

OS: Debian 11
GlobaLeaks 4.15.3 is updated to 4.15.6
GlobaLeaks 4.15.6 is installed and running
```
# dpkg -l | grep glob
ii  globaleaks                     4.15.6                         all          Free and open-source whistleblowing software
```
But web interface shows message An update is available: [4.15.6 (Changelog)] in the Home tab and in the Changelog tab shows Software version: 4.15.5

**Comment by evilaliv3** [comment]
Thank you @v-j-f, this is a known visual issue (with no impact) that will be solved by today emitting a release 4.15.7 including some bugfixing.
