### ISSUE TITLE
password dimenticata

### ISSUE THREAD

**Issue by ntavella1** [globaleaks/GlobaLeaks#4135]
### What version of GlobaLeaks are you using?

2024

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

non ricevo la mail per recuperare la password all'indirizzo ntavella@comune.melzo.mi.it; ho già verificato nell'indesiderata ma non c'è nulla

### Proposed solution

rigeneratemi voi la password per favore

**Comment by evilaliv3** [comment]
buongiorno, 

le ho inviato un link di reset all'indirizz anticorruzione@comune.melzo.mi.it che è l'indirizzo associato alla vostra piattaforma.

per supporto del progetto whistleblowingpa vi invitiamo per futuri contatti a scriverci all'indirizzo: info@whistleblowing.it
