### ISSUE TITLE
Not able to install (according to server / hosting support) Openleaks because Plesk is in use 

### ISSUE THREAD

**Issue by awescure** [globaleaks/GlobaLeaks#4146]
### Proposal

Hello, I wanted to install Global Leaks after my test. I have rented a server from Host Europe for this purpose. Host Europe support has now informed me of the following:  "Unfortunately, we had to realize that the desired installation of the Global Leaks software is not possible natively in Plesk, as both Plesk and Global Leaks claim port 8443 for themselves. As an installation is therefore only possible 'bypassing Plesk', we are unfortunately unable to install the software functionally"

Since I have users and max. 1st. Level, I can't get any further, but I would like to use the Globa Leaks web application. 

Andreas

### Motivation and context

Without support, i cannot use and support Global Leaks, which I prefer in the future

**Comment by evilaliv3** [comment]
hello, thank you for your feedback. Actually you could not use your Plesk server. To use globaleaks you need a dedicated server or a virtual private server running a plain Ubuntu or Debian but y
