### ISSUE TITLE
Wrong Tag Dockerhub

### ISSUE THREAD

**Issue by cdftrew** [globaleaks/GlobaLeaks#4150]
### What version of GlobaLeaks are you using?

v4.15.6

### What browser(s) are you seeing the problem on?

Chrome, Microsoft Edge

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

I think the tag on the docker hub page is wrong: https://hub.docker.com/r/globaleaks/globaleaks/tags
The latest release shows v4.14.8 but it shoud be v4.15.8

**Comment by evilaliv3** [comment]
Corrected! Thank you @cdftrew
