### ISSUE TITLE
Translation issue in "Revoke access"

### ISSUE THREAD

**Issue by evariitta** [globaleaks/GlobaLeaks#4154]
### What version of GlobaLeaks are you using?

4.15.8

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

The "close" button in the Revoke Access window is forced to be in English in all language versions. It is not possible to set a translation.
![image](https://github.com/user-attachments/assets/67352079-e455-4554-9b3c-881f61efd18d)

**Comment by evilaliv3** [comment]
Thank you @evariitta 

Today we released the new version 5.0.0 where this should be fixed.
