### ISSUE TITLE
Problem with update 4.15.9

### ISSUE THREAD

**Issue by eleibr** [globaleaks/GlobaLeaks#4158]
### What version of GlobaLeaks are you using?

4.15.9

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows, macOS

### Describe the issue

We have updated version from 4.15.8 to 4.15.9 but when I log in as administrator, results version 4.15.8 also if changelog shows 4.15.9 update.
If I try to update again it tells that version is already 4.15.9 but the pop-up says that there is an update to install (4.15.9).

![image](https://github.com/user-attachments/assets/62e08dfd-3efa-4e13-91c9-b39f1b3eac98)

![image](https://github.com/user-attachments/assets/24cfea32-f140-47ae-8406-e38ce4583ceb)

**Comment by evilaliv3** [comment]
Thank you @eleibr 

Actually this was a minor defect (just visual of release 4.15.8). You can simply ignore this and eventually update to the new 5.0.0
