### ISSUE TITLE
Submission list  - submission last updated date does not refresh properly

### ISSUE THREAD

**Issue by aetdr** [globaleaks/GlobaLeaks#4161]
### What version of GlobaLeaks are you using?

4.15.4

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

Hi @evilaliv3 

When a submission is updated by reciever, normally it is possible to navigate to the submission list, click on the refresh button, and see the submissions update date change.  At the same time the changed submission gets highlighted with bold text.

 This functionality works initially, but after a comment or two does not work any more. 
Clicking on the refresh button will not update date and no bold text is shown.

As this is the way recievers usually check for updates from whistleblowers, they are worried that they do not get notified of updates from whistleblowers.

From my testing, updates from whistleblowers are highlighted correctly. Only updates from recievers are affected.

**Comment by evilaliv3** [comment]
Hello @aetdr ,

do you mind retesting this on the latest version?

I do not consider this issue exists there; maybeit was a bug in 4.15.4

**Comment by aetdr** [comment]
Hi @evilaliv3 

We are not at that version yet. Usualy we wait a bit after major versions release before we move forward.

Anyway, if you as reciever just keep posting comments on a particular submission, and check the page with the refresh button in parallel, than, it would work at first, but eventually it stops.

I will test this again when we are moved to the new release..

**Comment by evilaliv3** [comment]
Closing as stale. Please reopen it if you have any additional input.
