### ISSUE TITLE
Questionnaire survey not showing up anymore after update to 5.0.0

### ISSUE THREAD

**Issue by kairos322** [globaleaks/GlobaLeaks#4162]
### What version of GlobaLeaks are you using?

5.0.0

### What browser(s) are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

I've updated my Globaleaks instance from 4.15.5 to 5.0.0 and questionnaires/channel that used to work do not show anymore. Even after trying to create a new channel with the default GLOBALEAKS questionnaire I see the following error in the dev console:

![image](https://github.com/user-attachments/assets/5960e7f0-dfed-46ef-9a36-6d98e1198721)

**Comment by evilaliv3** [comment]
Thank you for reporting this @kairos322 

Actually the console error that you are reporting does not seems to be related to your issue.

Would you please provide a link to your site or some screenshots and instructions on how to replicate your configuration?

\cc @msmannan00

**Comment by evilaliv3** [comment]
It would be great actually @kairos322 if you could share here or to me a copy of your questionnaire, to see if the defects lie in some rarely used options.

You may find me directly on community.globaleaks.org

**Comment by kairos322** [comment]
Hi @evilaliv3. Thanks for your time and responses.

I'll send you a link privately.

**Comment by evilaliv3** [comment]
Fixed in commit: https://github.com/globaleaks/GlobaLeaks/commit/a58a20c87899047142643b54c7b23966e67740c1
