### ISSUE TITLE
CSS got messed up after update to 5.0.0

### ISSUE THREAD

**Issue by HessamAyoubi** [globaleaks/GlobaLeaks#4163]
### What version of GlobaLeaks are you using?

5.0.0

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

After updating to 5.0.0, previous custom css does not apply anymore and the page looks like this with blue background.
![image](https://github.com/user-attachments/assets/635c230c-0e0b-4f99-a580-62041d178e56)
Also I can not upload a new CSS file, when I try to enable it, it asked for password but it doesn't do anything after input.
![image](https://github.com/user-attachments/assets/b6855aee-509f-4de1-a588-07e25ee10dd8)

What should I do here to fix the CSS?

**Comment by evilaliv3** [comment]
Thank you @HessamAyoubi 

The release 5.0.0 features a new client based on Angular 18 and bootstrap 5 and it is very likely that your CSS would need some adaptations becauuse you could have based you curstomization on some CSS IDs or classes that may have varied.

If you would like please feel free to load here your css fil or you culd pass it to me on community.globaleaks.org and we may give it a look.

**Comment by evilaliv3** [comment]
Closing as stale. Please reopen it if you have any additional input.
