### ISSUE TITLE
Customized sub-status expiring days not working

### ISSUE THREAD

**Issue by larrykind** [globaleaks/GlobaLeaks#4177]
### What version of GlobaLeaks are you using?

4.15.5

### What browser(s) are you seeing the problem on?

All

### What operating system(s) are you seeing the problem on?

Linux

### Describe the issue

If a new sub-status is created using the feature "Set expire after X days" it seems to be not working, the report is always there and logs are not showing as usual the row "XX-XX-2024 02:00 | delete_report | system".
The channel used for the report has a default expiration set after 5 years.

**Comment by evilaliv3** [comment]
Thank you @larrykind 

I've fixed this issue and i'm about to release a 5.0.3 including the correction.

We are not considering issuing fixes for previous releases but if you need to fix your setup you could manually apply the same patch.

**Comment by larrykind** [comment]
Thank you @evilaliv3. 
After the patch was applied, what will happen to reports that are supposed to be deleted in the days before? Will they be deleted anyway?

**Comment by evilaliv3** [comment]
Thank you @larrykind for your question.

Since the bug was in place, it was not possible for users to change the status of the report.

**Comment by evilaliv3** [comment]
Fixed and fix included in release 5.0.3

**Comment by evilaliv3** [comment]
Tank you @larrykind 

Actually i confirm the errors as for points 1. and 2. in your comment that will be fixed in release 5.0.5 but the feature seems to work as expected in the other situations.

I suggest you to retry on 5.0.5
