### ISSUE TITLE
Problem to upload a file from the receiver

### ISSUE THREAD

**Issue by marcopvl** [globaleaks/GlobaLeaks#4178]
### What version of GlobaLeaks are you using?

5.0.3

### What browser(s) are you seeing the problem on?

Chrome, Firefox

### What operating system(s) are you seeing the problem on?

Windows

### Describe the issue

There are problems to upload a file from the receiver.
The receiver can't upload a file, it seems the upload-button is disabled.
Please see the 3 pictures attached.

Thanks in advance.
Best regards.

![image1](https://github.com/user-attachments/assets/04b0dbd5-1e89-44a4-b4dc-605abca6af7c)
![image2](https://github.com/user-attachments/assets/3b7b6b52-888d-4700-aa82-fe7036009835)
![image3](https://github.com/user-attachments/assets/1299df93-3997-4b4c-a130-f34d1c6cd91d)

**Comment by evilaliv3** [comment]
@marcopvl : This interface currently requires that you first describe your file and then you upload it.
