### ISSUE TITLE
Securely contact the administrator of the node

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#422]
It maybe desirable (low priority feature) that an unknown visitors of a globaleaks's based initiative would like to get in contact with the administrator of the platform.

This ticket is about implement a functionality to let anyone to contact securely the administrator of the node. 

The messages received from the web interface for the admin, should be text only with no files attachment functionalities.

The messages only provide pre-configured form such as "Reason of inquiry" and "Inquiry" with no ability to configure it. 

The messages are dispatched, in a PGP encrypted format, via email to the administrator.

The administrator can enable this functionality from the web interface.

The administrator must upload his PGP key and configure the email of the node in order to enable this functionality.

The link to contact the administrator must be available from the main interface.
##

**Comment by evilaliv3** [comment]
Related to: https://github.com/globaleaks/GlobaLeaks/issues/2647

**Comment by evilaliv3** [comment]
Closing in favour of https://github.com/globaleaks/GlobaLeaks/issues/422

**Comment by evilaliv3** [comment]
Very related to: https://github.com/globaleaks/globaleaks-whistleblowing-software/issues/2647
