### ISSUE TITLE
Procedure to provide, at a later stage, "proof of authorship" of the whistleblower

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#423]
One GlobaLeaks adopter (italian media), asked for a feature that would allow the whistleblower, to identify at a later stage himself as the author of a specific submission within the respect to the Receivers.

The use scenario is:
- The Whistleblower make a submission
- The Receivers handle it
- The submission expire
- The Whistleblower decide, at a later stage for some kind of reasons, to contact the Receivers via OOB (Out of Bound) channel, even in person.
- The Whistleblower need a way to provide, to the Receiver he is going to contact/meet, a proof of authorship of the submission (now expired).

The idea is to generate and show to the Whistleblower and to Receivers an "authorship code" that he can save and show to the Receiver at a later stage, if he decide to contact them again.

The drawback of this "simple solution" is that also the Receivers maybe able to "fake the whistleblower" having the authorship code.

@hellais had some ideas to use blind signature or some other crypto method.

**Comment by evilaliv3** [comment]
Closing this ticket in favor of the more recent: https://github.com/globaleaks/GlobaLeaks/issues/3397
