### ISSUE TITLE
GlobaLeaks does not scale on very high number of submissions

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#446]
GlobaLeaks does not scale on very high number of submissions because the storage of files is done into a single directory over /var/globaleaks/files/submission/$FILE .

This ticket is about introducing support for storage of files with directories and subdirectories.

It maybe an hash-three or organized over a directory structure with dates like /var/globaleaks/files/submission/2013/07/01/$FILE

**Comment by evilaliv3** [comment]
As we are considering reducing more more the usage of the filesystem this ticket is now deprecated.

In addition since it was opened files are not saved anymore with the original filename but with a random UUID.
