### ISSUE TITLE
Brainstorm Continuous Integration with Browser Testing

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#448]
This ticket is to brainstorm, collect links, make consideration on introducing a Browser Testing Continuous Integration for GlobaLeaks.

This would let, not just to test current globaleaks backend and packaging, but also catch major incompatibility issues between GLClient and various browsers.

The integration of #437 would be valuable within that process.

**Comment by evilaliv3** [comment]
closing this ticket as Protractor has been currently adopted and integrated with Saucelabs and all the related code is already in place on devel branch
