### ISSUE TITLE
The user must be able to upload it's PGP key

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#470]
The user must be able to upload it's PGP key.

Most web software supporting PGP, that's because all key management software does provide "export functionality" for public keys, but not "clipboard copy" .

This ticket is to improve the usability of the PGP key activation by having them uploaded rather than copy/pasted.

**Comment by origliante** [comment]
@fpietrosanti outdated?

**Comment by fpietrosanti** [comment]
@origliante dunno, ask @evilaliv3 as i lost myself in the ticketing status of e2e. If the Receiver can upload a public key from a file, then it's not outdated but it's implemented and, the related code commit, shall be linked to the tickt.

**Comment by evilaliv3** [comment]
no this is not uoutdated at all. receivers will continue to need the possibility to load they PGP key for notifications (that is nothing related to end2end encryption).

**Comment by evilaliv3** [comment]
The user since various time has the possibility to upload/change it's own key.

The only think that still is not possible is to upload the key as file, but this specific possibility is tracked by issue: Closing the ticket as outdated.

**Comment by fpietrosanti** [comment]
That's still needed when client-side encryption will be in place and it's required because all PGP desktop software do provide the default option to "export public key" rather than "put into clipboard" .

**Comment by evilaliv3** [comment]
dear friend, read better my comments; https://github.com/globaleaks/GlobaLeaks/issues/792 is tracking of that. :)
