### ISSUE TITLE
There's no client side validation of submission fields for number, email, phones, url

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#474]
There's no client side validation of submission fields for number, email, phones, url .

This ticket is about introducing client side validation for those submission fields.

See screenshot attached

![screen shot 2013-07-24 at 1 31 27 pm](https://f.cloud.github.com/assets/770363/848154/fe0821c8-f454-11e2-8371-042a4bacf5ac.png)
##

**Comment by evilaliv3** [comment]
all this things still need to be implemented as i removed them and should be readded in the future so this is currently a dead ticket.

**Comment by fpietrosanti** [comment]
@evilaliv3 why closing a ticket that's still in the same condition? The missing validation is still there to be implemented

**Comment by evilaliv3** [comment]
and why you open ticket without understanding why they are closed?
currenly we do not have any of this: email, number, email, phonenumber field type so having a ticket that talks about their validation is like talking about eating now the food i will cook tomorrow. antani!

**Comment by evilaliv3** [comment]
Validation exists and is configurable by means of default regexps for common types (numbers, emails, phone numbers) and optionally it is possible to configure a custom regexps.
