### ISSUE TITLE
Evaluate if BREACH apply to tor2web/globaleaks 

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#501]
Following the recent release of BREACH attack to SSL, we should analyze if globaleaks, when accessed behind tor2web, is vulnerable to this kind of attack.

If so, which has to be the mitigation strategies.

http://bit.ly/141SfIq

**Comment by evilaliv3** [comment]
Closing the ticket as outdated and not affecting nor globaleaks/tor2web.
