### ISSUE TITLE
Improve visualization of comments and messages

### ISSUE THREAD

**Issue by hellais** [globaleaks/GlobaLeaks#531]
This ticket deals with improving visualizationon of commets by showing only a subset of all the comments and allow the user to click on "view more" to see the rest.

**Comment by evilaliv3** [comment]
Supporting some of the activities necessary to the publeaks project i've implemented the pagination for Messages and Comments.

Here are the screenshots of the current interface:
![Screenshot-2019-10-8 evilaliv3 gmail com](https://user-images.githubusercontent.com/217034/66397547-5afb3400-e9dc-11e9-964e-1d0be4f0c52b.png)

**Comment by evilaliv3** [comment]
Closing as implemented.

**Comment by evilaliv3** [comment]
-
