### ISSUE TITLE
Improvements to cover traffic widget

### ISSUE THREAD

**Issue by hellais** [globaleaks/GlobaLeaks#534]
Currently the cover traffic widget just sends requests of random size at random intervals.

To make it harder for an attacker based on timing and requests size to determine that a user is a user of GlobaLeaks and not a widget user, we should profile GLClient and reproduce similar requests in the decoy traffic widget.

We could create "request profiles" for every action (the first load, create a new submission, access the tip interface, etc.).

These actions could then be performed in some order or in random order.

I think the actions we want to simulate through such widget are just the submission steps:
1. User visits the landing page of the submission system.
   These are N requests and are fixed size, the size of the responses will only change if some configuration on the node is changed. 
2. User accesses the /submission URI and performs a submission. These are N requests of variable size and the response are generally of fixed size.
3. The user accesses the Tip interface. These are N requests and the responses are of variable size. The size of the response is proportional to the size of the request in the previous step.
##

**Comment by evilaliv3** [comment]
Closing as outdated
