### ISSUE TITLE
The whistleblower session expire after 60 minutes also if there is a file upload in progress

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#536]
The whistleblower session expire after 60 minutes also if there is a file upload in progress.

If a whistleblower need to upload a file or multiple files, whose's upload session last more than 60 minutes, the submission will fail.

This ticket is to allow a whistleblower to make file upload longer than 60 minutes.

This fix can be done by avoiding the Whistleblower's sessions expire if there is an ongoing file upload in progress.

**Comment by NSkelsey** [comment]
The current implementation of GL Session handles this.
