### ISSUE TITLE
AngularJS cannot be packaged into debian repository due to a software licensing issue with Angular.JS

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#543]
This is in italian because addressed to hermes's lawyers, for please use google translate:
"
Una libreria javascript chiamata JSHINT da cui dipendono varie altre librerie (tra cui anche grunt da cui dipende angular.js da cui dipende GlobaLeaks) è rilasciata sotto una licenza MIT modificata.

La modifica alla licenza MIT e' la clausula:

"The software shall be used for good not evil."

http://news.cnet.com/8301-30685_3-10422338-264.html

Questa clausula fa sí che il software sia classificato come non-free e quindi non può essere parte di progetti free software come ad esempio debian.

Mi sono ritrovato in questo problema mentre veniva pacchettizzato ooni-probe per debian.

Le procédure di packaging debian dicono che tutte le dipendenze devono essere pacchettizzate come un pacchetto a se e non possono essere scippate dentro al tuo .deb (anche nel caso di dipendenze javascript).

Questo significa che se vogliamo avere GlobaLeaks dentro debian non lo potremo fare perché GLClient non può essere pacchettizzato in quanto angular.js non può essere pacchettizato perché grunt non può perché JSHINT non può.

Vedete ad esempio quello accaduto qui:
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=673727

C'e' stata una discussione interessante sul github di jshint: https://github.com/jshint/jshint/issues/1234.

Quello che è emerso e' il seguente:

L'autore originario, Douglas Crockford, quello che ha scelto questa licenza molto strampalata, ha scritto l'ultimo commit per JSHINT nel 2011.

Da quel giorno ad oggi il progetto e' nelle mani di Anton Kovalyov che ha sostanzialmente cambiato tutto il codice ed e' la persona che al momento mantiene questo progetto.

Ho usando un po' di tool per trovare similitudine di codice tra l'ultimo commit di Douglas Crockford (https://github.com/jshint/jshint/commit/40e3f73) ad oggi.

E' uscito fuori che il numero di righe duplicate sono 195 in un progetto che ha 9000 righe di codice.

Quale e' il modo giusto di procedere? Vanno refactorate quelle righe di codice o si può procedere al relicensing dritto per dritto?"
"

/cc @hellais 
##

**Comment by NCommander** [comment]
Angular license issues resolved, closing.
