### ISSUE TITLE
If a notification (or exception) email is not delivered, an exception is generated

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#547]
If a notification (or exception) email is not delivered, an exception is generated.

To reproduce the issue, trigger an exception and/or a notification (this has still to be investigated).

This ticket is to handle this issue carefully, by logging the error in the log file and eventually in standard output.

Below an example email that i received, following the erroneous sending of an email due to a remote SMTP error:

Source: Linux remotehost 3.5.0-36-generic #57~precise1-Ubuntu SMP Thu Jun 20 18:21:09 UTC 2013 x86_64

Version: 2.24.9

twisted.mail.smtp.SMTPDeliveryError Indicates that a delivery attempt has had an error.

SMTPDeliveryError: 451 No recipients accepted
globaleaks-stackexception@lists.globaleaks.org: 451 4.3.5 <tor31.anonymizer.ccc.de[217.115.10.131]>: Client host rejected: Server configuration error
>>> MAIL FROM:<sendaccount@lists.globaleaks.org>
<<< 250 2.1.0 Ok
>>> RCPT TO:<globaleaks-stackexception@lists.globaleaks.org>
<<< 451 4.3.5 <tor31.anonymizer.ccc.de[217.115.10.131]>: Client host rejected: Server configuration error

**Comment by evilaliv3** [comment]
this should be now handled thanks to various fixes by @origliante.
