### ISSUE TITLE
Improve usability of globaleaks customization process to make it more easier

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#582]
This ticket is to Improve usability of globaleaks customization process to make it more easier .

Today each adopter willing to customize globaleaks must have a separate installation of globaleaks running from source codes, following development procedures that maybe prone to have much more bugs and be more complicated that what an average sysadmin may require just to configure a custom HTML template.

For that reason this ticket propose to make it possible for a globaleaks sysadmin to setup the GLClient HTML template customization environment from the standard GlobaLeaks package, without the need to setup globaleaks from source code.

Also the maintenance process of re-build of GLC across new releases must be considered, to bring to the minimum level of complexity the software lifecycle effort also during upgrades of new versions, while using custom built template.

This would effectively make "more easier" (yet still improvable) for an adopter to customize their HTML template.

/cc @hellais

**Comment by NSkelsey** [comment]
Outdated.
