### ISSUE TITLE
If Whistleblower upload a file while on it's Tip, with expired session, (s)he is given an error

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#603]
If Whistleblower upload a file while on it's Tip, with expired session, he is given an error "Precondition failed" but is not informed by the UI that his session has expired.

This ticket is to notify to the Whistleblower that the session is expired, bringing him to the next action such as insert again his receipt.

![screen shot 2013-09-08 at 11 03 56 pm](https://f.cloud.github.com/assets/770363/1103854/48c15c7c-18ca-11e3-8a4c-ca002fc0db5a.png)
##

**Comment by hellais** [comment]
Is this still relevant?

**Comment by evilaliv3** [comment]
i think so. let's keep this open a little and close when verified that what happens on this situation is somehow handled.

i will take care of this evalutation and eventually of marking improvements.

**Comment by evilaliv3** [comment]
reviewed and i confirm that all seems handled correctly.

**Comment by fpietrosanti** [comment]
So, now on an expired session with the Tip in front of the Whistlblowr, if i click "upload", it will automatically detect such condition and BEFORE letting me upload stuff, it will ask me again for a Receipt (or somthing like that)?

**Comment by evilaliv3** [comment]
Ah no, you are right. i've simply checked that now unhandled exceptions were scattered.

**Comment by evilaliv3** [comment]
The implementation in commit https://github.com/globaleaks/GlobaLeaks/commit/85e583de77eedc1d43d29b353d88b6140a2ae9ba  addresses this ticket by:
- recognizing user activities (usage of mouse and keyboard) and implementing keep alive of sessions.
- recognizing if the session is expired and closing the application by redirecting the user to the homepage.

This implementation will be included in the stable release starting from release 4.5.4
