### ISSUE TITLE
Add support for generating keys for unittests

### ISSUE THREAD

**Issue by hellais** [globaleaks/GlobaLeaks#615]
In https://github.com/globaleaks/GlobaLeaks/issues/606 came up the necessity to test keys that expire at a given time frame.

We are currently hardcoding keys inside of the GPG testing code without specifying how those keys were generated or what properties they have.

I would suggest we add support for generating keys to be fed to the unittest. Since key generation is a process that can require time (mainly due to entropy collection) we can either do a hack to seed more entropy in the key generation phase (like seed it with a large number of "A" chars, obviously leading to an insecure key) or just implement some caching for the generated keys.
##

**Comment by evilaliv3** [comment]
the only test that would benefit of having generation of keys is a test with a key that on a first load is valid, and after 5 minutes is expired but it could be mocked by first loading a valid key, and then altering the database putting a key that is expired.

for all the rest we can have two keys:
- an expired key
- a key that never expire

for this reason i think we can close the ticket.
