### ISSUE TITLE
String encoding testing/refactoring

### ISSUE THREAD

**Issue by hellais** [globaleaks/GlobaLeaks#616]
As suggested by @nathan-at-least in #584 we should be sure to encode in utf-8 as late as possible and keep using `unicode` for as long as possible.

In preparation of the partner-x deployment we went for the most robust solution we could safely implement in the least amount of time.

We should now actually look to investigate these kinds of issues and provide unittests that hunt for these kinds of bugs in other parts of the code. Then we should move the encoding done https://github.com/globaleaks/GLBackend/commit/10dd97f12a0e66d3811de066fb1599dbaaf1bdc5 into the `notification.py` module and wherever else an underlying library requires it.
##

**Comment by evilaliv3** [comment]
Closing the ticket as outdated.
