### ISSUE TITLE
Add support for creating and rendering content with markdown

### ISSUE THREAD

**Issue by hellais** [globaleaks/GlobaLeaks#618]
GLClient should be aware of the fact that certain elements can be in markdown and it should expose a way to edit markdown from the admin interfaces and visualise it in markdown on the client.

I would suggest we collect here all the places where we want to have markdown support.
##

**Comment by evilaliv3** [comment]
Closed in favour of the duplicated (but more updated) https://github.com/globaleaks/GlobaLeaks/issues/1101
