### ISSUE TITLE
Enable the adopter to load up it's own custom, multi-language selection landing page to globaleaks

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#628]
It has been requested by an IRPI the ability to load up their own custom, multi-language selection landing page to globaleaks to be able to load up to GlobaLeaks.

Their goal is to provide a main page with two big selection, one in Italian and the other one in English.

Then when the whistleblower select the right language, be redirected to the globaleaks interface in the right language

The requested feature is to enable the adopter to:
- Load a custom landing page (HTML+CSS) in place of the default "Index"
- Enable the designer of the landing page, to redirect the whistleblower to main page in a specific language
##

**Comment by evilaliv3** [comment]
Closing as outdated and not in line with current ideas.
