### ISSUE TITLE
Clicking on the link on the received notification email, "Not authenticated" message it's shown 3 time

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#629]
The receiver, by clicking on the link on the received notification email, see the error message "Not authenticated" message 3 time, only after it's shown the login box.

This is probably because the URL sent in notification contain the UUID of the TIP and GLC try to access it immediately after login.contain GLC try to access the 

Fixing this ticket require:
- Avoid showing "not authenticated" error message when clicking on notification link
- Provide a very specific message to the receiver, that he have received a notification and he should write his username and password.
##

**Comment by evilaliv3** [comment]
Closing as outdated and solved by current client logic
