### ISSUE TITLE
Load on globaleaks website thanks and logos of JetBrain for providing us free licenses

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#641]
Load on globaleaks website thanks and logos of JetBrain for providing us free licenses of PyCharm and WebStorm

http://www.jetbrains.com/company/press/logos.html
##

**Comment by fpietrosanti** [comment]
Add also:
- Google Cloud
- OTF Cloud

**Comment by evilaliv3** [comment]
This ticket could be closed as licenses are no longer sponsored.
