### ISSUE TITLE
Make a web page on globaleaks website about existing users and use cases

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#642]
Make a web page on globaleaks website about existing users and use cases.

The web page must include the major experience we've seen being used by globaleaks, including the logo of the initiative, a screenshot of their globaleaks site, a link to their project website initiative and a quote from the project leaders.

**Comment by evilaliv3** [comment]
Closing as current site hosts a page specifically designed for this reason: https://www.globaleaks.org/usecases/
