### ISSUE TITLE
Multi-Select submission fields, marked as required, are not enforced by the GL Client

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#652]
Multi-Select submission fields, marked as required, are not enforced by the GL Client.

The Whistleblower is given the ability to apply a submission also without selecting the right choice from a multi-select submission field that has been configured and marked as required.

This ticket is to improve the globaleaks client by enforcing the "required" flag on multi-select submission field.
##

**Comment by hellais** [comment]
Is this bug even still relevant?

@fpietrosanti @vecna @evilaliv3 ?

I think this can probably be closed.

**Comment by evilaliv3** [comment]
this still need to be fixed.

there should be a validator function that should consider a multiselect with required option set valid only if at least one of the selection checkbox is marked.

**Comment by evilaliv3** [comment]
Implemented by @vondrakk in https://github.com/globaleaks/GlobaLeaks/pull/2163

thank you vondrakk!
