### ISSUE TITLE
DNSLookup failure while sending notification email trigger unhandled exception

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#657]
DNSLookup failure while sending notification email trigger unhandled exception

Following an example:
Source: Linux qq 3.8.0-31-generic #46-Ubuntu SMP Tue Sep 10 19:56:49 UTC 2013 i686
Version: 2.27.11
twisted.internet.error.DNSLookupError DNS lookup failed
DNSLookupError: DNS lookup failed: address \'mail.headstrong.de\' not found: [Errno 110] Connection timed out.
##

**Comment by evilaliv3** [comment]
Closing as outdated.
