### ISSUE TITLE
Improve GlobaLeaks wikipedia entry

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#661]
Current wikipedia entry https://en.wikipedia.org/wiki/GlobaLeaks is outdated and is missing many information.

This ticket is to improve the page with:
- History of releases
- Link to all adoptions (create a list of all the initiatives using it and make corresponding wikipedia entry)
- List of developers
- List of the sponsor (like USAID in 2011 and OpenTechFund in 2012-2013)
##

**Comment by evilaliv3** [comment]
All what described is somehow implemented by the uptodate wikipedia page.

The list of the known initiatives is now maintained on our official website: https://www.globaleaks.org/implementations/

![image](https://cloud.githubusercontent.com/assets/217034/21271701/41f2b08a-c3bc-11e6-831d-3e56e3a94c6e.png)
