### ISSUE TITLE
Make a wikipedia entry for each of the globaleaks adopter

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#662]
This ticket is to make a wikipedia entry for each of the globaleaks adopter.

The goal is to create a new wikipedia entry for each of the initiative and to notify the owner to enrich it with links to news and activities related to it
##

**Comment by evilaliv3** [comment]
For how things are going, i do not consider this any more of interest.

The users that wants (like AWP) are maitaining their wikipedia page, and independent journalists and wikipedia users are starting creating entries naturally.
