### ISSUE TITLE
Write contributing guidelines on github

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#682]
In order to facilitate contribution to the project, we need to write a web page with "Contributing guidelines", like for example https://github.com/jcbrand/converse.js/blob/master/CONTRIBUTING.rst .

The good stuff is that github,whenever a new ticket or pull request is going to be open, will always warn the user doing so to before reading the "Contribution Guideline".

**Comment by evilaliv3** [comment]
Duplicated ticket of https://github.com/globaleaks/GlobaLeaks/issues/1263
