### ISSUE TITLE
Check if the user is adopting the latests version of Tor Browser Bundle

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#707]
This feature is to introduce a check if the user is adopting the latests version of Tor Browser Bundle.

This is a security awareness feature that should be implemented in order to advise the whistleblower, coming from Tor, that he's not using the latests version of TBB.

The administration need to be able to explicitly configure if the whistleblower is allowed to make submission:
1) In presence or not of TBB (ex: Chrome + Tor)
2) In presence or not of latest version of TBB

This ticket imply:
a) Fingerprinting that the user is using TBB
b) Detecting which version he is using
c) Making the behavior configurable
d) Defining all appropriate security text warning/disclaimer/messages

For "a" we should use the technique described at https://github.com/freedomofpress/securedrop/issues/101 .

For "b" we should check the version against
https://check.torproject.org/RecommendedTBBVersions

**Comment by fpietrosanti** [comment]
Because the Tor Browser fingerprint is likely going to fixed (see email from mike perry of 6 Feb 2015 on OTF-projects mailing list), we need a new way to do it. The best way to do it, is to do in a way that does not require loading of external, network-reachable resources.

It's suggested to use the very same TBB's method that load TorButton resources (TBB's start page).

This method will only work for user with TBB, that's a constraint we can live with for now.

**Comment by fpietrosanti** [comment]
Asked on tor-dev for an opinion https://lists.torproject.org/pipermail/tor-dev/2015-February/008236.html

**Comment by fpietrosanti** [comment]
The solution could be:
IF (URL != .onion); then
  { IF(URL = HTTPS); then
    Check_For_Tor2web_Headers_telling_we_are_on_Tor_or_Not();
 else
  Hard_Fail_as_we_do_not_serve_globaleaks_over_http();
 fi 
 }
ELSE
 check_tor_with_check_torproject() // https://check.torproject.org/?TorButton=true
FI

**Comment by evilaliv3** [comment]
this was implemented by me but i've removed the code in commit.:https://github.com/globaleaks/GlobaLeaks/commit/d7131d3115150380f74d83434546a1e9f7a5181a while addressing https://github.com/globaleaks/GlobaLeaks/issues/1149

closing the ticket as it is not possible anymore to implement such a feature.
