### ISSUE TITLE
Document procedure to setup a .onion vanity name

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#712]
It has been reported by some adopter that it would be very valuable to have a vanity name for their .onion.

This ticket is to document the procedure to setup a .onion vanity name in a globaleaks system.
##

**Comment by evilaliv3** [comment]
This ticket could be re-evaluated in relation to the integration of txtorcon and the possibilities of configuration directly via GlobaLeaks of an ephemeral HS with a custom key generated on the fly.

**Comment by NSkelsey** [comment]
This can be done with the use of `gl-admin setvar onionservice` and the properly formatted use of `gl-admin setvar tor_priv_key`

**Comment by evilaliv3** [comment]
With onion services version 3 this ticket lost value.
