### ISSUE TITLE
Improve entropy of a GlobaLeaks system with HAVEGE algorithm

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#720]
Improving entropy is always a good stuff and crypto-experts that don't trust Linux kernel always appreciate it.

This ticket is to improve entropy of a globaleaks system with HAVEGE:
http://www.issihosts.com/haveged/faq.html

The task to be done are the following:
- Integrate Havege package as a globaleaks dependency
- Document it on the Wiki
- Document it into the Threat Model
- Prepare a section into the Wiki about "Encryption use in GlobaLeaks" summarizing all the uses of encryption in globaleaks

**Comment by fpietrosanti** [comment]
Info from securedrop https://github.com/freedomofpress/securedrop/pull/710

**Comment by fpietrosanti** [comment]
Info from securedrop https://github.com/freedomofpress/securedrop/pull/710

**Comment by evilaliv3** [comment]
Implemented!

**Comment by fpietrosanti** [comment]
Closing this ticket require improving:
- Wiki, in the encryption section
- Technical security specificati in Google docs (linked in main page)

**Comment by evilaliv3** [comment]
Right!

**Comment by evilaliv3** [comment]
documented!
