### ISSUE TITLE
Forced selection of all receivers

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#723]
It has been discussed with an adopter (IRPI) that it would be really nice to show on the submission interface ALL of the receivers, but without giving to the whistleblower the ability to select/deselect some of them.

Currently the staff of journos is represented as a "Single Receiver" that's IRPI.

However "behind that single receiver" there are multiple journos sharing an email alias and this single common GlobaLeaks access.

In order to improve transparency and gives better "Human Trust" to the Whistleblower, it would be better to have the Receivers to be published with their photos and bios.

However all of them MUST receive all the Tips, with no ability from the whistleblower to select "who will receive the Tip".

This ticket is to implement this feature, available as an optional selector on the context, that do provide "Forced Selection of all Receivers"  with a YES/NO flag.

**Comment by evilaliv3** [comment]
this has been implemeneted by me.

to achieve such a score all receiver should be configured as "Forcefully Selected"

the feature will be shipped in release 2.60.47
