### ISSUE TITLE
Provide a big Warning if the default email server is used for notification

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#724]
GlobaLeaks by default leave configured for the end-user an email server with an email account of globaleaks, to facilitate the testing of the software.

However it happened that some site went in production by using the default mailserver, that's obviously something that must not happen anymore.

This ticket is to provide a big Warning if the default email server is used for notification (es: the email server and/or the email account provided by default).

The warning must be shown:
- Over the submission web interface
- In the Receiver interface
- In the Admin interface

That way a website cannot go in "production" without noticing the issue.
##

**Comment by NSkelsey** [comment]
This is related to #1611

**Comment by NSkelsey** [comment]
Closing in favor of #1830.
