### ISSUE TITLE
Hidden Receiver functionality

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#735]
It has been requested to add a receiver that's not shown over the submission interface, but can be effectively receive a submission.

This ticket is enable configuring a receiver as "Hidden" .

In that case:
- The whistleblower does not see it on Submission
- The whistleblower does not see it on Tip Status
- The hidden can send comments, in that case will reveal it's unique user data to the whistleblower

**Comment by evilaliv3** [comment]
implemented by me. for this as for all advanced settings like this all the documentation is still missing so that i will take care of creating new tickets dealing with specific sections to be documented.

**Comment by evilaliv3** [comment]
This was removed long time ago for transparency reasons with respect to whistleblowers.

It was consider that iether the whistleblower should let send their submission to the organization, either to an announced selection of recipients.

Exposing some but then send to others is not considered safe in any way.
