### ISSUE TITLE
GlobaLeaks while loading the submission interface show some debugging information

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#739]
GlobaLeaks while loading the submission interface show some debugging information related to maximum selectable receivers.

This ticket is to avoid displaying those information while loading.

![screen shot 2013-12-16 at 11 30 09 am](https://f.cloud.github.com/assets/770363/1753443/2cf9273e-663d-11e3-8a03-95a84733c5c3.png)
##

**Comment by evilaliv3** [comment]
Closing the ticket as outdated.
