### ISSUE TITLE
Notification of upcoming Tip Expiry date

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#748]
It has been requested by a prospect adopter (amnesty international) to have a procedure to provide notification of upcoming expiration of Tip to receivers part of it.

The notification of tip expiration should be configurable from the receiver, both in term of enabling/disabling the feature, and in terms of timing remaining until expiration when they need to get notified.

That's specifically because some of the researcher are "in office" while some other are often travelling, so they may need very different configuration related to notification of upcoming tip expiry time.

**Comment by vecna** [comment]
well, for sure, in the notification_sched has to be catch this event, reported in the "activities" and eventually via email #921 I guess is a sub-ticket of this one.

**Comment by vecna** [comment]
I was checking the status of this issue, and is implemented, the Template are present, the email sent are these:

    Dear vecna,

    The submission [825] related to context something is going to expire in 48 hours.

    Log in and check it out before it's too late!

    The submission can be accessed:
    via Tor at: ADMIN, CONFIGURE YOUR HIDDEN SERVICE (Advanced configuration)!
    via Tor2web at: [Ask to your admin about Tor]

    Submission date: Tuesday 05 May 2015 14:35
    Expiration date: 06/05/2015

    Kind regards,
    Development Node

But the bug was preventing the triggering of the condition! Now I guess can be closed ?

**Comment by fpietrosanti** [comment]
Is it configurable as described in the ticket?
"The notification of tip expiration should be configurable from the receiver, both in term of enabling/disabling the feature, and in terms of timing remaining until expiration when they need to get notified."

**Comment by evilaliv3** [comment]
nope it's still not configurable, let's wait for that before closing the issue

**Comment by vecna** [comment]
To make it configurable, has to be updated the DB, I'll create a dedicated branch called database-21 from which I start the new branches, covering some of the feature that require it.

**Comment by evilaliv3** [comment]
great!

let's avoid working on the integration script.
in general i suggest always to avoid writing it before the moment that the patch is near to be integrated in devel. this will help reducing unneded work.

**Comment by fpietrosanti** [comment]
@evilaliv3 is this released?

**Comment by evilaliv3** [comment]
nope, it will be released by this week

**Comment by fpietrosanti** [comment]
Is this finished?

**Comment by vecna** [comment]
Yes, closing issue.
