### ISSUE TITLE
Improve post-submission "Receipt display message" usability and effectiveness

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#752]
It has been noted by an Adopter (publeaks) that only 50% of the whistleblower get back with their receipt.

It has been suggested to improve post-submission Receipt display message, with some better text and possibly a small explanatory image on what's the Receipt is, how he should save it (on the mobile phone for example), and why he should get back.

**Comment by evilaliv3** [comment]
this ticket has been superseded by a lot of others and being too much general with respect to the others can be closed.
