### ISSUE TITLE
gpg: keyserver communications error: general error

### ISSUE THREAD

**Issue by wanderer** [globaleaks/GlobaLeaks#772]
When using the install script I got 

Running: "gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 0x24045008"... FAIL
COMBINED STDOUT/STDERR OUTPUT OF FAILED COMMAND:
gpg: WARNING: unsafe ownership on configuration file `/home/*/.gnupg/gpg.conf'
gpg: external program calls are disabled due to unsafe options file permissions

I just manully ran pgp as my regular user and commented out this [line](https://github.com/globaleaks/GlobaLeaks/blob/master/scripts/install-ubuntu-12_04.sh#L554) and it worked
##

**Comment by origliante** [comment]
@fpietrosanti outdated

**Comment by fpietrosanti** [comment]
@origliante why is outdated?

**Comment by evilaliv3** [comment]
Closing as outdated.

In addition currently the run of gpg binary are handled using the DO function we implemented in the install script in order to carefully log errors and stop script execution.
