### ISSUE TITLE
optimize GLClient by avoid angular automatic "watch" on {{ }} directives.

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#774]
it seems that angular always creates automagically a "watch" when using a {{ var }} to print something.

this is because it creates various bindings and continues to reevaluate them causing a lot of CPU waste (from 10% to 50% for multiple watchs on a modern CPU).

@hellais @vecna @fpietrosanti: for now i've found only this solution that consists in a manual patch of every place where we have used {{}} in the application templates:

https://stackoverflow.com/questions/16559098/is-there-a-way-to-evaluate-an-angularjs-expression-in-the-template-just-once-ie

@PascalPrecht do you have any suggestion?

**Comment by fpietrosanti** [comment]
Is this fixed?

**Comment by evilaliv3** [comment]
yep, this can be definitely be closed as since a few we optimized things using the one way binding of angular 1.4
