### ISSUE TITLE
Analyze which dependency is missing to bring GlobaLeaks to official Debian/Ubuntu's repository

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#775]
This ticket is to analyze which dependency is missing to bring GlobaLeaks to official Debian/Ubuntu's repository.

At CCC Congress (Dec 2013) i've been told that many python packages that was originally missing from GlobaLeaks dependency has been included into Debian sid.

We should make a new analysis to understand what's still missing in order to be able to distribute globaleaks directly as part of Ubuntu and/or Debian packages with no additional dependency/installation script.

**Comment by evilaliv3** [comment]
let's close this as outdated and with no info in relation to the current deeep analysis done in 1515.
