### ISSUE TITLE
Improve PGP key loading into globaleaks by enabling "file upload" of pgp file

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#792]
This ticket is to improve PGP key loading into globaleaks by enabling "file upload" of pgp file.

Currently in GlobaLeaks it's possible to only copy/paste an ascii armored pgp key of the receiver.

This ticket is to improve the PGP key loading functionality by enabling also the upload of a PGP key "as a file" .

The file must be supported both as a binary pgp key or ascii armored pgp key.
##

**Comment by origliante** [comment]
@evilaliv3 is this closed in the latest release? is the client-side key generation code with drag and drop upload included?

**Comment by evilaliv3** [comment]
no this is still not included in the devel branch but only in the feature/end2end.

**Comment by evilaliv3** [comment]
this code still need to be finalized and integrated in end2end branch

**Comment by evilaliv3** [comment]
this would be now easy to be implement as OpenPGP.js is finally integrated in globaleaks and we should evaluate also to validate the textarea based on the keey validation in case of cut+paste.

**Comment by NSkelsey** [comment]
This will be implemented with the `inputFileChange` directive. I would like to simplify the interface and remove the text area entirely. There are a few interfaces that will be affected by this change.

The complete list:
- [ ] ./admin/users.html
- [ ] ./admin/mail/tab4.html
- [ ] ./partials/preferences/pgpkey.html

Finally we could add the key add back to the wizard as non-required optional choice, b/c now it is easier to use!

**Comment by NSkelsey** [comment]
We are going to copy Github's style.

![copyme](https://user-images.githubusercontent.com/1095794/29619416-5eb18fce-881b-11e7-9e4a-bd20e35aedb3.png)

Well sort of:

![encryption-add-btn](https://user-images.githubusercontent.com/1095794/29620066-1b6b4f00-881d-11e7-892e-c032b12c5aa9.png)

**Comment by NSkelsey** [comment]
The commit 44bb803 is based in the feature/2042 branch, which should have a short lifespan. A cherry pick into devel might be a good idea as we can apply these changes now also to the `admin/network/https_file_cfg.html` view.

**Comment by NSkelsey** [comment]
This has been implemented and will be released with `v2.72.0`
