### ISSUE TITLE
Flood Resiliency: Human Captcha

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#795]
In relation to the GlobaLeaks Submission Flood Resiliency Project documented at https://docs.google.com/document/d/1P-uHM5K3Hhe_KD6YvARbRTuqjVOVj0VkI7qPO9aWFQw/edit?usp=sharing this ticket is to implement Human Captcha support.

**Comment by vecna** [comment]
Implemented as a sum. To test it, go in /#/submission, refresh at least 5 times (means, 5 new submission in less than 10 seconds) await that Anomaly schedule run (every 10 seconds), and when you refresh again, you've to answer A + B.

you can fail three times (defined in globaleaks.utils.token)

**Comment by vecna** [comment]
This is integrated currently in master. The threshold analysis has to be done, but they are part of the whole Token impact analysis. Closing this issue.
