### ISSUE TITLE
Flood Resiliency: Per recipient notification limits

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#798]
In relation to the GlobaLeaks Submission Flood Resiliency Project documented at https://docs.google.com/document/d/1P-uHM5K3Hhe_KD6YvARbRTuqjVOVj0VkI7qPO9aWFQw/edit?usp=sharing this ticket is to implement per recipient notification limits.

**Comment by vecna** [comment]
Implemented first draft of digest: https://github.com/globaleaks/GlobaLeaks/tree/issue/921%2B748-expiration-notif /cc @evilaliv3

**Comment by fpietrosanti** [comment]
@vecna i'd suggest to make it configurable with a node-level and receiver-level settings as follow:

[Email Notification Preferences]
Maximum Notification Per Recipient per Hour: X (within this threshold there's no flood protection in place)

Anytime that limit is surpassed, we'll start limiting the outgoing notifications for that recipient to value Y/hour for K hours, just discarding any over-quota email notification.

**Comment by vecna** [comment]
discarding has never been considered an option (and this is very different from the needs recent requirement expressed by TI - never lose an email - ). 
And this is also completely different from the digest approach (for reduce notification). 

Anyway, I'll see in the next week what can be added, I guess the easier approach, is a receiver setting a maximum number of email per hour, and if it happen, digest became enabled for the next X hours.

**Comment by fpietrosanti** [comment]
Because email does not practically have *any informative content* creating composite emails made up of the content of the many unsent notification emails may just not be useful for end-user.

Discarding it's just the quicker and easier way to prevent a notification flood from being a problem.

Regarding this digest, is that specified or described functionally how it should work / which is the content / usefulness for the end-user? Is this approach formatting a completely new email with a summary of what's happened in the past X period (like "You received 5 comments on 3 Tips") or how does it work?

**Comment by vecna** [comment]
The goal was "do not modify the templates", so, at the moment, the digest is:

Mail Title: Tip (Number of Tip), File (number of file), Comment (number of comment)
Mail Content:

The Title of original mail 1
---------------
Content mail 1
===============================
The Title of original mail 2
---------------
Content mail 2
===============================

At the moment, the encrypted template, CAN have meaningful information (like the **submission fields dump**, or the **file name + size** submitted), but only the encrypted template.

**Comment by vecna** [comment]
but I see your point, skip notification is not a big deal when a certain flood is detected. just the user has to be noticed that "10k notification for you has been suppressed in the latest two hours".

**Comment by vecna** [comment]
so, to close this issue:

  * define an hard-coded threshold of maximum event per hour (to be put in the next DB at notification table)
  * keep in memory the amount of email per receiver sent (ignoring the DB or what ? can be a stat if is in the DB ?)
  * define text for an email
  * implement in notification the suppression trigger check.

any comment before I start ?

**Comment by evilaliv3** [comment]
ok for me! perfect!

1) can be a configurable variable in admin/advanced settigns but ok for the moment to keep it only hardcoded.
2) let's avoid adding this to the db now
3) allright!
4) in what does this consist?

**Comment by vecna** [comment]
1) ok
2) better
3) Waiting for review 
4) modify mailflush_sched accordingly

**Comment by vecna** [comment]
Done, as you can see, I've not modify at all the database at the moment.
I've implemented a queue that check the last email per hour, using the TempObj, so, are kept effectively the window of the last 60 minutes and the number of email in the last 60 minutes.

If the number overcame "20", the notification get disabled for 4 hours. 

This is the link to compare with devel: https://github.com/globaleaks/GlobaLeaks/compare/devel...issue/798

I've used the current version of the text from the gdocs above.
I'll keep this issue in suspend until we've to merge them all and do the new DB.

**Comment by evilaliv3** [comment]
olè!

**Comment by fpietrosanti** [comment]
Let's make any parameters to be visibile/configurable from the admin interface

**Comment by vecna** [comment]
Still TODO(s) in the subject:

  * put in the notification DB
  * put in admin interface
  * save the anomaly as part of the anomalies tracker

**Comment by vecna** [comment]
Update on the issues:

  * text taken from gdocs: https://docs.google.com/document/d/10zRQ2VeaBzo5w1UWyq7Eka910NxFtq3hgyPqQWs8xBA/edit?pli=1# and stored in DB
  * DB update with settings configurable + threshold template
  * model, data init.

TODO:
  * under UT
  * Missing admin entry client for notification parameters.

**Comment by vecna** [comment]
Done some days ago the first and the second. still TODO the anomaly savings.
