### ISSUE TITLE
Flood Resiliency: Proof of Work Antispam with HashCash

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#799]
In relation to the GlobaLeaks Submission Flood Resiliency Project documented at https://docs.google.com/document/d/1P-uHM5K3Hhe_KD6YvARbRTuqjVOVj0VkI7qPO9aWFQw/edit?usp=sharing this ticket is to implement Proof of Work Antispam with HashCash

**Comment by vecna** [comment]
So IIRC, the algorithm proposal was:

give a random string to be put at the beginning of the POW,
that POW get bruteforced up to reach a certain number of 0s (or another random string)

we can use SHA to do that (any pointer where is used now ?), and in verification process, we have to do only a single sha to validated. this check is performed after the time check.

**Comment by evilaliv3** [comment]
ok for me, clientside it would require webworkers + windows.crypto so not more things that the one required by openpgp/scrypt; if you want tomorrow i can show you whot webworker + webcrypto works so that you can going on testing this thing.

**Comment by fpietrosanti** [comment]
Is this approach time deterministic in terms of time or it may require a possibly very long amount of time?

**Comment by evilaliv3** [comment]
yes, it's statistically deterministic if the sha will result uniformly distributed as it is designed for.

anyway we can make a simple demo of this an calculate the meantime on the browsers and validate this with expectation with unit testing.

**Comment by vecna** [comment]
@fpietrosanti do not exist a deterministic proof of work. the algorithm has always the same probability to find the secret. no computation about the number of tries can be done, and if someone is giving an "average time", is just an average of a time that, in theory, can last at infinite. (very quite unlikely, but ...)

SHA is uniformly distributed, but that don't change the hypothesis that, in theory, you can loop up to the infinite.

@hellais FISA request: can you confirm or deny ?

**Comment by vecna** [comment]
The easiest way to do this branch is point to feature/end2end, the library involved are the same. or not ?

**Comment by vecna** [comment]
nah, I'm just fetching hellais/openpgpjs.zip in Gruntfile.js, like the current end2end

**Comment by evilaliv3** [comment]
Claudio can you please take care of working first on the things you were
doing and that I've asked you to patch ?
Please do one thing at once.

Anyway if you want to start think to this (while developing only on the
things you still have to close) to go on with this please evaluate and
document here  if there is some good hash cash library / proof of work
library published of the shelf and maintained by a good community. As last
resort only evaluate or custom thing.

A lot of time passed since the discussion (one year) so maybe there is
something already developed out there

**Comment by vecna** [comment]
you ask me for three stuff: https://github.com/globaleaks/GlobaLeaks/tree/issue/1400 done, https://github.com/globaleaks/GlobaLeaks/tree/unittest/1156 done and on the #1406 I commented is a major change.

**Comment by evilaliv3** [comment]
Ah perfect! I was thinking them they would take time. I find all on the
pull request? Thanks claudio

**Comment by vecna** [comment]
PR here https://github.com/globaleaks/GlobaLeaks/pull/1429

**Comment by evilaliv3** [comment]
reviewed and integrated in devel (https://github.com/globaleaks/GlobaLeaks/commit/3f5549a44bebcf10504f0070ad33ed76eeac70c4)

now the proof of work is integrated using web workers:

- web worker definition: https://github.com/globaleaks/GlobaLeaks/blob/devel/client/app/scripts/crypto/proof-of-work.worker.js
- usage inside submission.js: https://github.com/globaleaks/GlobaLeaks/blob/devel/client/app/scripts/controllers/submission.js#L179

@vecna: check it out! :)

**Comment by evilaliv3** [comment]
implemented by @vecna and reviewed by me in https://github.com/globaleaks/GlobaLeaks/commit/b09f792a3f1396466b3d68edb63a0dadf40d4f58.

The javascript proof of work routines are implemented making use of web workers defined here: https://github.com/globaleaks/GlobaLeaks/commit/e34c0ae69325db9894b10bf5fd05f11cb0d7dae1
