### ISSUE TITLE
Publish GlobaLeaks Releases on FreeCode (former freshmeat)

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#834]
This ticket is to Publish GlobaLeaks Releases on FreeCode (former freshmeat) so that all of the opensource community following freecode could know about GlobaLeaks releases.

This ticket imply automation of releases on FreeCode trough the FreeCode API:
http://help.freecode.com/kb/api-7/data-api-introduction

**Comment by NSkelsey** [comment]
According to the FreeCode site, it is no longer being updated. Hat off to the creator

http://help.freecode.com/about
