### ISSUE TITLE
Enable a receiver to be always selected among a group of unselect by default ones

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#835]
This ticket is to enable one or more than one receiver to be forcefully selected among a group of unselect by default one.

The use case is enable on a specific context, to have a group of "staff journalists" that always receive submission from the whistleblowers, and the remaining journalists that are by default de-selected.

From an adopter:
"What I really want to avoid is that somebody leaks to a journalist, but that journalist doesn't take any action. Somehow we need to combine the personal appeal of targeting a specific journalist, with the reliability of having somebody to make sure all leaks are responded to.

So what I want is a default context where:
 * staff receiver is selected by default, cannot be unselected
 * all other receivers are visible, not selected by default, but one/many can be selected"

The admin must be able, while configuring a receiver on a context, to specify if the receiver being added have this specific property of being always selected.

**Comment by evilaliv3** [comment]
this has been implemented by me and will be delivered in 2.60.47

**Comment by evilaliv3** [comment]
Related to: https://github.com/globaleaks/globaleaks-whistleblowing-software/issues/723
