### ISSUE TITLE
Improve Quiz Disclaimer UX to be one-page

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#836]
It has been noticed by one adopter (wildleaks) that the usability of the Quiz/Disclaimer that's shown while clicking "Blow the Whistle" in a Tor2web scenario, can be improved.

Currently the Whistleblower have a set of "pages" where he must click "next" in order to goes to the next-step. 
If the answer provided is wrong, he must click "back" in order to try it again.

The current proposal is to make this feature, from UX perspective, a single page structured as follow:
[Explaination](ex-first-page)
[Quiz](ex-second-page)
[submit button]

If the answer provided is "wrong" the error message must be reported in this page, without the need to go back and forward.
If the answer provided is wrong, the whistleblower must be able to immediately select a new choice and click "submit" again.
##

**Comment by evilaliv3** [comment]
Closing the ticket recognizing what implemented as valuable and good compromise in security and usability.

Already the current implementation ends most of the time in being disabled and having a easy widget helps supporting users to keep it enabled.
