### ISSUE TITLE
Switch to new python-gnupg module

### ISSUE THREAD

**Issue by filternetz** [globaleaks/GlobaLeaks#838]
The package gnupg fixes numerous security vulnerabilities found in the previous standard module, python-gnupg. 

Probably there will be a few changes necessary to the code of GLBackend.

For example the patched module from @isislovecruft[1] could be used as a replacement. 

[1] https://github.com/isislovecruft/python-gnupg

**Comment by origliante** [comment]
@fpietrosanti outdated

**Comment by fpietrosanti** [comment]
@origliante We are using last one, is not outdated, but a ticket to be closed.
