### ISSUE TITLE
Move scrypt library from py-scrypt to Cryptography

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#863]
In order to simplify our dependency chain we could remove py-script switching to Cryptography for scrypt implementation.

This ticket is about integrating scrypt using the upcoming "cryptography" implementation of scrypt .
Reference: https://github.com/pyca/cryptography/pull/777
##

**Comment by evilaliv3** [comment]
Scrypt is finally included in cryptography: https://github.com/pyca/cryptography/blob/1.6/src/cryptography/hazmat/primitives/kdf/scrypt.py

The first version that includes it is the 1.6.0 released in November 2016.

These version is not included in Xenial/Stretch so we could not valuate the replacement before next releases.

**Comment by evilaliv3** [comment]
Closing as finally landed in the software time ago.
