### ISSUE TITLE
Error in GPG interface object .... ascii codec can't encode character u&#39;&#92;&#92;&#92;&#92;xed&#39; in position 402: ordinal not in range(128))! (notification+encryption)

### ISSUE THREAD

**Issue by ghost** [globaleaks/GlobaLeaks#866]
Error in GPG interface object .... ascii codec can't encode character u&#39;&#92;&#92;&#92;&#92;xed&#39; in position 402: ordinal not in range(128))! (notification+encryption)

it seems that email templates handling code cannot handle non ascii chars.

the error has triggered on a demo of @infosquatter

evilaliv3: @vecna i'm going to investigate this, implement unittests retest and probably push a patch by tomorrow night.

**Comment by evilaliv3** [comment]
this ticket is old and the error is not happening since time so probably it has been fixed.

**Comment by fpietrosanti** [comment]
This ticket has not been fixed as far as i remember and prevent the use of globaleaks in an international context with non ascii charset of variabile.

Please re-open it with followup to test it again as documented in this ticket with reproducibiliy steps by two adopters

**Comment by vecna** [comment]
is quite odd anyway, in the UT we are using unicode characters all around in order to spot them. I'm testing it now.

**Comment by vecna** [comment]
I tested, having sender name with unicode char do not trigger an error, but just deliver the notification properly.

**Comment by fpietrosanti** [comment]
Re-happed by Sergiy on Ukrainan submission, when notifying encrypted emails:
2015-01-25 14:12:57-0500 [-] &quot;[!] Error in GPG interface object (for ___________: &#39;ascii&#39; codec can&#39;t encode characters in position 0-7: ordinal not in range(128))! (notification+encryption)&quot;

**Comment by fpietrosanti** [comment]
Maybe python-gnupg with 0.3.7 fix this issue: 
"Changed in version 0.3.7: The default encoding was changed to latin-1. In earlier versions, it was either locale.getpreferredencoding() or, failing that, sys.stdin.encoding, and failing that, utf-8."

**Comment by evilaliv3** [comment]
this issue can be probably related to https://github.com/globaleaks/GlobaLeaks/issues/948

0.3.7 seems to not solve the issue that lies in having the gpg.encoding != 'UTF-8'
in fact from the test done with sergiy in all conditions in whitch gpg.encoding != 'UTF-8' (e.g. latin-1 or ascii) the encoder fails in managing ukrainian chars and this is reasonable. globaleaks make use of UTF-8 so utf-8 encoding should be always enforced by the application.

**Comment by evilaliv3** [comment]
with previous commit i've enforced g.g.encoding == 'UTF-8'.
this fixed the issue for sergiy.

in addition i've relaxed the python-gnupg requirement from == 0.3.6 to >= 0.3.6 so that on systems where we still use pip (all ubuntus, debian wheezy) we start using python-gnupg 0.3.7.

**Comment by infosquatter** [comment]
Something similar just happened again. I'm having issues with email notifications in this node. Error log is:

UnicodeEncodeError Unicode encoding error.

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", =
line 1099, in _inlineCallbacks
    result =3D g.send(result)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/mailflush_sched.py=
", line 422, in operation
    receivers_synthesis)

  File "/usr/lib/python2.7/dist-packages/globaleaks/jobs/mailflush_sched.py=
", line 350, in ping_mail_flush
    notification_settings['ping_mail_template'], fakeevent)

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/templating.py", l=
ine 72, in format_template
    variable_content =3D getattr(keyword_converter, kw[1:-1])()

  File "/usr/lib/python2.7/dist-packages/globaleaks/utils/templating.py", l=
ine 316, in ReceiverName
    return str(self.name)

UnicodeEncodeError: 'ascii' codec can't encode character u'\xed' in positio=
n 1: ordinal not in range(128)
