### ISSUE TITLE
GlobaLeaks should detect that disk (and also ramdisk) is full and take action

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#872]
Currently if the disk became Full globaleaks will start triggering unhandled exception.

This ticket is to make GlobaLeaks to detect that disk (and also ramdisk) is full and take action such as:
- notify the administrator
- stop accepting new submissions
- notify the whistleblowers and/or receivers that the node is not accepting submission because the disk is full

The configuration to take action on disk full should be done on:
- Percentage of /var/globaleaks
- Percentage of /dev/shm/

Related to #297

**Comment by vecna** [comment]
Ramdisk check integrated here: https://github.com/globaleaks/GlobaLeaks/commit/7f20dd40b6d38b7262541e57a65131302aa4b90c not yet decided the 'action' to be taken.

**Comment by vecna** [comment]
Closing this issue, discussion and updated done in #297

**Comment by evilaliv3** [comment]
an issue has to be considered closed when integrated in devel by the review of someone.

let's try to re-enter all in this path. i will take care of this.

**Comment by vecna** [comment]
Yes ok for the policy but is duplicated in the other issue mentioned :P

**Comment by evilaliv3** [comment]
closing this ticket as the fix to this are aggregated in ticket 297
