### ISSUE TITLE
Submission Suggest a new Receiver to be added

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#88]
It should be possible for a whistleblower to add a new receiver to the list of available receivers. 
This request would be received by the node administrator.
This is a new feature in itself and we should think a bit about this.

https://github.com/globaleaks/GLClient/issues/40
##

**Comment by vodkina** [comment]
What about this issue?!? Any progress?

**Comment by evilaliv3** [comment]
Closing the ticket as outdated.

It is not in line with current goals and there has been no interestet in the past years.
