### ISSUE TITLE
Notify Receiver based on selection of specific submission field list

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#897]
It has been requested by an adopter to be able to have different receivers depending on the selection done by the Whistleblower on the submission field.

The use case example is as follow:
- In a corporate whistleblowing system there is a context related to Fraud
- The internal audit department take case of all of the submission related to Fraud
- One of the submission fields is a select-box with the "Amount of Money" related to the fraud as follow:
  - $0-$1.000
  - $1.001-$10.000
  - $10.001- $100.000
  - above $100.000

The CFO want to receive all the submission in the context "Fraud" whose amount of money is "higher than $100.000", while all the other submission will only goes to the "Internal audit" analysts.

This ticket is to implement this feature to enable to have receivers receiving submission based on the selection on specific submission fields.

**Comment by evilaliv3** [comment]
Closing this ticket as the feature was implemented long time ago as an extention of dropdown questions.
