### ISSUE TITLE
it should be possible to link to a specific context submission page

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#899]
it should be possible to link to a specific context submission page

one of the need of a a possible adopter is to have an umbrella site dealing with different campaign.

it should be useful to implement a feature in order to link directly to a specific context of submission.

**Comment by evilaliv3** [comment]
permalink have already been implemented in https://github.com/globaleaks/GlobaLeaks/issues/899 and released in 2.60.42

that ticket is now tracking the missing documentation for the feature so this one can now be closed.

**Comment by fpietrosanti** [comment]
If documentation is missing, the ticket shall not be closed

**Comment by evilaliv3** [comment]
read before comment :) there are two tickets tracking this so #899 has been
left open and this can be closed as duplicated.
