### ISSUE TITLE
Make an User Manual for GlobaLeaks software

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#901]
We are completely missing any manual and/or feature overview of the globaleaks platform from the receiver point of view.

This ticket is to improve the documentation by making a proper "User Manual" of GlobaLeaks focused on Receiver's user functionalities,  including all of the graphical screenshots.

**Comment by evilaliv3** [comment]
A minimal recipient documentation was provided here along the general documetation:
- https://docs.globaleaks.org/en/main/user/Recipient.html
- https://docs.globaleaks.org/en/main/user/Common.html
