### ISSUE TITLE
it should be possible to configure optional submission workflows (conditional field activation) based on field answers

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#910]
Add support for optional workflows based on field answers.

This feature is particularly needed in order to implement the TI-it platform, by the way it's particularly interesting in general.

Internal note: "For over 18 -> Activate "Phone Number Field" in Stage-II"

**Comment by evilaliv3** [comment]
support had been added, not what is missing is simply the clientside implementation of the feature that would require not so much work.

let's postpone the ticket to next milestone as the time is ended for this :)

**Comment by evilaliv3** [comment]
backend support for the feature is ready in devel branch and we still need client implementation.

let's move this ticket to next milestone.

**Comment by fpietrosanti** [comment]
Example: field activated by options (discussed at crimery in SF for OpenWhistleblowing)

**Comment by evilaliv3** [comment]
Here follows the screenshots of the current implementation:

![screenshot from 2016-02-12 13 03 45](https://cloud.githubusercontent.com/assets/217034/13006513/b499be74-d189-11e5-8ff5-0f5cc05ce609.png)
![screenshot from 2016-02-12 13 04 09](https://cloud.githubusercontent.com/assets/217034/13006522/bbe180ea-d189-11e5-80c8-be22af29f0ad.png)
