### ISSUE TITLE
Add support for minimal links markdown

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#914]
It should be interesting to add a minimal links markdown in the following format:
    [optional_title][url]

this can be probably achieved in the short term by implementing something as:
https://gist.github.com/jakemmarsh/6008983

it would require only clientside actions.
##

**Comment by fpietrosanti** [comment]
That's also a requirement for Ozivieni

**Comment by evilaliv3** [comment]
Markdown is now implement in almost all the interfaces that benefit of it.
