### ISSUE TITLE
Allow Globaleaks to work within LXC

### ISSUE THREAD

**Issue by DrWhax** [globaleaks/GlobaLeaks#919]
Hey Globaleaks team,

I'm trying out to get Globaleaks to work within an LXC (ubuntu 12.04) environment, which seems to more or less work. The only problem is AppArmor, since you can't really control AppArmor within LXC.

```
# /etc/init.d/globaleaks start
 * Starting GlobaLeaks daemon globaleaks                                                                                                      
 * Enabling GlobaLeaks Network Sandboxing...                                                                                           [ OK ] 
Traceback (most recent call last):
  File "/usr/sbin/aa-status", line 194, in <module>
    commands[cmd]()
  File "/usr/sbin/aa-status", line 17, in cmd_enabled
    if get_profiles() == {}:
  File "/usr/sbin/aa-status", line 92, in get_profiles
    for p in open(apparmor_profiles).readlines():
IOError: [Errno 13] Permission denied: '/sys/kernel/security/apparmor/profiles'
```

It starts Globaleaks and it seems to be fine, is there anything important that needs to be opened or written to the profiles?
##

**Comment by evilaliv3** [comment]
Closing the ticket as outdated.

**Comment by evilaliv3** [comment]
My friend @fpietrosanti prefer to leave the ticket open!

**Comment by evilaliv3** [comment]
Deprecated since the implementation of https://github.com/globaleaks/GlobaLeaks/issues/1177

Platforms with no apparmo/ iptables will be able to start correctly with just a WARNING for the missing support.
