### ISSUE TITLE
Migrate from cookies to localstorage for XSRF token storage

### ISSUE THREAD

**Issue by hellais** [globaleaks/GlobaLeaks#923]
Currently GLClient uses cookies to store the XSRF token, that is then though sent via HTTP headers. I would propose we switch over to using localstorage instead as this is a less frightening option for the user.

**Comment by evilaliv3** [comment]
as cookies are going to not be used anymore, the security concern expressed by @fpietrosanti is valid.

since no cookies nor local storage will be used we will be forensic proof.
