### ISSUE TITLE
Implement Chunked File Uploading support on GLBackend

### ISSUE THREAD

**Issue by evilaliv3** [globaleaks/GlobaLeaks#929]
Add support for chunked file uploads inside of cyclone, glbackend and test integration with jquery-file-uploader.

**Comment by fpietrosanti** [comment]
Any news from this point of view?

**Comment by dpnova** [comment]
I've left comments on the related ticket over on the cyclone repo.

**Comment by evilaliv3** [comment]
thanks @dpnova; we didnt notice it. @hellais can you do a followup on the upstream pull request?

**Comment by hellais** [comment]
yeah thanks @dpnova. I had seen the comments, but didn't have time to reply.

**Comment by evilaliv3** [comment]
this ticket is now outdated for use and can be closed as we switched to the Flow.js library and we implemented its chunked transfer protocol directly in an application handler so that we do not need anymore cyclone edits for this.
