### ISSUE TITLE
Enable Receiver to "Export" a single Tip in a Safe way

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#931]
This ticket is to enable a Receiver to "Export" a single TIp, including all it's elements:
- Fields
- Comments
- Messages
- Files

The Receiver need to have "Export" button available:
- On the Tip List
- On the Tip itself

The receiver shall be able to export a single tip as a Zip file containing:
- a structured HTML or PDF document with all the Fields, Comments, Messages, File Lists (including timestamp of all interactions)
- Files that has been uploaded

The Zip file shall be available also as an encrypted version (ZIP with AES).

The Receiver must be able to setup it's Export Password (to be used by the ZIP) in his Preferences.

The Preferences of the Receiver shall provide the following additional options:
- Generale Export Password (this will generate a password of 24 alpha-numeric chars separated by "-" like okdo-38da-48dx-1ksm-XXX)
- Print Export Password (this will trigger download for printing of a A4 sized pdf, with the password and "basic instructions" on how to use it).

With the presence of Client Side encryption, the export password shall be saved encrypted.

**Comment by evilaliv3** [comment]
As the main export has been implemented i'm about to close the ticket under the February milestone to keep track of when we did it.

I'm then goind to open two specific tickets for what is missing:
- add the export button the tip list: to be done in the march milestone as easy ticket;
- add possibility to export the tip as an encrypted zip with AES.
