### ISSUE TITLE
Context-selection select-box is too wide

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#932]
The Context-selection select-box is too wide and not adjusted with the length of the name of the context.

See below:
![screen shot 2014-08-28 at 11 22 15 am](https://cloud.githubusercontent.com/assets/770363/4077047/4ce17de4-2ebf-11e4-8861-11ad38aa4579.png)

**Comment by vecna** [comment]
any way to reproduce ?

**Comment by evilaliv3** [comment]
i don't remember if i've already fixed this.
by the way is something that ways happen simply by opening the web application. cause is due to the use of a bootstrap class.

i will take care of the issue that i'm confident of the various templates that have this issue.

thanks @vecna

**Comment by evilaliv3** [comment]
this has been fixed by me since a few.
