### ISSUE TITLE
/token API specification to handle properly all the OTF-D8 resiliency strategies.

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#934]
Three kind of in-memory-token need to exists in GlobaLeaks design:

  * when you want upload file from an anonymous perspective 
  * when you want finalize a submission (will be only an atomic operation, no update anymore) 
  * when you want post a comment and or upload a new file, you have to get a token (also if you're an authenticated user)

The submission refactor will address the first two points. This is a required modification for all the DoS resiliency patches.

**Comment by vecna** [comment]
I confirm, at the moment only the Token_ID in the URL, but probably is overdoing, and I can put it too in the request.

the request contain the answers (not yet covert that part)

**Comment by vecna** [comment]
The request contain the answer, the REST URI contain Token (and context). I've to update the specification. but before I want complete the UT.

**Comment by evilaliv3** [comment]
integrated but still to be finalized with some minor change in the API.

e.g. some variables of the token API declare to export seconds (_secs suffix) but then they export a date; it should be ok to export seconds as a number that the client will consider relative to the creation date exported in the token in UTC; this will reduce also the overhead of the backend that wont calculate two dates (start, stop).

**Comment by vecna** [comment]
@evilaliv3  To close this issue, what is required ? a review of the naming used in the API ?

**Comment by evilaliv3** [comment]
yep that. i've written some above if you want proceed on this. 
in addition probably the token concept is still to be described on the Applicatioin Security document?

**Comment by vecna** [comment]
RAML has been anyway lost during the branch/repo changes

**Comment by evilaliv3** [comment]
naaaa: https://github.com/globaleaks/GLBackend-outdated/blob/D8-OTF-fix/docs/Token.raml

**Comment by fpietrosanti** [comment]
I suggest to completely remove any API documentation:
a) because are not updated
b) because will never be used by anyone (due to the added complexity of GLClient)

The specification for anti-dos is better to be an "anti dos" specification, rather than an "API specification".

Whatever integration for inbound submission will be done in future, is likely to be done with a custom GCLient and not by using GlobaLeaks API.

**Comment by vecna** [comment]
I share the same thoughts of @fpietrosanti, and the specification of "anti DoS" has to be done as #1266.

I've updated in the commit above the naming as suggested, closing this issue now. The branch will be merged with the countdown (tomorrow)

          return {
              'token_id': self.token_id,
              'creation_date': datetime_to_ISO8601(self.creation_date),       
              'start_validity_secs': self.start_validity_secs,
              'end_validity_secs': self.end_validity_secs,
              'remaining_allowed_attempts': self.remaining_allowed_attempts,
              'type': self.kind,
              'graph_captcha': self.graph_captcha['question'] if self.graph_captcha else False,
              'human_captcha': self.human_captcha['question'] if self.human_captcha else False,
              'proof_of_work': self.proof_of_work['question'] if self.proof_of_work else False,
          }

I'll keep the branch active, so I'll not make a PR now, and I'll reference the issue #1269

**Comment by vecna** [comment]
This will be merged in #798 (that contain #796) and then PR
