### ISSUE TITLE
Encrypt file uploads with the keys of the receivers obtained from glbackend

### ISSUE THREAD

**Issue by hellais** [globaleaks/GlobaLeaks#935]
This involves fetching the public keys of the receivers from the backend and using such keys inside of GLClient to encrypt the file upload.

File encryption shall therefore not be done anymore inside of the backend.
##

**Comment by evilaliv3** [comment]
This is finally near the completion. moving this to the April milestone and me or @origliantre will take care of integrating the work performed by @hellais in the end2end branch.

**Comment by hellais** [comment]
Let me know if you run into any difficulties and/or there are aspects of this you would like to discuss.

**Comment by hellais** [comment]
From talking on god aweful Skype with @evilaliv3 it appears that they have worked on integrating flow.js, but have not made progress on integrating flow.js + openpgp.js.

I shall hence look at this matter.

**Comment by evilaliv3** [comment]
this has been implemented completely but the code is still in end2end branch. let's move this ticket to june milestone with the aim of integrating end2end branch.

**Comment by evilaliv3** [comment]
Closing as outdated.
