### ISSUE TITLE
Events collection, measurement and anomaly detection.

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#937]
In order to develop all the DoS resiliency trigger, is important having an anomaly detection and resource measurement.

What is needed, is develop a subsystem of event collection from all the operation that are:
  * CPU intensive
  * I/O intensive 
  * Receiver-effort intensive 

and perform analysis on timed basis. Based on the amount of threshold reached, few or multiple level of "stress" are raised. more stress level are raised, and different counter measure are adopted by the system.

This is an enhancement of the previously developed decorator **anomaly_check** and the GLSetting.anomaly_counter.

This is a requirement to log/notify to the Admin that the system is under attack/stress.

**Comment by evilaliv3** [comment]
to be still reviewd and completed finalizing the documentation in the new repo.

@vecna we will tackle the discussion after the afrileaks priorities, no need to think about this right now.

**Comment by vecna** [comment]
At the moment, I'm looking over our demo node the status:

  * there is a bug in the hour 12
  * the automatic scaling of the heatmap is causing two blog of ">= 0"
  * the supporter text has can be improved 
  * is still missing the check of the past weeks
  * the anomaly list do not provide serious information, beside the event that has trigger the anomaly

but overall is a quite good thing, please take a look demo and feel free to DoS :P

**Comment by evilaliv3** [comment]
@vecna can you clarify me how to solve the first two issues? in few days i will push out a new package an i would like to get them fixed

**Comment by vecna** [comment]
there are more than one bug :\ I just check now, expecting to find some activity report, but they were missing. tomorrow we'll check.

**Comment by vecna** [comment]
the fact is: something has gone bad during the merge, or I've not kept something in mind, but in demo.globaleaks.org apparently the REST api is not returning meaningful data.

**Comment by evilaliv3** [comment]
@vecna: i think that this ticket can be considered closed and if needed lets open new small tickets related to the missing things and then close this.
