### ISSUE TITLE
Client support and API specification for /token

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#938]
The various path of DoS resiliency require a dedicated API, message format and javascript controller to be implemented.

When the client request for a token (needed in #189 #795 #796 #799 #800) the answer can be:

  * deny
  * ok (take token)
  * "not ok, but" = (please do: A or B or C or D or mixed combination)

The GLClient need a dedicated window that appear (fixed div ? modal ? to be discussed) with the appropriate answer.

If the answer has been "not ok, but" the request appear, the solution is computed by client and sent back. 

Those condition need as requirement a GLClient implementation and a (little) protocol specification. This operation is blocking to complete the milestone, not blocking to implement GLBackend handler and unitTest.

**Comment by vecna** [comment]
I've completed in this branch: https://github.com/globaleaks/GlobaLeaks/commits/token-integration:

  * submission based on Token, now instead the POST (create internaltip marked as 'submission') the POST create a Token (and, based on the stress level, add human Captcha)
  * file update: they are not anymore saved on the DB from incompleted submission, they are associated to the token, https://github.com/globaleaks/GlobaLeaks/commit/7fdb047f937d7d22bc1e1fc29560b86190ff036e and when the submission is finalized, the InternalFile are created.
  * the submission API take as REST argument the context_id, because every submission is a resource of a specific context. In the future we can remove 'context_id' field from wbSubmissionRequest struct

**Comment by evilaliv3** [comment]
Great! Tomorrow I will work on reviewing this also. It's ready for
integration from your side?
Il 15/Feb/2015 19:32 "Claudio A." <notifications@github.com> ha scritto:

**Comment by vecna** [comment]
yes, but the unit test are completely screw up, I'm fixing them as part of the job of today

**Comment by vecna** [comment]
I've committed the code in token-integration, I've put comments to explain the latest commit:
https://github.com/globaleaks/GlobaLeaks/commit/5cc0f198315c59a2cbe847608b5932da21908655
but in the UT, I still have problem with the DelayCall

**Comment by evilaliv3** [comment]
if it is ok today i will digg into this code review in order to test and integrate it.

i will take care of completing the UT as part of my testing.

**Comment by evilaliv3** [comment]
integrated but still to be finalized with some UI and actions. to be moved to April milestone.

**Comment by vecna** [comment]
What I can do about this ?

**Comment by hellais** [comment]
What WAS, done about this?

**Comment by vecna** [comment]
don't worry, just the stuff has been integrated, and now many other issues depends on this code, so we can safely assume that everything is gone well.
