### ISSUE TITLE
Adjust Threat Model to explicitly mention limits of GlobaLeaks

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#944]
This ticket is to adjust Thread Model to explicitly mention limits of GlobaLeaks following the example of https://protonmail.ch/blog/protonmail-threat-model/ that say:

"NOT RECOMMENDED:
Edward Snowden – If you are Edward Snowden, or the next Edward Snowden, and have a life and death situation that requires privacy, we would not recommend using ProtonMail. For extremely sensitive situations, it is simply not a good idea to use email as a medium for communications."

I feel we shall formulate a similar statement and write in our Threat Model and README.md document on Github, as that's what we're already saying during conferences and while discussing with adopters.

Tips from Rufo, tnx!

**Comment by evilaliv3** [comment]
Closing this ticker as current [Threat Model](https://docs.globaleaks.org/en/main/security/ThreatModel.html) document contains references to known limitations.
