### ISSUE TITLE
Some PGP key cannot be uploaded with error: "The PGP key cannot be imported"

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#948]
Some PGP key cannot be uploaded with error: "The PGP key cannot be imported" .

The error is:
"/admin/receiver/3a781002-e9da-4528-9a85-4a2d947547cd
The PGP key proposed can't be imported "

That's a critical stopping issue for an adopter whose public is at:
http://pgp.mit.edu/pks/lookup?op=get&search=0xFAFD9A33DD05EE8A

The problem can be perfectly replicated

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: SKS 1.1.4
Comment: Hostname: pgp.mit.edu

mQENBFQRml0BB/9f0RasH3Tqlb3ANVfRfBKjMnFk+W0SPkzxpGTTTU5MUKk3RQ12gI8Isrjx
9WPEpl71zqEqFNYZ0qwP5Yr1hvKeA1YPTo+Sn0JQ+HFkTrelQtpJOsDCge001orLaq6G+vXr
JlDLVNiFzuaXFA3vK/l2o9wRqHdhJyUnyOvfdnkM8NnjpPxfm1n8U4hbZQrpoZtPIMTcdBf9
4CDL3DKWDPBRMR+ZIY+5j7KTdiS2sJyhXhrvMTR1ZApoggZIh6sugK4YIndP25uZF6osOMZC
PsyYcyaGuuLB9B6U8NtMRdFhThI6u8w/E73TIuL572z3JxgI5P+lPUsSoB0G0MTdV5tpABEB
AAG0Kk1laG1ldCBBdGFrYW4gRm/Dp2EgPGF0YWthbmZvY2FAZ21haWwuY29tPokBMgQQAQgA
JgUCVBGaZAYLCQgHAwIJEPr9mjPdBe6KBBUIAgoDFgIBAhsDAh4BAAAQPwf/UbmHYqqWLm/U
AvuE459tqIUIGJGJCkXtXeiwAOTCtcFTtWs/0fkAw4G3Jq9bgJrUt4FbDySlbvpdkw71iQkg
N4d/Va75r1s1zKGgAvak7pdM4DfNItxPtdeHVGQ9sEETFlCTL/ti3mZ6DMhiz9cUhoa8T5WP
hGxRvRJWMQvkN7FFMl6voByaViJnZEG+o1j/QE05sxD4Vu9CKP6GMKywWEpse/BPvIoaqNVa
+ivvVD7moaU9/jvVsJeUWQr9u8JH7EOHl0f2W8hk/+5g7CYySW3Ljy/u66y4oDh6ycguk5jB
X9PoAWk+1nqBcbuSnsdTGqu0ANiCUIwteW7kqsCQfLkBDQRUEZplAQgAldAgRNbTZrndxOnG
AZJGuQwp4FvuuupqGHyJdsNcvwwff2475QnVmJWVUVJowGjfVqDkGnrbPuQt/I69cIJBL/x+
e9/yAweIEljTsdCvVO1Fei2jEPSYjc5Ra+Ze1lS6ySyNMEiesCthZBYlcLhXO9fOrD5z+t4b
+Z3rZb1wAOPI6Kj4L+xF94X7gx1fksY44yYr/tNnSMk1iB8Z8R1NyQ1C/SgqFd1SR/Sdk1M0
e8TxPUUe6v0dT2gBiUb1RRTdmh3PHHVXrlYzrY+jpHQkLmj33jL8BmTJoa65EOn6ikniEATi
lJz4ftiNinObMeCt6VI7cbmElnB7f+2w+cQwTQARAQABiQEfBBgBCAATBQJUEZpzCRD6/Zoz
3QXuigIbDAAAivsH/iYz5mhlLAY10nX7DL7xiR0h/GywiRkWiQjkYzsNdIurYR0qPEhHYvNP
JzJ2oukqu1d7fCM0wFyTkLFEmZyn+4TMOhlSKsDUx578jpUaT9B2GkOZSDzeih0Yx57oPp6f
nHp4ZUqBK/BTRazlV2nFaOy8QoKFoEDtLMD5nfbKaydfJ811+8Dgic8joqZ+jIRdH4q0ADSH
b44/5FqaT+hjKwIaobShFduk/nAuaau2j4olT8bj40U3hkJRkMtQNHvjz6s8KarOQSPzqKaA
1T0RBl1AGhTrlwi+Fni8LXvSsn5iAczyt0FJz0aDfm1jLvdM3jJpNkaHQqV2mBI3e+nu3lw=
=La0b
-----END PGP PUBLIC KEY BLOCK-----

**Comment by NSkelsey** [comment]
This issue reemerged in GlobaLeaks `v2.67.4` and was reported by an adopter. 

I am reopening the ticket until our unit test coverage demonstrates the issue is fixed, the debian postinstall script adds the needed locale or another non-manual fix is found.

**Comment by NCommander** [comment]
This issue should be properly resolved when running under Py3 which changes how locales works and is utf-8 safe out of the box (no unicode type). It might still reoccur under Py2 but new installs should be on bionic and Py3.
