### ISSUE TITLE
When Tor Browser Bundle is on the "Activation Wizard" it consume CPUs at 100%.

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#952]
When Tor Browser Bundle is on the "Activation Wizard" it consume CPUs at 100%.

Maybe there is some bugs in the wizard code that make this happen.

Using latests TBB and latest GlobaLeaks at 19.09.2014.

**Comment by evilaliv3** [comment]
this probably has been fixed and was caused by the login error that caused a while(1) in the authentication. by the release of tonight @fpietrosanti  can you please do a retesting by your own?

**Comment by fpietrosanti** [comment]
tested, fixed
