### ISSUE TITLE
keep option to use pre-configured Tor hidden services

### ISSUE THREAD

**Issue by adrelanos** [globaleaks/GlobaLeaks#962]
It is my understanding, that at the moment, users of the globaleaks backend have to manually set up their Tor hidden service as per:
https://github.com/globaleaks/GlobaLeaks/wiki/Installation-guide#step-3---create-your-hidden-service
And this is a very good thing from my perspective as a maintainer of [Whonix](https://www.whonix.org).

You might plan to automate this some day, i.e. using Tor's ControlPort or so. It might be useful in some setups to improve usability for users. (#70)? But this is not what I am requesting here.

The feature request here is to always leave an option for users who want to manually set up their Tor hidden service. In other words, please keep globaleaks being able to use an already existing, pre-configured Tor hidden service.

This is because as per [Whonix Hidden Services Instructions](https://www.whonix.org/wiki/Hidden_Services) and for similar for other implementations of Tor configurations that use network isolation, where Tor runs on a different machine then client applications... The hidden service would run on the gateway. And the GlobaLeaks software would run in the workstation. Implementing this works if you keep globaleaks being able to use an already existing, pre-configured Tor hidden service.

So if you like this idea, please keep this in mind and/or add it to your design documentation.

(This ticket is similar to https://github.com/micahflee/onionshare/issues/27 and https://github.com/ricochet-im/ricochet/issues/30.)
##

**Comment by adrelanos** [comment]
A lot things have changed since. I take this feature request back. Please consider it superseded by https://github.com/globaleaks/GlobaLeaks/issues/1909.

**Comment by evilaliv3** [comment]
Closing as superseded.
