### ISSUE TITLE
It's not possible to delete an item from a listbox when configuring the fields

### ISSUE THREAD

**Issue by fpietrosanti** [globaleaks/GlobaLeaks#977]
It's not possible to delete an item from a listbox as reported by TI-it

![problema1](https://cloud.githubusercontent.com/assets/770363/4544562/5c35e6d8-4e34-11e4-9b64-7f0ed67efb32.png)

![esplicitazione del problema1](https://cloud.githubusercontent.com/assets/770363/4544561/57b34e70-4e34-11e4-997a-bc1f30922555.png)

**Comment by evilaliv3** [comment]
this has been implemented in fields refactoring of december and integrated since release 2.60.42
