### ISSUE TITLE
Integration strategy for Flood detection and prevention techniques

### ISSUE THREAD

**Issue by vecna** [globaleaks/GlobaLeaks#993]
There are [many issues](https://github.com/globaleaks/GlobaLeaks/labels/OTF-D8:%20Flood%20Resiliency) and [subdeliverable](https://projects.globaleaks.org/issues/57) associated with D8, and with different kind of impact on UX, settings, database, client.

This is the proposed strategy to permit a painless integration:

### First goal: milestone October 2013

  * anomaly.py contain the class Alarm and the new activity collection class. will be added 
  * handler/statistics.py (implement three API: /admin/(anomalies|stats|activities) ), they represent respectly:
    * anomalies: log of the latest time the system has registered a stress
    * stats: long term usage collection 
    * activities: short term detailed timeline of activity 
  * GLClient: Admin interface only, those three new stuff
  * statistic_sched.py update to collect also the disk availability and to make summary of activities in order to raise the Alarm level
  * the docs/ directory contain two specification files, one about statistics and the other on the token design.

This will complete the issues: #937 #802, they shall be integrated in devel when those section are ready

### Next Milestone, November 2014

The main issue in the all D8 anti flood techniques, is the new submission interface. has been specified in RAML: https://github.com/globaleaks/GLBackend/blob/D8-OTF-Token/docs/Token.raml and some old issues may be addressed right now, for example #489 

  * adding of v2submission.py and v2files.py (the second version API for file upload [supporting description and token] and submission [context based, no update permitted]). here in development: https://github.com/globaleaks/GLBackend/blob/D8-OTF-Token/globaleaks/handlers/v2submission.py 
  * adding of GLClient support to the v2
  * adding of a switch in globaleaks able to enable v2 or not 
  * The submission integration is needed to effectively tune the threshold of: #189 #796 #795 and #800
  * The October 2014 statistics will be already in place, as requirement to effectively assess the alert threshold. 

### Branch usage

I'm implementing everything in [D8-OTF-Token](https://github.com/globaleaks/GLBackend/tree/D8-OTF-Token), probably I'll never gonna to merge that branch, and create new branches before the PR.

This issues will be used to keep track of the partial merging of the branch in devel.

**Comment by evilaliv3** [comment]
all integrated and delivered in 2.60.42
